### ISSUE TITLE
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms

### ISSUE THREAD

**Issue by bradnussbaum** [neo4j/neo4j#10223]
I've been seeing this issue for a while in debug logs and believe I tracked it to limited bandwidth connections loading the neo4j browser. Over a limited bandwidth connection the jetty server is terminating downloads that take too long to complete.

- Neo4j version: 3.3.0-rc1
- Operating system: Ubuntu 16.04

### Steps to reproduce
1. Limit web connection download speed so that app/vendor.js takes at least 60s to download
2. Load the neo4j browser over limited connection
3. Observed failure to download app/vendor.js (usually fails around 57s)

### Potentially Related To
https://github.com/eclipse/jetty.project/issues/517

### Debug Log
2017-10-07 18:22:52.574+0000 WARN  /browser/app-fb224bcf5bb783cc86a9.js java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
        at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:213)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:149)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:386)
        at org.eclipse.jetty.util.IO.copy(IO.java:152)
        at org.eclipse.jetty.util.resource.Resource.writeTo(Resource.java:634)
        at org.eclipse.jetty.servlet.DefaultServlet.sendData(DefaultServlet.java:992)
        at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:534)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at org.neo4j.server.web.StaticContentFilter.doFilter(StaticContentFilter.java:52)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.neo4j.server.rest.dbms.AuthorizationEnabledFilter.doFilter(AuthorizationEnabledFilter.java:86)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
        at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:161)
        at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more

**Comment by zhenlineo** [comment]
Hi @bradnussbaum,

It might be related to a bug in jetty version `9.2.22.v20170606` we used in 3.3 Neo4j.
We upgraded jetty to `9.4.11.v20180605` in 3.4. I run the same test against the latest 3.4 server, it gives me no error. The browser page also is loaded normally.

I do not think we will upgrade jetty versions in 3.3 server. So I would suggest you to upgrade to 3.4 or our latest 3.5 servers where we have this issue fixed.

If you have any further question regarding using browser with the new servers, pls do not hesitate to come back to us.

Cheers,
Zhen
