### ISSUE TITLE
Java driver cannot pass nodes as parameters

### ISSUE THREAD

**Issue by szarnyasg** [neo4j/neo4j#10239]
I would like to use `WITH` to pass nodes (returned by previous queries) to the next query. It works fine in the embedded version, but does not work with the Java driver.

We had a [discussion](https://neo4j-users.slack.com/archives/C08J11DC6/p1507513663000043) on this in the Neo4j User slack with @jexp in #help-cypher.

- Neo4j version: 3.2.1
- Operating system: Ubuntu 16.04
- API/Driver: Cypher/Java driver (1.1.4)

### Embedded version (working)

It works with the embedded API.

```java
GraphDatabaseService gds = new TestGraphDatabaseFactory().newImpermanentDatabaseBuilder().newGraphDatabase();

Result result1 = gds.execute("CREATE (p:Person) RETURN p");
Map<String, Object> row = result1.next();

Object n = row.get("p");

Map<String,Object> params = ImmutableMap.of("n", n);
Result result2 = gds.execute("WITH $n AS n RETURN n", params);

System.out.println(result2.next());
```

This returns: `{n=Node[0]}`

### Steps to reproduce

However, it does not work with the driver:

```java
Driver driver = GraphDatabase.driver("bolt://localhost:7687", AuthTokens.basic("usr", "pw"));
Session session = driver.session();

StatementResult result1 = session.run("CREATE (p:Person) RETURN p");
Record record = result1.next();

Object n = record.get("p");

Map<String,Object> params = ImmutableMap.of("n", n);
StatementResult result2 = session.run("WITH $n AS n RETURN n", params);

System.out.println(result2.next());
```

### Expected behavior

It should return the node, similarly to the embedded version.

### Actual behavior

It throws an exception when running the second query:

```
Oct 08, 2017 9:15:11 PM org.neo4j.driver.internal.logging.JULogger error
SEVERE: [1307096070] TLS socket could not be closed cleanly
java.nio.channels.ClosedChannelException
    at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:270)
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:461)
    at org.neo4j.driver.internal.security.TLSSocketChannel.channelWrite(TLSSocketChannel.java:190)
    at org.neo4j.driver.internal.security.TLSSocketChannel.close(TLSSocketChannel.java:476)
    at org.neo4j.driver.internal.net.SocketClient.stop(SocketClient.java:207)
    at org.neo4j.driver.internal.net.SocketConnection.close(SocketConnection.java:265)
    at org.neo4j.driver.internal.net.ConcurrencyGuardingConnection.close(ConcurrencyGuardingConnection.java:178)
    at org.neo4j.driver.internal.net.pooling.PooledSocketConnection.dispose(PooledSocketConnection.java:251)
    at org.neo4j.driver.internal.net.pooling.BlockingPooledConnectionQueue.disposeSafely(BlockingPooledConnectionQueue.java:163)
    at org.neo4j.driver.internal.net.pooling.BlockingPooledConnectionQueue.disposeBroken(BlockingPooledConnectionQueue.java:116)
    at org.neo4j.driver.internal.net.pooling.PooledConnectionReleaseConsumer.accept(PooledConnectionReleaseConsumer.java:50)
    at org.neo4j.driver.internal.net.pooling.PooledConnectionReleaseConsumer.accept(PooledConnectionReleaseConsumer.java:29)
    at org.neo4j.driver.internal.net.pooling.PooledSocketConnection.close(PooledSocketConnection.java:200)
    at org.neo4j.driver.internal.NetworkSession.closeCurrentConnection(NetworkSession.java:375)
    at org.neo4j.driver.internal.NetworkSession.closeCurrentConnection(NetworkSession.java:354)
    at org.neo4j.driver.internal.NetworkSession.onResultConsumed(NetworkSession.java:221)
    at org.neo4j.driver.internal.InternalStatementResult.receiveOne(InternalStatementResult.java:339)
    at org.neo4j.driver.internal.InternalStatementResult.tryFetchNext(InternalStatementResult.java:325)
    at org.neo4j.driver.internal.InternalStatementResult.next(InternalStatementResult.java:205)
[...]
org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Failed to receive any data from the connected address localhost:7687. Please ensure a working connection to the database.
    at org.neo4j.driver.internal.security.TLSSocketChannel.channelRead(TLSSocketChannel.java:176)
    at org.neo4j.driver.internal.security.TLSSocketChannel.unwrap(TLSSocketChannel.java:235)
[...]
```

**Comment by technige** [comment]
Nodes, relationships and paths were deliberately excluded from the list of supported parameter types when Bolt was introduced. The developer manual explicitly lists the types that are supported:
https://neo4j.com/docs/developer-manual/current/drivers/cypher-values/#driver-neo4j-type-system

While this works in embedded for historical reasons, the same functionality cannot be unambiguously applied in a client-server setup. Extracting a node from a result takes a copy or projection of that node; no permanent link to the original node is maintained. Were you to pass this back into a query, it is unclear whether the node should be passed by reference or by value.

This in no way restricts the functionality available to you however. Should you want to pass by reference, you will need to pass in the node ID. To pass by value, extract the properties and pass those as a map instead.

**Comment by szarnyasg** [comment]
Thank you for the insightful information. I think that the driver could throw more meaningful exceptions, i.e. it should check the parameters before even starting to communicate with the server. Do you think this would be a valuable addition? If so, I'd be happy to contribute this to the Java driver.

**Comment by technige** [comment]
Yes @szarnyasg I think the error could be more usefully presented here. We're working on adding new data types for Neo4j 3.4, some of which will be acceptable as parameters, so we'll address this at the same time.
