### ISSUE TITLE
[Test harness] Neo4jRule should start a graph DB with all the built-in procedures/functions

### ISSUE THREAD

**Issue by sapiriou** [neo4j/neo4j#10280]
I've tried using the Neo4jRule to test the execution of a procedure and it crashed because the built-in procedures are not included and cannot be.

**Neo4j version:** 3.2.6
**Operating system:** Mac OS Sierra (10.12.6)
**API/Driver:** Test harness

### Steps to reproduce
Write a test with the following setup:

```java
import org.assertj.core.api.Assertions.assertThat;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.neo4j.driver.v1.AccessMode;
import org.neo4j.driver.v1.Config;
import org.neo4j.driver.v1.Driver;
import org.neo4j.driver.v1.GraphDatabase;
import org.neo4j.driver.v1.Session;
import org.neo4j.harness.junit.Neo4jRule;
import org.neo4j.server.security.auth.AuthProcedures;

public class MyServiceTest {
    @Rule
    private Neo4jRule neo4jRule = new Neo4jRule().withProcedure(AuthProcedures.class);
    private Driver driver;
    private MyService subject = new MyService();

    @Before
    public void prepare() {
        driver = GraphDatabase.driver(neo4jRule.boltURI(), Config.build().withoutEncryption().toConfig());
    }

   @Test
    public void exists_returns_true_when_the_provided_user_already_exists() {
        try (Session session = driver.session(AccessMode.WRITE)) {
            session.run("CALL dmbs.security.createUser('binding-id', 'blah', false)");
        }
        assertThat(myService.exists(driver, "binding-id")).isTrue();
    }
}
```

### Expected behavior

The test should NOT crash.

### Actual behavior

The test crashes with the following stack trace:

```java
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@13741d5a' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to set up injection for procedure `AuthProcedures`, the field `userManager` has type `interface org.neo4j.kernel.api.security.UserManager` which is not a known injectable component.".

	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:215)
	at org.neo4j.harness.internal.InProcessServerControls.start(InProcessServerControls.java:71)
	at org.neo4j.harness.internal.AbstractInProcessServerBuilder.newServer(AbstractInProcessServerBuilder.java:151)
	at org.neo4j.harness.junit.Neo4jRule$1.evaluate(Neo4jRule.java:73)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@13741d5a' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to set up injection for procedure `AuthProcedures`, the field `userManager` has type `interface org.neo4j.kernel.api.security.UserManager` which is not a known injectable component.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:207)
	... 27 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /var/folders/zh/3gnrkszj2wq2m9gzb46zg20h0000gn/T/562be96bed28db4771f687a0b1b7e83d/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:209)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:124)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	... 29 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.harness.internal.AbstractInProcessServerBuilder$Neo4jHarnessExtensions$1@4487c0c2' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to set up injection for procedure `AuthProcedures`, the field `userManager` has type `interface org.neo4j.kernel.api.security.UserManager` which is not a known injectable component.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:85)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:205)
	... 33 more
Caused by: org.neo4j.kernel.api.exceptions.ComponentInjectionException: Unable to set up injection for procedure `AuthProcedures`, the field `userManager` has type `interface org.neo4j.kernel.api.security.UserManager` which is not a known injectable component.
	at org.neo4j.kernel.impl.proc.FieldInjections.createInjector(FieldInjections.java:129)
	at org.neo4j.kernel.impl.proc.FieldInjections.setters(FieldInjections.java:111)
	at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler.compileProcedure(ReflectiveProcedureCompiler.java:263)
	at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler.compileProcedure(ReflectiveProcedureCompiler.java:213)
	at org.neo4j.kernel.impl.proc.Procedures.registerProcedure(Procedures.java:155)
	at org.neo4j.kernel.impl.proc.Procedures.registerProcedure(Procedures.java:142)
	at org.neo4j.kernel.impl.proc.Procedures.registerProcedure(Procedures.java:132)
	at org.neo4j.harness.internal.HarnessRegisteredProcs.applyTo(HarnessRegisteredProcs.java:54)
	at org.neo4j.harness.internal.AbstractInProcessServerBuilder$Neo4jHarnessExtensions$1.start(AbstractInProcessServerBuilder.java:317)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	... 38 more
``` 

I believe there is no way to configure Neo4j dependency injection via `Neo4jRule` to bind `BasicUserManager` to the interface `UserManager`.

**Comment by OliviaYtterbrink** [comment]
Instead of trying to load the AuthProcedures manually you should enable auth through setting the config.
`public Neo4jRule neo4jRule = new Neo4jRule().withConfig( GraphDatabaseSettings.auth_enabled, "true" );`

Enabling auth does require you to create the driver with an AuthToken as well, and you should change the password after logging in.

```java
    @Rule
    public Neo4jRule neo4jRule = new Neo4jRule().withConfig( GraphDatabaseSettings.auth_enabled, "true" );

    @Before
    public void prepare()
    {
        driver = GraphDatabase.driver( neo4jRule.boltURI(), AuthTokens.basic( "neo4j", "neo4j"  ), Config.build().withoutEncryption().toConfig() );
    }

    @Test
    public void exists_returns_true_when_the_provided_user_already_exists()
    {
        try ( Session session = driver.session( AccessMode.WRITE ) )
        {
            session.run( "CALL dbms.security.changePassword('j4oen')" );
            session.run( "CALL dbms.security.createUser('binding-id', 'blah', false)" );
        }
    }
```

**Comment by Lojjs** [comment]
@sapiriou I will close this issue for now. If you need more help than Olivia's answer above, please feel free to re-open it.
