### ISSUE TITLE
BatchInserter max node id value?

### ISSUE THREAD

**Issue by mihairaulea** [neo4j/neo4j#10364]
I am using Neo4j 3.1.4, on Mac OS X El Capitan, single machine. The database is always clean when running the test below.
Inserting nodes with large Long numbers fails. I think it has something to do with the underlying lucene index. If i change 4766131808L to a smaller number, the system behaves as expected. If not, the error bellow occurs. 

```
@Test
    public void quickBenchmark2() {
        for(int i=0;i<3000;i++)
            batchInserter.createNode(4766131808L+i,new HashMap<>());
        batchInserter.shutdown();
    }
```

Error: 

```
org.neo4j.kernel.impl.store.UnderlyingStorageException: java.io.IOException: Exception in the page eviction thread

	at org.neo4j.kernel.impl.store.CommonAbstractStore$1.next(CommonAbstractStore.java:1171)
	at org.neo4j.kernel.impl.store.CommonAbstractStore$1.next(CommonAbstractStore.java:1147)
	at org.neo4j.unsafe.impl.batchimport.staging.ReadRecordsStep.nextBatchOrNull(ReadRecordsStep.java:85)
	at org.neo4j.unsafe.impl.batchimport.staging.ProducerStep.process(ProducerStep.java:78)
	at org.neo4j.unsafe.impl.batchimport.staging.ProducerStep$1.run(ProducerStep.java:56)
Caused by: java.io.IOException: Exception in the page eviction thread
	at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.assertHealthy(MuninnPageCache.java:654)
	at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.grabFreeAndExclusivelyLockedPage(MuninnPageCache.java:708)
	at org.neo4j.io.pagecache.impl.muninn.MuninnPagedFile.grabFreeAndExclusivelyLockedPage(MuninnPagedFile.java:521)
	at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.pageFault(MuninnPageCursor.java:317)
	at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.initiatePageFault(MuninnPageCursor.java:290)
	at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.uncommonPin(MuninnPageCursor.java:271)
	at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.pin(MuninnPageCursor.java:254)
	at org.neo4j.io.pagecache.impl.muninn.MuninnReadPageCursor.next(MuninnReadPageCursor.java:60)
	at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.next(MuninnPageCursor.java:121)
	at org.neo4j.kernel.impl.store.CommonAbstractStore.readIntoRecord(CommonAbstractStore.java:1026)
	at org.neo4j.kernel.impl.store.CommonAbstractStore.access$000(CommonAbstractStore.java:63)
	at org.neo4j.kernel.impl.store.CommonAbstractStore$1.next(CommonAbstractStore.java:1166)
	... 4 more
Caused by: java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.pwrite0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.pwrite(FileDispatcherImpl.java:66)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:89)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:778)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:764)
	at org.neo4j.io.fs.StoreFileChannel.write(StoreFileChannel.java:50)
	at org.neo4j.io.fs.StoreFileChannel.writeAll(StoreFileChannel.java:65)
	at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.swapOut(SingleFilePageSwapper.java:270)
	at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.write(SingleFilePageSwapper.java:435)
	at org.neo4j.io.pagecache.impl.muninn.MuninnPage.doFlush(MuninnPage.java:154)
	at org.neo4j.io.pagecache.impl.muninn.MuninnPage.flush(MuninnPage.java:142)
	at org.neo4j.io.pagecache.impl.muninn.MuninnPage.evict(MuninnPage.java:209)
	at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.evictPage(MuninnPageCache.java:979)
	at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.evictPages(MuninnPageCache.java:937)
	at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.continuouslySweepPages(MuninnPageCache.java:863)
	at org.neo4j.io.pagecache.impl.muninn.EvictionTask.run(EvictionTask.java:39)
	at org.neo4j.io.pagecache.impl.muninn.BackgroundTask.run(BackgroundTask.java:45)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by chrisvest** [comment]
Don't set explicit internal ids on the nodes or relationships you create. Let the database assign them for you, and instead (if you need those numbers) put your ids in a property and create an index for them — that's the way to fix this.

The internal ids correspond to physical record positions in our internal data structures, which means that these large numbers will cause our store files to become too large to fit on your drive.
