### ISSUE TITLE
Error with complex parameter in 3.3.0 (working in 3.2.6)

### ISSUE THREAD

**Issue by sgehrig** [neo4j/neo4j#10387]
**Neo4j Version:** 3.3.0-enterprise
**Operating System:** Docker Image and Ubuntu 16.04
**Driver:** PHP graphaware/neo4j-bolt-php 1.10.0

The following query

```
MATCH (role:ROLE)
WHERE role.id = $id
WITH role
UNWIND $permissions AS permission
MATCH (realm:REALM)
WHERE realm.id = permission.realmId
CREATE (role)-[:HAS_PERMISSION { permissions: permission.rights }]->(realm)
```

with these parameters

```
{

    id: 'abc',
    permissions: [
        {
            realmId: 'def',
            rights: ['read']
        }
    ]
}
```

fails on 3.3.0 while it's working fine on 3.2.6.

The error log shows

```
[o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: null, reference 9f658959-e0c0-4db7-95b1-b739b497fd30.
2017-11-06 13:00:00.750+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: null, reference 9f658959-e0c0-4db7-95b1-b739b497fd30.
java.lang.ArrayIndexOutOfBoundsException
  at java.lang.System.arraycopy(Native Method)
  at org.neo4j.cypher.internal.compatibility.v3_3.runtime.slotted.PrimitiveExecutionContext.copyFrom(PrimitiveExecutionContext.scala:55)
  at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.QueryState$$anonfun$copyArgumentStateTo$1.apply(QueryState.scala:77)
  at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.QueryState$$anonfun$copyArgumentStateTo$1.apply(QueryState.scala:77)
  at scala.Option.foreach(Option.scala:257)
```

Running the same query with the same parameters in the Neo4j browser works. Same is true if the query is prefixed with `cypher runtime=interpreted ...`.

### Expected behavior
Query should work as in 3.2.6.

### Actual behavior
Query fails.

**Comment by sgehrig** [comment]
Might also be a problem with the PHP Bolt driver in use (https://github.com/graphaware/neo4j-bolt-php) in combination with Neo4j 3.3.0. Still investigating.

**Comment by SaschaPeukert** [comment]
Hi and thanks for reporting this error.
We will look into it!

**Comment by sgehrig** [comment]
I'm still failing in building a reproducible test case outside our integration test suite. But still, one thing holds true: it's working with 3.2.6 (enterprise or not) or with a `cypher runtime=interpreted ...` prefix.

**Comment by sgehrig** [comment]
There's a lot more output in the debug log than I mentioned above:

```
2017-11-07 14:13:39.299+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: Unable to write to the closed output channel, reference 031201cc-3a57-4bbe-aef1-2b1910430630.
2017-11-07 14:13:39.299+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: Unable to write to the closed output channel, reference 031201cc-3a57-4bbe-aef1-2b1910430630. Unable to write to the closed output channel
org.neo4j.bolt.v1.packstream.PackOutputClosedException: Unable to write to the closed output channel
	at org.neo4j.bolt.v1.transport.ChunkedOutput.ensure(ChunkedOutput.java:166)
	at org.neo4j.bolt.v1.transport.ChunkedOutput.writeShort(ChunkedOutput.java:95)
	at org.neo4j.bolt.v1.packstream.PackStream$Packer.packStructHeader(PackStream.java:440)
	at org.neo4j.bolt.v1.messaging.BoltResponseMessageWriter.onRecord(BoltResponseMessageWriter.java:71)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter$ResultHandler$1.visit(BoltMessageRouter.java:153)
	at org.neo4j.bolt.v1.runtime.CypherAdapterStream.lambda$accept$0(CypherAdapterStream.java:78)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.procs.ProcedureExecutionResult$$anonfun$accept$1.apply(ProcedureExecutionResult.scala:117)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.procs.ProcedureExecutionResult$$anonfun$accept$1.apply(ProcedureExecutionResult.scala:96)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at org.neo4j.cypher.internal.spi.v3_3.ExceptionTranslationSupport$$anon$1.foreach(ExceptionTranslationSupport.scala:46)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.procs.ProcedureExecutionResult.accept(ProcedureExecutionResult.scala:96)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply$mcV$sp(ClosingExecutionResult.scala:175)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:174)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:174)
	at org.neo4j.cypher.internal.compatibility.v3_3.exceptionHandler$runSafely$.apply(exceptionHandler.scala:90)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.accept(ClosingExecutionResult.scala:174)
	at org.neo4j.bolt.v1.runtime.CypherAdapterStream.accept(CypherAdapterStream.java:76)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter$ResultHandler.onRecords(BoltMessageRouter.java:146)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.lambda$pullAll$0(BoltStateMachine.java:452)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:235)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:98)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.pullAll(BoltStateMachine.java:451)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.pullAll(BoltStateMachine.java:236)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onPullAll$6(BoltMessageRouter.java:114)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:134)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.executeBatch(RunnableBoltWorker.java:127)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)
2017-11-07 14:13:39.299+0000 WARN [o.n.b.v.t.BoltMessagingProtocolV1Handler] Unable to send error back to the client. Communication channel is closed. Client has probably been stopped. Unable to write to the closed output channel
org.neo4j.bolt.v1.packstream.PackOutputClosedException: Unable to write to the closed output channel
	at org.neo4j.bolt.v1.transport.ChunkedOutput.ensure(ChunkedOutput.java:166)
	at org.neo4j.bolt.v1.transport.ChunkedOutput.writeShort(ChunkedOutput.java:95)
	at org.neo4j.bolt.v1.packstream.PackStream$Packer.packStructHeader(PackStream.java:440)
	at org.neo4j.bolt.v1.messaging.BoltResponseMessageWriter.onRecord(BoltResponseMessageWriter.java:71)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter$ResultHandler$1.visit(BoltMessageRouter.java:153)
	at org.neo4j.bolt.v1.runtime.CypherAdapterStream.lambda$accept$0(CypherAdapterStream.java:78)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.procs.ProcedureExecutionResult$$anonfun$accept$1.apply(ProcedureExecutionResult.scala:117)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.procs.ProcedureExecutionResult$$anonfun$accept$1.apply(ProcedureExecutionResult.scala:96)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at org.neo4j.cypher.internal.spi.v3_3.ExceptionTranslationSupport$$anon$1.foreach(ExceptionTranslationSupport.scala:46)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.procs.ProcedureExecutionResult.accept(ProcedureExecutionResult.scala:96)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply$mcV$sp(ClosingExecutionResult.scala:175)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:174)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:174)
	at org.neo4j.cypher.internal.compatibility.v3_3.exceptionHandler$runSafely$.apply(exceptionHandler.scala:90)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.accept(ClosingExecutionResult.scala:174)
	at org.neo4j.bolt.v1.runtime.CypherAdapterStream.accept(CypherAdapterStream.java:76)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter$ResultHandler.onRecords(BoltMessageRouter.java:146)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.lambda$pullAll$0(BoltStateMachine.java:452)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:235)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:98)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.pullAll(BoltStateMachine.java:451)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.pullAll(BoltStateMachine.java:236)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onPullAll$6(BoltMessageRouter.java:114)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:134)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.executeBatch(RunnableBoltWorker.java:127)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)
2017-11-07 14:13:39.495+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: null, reference ab3e58c4-30aa-4340-a92b-08f109fe92ab.
2017-11-07 14:13:39.495+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: null, reference ab3e58c4-30aa-4340-a92b-08f109fe92ab.
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.slotted.PrimitiveExecutionContext.copyFrom(PrimitiveExecutionContext.scala:55)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.QueryState$$anonfun$copyArgumentStateTo$1.apply(QueryState.scala:77)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.QueryState$$anonfun$copyArgumentStateTo$1.apply(QueryState.scala:77)
	at scala.Option.foreach(Option.scala:257)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.QueryState.copyArgumentStateTo(QueryState.scala:77)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.slotted.pipes.NodeIndexScanSlottedPipe$$anonfun$internalCreateResults$1.apply(NodeIndexScanSlottedPipe.scala:46)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.slotted.pipes.NodeIndexScanSlottedPipe$$anonfun$internalCreateResults$1.apply(NodeIndexScanSlottedPipe.scala:44)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.helpers.PrimitiveLongHelper$$anon$1.next(PrimitiveLongHelper.scala:28)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:445)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:463)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.EmptyResultPipe.internalCreateResults(EmptyResultPipe.scala:28)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:62)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.createResults(DefaultExecutionResultBuilderFactory.scala:102)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:74)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.BuildInterpretedExecutionPlan$$anonfun$getExecutionPlanFunction$1.apply(BuildInterpretedExecutionPlan.scala:111)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.BuildInterpretedExecutionPlan$$anonfun$getExecutionPlanFunction$1.apply(BuildInterpretedExecutionPlan.scala:94)
	at org.neo4j.cypher.internal.BuildSlottedExecutionPlan$SlottedExecutionPlan.run(BuildSlottedExecutionPlan.scala:102)
	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(Compatibility.scala:182)
	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(Compatibility.scala:178)
	at org.neo4j.cypher.internal.compatibility.v3_3.exceptionHandler$runSafely$.apply(exceptionHandler.scala:90)
	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$ExecutionPlanWrapper.run(Compatibility.scala:178)
	at org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:29)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:116)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:62)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachineSPI$1.start(TransactionStateMachineSPI.java:146)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$2.run(TransactionStateMachine.java:285)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:77)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$2.run(BoltStateMachine.java:398)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.run(BoltStateMachine.java:200)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onRun$3(BoltMessageRouter.java:93)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:134)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)
```

**Comment by sgehrig** [comment]
And another strange thing I noticed: as soon as I do a query-by-query step debugging on PHP side  and thus extending the time between two queries, the statement works.

**Comment by pontusmelke** [comment]
Hi @sgehrig, thanks for reporting this issue. I am so far unable to reproduce the failure, are you saying you only seen the error using the PHP driver? When you say "extending the time between the queries", what do you mean? Do you only see the error when running the query twice?

Could you try running with `dbms.logs.query.enabled=true` in `neo4j.conf` (only available in enterprise)? Since it seems to be working both in the browser (which uses the javascript driver) and it seems to work fine when called directly on the server I am suspecting there is something weird with the data being sent from the php-driver, and looking in the `query.log` we should be able to see what kind of data the server gets.

Regards,
Pontus

**Comment by sgehrig** [comment]
Hi @pontusmelke,

by "extending the time between the queries" I meant that, the time between two queries is longer when we debug through the code (because the debugger stops at every step). 

Even though I initially thought as well that the issue is to be found on the driver side, the fact that everything works as expected when we switch the Cypher runtime to `interpreted` (or when using 3.2.6)  hints that it's not (only) the driver.

The problem is indeed that the issue is really hard to reproduce and that it's more the sequence of queries that lead to the error. We have another query that results in the same error - but that was hidden by a very aggressive exception catching block 😉

I'll enable the query log and report back the results.

**Comment by sgehrig** [comment]
@pontusmelke How can I send you the log files?

**Comment by pontusmelke** [comment]
You can just attach the log to the issue, please attach the debug.log as well.

So you're seeing the error when you run multiple queries? Are they all run in the same session/transaction?

**Comment by sgehrig** [comment]
These are the two log files: [query.log](https://github.com/neo4j/neo4j/files/1466722/query.log),  [debug.log](https://github.com/neo4j/neo4j/files/1466724/debug.log)

The error occurs reproducibly on an integration test that runs multiple queries in a single transaction.

**Comment by pontusmelke** [comment]
Ok, thanks!

**Comment by pontusmelke** [comment]
You couldn't by any chance send all the queries that are run in that transaction?

**Comment by sgehrig** [comment]
The transaction should start with the query in line `2017-11-13 10:48:25.173+0000 INFO...` in the query log. Or do you need the parameters as well?

**Comment by sgehrig** [comment]
Both logs have been created during a single run of the failing test.

**Comment by pontusmelke** [comment]
Ok, the query you posted is not in the query.log but that may be because it fails and doesn't write anything to the query.log, but I think I should be able to take the others from the log.

**Comment by sgehrig** [comment]
Yes that's true. That is the one that's failing. I've provided you with all the queries that are/should be executed during this one test:

```
// drop schema: CALL db.constraints() and CALL db.indexes() and then 
// drop all keys

// create schema
CREATE INDEX ON :NODE_VERSION(from)
CREATE INDEX ON :NODE_VERSION(until)
CREATE CONSTRAINT ON (x:NODE) ASSERT x.id IS UNIQUE
CREATE CONSTRAINT ON (x:NODE_VERSION) ASSERT x.id IS UNIQUE
CREATE CONSTRAINT ON (x:USER) ASSERT x.id IS UNIQUE
CREATE CONSTRAINT ON (x:USER) ASSERT x.login IS UNIQUE
CREATE CONSTRAINT ON (x:USER) ASSERT x.email IS UNIQUE
CREATE CONSTRAINT ON (x:ROLE) ASSERT x.id IS UNIQUE
CREATE CONSTRAINT ON (x:ROLE) ASSERT x.name IS UNIQUE
CREATE CONSTRAINT ON (x:REALM) ASSERT x.id IS UNIQUE
CREATE CONSTRAINT ON (x:REALM) ASSERT x.name IS UNIQUE
CREATE CONSTRAINT ON (x:GROUP) ASSERT x.id IS UNIQUE
CREATE CONSTRAINT ON (x:GROUP) ASSERT x.name IS UNIQUE
CREATE CONSTRAINT ON (x:DISTRIBUTION_LIST) ASSERT x.id IS UNIQUE
CREATE CONSTRAINT ON (x:DISTRIBUTION_LIST) ASSERT x.name IS UNIQUE
CREATE CONSTRAINT ON (x:METRIC) ASSERT x.id IS UNIQUE
CREATE CONSTRAINT ON (x:FORM) ASSERT x.id IS UNIQUE
CREATE CONSTRAINT ON (x:FORM_VERSION) ASSERT x.id IS UNIQUE
CREATE CONSTRAINT ON (x:CAMPAIGN) ASSERT x.id IS UNIQUE
```

```
CREATE (realm:REALM $properties)
SET realm.lockVersion = coalesce(realm.lockVersion, 1) + 1
RETURN realm
```
with parameters:
```
[
    'properties' => [
        'id'       => $id,
        'name'     => $name,
        'rights'   => [
            'read',
            'edit',
            'create',
            'delete',
            'comment',
        ],
        'creator'  => '__system__',
        'created'  => '2017-11-08T09:25:59+0000',
        'modifier' => '__system__',
        'modified' => '2017-11-08T09:25:59+0000',
    ],
]
// where $id (first element) and $name (second element) are
$realms = [
    ['9c7c6d0f-a96e-4c58-8961-6e69510df049', 'acl'],
    ['512330ce-8c14-4653-8de1-1ac2bbb3c42b', 'enterprise_structure'],
    ['280608c7-22ea-4303-89fd-7429118d2046', 'node_overview'],
    ['e401b1a0-1dcd-4cd9-8917-aaea46b5cd87', 'metric'],
    ['dbd4efa2-ffd2-4a17-91b6-6934a9495a20', 'unit_system'],
    ['9afccd83-da57-494b-9caf-f18dc988dabf', 'campaign'],
    ['a25c0dc8-47c5-4b89-bc4c-b741b91974f1', 'form'],
    ['10ede59b-f739-44c3-8fdb-95b01bab9119', 'enterprise_structure_node_data'],
];
```

```
CREATE (role:ROLE $properties)
SET role.lockVersion = coalesce(role.lockVersion, 1) + 1
```
with parameters:
```
[
    'properties' => [
        'id'        => $id,
        'name'      => $name,
        'contentId' => null,
        'creator'   => '__system__',
        'created'   => '2017-11-08T09:25:59+0000',
        'modifier'  => '__system__',
        'modified'  => '2017-11-08T09:25:59+0000',
    ],
]
```

```
MATCH (role:ROLE), (realm:REALM)
WHERE role.id = $id
WITH role, realm
ORDER BY realm.name ASC
WITH role, realm,
    [(role)-[permission:HAS_PERMISSION]->(realm) | permission.permissions] AS permissions
RETURN role, COLLECT({realm: realm, permissions: coalesce(head(permissions), [])}) AS permissions
```
with parameters:
```
[
    'id' => $id,
]
```

```
MATCH (n:`ROLE`) WHERE true AND n.`id` = $param_0 RETURN n
```
with parameters:
```
[
    'param_0' => $id,
]
```

```
MATCH (role:ROLE)
WHERE role.id = $id
SET role += $properties
SET role.lockVersion = coalesce(role.lockVersion, 1) + 1
```
with parameters:
```
[
    'id'         => $id,
    'properties' => [
        'id'        => $id,
        'name'      => $name,
        'contentId' => null,
        'modifier'  => '__system__',
        'modified'  => '2017-11-08T09:25:59+0000',
    ],
]
```

```
MATCH (role:ROLE)-[permission:HAS_PERMISSION]->(:REALM)
WHERE role.id = $id
DELETE permission
```
with parameters:
```
[
    'id' => $id,
]
```

That'a the one that fails at some point:
```
MATCH (role:ROLE)
WHERE role.id = $id
WITH role
UNWIND $permissions AS permission
MATCH (realm:REALM)
WHERE realm.id = permission.realmId
CREATE (role)-[:HAS_PERMISSION { permissions: permission.rights }]->(realm)
```
with parameters:
```
[
    'id'          => $id,
    'permissions' => $permissions,
]
```

```
MATCH (role:ROLE), (realm:REALM)
WHERE role.id = $id
WITH role, realm
ORDER BY realm.name ASC
WITH role, realm,
    [(role)-[permission:HAS_PERMISSION]->(realm) | permission.permissions] AS permissions
RETURN role, COLLECT({realm: realm, permissions: coalesce(head(permissions), [])}) AS permissions
```
with parameters:
```
[
    'id' => $id,
]
```

```
// where $id (first element), $name (second element) and $permissions (third element) are
$roles = [
    [
        '67cd8e40-b243-4617-a2ab-ef8a5cd1bd93',
        'TestRole1 (r)',
        [
            [
                'realmId' => '9c7c6d0f-a96e-4c58-8961-6e69510df049',
                'rights'  => ['read'],
            ],
        ],
    ],
    [
        'cd876120-cb1f-4606-8740-b8ebef74baf7',
        'TestRole2 (re)',
        [
            [
                'realmId' => '9c7c6d0f-a96e-4c58-8961-6e69510df049',
                'rights'  => ['read', 'edit', 'comment'],
            ],
        ],
    ],
    [
        '47ed23de-5447-4540-a07f-f0318d538efa',
        'TestRole3 (rec)',
        [
            [
                'realmId' => '9c7c6d0f-a96e-4c58-8961-6e69510df049',
                'rights'  => ['read', 'edit', 'create', 'comment'],
            ],
        ],
    ],
    [
        '8a095941-fd4b-4bd4-a01b-35c548e866d5',
        'TestRole4 (recd)',
        [
            [
                'realmId' => '9c7c6d0f-a96e-4c58-8961-6e69510df049',
                'rights'  => ['read', 'edit', 'create', 'delete', 'comment'],
            ],
        ],
    ],
];
```

**Comment by pontusmelke** [comment]
Thanks for providing all the info, I think finally was able to track down the issue https://github.com/neo4j/neo4j/pull/10437

The fix will go out in the next version of neo4j, thanks again for reporting and sorry for the inconvenience.
Regards,
Pontus

**Comment by sgehrig** [comment]
@pontusmelke Great! Thanks a lot! We really appreciate your effort!!! 
Two questions:
1) What will be the release date for the next version?
2) Can you tell me a little bit more about the problem? What was the real cause and why was it so hard to reproduce the issue?

**Comment by pontusmelke** [comment]
It will most probably go out with 3.3.1, I cannot give you an exact date but it will go out pretty soon. 

The problem was only for index scans so the database must be in a state where the cost planner computes it to be more efficient to do a scan than a unique index seek. If you remove the constraints on `:ROLE(id)` and `:REALM(id)` and instead use an index on these properties the error was a little bit easier to reproduce.

**Comment by sgehrig** [comment]
OK - that's understood. Thanks so much for your support.

**Comment by sherfert** [comment]
3.3.1 is out by the way, including the fix.

**Comment by sgehrig** [comment]
Great. We're only waiting for the 3.3.1 docker images to verify the fix.
