### ISSUE TITLE
Neo4j Desktop: Failure to restart- StoreLockException after database crash

### ISSUE THREAD

**Issue by luanne** [neo4j/neo4j#10420]
After the database crashes, for example, with an OutOfMemoryException, restarting the database via Neo4j Desktop, or even quitting and restarting Neo4j Desktop itself fails to start the database (StoreLockException)

- Neo4j version: 3.3.0
- Operating system: Mac OS 10.12.6
- API/Driver: Neo4j Desktop

- **Steps to reproduce**
1. Cause a database crash- I tried to set a property on 500k nodes with default memory config, producing
```
2017-11-12 13:05:17.118+0000 ERROR [o.n.b.v.r.c.RunnableBoltWorker] Worker for session 'b7578d9d-e6ef-478b-b133-56b169960e5b' crashed. Java heap space
java.lang.OutOfMemoryError: Java heap space

2017-11-12 13:06:11.448+0000 ERROR [o.n.k.i.DatabaseHealth] Database panic: Database has encountered some problem, please perform necessary action (tx recovery/restart) Failed to apply transaction: Transaction #105 at log position LogPosition{logVersion=1, byteOffset=61981784} {started 2017-11-12 13:04:34.482+0000, committed 2017-11-12 13:04:39.120+0000, with 500002 commands in this transaction, authored by -1, with master id -1, lock session 1, latest committed transaction id when started was 103, additional header bytes: 
6C
7D
69
A8
8D
9D
31
4E}
org.neo4j.kernel.api.exceptions.TransactionApplyKernelException: Failed to apply transaction: Transaction #105 at log position LogPosition{logVersion=1, byteOffset=61981784} {started 2017-11-12 13:04:34.482+0000, committed 2017-11-12 13:04:39.120+0000, with 500002 commands in this transaction, authored by -1, with master id -1, lock session 1, latest committed transaction id when started was 103, additional header bytes: 
6C
7D
69
A8
8D
9D
31
4E}
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:334)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:78)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:51)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:597)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:468)
	at org.neo4j.kernel.api.KernelTransaction.close(KernelTransaction.java:138)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.closeTransaction(TransactionStateMachine.java:361)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:237)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:98)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.pullAll(BoltStateMachine.java:451)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.pullAll(BoltStateMachine.java:236)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onPullAll$6(BoltMessageRouter.java:114)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:134)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.executeBatch(RunnableBoltWorker.java:127)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.neo4j.kernel.impl.locking.AbstractLockService.acquireNodeLock(AbstractLockService.java:52)
	at org.neo4j.kernel.impl.locking.ReentrantLockService.acquireNodeLock(ReentrantLockService.java:35)
	at org.neo4j.kernel.impl.transaction.command.NeoStoreTransactionApplier.visitNodeCommand(NeoStoreTransactionApplier.java:75)
	at org.neo4j.kernel.impl.transaction.command.Command$NodeCommand.handle(Command.java:253)
	at org.neo4j.kernel.impl.api.TransactionApplierFacade.visit(TransactionApplierFacade.java:61)
	at org.neo4j.kernel.impl.api.TransactionApplierFacade.visit(TransactionApplierFacade.java:35)
	at org.neo4j.kernel.impl.transaction.log.PhysicalTransactionRepresentation.accept(PhysicalTransactionRepresentation.java:69)
	at org.neo4j.kernel.impl.api.TransactionToApply.accept(TransactionToApply.java:115)
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:326)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:78)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:51)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:597)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:468)
	at org.neo4j.kernel.api.KernelTransaction.close(KernelTransaction.java:138)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.closeTransaction(TransactionStateMachine.java:361)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:237)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:98)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.pullAll(BoltStateMachine.java:451)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.pullAll(BoltStateMachine.java:236)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onPullAll$6(BoltMessageRouter.java:114)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter$$Lambda$384/1852064946.perform(Unknown Source)
	... 9 more
```
2. Stop and restart the database via Neo4j Desktop

- Expected behavior
The database restarts and store locks are released
- Actual behavior
The database fails to start
```
2017-11-12 13:16:40.078+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4331d187' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: /Users/luanne/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7c839fda-8910-4722-93b2-4703b7dd6334/current/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4331d187' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: /Users/luanne/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7c839fda-8910-4722-93b2-4703b7dd6334/current/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4331d187' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: /Users/luanne/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7c839fda-8910-4722-93b2-4703b7dd6334/current/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:218)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4331d187' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: /Users/luanne/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7c839fda-8910-4722-93b2-4703b7dd6334/current/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:210)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /Users/luanne/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7c839fda-8910-4722-93b2-4703b7dd6334/current/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
	at org.neo4j.kernel.enterprise.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:36)
	at org.neo4j.server.enterprise.EnterpriseNeoServer.lambda$static$1(EnterpriseNeoServer.java:75)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter@38aa816f' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: /Users/luanne/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7c839fda-8910-4722-93b2-4703b7dd6334/current/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
	... 9 more
Caused by: org.neo4j.kernel.StoreLockException: Store and its lock file has been locked by another process: /Users/luanne/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7c839fda-8910-4722-93b2-4703b7dd6334/current/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)
	at org.neo4j.kernel.internal.locker.StoreLocker.storeLockException(StoreLocker.java:116)
	at org.neo4j.kernel.internal.locker.StoreLocker.checkLock(StoreLocker.java:92)
	at org.neo4j.kernel.internal.locker.GlobalStoreLocker.checkLock(GlobalStoreLocker.java:60)
	at org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter.start(StoreLockerLifecycleAdapter.java:36)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 11 more
```

Quitting and relaunching the desktop is of no help.

**Comment by The-Don-Himself** [comment]
I believe I'm also running into this when trying to test out Neo4j.

Neo4j desktop crashes and cant be restarted, I can seem to find where the logs are stored though, any pointers so that I can add to this? 

- Windows 7 64 Bit setup.

Neo4j desktop 1.07 but updated just before crash, no data at all in DB.

**Comment by The-Don-Himself** [comment]
Never mind, found it and investigating the crash now. 
Thanks

**Comment by klaren** [comment]
All locked files should be released by the OS once the owning process is killed. What happens in this issue is that when you encounter an out of memory exception the neo4j instance cannot be shut down cleanly and even if you instruct it to stop, it will still linger. 

To get out of this you can locate the process id of the neo4j instance with 
```bash
ps aux | grep "org.neo4j.server"
```
and then 
```bash
kill -9 <process id>
```
This should release all the file locks.

This task could be automated in the neo4j desktop application and I've created a feature request for this. Thanks for reporting this issue!

**Comment by mohseen1196** [comment]
Killing this process Id is restarting it again and again

Eg - sudo kill -9 11458 --> Kills this process but when i run ps aux | grep "org.neo4j.server"

It creates another process 

ps aux | grep "org.neo4j.server"
neo4j    11529 85.0 10.9 3054108 897060 ?      Ssl  08:01   0:00 /usr/bin/java -cp /var/lib/neo4j/plugins:/etc/neo4j:/usr/share/neo4j/lib/*:/var/lib/neo4j/plugins/* -server -Xms2G -Xmx2G -XX:+UseG1GC -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:+DisableExplicitGC -Djdk.tls.ephemeralDHKeySize=2048 -Djdk.tls.rejectClientInitiatedRenegotiation=true -Dunsupported.dbms.udc.source=debian -Dfile.encoding=UTF-8 org.neo4j.server.CommunityEntryPoint --home-dir=/var/lib/neo4j --config-dir=/etc/neo4j
ubuntu   11585  0.0  0.0  12940   984 pts/1    S+   08:01   0:00 grep --color=auto org.neo4j.server

**Comment by daniel10012** [comment]
I have the same problem it keeps restarting, found any solution ?

**Comment by klaren** [comment]
@daniel10012 The problem in this issue can ultimately be fixed by restarting the computer/server. If it still fails to start, there is a different problem. If that is the case I recommend open a new issue.
