### ISSUE TITLE
Neo4j server crashed when load huge data by using LOAD CSV

### ISSUE THREAD

**Issue by cloudhuang** [neo4j/neo4j#10626]
## Guidelines

I need to load the huge data by using LOAD CSV, by standard, load nodes, then load relationships,  but after load 100, 000, 000+ nodes & relationships, the neo4j server crashed

- Neo4j version: 3.2.3
- Operating system: Ubuntu 16.04 LTS
- 64GB OS Memory: 16GB Heap + 45GB page cache

**debug.log**
```
2017-12-11 20:49:14.528+0000 INFO [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [521]:  Starting log pruning.
2017-12-11 20:50:16.019+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 3397ms.
2017-12-11 20:52:16.434+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 5594ms.
2017-12-11 20:52:24.616+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 205ms.
2017-12-11 20:53:33.820+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 1998ms.
2017-12-11 20:54:08.930+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 8591ms.
2017-12-11 20:56:12.319+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 9704ms.
2017-12-11 20:56:24.922+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 1598ms.
2017-12-11 20:57:49.020+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 1585ms.
2017-12-11 20:58:24.126+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 15906ms.
2017-12-11 20:58:44.140+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 2791ms.
2017-12-11 20:58:55.438+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 4081ms.
2017-12-11 20:59:19.023+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 2289ms.
```
I'm using the default GC but seems GC take a lots of time.

**neo4j.log**
```
java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:161)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-11 20:42:58.254+0000 WARN  Commit failed Idle timeout expired: 30030/30000 ms
java.util.concurrent.TimeoutException: Idle timeout expired: 30030/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:161)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-11 20:43:10.942+0000 WARN  Commit failed Idle timeout expired: 30000/30000 ms
java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:161)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-11 20:58:39.557+0000 WARN  Commit failed Idle timeout expired: 30000/30000 ms
java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:161)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Lojjs** [comment]
Thanks for reporting, we will take a look at this and see if it can be a bug.
/Louise, Neo4j Cypher Team

**Comment by InverseFalcon** [comment]
You'll need to add more here for there to be any useful analysis. Can you provide the LOAD CSV query, and the profile plan from an EXPLAIN of the query (with all elements of the plan expanded)

**Comment by sherfert** [comment]
Closing for now. Please reopen with more information, if desired.
