### ISSUE TITLE
Neo4j server doesn't start on NFS mounts due to lock issue

### ISSUE THREAD

**Issue by mmcauliffe** [neo4j/neo4j#10625]
I had an issue getting a Neo4j server to start on a NFS mounted drive in Debian 8.  It seems like locking is slightly problematic in NFS, but there might be something on your end that could be fixed?

**Neo4j Version:** 3.3.1
**Operating System:** Debian 8

### Steps to reproduce
1. Using the standalone install (https://go.neo4j.com/download-thanks.html?edition=community&release=3.3.1&flavour=unix) and untar
2. Run `bin/neo4j console` in the directory

### Expected behavior
Neo4j should start with no problem

### Actual behavior
Neo4j doesn't start and gives the following output:

```
Active database: graph.db
Directories in use:
  home:         /home/linguistics/prosodylab/dev/polyglot-server/test_data/data/cont/neo4j
  config:       /home/linguistics/prosodylab/dev/polyglot-server/test_data/data/cont/neo4j/conf
  logs:         /home/linguistics/prosodylab/dev/polyglot-server/test_data/data/cont/neo4j/logs
  plugins:      /home/linguistics/prosodylab/dev/polyglot-server/test_data/data/cont/neo4j/plugins
  import:       NOT SET
  data:         /home/linguistics/prosodylab/dev/polyglot-server/test_data/data/cont/neo4j/data
  certificates: /home/linguistics/prosodylab/dev/polyglot-server/test_data/data/cont/neo4j/certificates
  run:          /home/linguistics/prosodylab/dev/polyglot-server/test_data/data/cont/neo4j/run
Starting Neo4j.
2017-12-11 23:17:51.795+0000 WARN  dbms.connector.bolt.type is deprecated.
2017-12-11 23:17:51.803+0000 WARN  dbms.connector.https.encryption is deprecated.
2017-12-11 23:17:51.803+0000 WARN  dbms.connector.http.type is deprecated.
2017-12-11 23:17:51.803+0000 WARN  dbms.connector.https.type is deprecated.
2017-12-11 23:17:51.838+0000 INFO  ======== Neo4j 3.3.1 ========
2017-12-11 23:17:51.895+0000 INFO  Starting...
2017-12-11 23:17:53.155+0000 INFO  Bolt enabled on 127.0.0.1:7402.
2017-12-11 23:18:05.284+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6c61a903' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: /home/linguistics/prosodylab/dev/polyglot-server/test_data/data/cont/neo4j/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6c61a903' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: /home/linguistics/prosodylab/dev/polyglot-server/test_data/data/cont/neo4j/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6c61a903' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: /home/linguistics/prosodylab/dev/polyglot-server/test_data/data/cont/neo4j/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:219)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6c61a903' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: /home/linguistics/prosodylab/dev/polyglot-server/test_data/data/cont/neo4j/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /home/linguistics/prosodylab/dev/polyglot-server/test_data/data/cont/neo4j/data/databases/graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:126)
        at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter@704deff2' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: /home/linguistics/prosodylab/dev/polyglot-server/test_data/data/cont/neo4j/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
        ... 9 more
Caused by: org.neo4j.kernel.StoreLockException: Unable to obtain lock on store lock file: /home/linguistics/prosodylab/dev/polyglot-server/test_data/data/cont/neo4j/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)
        at org.neo4j.kernel.internal.locker.StoreLocker.storeLockException(StoreLocker.java:116)
        at org.neo4j.kernel.internal.locker.StoreLocker.unableToObtainLockException(StoreLocker.java:109)
        at org.neo4j.kernel.internal.locker.StoreLocker.checkLock(StoreLocker.java:97)
        at org.neo4j.kernel.internal.locker.GlobalStoreLocker.checkLock(GlobalStoreLocker.java:60)
        at org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter.start(StoreLockerLifecycleAdapter.java:36)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 11 more
```

**Comment by chrisvest** [comment]
First make sure that you only have a single Neo4j instance trying to access the store.

NFS protocol version 4 should support locking. If you are using that version, then I would expect `local_lock=all` (with `lock`/`nolock` unspecified) to work. If you can't get that to work, then you can try `nolock` or `local_lock=none`, but then it's up to you and your ops to ensure that no two Neo4j instances work on the store files and transaction log at the same time. NFS man page for reference: https://linux.die.net/man/5/nfs

**Comment by mmcauliffe** [comment]
Definitely one instance, this was the first time setting it up on this particular server, and I checked all the running processes and lsof.

It looks like the NFS is version 3, which is probably the issue (it doesn't support locking?).  I worked around it by installing it to an ext4 partition instead, since the NFS is maintained at the institution level.

**Comment by chrisvest** [comment]
I _think_ NFS 3 can be configured in a way that allows Neo4j to run, but it might not be worth the hassle in your case since you found yourself a work-around.

On our end we have to insist on locking the files, because it prevents a lot of simple mistakes, like forgetting you already have Neo4j running and then you try to start it again on the same store, etc.

I think we can close this issue.
