### ISSUE TITLE
NullPointerReference when updating or deleting objects

### ISSUE THREAD

**Issue by peterfarabaugh** [neo4j/neo4j#10656]
Something is corrupting nodes in my db. So far it is localized to one label 'User'. I can create them and set properties, eventually something happens and any attempt to set a value or delete the node hangs.
For example: 
match (u:User {email: 'myuser@gmail.com'}) delete u

although:

match(u:User {email: 'myuser@gmail.com'}) return u

still works fine. If I make another user it works for a bit then the same thing happens.

UPDATE2: I narrowed it down; it is the properties() that does it.
MATCH (x:X) set x.y=1 RETURN properties(x) as x
hangs, 
MATCH (x:X) set x.y=1 RETURN x

doesn't.

UPDATE: I distilled it down to 2 steps: 
1. create (u:User {email: 'u2@gmail.com',password: 'bob',username: 'pfarabaugh',firstname: 'Peter',lastname: 'Farabaugh'})
2. MATCH (u:User {email: $username,password: $password}) SET u.token=$token RETURN properties(u) as u with {
  "username": "u2@gmail.com",
  "password": "bob",
  "token": "eyJhbGciOiJIUzI1NiJ9.dTFAZ21haWwuY29t.RDSX-PmBGogJUXxtERV1FhKG9lFORTwAYXmu4bUB2uc"
}
I also verified that any fieldname or value in the set will cause the hang.

The debug log shows: 
2017-12-18 18:09:15.371+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: null, reference 283bf860-a060-4195-a1f7-eb0b19fa6db0.
2017-12-18 18:09:15.371+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: null, reference 283bf860-a060-4195-a1f7-eb0b19fa6db0.
java.lang.NullPointerException
        at org.neo4j.cypher.internal.spi.v3_3.TransactionBoundQueryContext$NodeOperations.propertyKeyIds(TransactionBoundQueryContext.scala:350)
        at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext$ExceptionTranslatingOperations$$anonfun$propertyKeyIds$1.apply(ExceptionTranslatingQueryContext.scala:282)
        at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext$ExceptionTranslatingOperations$$anonfun$propertyKeyIds$1.apply(ExceptionTranslatingQueryContext.scala:282)
        at org.neo4j.cypher.internal.spi.v3_3.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:32)
        at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:39)
        at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext$ExceptionTranslatingOperations.propertyKeyIds(ExceptionTranslatingQueryContext.scala:282)
        at org.neo4j.cypher.internal.spi.v3_3.DelegatingOperations.propertyKeyIds(DelegatingQueryContext.scala:259)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.helpers.LazyMap.size$lzycompute(MapSupport.scala:88)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.helpers.LazyMap.size(MapSupport.scala:88)
        at org.neo4j.values.virtual.MapValue.writeTo(MapValue.java:62)
        at org.neo4j.bolt.v1.messaging.Neo4jPack$Packer.pack(Neo4jPack.java:86)
        at org.neo4j.bolt.v1.messaging.BoltResponseMessageWriter.onRecord(BoltResponseMessageWriter.java:75)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter$ResultHandler$1.visit(BoltMessageRouter.java:153)
        at org.neo4j.bolt.v1.runtime.CypherAdapterStream.lambda$accept$0(CypherAdapterStream.java:78)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.helpers.RuntimeJavaValueConverter$feedIteratorToVisitable.accept(RuntimeJavaValueConverter.scala:55)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.PipeExecutionResult.accept(PipeExecutionResult.scala:112)
        at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply$mcV$sp(ClosingExecutionResult.scala:175)
        at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:174)
        at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:174)
        at org.neo4j.cypher.internal.compatibility.v3_3.exceptionHandler$runSafely$.apply(exceptionHandler.scala:90)
        at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.accept(ClosingExecutionResult.scala:174)
        at org.neo4j.bolt.v1.runtime.CypherAdapterStream.accept(CypherAdapterStream.java:76)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter$ResultHandler.onRecords(BoltMessageRouter.java:146)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.lambda$pullAll$0(BoltStateMachine.java:452)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:235)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:98)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.pullAll(BoltStateMachine.java:451)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.pullAll(BoltStateMachine.java:236)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onPullAll$6(BoltMessageRouter.java:114)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:134)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:91)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)

**Neo4j Version:** 3.3.0 
**Operating System:** Amazon Linux  
**API:** neo4j-driver (node.js)

### Steps to reproduce
Not sure yet. I will update if I can figure out exactly which command breaks it, 

### Expected behavior
attributes should be settable and nodes should be deletable
### Actual behavior
setting attributes or deleting properties fails and hangs

**Comment by Lojjs** [comment]
@peterfarabaugh thanks for reporting, this sounds like a serious bug related to updating and returning properties in the same query. We will investigate this and come back to you once it is solved.
Best regards Louise, Neo4j Cypher team

**Comment by sherfert** [comment]
There is a bugfix for this in the soon to be released 3.3.2
