### ISSUE TITLE
Cypher throws "failed assertion" when comparing elements with <>

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#10695]
**Neo4j Version:** 3.3.1 EE
**Operating System:** OS X
**API:** Browser

### Steps to reproduce

Given some nodes and relationships, run the following query : 

```
MATCH (b:Book)-[:CHILD]->(:Chapter)-[:CHILD]->(c)
MATCH (c)-[:CHILD*]->(r:ReadableText)<-[:INDEXES]-(k)
WITH r, k, count(*) AS f
MATCH (k)-[:INDEXES]->(r2)
WHERE r <> r2
RETURN r.text, r2.text, collect(distinct k.value)
LIMIT 10
```

*Notice* the `WHERE r <> r2` => it works.

Change to `WHERE r2 <> r` => Throws a `failed assertion exception`

### Expected behavior

The query should work independently of the position of identifiers in the comparison

### Actual behavior

It throws an exception with the following stacktrace : 

```
2017-12-28 00:09:29.473+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: assertion failed, reference 029a2952-6048-49d1-8fa4-ac7bca4dcae4. assertion failed
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.SlottedRewriter$$anonfun$3.applyOrElse(SlottedRewriter.scala:150)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.neo4j.cypher.internal.frontend.v3_3.Rewritable$RewritableAny$.rewrite$extension(Rewritable.scala:113)
	at org.neo4j.cypher.internal.frontend.v3_3.topDown$TopDownRewriter.rec(Rewritable.scala:183)
	at org.neo4j.cypher.internal.frontend.v3_3.topDown$TopDownRewriter.apply(Rewritable.scala:160)
	at org.neo4j.cypher.internal.frontend.v3_3.Rewritable$RewritableAny$.rewrite$extension(Rewritable.scala:113)
	at org.neo4j.cypher.internal.frontend.v3_3.Rewritable$RewritableAny$.endoRewrite$extension(Rewritable.scala:120)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.SlottedRewriter$$anonfun$1.applyOrElse(SlottedRewriter.scala:108)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.neo4j.cypher.internal.frontend.v3_3.Rewritable$RewritableAny$.rewrite$extension(Rewritable.scala:113)
	at org.neo4j.cypher.internal.frontend.v3_3.topDown$TopDownRewriter.rec(Rewritable.scala:183)
	at org.neo4j.cypher.internal.frontend.v3_3.topDown$TopDownRewriter.apply(Rewritable.scala:160)
	at org.neo4j.cypher.internal.frontend.v3_3.Rewritable$RewritableAny$.rewrite$extension(Rewritable.scala:113)
	at org.neo4j.cypher.internal.frontend.v3_3.Rewritable$RewritableAny$.endoRewrite$extension(Rewritable.scala:120)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.SlottedRewriter.apply(SlottedRewriter.scala:115)
	at org.neo4j.cypher.internal.BuildSlottedExecutionPlan$.rewritePlan(BuildSlottedExecutionPlan.scala:88)
	at org.neo4j.cypher.internal.BuildSlottedExecutionPlan$.createSlottedRuntimeExecPlan(BuildSlottedExecutionPlan.scala:56)
	at org.neo4j.cypher.internal.BuildSlottedExecutionPlan$.process(BuildSlottedExecutionPlan.scala:50)
	at org.neo4j.cypher.internal.BuildSlottedExecutionPlan$.process(BuildSlottedExecutionPlan.scala:42)
	at org.neo4j.cypher.internal.frontend.v3_3.phases.Phase$$anonfun$transform$1.apply(Phase.scala:36)
	at org.neo4j.cypher.internal.frontend.v3_3.helpers.package$$anonfun$closing$1.apply(package.scala:24)
	at org.neo4j.cypher.internal.frontend.v3_3.helpers.package$$anonfun$closing$1.apply(package.scala:24)
	at org.neo4j.cypher.internal.frontend.v3_3.helpers.package$.using(package.scala:32)
	at org.neo4j.cypher.internal.frontend.v3_3.helpers.package$.closing(package.scala:24)
	at org.neo4j.cypher.internal.frontend.v3_3.phases.Phase$class.transform(Phase.scala:35)
	at org.neo4j.cypher.internal.BuildSlottedExecutionPlan$.transform(BuildSlottedExecutionPlan.scala:42)
	at org.neo4j.cypher.internal.frontend.v3_3.phases.PipeLine.transform(Transformer.scala:45)
	at org.neo4j.cypher.internal.frontend.v3_3.phases.If.transform(Transformer.scala:80)
	at org.neo4j.cypher.internal.frontend.v3_3.phases.PipeLine.transform(Transformer.scala:49)
	at org.neo4j.cypher.internal.frontend.v3_3.phases.PipeLine.transform(Transformer.scala:45)
	at org.neo4j.cypher.internal.frontend.v3_3.phases.If.transform(Transformer.scala:80)
	at org.neo4j.cypher.internal.frontend.v3_3.phases.PipeLine.transform(Transformer.scala:49)
	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$$anon$2$$anonfun$plan$1.org$neo4j$cypher$internal$compatibility$v3_3$Compatibility$class$$anon$$anonfun$$createPlan$1(Compatibility.scala:127)
	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$$anon$2$$anonfun$plan$1$$anonfun$7.apply(Compatibility.scala:131)
	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$$anon$2$$anonfun$plan$1$$anonfun$7.apply(Compatibility.scala:131)
	at org.neo4j.cypher.internal.compatibility.v3_3.QueryCache$$anonfun$getOrElseUpdate$1$$anonfun$apply$1.apply(CacheAccessor.scala:36)
	at org.neo4j.cypher.internal.compatibility.v3_3.MonitoringCacheAccessor$$anonfun$1.apply(CacheAccessor.scala:57)
	at org.neo4j.cypher.internal.compatibility.v3_3.LFUCache$$anon$1.apply(LFUCache.scala:31)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$16(BoundedLocalCache.java:1973)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1892)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1971)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1954)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
	at org.neo4j.cypher.internal.compatibility.v3_3.LFUCache.getOrElseUpdate(LFUCache.scala:30)
	at org.neo4j.cypher.internal.compatibility.v3_3.LFUCache.apply(LFUCache.scala:48)
	at org.neo4j.cypher.internal.compatibility.v3_3.MonitoringCacheAccessor.getOrElseUpdate(CacheAccessor.scala:55)
	at org.neo4j.cypher.internal.compatibility.v3_3.QueryCache$$anonfun$getOrElseUpdate$1.apply(CacheAccessor.scala:34)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:445)
	at org.neo4j.cypher.internal.compatibility.v3_3.QueryCache.getOrElseUpdate(CacheAccessor.scala:46)
	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$$anon$2$$anonfun$plan$1.apply(Compatibility.scala:131)
	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$$anon$2$$anonfun$plan$1.apply(Compatibility.scala:107)
	at org.neo4j.cypher.internal.compatibility.v3_3.exceptionHandler$runSafely$.apply(exceptionHandler.scala:90)
	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$$anon$2.plan(Compatibility.scala:107)
	at org.neo4j.cypher.internal.ExecutionEngine.org$neo4j$cypher$internal$ExecutionEngine$$producePlan$1(ExecutionEngine.scala:176)
	at org.neo4j.cypher.internal.ExecutionEngine$$anonfun$3.apply(ExecutionEngine.scala:180)
	at org.neo4j.cypher.internal.ExecutionEngine$$anonfun$3.apply(ExecutionEngine.scala:180)
	at org.neo4j.cypher.internal.compatibility.v3_3.QueryCache$$anonfun$getOrElseUpdate$1$$anonfun$apply$1.apply(CacheAccessor.scala:36)
	at org.neo4j.cypher.internal.compatibility.v3_3.MonitoringCacheAccessor$$anonfun$1.apply(CacheAccessor.scala:57)
	at org.neo4j.cypher.internal.compatibility.v3_3.LFUCache$$anon$1.apply(LFUCache.scala:31)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$16(BoundedLocalCache.java:1973)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1971)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1954)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
	at org.neo4j.cypher.internal.compatibility.v3_3.LFUCache.getOrElseUpdate(LFUCache.scala:30)
	at org.neo4j.cypher.internal.compatibility.v3_3.LFUCache.apply(LFUCache.scala:48)
	at org.neo4j.cypher.internal.compatibility.v3_3.MonitoringCacheAccessor.getOrElseUpdate(CacheAccessor.scala:55)
	at org.neo4j.cypher.internal.compatibility.v3_3.QueryCache$$anonfun$getOrElseUpdate$1.apply(CacheAccessor.scala:34)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:445)
	at org.neo4j.cypher.internal.compatibility.v3_3.QueryCache.getOrElseUpdate(CacheAccessor.scala:46)
	at org.neo4j.cypher.internal.ExecutionEngine.liftedTree1$1(ExecutionEngine.scala:180)
	at org.neo4j.cypher.internal.ExecutionEngine.planQuery(ExecutionEngine.scala:164)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:115)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:62)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachineSPI$1.start(TransactionStateMachineSPI.java:146)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:210)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:77)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$2.run(BoltStateMachine.java:398)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.run(BoltStateMachine.java:200)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onRun$3(BoltMessageRouter.java:93)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:134)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)
```

**Comment by Lojjs** [comment]
@ikwattro Can you please send us a copy of your database or some smaller set of nodes and relationships where this failure occurs for debugging?

**Comment by ikwattro** [comment]
@Lojjs Sure, I cannot share here publicly but I can send a link to a downloadable backup to your email, you can send me your address to `christophe` ( at ) `graphaware` dot com . Thanks

**Comment by Lojjs** [comment]
@ikwattro I have send you an email

**Comment by fickludd** [comment]
@ikwattro I am unable to reproduce this on `3.3.1`, `OSX 10.11.6` and 

```
Johans-MacBook-Pro-3:bin johant$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

Both `r <> r2` and `r2 <> r` give the same result when I try. The fact that the assertion was failed by `scala.Predef` could possibly mean that it's a setup problem. Could you try to reproduce this on some other system?

**Comment by ikwattro** [comment]
@fickludd You mean been unable to reproduce with the db I have sent to @Lojjs ? 

I can try to test on a nix server yes.
 
Btw, for my side - OSX 10.13.2 : 
```
ikwattro@mbp666 ~> java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
ikwattro@mbp666 ~>
```

**Comment by fickludd** [comment]
Yes, I used that db and the specified query. Your java/OSX setup seems very similar so maybe that's not it.

**Comment by ikwattro** [comment]
@fickludd 

I ported the db to an ubuntu server : 

```
root@knowledge-studio-neo4j:/opt/neo4j# java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
root@knowledge-studio-neo4j:/opt/neo4j#
```

No issue here, despite the same java environment but not the OS.

**Comment by fickludd** [comment]
@ikwattro No issue as in the bug disappeared? What about plugins or extensions - do you have any of those in your local installation?

**Comment by ikwattro** [comment]
No issue as yes, the bug do not appear. However I haven't installed the plugins on the ubuntu server while I have 5 extensions locally. Let me check on the server with the plugins.

**Comment by ikwattro** [comment]
@fickludd So, on the ubuntu server, even with the plugins installed and loaded, the issue doesnt appear.

**Comment by ikwattro** [comment]
I just tried also locally without plugins : 

```
neo4j> MATCH (b:Book)-[:CHILD]->(:Chapter)-[:CHILD]->(c)
       MATCH (c)-[:CHILD*]->(r:ReadableText)<-[:INDEXES]-(k)
       WITH r, k, count(*) AS f
       MATCH (k)-[:INDEXES]->(r2)
       WHERE r2 <> r
       RETURN r.text, r2.text, collect(distinct k.value)
       LIMIT 10;
assertion failed
neo4j>
```

**Comment by fickludd** [comment]
Hmm, I asked for more help on this, and it seems like this is actually an old bug in the slotted runtime (https://github.com/neo4j/neo4j/pull/10160/files#diff-99142750b9ec568699936e7fd156f2b5R150) which was solved in november (https://github.com/neo4j/neo4j/pull/10429). Could you confirm that this appears on a fresh `3.3.1` locally?

**Comment by ikwattro** [comment]
@fickludd Sorry for the timeloss, it seems my local neo was on 3.3.0 :(
