### ISSUE TITLE
NullPointerException while indexing

### ISSUE THREAD

**Issue by amadfida** [neo4j/neo4j#10727]
During an insert we noticed null pointer exceptions in debug.log. I don't have access to data or what was being created at the time but I do have stacktrace error that I am sharing here,

- Neo4j version: 3.1.1
- Operating system: Debian 8 (Jessie)
- API/Driver: Java driver 1.5.0

```
java.lang.NullPointerException
	at org.neo4j.kernel.api.impl.schema.ValueEncoding$4.encodeQuery(ValueEncoding.java:174)
	at org.neo4j.kernel.api.impl.schema.LuceneDocumentStructure.newSeekQuery(LuceneDocumentStructure.java:110)
	at org.neo4j.kernel.api.impl.schema.reader.SimpleIndexReader.seek(SimpleIndexReader.java:154)
	at org.neo4j.kernel.api.impl.schema.reader.SimpleIndexReader.query(SimpleIndexReader.java:104)
	at org.neo4j.kernel.impl.index.schema.fusion.FusionIndexReader.query(FusionIndexReader.java:83)
	at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.indexQuery(StateHandlingStatementOperations.java:853)
	at org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.indexQuery(ConstraintEnforcingEntityOperations.java:364)
	at org.neo4j.kernel.impl.api.OperationsFacade.indexQuery(OperationsFacade.java:232)
	at org.neo4j.cypher.internal.compiler.v3_3.generated.GeneratedExecutionPlan316835716164251Execution.accept(Unknown Source)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.compiled.CompiledExecutionResult.accept(CompiledExecutionResult.scala:53)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply$mcV$sp(ClosingExecutionResult.scala:175)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:174)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:174)
	at org.neo4j.cypher.internal.compatibility.v3_3.exceptionHandler$runSafely$.apply(exceptionHandler.scala:90)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.accept(ClosingExecutionResult.scala:174)
	at org.neo4j.bolt.v1.runtime.CypherAdapterStream.accept(CypherAdapterStream.java:76)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter$ResultHandler.onRecords(BoltMessageRouter.java:146)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.lambda$pullAll$0(BoltStateMachine.java:462)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$2.streamResult(TransactionStateMachine.java:347)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:105)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.pullAll(BoltStateMachine.java:461)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.pullAll(BoltStateMachine.java:236)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onPullAll$6(BoltMessageRouter.java:114)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:139)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.executeBatch(RunnableBoltWorker.java:132)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:97)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)
```

On the client side we get 

```
org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Unable to establish connection in 5000ms
```

We may be inserting `null` value, for a property which is indexes, but I didn't think that would cause this problem.

**Comment by chrisvest** [comment]
@amadfida Are you sure about your Neo4j 3.1.1 version? The line numbers in the stack trace don't line up with our 3.1.1 tag.

**Comment by chrisvest** [comment]
Please reopen if this is still a problem, and we can get more information on diagnosing this.
