### ISSUE TITLE
Fedora 27 cypher-shell "failed to construct terminal"

### ISSUE THREAD

**Issue by omerule** [neo4j/neo4j#10739]
After update from Fedora 26 to 27, I get an error message when starting cypher-shell

- Neo4j version: neo4j-3.3.1-1.src.rpm
- Operating system: Fedora 27 on both  32 and 64 bit (upgraded with dnf from fedora 26)
- API/Driver: I think Java cypher-shell (bolt?)
- steps:
1) Fedora 26 add Neo4j repo.
 2) Install with dnf "dnf install neo4j" 
 3) Systemd start neo4j 
 4) Set password in browser localhost:7474
 5) In bash terminal: cypher-shell normal login (no error)
 6) Upgrade Fedora 26 to 27 with commands as sudo: 
               dnf system-upgrade download --releasever=27
               dnf system-upgrade reboot
 7) Start Neo4j in terminal $ cypher-shell (error)

- Expected behavior: only login questions
- Actual behavior:
""" 
$ cypher-shell 
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
	at jline.UnixTerminal.<init>(UnixTerminal.java:65)
	at jline.UnixTerminal.<init>(UnixTerminal.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
	at jline.TerminalFactory.create(TerminalFactory.java:102)
	at jline.TerminalFactory.get(TerminalFactory.java:186)
	at jline.TerminalFactory.get(TerminalFactory.java:192)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:243)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:235)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:227)
	at org.neo4j.shell.Main.promptForText(Main.java:156)
	at org.neo4j.shell.Main.promptForNonEmptyText(Main.java:135)
	at org.neo4j.shell.Main.connectMaybeInteractively(Main.java:110)
	at org.neo4j.shell.Main.startShell(Main.java:68)
	at org.neo4j.shell.Main.main(Main.java:36)

username: 
"""
No problem if more information is needed. 

Yours kindly.
Omer the Netherlands

**Comment by ideepblue** [comment]
I met the same problem after freshly installing neo4j community edition 3.3.5 on Ubuntu 18.04.

**Comment by 0mp** [comment]
I've had the same problem while opening `cypher-shell` in an [st terminal](https://www.freshports.org/x11/sterm/). Also, I'm getting the error no matter if I'm running `cypher-shell` inside a tmux session or not.

Here's the error message:

```console
$ cypher-shell
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
        at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
        at jline.UnixTerminal.<init>(UnixTerminal.java:65)
        at jline.UnixTerminal.<init>(UnixTerminal.java:50)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
        at jline.TerminalFactory.create(TerminalFactory.java:102)
        at jline.TerminalFactory.get(TerminalFactory.java:186)
        at jline.TerminalFactory.get(TerminalFactory.java:192)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:243)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:235)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:227)
        at org.neo4j.shell.Main.promptForText(Main.java:156)
        at org.neo4j.shell.Main.promptForNonEmptyText(Main.java:135)
        at org.neo4j.shell.Main.connectMaybeInteractively(Main.java:110)
        at org.neo4j.shell.Main.startShell(Main.java:68)
        at org.neo4j.shell.Main.main(Main.java:36)

username: 
```

I do not experience this problem when using xterm without tmux. If I'm running cypher-shell in a tmux session, which has `TERM` set to `screen-256color`, then I'm getting the error. When setting `TERM` to `xterm`, however, `cypher-shell` starts just fine.

----

Details:
 * OS: FreeBSD 12.0-CURRENT r333659 amd64
 * Neo4j installed using `pkg install neo4j`
 * Neo4j version:  3.3.2

**Comment by sarmbruster** [comment]
That is fixed in `cypher-shell` via commit https://github.com/neo4j/cypher-shell/commit/ca48b68f96df5efff02d3b552dd3de7808961646.
Either build cypher-shell locally from there or await next cypher-shell release.
