### ISSUE TITLE
Retrieving properties(n) fails on basic CREATE

### ISSUE THREAD

**Issue by tuddman** [neo4j/neo4j#10858]
- Neo4j version: 3.3.1
- Operating system: (Ubuntu 16.04)
- API/Driver: (Cypher/Java bolt driver 1.5.0)
### **Steps to reproduce**
`CREATE (n:Person {name: "john"}) RETURN properties(n)`
### Expected behavior
properties of the the newly created node to be returned
### Actual behavior
- using CYPHER / Browser:
query hangs indefinitely 
- using java-bolt-driver
```
Caused by: java.io.IOException: Unknown value type: STRUCT
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackValue(PackStreamMessageFormatV1.java:518)
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackRecordMessage(PackStreamMessageFormatV1.java:464)
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:390)
	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:83)
	... 37 more
```

**Comment by Lojjs** [comment]
@tuddman This is an unfortunate, but known bug in Neo4j version 3.3.1. We have received bug reports for this and included a fix in Neo4j 3.3.2, which has just been released this morning. You can download the new version on https://neo4j.com/download/other-releases/#releases.
Best regards Louise, Neo4j Cypher team
