### ISSUE TITLE
Neo4j 3.2.2. crashed when executing bolt message failed

### ISSUE THREAD

**Issue by cloudhuang** [neo4j/neo4j#10870]
## Guidelines
Neo4j crashed for wrong cypher, from the log, Expected STRING, received: NULL (0xff). 
1. It is better to log the correspsonding cypher when throw the exception
2. Neo4j should keep running but not crashed

```
2018-01-23 00:50:09.415+0000 ERROR [o.n.b.v.t.BoltProtocolV1] Failed to handle incoming Bolt message. Connection will be closed. Unable to read message type. Error was: Wrong type received. Expected STRING, received: NULL (0xff).
org.neo4j.bolt.v1.messaging.BoltIOException: Unable to read message type. Error was: Wrong type received. Expected STRING, received: NULL (0xff).
        at org.neo4j.bolt.v1.messaging.BoltRequestMessageReader.read(BoltRequestMessageReader.java:108)
        at org.neo4j.bolt.v1.transport.BoltV1Dechunker.handleHeader(BoltV1Dechunker.java:138)
        at org.neo4j.bolt.v1.transport.BoltV1Dechunker.handle(BoltV1Dechunker.java:74)
        at org.neo4j.bolt.v1.transport.BoltProtocolV1.handle(BoltProtocolV1.java:79)
        at org.neo4j.bolt.transport.SocketTransportHandler.channelRead(SocketTransportHandler.java:62)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.neo4j.bolt.v1.packstream.PackStream$Unexpected: Wrong type received. Expected STRING, received: NULL (0xff).
        at org.neo4j.bolt.v1.packstream.PackStream$Unpacker.unpackStringHeader(PackStream.java:677)
        at org.neo4j.bolt.v1.packstream.PackStream$Unpacker.unpackUTF8(PackStream.java:686)
        at org.neo4j.bolt.v1.packstream.PackStream$Unpacker.unpackString(PackStream.java:607)
        at org.neo4j.bolt.v1.messaging.BoltRequestMessageReader.read(BoltRequestMessageReader.java:76)
        ... 18 more
```

- Neo4j version: 3.2.2
- Operating system: Ubuntu 16.04 64bit
- API/Driver:  OGM 2.1.3

**Comment by technige** [comment]
Hi @cloudhuang - can you give us some details on what you were running when this happened?

**Comment by cloudhuang** [comment]
@technige ennn, as the cypher was not appropriate logged, so unfortunately I cannot give more details except the logs above.

**Comment by technige** [comment]
Closing issue as no more information is available. Please reopen if necessary.
