### ISSUE TITLE
Neo4j plugin not working

### ISSUE THREAD

**Issue by rkaran4** [neo4j/neo4j#10937]
I get the following exception when I start neo4j server with a stored procedure jar in plugins directory.

Caused by: java.lang.VerifyError: class com.fasterxml.jackson.databind.deser.Settabl
eBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class
;
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

Apoc plugin works fine.

**Comment by rkaran4** [comment]
Solved.
I was using apoc along with my plugin, apoc was using a different version of com.fasterxml.jackson.core:jackson-databind
Excluded this dependency from build target and now it works fine with apoc.
`
<plugin>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <excludes>
                                    <exclude>com.fasterxml.jackson.core:jackson-databind</exclude>
                                </excludes>
                            </artifactSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
`
