### ISSUE TITLE
Using Java stream and driver 3.1.0 : The requested operation cannot be performed, because it has to be performed in a transaction 

### ISSUE THREAD

**Issue by straumat** [neo4j/neo4j#11038]
- Neo4j version: 3.3.3
- Operating system: Ubuntu 16.04
- API/Driver: Java neo4j-ogm-embedded-driver / neo4j-ogm-bolt-driver 3.1.0

My project is working well with driver 3.0.2 but I get an exception after moving to driver 3.1.0

On my project [blockchain2graph](https://github.com/straumat/blockchain2graph), I'm using Spring boot and I'm doing something like this : 
```
t.getInputs()
  .parallelStream()
  .forEach(vin -> {
      Optional<BitcoinTransactionOutput> originTransactionOutput = getTransactionOutputRepository().findByTxIdAndN(vin.getTxId(), vin.getvOut());
});
```
And this is the repository i'm calling : 
```
package com.oakinvest.b2g.repository.bitcoin;

import com.oakinvest.b2g.domain.bitcoin.BitcoinTransactionOutput;
import org.springframework.data.neo4j.repository.Neo4jRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * BitcoinTransactionOutput repository.
 * Created by straumat on 22/03/17.
 */
@Repository
public interface BitcoinTransactionOutputRepository extends Neo4jRepository<BitcoinTransactionOutput, Long> {

    /**
     * Find by txId and n.
     *
     * @param txId transaction id
     * @param n output
     * @return transaction output
     */
    Optional<BitcoinTransactionOutput> findByTxIdAndN(String txId, int n);

}
```
It works very well with driver 3.0.2, but when I change to driver 3.1.0, i get this error : 
```
An error occurred while processing block : The requested operation cannot be performed, because it has to be performed in a transaction. Ensure you are wrapping your operation in the appropriate transaction boilerplate and try again.
org.neo4j.kernel.impl.core.ThreadToStatementContextBridge$BridgeNotInTransactionException: The requested operation cannot be performed, because it has to be performed in a transaction. Ensure you are wrapping your operation in the appropriate transaction boilerplate and try again.
	at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.assertInUnterminatedTransaction(ThreadToStatementContextBridge.java:73) ~[neo4j-kernel-3.3.3.jar:3.3.3,13ce0dc2e5eb1d72cc4e8df41612e4ec136c83e3]
	at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.getTopLevelTransactionBoundToThisThread(ThreadToStatementContextBridge.java:107) ~[neo4j-kernel-3.3.3.jar:3.3.3,13ce0dc2e5eb1d72cc4e8df41612e4ec136c83e3]
	at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.getKernelTransactionBoundToThisThread(ThreadToStatementContextBridge.java:115) ~[neo4j-kernel-3.3.3.jar:3.3.3,13ce0dc2e5eb1d72cc4e8df41612e4ec136c83e3]
	at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.get(ThreadToStatementContextBridge.java:66) ~[neo4j-kernel-3.3.3.jar:3.3.3,13ce0dc2e5eb1d72cc4e8df41612e4ec136c83e3]
	at org.neo4j.kernel.impl.core.NodeManager$NodeActionsImpl.statement(NodeManager.java:82) ~[neo4j-kernel-3.3.3.jar:3.3.3,13ce0dc2e5eb1d72cc4e8df41612e4ec136c83e3]
	at org.neo4j.kernel.impl.core.NodeProxy.getLabels(NodeProxy.java:639) ~[neo4j-kernel-3.3.3.jar:3.3.3,13ce0dc2e5eb1d72cc4e8df41612e4ec136c83e3]
	at org.neo4j.ogm.drivers.embedded.response.EmbeddedEntityAdapter.labels(EmbeddedEntityAdapter.java:52) ~[neo4j-ogm-embedded-driver-3.1.0.jar:3.1.0]
	at org.neo4j.ogm.drivers.embedded.response.EmbeddedGraphModelAdapter.labels(EmbeddedGraphModelAdapter.java:52) ~[neo4j-ogm-embedded-driver-3.1.0.jar:3.1.0]
	at org.neo4j.ogm.result.adapter.GraphModelAdapter.buildNode(GraphModelAdapter.java:89) ~[neo4j-ogm-api-3.0.0.jar:na]
	at org.neo4j.ogm.result.adapter.GraphRowModelAdapter.adapt(GraphRowModelAdapter.java:95) ~[neo4j-ogm-api-3.0.0.jar:na]
	at org.neo4j.ogm.drivers.embedded.response.EmbeddedGraphRowModelAdapter.adapt(EmbeddedGraphRowModelAdapter.java:93) ~[neo4j-ogm-embedded-driver-3.1.0.jar:3.1.0]
	at org.neo4j.ogm.drivers.embedded.response.EmbeddedGraphRowModelAdapter.adapt(EmbeddedGraphRowModelAdapter.java:68) ~[neo4j-ogm-embedded-driver-3.1.0.jar:3.1.0]
	at org.neo4j.ogm.drivers.embedded.response.GraphRowModelResponse.next(GraphRowModelResponse.java:40) ~[neo4j-ogm-embedded-driver-3.1.0.jar:3.1.0]
	at org.neo4j.ogm.drivers.embedded.response.GraphRowModelResponse.next(GraphRowModelResponse.java:24) ~[neo4j-ogm-embedded-driver-3.1.0.jar:3.1.0]
	at org.neo4j.ogm.context.GraphRowListModelMapper.map(GraphRowListModelMapper.java:53) ~[neo4j-ogm-core-3.0.0.jar:na]
	at org.neo4j.ogm.session.delegates.LoadByTypeDelegate.loadAll(LoadByTypeDelegate.java:63) ~[neo4j-ogm-core-3.0.0.jar:na]
	at org.neo4j.ogm.session.delegates.LoadByTypeDelegate.loadAll(LoadByTypeDelegate.java:120) ~[neo4j-ogm-core-3.0.0.jar:na]
	at org.neo4j.ogm.session.Neo4jSession.loadAll(Neo4jSession.java:255) ~[neo4j-ogm-core-3.0.0.jar:na]
	at sun.reflect.GeneratedMethodAccessor186.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
	at org.springframework.data.neo4j.transaction.SharedSessionCreator$SharedSessionInvocationHandler.invoke(SharedSessionCreator.java:131) ~[spring-data-neo4j-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at com.sun.proxy.$Proxy122.loadAll(Unknown Source) ~[na:na]
	at org.springframework.data.neo4j.repository.query.GraphQueryExecution$SingleEntityExecution.execute(GraphQueryExecution.java:67) ~[spring-data-neo4j-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.data.neo4j.repository.query.derived.DerivedGraphRepositoryQuery.doExecute(DerivedGraphRepositoryQuery.java:72) ~[spring-data-neo4j-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.data.neo4j.repository.query.AbstractGraphRepositoryQuery.execute(AbstractGraphRepositoryQuery.java:51) ~[spring-data-neo4j-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:570) ~[spring-data-commons-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:554) ~[spring-data-commons-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59) ~[spring-data-commons-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) ~[spring-tx-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[spring-data-commons-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at com.sun.proxy.$Proxy132.findByTxIdAndN(Unknown Source) ~[na:na]
	at com.oakinvest.b2g.batch.bitcoin.BitcoinBatchBlocks.lambda$null$5(BitcoinBatchBlocks.java:139) ~[classes/:na]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_161]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_161]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553) ~[na:1.8.0_161]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_161]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_161]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_161]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_161]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_161]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_161]
	at com.oakinvest.b2g.batch.bitcoin.BitcoinBatchBlocks.lambda$processBlock$8(BitcoinBatchBlocks.java:136) ~[classes/:na]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_161]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553) ~[na:1.8.0_161]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_161]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[na:1.8.0_161]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[na:1.8.0_161]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_161]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_161]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_161]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_161]
```

**Comment by eebus** [comment]
Hello @straumat 
This seems to be an issue with the  neo4j-ogm-bolt-driver could you reopen this issue at https://github.com/neo4j/neo4j-ogm/issues ?
Thanks

**Comment by straumat** [comment]
Done under https://github.com/neo4j/neo4j-ogm/issues/469
Thanks.
