### ISSUE TITLE
Error in slotted runtime for complex OPTIONAL MATCH

### ISSUE THREAD

**Issue by szarnyasg** [neo4j/neo4j#11067]
As a followup to #10910, I changed to Enterprise 3.4.0.alpha08 and continued testing the new runtime.

- Neo4j version: 3.4.0.alpha08 enterprise
- Operating system: Ubuntu 16.04
- API/Driver: any

I was experimenting with LDBC queries and ran into an error with [BI query 25](https://github.com/ldbc/ldbc_snb_implementations/blob/e3e08a1a72bb74d81d183e8125eee55f8585aa7c/cypher/queries-opencypher/bi-25.cypher). I managed to trim down the query to this:

```
MATCH path=allShortestPaths((p1:Person {id: 17592186045594})-[:KNOWS*]-(p2:Person {id: 2199023256530}))
UNWIND relationships(path) AS k
WITH path, startNode(k) AS pA, endNode(k) AS pB

OPTIONAL MATCH
  (pA)<-[:HAS_CREATOR]-(c:Comment)-[:REPLY_OF]->(post:Post)-[:HAS_CREATOR]->(pB),
  (post)<-[:CONTAINER_OF]-(forum:Forum)
WHERE forum.creationDate >= 20110201000000000 AND forum.creationDate <= 20110301000000000

RETURN *
```

The error message on the UI is:

> Neo.DatabaseError.General.UnknownError
> assertion failed

The `debug.log` shows the full stacktrace:

```
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at org.neo4j.cypher.internal.runtime.slotted.SlottedExecutionContext$$anonfun$mergeWith$1.apply(SlottedExecutionContext.scala:216)
	at org.neo4j.cypher.internal.runtime.slotted.SlottedExecutionContext$$anonfun$mergeWith$1.apply(SlottedExecutionContext.scala:210)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:130)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.SlotConfiguration.foreachSlot(SlotConfiguration.scala:298)
	at org.neo4j.cypher.internal.runtime.slotted.SlottedExecutionContext.mergeWith(SlottedExecutionContext.scala:210)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.NodeRightOuterHashJoinPipe$$anonfun$internalCreateResults$1$$anonfun$apply$1.apply(NodeRightOuterHashJoinPipe.scala:43)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.NodeRightOuterHashJoinPipe$$anonfun$internalCreateResults$1$$anonfun$apply$1.apply(NodeRightOuterHashJoinPipe.scala:43)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:73)
	at scala.collection.mutable.MutableList.foreach(MutableList.scala:30)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.NodeRightOuterHashJoinPipe$$anonfun$internalCreateResults$1.apply(NodeRightOuterHashJoinPipe.scala:43)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.NodeRightOuterHashJoinPipe$$anonfun$internalCreateResults$1.apply(NodeRightOuterHashJoinPipe.scala:37)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.TraversableOnce$FlattenOps$$anon$1.hasNext(TraversableOnce.scala:464)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.ClosingIterator$$anonfun$hasNext$1.apply$mcZ$sp(ResultIterator.scala:57)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.ClosingIterator$$anonfun$hasNext$1.apply(ResultIterator.scala:55)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.ClosingIterator$$anonfun$hasNext$1.apply(ResultIterator.scala:55)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.ClosingIterator$$anonfun$failIfThrows$1.apply(ResultIterator.scala:82)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.ClosingIterator.decoratedCypherException(ResultIterator.scala:91)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.ClosingIterator.failIfThrows(ResultIterator.scala:80)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.ClosingIterator.hasNext(ResultIterator.scala:54)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.neo4j.cypher.internal.runtime.RuntimeJavaValueConverter$feedIteratorToVisitable.accept(RuntimeJavaValueConverter.scala:53)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.PipeExecutionResult.accept(PipeExecutionResult.scala:112)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply$mcV$sp(ClosingExecutionResult.scala:174)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:173)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:173)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:88)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.accept(ClosingExecutionResult.scala:173)
	at org.neo4j.bolt.v1.runtime.CypherAdapterStream.accept(CypherAdapterStream.java:76)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter$ResultHandler.onRecords(BoltMessageRouter.java:146)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.lambda$pullAll$0(BoltStateMachine.java:454)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:267)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:104)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.pullAll(BoltStateMachine.java:453)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.pullAll(BoltStateMachine.java:236)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onPullAll$6(BoltMessageRouter.java:114)
	at org.neo4j.bolt.v1.runtime.MonitoredWorkerFactory$MonitoredBoltWorker.lambda$enqueue$0(MonitoredWorkerFactory.java:82)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:150)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.executeBatch(RunnableBoltWorker.java:143)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:110)
```

The assertion error comes from https://github.com/neo4j/neo4j/blob/9348d2e7a3dfe1379e461ea9164f49d961df6cc3/enterprise/cypher/slotted-runtime/src/main/scala/org/neo4j/cypher/internal/runtime/slotted/SlottedExecutionContext.scala#L216

Similarly to the previous issue, prefixing the query with `CYPHER runtime=interpreted` makes the error go away, so this must be an issue with the compiled runtime.

Reproducing the error needs some data. The scale factor 0.1 data set of the LDBC is sufficient for this goal:
* [zipped `graph.db` (Dropbox)](https://www.dropbox.com/s/z8l7o0yellsattr/graph.db.zip?dl=0)
* [CSV files with import instructions (GitHub)](https://github.com/szarnyasg/ldbc-sf01)

I am cc-ing @alexaverbuch who helped me debug the cause of this issue.

**Comment by Lojjs** [comment]
@szarnyasg Thanks for reporting! We will have a look as soon as possible.

**Comment by henriknyman** [comment]
@szarnyasg Thanks a lot for providing the `graph.db` to reproduce it with. Very helpful!

**Comment by szarnyasg** [comment]
I tested this with the Enterprise `alpha10` release and it works fine. Thanks!
