### ISSUE TITLE
Better error message when deleting nodes that still have rels

### ISSUE THREAD

**Issue by peterneubauer** [neo4j/neo4j#1112]
when trying to delete a nodes that still has rels, see http://console.neo4j.org/?id=zff9oh

I get a 

org.neo4j.graphdb.TransactionFailureException: Unable to commit transaction

This is legit and ok. However, the real issue is reported, but 4 levels down the stack trace. For a client or user, that is too deep, and leaves the user wondering what happened.

```
2013-08-28T09:37:52.011630+00:00 app[web.1]: org.neo4j.graphdb.TransactionFailureException: Unable to commit transaction
2013-08-28T09:37:52.011811+00:00 app[web.1]:    at org.neo4j.kernel.TopLevelTransaction.finish(TopLevelTransaction.java:143)
2013-08-28T09:37:52.011811+00:00 app[web.1]:    at org.neo4j.community.console.CypherQueryExecutor.cypherQuery(CypherQueryExecutor.java:198)
2013-08-28T09:37:52.011952+00:00 app[web.1]:    at org.neo4j.community.console.CypherQueryExecutor.cypherQuery(CypherQueryExecutor.java:174)
2013-08-28T09:37:52.012042+00:00 app[web.1]:    at org.neo4j.community.console.Neo4jService.cypherQuery(Neo4jService.java:138)
2013-08-28T09:37:52.012129+00:00 app[web.1]:    at org.neo4j.community.console.ConsoleService.execute(ConsoleService.java:127)
2013-08-28T09:37:52.012219+00:00 app[web.1]:    at org.neo4j.community.console.ConsoleApplication$2.doHandle(ConsoleApplication.java:46)
2013-08-28T09:37:52.012320+00:00 app[web.1]:    at org.neo4j.community.console.Route.handle(Route.java:37)
2013-08-28T09:37:52.012397+00:00 app[web.1]:    at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:135)
2013-08-28T09:37:52.012514+00:00 app[web.1]:    at spark.servlet.SparkFilter.doFilter(SparkFilter.java:82)
2013-08-28T09:37:52.012619+00:00 app[web.1]:    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
2013-08-28T09:37:52.012767+00:00 app[web.1]:    at org.neo4j.community.console.AllowAjaxFilter.doFilter(AllowAjaxFilter.java:48)
2013-08-28T09:37:52.012767+00:00 app[web.1]:    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
2013-08-28T09:37:52.012884+00:00 app[web.1]:    at org.neo4j.community.console.GuardingRequestFilter.doFilter(GuardingRequestFilter.java:60)
2013-08-28T09:37:52.012966+00:00 app[web.1]:    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
2013-08-28T09:37:52.013928+00:00 app[web.1]:    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:474)
2013-08-28T09:37:52.013928+00:00 app[web.1]:    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
2013-08-28T09:37:52.014059+00:00 app[web.1]:    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:517)
2013-08-28T09:37:52.014238+00:00 app[web.1]:    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
2013-08-28T09:37:52.014341+00:00 app[web.1]:    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:935)
2013-08-28T09:37:52.014432+00:00 app[web.1]:    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:404)
2013-08-28T09:37:52.014522+00:00 app[web.1]:    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
2013-08-28T09:37:52.014632+00:00 app[web.1]:    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:870)
2013-08-28T09:37:52.014796+00:00 app[web.1]:    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
2013-08-28T09:37:52.014796+00:00 app[web.1]:    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
2013-08-28T09:37:52.014949+00:00 app[web.1]:    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
2013-08-28T09:37:52.014949+00:00 app[web.1]:    at org.eclipse.jetty.server.Server.handle(Server.java:346)
2013-08-28T09:37:52.014949+00:00 app[web.1]:    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
2013-08-28T09:37:52.015210+00:00 app[web.1]:    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1068)
2013-08-28T09:37:52.015328+00:00 app[web.1]:    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:807)
2013-08-28T09:37:52.015445+00:00 app[web.1]:    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:220)
2013-08-28T09:37:52.015602+00:00 app[web.1]:    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
2013-08-28T09:37:52.015682+00:00 app[web.1]:    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:520)
2013-08-28T09:37:52.015885+00:00 app[web.1]:    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
2013-08-28T09:37:52.015993+00:00 app[web.1]:    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:528)
2013-08-28T09:37:52.016096+00:00 app[web.1]:    at java.lang.Thread.run(Thread.java:722)
2013-08-28T09:37:52.016244+00:00 app[web.1]: Caused by: javax.transaction.HeuristicRollbackException: Failed to commit, transaction rolledback ---> javax.transaction.xa.XAException
2013-08-28T09:37:52.016300+00:00 app[web.1]:    at org.neo4j.kernel.impl.transaction.TxManager.commit(TxManager.java:509)
2013-08-28T09:37:52.016439+00:00 app[web.1]:    at org.neo4j.kernel.impl.transaction.TxManager.commit(TxManager.java:349)
2013-08-28T09:37:52.020065+00:00 heroku[router]: at=info method=POST path=/console/cypher host=console-test.neo4j.org fwd="212.162.171.110" dyno=web.1 connect=1ms service=20ms status=200 bytes=143
2013-08-28T09:37:52.016439+00:00 app[web.1]:    at org.neo4j.kernel.impl.api.StoreKernelTransaction.commit(StoreKernelTransaction.java:82)
2013-08-28T09:37:52.016549+00:00 app[web.1]:    at org.neo4j.kernel.impl.api.DelegatingKernelTransaction.commit(DelegatingKernelTransaction.java:51)
2013-08-28T09:37:52.016650+00:00 app[web.1]:    at org.neo4j.kernel.impl.api.StateHandlingKernelTransaction.commit(StateHandlingKernelTransaction.java:139)
2013-08-28T09:37:52.016739+00:00 app[web.1]:    at org.neo4j.kernel.impl.api.DelegatingKernelTransaction.commit(DelegatingKernelTransaction.java:51)
2013-08-28T09:37:52.016828+00:00 app[web.1]:    at org.neo4j.kernel.impl.api.LockingKernelTransaction.commit(LockingKernelTransaction.java:83)
2013-08-28T09:37:52.016917+00:00 app[web.1]:    at org.neo4j.kernel.impl.api.ReferenceCountingKernelTransaction.commit(ReferenceCountingKernelTransaction.java:67)
2013-08-28T09:37:52.017038+00:00 app[web.1]:    at org.neo4j.kernel.impl.transaction.TransactionImpl.commit(TransactionImpl.java:124)
2013-08-28T09:37:52.017161+00:00 app[web.1]:    at org.neo4j.kernel.TopLevelTransaction.finish(TopLevelTransaction.java:127)
2013-08-28T09:37:52.017397+00:00 app[web.1]:    ... 34 more
2013-08-28T09:37:52.017583+00:00 app[web.1]: Caused by: javax.transaction.xa.XAException
2013-08-28T09:37:52.017713+00:00 app[web.1]:    at org.neo4j.kernel.impl.nioneo.xa.WriteTransaction.doPrepare(WriteTransaction.java:301)
2013-08-28T09:37:52.017786+00:00 app[web.1]:    at org.neo4j.kernel.impl.transaction.xaframework.XaTransaction.prepare(XaTransaction.java:301)
2013-08-28T09:37:52.017882+00:00 app[web.1]:    at org.neo4j.kernel.impl.transaction.xaframework.XaResourceManager.prepare(XaResourceManager.java:332)
2013-08-28T09:37:52.017971+00:00 app[web.1]:    at org.neo4j.kernel.impl.transaction.xaframework.XaResourceHelpImpl.prepare(XaResourceHelpImpl.java:101)
2013-08-28T09:37:52.018057+00:00 app[web.1]:    at org.neo4j.kernel.impl.transaction.TransactionImpl.doCommit(TransactionImpl.java:512)
2013-08-28T09:37:52.018143+00:00 app[web.1]:    at org.neo4j.kernel.impl.transaction.TxManager.commit(TxManager.java:399)
2013-08-28T09:37:52.018300+00:00 app[web.1]:    ... 43 more
2013-08-28T09:37:52.018446+00:00 app[web.1]: Caused by: org.neo4j.graphdb.ConstraintViolationException: Node record Node[390,used=false,rel=699,prop=197,labels=-549755813678,heavy,dynlabels=[DynamicRecord[210,used=true,light=false(6),type=0,data=byte[6,2,9,-122,51,0],start=true,next=-1]]] still has relationships
2013-08-28T09:37:52.018535+00:00 app[web.1]:    ... 49 more
```

**Comment by chrisvest** [comment]
We now have a better error message, e.g.: `Cannot delete node<3>, because it still has relationships. To delete this node, you must first delete its relationships.`
