### ISSUE TITLE
Query hangs in cypher 3.3

### ISSUE THREAD

**Issue by davehagler** [neo4j/neo4j#11217]
Neo4j version: 3.3.3 enterprise
Operating system: CentOS 7

A query that works in previous versions of neo4j hangs in 3.3.  The query contains a SET and extract() method.  This is the query (simplified)

MATCH (a)-[]->(b) 
OPTIONAL MATCH path=(b)<-[]-(c) 
SET b.prop2 = b.prop1 
WITH a,b,extract(x in nodes(path)| x.name) as names 
RETURN a,b,names

If the SET line is removed the query works.
If the extract function is removed the query works.
If the query is prefixed with CYPHER 3.2 the query works.

With CYPHER 3.3 it hangs and never returns, with a NullPointerException in the log

```
2018-03-09 22:21:26.569+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: null, reference 4fe3e19b-569b-473f-8f23-1b93b96a3a33.
java.lang.NullPointerException
	at org.neo4j.cypher.internal.spi.v3_3.TransactionBoundQueryContext$NodeOperations.getProperty(TransactionBoundQueryContext.scala:357)
	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext$ExceptionTranslatingOperations$$anonfun$getProperty$1.apply(ExceptionTranslatingQueryContext.scala:276)
	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext$ExceptionTranslatingOperations$$anonfun$getProperty$1.apply(ExceptionTranslatingQueryContext.scala:276)
	at org.neo4j.cypher.internal.spi.v3_3.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:32)
	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:39)
	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext$ExceptionTranslatingOperations.getProperty(ExceptionTranslatingQueryContext.scala:276)
	at org.neo4j.cypher.internal.spi.v3_3.DelegatingOperations.getProperty(DelegatingQueryContext.scala:255)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.commands.expressions.Property.apply(Property.scala:39)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.commands.expressions.LiteralMap$$anonfun$apply$1.apply(LiteralMap.scala:35)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.commands.expressions.LiteralMap$$anonfun$apply$1.apply(LiteralMap.scala:34)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:137)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.commands.expressions.LiteralMap.apply(LiteralMap.scala:34)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.commands.expressions.ExtractFunction$$anon$1.apply(ExtractFunction.scala:35)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.commands.expressions.ExtractFunction$$anon$1.apply(ExtractFunction.scala:34)
	at org.neo4j.values.virtual.ListValue$TransformedListValue.writeTo(ListValue.java:480)
	at org.neo4j.bolt.v1.messaging.Neo4jPack$Packer.pack(Neo4jPack.java:86)
	at org.neo4j.bolt.v1.messaging.BoltResponseMessageWriter.onRecord(BoltResponseMessageWriter.java:75)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter$ResultHandler$1.visit(BoltMessageRouter.java:153)
	at org.neo4j.bolt.v1.runtime.CypherAdapterStream.lambda$accept$0(CypherAdapterStream.java:78)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.helpers.RuntimeJavaValueConverter$feedIteratorToVisitable.accept(RuntimeJavaValueConverter.scala:55)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.PipeExecutionResult.accept(PipeExecutionResult.scala:112)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply$mcV$sp(ClosingExecutionResult.scala:175)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:174)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:174)
	at org.neo4j.cypher.internal.compatibility.v3_3.exceptionHandler$runSafely$.apply(exceptionHandler.scala:90)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.accept(ClosingExecutionResult.scala:174)
	at org.neo4j.bolt.v1.runtime.CypherAdapterStream.accept(CypherAdapterStream.java:76)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter$ResultHandler.onRecords(BoltMessageRouter.java:146)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.lambda$pullAll$0(BoltStateMachine.java:462)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:272)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:105)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.pullAll(BoltStateMachine.java:461)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.pullAll(BoltStateMachine.java:236)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onPullAll$6(BoltMessageRouter.java:114)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:152)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.executeBatch(RunnableBoltWorker.java:145)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:110)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)
```

**Comment by MarcianoAvihay** [comment]
I have had a similar issue with a query in 3.3 community ( a query hanged) and using the CYPHER 3.2 hint made it work. my query also contained a Match, an optional Match , List filtering  , and Reduce ( toInteger(round(REDUCE(s = 0.0, x IN associated_failures | s + x.disposition))  ... Reverted back to 3.2 because of it

**Comment by sherfert** [comment]
We will have a look at this. Thanks for the report.

**Comment by fickludd** [comment]
@davehagler this was a bug related to resource management and lazy evaluation of the `extract()` construct. It should be fixed with https://github.com/neo4j/neo4j/pull/11347, which will be part of `3.3.5`.

@MarcianoAvihay Although I fixes a similar issue with `filter()`, I'm haven't verified whether this solves your issue. I can do so if you provide the full query and a minimal graph if needed.
