### ISSUE TITLE
StackOverflowError in graph-matching

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#114]
@tinwelint: 'Given the Cypher query:

start root=node(0)
match
 root-[:CATEGORY]->category-[:TWITTER_USER]->user-[:POSTED]->value,
 value<-[:VALUE]-hour<-[h]-day<-[:IDX_DAY_04]-month<-[:IDX_MONTH_05]-year<-[:IDX_YEAR_2012]-root,
 root-[:CATEGORY]->category-[:TAG]->tag,
 value-[r:TAGGED]-tag
where tag.name='tinkerpop' and category.type='TWITTER' and type(h)
=~/IDX_HOUR_.*/ return count(r)

It gives:

java.lang.StackOverflowError
        at java.util.Stack.pop(Stack.java:84)
        at org.neo4j.graphmatching.PatternFinder.traverse(PatternFinder.java:323)
        at org.neo4j.graphmatching.PatternFinder.traverse(PatternFinder.java:325)
        at org.neo4j.graphmatching.PatternFinder.traverse(PatternFinder.java:325)
        at org.neo4j.graphmatching.PatternFinder.traverse(PatternFinder.java:238)
        at org.neo4j.graphmatching.PatternFinder.traverseFromCallStack(PatternFinder.java:203)
        at org.neo4j.graphmatching.PatternFinder.extractPotentialResult(PatternFinder.java:190)
        at org.neo4j.graphmatching.PatternFinder.traverseFromCallStack(PatternFinder.java:208)
        at org.neo4j.graphmatching.PatternFinder.extractPotentialResult(PatternFinder.java:190)
        at org.neo4j.graphmatching.PatternFinder.traverseFromCallStack(PatternFinder.java:208)
        at org.neo4j.graphmatching.PatternFinder.extractPotentialResult(PatternFinder.java:190)
        ....

For a data set I do not know at the time of writing this...'

**Comment by sherfert** [comment]
Five years (after the migration) and nothing happened... Please reopen if there is something to be done, still.
