### ISSUE TITLE
Neo4j 2.3 fails to update to Neo4j 3.3.4

### ISSUE THREAD

**Issue by ct-jzarrelli** [neo4j/neo4j#11638]
- Neo4j version: 2.3.3 -> 3.3.4
- Operating system: Windows 10
- API/Driver: Java API
- Steps to reproduce: Launched the project while linked to 3.3.4 Neo4j jars while the database was still in an older store format, I had my properties file set to allow upgrade.
- Expected Behavior: Neo4j to successfully upgrade store version
- Actual Behavior: Neo4j crashes with the following error: 
```
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, D:\Neo\db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:126)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:137)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(GraphDatabaseFactory.java:130)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:107)
	at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:193)
	at database.Neo4jDatabaseInitializer.initializeDB(Neo4jDatabaseInitializer.java:39)
	... 7 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.index.labelscan.NativeLabelScanStore@433e536f' was successfully initialized, but failed to start. Please see the attached cause exception "The node label update contained unsorted label ids [2, 7, 5, 8]".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.bringToState(LifeSupport.java:315)
	at org.neo4j.kernel.lifecycle.LifeSupport.add(LifeSupport.java:248)
	at org.neo4j.kernel.lifecycle.Lifespan.add(Lifespan.java:41)
	at org.neo4j.kernel.impl.storemigration.participant.NativeLabelScanStoreMigrator.migrate(NativeLabelScanStoreMigrator.java:83)
	at org.neo4j.kernel.impl.storemigration.StoreUpgrader.migrateToIsolatedDirectory(StoreUpgrader.java:215)
	at org.neo4j.kernel.impl.storemigration.StoreUpgrader.migrateIfNeeded(StoreUpgrader.java:135)
	at org.neo4j.kernel.impl.storemigration.DatabaseMigrator.migrate(DatabaseMigrator.java:101)
	at org.neo4j.kernel.NeoStoreDataSource.upgradeStore(NeoStoreDataSource.java:577)
	at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:436)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:100)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
	... 13 more
Caused by: java.lang.IllegalArgumentException: The node label update contained unsorted label ids [2, 7, 5, 8]
	at org.neo4j.kernel.impl.index.labelscan.NativeLabelScanWriter.extractChange(NativeLabelScanWriter.java:210)
	at org.neo4j.kernel.impl.index.labelscan.NativeLabelScanWriter.flushPendingChanges(NativeLabelScanWriter.java:175)
	at org.neo4j.kernel.impl.index.labelscan.NativeLabelScanWriter.write(NativeLabelScanWriter.java:144)
	at org.neo4j.kernel.impl.api.scan.FullLabelStream.visit(FullLabelStream.java:61)
	at org.neo4j.kernel.impl.storemigration.participant.NativeLabelScanStoreMigrator$MonitoredFullLabelStream.visit(NativeLabelScanStoreMigrator.java:178)
	at org.neo4j.kernel.impl.storemigration.participant.NativeLabelScanStoreMigrator$MonitoredFullLabelStream.visit(NativeLabelScanStoreMigrator.java:164)
	at org.neo4j.kernel.impl.transaction.state.storeview.StoreViewNodeStoreScan.process(StoreViewNodeStoreScan.java:91)
	at org.neo4j.kernel.impl.transaction.state.storeview.NodeStoreScan.run(NodeStoreScan.java:74)
	at org.neo4j.kernel.impl.api.scan.FullLabelStream.applyTo(FullLabelStream.java:54)
	at org.neo4j.kernel.impl.index.labelscan.NativeLabelScanStore.start(NativeLabelScanStore.java:434)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 28 more
	Suppressed: java.lang.IllegalArgumentException: The node label update contained unsorted label ids [2, 7, 5, 8]
		at org.neo4j.kernel.impl.index.labelscan.NativeLabelScanWriter.extractChange(NativeLabelScanWriter.java:210)
		at org.neo4j.kernel.impl.index.labelscan.NativeLabelScanWriter.flushPendingChanges(NativeLabelScanWriter.java:175)
		at org.neo4j.kernel.impl.index.labelscan.NativeLabelScanWriter.close(NativeLabelScanWriter.java:270)
		at org.neo4j.kernel.impl.index.labelscan.NativeLabelScanStore.start(NativeLabelScanStore.java:435)
		... 29 more
```
From the debug log:
```
2018-04-23 22:14:53.777+0000 INFO [o.n.k.i.DiagnosticsManager] --- INITIALIZED diagnostics END ---
2018-04-23 22:14:56.773+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Selected RecordFormat:StandardV2_3[v0.A.6] record format from store D:\Neo\db
2018-04-23 22:14:56.784+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Selected format 'RecordFormat:StandardV3_2[v0.A.8]' for existing store with format 'RecordFormat:StandardV2_3[v0.A.6]'
2018-04-23 22:14:56.898+0000 INFO [o.n.k.i.s.p.StoreMigrator] Starting upgrade of database
2018-04-23 22:14:57.446+0000 INFO [o.n.k.i.s.p.StoreMigrator] Migrating Indexes (1/5):
2018-04-23 22:14:57.477+0000 INFO [o.n.k.i.s.p.StoreMigrator]   10% completed
2018-04-23 22:14:57.477+0000 INFO [o.n.k.i.s.p.StoreMigrator]   20% completed
2018-04-23 22:14:57.478+0000 INFO [o.n.k.i.s.p.StoreMigrator]   30% completed
2018-04-23 22:14:57.478+0000 INFO [o.n.k.i.s.p.StoreMigrator]   40% completed
2018-04-23 22:14:57.478+0000 INFO [o.n.k.i.s.p.StoreMigrator]   50% completed
2018-04-23 22:14:57.478+0000 INFO [o.n.k.i.s.p.StoreMigrator]   60% completed
2018-04-23 22:14:57.478+0000 INFO [o.n.k.i.s.p.StoreMigrator]   70% completed
2018-04-23 22:14:57.478+0000 INFO [o.n.k.i.s.p.StoreMigrator]   80% completed
2018-04-23 22:14:57.478+0000 INFO [o.n.k.i.s.p.StoreMigrator]   90% completed
2018-04-23 22:14:57.478+0000 INFO [o.n.k.i.s.p.StoreMigrator]   100% completed
2018-04-23 22:14:57.478+0000 INFO [o.n.k.i.s.p.StoreMigrator] Migrating Explicit indexes (2/5):
2018-04-23 22:14:57.963+0000 INFO [o.n.k.i.s.p.StoreMigrator]   10% completed
2018-04-23 22:14:57.963+0000 INFO [o.n.k.i.s.p.StoreMigrator]   20% completed
2018-04-23 22:14:57.963+0000 INFO [o.n.k.i.s.p.StoreMigrator]   30% completed
2018-04-23 22:14:57.963+0000 INFO [o.n.k.i.s.p.StoreMigrator]   40% completed
2018-04-23 22:14:57.963+0000 INFO [o.n.k.i.s.p.StoreMigrator]   50% completed
2018-04-23 22:14:57.963+0000 INFO [o.n.k.i.s.p.StoreMigrator]   60% completed
2018-04-23 22:14:57.963+0000 INFO [o.n.k.i.s.p.StoreMigrator]   70% completed
2018-04-23 22:14:57.963+0000 INFO [o.n.k.i.s.p.StoreMigrator]   80% completed
2018-04-23 22:14:57.963+0000 INFO [o.n.k.i.s.p.StoreMigrator]   90% completed
2018-04-23 22:14:57.963+0000 INFO [o.n.k.i.s.p.StoreMigrator]   100% completed
2018-04-23 22:14:57.972+0000 INFO [o.n.k.i.s.p.StoreMigrator] Migrating Store files (3/5):
2018-04-23 22:14:58.185+0000 INFO [o.n.k.i.s.p.StoreMigrator]   10% completed
2018-04-23 22:14:58.186+0000 INFO [o.n.k.i.s.p.StoreMigrator]   20% completed
2018-04-23 22:14:58.186+0000 INFO [o.n.k.i.s.p.StoreMigrator]   30% completed
2018-04-23 22:14:58.186+0000 INFO [o.n.k.i.s.p.StoreMigrator]   40% completed
2018-04-23 22:14:58.186+0000 INFO [o.n.k.i.s.p.StoreMigrator]   50% completed
2018-04-23 22:14:58.186+0000 INFO [o.n.k.i.s.p.StoreMigrator]   60% completed
2018-04-23 22:14:58.186+0000 INFO [o.n.k.i.s.p.StoreMigrator]   70% completed
2018-04-23 22:14:58.186+0000 INFO [o.n.k.i.s.p.StoreMigrator]   80% completed
2018-04-23 22:14:58.186+0000 INFO [o.n.k.i.s.p.StoreMigrator]   90% completed
2018-04-23 22:14:58.186+0000 INFO [o.n.k.i.s.p.StoreMigrator]   100% completed
2018-04-23 22:14:58.186+0000 INFO [o.n.k.i.s.p.StoreMigrator] Migrating Native label scan index (4/5):
2018-04-23 22:14:59.396+0000 INFO [o.n.k.i.DiagnosticsManager] --- STOPPING diagnostics START ---
2018-04-23 22:14:59.397+0000 INFO [o.n.k.i.DiagnosticsManager] --- STOPPING diagnostics END ---
2018-04-23 22:14:59.432+0000 INFO [o.n.k.i.f.GraphDatabaseFacadeFactory] Shutdown started
```

**Comment by ct-jzarrelli** [comment]
Upgrading to 2.3.12 first does not resolve this error - I get the exact same error message as I do when going from 2.3.3.

**Comment by chrisvest** [comment]
Hi @ct-jzarrelli. How big is the store, and what are the odds that you'll be able to share it?

**Comment by ct-jzarrelli** [comment]
I cannot share the store as it contains proprietary data, it is approximately 15GB in size. From the log:
```
2018-04-23 23:11:40.235+0000 INFO  [o.n.k.i.DiagnosticsManager]   ArrayPropertyStore v0.A.6: used=1 high=0
2018-04-23 23:11:40.236+0000 INFO  [o.n.k.i.DiagnosticsManager]   NodeStore v0.A.6: used=14205991 high=14205990
2018-04-23 23:11:40.236+0000 INFO  [o.n.k.i.DiagnosticsManager]   StringPropertyStore v0.A.6: used=42 high=41
2018-04-23 23:11:40.236+0000 INFO  [o.n.k.i.DiagnosticsManager]   PropertyIndexStore v0.A.6: used=38 high=37
2018-04-23 23:11:40.236+0000 INFO  [o.n.k.i.DiagnosticsManager]   StringPropertyStore v0.A.6: used=444530 high=444529
2018-04-23 23:11:40.236+0000 INFO  [o.n.k.i.DiagnosticsManager]   ArrayPropertyStore v0.A.6: used=13298571 high=13298570
2018-04-23 23:11:40.236+0000 INFO  [o.n.k.i.DiagnosticsManager]   PropertyStore v0.A.6: used=162595435 high=162595434
2018-04-23 23:11:40.236+0000 INFO  [o.n.k.i.DiagnosticsManager]   RelationshipStore v0.A.6: used=56938985 high=56938984
2018-04-23 23:11:40.236+0000 INFO  [o.n.k.i.DiagnosticsManager]   StringPropertyStore v0.A.6: used=3 high=2
2018-04-23 23:11:40.236+0000 INFO  [o.n.k.i.DiagnosticsManager]   RelationshipTypeStore v0.A.6: used=2 high=1
2018-04-23 23:11:40.237+0000 INFO  [o.n.k.i.DiagnosticsManager]   StringPropertyStore v0.A.6: used=21 high=20
2018-04-23 23:11:40.237+0000 INFO  [o.n.k.i.DiagnosticsManager]   LabelTokenStore v0.A.6: used=19 high=18
2018-04-23 23:11:40.237+0000 INFO  [o.n.k.i.DiagnosticsManager]   SchemaStore v0.A.6: used=60 high=59
2018-04-23 23:11:40.237+0000 INFO  [o.n.k.i.DiagnosticsManager]   RelationshipGroupStore v0.A.6: used=302329 high=302328
2018-04-23 23:11:40.237+0000 INFO  [o.n.k.i.DiagnosticsManager]   NeoStore v0.A.6: used=13 high=12
```

**Comment by MishaDemianenko** [comment]
Hi @ct-jzarrelli it looks like that somehow your node label index was unfortunatelly corrupted. And to be able to migrate it that index needs to be rebuilt.

**Please make a copy of your store before proceeding with further steps.**
In 2.3 you can find that index in your_storeDir/schema/label directory. If you will remove this directory this label-node index will be recreated next time you will start your 2.3.x database.

So if you will do the following steps:
1. Make a copy of your db.
2. Delete broken index in your_storeDir/schema/label directory.
3. Start 2.3 database on top of the store without index.
4. Stop 2.3 database.
5. Perform migration.

And now your migration should be able to perform "Migrating Native label scan index" without problems
We are sorry that it's not as smooth as it should be . And please let me know if following steps solved this.

**Comment by MishaDemianenko** [comment]
@ct-jzarrelli also i have another theory on what can be wrong here, if above will not gonna help can you please run consistency checker on top of the store you tried to migrate and provide us the output. Thx in advance!

**Comment by klaren** [comment]
@ct-jzarrelli Did any of the above solutions work for you?

**Comment by MishaDemianenko** [comment]
Closing issue because of reporter inactivity. Please feel free to reopen this issue if it's still a problem.

**Comment by niiakrong** [comment]
> @ct-jzarrelli also i have another theory on what can be wrong here, if above will not gonna help can you please run consistency checker on top of the store you tried to migrate and provide us the output. Thx in advance!

I am facing a similar challenge. Following the steps you outlined didn't solve the problem though. 
Here's the output from running the consistency checker on top of the store I tried to migrate 


[root@74811b0ef9c0 neo4j-community-3.5.11]# bin/neo4j-admin check-consistency
2020-02-27 11:53:07.982+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Selected RecordFormat:StandardV2_3[v0.A.6] record format from store /home/pos/neo4j-community-3.5.11/data/databases/graph.db
2020-02-27 11:53:07.984+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Format not configured. Selected format from the store: RecordFormat:StandardV2_3[v0.A.6]
2020-02-27 11:53:08.282+0000 ERROR [o.n.k.i.s.c.CountsTracker] Failed to open counts store file: /home/pos/neo4j-community-3.5.11/data/databases/graph.db/neostore.counts.db.a Format header/trailer has changed. Expected format:`['N', 'e', 'o', 'C', 'o', 'u', 'n', 't', 'S', 't', 'o', 'r', 'e', 0x00, 0x02, 'V']`, actual:`['N', 'e', 'o', 'C', 'o', 'u', 'n', 't', 'S', 't', 'o', 'r', 'e', 0x00, 0x01, 'V']`.
java.lang.IllegalStateException: Format header/trailer has changed. Expected format:`['N', 'e', 'o', 'C', 'o', 'u', 'n', 't', 'S', 't', 'o', 'r', 'e', 0x00, 0x02, 'V']`, actual:`['N', 'e', 'o', 'C', 'o', 'u', 'n', 't', 'S', 't', 'o', 'r', 'e', 0x00, 0x01, 'V']`.
	at org.neo4j.kernel.impl.store.kvstore.MetadataCollector$State.readFormatSpecifier(MetadataCollector.java:242)
	at org.neo4j.kernel.impl.store.kvstore.MetadataCollector$State.access$100(MetadataCollector.java:114)
	at org.neo4j.kernel.impl.store.kvstore.MetadataCollector$State$1.visit(MetadataCollector.java:121)
	at org.neo4j.kernel.impl.store.kvstore.MetadataCollector.visit(MetadataCollector.java:69)
	at org.neo4j.kernel.impl.store.kvstore.MetadataCollector.visit(MetadataCollector.java:29)
	at org.neo4j.kernel.impl.store.kvstore.KeyValueStoreFile.visitKeyValuePairs(KeyValueStoreFile.java:193)
	at org.neo4j.kernel.impl.store.kvstore.KeyValueStoreFile.scanAll(KeyValueStoreFile.java:184)
	at org.neo4j.kernel.impl.store.kvstore.KeyValueStoreFileFormat.open(KeyValueStoreFileFormat.java:288)
	at org.neo4j.kernel.impl.store.kvstore.KeyValueStoreFileFormat.openStore(KeyValueStoreFileFormat.java:79)
	at org.neo4j.kernel.impl.store.kvstore.RotationStrategy.open(RotationStrategy.java:66)
	at org.neo4j.kernel.impl.store.kvstore.DeadState$Stopped.initialize(DeadState.java:128)
	at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore.init(AbstractKeyValueStore.java:185)
	at org.neo4j.kernel.impl.store.NeoStores.createCountStore(NeoStores.java:652)
	at org.neo4j.kernel.impl.store.StoreType$15.open(StoreType.java:148)
	at org.neo4j.kernel.impl.store.StoreType$15.open(StoreType.java:143)
	at org.neo4j.kernel.impl.store.NeoStores.openStore(NeoStores.java:264)
	at org.neo4j.kernel.impl.store.NeoStores.getOrCreateStore(NeoStores.java:309)
	at org.neo4j.kernel.impl.store.NeoStores.<init>(NeoStores.java:150)
	at org.neo4j.kernel.impl.store.StoreFactory.openNeoStores(StoreFactory.java:129)
	at org.neo4j.kernel.impl.store.StoreFactory.openAllNeoStores(StoreFactory.java:83)
	at org.neo4j.consistency.ConsistencyCheckService.runFullConsistencyCheck(ConsistencyCheckService.java:253)
	at org.neo4j.consistency.ConsistencyCheckService.runFullConsistencyCheck(ConsistencyCheckService.java:168)
	at org.neo4j.consistency.CheckConsistencyCommand.execute(CheckConsistencyCommand.java:204)
	at org.neo4j.commandline.admin.AdminTool.execute(AdminTool.java:127)
	at org.neo4j.commandline.admin.AdminTool.main(AdminTool.java:51)
2020-02-27 11:53:08.285+0000 ERROR [o.n.k.i.s.c.CountsTracker] Failed to open counts store file: /home/pos/neo4j-community-3.5.11/data/databases/graph.db/neostore.counts.db.b Format header/trailer has changed. Expected format:`['N', 'e', 'o', 'C', 'o', 'u', 'n', 't', 'S', 't', 'o', 'r', 'e', 0x00, 0x02, 'V']`, actual:`['N', 'e', 'o', 'C', 'o', 'u', 'n', 't', 'S', 't', 'o', 'r', 'e', 0x00, 0x01, 'V']`.
java.lang.IllegalStateException: Format header/trailer has changed. Expected format:`['N', 'e', 'o', 'C', 'o', 'u', 'n', 't', 'S', 't', 'o', 'r', 'e', 0x00, 0x02, 'V']`, actual:`['N', 'e', 'o', 'C', 'o', 'u', 'n', 't', 'S', 't', 'o', 'r', 'e', 0x00, 0x01, 'V']`.
	at org.neo4j.kernel.impl.store.kvstore.MetadataCollector$State.readFormatSpecifier(MetadataCollector.java:242)
	at org.neo4j.kernel.impl.store.kvstore.MetadataCollector$State.access$100(MetadataCollector.java:114)
	at org.neo4j.kernel.impl.store.kvstore.MetadataCollector$State$1.visit(MetadataCollector.java:121)
	at org.neo4j.kernel.impl.store.kvstore.MetadataCollector.visit(MetadataCollector.java:69)
	at org.neo4j.kernel.impl.store.kvstore.MetadataCollector.visit(MetadataCollector.java:29)
	at org.neo4j.kernel.impl.store.kvstore.KeyValueStoreFile.visitKeyValuePairs(KeyValueStoreFile.java:193)
	at org.neo4j.kernel.impl.store.kvstore.KeyValueStoreFile.scanAll(KeyValueStoreFile.java:184)
	at org.neo4j.kernel.impl.store.kvstore.KeyValueStoreFileFormat.open(KeyValueStoreFileFormat.java:288)
	at org.neo4j.kernel.impl.store.kvstore.KeyValueStoreFileFormat.openStore(KeyValueStoreFileFormat.java:79)
	at org.neo4j.kernel.impl.store.kvstore.RotationStrategy.open(RotationStrategy.java:66)
	at org.neo4j.kernel.impl.store.kvstore.DeadState$Stopped.initialize(DeadState.java:128)
	at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore.init(AbstractKeyValueStore.java:185)
	at org.neo4j.kernel.impl.store.NeoStores.createCountStore(NeoStores.java:652)
	at org.neo4j.kernel.impl.store.StoreType$15.open(StoreType.java:148)
	at org.neo4j.kernel.impl.store.StoreType$15.open(StoreType.java:143)
	at org.neo4j.kernel.impl.store.NeoStores.openStore(NeoStores.java:264)
	at org.neo4j.kernel.impl.store.NeoStores.getOrCreateStore(NeoStores.java:309)
	at org.neo4j.kernel.impl.store.NeoStores.<init>(NeoStores.java:150)
	at org.neo4j.kernel.impl.store.StoreFactory.openNeoStores(StoreFactory.java:129)
	at org.neo4j.kernel.impl.store.StoreFactory.openAllNeoStores(StoreFactory.java:83)
	at org.neo4j.consistency.ConsistencyCheckService.runFullConsistencyCheck(ConsistencyCheckService.java:253)
	at org.neo4j.consistency.ConsistencyCheckService.runFullConsistencyCheck(ConsistencyCheckService.java:168)
	at org.neo4j.consistency.CheckConsistencyCommand.execute(CheckConsistencyCommand.java:204)
	at org.neo4j.commandline.admin.AdminTool.execute(AdminTool.java:127)
	at org.neo4j.commandline.admin.AdminTool.main(AdminTool.java:51)
unexpected error: Component 'org.neo4j.kernel.impl.index.labelscan.NativeLabelScanStore@4082ba93' failed to initialize. Please see the attached cause exception "/home/pos/neo4j-community-3.5.11/data/databases/graph.db/neostore.labelscanstore.db: Cannot map non-existing file".
