### ISSUE TITLE
Better error message for unsuccessful deletion

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#117]
@wingy: 'When deleting a node that has a relationship to another node you will get an error message telling the transaction failed.

It would be better if it told which relationships must be deleted to be able to delete the node.'

**Comment by tinwelint** [comment]
@kurijov Nowadays there will be an exception like:

```
org.neo4j.graphdb.ConstraintViolationException: Cannot delete node<0>, because it still has relationships. To delete this node, you must first delete its relationships.
	at org.neo4j.kernel.impl.coreapi.TopLevelTransaction.close(TopLevelTransaction.java:92)
       ...<left out for brevity in this context>...
Caused by: org.neo4j.kernel.api.exceptions.ConstraintViolationTransactionFailureException: Cannot delete node<0>, because it still has relationships. To delete this node, you must first delete its relationships.
	at org.neo4j.kernel.impl.transaction.state.IntegrityValidator.validateNodeRecord(IntegrityValidator.java:53)
	at org.neo4j.kernel.impl.transaction.state.TransactionRecordState.extractCommands(TransactionRecordState.java:166)
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.createCommands(RecordStorageEngine.java:330)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:552)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:459)
	at org.neo4j.kernel.api.KernelTransaction.close(KernelTransaction.java:138)
	at org.neo4j.kernel.impl.coreapi.TopLevelTransaction.close(TopLevelTransaction.java:80)
	... 26 more
```

it doesn't include which relationships because it may potentially be quite a lot, couldn't it?
