### ISSUE TITLE
Import Error: Cursor org.neo4j.io.pagecache.impl.muninn.MuninnWritePageCursor

### ISSUE THREAD

**Issue by dterg** [neo4j/neo4j#11888]
- Neo4j version: 3.4.0
- Operating system: Windows 10 64 bit
- Neo4j Desktop: 1.1.2

Using the bulk csv import through neo4j desktop generated this error. As you may also see from the timings this importing had taken >20 hours. I had upgraded from neo4j 3.3.4 to attempt to get away with the slow speeds. Not sure if this error is related to the slow importing, but the full details are on [stackoverflow](https://stackoverflow.com/questions/50552882/neo4j-bulk-import-doesnt-work-for-big-datasets)

```
C:\Users\D\.Neo4jDesktop\neo4jDatabases\database-d6438069-dd9b-435c-bbc1-83e313cdc77f\installation-3.4.0>SET DATA=D:\Neo4jdb\data

C:\Users\D\.Neo4jDesktop\neo4jDatabases\database-d6438069-dd9b-435c-bbc1-83e313cdc77f\installation-3.4.0>.\bin\neo4j-admin import ^
More? --mode=csv ^
More? --database=association_graph.db ^
More? --ignore-duplicate-nodes true ^
More? --nodes %DATA%\nodes_assocs.csv ^
More? --nodes %DATA%\nodes_docs_fixed.csv ^
More? --nodes %DATA%\nodes_entities_dedup.csv ^
More? --nodes %DATA%\nodes_sents.csv ^
More? --relationships %DATA%\edges_IN_ASSOC.csv ^
More? --relationships %DATA%\edges_IN_DOC.csv ^
More? --relationships %DATA%\edges_IN_SENT.csv

WARNING: This command does not appear to be running with administrative rights.  Some commands may fail e.g. Start/Stop

Neo4j version: 3.4.0

Importing the contents of these files into D:\Neo4jdb\databases\association_graph.db:
Nodes:

.\bin\neo4j-admin import ^

--mode=csv ^
--database=association_graph.db ^
--ignore-duplicate-nodes true ^
--nodes D:\Neo4jdb\data\nodes_assoc.csv ^
--nodes D:\Neo4jdb\data\nodes_article.csv ^
--nodes D:\Neo4jdb\data\nodes_term.csv ^
--nodes D:\Neo4jdb\data\nodes_chunk.csv ^
--relationships %DATA%\edges_IN_ASSOC.csv ^
--relationships %DATA%\edges_IN_ARTICLE.csv ^
--relationships %DATA%\edges_IN_CHUNK.csv

Available resources:
  Total machine memory: 63.91 GB
  Free machine memory: 54.02 GB
  Max heap memory : 14.20 GB
  Processors: 12
  Configured max memory: 44.74 GB
  High-IO: false

Import starting 2018-05-28 18:28:00.474+0100
  Estimated number of nodes: 653.00 M
  Estimated number of node properties: 1.01 G
  Estimated number of relationships: 641.45 M
  Estimated number of relationship properties: 0.00
  Estimated disk space usage: 104.70 GB
  Estimated required memory usage: 9.02 GB

InteractiveReporterInteractions command list (end with ENTER):
  c: Print more detailed information about current stage
  i: Print more detailed information

(1/4) Node import 2018-05-28 18:28:00.642+0100
  Estimated number of nodes: 653.00 M
  Estimated disk space usage: 84.39 GB
  Estimated required memory usage: 9.02 GB
.......... .......... .......... .......... .......... 5%
.......... .......... .......... .......... .......... 10%
.......... .......... .......... .......... .......... 15%
.......... .......... .......... .......... .......... 20%
.......... .......... .......... .......... .......... 25%
.......... .......... .......... .......... .......... 30%
.......... .......... .......... .......... .......... 35%
.......... .......... .......... .......... .......... 40%
.......... .......... .......... .......... .......... 45%
.......... .......... .......... .......... .......... 50%
.......... .......... .......... .......... .......... 55%
.......... .......... .......... .......... .......... 60%
.......... .......... .......... .......... .......... 65%
.......... .......... .......... .......... .......... 70%
.......... .......... .......... .......... .......... 75%
.......... .......... .......... .......... .......... 80%
.......... .......... .......... .......... .......... 85%
..Exception in thread "Thread-8" java.lang.RuntimeException: java.lang.IllegalStateException: Cursor org.neo4j.io.pagecache.impl.muninn.MuninnWritePageCurso
r@4b7148ec access out of bounds, page id 11, offset 0
        at org.neo4j.unsafe.impl.batchimport.staging.AbstractStep.issuePanic(AbstractStep.java:150)
        at org.neo4j.unsafe.impl.batchimport.staging.AbstractStep.issuePanic(AbstractStep.java:142)
        at org.neo4j.unsafe.impl.batchimport.staging.LonelyProcessingStep.lambda$receive$0(LonelyProcessingStep.java:58)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Cursor org.neo4j.io.pagecache.impl.muninn.MuninnWritePageCursor@4b7148ec access out of bounds, page id 11, offse
t 0
        at org.neo4j.unsafe.impl.batchimport.cache.PageCacheNumberArray.checkBounds(PageCacheNumberArray.java:185)
        at org.neo4j.unsafe.impl.batchimport.cache.PageCacheByteArray.setShort(PageCacheByteArray.java:292)
        at org.neo4j.unsafe.impl.batchimport.cache.DynamicByteArray.setShort(DynamicByteArray.java:136)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.StringCollisionValues.add(StringCollisionValues.java:69)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.EncodingIdMapper.buildCollisionInfo(EncodingIdMapper.java:508)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.EncodingIdMapper.prepare(EncodingIdMapper.java:237)
        at org.neo4j.unsafe.impl.batchimport.IdMapperPreparationStep.process(IdMapperPreparationStep.java:56)
        at org.neo4j.unsafe.impl.batchimport.staging.LonelyProcessingStep.lambda$receive$0(LonelyProcessingStep.java:53)
        ... 1 more
........ .......... .......... .......... .......... 90%
.......... .......... .......... .......... .......... 95%
.......... .......... .......... .......... .......... 100%


IMPORT DONE in 21h 24m 620ms.
Data statistics is not available.
Peak memory usage: 5.91 GB
Import error: Cursor org.neo4j.io.pagecache.impl.muninn.MuninnWritePageCursor@4b7148ec access out of bounds, page id 11, offset 0
Caused by:Cursor org.neo4j.io.pagecache.impl.muninn.MuninnWritePageCursor@4b7148ec access out of bounds, page id 11, offset 0
java.lang.IllegalStateException: Cursor org.neo4j.io.pagecache.impl.muninn.MuninnWritePageCursor@4b7148ec access out of bounds, page id 11, offset 0
        at org.neo4j.unsafe.impl.batchimport.cache.PageCacheNumberArray.checkBounds(PageCacheNumberArray.java:185)
        at org.neo4j.unsafe.impl.batchimport.cache.PageCacheByteArray.setShort(PageCacheByteArray.java:292)
        at org.neo4j.unsafe.impl.batchimport.cache.DynamicByteArray.setShort(DynamicByteArray.java:136)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.StringCollisionValues.add(StringCollisionValues.java:69)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.EncodingIdMapper.buildCollisionInfo(EncodingIdMapper.java:508)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.EncodingIdMapper.prepare(EncodingIdMapper.java:237)
        at org.neo4j.unsafe.impl.batchimport.IdMapperPreparationStep.process(IdMapperPreparationStep.java:56)
        at org.neo4j.unsafe.impl.batchimport.staging.LonelyProcessingStep.lambda$receive$0(LonelyProcessingStep.java:53)
        at java.lang.Thread.run(Thread.java:748)

WARNING Import failed. The store files in D:\Neo4jdb\databases\association_graph.db are left as they are, although they are likely in an unusable state. Sta
rting a database on these store files will likely fail or observe inconsistent records so start at your own risk or delete the store manually
java.lang.IllegalStateException: Cursor org.neo4j.io.pagecache.impl.muninn.MuninnWritePageCursor@4b7148ec access out of bounds, page id 11, offset 0
        at org.neo4j.unsafe.impl.batchimport.cache.PageCacheNumberArray.checkBounds(PageCacheNumberArray.java:185)
        at org.neo4j.unsafe.impl.batchimport.cache.PageCacheByteArray.setShort(PageCacheByteArray.java:292)
        at org.neo4j.unsafe.impl.batchimport.cache.DynamicByteArray.setShort(DynamicByteArray.java:136)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.StringCollisionValues.add(StringCollisionValues.java:69)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.EncodingIdMapper.buildCollisionInfo(EncodingIdMapper.java:508)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.EncodingIdMapper.prepare(EncodingIdMapper.java:237)
        at org.neo4j.unsafe.impl.batchimport.IdMapperPreparationStep.process(IdMapperPreparationStep.java:56)
        at org.neo4j.unsafe.impl.batchimport.staging.LonelyProcessingStep.lambda$receive$0(LonelyProcessingStep.java:53)
        at java.lang.Thread.run(Thread.java:748)
unexpected error: Cursor org.neo4j.io.pagecache.impl.muninn.MuninnWritePageCursor@4b7148ec access out of bounds, page id 11, offset 0
```

**Comment by tinwelint** [comment]
The node cache for your import should fit nicely in memory (as the importer says it requires 9GiB for it), but for some reason it opts for pagecache-backed caching, which slows down your import significantly. Also there seems to be an issue with the collision value handling when using that caching strategy that has to be fixed.

I'll see if I can add some output as to which caching strategy it chooses and why when I'm at it.

**Comment by tinwelint** [comment]
@dterg do you have very large node IDs?

**Comment by tinwelint** [comment]
I managed to reproduce this. Fix coming shortly, and should go into some upcoming 3.4.x patch release.

**Comment by dterg** [comment]
Thank you and sorry but don’t have access to this at the moment. Can provide more details if required once I’m back from vacation.
