### ISSUE TITLE
Neo4j 3.4 does not start on Oracle 8/Ubuntu  with plugins present

### ISSUE THREAD

**Issue by Adarsh-kumar** [neo4j/neo4j#11914]
I am on ubuntu (16.04) and running Neo4j (3.4.0, from tarball), and using Java 8 (HotSpot 1.8.0_171).

I have the following plugins:
1. graphaware-nlp-3.4.0.52.8.jar
2. nlp-stanfordnlp-3.4.0.52.8.jar
3. graphaware-server-enterprise-all-3.4.0.52.jar

I get the following error on startup:
~~~~Active database: graph.db
Directories in use:
  home:         /home/ad/neo4j-community-3.4.0
  config:       /home/ad/neo4j-community-3.4.0/conf
  logs:         /home/ad/neo4j-community-3.4.0/logs
  plugins:      /home/ad/neo4j-community-3.4.0/plugins
  import:       /home/ad/neo4j-community-3.4.0/import
  data:         /home/ad/neo4j-community-3.4.0/data
  certificates: /home/ad/neo4j-community-3.4.0/certificates
  run:          /home/ad/neo4j-community-3.4.0/run
Starting Neo4j.
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
2018-06-01 10:27:19.089+0000 INFO  ======== Neo4j 3.4.0 ========
2018-06-01 10:27:19.115+0000 INFO  Starting...
2018-06-01 10:27:20.737+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2018-06-01 10:27:20.739+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime enabled, bootstrapping...
2018-06-01 10:27:20.755+0000 INFO [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 1, ID NLP, using com.graphaware.nlp.module.NLPBootstrapper
2018-06-01 10:27:20.807+0000 INFO  Registering module NLP with GraphAware Runtime.
2018-06-01 10:27:20.811+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime bootstrapped, starting the Runtime...
2018-06-01 10:27:24.105+0000 INFO  Shutting down GraphAware Runtime... 
2018-06-01 10:27:24.105+0000 INFO  Shutting down module NLP
2018-06-01 10:27:24.105+0000 INFO  Terminating task scheduler...
2018-06-01 10:27:24.106+0000 INFO  Task scheduler terminated successfully.
2018-06-01 10:27:24.106+0000 INFO  GraphAware Runtime shut down.
2018-06-01 10:27:24.109+0000 ERROR [c.g.r.b.RuntimeKernelExtension] Could not start GraphAware Runtime because the database didn't get to a usable state within 5 minutes.
2018-06-01 10:27:24.115+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@55fc6344' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@55fc6344' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@55fc6344' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@55fc6344' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
	... 3 more
....
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@149162a4' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
	... 9 more
Caused by: java.lang.UnsupportedClassVersionError: module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:137)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:114)
	at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
	at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:87)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:78)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:323)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 11 more
2018-06-01 10:27:24.116+0000 INFO  Neo4j Server shutdown initiated by request
~~~~~

This seems to be a class version error, where the library has been compiled against Java 9. However, Oracle Java 9 is no longer supported, and Neo4j does not work with OpenJDK Java 9. And Neo4j does not work with higher versions (Oracle Java 10).

**Without the plugins, it works.**
Please advise.

**Comment by chrisvest** [comment]
Java 9 class files just won't work in a Java 8 JVM. That's what you have to solve. Either run on Java 9, or try your luck on Java 10, or have the plugin compiled with Java 8, or don't use that plugin.
