### ISSUE TITLE
Neo4j 3.4.1 on ubuntu 14.04 upgrade fails

### ISSUE THREAD

**Issue by mkrogh** [neo4j/neo4j#11942]
- Neo4j version: 3.4.1  (from http://debian.neo4j.org/)
- Operating system: Ubuntu 14.04
- Java version "1.8.0_171"

### Steps to reproduce

- Upgrade from `3.3.3` to `3.4.1` using apt-get upgrade.

### Expected behavior

The upgrade should just work.

### Actual behavior

When starting the neo4j service you get an error:

```
2018-06-13 06:54:05.826+0000 WARN  WARNING! Deprecated configuration options used. See manual for details
2018-06-13 06:54:05.830+0000 WARN  dbms.allow_format_migration has been replaced with dbms.allow_upgrade.
2018-06-13 06:54:05.878+0000 INFO  ======== Neo4j 3.4.1 ========
2018-06-13 06:54:05.930+0000 INFO  Starting...
2018-06-13 06:54:06.001+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@358c99f5' w
as successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.scheduler.JobScheduler$Group.threadName()Ljava/lang/St
ring;". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@358c99f5' was successfully initialized, but failed to start.
Please see the attached cause exception "org.neo4j.scheduler.JobScheduler$Group.threadName()Ljava/lang/String;".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@358c99f5' was successfully i
nitialized, but failed to start. Please see the attached cause exception "org.neo4j.scheduler.JobScheduler$Group.threadName()Ljava/lang/String;".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:219)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@358c99f5' was successfully initial
ized, but failed to start. Please see the attached cause exception "org.neo4j.scheduler.JobScheduler$Group.threadName()Ljava/lang/String;".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211)
        ... 3 more
Caused by: java.lang.NoSuchMethodError: org.neo4j.scheduler.JobScheduler$Group.threadName()Ljava/lang/String;
        at org.neo4j.kernel.impl.scheduler.GroupedDaemonThreadFactory.newThread(GroupedDaemonThreadFactory.java:43)
        at org.neo4j.kernel.impl.scheduler.CentralJobScheduler.<init>(CentralJobScheduler.java:80)
        at org.neo4j.kernel.impl.factory.PlatformModule.createJobScheduler(PlatformModule.java:304)
        at org.neo4j.kernel.impl.factory.PlatformModule.<init>(PlatformModule.java:150)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.createPlatform(GraphDatabaseFacadeFactory.java:245)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:157)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:125)
        at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 5 more
2018-06-13 06:54:06.008+0000 INFO  Neo4j Server shutdown initiated by request
nohup: ignoring input
```

### Other info

Even when you delete the `graph.db` directory it still fails with:

```
2018-06-13 08:37:31.739+0000 INFO  ======== Neo4j 3.4.1 ========
2018-06-13 08:37:31.795+0000 INFO  Starting...
2018-06-13 08:37:31.870+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@14ec4505' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.scheduler.JobScheduler$Group.threadName()Ljava/lang/String;". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@14ec4505' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.scheduler.JobScheduler$Group.threadName()Ljava/lang/String;".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@14ec4505' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.scheduler.JobScheduler$Group.threadName()Ljava/lang/String;".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:219)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@14ec4505' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.scheduler.JobScheduler$Group.threadName()Ljava/lang/String;".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211)
        ... 3 more
Caused by: java.lang.NoSuchMethodError: org.neo4j.scheduler.JobScheduler$Group.threadName()Ljava/lang/String;
        at org.neo4j.kernel.impl.scheduler.GroupedDaemonThreadFactory.newThread(GroupedDaemonThreadFactory.java:43)
        at org.neo4j.kernel.impl.scheduler.CentralJobScheduler.<init>(CentralJobScheduler.java:80)
        at org.neo4j.kernel.impl.factory.PlatformModule.createJobScheduler(PlatformModule.java:304)
        at org.neo4j.kernel.impl.factory.PlatformModule.<init>(PlatformModule.java:150)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.createPlatform(GraphDatabaseFacadeFactory.java:245)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:157)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:125)
        at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 5 more
2018-06-13 08:37:31.880+0000 INFO  Neo4j Server shutdown initiated by request
```

**Comment by gacra** [comment]
Hi, I had an error similar to yours when upgrading to version 3.4.1. For me, it worked to remove a plugin I had in Neo4j (which luckily I was not using anymore, but I had left the .jar in the plugins folder).
While people who really know Neo4j do not show up, I think it's worth trying to delete the plugins as a test.

**Comment by mkrogh** [comment]
Hmm weird. I am not using any plugins though, it is just a vanilla install of neo4j that has been upgraded from 3.2.x to 3.3.x and now fails on 3.4.0/3.4.1.

I might just try and do a full purge and reinstall to see if that fixes the problem.

**Comment by mkrogh** [comment]
Ok doing a `sudo apt-get remove --purge neo4j` and then installing neo4j again seems to have worked.
