### ISSUE TITLE
Creation of index fails with java.io.IOException:org.neo4j.index.internal.gbptree.TreeInconsistencyException: Some internal problem causing out of bounds: pageId:324521   

### ISSUE THREAD

**Issue by codyAnivive** [neo4j/neo4j#11966]
The creation of large string unique constraint fails with java.io.IOException: org.neo4j.index.internal.gbptree.TreeInconsistencyException: Some internal problem causing out of bounds: pageId:324521

I have attempted to create the unique constraint several times and it fails consistently. The pageID number that is referenced as out of bounds changes every time the constraint creation is attempted. 

In order to make sure it was not an issue with unique constraint I also attempt to only create an index without the unique constraint however the index creation fails with the same error.

- Neo4j version: 3.4.1
- Operating system: openjdk:8-jre-alpine (docker container)
-Steps to Reproduce
  1. Seed fresh copy of database after store-utils repair without indexes 
  2. Attempt to create unique constraint on large string field (large number of nodes but max string size is under 1000 characters) 
  3. Index creation required for constraint fails 

- Expected behavior
   Index is created 
- Actual behavior
   Index creation fails 

Stack trace: 
2018-07-10 04:58:41.999+0000 ERROR [o.n.k.i.a.i.IndexPopulationJob] Failed to populate index: [:FailedNode(property) [provider: {key=lucene+native, version=2.0}]] org.neo4j.index.internal.gbptree.TreeInconsistencyException: Some intern
java.io.IOException: org.neo4j.index.internal.gbptree.TreeInconsistencyException: Some internal problem causing out of bounds: pageId:324521                                                                                                   
        at org.neo4j.kernel.impl.index.schema.NativeSchemaIndexPopulator.applyWithWorkSync(NativeSchemaIndexPopulator.java:251)                                                                                                                
        at org.neo4j.kernel.impl.index.schema.NativeSchemaIndexPopulator.add(NativeSchemaIndexPopulator.java:153)                                                                                                                              
        at org.neo4j.kernel.impl.index.schema.fusion.FusionIndexPopulator.add(FusionIndexPopulator.java:82)                                                                                                                                    
        at org.neo4j.kernel.impl.api.index.BatchingMultipleIndexPopulator.lambda$flush$2(BatchingMultipleIndexPopulator.java:167)                                                                                                              
        at java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy.rejectedExecution(ThreadPoolExecutor.java:2022)                                                                                                                            
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)                                                                                                                                                         
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)                                                                                                                                                       
        at org.neo4j.kernel.impl.api.index.BatchingMultipleIndexPopulator.flush(BatchingMultipleIndexPopulator.java:163)                                                                                                                       
        at org.neo4j.kernel.impl.api.index.MultipleIndexPopulator$IndexPopulation.onUpdate(MultipleIndexPopulator.java:558)                                                                                                                    
        at org.neo4j.kernel.impl.api.index.MultipleIndexPopulator$IndexPopulation.access$1000(MultipleIndexPopulator.java:481)                                                                                                                 
        at org.neo4j.kernel.impl.api.index.MultipleIndexPopulator$NodePopulationVisitor.add(MultipleIndexPopulator.java:634)                                                                                                                   
        at org.neo4j.kernel.impl.api.index.MultipleIndexPopulator$NodePopulationVisitor.visit(MultipleIndexPopulator.java:623)                                                                                                                 
        at org.neo4j.kernel.impl.api.index.MultipleIndexPopulator$NodePopulationVisitor.visit(MultipleIndexPopulator.java:617)                                                                                                                 
        at org.neo4j.kernel.impl.transaction.state.storeview.StoreViewNodeStoreScan.process(StoreViewNodeStoreScan.java:117)                                                                                                                   
        at org.neo4j.kernel.impl.transaction.state.storeview.NodeStoreScan.run(NodeStoreScan.java:74)                                                                                                                                          
        at org.neo4j.kernel.impl.api.index.MultipleIndexPopulator$DelegatingStoreScan.run(MultipleIndexPopulator.java:651)                                                                                                                     
        at org.neo4j.kernel.impl.api.index.MultipleIndexPopulator$1.run(MultipleIndexPopulator.java:172)                                                                                                                                       
        at org.neo4j.kernel.impl.api.index.MultipleIndexPopulator$DelegatingStoreScan.run(MultipleIndexPopulator.java:651)                                                                                                                     
        at org.neo4j.kernel.impl.api.index.BatchingMultipleIndexPopulator$BatchingStoreScan.run(BatchingMultipleIndexPopulator.java:279)                                                                                                       
        at org.neo4j.kernel.impl.api.index.IndexPopulationJob.indexAllNodes(IndexPopulationJob.java:134)                                                                                                                                       
        at org.neo4j.kernel.impl.api.index.IndexPopulationJob.run(IndexPopulationJob.java:107)                                                                                                                                                 
        at org.neo4j.kernel.impl.api.index.IndexPopulationJobController$IndexPopulationJobWrapper.run(IndexPopulationJobController.java:82)                                                                                                    
        at org.neo4j.kernel.impl.scheduler.ThreadPool.lambda$submit$0(ThreadPool.java:58)                                                                                                                                                      
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                                                                                                                                             
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                                                                                                            
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)                                                                                                                                                     
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)                                                                                                                                                     
        at java.lang.Thread.run(Thread.java:748)                                                                                                                                                                                               
Caused by: org.neo4j.index.internal.gbptree.TreeInconsistencyException: Some internal problem causing out of bounds: pageId:324521                                                                                                             
        at org.neo4j.index.internal.gbptree.PageCursorUtil.checkOutOfBounds(PageCursorUtil.java:154)                                                                                                                                           
        at org.neo4j.index.internal.gbptree.GBPTree$SingleWriter.merge(GBPTree.java:1203)                                                                                                                                                      
        at org.neo4j.kernel.impl.index.schema.NativeSchemaIndexUpdater.processAdd(NativeSchemaIndexUpdater.java:132)                                                                                                                           
        at org.neo4j.kernel.impl.index.schema.NativeSchemaIndexUpdater.processUpdate(NativeSchemaIndexUpdater.java:86)                                                                                                                         
        at org.neo4j.kernel.impl.index.schema.NativeSchemaIndexPopulator$IndexUpdateApply.process(NativeSchemaIndexPopulator.java:328)                                                                                                         
        at org.neo4j.kernel.impl.index.schema.NativeSchemaIndexPopulator$IndexUpdateWork.apply(NativeSchemaIndexPopulator.java:355)                                                                                                            
        at org.neo4j.kernel.impl.index.schema.NativeSchemaIndexPopulator$IndexUpdateWork.apply(NativeSchemaIndexPopulator.java:334)                                                                                                            
        at org.neo4j.concurrent.WorkSync.doSynchronizedWork(WorkSync.java:231)                                                                                                                                                                 
        at org.neo4j.concurrent.WorkSync.tryDoWork(WorkSync.java:157)                                                                                                                                                                          
        at org.neo4j.concurrent.WorkSync.apply(WorkSync.java:91)                                                                                                                                                                               
        at org.neo4j.kernel.impl.index.schema.NativeSchemaIndexPopulator.applyWithWorkSync(NativeSchemaIndexPopulator.java:238)                                                                                                                
        ... 27 more

**Comment by codyAnivive** [comment]
Following suggestions from andrew bowman I attempted index creation with lucene+native-1.0 which successfully created the constraint and accompanying index

**Comment by tinwelint** [comment]
This is a bug, have been reproduced and will be fixed as part of an upcoming 3.4.x release. I'll keep you posted.
