### ISSUE TITLE
Store and its lock file has been locked by another process

### ISSUE THREAD

**Issue by mafshin** [neo4j/neo4j#11971]
- Neo4j Desktop version: 1.1.7
- Neo4j Version: 3.3.5
- Operating system: Windows 10 64bit

**Steps to reproduce**
- Expected behavior: Neo4j db instance must run
- Actual behavior: 'Database failed to start, Startup timed out'

My Neo4j Desktop was frozen, I restarted the OS and since then I can't start the instance because of store lock exception:

**Log**

```
2018-07-12 07:57:20.813+0000 INFO  Starting...
2018-07-12 07:57:24.438+0000 INFO  Bolt enabled on localhost:22005.
2018-07-12 07:57:24.484+0000 INFO  Initiating metrics...
2018-07-12 07:57:25.047+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@44e3a2b2' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: C:\Users\Administrator\.Neo4jDesktop\neo4jDatabases\database-5555716c-b2b0-4e76-95a1-544991f0fb10\installation-3.3.5\data\databases\graph.db\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@44e3a2b2' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: C:\Users\Administrator\.Neo4jDesktop\neo4jDatabases\database-5555716c-b2b0-4e76-95a1-544991f0fb10\installation-3.3.5\data\databases\graph.db\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@44e3a2b2' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: C:\Users\Administrator\.Neo4jDesktop\neo4jDatabases\database-5555716c-b2b0-4e76-95a1-544991f0fb10\installation-3.3.5\data\databases\graph.db\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@44e3a2b2' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: C:\Users\Administrator\.Neo4jDesktop\neo4jDatabases\database-5555716c-b2b0-4e76-95a1-544991f0fb10\installation-3.3.5\data\databases\graph.db\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, C:\Users\Administrator\.Neo4jDesktop\neo4jDatabases\database-5555716c-b2b0-4e76-95a1-544991f0fb10\installation-3.3.5\data\databases\graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
	at org.neo4j.kernel.enterprise.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:36)
	at org.neo4j.server.enterprise.OpenEnterpriseNeoServer.lambda$static$1(OpenEnterpriseNeoServer.java:75)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter@6f152006' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: C:\Users\Administrator\.Neo4jDesktop\neo4jDatabases\database-5555716c-b2b0-4e76-95a1-544991f0fb10\installation-3.3.5\data\databases\graph.db\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
	... 9 more
Caused by: org.neo4j.kernel.StoreLockException: Store and its lock file has been locked by another process: C:\Users\Administrator\.Neo4jDesktop\neo4jDatabases\database-5555716c-b2b0-4e76-95a1-544991f0fb10\installation-3.3.5\data\databases\graph.db\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)
	at org.neo4j.kernel.internal.locker.StoreLocker.storeLockException(StoreLocker.java:116)
	at org.neo4j.kernel.internal.locker.StoreLocker.checkLock(StoreLocker.java:92)
	at org.neo4j.kernel.internal.locker.GlobalStoreLocker.checkLock(GlobalStoreLocker.java:60)
	at org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter.start(StoreLockerLifecycleAdapter.java:36)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 11 more
```

**What I have tried**
- Deleting store_lock file
- Killing all Neo4j and java process
- Moving store location to c:\neo4j  via Neo4j Browser new feature
- Running as Adminsitrator

**Note**
I encountered this issue in previous version of Neo4j Desktop and the above workarounds didn't help so I upgraded (both with clean install and without clean install) to 1.1.7 but yet again I'm getting this exception.

None of above items helped

**Comment by AlanLongYu** [comment]
because the web program http://localhost:7474/browser/ locked the graph.db. we need import to another database

**Comment by tinwelint** [comment]
Any further information? Have you tried with a more recent version, like 3.5? It seems strange that this would occur if all java/neo4j processes were closed before trying to start. Is the neo4j process running with a user that has write permission to that file and directory?

**Comment by digitalillusion** [comment]
I have the same problem after building a new image with the following dockerfile:
```
FROM docker.io/neo4j:3.5.6
ENV APOC_VERSION 3.5.0.4
ENV APOC_URI https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/${APOC_VERSION}/apoc-${APOC_VERSION}-all.jar
RUN apt-get update \
    && apt-get install -y wget
RUN wget $APOC_URI && mv apoc-${APOC_VERSION}-all.jar plugins/apoc-${APOC_VERSION}-all.jar
EXPOSE 7474 7473 7687
CMD ["neo4j"]
```
running it as follows:
```
docker build . -t mt-neo4j:local
docker run     --name mt-neo4j     -p7474:7474 -p7687:7687     -d     -v $HOME/neo4j/data:/data     -v $HOME/neo4j/logs:/logs     -v $HOME/neo4j/import:/var/lib/neo4j/import     -v $HOME/neo4j/plugins:/plugins     --env NEO4J_AUTH=neo4j/secret --env NEO4J_dbms_memory_heap_max__size=4G     mt-neo4j:local
```
It's maybe worth noticing that my $HOME/neo4j directory contains data from a docker.io/neo4j:3.4.5 installation.

**It turns out that $HOME/neo4j became somehow owned by root and simply chown back to me solved the issue**

**Comment by ryandaugherty** [comment]
Plus one. Same issue in docker container, neo4j 3.5.14. Only workaround that seems viable (other than messing with lock file) is to use cypher-shell to do a LOAD CSV statement.

**Comment by tinwelint** [comment]
Have you checked that the permissions of the database folder and the `store_lock` file matches the user that runs the Neo4j process?

**Comment by behindblackwalls** [comment]
I'm also experiencing this issue, any fix?

**Comment by rjurney** [comment]
Do we remove `databases/store_lock`?

**Comment by tinwelint** [comment]
The presence of that file doesn't mean the db is locked. It's only locked if there's a file lock on it. I'd say most of the issues come from the file existing, but with wrong permissions for some reason. And since it only acts a guard opening a db in multiple dbms's running at the same time it's safe to delete it if the dbms is stopped.

**Comment by rjurney** [comment]
Somehow I had two neo4j processes running. One got loose via Docker.
