### ISSUE TITLE
Neo4j 3.4.4 cold start: Failed to process a bolt message

### ISSUE THREAD

**Issue by nicolas-voigt** [neo4j/neo4j#12002]
Hi, after an install and a cold start, the following error messages pop up on the console.
- Neo4j version: 3.4.4, same behavior on 3.4.4 community and 3.4.5 community
- Operating system: Ubuntu 18.04 LTS
- API/Driver: Web interface
- **Steps to reproduce**
Extract the neo4j tarball
Execute bin/neo4j console
Open http://localhost:7474 on a browser
- Expected behavior
As the browser just opened for the first time, no error should be thrown
- Actual behavior
Sending the same error twice with different bolt sessions, debug log as follows
```nicolas@nicolas-pc:/tmp/neo4j-enterprise-3.4.4$ cd bin

nicolas@nicolas-pc:/tmp/neo4j-enterprise-3.4.4/bin$ ./neo4j console

Active database: graph.db
Directories in use:
  home:         /tmp/neo4j-enterprise-3.4.4
  config:       /tmp/neo4j-enterprise-3.4.4/conf
  logs:         /tmp/neo4j-enterprise-3.4.4/logs
  plugins:      /tmp/neo4j-enterprise-3.4.4/plugins
  import:       /tmp/neo4j-enterprise-3.4.4/import
  data:         /tmp/neo4j-enterprise-3.4.4/data
  certificates: /tmp/neo4j-enterprise-3.4.4/certificates
  run:          /tmp/neo4j-enterprise-3.4.4/run
Starting Neo4j.
2018-08-02 13:42:31.216+0000 INFO  ======== Neo4j 3.4.4 ========
2018-08-02 13:42:31.232+0000 INFO  Starting...
2018-08-02 13:42:31.887+0000 INFO  Initiating metrics...
2018-08-02 13:42:32.438+0000 INFO  Sending metrics to CSV file at /tmp/neo4j-enterprise-3.4.4/metrics
2018-08-02 13:42:32.570+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2018-08-02 13:42:33.607+0000 INFO  Started.
2018-08-02 13:42:33.691+0000 INFO  Mounted REST API at: /db/manage
2018-08-02 13:42:33.723+0000 INFO  Server thread metrics has been registered successfully
2018-08-02 13:42:34.053+0000 WARN  Low configured threads: (max={} - required={})={} < warnAt={} for {}
2018-08-02 13:42:34.061+0000 INFO  Remote interface available at http://localhost:7474/
2018-08-02 13:43:01.164+0000 ERROR Unexpected error detected in bolt session '309c23fffe881233-00001ba8-00000001-4d0f1452e3609ac0-493d4a51'. Failed to process a bolt message
org.neo4j.bolt.v1.runtime.BoltConnectionFatality: Failed to process a bolt message
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:742)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:728)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.access$500(BoltStateMachine.java:62)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:435)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.init(BoltStateMachine.java:145)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onInit$0(BoltMessageRouter.java:70)
        at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.lambda$enqueue$0(MetricsReportingBoltConnection.java:69)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:195)
        at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.processNextBatch(MetricsReportingBoltConnection.java:87)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:143)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:170)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:153)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.bolt.security.auth.AuthenticationException: The client is unauthorized due to authentication failure.
        at org.neo4j.bolt.security.auth.BasicAuthentication.doAuthenticate(BasicAuthentication.java:78)
        at org.neo4j.bolt.security.auth.BasicAuthentication.authenticate(BasicAuthentication.java:60)
        at org.neo4j.bolt.v1.runtime.BoltStateMachineSPI.authenticate(BoltStateMachineSPI.java:93)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:412)
        ... 12 more
2018-08-02 13:43:01.520+0000 ERROR Unexpected error detected in bolt session '309c23fffe881233-00001ba8-00000002-d0a62e85e3609c8a-bd4d89d8'. Failed to process a bolt message
org.neo4j.bolt.v1.runtime.BoltConnectionFatality: Failed to process a bolt message
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:742)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:728)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.access$500(BoltStateMachine.java:62)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:435)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.init(BoltStateMachine.java:145)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onInit$0(BoltMessageRouter.java:70)
        at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.lambda$enqueue$0(MetricsReportingBoltConnection.java:69)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:195)
        at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.processNextBatch(MetricsReportingBoltConnection.java:87)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:143)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:170)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:153)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.bolt.security.auth.AuthenticationException: The client is unauthorized due to authentication failure.
        at org.neo4j.bolt.security.auth.BasicAuthentication.doAuthenticate(BasicAuthentication.java:78)
        at org.neo4j.bolt.security.auth.BasicAuthentication.authenticate(BasicAuthentication.java:60)
        at org.neo4j.bolt.v1.runtime.BoltStateMachineSPI.authenticate(BoltStateMachineSPI.java:93)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:412)
        ... 12 more```

**Comment by rafaelctavares** [comment]
I have faced the same issue with version 3.4.5 running on Docker (official Neo4j community image) on Debian GNU/Linux 9.

Also, in my case, when I keep the Neo4j browser open, I can see it is reconnecting all the time, and sometimes my queries fail due to this connection drops. I have a very small graph database, so I found this quite strange. Nevertheless, I have tried to raise the heap and page cache limits, as well as the worker threads, but had no success.

I don't remember of this happening on older versions such as 3.4.1, but I might be wrong. Does anyone have any idea of what may be causing this?

**Comment by ishaanmadan19** [comment]
I have the same issue as well.

**Comment by msafder** [comment]
I too have the same issue. Any ideas yet?
