### ISSUE TITLE
[Cypher] ORDER BY + LIMIT can throw an OOM with an empty database

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#12004]
**Neo4j Version:** 3.4
**Operating System:** OSX
**API:** Any

ORDER BY + LIMIT will set the size of the PriorityQueue to the given LIMIT, even with the db is empty.
If the LIMIT is high, for eg INT_MAX, this will throw an OOM.

### Steps to reproduce

```
 @Test
    public void testOOMWithNoNodes() {
        try (Transaction tx = getDatabase().beginTx()) {
            Result result = getDatabase().execute("MATCH (n) RETURN n ORDER BY id(n) ASC LIMIT $limit", Collections.singletonMap("limit", Integer.MAX_VALUE));
            assertTrue(result.hasNext());
            tx.success();
        }
    }
```

Or same query in browser : 

![screen shot 2018-08-03 at 22 32 30](https://user-images.githubusercontent.com/1222009/43664912-d6074a38-976e-11e8-817d-e980ca80b8c6.png)

### Expected behavior

An OOM should not be thrown

### Actual behavior

```
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
```

Stacktrace : 
```
java.lang.OutOfMemoryError: Requested array size exceeds VM limit

	at java.util.PriorityQueue.<init>(PriorityQueue.java:169)
	at org.neo4j.cypher.internal.codegen.DefaultTopTable.<init>(DefaultTopTable.java:66)
	at org.neo4j.cypher.internal.compiler.v3_4.generated.GeneratedExecutionPlan296151035608328Execution.accept(Unknown Source)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.compiled.CompiledExecutionResult.accept(CompiledExecutionResult.scala:55)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.StandardInternalExecutionResult.accept(StandardInternalExecutionResult.scala:97)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.StandardInternalExecutionResult.doInAccept(StandardInternalExecutionResult.scala:164)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.StandardInternalExecutionResult$IterateByAccepting$class.createInner(StandardInternalExecutionResult.scala:230)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.compiled.CompiledExecutionResult.createInner(CompiledExecutionResult.scala:39)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.StandardInternalExecutionResult.inner$lzycompute(StandardInternalExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.StandardInternalExecutionResult.inner(StandardInternalExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.StandardInternalExecutionResult.hasNext(StandardInternalExecutionResult.scala:54)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.org$neo4j$cypher$internal$compatibility$ClosingExecutionResult$$closeIfEmpty(ClosingExecutionResult.scala:183)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$javaIterator$1.apply$mcV$sp(ClosingExecutionResult.scala:55)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$javaIterator$1.apply(ClosingExecutionResult.scala:55)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$javaIterator$1.apply(ClosingExecutionResult.scala:55)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.javaIterator(ClosingExecutionResult.scala:54)
	at org.neo4j.cypher.internal.javacompat.ExecutionResult.innerIterator(ExecutionResult.java:325)
	at org.neo4j.cypher.internal.javacompat.ExecutionResult.hasNext(ExecutionResult.java:223)
	at com.graphaware.nlp.enterprise.DevTest.testOOMWithNoNodes(DevTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
```

**Comment by SaschaPeukert** [comment]
@ikwattro Thanks for reporting this. We will work on it and get back to you
