### ISSUE TITLE
New installation / launch of Neo4j browser interface results in 'bolt session' error

### ISSUE THREAD

**Issue by abildgaard** [neo4j/neo4j#12010]
- Neo4j version: 3.4.5 (community edition)
- Operating system: MacOS 10.13.4
- API/Driver: N/A

 **Steps to reproduce**

* install latest version of Ne04j 3.4.5

* change the following values in the neo4j.conf file:
     - dbms.connectors.default_listen_address=10.1.10.201
     - dbms.connector.bolt.listen_address=:6470
     - dbms.connector.http.listen_address=:7470
     - dbms.connector.https.listen_address=:8470

* added in certificates directory:
  - neo4j.cert
  - neo4j.key
  which both are working when our app is interfacing Neo4j

* started neo4j:
```
2018-08-09 16:20:21.208+0000 INFO  ======== Neo4j 3.4.5 ========
2018-08-09 16:20:21.242+0000 INFO  Starting...
2018-08-09 16:20:23.075+0000 INFO  Bolt enabled on 10.1.10.201:6470.
2018-08-09 16:20:24.808+0000 INFO  Started.
2018-08-09 16:20:25.693+0000 INFO  Remote interface available at http://localhost:7470/
```

* launched neo4j browser in Safari browser using  ***https://10.1.10.201:8470/browser/*** and get the following error on the console even before having to log in with credentials.

```
2018-08-09 16:20:40.496+0000 ERROR Unexpected error detected in bolt session 'e4ce8ffffe5ccb70-00000396-00000001-c24e3904dffd74f5-56b81c80'. Failed to process a bolt message
org.neo4j.bolt.v1.runtime.BoltConnectionFatality: Failed to process a bolt message
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:742)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:728)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.access$500(BoltStateMachine.java:62)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:435)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.init(BoltStateMachine.java:145)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onInit$0(BoltMessageRouter.java:70)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:195)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:143)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:170)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:153)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.bolt.security.auth.AuthenticationException: The client is unauthorized due to authentication failure.
	at org.neo4j.bolt.security.auth.BasicAuthentication.doAuthenticate(BasicAuthentication.java:78)
	at org.neo4j.bolt.security.auth.BasicAuthentication.authenticate(BasicAuthentication.java:60)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineSPI.authenticate(BoltStateMachineSPI.java:93)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:412)
	... 10 more
2018-08-09 16:20:40.512+0000 ERROR Unexpected error detected in bolt session 'e4ce8ffffe5ccb70-00000396-00000002-2acc3cecdffd75b8-a2d0afcc'. Failed to process a bolt message
org.neo4j.bolt.v1.runtime.BoltConnectionFatality: Failed to process a bolt message
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:742)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:728)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.access$500(BoltStateMachine.java:62)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:435)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.init(BoltStateMachine.java:145)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onInit$0(BoltMessageRouter.java:70)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:195)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:143)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:170)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:153)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.bolt.security.auth.AuthenticationException: The client is unauthorized due to authentication failure.
	at org.neo4j.bolt.security.auth.BasicAuthentication.doAuthenticate(BasicAuthentication.java:78)
	at org.neo4j.bolt.security.auth.BasicAuthentication.authenticate(BasicAuthentication.java:60)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineSPI.authenticate(BoltStateMachineSPI.java:93)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:412)
	... 10 more
2018-08-09 16:23:39.703+0000 ERROR Unexpected error detected in bolt session 'e4ce8ffffe5ccb70-00000396-00000003-94e4a077ab00318f-e0f26737'. Failed to process a bolt message
org.neo4j.bolt.v1.runtime.BoltConnectionFatality: Failed to process a bolt message
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:742)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:728)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.access$500(BoltStateMachine.java:62)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:435)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.init(BoltStateMachine.java:145)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onInit$0(BoltMessageRouter.java:70)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:195)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:143)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:170)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:153)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.bolt.security.auth.AuthenticationException: The client is unauthorized due to authentication failure.
	at org.neo4j.bolt.security.auth.BasicAuthentication.doAuthenticate(BasicAuthentication.java:78)
	at org.neo4j.bolt.security.auth.BasicAuthentication.authenticate(BasicAuthentication.java:60)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineSPI.authenticate(BoltStateMachineSPI.java:93)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:412)
	... 10 more
2018-08-09 16:23:39.723+0000 ERROR Unexpected error detected in bolt session 'e4ce8ffffe5ccb70-00000396-00000004-9d9ac4b7ab0031c3-063074de'. Failed to process a bolt message
org.neo4j.bolt.v1.runtime.BoltConnectionFatality: Failed to process a bolt message
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:742)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:728)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.access$500(BoltStateMachine.java:62)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:435)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.init(BoltStateMachine.java:145)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onInit$0(BoltMessageRouter.java:70)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:195)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:143)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:170)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:153)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.bolt.security.auth.AuthenticationException: The client is unauthorized due to authentication failure.
	at org.neo4j.bolt.security.auth.BasicAuthentication.doAuthenticate(BasicAuthentication.java:78)
	at org.neo4j.bolt.security.auth.BasicAuthentication.authenticate(BasicAuthentication.java:60)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineSPI.authenticate(BoltStateMachineSPI.java:93)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:412)
	... 10 more

```

- Expected behavior
 NOT what what is happening above

Once I have successfully logged in using default password and changed the password then I don't see the errors again (so far) when I use cypher commands

**Comment by abildgaard** [comment]
Once I have successfully logged in using default password and changed the password then I don't see the errors again (so far)

**Comment by craigtaverner** [comment]
Duplicate: https://github.com/neo4j/neo4j/issues/12002
