### ISSUE TITLE
Received fatal alert: bad_certificate error with chained certificate

### ISSUE THREAD

**Issue by smadurange** [neo4j/neo4j#12025]
I'm using Neo4j 3.4.5 Enterprise Edition deployed on a CentOS7 server. I have obtained a wildcard certificate from GoDaddy. I configured SSL in Neo4j as below:

1. Copied public.crt (which is a chained certificate with intermediate and root certificates) to `/certificates/default` and `/certificates/default/trusted` and set the permissions `-rw-r--r--`.
2. Copied private.key to `/certificates/default` and set permissions to `-r--------`.
3. Added the following configuration to `neo4j.conf` file:

    ```
    dbms.directories.certificates=/var/lib/neo4j/certificates
    
    dbms.connectors.default_listen_address=0.0.0.0
    
    dbms.connector.bolt.enabled=true
    dbms.connector.bolt.tls_level=REQUIRED
    dbms.connector.bolt.listen_address=:7687
    
    dbms.connector.http.enabled=true
    dbms.connector.http.listen_address=:7474
    
    dbms.connector.https.enabled=true
    dbms.connector.https.listen_address=:7473
    
    bolt.ssl_policy=default
    https.ssl_policy=default
    
    dbms.ssl.policy.default.base_directory=certificates/default
    dbms.ssl.policy.default.allow_key_generation=false

    dbms.ssl.policy.default.trust_all=false
    dbms.ssl.policy.default.client_auth=require```

I verified the installation of certificates using DigiCert® SSL Installation Diagnostics Tool and the installation test passes without any warning or issue.

However, when I try to access the Neo4J browser like https://example.com:7473/browser I get the error from the browser (Firefox, and Chrome gives a similar error):

An error occurred during a connection to example.com:7473. SSL peer cannot verify your certificate. Error code: SSL_ERROR_BAD_CERT_ALERT.

When I check the debug.log, I see the following stack trace:

    2018-08-21 13:00:07.997+0000 ERROR [o.n.b.t.p.ProtocolHandshaker] Fatal error occurred during protocol handshaking: [id: xxxxx, L:/xx.xxx.x.xx:7687 - R:/xxx.xx.xxx.xxx:51337] An unencrypted connection attempt was made where encryption is required.
    java.lang.SecurityException: An unencrypted connection attempt was made where encryption is required.
            at org.neo4j.bolt.transport.pipeline.ProtocolHandshaker.assertEncryptedIfRequired(ProtocolHandshaker.java:154)
            at org.neo4j.bolt.transport.pipeline.ProtocolHandshaker.channelRead(ProtocolHandshaker.java:86)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
            at org.neo4j.bolt.transport.pipeline.WebSocketFrameTranslator.channelRead(WebSocketFrameTranslator.java:39)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
            at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
            at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
            at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
            at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:77)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
            at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandler$1.channelRead(WebSocketServerProtocolHandler.java:204)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
            at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
            at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
            at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
            at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
            at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
            at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
            at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
            at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
            at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
            at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
            at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
            at java.lang.Thread.run(Thread.java:748)

Then, from my CentOS terminal, I tried to connect to cypher shell like: `cypher-shell -u neo4j -p neo4j` and I get the error: `Received fatal alert: bad_certificate`

In the debug.log, I can see the following error trace after this:

    2018-08-21 13:07:14.328+0000 ERROR [o.n.b.t.TransportSelectionHandler] Fatal error occurred during protocol selection for connection: [id: xxxxx, L:/xxx.x.x.x:7687 ! R:/xxx.x.x.x:39078] javax.net.ssl.SSLHandshakeException: null cert chain
    io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: null cert chain
            at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
            at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
            at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
            at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
            at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
            at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
            at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
            at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
            at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
            at java.lang.Thread.run(Thread.java:748)
    Caused by: javax.net.ssl.SSLHandshakeException: null cert chain
            at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1529)
            at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
            at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
            at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
            at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
            at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:294)
            at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1275)
            at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1177)
            at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1221)
            at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
            at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
            ... 17 more
    Caused by: javax.net.ssl.SSLHandshakeException: null cert chain
            at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
            at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
            at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:330)
            at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:318)
            at sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:1935)
            at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:237)
            at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
            at sun.security.ssl.Handshaker$1.run(Handshaker.java:992)
            at sun.security.ssl.Handshaker$1.run(Handshaker.java:989)
            at java.security.AccessController.doPrivileged(Native Method)
            at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1467)
            at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1435)
            at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1343)

**Comment by smadurange** [comment]
Needed to set `dbms.ssl.policy.default.client_auth=NONE`
