### ISSUE TITLE
Connection refused  while trying to start neo4j shell.

### ISSUE THREAD

**Issue by sanyalpp** [neo4j/neo4j#12024]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests.  If you have questions on how to use Neo4j, please ask on [StackOverflow](http://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

If you want to make a feature request then there is no guideline, so feel free to stop reading and open an issue. If you have a bug report however, please continue reading.
To help us understand your issue, please specify important details, primarily:

- Neo4j version: 3.4.4
- Operating system: (for example Windows 95/Ubuntu 16.04) :MacOS
- API/Driver: (for example Cypher/Java API/Python driver vX.Y.Z)
- **Steps to reproduce**
- Expected behavior
- Actual behavior

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

**Neo4j Version:** 3.4.4
**Operating System:** MacOS

### Steps to reproduce
I am trying to run the n eo4j shell. I am receiving a connection refused error:

0
down vote
favorite
I am trying to follow the steps listed here https://neo4j.com/developer/kb/fulltext-search-in-neo4j/

I am using version 3.4.4

to try out full text search. I am not able to run the neo4jshell. I always get the following error :

$ ./neo4j-shell 
ERROR (-v for expanded information):
    Connection refused

 -host      Domain name or IP of host to connect to (default: localhost)
 -port      Port of host to connect to (default: 1337)
 -name      RMI name, i.e. rmi://<host>:<port>/<name> (default: shell)
 -pid       Process ID to connect to
 -c         Command line to execute. After executing it the shell exits
 -file      File containing commands to execute, or '-' to read from stdin. After executing it the shell exits
 -readonly  Connect in readonly mode (only for connecting with -path)
 -path      Points to a neo4j db path so that a local server can be started there
 -config    Points to a config file when starting a local server

Example arguments for remote:
    -port 1337
    -host 192.168.1.234 -port 1337 -name shell
    -host localhost -readonly
    ...or no arguments for default values
Example arguments for local:
    -path /path/to/db
    -path /path/to/db -config /path/to/neo4j.config
    -path /path/to/db -readonly

java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
    java.net.ConnectException: Connection refused (Connection refused)
    at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
    at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
    at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
    at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:338)
    at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:112)
    at java.rmi.Naming.lookup(Naming.java:101)
    at org.neo4j.shell.impl.RmiLocation.getBoundObject(RmiLocation.java:191)
    at org.neo4j.shell.impl.RemoteClient.findRemoteServer(RemoteClient.java:72)
    at org.neo4j.shell.impl.RemoteClient.<init>(RemoteClient.java:65)
    at org.neo4j.shell.impl.RemoteClient.<init>(RemoteClient.java:46)
    at org.neo4j.shell.ShellLobby.newClient(ShellLobby.java:203)
    at org.neo4j.shell.StartClient.startRemote(StartClient.java:353)
    at org.neo4j.shell.StartClient.start(StartClient.java:229)
    at org.neo4j.shell.StartClient.main(StartClient.java:147)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at java.net.Socket.connect(Socket.java:538)
    at java.net.Socket.<init>(Socket.java:434)
    at java.net.Socket.<init>(Socket.java:211)
    at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
    at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
    at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
    ... 13 more
I have tried the localhost, port etc options as well. No luck. Do I have to do any configuration changes?

Please help!

**Comment by sanyalpp** [comment]
Started working all of a sudden!
