### ISSUE TITLE
Failed to start Neo4J after configuring SSL for Bolt and HTTPS

### ISSUE THREAD

**Issue by smadurange** [neo4j/neo4j#12022]
I'm using Neo4J Server version 3.4.6 Enterprise edition on 64 bit CentOS7 with OpenJDK.

I'm trying to configure SSL with the auto-generated keys (self-signed names neo4j.key and neo4j.cert). The SSL related configuration settings are as below:

```
dbms.directories.certificates=/var/lib/neo4j/certificates

# Bolt connector
dbms.connector.bolt.enabled=true
dbms.connector.bolt.tls_level=REQUIRED
dbms.connector.bolt.listen_address=:7687

# HTTP Connector. There must be exactly one HTTP connector.
dbms.connector.http.enabled=true
dbms.connector.http.listen_address=:7474

# HTTPS Connector. There can be zero or one HTTPS connectors.
dbms.connector.https.enabled=true
dbms.connector.https.listen_address=:7473

#*****************************************************************
# SSL system configuration
#*****************************************************************

bolt.ssl_policy=default_policy
https.ssl_policy=default_policy

#*****************************************************************
# SSL policy configuration
#*****************************************************************

dbms.ssl.policy.default_policy.base_directory=certificates/default_policy
dbms.ssl.policy.default_policy.allow_key_generation=false
dbms.ssl.policy.default_policy.trust_all=false
dbms.ssl.policy.default_policy.private_key=/var/lib/neo4j/certificates/default_policy/neo4j.key
dbms.ssl.policy.default_policy.public_certificate=/var/lib/neo4j/certificates/default_policy/neo4j.cert
dbms.ssl.policy.default_policy.client_auth=require
```

Other related settings to SSL such as trusted directories are commented out (so, I reckon the defaults are used). I have already created the directory structure with the same file and directory permissions as described in the docs [here](https://neo4j.com/docs/operations-manual/current/security/ssl-framework/).

 Then I tried to start neo4j server using `neo4j start`, however this started to give an error that mentioned the PID file was not being created. This command was working before I changed the SSL config.

Anyway, after killing any processes related neo4j, I tried to bring it up with `systemctl start neo4j`. When I checked status with `systemctl status neo4j`, at first it looked like the server came up. However, I could not access the browser client. When I tried the `systemctl status neo4j` again, I see the message:

```
● neo4j.service - Neo4j Graph Database
   Loaded: loaded (/usr/lib/systemd/system/neo4j.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Sun 2018-08-19 10:54:41 UTC; 8s ago
  Process: 3207 ExecStart=/usr/share/neo4j/bin/neo4j console (code=exited, status=1/FAILURE)
 Main PID: 3207 (code=exited, status=1/FAILURE)

Aug 19 10:54:41 neo4j-centos-prod systemd[1]: neo4j.service: main process exited, code=exited, status=1/FAILURE
Aug 19 10:54:41 neo4j-centos-prod systemd[1]: Unit neo4j.service entered failed state.
Aug 19 10:54:41 neo4j-centos-prod systemd[1]: neo4j.service failed.
Aug 19 10:54:41 neo4j-centos-prod systemd[1]: neo4j.service holdoff time over, scheduling restart.
Aug 19 10:54:41 neo4j-centos-prod systemd[1]: start request repeated too quickly for neo4j.service
Aug 19 10:54:41 neo4j-centos-prod systemd[1]: Failed to start Neo4j Graph Database.
Aug 19 10:54:41 neo4j-centos-prod systemd[1]: Unit neo4j.service entered failed state.
Aug 19 10:54:41 neo4j-centos-prod systemd[1]: neo4j.service failed.
```

In the logs in `/var/log/neo4j/neo4j.log` I see the following error:

```
2018-08-19 10:38:07.431+0000 INFO  ======== Neo4j 3.4.6 ========
2018-08-19 10:38:07.490+0000 INFO  Starting...
2018-08-19 10:38:10.199+0000 INFO  Initiating metrics...
2018-08-19 10:38:10.555+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7e38a7fe' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: /var/lib/neo4j/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7e38a7fe' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: /var/lib/neo4j/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7e38a7fe' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: /var/lib/neo4j/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7e38a7fe' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: /var/lib/neo4j/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases/graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
        at org.neo4j.kernel.enterprise.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:39)
        at org.neo4j.server.enterprise.OpenEnterpriseNeoServer.lambda$static$1(OpenEnterpriseNeoServer.java:78)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter@3e34ace1' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: /var/lib/neo4j/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
        ... 9 more
Caused by: org.neo4j.kernel.StoreLockException: Store and its lock file has been locked by another process: /var/lib/neo4j/data/databases/graph.db/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)
        at org.neo4j.kernel.internal.locker.StoreLocker.storeLockException(StoreLocker.java:117)
        at org.neo4j.kernel.internal.locker.StoreLocker.checkLock(StoreLocker.java:93)
        at org.neo4j.kernel.internal.locker.GlobalStoreLocker.checkLock(GlobalStoreLocker.java:60)
        at org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter.start(StoreLockerLifecycleAdapter.java:36)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 11 more
2018-08-19 10:38:10.569+0000 INFO  Neo4j Server shutdown initiated by request
2018-08-19 10:46:53.868+0000 INFO  Neo4j Server shutdown initiated by request
2018-08-19 10:46:53.903+0000 INFO  Stopping...
2018-08-19 10:46:54.305+0000 INFO  Stopped.
```

I verified using `ps aux` that no other process related to neo4j is running. Also, there's no `store_lock` file in `/var/lib/neo4j/data/databases/graph.db`.

**Comment by clayscode** [comment]
What did you do to fix this problem because I'm running into exactly the same issue?

**Comment by smadurange** [comment]
@clayscode Can try setting the following configuration settings:

`dbms.ssl.policy.default.client_auth=NONE`

There was a doc on not being able to set client_auth while using TLS but I can't find it right now.
