### ISSUE TITLE
Exception logs every 3 seconds server side

### ISSUE THREAD

**Issue by CodeDogDream** [neo4j/neo4j#12066]
One of our customer db has log entries every 3s, the origin is unknown.
Neo4j Version: 3.2.3 & 3.4.1
Operating System: Centos 
API: JAVA
Actual behavior
`2018-10-31 09:49:12.078+0000 WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. Connection reset by peer
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
2018-10-31 09:49:12.531+0000 WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. Connection reset by peer
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.`

**Comment by chrisvest** [comment]
"Connection reset by peer" means that from the point of view of the server, it looks like the client closed the connection. In practice it could also be a firewall that terminated the connection. Firewalls sometimes terminate connections that idle for too long.

**Comment by CodeDogDream** [comment]
> "Connection reset by peer" means that from the point of view of the server, it looks like the client closed the connection. In practice it could also be a firewall that terminated the connection. Firewalls sometimes terminate connections that idle for too long.

When we manually sent the request, there was no similar problem and it should not be a firewall problem

**Comment by ali-ince** [comment]
Hi @CodeDogDream,

There's nothing we can do about `connection reset by peer` errors because those are operating system generated errors on receipt of `TCP Reset (RST)` package from the other end of the connection. You can find a good explanation of the situation at https://stackoverflow.com/a/1434592.

We however introduced the fix where these errors are caught early and logged explicitly by related handlers rather than being logged as unhandled exceptions. `Connection reset by peer` errors will be logged at `WARN` level without a stack trace.

The fix will be available in upcoming releases of 3.2 and upwards (https://github.com/neo4j/neo4j/commit/513b99dc10432bcbf85a69802cd5deb61f78e9bc).

Thanks.
