### ISSUE TITLE
Neo4j browser Not Reading database

### ISSUE THREAD

**Issue by sranasir** [neo4j/neo4j#12067]
Using Neo4j 3.4.4, I am trying to read my local database on localhost:7474. The credentials are good and I am able to log in. The database, however, does not show up. `dbms.active_database` points to the correct database folder. This was working fine with Neo4j 2.x until I upgraded it to 3.x recently. This closed issue is similar in nature but the mentioned reasoning but does not seem to hold true: https://github.com/neo4j/neo4j/issues/11972/

Following is a dump of the debug log and the configuration file:
[neo4j.conf.txt](https://github.com/neo4j/neo4j/files/2540206/neo4j.conf.txt)

2018-11-01 21:25:15.829+0000 ERROR [o.n.b.r.DefaultBoltConnection] Unexpected error detected in bolt session 'acb
c32fffeb2c2d7-00001989-00000001-4c35f487886a8119-3dd60ca1'. Failed to process a bolt message
org.neo4j.bolt.v1.runtime.BoltConnectionFatality: Failed to process a bolt message
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:742)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:728)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.access$500(BoltStateMachine.java:62)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:435)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.init(BoltStateMachine.java:145)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onInit$0(BoltMessageRouter.java:70)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:195)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:143)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:170)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler
.java:153)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.neo4j.bolt.security.auth.AuthenticationException: The client is unauthorized due to authentication failure.
        at org.neo4j.bolt.security.auth.BasicAuthentication.doAuthenticate(BasicAuthentication.java:78)
        at org.neo4j.bolt.security.auth.BasicAuthentication.authenticate(BasicAuthentication.java:60)
        at org.neo4j.bolt.v1.runtime.BoltStateMachineSPI.authenticate(BoltStateMachineSPI.java:93)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:412)
        ... 10 more
2018-11-01 21:25:19.612+0000 ERROR [o.n.b.r.DefaultBoltConnection] Unexpected error detected in bolt session 'acbc32fffeb2c2d7-00001989-00000008-e47ed128086a9074-3591c1ea'. Failed to process a bolt message
org.neo4j.bolt.v1.runtime.BoltConnectionFatality: Failed to process a bolt message
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:742)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:728)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.access$500(BoltStateMachine.java:62)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:435)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.init(BoltStateMachine.java:145)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onInit$0(BoltMessageRouter.java:70)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:195)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:143)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:170)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:153)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.neo4j.bolt.security.auth.AuthenticationException: The client is unauthorized due to authentication failure.
        at org.neo4j.bolt.security.auth.BasicAuthentication.doAuthenticate(BasicAuthentication.java:78)
        at org.neo4j.bolt.security.auth.BasicAuthentication.authenticate(BasicAuthentication.java:60)
        at org.neo4j.bolt.v1.runtime.BoltStateMachineSPI.authenticate(BoltStateMachineSPI.java:93)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:412)
        ... 10 more

Could it be that it is something that I am doing wrong?

**Comment by craigtaverner** [comment]
I've notified the browser team to look into this, but could I check if you are sure of two things:

* Are you really using the latest browser that comes with the version of Neo4j you are running? Try go to http://localhost:7474 (not anything else, especially not the `/url` you hinted above) and also try force reload.
* Is is possible you are not entering the correct credentials for the login.

**Comment by sranasir** [comment]
Both of these are fine. The `/url` was a typo. I have corrected that.
The issue of database not showing up was resolved as the browser was pulling up the database from the default data directory which contained nothing.
However, the same bolt failure message is still showing up in the logs for some reason.

**Comment by oskarhane** [comment]
Currently neo4j-browser wants to know if the database has auth enabled so when it loads it will run a command without credentials to see if it's allowed in.
If you have auth enabled, then the above error massage is shown.
Calling that an 'error' in the logs is overreacting imho. Maybe a 'warning' would be appropriate.
Anyway, neo4j-browser might not do this in the future, and the log entires severity might change.

We have this tracked and will act on it somehow.
