### ISSUE TITLE
Upgrade from Neo 2.3.10 to 3.4.10 fails due to Transaction logs prefix < 5

### ISSUE THREAD

**Issue by StevenMapes** [neo4j/neo4j#12087]
- Neo4j version (from): 2.3.10
- Neo4j version (to): 3.4.10
- Operating system: Ubuntu 18.04
- API/Driver: N/A
- Following the instructions from https://neo4j.com/docs/operations-manual/3.4/upgrade/deployment-upgrading/
If you then run ```neo4j console``` the upgrade will appear to complete and you can connect to ```http://localhost:7474/browser/``` and can query the graph. However when you then terminate the error occurs. You can also install neo4j 3.4.10 as a service but it will go into an endless crash loop upon startup
- Expected behavior - Upgrade to work
- Actual behavior - Failure to stably upgrade and generation of the following exception when ```neo4j console``` is terminated.
```
Exception in thread "Thread-0" org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource$2@3930487d' failed to transition from stopped to shutting_down. Please see the attached cause exception "Transaction logs contains entries with prefix 4, and the lowest supported prefix is 5. This indicates that the log files originates from an older version of neo4j, which we don't support migrations from.. At position LogPosition{logVersion=224, byteOffset=16} and entry version null"
```
Here is the complete output from the terminal

```
root@host:/usr/bin# neo4j console
Active database: graph.db
Directories in use:
  home:         /var/lib/neo4j
  config:       /etc/neo4j
  logs:         /var/log/neo4j
  plugins:      /var/lib/neo4j/plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/run/neo4j
Starting Neo4j.
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
2018-11-18 11:28:03.966+0000 INFO  ======== Neo4j 3.4.10 ========
2018-11-18 11:28:04.042+0000 INFO  Starting...
2018-11-18 11:28:08.816+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2018-11-18 11:28:11.607+0000 INFO  Started.
2018-11-18 11:28:12.854+0000 INFO  Remote interface available at http://localhost:7474/
^C
2018-11-18 11:29:13.807+0000 INFO  Neo4j Server shutdown initiated by request
2018-11-18 11:29:13.820+0000 INFO  Stopping...
Exception in thread "Thread-0" org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource$2@3930487d' failed to transition from stopped to shutting_down. Please see the attached cause exception "Transaction logs contains entries with prefix 4, and the lowest supported prefix is 5. This indicates that the log files originates from an older version of neo4j, which we don't support migrations from.. At position LogPosition{logVersion=224, byteOffset=16} and entry version null".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:519)
        at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:206)
        at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:767)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:480)
        at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.stop(DataSourceManager.java:120)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:480)
        at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
        at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:191)
        at org.neo4j.kernel.impl.factory.ClassicCoreSPI.shutdown(ClassicCoreSPI.java:180)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.shutdown(GraphDatabaseFacade.java:364)
        at org.neo4j.server.database.LifecycleManagingDatabase.stop(LifecycleManagingDatabase.java:105)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:480)
        at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
        at org.neo4j.server.AbstractNeoServer.stop(AbstractNeoServer.java:392)
        at org.neo4j.server.ServerBootstrapper.lambda$addShutdownHook$3(ServerBootstrapper.java:213)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.kernel.impl.transaction.log.entry.UnsupportedLogVersionException: Transaction logs contains entries with prefix 4, and the lowest supported prefix is 5. This indicates that the log files originates from an older version of neo4j, which we don't support migrations from.. At position LogPosition{logVersion=224, byteOffset=16} and entry version null
        at org.neo4j.kernel.impl.transaction.log.entry.LogEntryVersion.byVersion(LogEntryVersion.java:169)
        at org.neo4j.kernel.impl.transaction.log.entry.VersionAwareLogEntryReader.readLogEntry(VersionAwareLogEntryReader.java:80)
        at org.neo4j.kernel.impl.transaction.log.files.TransactionLogFileInformation$TransactionLogFileTimestampMapper.getTimestampForVersion(TransactionLogFileInformation.java:113)
        at org.neo4j.kernel.impl.transaction.log.files.TransactionLogFileInformation.getFirstStartRecordTimestamp(TransactionLogFileInformation.java:92)
        at org.neo4j.kernel.impl.transaction.log.pruning.EntryTimespanThreshold.reached(EntryTimespanThreshold.java:53)
        at org.neo4j.kernel.impl.transaction.log.pruning.ThresholdBasedPruneStrategy.findLogVersionsToDelete(ThresholdBasedPruneStrategy.java:68)
        at org.neo4j.kernel.impl.transaction.log.pruning.LogPruningImpl.pruneLogs(LogPruningImpl.java:124)
        at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:178)
        at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.forceCheckPoint(CheckPointerImpl.java:92)
        at org.neo4j.kernel.NeoStoreDataSource$2.shutdown(NeoStoreDataSource.java:795)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:511)
        ... 19 more
```

# neo4j.conf changes
The following changes have been made to the neo4j.conf only
 ```
dbms.allow_upgrade=true
dbms.connectors.default_listen_address=0.0.0.0
dbms.connector.http.enabled=true
dbms.connector.http.listen_address=:7474
dbms.connector.https.enabled=true
```

NEO4J_CONF environmental setting has also been set
```
root@host:/usr/bin# echo $NEO4J_CONF
/etc/neo4j/neo4j.conf
```

# Output of neo4j-admin commands
```
root@host:/usr/bin# neo4j-admin store-info --store=/var/lib/neo4j/data/databases/graph.db/
Store format version:         v0.A.9                                            
Store format introduced in:   3.4.0    
```

```
neo4j-admin check-consistency --database=graph.db              
2018-11-18 11:11:37.546+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Selected RecordFormat:StandardV3_4[v0.A.9] recor$
 format from store /var/lib/neo4j/data/databases/graph.db                                
2018-11-18 11:11:37.551+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Format not configured. Selected format from the $
tore: RecordFormat:StandardV3_4[v0.A.9]                                                    
....................  10%                                                             
....................  20%                                                          
....................  30%                                                          
....................  40%                                                                              
....................  50%                                                           
....................  60%                                                         
....................  70%                                                                           
....................  80%                                                                
....................  90%                                                                  
..................Checking node and relationship counts                                       
....................  10%                                                                     
....................  20%                                                                     
....................  30%                                                            
....................  40%                                                           
....................  50%                                                        
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
```

**Comment by poppingtonic** [comment]
This is late, but there's a specific upgrade process that you should use if you're running neo4j in Ubuntu. It requires you to upgrade to neo4j 3.2 first, then to the latest version. Here's the link: https://neo4j.com/docs/operations-manual/current/installation/linux/debian/#debian-upgrade
