### ISSUE TITLE
[neo4j-community-3.4.9-1] Server isn't start

### ISSUE THREAD

**Issue by vlamai** [neo4j/neo4j#12085]
OS: Manjaro Linux x86_64 
Kernel: 4.14.81-1-MANJARO 
Neo4j : neo4j-community-3.4.9-1

<pre>23:45:35 | ~ 
----&gt; neo4j console
Active database: graph.db
Directories in use:
  home:         /home/kzoper/neo
  config:       /home/kzoper/neo/conf
  logs:         /home/kzoper/neo/logs
  plugins:      /home/kzoper/neo/plugins
  import:       NOT SET
  data:         /home/kzoper/neo/data
  certificates: /home/kzoper/neo/certificates
  run:          /home/kzoper/neo/run
Starting Neo4j.
Error: Could not find or load main class org.neo4j.server.CommunityEntryPoint
23:45:53 | ~ 
----&gt; neo4j start
Active database: graph.db
Directories in use:
  home:         /home/kzoper/neo
  config:       /home/kzoper/neo/conf
  logs:         /home/kzoper/neo/logs
  plugins:      /home/kzoper/neo/plugins
  import:       NOT SET
  data:         /home/kzoper/neo/data
  certificates: /home/kzoper/neo/certificates
  run:          /home/kzoper/neo/run
Starting Neo4j.
/usr/bin/neo4j: line 418: /home/kzoper/neo/run/neo4j.pid: No such file or directory
/usr/bin/neo4j: line 417: /home/kzoper/neo/logs/neo4j.log: No such file or directory
</pre>

After `systemctl start neo4j`
```
2018-11-17 18:51:02.740+0000 INFO  ======== Neo4j 3.4.9 ========
2018-11-17 18:51:02.759+0000 INFO  Starting...
2018-11-17 18:51:04.129+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2018-11-17 18:51:04.458+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3a4ba480' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/dbms/1951848603279113197_auth.tmp (Permission denied)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3a4ba480' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/dbms/1951848603279113197_auth.tmp (Permission denied)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3a4ba480' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/dbms/1951848603279113197_auth.tmp (Permission denied)".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3a4ba480' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/dbms/1951848603279113197_auth.tmp (Permission denied)".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:125)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.security.auth.BasicAuthManager@38548b19' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/dbms/1951848603279113197_auth.tmp (Permission denied)".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
	... 9 more
Caused by: java.io.FileNotFoundException: /var/lib/neo4j/data/dbms/1951848603279113197_auth.tmp (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.neo4j.io.fs.DefaultFileSystemAbstraction.openAsOutputStream(DefaultFileSystemAbstraction.java:76)
	at org.neo4j.server.security.auth.FileRepositorySerializer.writeToFile(FileRepositorySerializer.java:47)
	at org.neo4j.server.security.auth.FileRepositorySerializer.saveRecordsToFile(FileRepositorySerializer.java:80)
	at org.neo4j.server.security.auth.FileUserRepository.persistUsers(FileUserRepository.java:96)
	at org.neo4j.server.security.auth.AbstractUserRepository.create(AbstractUserRepository.java:82)
	at org.neo4j.server.security.auth.BasicAuthManager.newUser(BasicAuthManager.java:151)
	at org.neo4j.server.security.auth.BasicAuthManager.start(BasicAuthManager.java:91)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 11 more
2018-11-17 18:51:04.459+0000 INFO  Neo4j Server shutdown initiated by request
```
Change envariment variable to export `NEO4J_HOME=$HOME/neo` with default value same thing

**Comment by jennyowen** [comment]
How did you install Neo4j? 
I guess from the path that you used the tarball to install, but the tarball doesn't install a neo4j service, so I'm not sure how you were able to start a service using `systemctl` unless you had a pre-existing installation or used a package installer.

Manjaro isn't one of the supported Linux operating systems (see: https://neo4j.com/docs/operations-manual/current/installation/requirements ) so some weirdness might have happened if you used the deb or rpm installer.

What does `which neo4j` return?
Could you make sure that Neo4j is completely uninstalled and try installing again from the tarball?
