### ISSUE TITLE
Starting without any transaction log is broken

### ISSUE THREAD

**Issue by norbusan** [neo4j/neo4j#12084]
- Neo4j 3.4.9 docker image
- linux Debian/stable
- related issues #8681

I transfered a database from one computer to another, but have removed all transaction logs due to size. Before transferring I have properly shut down neo4j on the one server, and then copied over all of the `graph.db` directory. Restarting on the other server did not work out with:

```

2018-11-16 16:45:47.047+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@773bd77b' was successfully initialized, but failed to start. Please see the attached cause exception "No check point found in any log file from version 19 to 19". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@773bd77b' was successfully initialized, but failed to start. Please see the attached cause exception "No check point found in any log file from version 19 to 19".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@773bd77b' was successfully initialized, but failed to start. Please see the attached cause exception "No check point found in any log file from version 19 to 19".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
```

Is this an unsupported operation? I have often done similar transfers, but this time the transaction logs amounted to 5Gb (while the database was only 500Mb) so I decided to remove them, as I found several comments that removing the transaction log is fine if one doesn't want to make a backup. On the original server I have no problems stopping and re-starting neo4j, though.

Thanks

**Comment by chrisvest** [comment]
Deleting transaction log files manually is not supported, no. The comments that told you it was are wrong.

You can reduce the transaction log data that you have to a minimum by setting `dbms.tx_log.rotation.retention_policy` to `keep_none`, starting the database up and then shutting it down again. The startup and shutdown will create a new checkpoint which will end with unnecessary log files being pruned away. The `keep_none` setting will leave one transaction log file behind, which is necessary for the database to verify that it doesn't need to do recovery, when it starts.

https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/#config_dbms.tx_log.rotation.retention_policy

**Comment by tricepat** [comment]
In the case that all transaction logs were deleted, how do I get around the "no check point" error?

**Comment by codyAnivive** [comment]
Any update on this?

**Comment by lazyonemax** [comment]
In the case that all transaction logs were deleted, how do I get around the "no check point" error?

**Comment by chrisvest** [comment]
If you have a support contract, you should ask for help via that channel first.

Otherwise, you can try to set `unsupported.dbms.tx_log.fail_on_corrupted_log_files=true` in `neo4j.conf`. There will likely be inconsistencies in the data after this, though.

**Comment by lazyonemax** [comment]
cannot start yet set unsupported.dbms.tx_log.fail_on_corrupted_log_files=true 

`
2019-08-08 02:24:28.782+0000 WARN [o.n.k.NeoStoreDataSource] Exception occurred while starting the datasource. Attempting to close things down. Component 'org.neo4j.kernel.recovery.Recovery@795fd838' failed to initialize. Please see the attached cause exception "No check point found in any log file from version 107 to 107".
org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.recovery.Recovery@795fd838' failed to initialize. Please see the attached cause exception "No check point found in any log file from version 107 to 107".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:434)
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:66)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:102)
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:444)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:116)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:225)
        at com.neo4j.commercial.edition.CommercialGraphDatabase.<init>(CommercialGraphDatabase.java:20)
        at com.neo4j.server.database.CommercialGraphFactory.newGraphDatabase(CommercialGraphFactory.java:40)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.impl.store.UnderlyingStorageException: No check point found in any log file from version 107 to 107
        at org.neo4j.kernel.recovery.RecoveryStartInformationProvider.get(RecoveryStartInformationProvider.java:108)
        at org.neo4j.kernel.recovery.DefaultRecoveryService.getRecoveryStartInformation(DefaultRecoveryService.java:61)
        at org.neo4j.kernel.recovery.Recovery.init(Recovery.java:67)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:413)
        ... 18 more
2019-08-08 02:24:28.786+0000 INFO [o.n.i.d.DiagnosticsManager] --- STOPPING diagnostics START ---
2019-08-08 02:24:28.786+0000 INFO [o.n.i.d.DiagnosticsManager] --- STOPPING diagnostics END ---
2019-08-08 02:24:28.787+0000 INFO [o.n.g.f.GraphDatabaseFacadeFactory] Shutdown started
`
