### ISSUE TITLE
 Unexpected thread death

### ISSUE THREAD

**Issue by meshmmanuel** [neo4j/neo4j#12083]
**My neo4j server started to deny user access, restart and stop access. When I checked the log, I found this:**

  GNU nano 2.0.9                                                                  File: neo4j.log

2018-11-15 11:30:05.106+0000 INFO  ======== Neo4j 3.4.9 ========
2018-11-15 11:30:05.196+0000 INFO  Starting...
2018-11-15 11:30:09.036+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2018-11-15 11:30:11.024+0000 INFO  Started.
2018-11-15 11:30:12.079+0000 INFO  Remote interface available at http://0.0.0.0:7474/
2018-11-15 17:37:32.940+0000 WARN   Java heap space
java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.addConditionWaiter(AbstractQueuedSynchronizer.java:1855)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2068)
        at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:392)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.idleJobPoll(QueuedThreadPool.java:653)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.access$800(QueuedThreadPool.java:48)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:717)
        at java.lang.Thread.run(Thread.java:748)
2018-11-15 17:37:32.955+0000 WARN   Java heap space
java.lang.OutOfMemoryError: Java heap space
        at java.util.HashMap$KeySet.iterator(HashMap.java:917)
        at java.util.HashSet.iterator(HashSet.java:173)
        at sun.nio.ch.SelectorImpl.processDeregisterQueue(SelectorImpl.java:145)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:97)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        at sun.nio.ch.SelectorImpl.selectNow(SelectorImpl.java:105)
        at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:401)
        at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
        at java.lang.Thread.run(Thread.java:748)
2018-11-15 17:37:32.955+0000 WARN  Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@151f924a in QueuedThreadPool[qtp1461565620]@571db8b4{STARTED,8<=14<=14,i=0,q=2}[ReservedThreadExecutor@11201431{s=1/1,p=1}]
2018-11-15 17:37:32.955+0000 WARN   Java heap space
java.lang.OutOfMemoryError: Java heap space
2018-11-15 17:37:32.956+0000 WARN  Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@151f924a in QueuedThreadPool[qtp1461565620]@571db8b4{STARTED,8<=14<=14,i=0,q=2}[ReservedThreadExecutor@11201431{s=1/1,p=1}]

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "neo4j.Scheduler-1"
2018-11-15 19:49:27.390+0000 WARN   Java heap space
java.lang.OutOfMemoryError: Java heap space
2018-11-15 19:49:27.390+0000 WARN  Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@151f924a in QueuedThreadPool[qtp1461565620]@571db8b4{STARTED,8<=8<=14,i=0,q=0}[ReservedThreadExecutor@11201431{s=0/1,p=0}]
2018-11-16 11:14:04.730+0000 INFO  Neo4j Server shutdown initiated by request

Please what can I do?

**Here is my conf file**

  GNU nano 2.0.9                                                              File: /etc/neo4j/neo4j.conf

Neo4j configuration

dbms.directories.import=/var/lib/neo4j/import

dbms.memory.heap.initial_size=4G

dbms.memory.heap.max_size=12G

dbms.memory.pagecache.size=10g

**Comment by chrisvest** [comment]
You need to either increase the heap.max_size, or make your transactions smaller (assuming that's where the memory was going, which might be an incorrect assumption), or have fewer transactions running concurrently. The last two points are about reducing peak heap usage.

There is no rule to tell you exactly how much memory you need for what. You'll need to look at your JVM monitoring (if you have any) and your usage patterns to figure out what your configuration should look like.

If you have Neo4j installed in a way that it is automatically restarted if the server exits abruptly, then you can try adding `dbms.jvm.additional=-XX:+ExitOnOutOfMemoryError` to your `neo4j.conf`, as a stop-gap measure. It'll cause the server to exit whenever it would otherwise have thrown an OOME.
