### ISSUE TITLE
Neo4j Desktop: Neo4j 3.5.0 Fails to start on mac mojave after upgrade from 3.4.9

### ISSUE THREAD

**Issue by neurofoo** [neo4j/neo4j#12098]
Using Neo4j Desktop Version 1.1.13 (1.1.13.1058)

Upgraded database from 3.4.9 to 3.5.0 using the desktop app upgrade tools (manage > upgrade). I don't think that I clicked the additional option checkbox that I recall being there.

Upgraded the plugins (APOC v3.5.0.1, Graph Algorithms v3.5.0.1, GraphQL v3.5.0.1).

On start, fails with the error message below.
I have 3 indexes that are apparently (now) using deprecated providers. Not sure if this root of the problem.

Created a fresh 3.5 database and that runs without issues.

```
Active database: graph.db
Directories in use:
  home:         /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-876f21eb-d67c-4611-82b4-829bd06cc71a/installation-3.5.0
  config:       /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-876f21eb-d67c-4611-82b4-829bd06cc71a/installation-3.5.0/conf
  logs:         /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-876f21eb-d67c-4611-82b4-829bd06cc71a/installation-3.5.0/logs
  plugins:      /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-876f21eb-d67c-4611-82b4-829bd06cc71a/installation-3.5.0/plugins
  import:       /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-876f21eb-d67c-4611-82b4-829bd06cc71a/installation-3.5.0/import
  data:         /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-876f21eb-d67c-4611-82b4-829bd06cc71a/installation-3.5.0/data
  certificates: /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-876f21eb-d67c-4611-82b4-829bd06cc71a/installation-3.5.0/certificates
  run:          /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-876f21eb-d67c-4611-82b4-829bd06cc71a/installation-3.5.0/run
Starting Neo4j.
2018-11-29 19:16:21.372+0000 WARN  ha.pull_interval is deprecated.
2018-11-29 19:16:21.388+0000 INFO  ======== Neo4j 3.5.0 ========
2018-11-29 19:16:21.390+0000 INFO  Starting...
2018-11-29 19:16:22.152+0000 INFO  Initiating metrics...
2018-11-29 19:16:22.964+0000 INFO  Deprecated index providers in use: lucene+native-2.0 (3 indexes). Use procedure 'db.indexes()' to see what indexes use which index provider.
2018-11-29 19:16:27.496+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@72b88762' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@72b88762' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@72b88762' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:184)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:122)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@72b88762' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:177)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-876f21eb-d67c-4611-82b4-829bd06cc71a/installation-3.5.0/data/databases
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
	at com.neo4j.commercial.edition.CommercialGraphDatabase.<init>(CommercialGraphDatabase.java:20)
	at com.neo4j.server.database.CommercialGraphFactory.newGraphDatabase(CommercialGraphFactory.java:40)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:78)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@3c657771' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:203)
	... 9 more
Caused by: org.neo4j.internal.kernel.api.exceptions.ProcedureException: Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.
	at org.neo4j.kernel.impl.proc.ProcedureRegistry.register(ProcedureRegistry.java:87)
	at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:138)
	at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:93)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:326)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 11 more
2018-11-29 19:16:27.496+0000 INFO  Neo4j Server shutdown initiated by request
```

**Comment by neurofoo** [comment]
Am able to reproduce this.
- Create a new db version 3.4.9 in desktop
- install the noted plugins
- open browser

```
CREATE (a:Node {id: apoc.create.uuid()});
CREATE INDEX ON :Node(id);
```

close browser, shutdown database. 
Go to manage, upgrade.
Upgrade to 3.5.0 and do no check the migration checkbox.
Upgrade looks okay.
Latest plugins there.

Start it. Boom, hello error message (as before):

```
Active database: graph.db
Directories in use:
  home:         /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7a77bb7e-a93b-453c-a1a8-fbc561d988b1/installation-3.5.0
  config:       /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7a77bb7e-a93b-453c-a1a8-fbc561d988b1/installation-3.5.0/conf
  logs:         /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7a77bb7e-a93b-453c-a1a8-fbc561d988b1/installation-3.5.0/logs
  plugins:      /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7a77bb7e-a93b-453c-a1a8-fbc561d988b1/installation-3.5.0/plugins
  import:       /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7a77bb7e-a93b-453c-a1a8-fbc561d988b1/installation-3.5.0/import
  data:         /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7a77bb7e-a93b-453c-a1a8-fbc561d988b1/installation-3.5.0/data
  certificates: /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7a77bb7e-a93b-453c-a1a8-fbc561d988b1/installation-3.5.0/certificates
  run:          /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7a77bb7e-a93b-453c-a1a8-fbc561d988b1/installation-3.5.0/run
Starting Neo4j.
2018-11-29 20:13:51.192+0000 WARN  ha.pull_interval is deprecated.
2018-11-29 20:13:51.206+0000 INFO  ======== Neo4j 3.5.0 ========
2018-11-29 20:13:51.209+0000 INFO  Starting...
2018-11-29 20:13:51.889+0000 INFO  Initiating metrics...
2018-11-29 20:13:52.674+0000 INFO  Deprecated index providers in use: lucene+native-2.0 (1 index). Use procedure 'db.indexes()' to see what indexes use which index provider.
2018-11-29 20:13:57.495+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@268215b3' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@268215b3' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@268215b3' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:184)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:122)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@268215b3' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:177)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7a77bb7e-a93b-453c-a1a8-fbc561d988b1/installation-3.5.0/data/databases
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
	at com.neo4j.commercial.edition.CommercialGraphDatabase.<init>(CommercialGraphDatabase.java:20)
	at com.neo4j.server.database.CommercialGraphFactory.newGraphDatabase(CommercialGraphFactory.java:40)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:78)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@622be81d' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:203)
	... 9 more
Caused by: org.neo4j.internal.kernel.api.exceptions.ProcedureException: Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.
	at org.neo4j.kernel.impl.proc.ProcedureRegistry.register(ProcedureRegistry.java:87)
	at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:138)
	at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:93)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:326)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 11 more
2018-11-29 20:13:57.496+0000 INFO  Neo4j Server shutdown initiated by request
```

**Comment by neurofoo** [comment]
Make new 3.4.9 database. 
Do as above.
This time click the 'migration' checkbox.
Upgrade fails with following error message:

```
Active database: graph.db
Directories in use:
  home:         /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-4b1fb4fe-6e24-4b8c-a9cf-9e1ae35b25c0/installation-3.5.0
  config:       /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-4b1fb4fe-6e24-4b8c-a9cf-9e1ae35b25c0/installation-3.5.0/conf
  logs:         /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-4b1fb4fe-6e24-4b8c-a9cf-9e1ae35b25c0/installation-3.5.0/logs
  plugins:      /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-4b1fb4fe-6e24-4b8c-a9cf-9e1ae35b25c0/installation-3.5.0/plugins
  import:       /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-4b1fb4fe-6e24-4b8c-a9cf-9e1ae35b25c0/installation-3.5.0/import
  data:         /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-4b1fb4fe-6e24-4b8c-a9cf-9e1ae35b25c0/installation-3.5.0/data
  certificates: /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-4b1fb4fe-6e24-4b8c-a9cf-9e1ae35b25c0/installation-3.5.0/certificates
  run:          /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-4b1fb4fe-6e24-4b8c-a9cf-9e1ae35b25c0/installation-3.5.0/run
Starting Neo4j.
2018-11-29 20:19:03.723+0000 WARN  ha.pull_interval is deprecated.
2018-11-29 20:19:03.738+0000 INFO  ======== Neo4j 3.5.0 ========
2018-11-29 20:19:03.741+0000 INFO  Starting...
2018-11-29 20:19:04.486+0000 INFO  Initiating metrics...
2018-11-29 20:19:05.339+0000 INFO  Deprecated index providers in use: lucene+native-2.0 (1 index). Use procedure 'db.indexes()' to see what indexes use which index provider.
2018-11-29 20:19:10.329+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@49a6503f' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@49a6503f' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@49a6503f' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:184)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:122)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@49a6503f' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:177)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /Users/donald/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-4b1fb4fe-6e24-4b8c-a9cf-9e1ae35b25c0/installation-3.5.0/data/databases
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
	at com.neo4j.commercial.edition.CommercialGraphDatabase.<init>(CommercialGraphDatabase.java:20)
	at com.neo4j.server.database.CommercialGraphFactory.newGraphDatabase(CommercialGraphFactory.java:40)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:78)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@622be81d' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:203)
	... 9 more
Caused by: org.neo4j.internal.kernel.api.exceptions.ProcedureException: Unable to register procedure, because the name `apoc.periodic.cancel` is already in use.
	at org.neo4j.kernel.impl.proc.ProcedureRegistry.register(ProcedureRegistry.java:87)
	at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:138)
	at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:93)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:326)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 11 more
2018-11-29 20:19:10.330+0000 INFO  Neo4j Server shutdown initiated by request
```

**Comment by neurofoo** [comment]
Use the new db (from previous post).
Start. Go to browser. Drop index.
Try upgrade with migration again.
Fails as before.

**Comment by Hunterness** [comment]
Hi, thanks for reporting this problem. We will look into it and get back to you.

**Comment by craigtaverner** [comment]
@neurofoo My impression from reading this is that there might be two versions of the procedure library in the plugins folder. Since you are using Neo4j Desktop to manage your plugins, I'm expecting this is a bug in Neo4j Desktop, and have changed the labels accordingly, so that team can investigate.

In the meantime, could you see if you can find the relevant plugins folder and verify if there are two versions of the same plugin JAR in that directory? If there are, delete the incorrect one (based on Neo4j version) and restart the database and see if the problem is resolved.

**Comment by neurofoo** [comment]
@craigtaverner thanks! that was the issue. 

I went to the plugins dir and found the previous version of the apoc, graphql, and graphalgos there in addition to the new ones for 3.5.  

Once I removed the previous versions, the db booted up fine.

Thanks!
