### ISSUE TITLE
"Did not find any type information for expression" error after upgrading to 3.5

### ISSUE THREAD

**Issue by tolomaus** [neo4j/neo4j#12100]
Hi,

I have loaded my neo4j database via `neo4j-admin import`, one of the source datasets is AnnualAccount with id reference (field name in the csv file: `reference:ID(AnnualAccount)`)

I got the following error when executing a cypher query with `OPTIONAL MATCH (company)-[:HAS]->(annualAccount:AnnualAccount) WHERE company.annualAccountReference = annualAccount.reference`

This has always worked just fine on version 3.4.x and before until I upgraded to 3.5 a moment ago. Running on aws ec2 centos, installed using yum.

```
2018-12-02 14:26:31.154+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.Statement.ExecutionFailed]: Did not find any type information for expression Property(Variable(annualAccount),PropertyKeyName(reference)), reference 62005d51-b852-448a-a663-e295b25dc6d4.
2018-12-02 14:26:31.154+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.Statement.ExecutionFailed]: Did not find any type information for expression Property(Variable(annualAccount),PropertyKeyName(reference)), reference 62005d51-b852-448a-a663-e295b25dc6d4. Did not find any type information for expression Property(Variable(annualAccount),PropertyKeyName(reference))
org.neo4j.kernel.impl.query.QueryExecutionKernelException: Did not find any type information for expression Property(Variable(annualAccount),PropertyKeyName(reference))
	at org.neo4j.bolt.v1.runtime.TransactionStateMachineV1SPI$BoltResultHandleV1.start(TransactionStateMachineV1SPI.java:203)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.startExecution(TransactionStateMachine.java:506)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.execute(TransactionStateMachine.java:300)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:269)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:110)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:98)
	at org.neo4j.bolt.v1.runtime.ReadyState.processRunMessage(ReadyState.java:140)
	at org.neo4j.bolt.v1.runtime.ReadyState.processRunMessage(ReadyState.java:100)
	at org.neo4j.bolt.v1.runtime.ReadyState.process(ReadyState.java:61)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.kernel.impl.query.QueryExecutionKernelException: Did not find any type information for expression Property(Variable(annualAccount),PropertyKeyName(reference))
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:89)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachineV1SPI$BoltResultHandleV1.start(TransactionStateMachineV1SPI.java:189)
	... 19 more
Caused by: org.neo4j.cypher.InternalException: Did not find any type information for expression Property(Variable(annualAccount),PropertyKeyName(reference))
	at org.neo4j.cypher.exceptionHandler$.internalException(exceptionHandler.scala:45)
	at org.neo4j.cypher.exceptionHandler$.internalException(exceptionHandler.scala:26)
	at org.opencypher.v9_0.util.InternalException.mapToPublic(CypherException.scala:80)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:94)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner.parseAndPlan(Cypher35Planner.scala:116)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler.compile(CypherCurrentCompiler.scala:82)
	at org.neo4j.cypher.internal.MasterCompiler.innerCompile$1(MasterCompiler.scala:115)
	at org.neo4j.cypher.internal.MasterCompiler.compile(MasterCompiler.scala:150)
	at org.neo4j.cypher.internal.ExecutionEngine$$anonfun$compilers$3.apply(ExecutionEngine.scala:136)
	at org.neo4j.cypher.internal.ExecutionEngine$$anonfun$compilers$3.apply(ExecutionEngine.scala:136)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:167)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:126)
	at org.neo4j.cypher.internal.ExecutionEngine.getOrCompile(ExecutionEngine.scala:156)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:95)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:85)
	... 20 more
Caused by: org.opencypher.v9_0.util.InternalException: Did not find any type information for expression Property(Variable(annualAccount),PropertyKeyName(reference))
	at org.opencypher.v9_0.ast.semantics.SemanticTable$$anonfun$getActualTypeFor$1.apply(SemanticTable.scala:55)
	at org.opencypher.v9_0.ast.semantics.SemanticTable$$anonfun$getActualTypeFor$1.apply(SemanticTable.scala:55)
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
	at org.opencypher.v9_0.ast.ASTAnnotationMap.getOrElse(ASTAnnotationMap.scala:27)
	at org.opencypher.v9_0.ast.semantics.SemanticTable.getActualTypeFor(SemanticTable.scala:55)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.steps.AbstractIndexSeekLeafPlanner$$anonfun$asIndexCompatiblePredicate$1.applyOrElse(AbstractIndexSeekLeafPlanner.scala:173)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.steps.AbstractIndexSeekLeafPlanner$$anonfun$asIndexCompatiblePredicate$1.applyOrElse(AbstractIndexSeekLeafPlanner.scala:160)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:141)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:140)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
	at scala.collection.TraversableLike$class.collect(TraversableLike.scala:271)
	at scala.collection.AbstractTraversable.collect(Traversable.scala:104)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.steps.AbstractIndexSeekLeafPlanner.producePlanFor(AbstractIndexSeekLeafPlanner.scala:58)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.steps.OrLeafPlanner$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(OrLeafPlanner.scala:39)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.steps.OrLeafPlanner$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(OrLeafPlanner.scala:39)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.steps.OrLeafPlanner$$anonfun$apply$1$$anonfun$1.apply(OrLeafPlanner.scala:39)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.steps.OrLeafPlanner$$anonfun$apply$1$$anonfun$1.apply(OrLeafPlanner.scala:38)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.steps.OrLeafPlanner$$anonfun$apply$1.apply(OrLeafPlanner.scala:37)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.steps.OrLeafPlanner$$anonfun$apply$1.apply(OrLeafPlanner.scala:33)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.steps.OrLeafPlanner.apply(OrLeafPlanner.scala:33)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.LeafPlannerList$$anonfun$1.apply(LeafPlannerIterable.scala:37)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.LeafPlannerList$$anonfun$1.apply(LeafPlannerIterable.scala:37)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.LeafPlannerList.candidates(LeafPlannerIterable.scala:37)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.steps.leafPlanOptions$.apply(leafPlanOptions.scala:35)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.SingleComponentPlanner.planComponent(SingleComponentPlanner.scala:46)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPQueryGraphSolver$$anonfun$planComponents$1.apply(IDPQueryGraphSolver.scala:80)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPQueryGraphSolver$$anonfun$planComponents$1.apply(IDPQueryGraphSolver.scala:79)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPQueryGraphSolver.planComponents(IDPQueryGraphSolver.scala:79)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPQueryGraphSolver.plan(IDPQueryGraphSolver.scala:59)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.steps.applyOptional$.apply(solveOptionalMatches.scala:35)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPQueryGraphSolver$$anonfun$2.apply(IDPQueryGraphSolver.scala:101)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPQueryGraphSolver$$anonfun$2.apply(IDPQueryGraphSolver.scala:101)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:355)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPQueryGraphSolver.recurse$1(IDPQueryGraphSolver.scala:101)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPQueryGraphSolver.connectComponentsAndSolveOptionalMatch(IDPQueryGraphSolver.scala:115)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPQueryGraphSolver.plan(IDPQueryGraphSolver.scala:62)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.planPart$.apply(QueryPlanner.scala:127)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.PlanSingleQuery.apply(PlanSingleQuery.scala:47)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:106)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:104)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.QueryPlanner.planQueries(QueryPlanner.scala:104)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.QueryPlanner.plan(QueryPlanner.scala:94)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.QueryPlanner.process(QueryPlanner.scala:72)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.QueryPlanner.process(QueryPlanner.scala:33)
	at org.opencypher.v9_0.frontend.phases.Phase$$anonfun$transform$1.apply(Phase.scala:35)
	at org.opencypher.v9_0.frontend.helpers.package$$anonfun$closing$1.apply(package.scala:23)
	at org.opencypher.v9_0.frontend.helpers.package$$anonfun$closing$1.apply(package.scala:23)
	at org.opencypher.v9_0.frontend.helpers.package$.using(package.scala:31)
	at org.opencypher.v9_0.frontend.helpers.package$.closing(package.scala:23)
	at org.opencypher.v9_0.frontend.phases.Phase$class.transform(Phase.scala:34)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.QueryPlanner.transform(QueryPlanner.scala:33)
	at org.opencypher.v9_0.frontend.phases.PipeLine.transform(Transformer.scala:59)
	at org.opencypher.v9_0.frontend.phases.PipeLine.transform(Transformer.scala:59)
	at org.opencypher.v9_0.frontend.phases.PipeLine.transform(Transformer.scala:59)
	at org.opencypher.v9_0.frontend.phases.PipeLine.transform(Transformer.scala:59)
	at org.opencypher.v9_0.frontend.phases.PipeLine.transform(Transformer.scala:63)
	at org.opencypher.v9_0.frontend.phases.If.transform(Transformer.scala:88)
	at org.opencypher.v9_0.frontend.phases.PipeLine.transform(Transformer.scala:63)
	at org.neo4j.cypher.internal.compiler.v3_5.CypherPlanner.planPreparedQuery(CypherPlanner.scala:57)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner$$anonfun$parseAndPlan$1.org$neo4j$cypher$internal$compatibility$v3_5$Cypher35Planner$$anonfun$$createPlan$1(Cypher35Planner.scala:151)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner$$anonfun$parseAndPlan$1$$anonfun$6.apply(Cypher35Planner.scala:169)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner$$anonfun$parseAndPlan$1$$anonfun$6.apply(Cypher35Planner.scala:169)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:167)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:126)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner$$anonfun$parseAndPlan$1.apply(Cypher35Planner.scala:167)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner$$anonfun$parseAndPlan$1.apply(Cypher35Planner.scala:116)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	... 31 more
```

**Comment by Hunterness** [comment]
Hi, thanks for reporting. We will look into it and get back to you.

**Comment by tolomaus** [comment]
I got this error while using the neo4j java driver (from scala) version 1.6.1. I just checked and it turns out that neo4j 3.5 is only supported from version 1.7 on. As soon as I have some time I will do another test

**Comment by Hunterness** [comment]
Hi again, for us to be able to look into this we need a sample database where the problem occurs. Could you provide us with that?

**Comment by tolomaus** [comment]
Hi Hunterness,

I tested with the new neo4j java driver 1.7.2 and the issue hasn't come resurfaced so I'm going to close the issue. Thx
