### ISSUE TITLE
Running 2 instances of embedded neo4j, store and its lock file has been locked by another process

### ISSUE THREAD

**Issue by vmandrychenko** [neo4j/neo4j#12133]
We run embedded db for dev purposes on our development computers, at the same time we are also starting embedded db to run integration tests (think Scalatest or JUnit) on our development machines. It seems that new lock behaviour in 3.5 is preventing us from using two separate embedded dbs in different directories (see below) on different ports in parallel. This is blocking the upgrade from 3.4 to 3.5.

- Neo4j version: 3.5.1
- Operating system: (Mac OS Mojave 10.14.2)
- API/Driver: (for example Cypher Bolt v3.5.1)

### Steps to reproduce
1. Run embedded database for development purpose as part of Play application. 
2. Run integration test that spins up it's own imbedded database on the same machine. 

### Expected behavior
Test passes when embedded db running

### Actual behavior
Test is failing to start due to:

```
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter@3de3253f' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: /private/var/folders/hg/wb_rmvqd4cvbjsyv3l8msprm0000gn/T/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
    at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
    at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:135)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:133)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(GraphDatabaseFactory.java:122)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory$EmbeddedDatabaseCreator.newDatabase(GraphDatabaseFactory.java:178)
    at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:210)
    at com.garnercorp.lighthouse.persistence.graphing.neo4j.connection.embedded.EmbeddedDatabase$.createDatabase(EmbeddedDatabase.scala:42)
    at com.garnercorp.lighthouse.persistence.graphing.neo4j.connection.embedded.EmbeddedDatabase$.initialize(EmbeddedDatabase.scala:20)
Caused by: org.neo4j.kernel.StoreLockException: Store and its lock file has been locked by another process: /private/var/folders/hg/wb_rmvqd4cvbjsyv3l8msprm0000gn/T/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)
    at org.neo4j.kernel.internal.locker.StoreLocker.storeLockException(StoreLocker.java:116)
    at org.neo4j.kernel.internal.locker.StoreLocker.checkLock(StoreLocker.java:92)
    at org.neo4j.kernel.internal.locker.GlobalStoreLocker.checkLock(GlobalStoreLocker.java:61)
    at org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter.start(StoreLockerLifecycleAdapter.java:36)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
    at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
    at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:135)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:133)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(GraphDatabaseFactory.java:122)```

**Comment by vmandrychenko** [comment]
When we create a DB we store it in the temp directory with timestamp to avoid clashing: 
`/var/folders/hg/wb_rmvqd4cvbjsyv3l8msprm0000gn/T/EmbeddedNeo4jDB4307589988154436220104461888733163`

Store lock file is located here: 
`/private/var/folders/hg/wb_rmvqd4cvbjsyv3l8msprm0000gn/T/store_lock`


Note `private` and also, why is store lock not in the same directory as DB directory?

```bash 
ls -l /var/folders/hg/wb_rmvqd4cvbjsyv3l8msprm0000gn/T/EmbeddedNeo4jDB4307589988154436220104461888733163
total 624
drwxr-xr-x  2 vmandrychenko  staff      64 11 Jan 11:06 index
-rw-r--r--  1 vmandrychenko  staff    8192 11 Jan 11:06 neostore
-rw-r--r--  1 vmandrychenko  staff      96 11 Jan 11:06 neostore.counts.db.a
-rw-r--r--  1 vmandrychenko  staff       9 11 Jan 11:06 neostore.id
-rw-r--r--  1 vmandrychenko  staff   40960 11 Jan 11:06 neostore.labelscanstore.db
-rw-r--r--  1 vmandrychenko  staff       0 11 Jan 11:06 neostore.labeltokenstore.db
-rw-r--r--  1 vmandrychenko  staff       9 11 Jan 11:06 neostore.labeltokenstore.db.id
-rw-r--r--  1 vmandrychenko  staff    8192 11 Jan 11:06 neostore.labeltokenstore.db.names
-rw-r--r--  1 vmandrychenko  staff       9 11 Jan 11:06 neostore.labeltokenstore.db.names.id
-rw-r--r--  1 vmandrychenko  staff       0 11 Jan 11:06 neostore.nodestore.db
-rw-r--r--  1 vmandrychenko  staff       9 11 Jan 11:06 neostore.nodestore.db.id
-rw-r--r--  1 vmandrychenko  staff    8192 11 Jan 11:06 neostore.nodestore.db.labels
-rw-r--r--  1 vmandrychenko  staff       9 11 Jan 11:06 neostore.nodestore.db.labels.id
-rw-r--r--  1 vmandrychenko  staff       0 11 Jan 11:06 neostore.propertystore.db
-rw-r--r--  1 vmandrychenko  staff    8192 11 Jan 11:06 neostore.propertystore.db.arrays
-rw-r--r--  1 vmandrychenko  staff       9 11 Jan 11:06 neostore.propertystore.db.arrays.id
-rw-r--r--  1 vmandrychenko  staff       9 11 Jan 11:06 neostore.propertystore.db.id
-rw-r--r--  1 vmandrychenko  staff       0 11 Jan 11:06 neostore.propertystore.db.index
-rw-r--r--  1 vmandrychenko  staff       9 11 Jan 11:06 neostore.propertystore.db.index.id
-rw-r--r--  1 vmandrychenko  staff    8192 11 Jan 11:06 neostore.propertystore.db.index.keys
-rw-r--r--  1 vmandrychenko  staff       9 11 Jan 11:06 neostore.propertystore.db.index.keys.id
-rw-r--r--  1 vmandrychenko  staff    8192 11 Jan 11:06 neostore.propertystore.db.strings
-rw-r--r--  1 vmandrychenko  staff       9 11 Jan 11:06 neostore.propertystore.db.strings.id
-rw-r--r--  1 vmandrychenko  staff    8192 11 Jan 11:06 neostore.relationshipgroupstore.db
-rw-r--r--  1 vmandrychenko  staff       9 11 Jan 11:06 neostore.relationshipgroupstore.db.id
-rw-r--r--  1 vmandrychenko  staff       0 11 Jan 11:06 neostore.relationshipstore.db
-rw-r--r--  1 vmandrychenko  staff       9 11 Jan 11:06 neostore.relationshipstore.db.id
-rw-r--r--  1 vmandrychenko  staff       0 11 Jan 11:06 neostore.relationshiptypestore.db
-rw-r--r--  1 vmandrychenko  staff       9 11 Jan 11:06 neostore.relationshiptypestore.db.id
-rw-r--r--  1 vmandrychenko  staff    8192 11 Jan 11:06 neostore.relationshiptypestore.db.names
-rw-r--r--  1 vmandrychenko  staff       9 11 Jan 11:06 neostore.relationshiptypestore.db.names.id
-rw-r--r--  1 vmandrychenko  staff    8192 11 Jan 11:06 neostore.schemastore.db
-rw-r--r--  1 vmandrychenko  staff       9 11 Jan 11:06 neostore.schemastore.db.id
-rw-r--r--  1 vmandrychenko  staff  116055 11 Jan 11:06 neostore.transaction.db.0
drwxr-xr-x  3 vmandrychenko  staff      96 11 Jan 11:06 schema```

**Comment by chrisvest** [comment]
As part of preparing to natively support multiple databases at runtime, the store lock file has been moved to the parent directory of the individual database directories. For backwards compatibility, we cannot change how pointing the embedded graph database factories at a directory, will start a database in that directory. You'll have to move your databases down one directory level to work around it.

**Comment by vmandrychenko** [comment]
Thanks for a quick response, I will give it a shot.

**Comment by KamalMalik** [comment]
@vmandrychenko and @chrisvest is this issue going to resolved in future neo4j release. currently trying to upgrade to 3.5.8 facing the same issue. 

Why store_lock file has been moved the parent directory to the databases, not allowing to create new database in same parent directory.

Any quick fix solution for the same will be appreciated.
