### ISSUE TITLE
Neo4J crashed while running and failing on restart

### ISSUE THREAD

**Issue by saleel** [neo4j/neo4j#12131]
Got this error when NEO4J was running

```
{ Neo4jError: The database has encountered a critical error, and needs to be restarted. Please see database logs for more details.

    at captureStacktrace (/www/node_modules/neo4j-driver/lib/v1/result.js:200:15)
    at new Result (/www/node_modules/neo4j-driver/lib/v1/result.js:73:19)
    at _newRunResult (/www/node_modules/neo4j-driver/lib/v1/transaction.js:342:10)
    at Object.run (/www/node_modules/neo4j-driver/lib/v1/transaction.js:251:14)
    at Transaction.run (/www/node_modules/neo4j-driver/lib/v1/transaction.js:120:26)
    at session.readTransaction (file:///www/src/neo4j.mjs:25:34)
    at TransactionExecutor._safeExecuteTransactionWork (/www/node_modules/neo4j-driver/lib/v1/internal/transaction-executor.js:136:22)
    at TransactionExecutor._executeTransactionInsidePromise (/www/node_modules/neo4j-driver/lib/v1/internal/transaction-executor.js:124:32)
    at /www/node_modules/neo4j-driver/lib/v1/internal/transaction-executor.js:67:15
    at new Promise (/www/node_modules/core-js/library/modules/es6.promise.js:177:7)
    at TransactionExecutor.execute (/www/node_modules/neo4j-driver/lib/v1/internal/transaction-executor.js:66:14)
    at Session._runTransaction (/www/node_modules/neo4j-driver/lib/v1/session.js:290:40)
    at Session.readTransaction (/www/node_modules/neo4j-driver/lib/v1/session.js:261:19)
    at Driver.neo4jDriver.execReadQuery (file:///www/src/neo4j.mjs:24:20)
    at Object.find (file:///www/src/services/nodes/nodes.service.mjs:150:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'Neo.DatabaseError.Transaction.TransactionStartFailed',
  name: 'Neo4jError' }
```

When attempted to restart, the following error came

```
Caused by: java.io.UncheckedIOException: java.io.IOException: Quota exceeded | GB+Tree[file:/data/databases/graph.db/neostore.labelscanstore.db, layout:LabelScanLayout[version:0.1, identifier:21483684112629824, fixedSize:true], generation:1/2]
    at org.neo4j.index.internal.gbptree.GBPTree.<init>(GBPTree.java:508)
    at org.neo4j.kernel.impl.index.labelscan.NativeLabelScanStore.instantiateTree(NativeLabelScanStore.java:356)
    at org.neo4j.kernel.impl.index.labelscan.NativeLabelScanStore.init(NativeLabelScanStore.java:314)
    at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.init(RecordStorageEngine.java:376)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:413)
    ... 18 more
Caused by: java.io.IOException: Quota exceeded
    at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
    at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:90)
    at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1115)
    at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
    at org.neo4j.io.fs.StoreFileChannel.tryLock(StoreFileChannel.java:142)
    at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.acquireLock(SingleFilePageSwapper.java:224)
    at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.<init>(SingleFilePageSwapper.java:178)
    at org.neo4j.io.pagecache.impl.SingleFilePageSwapperFactory.createPageSwapper(SingleFilePageSwapperFactory.java:66)
    at org.neo4j.io.pagecache.impl.muninn.MuninnPagedFile.<init>(MuninnPagedFile.java:149)
    at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.map(MuninnPageCache.java:408)
    at org.neo4j.index.internal.gbptree.GBPTree.openExistingIndexFile(GBPTree.java:574)
    at org.neo4j.index.internal.gbptree.GBPTree.openOrCreate(GBPTree.java:563)
    at org.neo4j.index.internal.gbptree.GBPTree.<init>(GBPTree.java:469)
    ... 22 more
2019-01-10 09:15:26.207+0000 INFO  Neo4j Server shutdown initiated by request
```

- Neo4j version: 3.5.0
- Operating system: CentOs/ docker
- API/Driver: Initial error while using Javascript Driver, restart was tried from cli

Could not find details on `Quota exceeded | GB+Tree` error anywhere. Is this related to disk space or memory limit?

### Steps to reproduce
N/A as this is likely to be specific to our DB or ENV.
DB has about 2.7 million nodes.

### Expected behavior
neo4j should be started without any errors

### Actual behavior
Getting the above error while starting neo4j

**Comment by kcrimson** [comment]
Is your database running on NetApp storage? This seems to be an error from NetApp about disk size limit/quota.

**Comment by saleel** [comment]
We are using EFS from AWS. There is no disk quota issue as well.

It started working on redeploy. Closing the issue for now.
