### ISSUE TITLE
Import error in Docker Container

### ISSUE THREAD

**Issue by tlxnithin** [neo4j/neo4j#12151]
- Neo4j version: 3.4.9
- Environment: Docker

- **Steps to reproduce**
Bring up the docker container. Copy some CSV files to container to import.
```
docker exec -it bash -c "./bin/neo4j-import \
--into ./data/databases/graph.db \
--id-type string \
--nodes:Movie ./movies.csv \
--nodes:User ./users.csv"
```

- Expected behavior
Should be importing the data.
- Actual behavior
Getting the below exception.

```
Import error: org.neo4j.io.pagecache.impl.FileLockException: Externally locked: /data/databases/graph.db/neostore
Caused by:org.neo4j.io.pagecache.impl.FileLockException: Externally locked: /data/databases/graph.db/neostore
org.neo4j.kernel.impl.store.UnderlyingStorageException: org.neo4j.io.pagecache.impl.FileLockException: Externally locked: /data/databases/graph.db/neostore
        at org.neo4j.kernel.impl.store.NeoStores.verifyRecordFormat(NeoStores.java:226)
        at org.neo4j.kernel.impl.store.NeoStores.<init>(NeoStores.java:143)
        at org.neo4j.kernel.impl.store.StoreFactory.openNeoStores(StoreFactory.java:160)
        at org.neo4j.kernel.impl.store.StoreFactory.openAllNeoStores(StoreFactory.java:124)
        at org.neo4j.unsafe.impl.batchimport.store.BatchingNeoStores.instantiateStores(BatchingNeoStores.java:235)
        at org.neo4j.unsafe.impl.batchimport.store.BatchingNeoStores.createNew(BatchingNeoStores.java:177)
        at org.neo4j.unsafe.impl.batchimport.ParallelBatchImporter.doImport(ParallelBatchImporter.java:84)
        at org.neo4j.tooling.ImportTool.doImport(ImportTool.java:583)
        at org.neo4j.tooling.ImportTool.main(ImportTool.java:483)
        at org.neo4j.tooling.ImportTool.main(ImportTool.java:378)
        Suppressed: java.lang.IllegalStateException: VM pause monitor is not started
                at org.neo4j.util.Preconditions.checkState(Preconditions.java:75)
                at org.neo4j.kernel.monitoring.VmPauseMonitor.stop(VmPauseMonitor.java:70)
                at org.neo4j.unsafe.impl.batchimport.staging.OnDemandDetailsExecutionMonitor.done(OnDemandDetailsExecutionMonitor.java:128)
                at org.neo4j.unsafe.impl.batchimport.staging.MultiExecutionMonitor.done(MultiExecutionMonitor.java:82)
                at org.neo4j.unsafe.impl.batchimport.staging.MultiExecutionMonitor.done(MultiExecutionMonitor.java:82)
                at org.neo4j.unsafe.impl.batchimport.ImportLogic.close(ImportLogic.java:517)
                at org.neo4j.unsafe.impl.batchimport.ParallelBatchImporter.doImport(ParallelBatchImporter.java:96)
                ... 3 more
Caused by: org.neo4j.io.pagecache.impl.FileLockException: Externally locked: /data/databases/graph.db/neostore
        at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.acquireLock(SingleFilePageSwapper.java:211)
        at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.<init>(SingleFilePageSwapper.java:162)
        at org.neo4j.io.pagecache.impl.SingleFilePageSwapperFactory.createPageSwapper(SingleFilePageSwapperFactory.java:71)
        at org.neo4j.io.pagecache.impl.muninn.MuninnPagedFile.<init>(MuninnPagedFile.java:150)
        at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.map(MuninnPageCache.java:401)
        at org.neo4j.kernel.impl.store.MetaDataStore.getRecord(MetaDataStore.java:291)
        at org.neo4j.kernel.impl.store.NeoStores.verifyRecordFormat(NeoStores.java:207)
        ... 9 more

WARNING Import failed. The store files in /var/lib/neo4j/./data/databases/graph.db are left as they are, although they are likely in an unusable state. Starting a database on these store files will likely fail or observe inconsistent records so start at your own risk or delete the store manually

```

**Comment by tlxnithin** [comment]
I took the 3.5.2 version for Linux and installed. Not the docker version. But still getting the same error.
Is it because the neo4j browser is connected to the DB?? If that is connected will we not be able to use neo4j-import?

If not what I am doing wrong here. Need some advice and help.

**Comment by tlxnithin** [comment]
I was able to import after I did [this](https://stackoverflow.com/questions/44757181/store-and-its-lock-file-has-been-locked-by-another-process-var-lib-neo4j-data). (Not resolved in Docker though)

So if browser is connected, we will not be able to use the import tool on the same database.
Also once we import, we can not do it again for a different CSV on the same database, Is it?

I have a use case where we get large CSV data every day, and we have to import those CSVs. So as we can not use import tool over and over, Is "LOAD CSV" cypher is the only option here?

**Comment by tomaszalusky** [comment]
I had similar problem and finally understood I cannot invoke `neo4j-admin import` if database has been once used, which is documented [here](https://stackoverflow.com/a/65688089/653539). 
The import tool just needs db unlocked. [Here is my investigation.](https://stackoverflow.com/a/65688089/653539)
Anyway, still I don't get why manual [advises](https://neo4j.com/docs/operations-manual/current/docker/operations/#docker-neo4j-import) `exec`-ing `neo4j-admin import` on running container.

**Comment by mskyttner** [comment]
I also don't understand how to use `neo4j-admin import` on a running container. The documentation at https://neo4j.com/docs/operations-manual/current/tutorial/neo4j-admin-import/ says "The neo4j-admin import command can be used on the local Neo4j instance even if the instance is running or not.", which sounds promising and in line with what some other RDMS containers support (such as the official images for mariadb, mysql, postgres which supports data to be loaded into a running container non-interactively).

There seems to be some mechanism for EXTENSION_SCRIPT in /docker-entrypoint.sh to allow for startup scripts (the main point of which would be to load data and add indexes I guess), but I seem to run into these issues:

- https://github.com/neo4j/docker-neo4j/issues/166
- https://github.com/neo4j/docker-neo4j/issues/151

Perhaps we need to raise a separate issue for this, ie how to start neo4j container with data bulk loaded using neo4j-admin import in a non-interactive way (without requiring removal of lock files).

**Comment by mskyttner** [comment]
And perhaps this issue should be reopened if this issue is not resolved when using docker?
