### ISSUE TITLE
neo4j 2.2.3 can't start after crashed

### ISSUE THREAD

**Issue by heipark** [neo4j/neo4j#12156]
- Neo4j version: neo4j-community-2.2.3
- Operating system: centos 5.7

neo4j 2.2.3 can't start after crashed，message below：
(i remove neostore.transaction.db.* and retry，but not work.)

2019-02-12 06:17:33.667+0000 INFO  [o.n.k.i.DiagnosticsManager]: --- INITIALIZED diagnostics END ---
2019-02-12 06:17:47.376+0000 INFO  [o.n.k.i.a.i.IndexingService]: IndexingService.init: index 1 on :label[0](property[0]) is ONLINE
2019-02-12 06:18:05.052+0000 INFO  [o.n.k.i.a.i.IndexingService]: IndexingService.init: index 2 on :label[0](property[1]) is ONLINE
2019-02-12 06:18:10.331+0000 INFO  [o.n.k.i.a.i.IndexingService]: IndexingService.init: index 3 on :label[0](property[2]) is ONLINE
2019-02-12 06:18:38.297+0000 INFO  [o.n.k.i.a.i.IndexingService]: IndexingService.init: index 5 on :label[1](property[0]) is ONLINE
2019-02-12 06:19:19.957+0000 INFO  [o.n.k.i.a.i.IndexingService]: IndexingService.init: index 6 on :label[1](property[1]) is ONLINE
2019-02-12 06:19:33.386+0000 ERROR [o.n.k.NeoStoreDataSource]: **Exception occurred while starting the datasource. Attempting to close things down.
org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.api.index.IndexingService@471d3df1' failed to initialize. Please see attached cause exceptio
n.**
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:489) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:72) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:106) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:530) ~[neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:117) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:331) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:59) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.server.database.LifecycleManagingDatabase$1.newGraphDatabase(LifecycleManagingDatabase.java:44) [neo4j-server-2.2.3.jar:2.2.3]
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:110) [neo4j-server-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:203) [neo4j-server-2.2.3.jar:2.2.3]
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:117) [neo4j-server-2.2.3.jar:2.2.3]
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:69) [neo4j-server-2.2.3.jar:2.2.3]
Caused by: java.lang.RuntimeException: java.nio.channels.ClosedByInterruptException
        at org.neo4j.kernel.api.index.util.FailureStorage.loadIndexFailure(FailureStorage.java:100) ~[neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.api.impl.index.LuceneSchemaIndexProvider.getInitialState(LuceneSchemaIndexProvider.java:119) ~[neo4j-lucene-index-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.impl.api.index.IndexingService.init(IndexingService.java:219) ~[neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:483) [neo4j-kernel-2.2.3.jar:2.2.3]
        ... 17 common frames omitted
**Caused by: java.nio.channels.ClosedByInterruptException: null**
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202) ~[na:1.7.0_75]
        at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:312) ~[na:1.7.0_75]
        at org.neo4j.kernel.api.index.util.FailureStorage.isFailed(FailureStorage.java:170) ~[neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.api.index.util.FailureStorage.loadIndexFailure(FailureStorage.java:92) ~[neo4j-kernel-2.2.3.jar:2.2.3]
        ... 20 common frames omitted
2019-02-12 06:19:33.459+0000 INFO  [o.n.k.i.s.StoreFactory]: About to rotate counts store at transaction 9783056 to [/home/admin/neo4j-community-2.2.3/data/graph.db/neostor
e.counts.db.b], from [/home/admin/neo4j-community-2.2.3/data/graph.db/neostore.counts.db.a].
2019-02-12 06:19:33.469+0000 ERROR [o.n.k.i.s.StoreFactory]: Failed to rotate counts store at transaction 9783056 to [/home/admin/neo4j-community-2.2.3/data/graph.db/neosto
re.counts.db.b], from [/home/admin/neo4j-community-2.2.3/data/graph.db/neostore.counts.db.a].
java.nio.channels.ClosedByInterruptException: null
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202) ~[na:1.7.0_75]
        at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:312) ~[na:1.7.0_75]
        at org.neo4j.io.fs.StoreFileChannel.size(StoreFileChannel.java:165) ~[neo4j-io-2.2.3.jar:2.2.3]
        at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.<init>(SingleFilePageSwapper.java:69) ~[neo4j-io-2.2.3.jar:2.2.3]
        at org.neo4j.io.pagecache.impl.SingleFilePageSwapperFactory.createPageSwapper(SingleFilePageSwapperFactory.java:50) ~[neo4j-io-2.2.3.jar:2.2.3]
        at org.neo4j.io.pagecache.impl.muninn.MuninnPagedFile.<init>(MuninnPagedFile.java:91) ~[neo4j-io-2.2.3.jar:2.2.3]
        at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.map(MuninnPageCache.java:327) ~[neo4j-io-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.impl.store.kvstore.KeyValueWriter$OpeningStreamWriter.open(KeyValueWriter.java:336) ~[neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.impl.store.kvstore.KeyValueWriter.openStoreFile(KeyValueWriter.java:110) ~[neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.impl.store.kvstore.KeyValueStoreFileFormat.create(KeyValueStoreFileFormat.java:199) ~[neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.impl.store.kvstore.KeyValueStoreFileFormat.createStore(KeyValueStoreFileFormat.java:59) ~[neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.impl.store.kvstore.RotationStrategy.next(RotationStrategy.java:106) ~[neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:81) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.impl.store.kvstore.DeadState$Prepared$1.rotate(DeadState.java:284) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:278) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:259) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.impl.store.counts.CountsTracker.rotate(CountsTracker.java:140) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.impl.store.NeoStore.closeStorage(NeoStore.java:296) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.impl.store.CommonAbstractStore.close(CommonAbstractStore.java:720) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:539) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:117) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:331) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:59) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.server.database.LifecycleManagingDatabase$1.newGraphDatabase(LifecycleManagingDatabase.java:44) [neo4j-server-2.2.3.jar:2.2.3]
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:110) [neo4j-server-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115) [neo4j-kernel-2.2.3.jar:2.2.3]
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:203) [neo4j-server-2.2.3.jar:2.2.3]
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:117) [neo4j-server-2.2.3.jar:2.2.3]
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:69) [neo4j-server-2.2.3.jar:2.2.3]
2019-02-12 06:19:33.469+0000 INFO  [o.n.k.NeoStoreDataSource]: Couldn't close neostore after startup failure
2019-02-12 06:19:33.471+0000 INFO  [o.n.k.i.DiagnosticsManager]: --- STOPPING diagnostics START ---
2019-02-12 06:19:33.471+0000 INFO  [o.n.k.i.DiagnosticsManager]: --- STOPPING diagnostics END ---

**Comment by chrisvest** [comment]
> i remove neostore.transaction.db.* and retry，but not work.

Don't do that. I suggest you restore from backup if you have one.

What you could have tried was removing or renaming the `/schema` directory. Something somewhere appears to be interrupting threads in the database as it is starting up. If you have any plugins or extensions, or if you are running the database in embedded mode, then you need to look for the source of thread interrupts, and eliminate it.

**Comment by heipark** [comment]
> > i remove neostore.transaction.db.* and retry，but not work.
> 
> Don't do that. I suggest you restore from backup if you have one.
> 
> What you could have tried was removing or renaming the `/schema` directory. Something somewhere appears to be interrupting threads in the database as it is starting up. If you have any plugins or extensions, or if you are running the database in embedded mode, then you need to look for the source of thread interrupts, and eliminate it.

can't start also, and not import clue，so.. i finally init db.  thx
