### ISSUE TITLE
neo4j-admin import tool hanging

### ISSUE THREAD

**Issue by dmsolow** [neo4j/neo4j#12169]
Here's the bit at the starting:

```
Available resources:
  Total machine memory: 29.45 GB
  Free machine memory: 2.20 GB
  Max heap memory : 6.54 GB
  Processors: 8
  Configured max memory: 20.61 GB
  High-IO: false

WARNING: heap size 6.54 GB is unnecessarily large for completing this import.
The abundant heap memory will leave less memory for off-heap importer caches. Suggested heap size is 1.04 GBImport starting 2019-02-25 20:08:15.863+0000
  Estimated number of nodes: 263.39 M
  Estimated number of node properties: 624.26 M
  Estimated number of relationships: 280.82 M
  Estimated number of relationship properties: 44.26 M
  Estimated disk space usage: 54.30 GB
  Estimated required memory usage: 4.23 GB

InteractiveReporterInteractions command list (end with ENTER):
  c: Print more detailed information about current stage
  i: Print more detailed information

(1/4) Node import 2019-02-25 20:08:15.918+0000
  Estimated number of nodes: 263.39 M
  Estimated disk space usage: 43.72 GB
  Estimated required memory usage: 4.23 GB
```

It hangs during node import at 45%. Here's the full stack trace: https://gist.github.com/dmsolow/44933dbf39dba01866ea482da24c4726

The only RUNNABLE thread that looks interesting is:

```
"SortWorker-0" #68 prio=5 os_prio=0 tid=0x00005649072cc000 nid=0x8f runnable [0x00007f0b2237b000]
   java.lang.Thread.State: RUNNABLE
	at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort$SortWorker.partition(ParallelSort.java:294)
	at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort$SortWorker.qsort(ParallelSort.java:337)
	at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort$SortWorker.run(ParallelSort.java:272)
	at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.Workers$Worker.run(Workers.java:126)
```

Any ideas on how to approach this?

**Comment by InverseFalcon** [comment]
Which version of Neo4j are you using?

**Comment by dmsolow** [comment]
This was a bug on my end. I was including an extra field in the header. Surprised that the import tool didn't complain earlier, but when I fixed the bug it started working.

**Comment by ravwojdyla** [comment]
I run into this issue as well. I believe this shouldn't have been closed, Neo4j should handle this issue and possibly throw exception on inconsistency between header and row size, otherwise it just hangs forever. Neo4j version I run into this issue: 3.4.8

**Comment by ravwojdyla** [comment]
@dmsolow or @InverseFalcon could you please reopen?

**Comment by tinwelint** [comment]
The importer does report if there are more data columns than header columns or if nodes/relationships are missing mandatory fields, see https://neo4j.com/docs/operations-manual/3.5/tools/import/ . Other mismatches are hard to do 100% accurately. What's an example of header line and data line that you had problems with?
