### ISSUE TITLE
Neo.DatabaseError.General.UnknownError: Connection has been shutdown: javax.net.ssl.SSLException: SSL peer shut down incorrectly

### ISSUE THREAD

**Issue by Manish-Giri** [neo4j/neo4j#12191]
I'm trying to import large datasets into Neo4J using Cypher. Because the datasets (csv files) are quite large (~100-200MB each), I use `USING PERIODIC COMMIT 100` statements in each query.

I was able to import 3 csv files, with each import taking about 6 minutes on average. However, starting from the 4th csv file, the spinner just keeps spinning and after about 10 minutes or so, I get the error - 

> Neo.DatabaseError.General.UnknownError: Connection has been shutdown: javax.net.ssl.SSLException: SSL peer shut down incorrectly

Screenshot - 

![Screenshot 2019-04-06 02 30 25](https://user-images.githubusercontent.com/11348778/55665879-7f4f3b80-5814-11e9-9a20-b0cce97f04b6.png)

- Neo4j version: 3.5.3
- Operating system: (for example Windows 95/Ubuntu 16.04): Mac OSX High Sierra
- API/Driver: (for example Cypher/Java API/Python driver vX.Y.Z): Cypher

**Comment by jexp** [comment]
Can you share EXPLAIN plan of your statement?

**Comment by MrDNA2018** [comment]
i have the same story: Neo.DatabaseError.General.UnknownError: Connection has been shutdown: javax.net.ssl.SSLException: SSL peer shut down incorrectly
USING PERIODIC COMMIT 10
LOAD CSV WITH HEADERS FROM "https://raw.githubusercontent.com/************************-reportorname.csv" AS row
MERGE (c:Persons {name: coalesce(row.reportorname,'is_empty')})

**Comment by kcrimson** [comment]
if this is possible can you share EXPLAIN statement output and debug.log file?

**Comment by tolik505** [comment]
I also have the problem
`{
  "statement": {
    "text": "explain USING PERIODIC COMMIT 1000 LOAD CSV WITH HEADERS FROM 'https://...' AS csv_line FIELDTERMINATOR '|' FOREACH (sth IN CASE WHEN csv_line.FREF_SECURITY_TYPE IN ['ADR', 'ALIEN', 'DR', 'GDR', 'NVDR', 'PREF', 'PREFEQ', 'RIGHT', 'SAVING', 'SHARE', 'STRUCT', 'TEMP', 'UNIT', 'WARRANT'] THEN [1] END | CREATE (:Security {uuid: csv_line.UUID, currency: csv_line.CURRENCY, proper_name: csv_line.PROPER_NAME }) )",
    "parameters": {}
  },
  "statementType": "w",
  "counters": {
    "_stats": {
      "nodesCreated": 0,
      "nodesDeleted": 0,
      "relationshipsCreated": 0,
      "relationshipsDeleted": 0,
      "propertiesSet": 0,
      "labelsAdded": 0,
      "labelsRemoved": 0,
      "indexesAdded": 0,
      "indexesRemoved": 0,
      "constraintsAdded": 0,
      "constraintsRemoved": 0
    }
  },
  "updateStatistics": {
    "_stats": {
      "nodesCreated": 0,
      "nodesDeleted": 0,
      "relationshipsCreated": 0,
      "relationshipsDeleted": 0,
      "propertiesSet": 0,
      "labelsAdded": 0,
      "labelsRemoved": 0,
      "indexesAdded": 0,
      "indexesRemoved": 0,
      "constraintsAdded": 0,
      "constraintsRemoved": 0
    }
  },
  "plan": {
    "operatorType": "ProduceResults",
    "identifiers": [
      "csv_line"
    ],
    "arguments": {
      "planner-impl": "IDP",
      "planner-version": "3.5",
      "runtime-version": "3.5",
      "runtime": "SLOTTED",
      "runtime-impl": "SLOTTED",
      "version": "CYPHER 3.5",
      "EstimatedRows": 1,
      "planner": "COST"
    },
    "children": [
      {
        "operatorType": "EmptyResult",
        "identifiers": [
          "csv_line"
        ],
        "arguments": {
          "EstimatedRows": 1
        },
        "children": [
          {
            "operatorType": "Foreach",
            "identifiers": [
              "csv_line"
            ],
            "arguments": {
              "EstimatedRows": 1
            },
            "children": [
              {
                "operatorType": "LoadCSV",
                "identifiers": [
                  "csv_line"
                ],
                "arguments": {
                  "EstimatedRows": 1
                },
                "children": []
              },
              {
                "operatorType": "Create",
                "identifiers": [
                  "  UNNAMED389",
                  "csv_line",
                  "sth"
                ],
                "arguments": {
                  "EstimatedRows": 1
                },
                "children": [
                  {
                    "operatorType": "Argument",
                    "identifiers": [
                      "csv_line",
                      "sth"
                    ],
                    "arguments": {
                      "EstimatedRows": 1
                    },
                    "children": []
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  "profile": false,
  "notifications": [],
  "server": {
    "address": "...",
    "version": "Neo4j/3.5.3"
  },
  "resultConsumedAfter": {
    "low": 0,
    "high": 0
  },
  "resultAvailableAfter": {
    "low": 1,
    "high": 0
  }
}`

**Debug log**
`2019-07-04 09:46:32.896+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: Connection has been shutdown: javax.net.ssl.SSLException: SSL peer shut down incorrectly, reference 0ea4273d-e679-446b-b2d0-ccee9146fc29.
2019-07-04 09:46:32.896+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: Connection has been shutdown: javax.net.ssl.SSLException: SSL peer shut down incorrectly, reference 0ea4273d-e679-446b-b2d0-ccee9146fc29. Connection has been shutdown: javax.net.ssl.SSLException: SSL peer shut down incorrectly
javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: SSL peer shut down incorrectly
	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1533)
	at sun.security.ssl.AppInputStream.available(AppInputStream.java:60)
	at java.io.BufferedInputStream.available(BufferedInputStream.java:410)
	at sun.net.www.MeteredStream.available(MeteredStream.java:170)
	at sun.net.www.http.KeepAliveStream.close(KeepAliveStream.java:85)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.close(HttpURLConnection.java:3517)
	at java.io.PushbackInputStream.close(PushbackInputStream.java:379)
	at sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:378)
	at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:193)
	at java.io.InputStreamReader.close(InputStreamReader.java:199)
	at org.neo4j.csv.reader.WrappedCharReadable.close(WrappedCharReadable.java:73)
	at org.neo4j.csv.reader.AutoReadingSource.close(AutoReadingSource.java:94)
	at org.neo4j.csv.reader.BufferedCharSeeker.close(BufferedCharSeeker.java:392)
	at org.neo4j.cypher.internal.runtime.interpreted.CSVResource.close(CSVResources.scala:59)
	at org.neo4j.cypher.internal.runtime.ResourceManager.close(ResourceManager.scala:54)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$2.apply(CypherCurrentCompiler.scala:188)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$2.apply(CypherCurrentCompiler.scala:188)
	at org.neo4j.cypher.internal.v3_5.util.TaskCloser$$anonfun$close$1.apply(TaskCloser.scala:43)
	at org.neo4j.cypher.internal.v3_5.util.TaskCloser$$anonfun$close$1.apply(TaskCloser.scala:41)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.neo4j.cypher.internal.v3_5.util.TaskCloser.close(TaskCloser.scala:40)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$4.apply(CypherCurrentCompiler.scala:224)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$4.apply(CypherCurrentCompiler.scala:224)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:108)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery.execute(CypherCurrentCompiler.scala:224)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:102)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:85)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachineV1SPI$BoltResultHandleV1.start(TransactionStateMachineV1SPI.java:189)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.startExecution(TransactionStateMachine.java:506)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.execute(TransactionStateMachine.java:300)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:269)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:110)
	at org.neo4j.bolt.v3.runtime.ReadyState.processRunMessage(ReadyState.java:85)
	at org.neo4j.bolt.v3.runtime.ReadyState.processUnsafe(ReadyState.java:56)
	at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
	at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.lambda$enqueue$0(MetricsReportingBoltConnection.java:68)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
	at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.processNextBatch(MetricsReportingBoltConnection.java:86)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:596)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3444)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.PushbackInputStream.read(PushbackInputStream.java:186)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at org.neo4j.csv.reader.SectionedCharBuffer.readFrom(SectionedCharBuffer.java:134)
	at org.neo4j.csv.reader.SectionedCharBuffer.readFrom(SectionedCharBuffer.java:123)
	at org.neo4j.csv.reader.WrappedCharReadable.read(WrappedCharReadable.java:46)
	at org.neo4j.csv.reader.AutoReadingSource.nextChunk(AutoReadingSource.java:49)
	at org.neo4j.csv.reader.BufferedCharSeeker.fillBuffer(BufferedCharSeeker.java:357)
	at org.neo4j.csv.reader.BufferedCharSeeker.nextChar(BufferedCharSeeker.java:317)
	at org.neo4j.csv.reader.BufferedCharSeeker.seek(BufferedCharSeeker.java:101)
	at org.neo4j.cypher.internal.runtime.interpreted.CSVResources$$anon$1.readNextRow(CSVResources.scala:81)
	at org.neo4j.cypher.internal.runtime.interpreted.CSVResources$$anon$1.next(CSVResources.scala:105)
	at org.neo4j.cypher.internal.runtime.interpreted.CSVResources$$anon$1.next(CSVResources.scala:76)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.LoadCsvIterator.next(LoadCsvIterator.scala:30)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.LoadCsvIterator.next(LoadCsvIterator.scala:24)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.LoadCSVPipe$IteratorWithHeaders.computeNextRow(LoadCSVPipe.scala:84)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.LoadCSVPipe$IteratorWithHeaders.hasNext(LoadCSVPipe.scala:70)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EmptyResultPipe.internalCreateResults(EmptyResultPipe.scala:28)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:76)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:72)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.BaseExecutionResultBuilderFactory$BaseExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:61)
	at org.neo4j.cypher.internal.compatibility.InterpretedRuntime$InterpretedExecutionPlan.run(InterpretedRuntime.scala:84)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$3.apply(CypherCurrentCompiler.scala:205)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$3.apply(CypherCurrentCompiler.scala:190)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	... 24 more
`

**Comment by kingrocy** [comment]
i also have the same problem,but i slove it. 
The reason for this problem is because your command may not be correct, which causes neo4j to need a lot of resources to execute.
I will explain my problem as a sample.
There is a 60,000 line csv file. I need to take him to do the following

`
LOAD CSV WITH HEADERS FROM 'https://xxxxx/xx.csv' AS LINE 
merge(:CarModel{
	name:line.model_name,
	model_code:line.model_code,
	model_name:line.model_name,
	series_name:line.series_name,
	brand_name:line.brand_name,
	manufacture:line.manufacture,
	country:line.country,
	fuel_form:line.fuel_form,
	market_time:line.market_time,
	level:line.level,
	wheel_base:line.wheel_base,
	site_num:line.site_num,
	guide_price:line.guide_price,
	driving_mode:line.driving_mode,
	rate_space:line.rate_space,
	rate_power:line.rate_power,
	rate_control:line.rate_control,
	rate_fuel:line.rate_fuel,
	rate_comfortable:line.rate_comfortable,
	rate_exterior:line.rate_exterior,
	rate_trim:line.rate_trim,
	rate_price:line.rate_price,
	official_accelerate:line.official_accelerate,
	official_oil_wear:line.official_oil_wear,
	vehicle_type:line.vehicle_type,
	accelerate_compare:line.accelerate_compare,
	fuel_compare:line.fuel_compare,
	gear_box_type:line.gear_box_type,
	model_year:line.model_year,
	display_tag:line.display_tag
})
`
The above command will report an error after a few minutes of execution. the error is same to yours.

the error command use the merge operat.that means neo4j will first do match then create when execute the command. the node has lots of properties. this need too much resource .so the connection is timeout.

at the end,i change the merge command to create. it work success.

I hope my experience can help you.

**Comment by tolik505** [comment]
My files are large (~3 GB), I've made workaround by splitting them into smaller parts.
