### ISSUE TITLE
Neo4j Admin Import didn't report with id-space collision occurred

### ISSUE THREAD

**Issue by bsquire0128** [neo4j/neo4j#12193]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests.  If you have questions on how to use Neo4j, please ask on [StackOverflow](http://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

If you want to make a feature request then there is no guideline, so feel free to stop reading and open an issue. If you have a bug report however, please continue reading.
To help us understand your issue, please specify important details, primarily:

- Neo4j version: Enterprise 3.5.3
- Operating system: Linux
- API/Driver: OpenJDK 1.8.0_201
- **Steps to reproduce**
`~/../../../usr/bin/neo4j-admin import --nodes "import/uids-header.csv,import/uid_no." --nodes "import/ga-header.csv,import/ggl_no." --nodes "import/citystate-header.csv,import/city_no." --relationships:OBSERVED_WITH "import/rels-header.csv,import/ggl_li.* --relationships:VISITED_FROM "import/rels-header.csv,import/city_li.*" --ignore-missing-nodes --delimiter="~" --high-io=true --id-type=integer`
- Expected behavior
Error message that explains where the collision took place, sort of like IMPORT FAILED in 3h 37m 21s 862ms.
Data statistics is not available.
Peak memory usage: 0.00 B
Error in input data
Caused by:ERROR in input
data source: BufferedCharSeeker[source:/var/lib/neo4j/import/ggl_no0035_part_00.csv, position:1896888, line:33873]
in field: :LABEL:3
for header: [node_id:ID, google_id:string, :LABEL]
raw field value: Google
original error: Id 4294967295 is reserved and can't be used as a regular record id
- Actual behavior
Exception in thread "Thread-18" java.lang.RuntimeException: org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.DuplicateInputIdException: Id '1154243009' is defined more than once in group 'global id space'
at org.neo4j.unsafe.impl.batchimport.staging.AbstractStep.issuePanic(AbstractStep.java:155)
at org.neo4j.unsafe.impl.batchimport.staging.AbstractStep.issuePanic(AbstractStep.java:147)
at org.neo4j.unsafe.impl.batchimport.staging.LonelyProcessingStep.lambda$receive$0(LonelyProcessingStep.java:59)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.DuplicateInputIdException: Id '1154243009' is defined more than once in group 'global id space'
at org.neo4j.unsafe.impl.batchimport.input.BadCollector$NodesProblemReporter.exception(BadCollector.java:278)
at org.neo4j.unsafe.impl.batchimport.input.BadCollector.collect(BadCollector.java:168)
at org.neo4j.unsafe.impl.batchimport.input.BadCollector.collectDuplicateNode(BadCollector.java:135)
at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.EncodingIdMapper.detectDuplicateInputIds(EncodingIdMapper.java:606)
at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.EncodingIdMapper.buildCollisionInfo(EncodingIdMapper.java:522)
at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.EncodingIdMapper.prepare(EncodingIdMapper.java:239)
at org.neo4j.unsafe.impl.batchimport.IdMapperPreparationStep.process(IdMapperPreparationStep.java:56)
at org.neo4j.unsafe.impl.batchimport.staging.LonelyProcessingStep.lambda$receive$0(LonelyProcessingStep.java:53)
... 1 more

IMPORT FAILED in 1h 31m 19s 634ms.
Data statistics is not available.
Peak memory usage: 39.25 GB
Duplicate input ids that would otherwise clash can be put into separate id space, read more about how to use id spaces in the manual: https://neo4j.com/docs/operations-manual/3.5/tools/import/file-header-format/#import-tool-id-spaces
Caused by:Id '1154243009' is defined more than once in group 'global id space'

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

With out knowing which file(s) '1154243009' is in I can't fix the issue without grep many many GB of files.

**Comment by bsquire0128** [comment]
I was reviewing my import cmd and found it had created one of the node files twice such as:
`~/../../../usr/bin/neo4j-admin import --nodes "import/uids-header.csv,import/uid_no." --nodes "import/ga-header.csv,import/ggl_no." --nodes "import/ga-header.csv,import/ggl_no." --nodes "import/citystate-header.csv,import/city_no." --relationships:OBSERVED_WITH "import/rels-header.csv,import/ggl_li.* --relationships:VISITED_FROM "import/rels-header.csv,import/city_li.*" --ignore-missing-nodes --delimiter="~" --high-io=true --id-type=integer`

This is why the global space was messing up. Now that I know what caused it, it would still be useful for a better error message if it can trace where the id collision occurred from. I had to grep 600 GB of  files to find which node-type it came from, if it had said collision from ggl_no123 or something it would be easier to debug where the issue was.

**Comment by tinwelint** [comment]
As of 3.5 there's a check for supplying input files multiple times, which will result in warnings printed out. Due to the parallel nature of the csv file reading it's technically a bit challenging to get precise line numbers, but I'm sure it should be possible. File name and byte position would be simple :) would that be enough?
