### ISSUE TITLE
Install user-defined plugin error

### ISSUE THREAD

**Issue by crazyyanchao** [neo4j/neo4j#12198]
version: ($NEO4J_HOME/plugin/)
apoc-3.4.0.1-all.jar
graph-algorithms-algo-3.4.7.0.jar
zdr_neo4j_workshop-1.0.0.jar (my jar) 
```java
2019-04-12 08:03:33.739+0000 INFO  Neo4j Server shutdown initiated by request
¾¯¸æ: This command does not appear to be running with administrative rights.  Some commands may fail e.g. Start/Stop
2019-04-12 08:12:51.593+0000 INFO  ======== Neo4j 3.4.4 ========
2019-04-12 08:12:51.653+0000 INFO  Starting...
2019-04-12 08:12:56.041+0000 INFO  Initiating metrics...
2019-04-12 08:13:04.878+0000 INFO  Sending metrics to CSV file at C:\Users\11416\.Neo4jDesktop\neo4jDatabases\database-ed7de0f9-129e-4602-866c-9b1196cd6e3c\installation-3.4.1\metrics
2019-04-12 08:13:07.949+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.all)
2019-04-12 08:13:07.953+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.idle)
2019-04-12 08:13:08.450+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2019-04-12 08:13:17.960+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@50e0b472' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@50e0b472' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@50e0b472' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@50e0b472' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, C:\Users\11416\.Neo4jDesktop\neo4jDatabases\database-ed7de0f9-129e-4602-866c-9b1196cd6e3c\installation-3.4.1\data\databases\linkedinGraphPerOrg.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
	at org.neo4j.kernel.enterprise.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:39)
	at org.neo4j.server.enterprise.OpenEnterpriseNeoServer.lambda$static$1(OpenEnterpriseNeoServer.java:78)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@dbcf7c3' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
	... 9 more
Caused by: java.lang.UnsupportedClassVersionError: module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:137)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:114)
	at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
	at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:87)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:78)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:323)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 11 more
```

zdr_neo4j_workshop-1.0.0.jar (my jar) 
pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>casia.isiteam.zdr</groupId>
    <artifactId>zdr_neo4j_workshop</artifactId>
    <version>1.0.0</version>

    <properties>
        <neo4j.version>3.4.9</neo4j.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <!-- This gives us the Procedure API our runtime code uses.
                 We have a `provided` scope on it, because when this is
                 deployed in a Neo4j Instance, the API will be provided
                 by Neo4j. If you add non-Neo4j dependencies to this
                 project, their scope should normally be `compile` -->
            <groupId>org.neo4j</groupId>
            <artifactId>neo4j</artifactId>
            <version>${neo4j.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- Test Dependencies -->
        <dependency>
            <!-- This is used for a utility that lets us start Neo4j with
                 a specific Procedure, which is nice for writing tests. -->
            <groupId>org.neo4j.test</groupId>
            <artifactId>neo4j-harness</artifactId>
            <version>${neo4j.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <!-- Used to send cypher statements to our procedure. -->
            <groupId>org.neo4j.driver</groupId>
            <artifactId>neo4j-java-driver</artifactId>
            <version>1.4.2</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.alibaba/fastjson -->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.47</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.2</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.ecf</groupId>
            <artifactId>org.apache.log4j</artifactId>
            <version>1.2.15.v201012070815</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.neo4j.procedure/apoc -->
        <dependency>
            <groupId>org.neo4j.procedure</groupId>
            <artifactId>apoc</artifactId>
            <version>3.4.0.1</version>
        </dependency>

        <!--<dependency>-->
            <!--<groupId>casia.isiteam</groupId>-->
            <!--<artifactId>ikanalyzer</artifactId>-->
            <!--<version>5.0</version>-->
        <!--</dependency>-->

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <!-- Neo4j Procedures require Java 8 -->
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <!-- This generates a jar-file with our procedure code,
                     plus any dependencies marked as `compile` scope.
                     This should then be deployed in the `plugins` directory
                     of each Neo4j instance in your deployment.
                     After a restart, the procedure is available for calling. -->
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.4.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>

                        <!--<configuration>-->
                            <!--<filters>-->
                                <!--<filter>-->
                                    <!--<artifact>*:*</artifact>-->
                                    <!--<excludes>-->
                                        <!--<exclude>META-INF/*.SF</exclude>-->
                                        <!--<exclude>META-INF/*.DSA</exclude>-->
                                        <!--<exclude>META-INF/*.RSA</exclude>-->
                                    <!--</excludes>-->
                                <!--</filter>-->
                            <!--</filters>-->
                        <!--</configuration>-->

                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

```
ELSE ， I found a warning when I executed maven install 
```
[INFO] Including org.apache.commons:commons-math3:jar:3.6.1 in the shaded jar.
[WARNING] accessors-smart-1.1.jar, asm-6.2.jar define 24 overlapping classes: 
[WARNING]   - org.objectweb.asm.Type
[WARNING]   - org.objectweb.asm.AnnotationVisitor
[WARNING]   - org.objectweb.asm.MethodVisitor
[WARNING]   - org.objectweb.asm.Attribute
[WARNING]   - org.objectweb.asm.FieldWriter
[WARNING]   - org.objectweb.asm.signature.SignatureWriter
[WARNING]   - org.objectweb.asm.Edge
[WARNING]   - org.objectweb.asm.MethodWriter
[WARNING]   - org.objectweb.asm.Handler
[WARNING]   - org.objectweb.asm.ByteVector
[WARNING]   - 14 more...
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/
[INFO] Replacing original artifact with shaded artifact.
```

**Comment by Hunterness** [comment]
Hi, thanks for reporting. We will look into it :)

**Comment by chrisvest** [comment]
@crazyyanchao Looking at the exception:

> `Caused by: java.lang.UnsupportedClassVersionError: module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

This appears to be saying that your JAR file, or one of its dependencies, is compiled and built with Java 11 (or at least version 9 or greater) and you are starting Neo4j with Java 8. Make sure that you are actually using Java 8 when building the JAR file, make sure you don't have any module-info.java files, and look through your dependencies to make sure that they work on Java 8.

**Comment by crazyyanchao** [comment]
> @crazyyanchao Looking at the exception:
> 
> > `Caused by: java.lang.UnsupportedClassVersionError: module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0`
> 
> This appears to be saying that your JAR file, or one of its dependencies, is compiled and built with Java 11 (or at least version 9 or greater) and you are starting Neo4j with Java 8. Make sure that you are actually using Java 8 when building the JAR file, make sure you don't have any module-info.java files, and look through your dependencies to make sure that they work on Java 8.

Idea can be used when compiling.It work on Java 8.Just,It reported an error while I packaging the plug-in for installation.

**Comment by crazyyanchao** [comment]
@chrisvest Thanks for your reply.
> > @crazyyanchao Looking at the exception:
> > > `Caused by: java.lang.UnsupportedClassVersionError: module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0`
> > 
> > 
> > This appears to be saying that your JAR file, or one of its dependencies, is compiled and built with Java 11 (or at least version 9 or greater) and you are starting Neo4j with Java 8. Make sure that you are actually using Java 8 when building the JAR file, make sure you don't have any module-info.java files, and look through your dependencies to make sure that they work on Java 8.
> 
> Idea can be used when compiling.It work on Java 8.Just,It reported an error while I packaging the plug-in for installation.

**Comment by SUBHAMILA** [comment]
Hi,
I am getting similar error, can you help me with it.
Thanks.
below is the error :
 recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)

**Comment by chrisvest** [comment]
This is always the same: you are asking an older JDK to load classes compiled with a newer JDK.

Either you are running Neo4j 4.0 on Java 8, or you are running Neo4j 3.x on Java 8, but you added a plug-in or extension that is compiled with Java 11.

The solution is to either downgrade or recompile that plug-in to work on Java 8 if you are using Neo4j 3.x, or to upgrade the JDK you are deploying on to Java 11 if you are using Neo4j 4.x.

Here is a list of class file versions for reference: https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers

**Comment by fssrepository** [comment]
You are uploading released versions compiled with java 11, which does not work with latest community edition fuck sake.
