### ISSUE TITLE
NullPointerException in org.neo4j.bolt.v1.transport.ChunkedOutput.close(ChunkedOutput.java:231)

### ISSUE THREAD

**Issue by rmetzler** [neo4j/neo4j#12207]
https://github.com/neo4j/neo4j/blob/4a8518da491df99ca31fb48b76210a042693c67c/community/bolt/src/main/java/org/neo4j/bolt/v1/transport/ChunkedOutput.java#L228-L233

#### Stacktrace

```
2019-04-30 20:35:04.935+0000 ERROR [o.n.b.r.DefaultBoltConnection] Unable to close pack output of bolt session 'bolt-181'.
java.lang.NullPointerException
        at org.neo4j.bolt.v1.transport.ChunkedOutput.close(ChunkedOutput.java:231)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.close(DefaultBoltConnection.java:313)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:242)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Version

```console
$ curl -s http://localhost:7474/db/manage/server/version
{
  "edition" : "community",
  "version" : "3.5.5"
}
```

**Comment by rmetzler** [comment]
closed in 691622eb5ae70ba5e3e7d5e3750189bdcbb27f74
