### ISSUE TITLE
Failure to start Neo4j on fresh install

### ISSUE THREAD

**Issue by benrudolph** [neo4j/neo4j#12205]
- Neo4j version: 3.5.4
- Operating system: Ubuntu 16.04
- API/Driver: Python driver (haven't installed this yet)
- **Steps to reproduce**

1. Install java8
```
[deploy@ip-10-0-1-117 ~ ]$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```
2. Install neo4j
sudo apt-get install neo4j-enterprise=1:3.5.4

- Expected behavior

Expect neo4j binary to work

- Actual behavior

```
[deploy@ip-10-0-1-117 ~ ]$ neo4j console
Active database: graph.db
Directories in use:
  home:         /var/lib/neo4j
  config:       /etc/neo4j
  logs:         /var/log/neo4j
  plugins:      /var/lib/neo4j/plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/run/neo4j
Starting Neo4j.
2019-04-24 17:46:54.335+0000 INFO  ======== Neo4j 3.5.4 ========
2019-04-24 17:46:54.343+0000 INFO  Starting...
2019-04-24 17:46:54.521+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@5dda768f' was successfully initialized, but failed to start. Please see the attached cause exception "/var/log/neo4j/debug.log (Permission denied)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@5dda768f' was successfully initialized, but failed to start. Please see the attached cause exception "/var/log/neo4j/debug.log (Permission denied)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@5dda768f' was successfully initialized, but failed to start. Please see the attached cause exception "/var/log/neo4j/debug.log (Permission denied)".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:123)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@5dda768f' was successfully initialized, but failed to start. Please see the attached cause exception "/var/log/neo4j/debug.log (Permission denied)".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
	... 3 more
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /var/log/neo4j/debug.log (Permission denied)
	at org.neo4j.graphdb.factory.module.PlatformModule.createLogService(PlatformModule.java:324)
	at org.neo4j.graphdb.factory.module.PlatformModule.<init>(PlatformModule.java:181)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.createPlatform(GraphDatabaseFacadeFactory.java:260)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:178)
	at com.neo4j.commercial.edition.CommercialGraphDatabase.<init>(CommercialGraphDatabase.java:20)
	at com.neo4j.server.database.CommercialGraphFactory.newGraphDatabase(CommercialGraphFactory.java:40)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 5 more
Caused by: java.io.FileNotFoundException: /var/log/neo4j/debug.log (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.neo4j.io.fs.DefaultFileSystemAbstraction.openAsOutputStream(DefaultFileSystemAbstraction.java:72)
	at org.neo4j.io.file.Files.createOrOpenAsOutputStream(Files.java:51)
	at org.neo4j.logging.RotatingFileOutputStreamSupplier.openOutputFile(RotatingFileOutputStreamSupplier.java:338)
	at org.neo4j.logging.RotatingFileOutputStreamSupplier.<init>(RotatingFileOutputStreamSupplier.java:137)
	at org.neo4j.logging.RotatingFileOutputStreamSupplier.<init>(RotatingFileOutputStreamSupplier.java:121)
	at org.neo4j.logging.internal.StoreLogService.<init>(StoreLogService.java:181)
	at org.neo4j.logging.internal.StoreLogService.<init>(StoreLogService.java:45)
	at org.neo4j.logging.internal.StoreLogService$Builder.build(StoreLogService.java:125)
	at org.neo4j.graphdb.factory.module.PlatformModule.createLogService(PlatformModule.java:320)
	... 12 more
2019-04-24 17:46:54.527+0000 INFO  Neo4j Server shutdown initiated by request
```
5. Stop the container: `docker stop neo4j-test`

### Expected behavior
`write.lock` should be removed now.

### Actual behavior
`write.lock` is still present and preventing access by other programs.

**Comment by benrudolph** [comment]
need to be `neo4j` user in order to start the process
