### ISSUE TITLE
Occasional "Found no solution for block with size 0"

### ISSUE THREAD

**Issue by ch-egli** [neo4j/neo4j#12212]
Since Version 3.5.1 we have occasionally the following error:
` Found no solution for block with size 0,
Vector() were the selected candidates from the table IDPPlanTable(numberOfPlans=3, largestSolved=1)`

This problem did never occur with version 3.5.0. 

- Neo4j version: 3.5.1, 3.5.2, 3.5.3, 3.5.4 and 3.5.5 
- Operating system: Windows 10 and Redhat Enterprise Linux 7
- API/Driver: Cypher/Java API

**Steps to reproduce** 
(unfortunately the error does not occur systematically, but only occasionally). 

Create a Graph with the following statements (this is our testcase)
`CREATE (:LinearElement {id: '00000000-0000-0000-0000-000000000001', bezeichnung: 'bez-00000000-0000-0000-0000-000000000001', spurweite: 'NORMALSPUR', uuidKey: 'uno-00000000-0000-0000-0000-000000000001'});
CREATE (tps:TmsTrackPositioningSystem:LinearPositioningSystem {id: '00000000-0000-0000-0000-000000000001', startMeasure: 0, endMeasure: 15000});
MATCH (tps:LinearPositioningSystem {id: '00000000-0000-0000-0000-000000000001'}) MATCH (le:LinearElement {id: '00000000-0000-0000-0000-000000000001'}) CREATE (tps)<-[:associatedWith {intrinsicCoord: 0.0, measure: 0}]-(le);
MATCH (tps:LinearPositioningSystem {id: '00000000-0000-0000-0000-000000000001'}) MATCH (le:LinearElement {id: '00000000-0000-0000-0000-000000000001'}) CREATE (tps)<-[:associatedWith {intrinsicCoord: 1.0, measure: 15000}]-(le);
CREATE (:LinearElement {id: '00000000-0000-0000-0000-000000000002', bezeichnung: 'bez-00000000-0000-0000-0000-000000000002', spurweite: 'NORMALSPUR', uuidKey: 'uno-00000000-0000-0000-0000-000000000002'});
CREATE (tps:TmsTrackPositioningSystem:LinearPositioningSystem {id: '00000000-0000-0000-0000-000000000002', startMeasure: 0, endMeasure: 50000});
MATCH (tps:LinearPositioningSystem {id: '00000000-0000-0000-0000-000000000002'}) MATCH (le:LinearElement {id: '00000000-0000-0000-0000-000000000002'}) CREATE (tps)<-[:associatedWith {intrinsicCoord: 0.0, measure: 0}]-(le);
MATCH (tps:LinearPositioningSystem {id: '00000000-0000-0000-0000-000000000002'}) MATCH (le:LinearElement {id: '00000000-0000-0000-0000-000000000002'}) CREATE (tps)<-[:associatedWith {intrinsicCoord: 1.0, measure: 50000}]-(le);
CREATE (:LinearElement {id: '00000000-0000-0000-0000-000000000003', bezeichnung: 'bez-00000000-0000-0000-0000-000000000003', spurweite: 'NORMALSPUR', uuidKey: 'uno-00000000-0000-0000-0000-000000000003'});
CREATE (tps:TmsTrackPositioningSystem:LinearPositioningSystem {id: '00000000-0000-0000-0000-000000000003', startMeasure: 0, endMeasure: 10000});
MATCH (tps:LinearPositioningSystem {id: '00000000-0000-0000-0000-000000000003'}) MATCH (le:LinearElement {id: '00000000-0000-0000-0000-000000000003'}) CREATE (tps)<-[:associatedWith {intrinsicCoord: 0.0, measure: 0}]-(le);
MATCH (tps:LinearPositioningSystem {id: '00000000-0000-0000-0000-000000000003'}) MATCH (le:LinearElement {id: '00000000-0000-0000-0000-000000000003'}) CREATE (tps)<-[:associatedWith {intrinsicCoord: 1.0, measure: 10000}]-(le);
CREATE (:LinearElement {id: '00000000-0000-0000-0000-000000000004', bezeichnung: 'bez-00000000-0000-0000-0000-000000000004', spurweite: 'NORMALSPUR', uuidKey: 'uno-00000000-0000-0000-0000-000000000004'});
CREATE (tps:TmsTrackPositioningSystem:LinearPositioningSystem {id: '00000000-0000-0000-0000-000000000004', startMeasure: 0, endMeasure: 2000});
MATCH (tps:LinearPositioningSystem {id: '00000000-0000-0000-0000-000000000004'}) MATCH (le:LinearElement {id: '00000000-0000-0000-0000-000000000004'}) CREATE (tps)<-[:associatedWith {intrinsicCoord: 0.0, measure: 0}]-(le);
MATCH (tps:LinearPositioningSystem {id: '00000000-0000-0000-0000-000000000004'}) MATCH (le:LinearElement {id: '00000000-0000-0000-0000-000000000004'}) CREATE (tps)<-[:associatedWith {intrinsicCoord: 1.0, measure: 2000}]-(le);
CREATE (:LinearElement {id: '00000000-0000-0000-0000-000000000005', bezeichnung: 'bez-00000000-0000-0000-0000-000000000005', spurweite: 'NORMALSPUR', uuidKey: 'uno-00000000-0000-0000-0000-000000000005'});
CREATE (tps:TmsTrackPositioningSystem:LinearPositioningSystem {id: '00000000-0000-0000-0000-000000000005', startMeasure: 0, endMeasure: 30000});
MATCH (tps:LinearPositioningSystem {id: '00000000-0000-0000-0000-000000000005'}) MATCH (le:LinearElement {id: '00000000-0000-0000-0000-000000000005'}) CREATE (tps)<-[:associatedWith {intrinsicCoord: 0.0, measure: 0}]-(le);
MATCH (tps:LinearPositioningSystem {id: '00000000-0000-0000-0000-000000000005'}) MATCH (le:LinearElement {id: '00000000-0000-0000-0000-000000000005'}) CREATE (tps)<-[:associatedWith {intrinsicCoord: 1.0, measure: 30000}]-(le);
MATCH (lnA:LinearElement {uuidKey: 'uno-00000000-0000-0000-0000-000000000003'}) MATCH (lnB:LinearElement {uuidKey: 'uno-00000000-0000-0000-0000-000000000001'})CREATE (lnA)-[:PositionedRelation {   positionOnA: 0,    positionOnB: 0,   navigability: 'None'}]->(lnB);
MATCH (lnA:LinearElement {uuidKey: 'uno-00000000-0000-0000-0000-000000000002'}) MATCH (lnB:LinearElement {uuidKey: 'uno-00000000-0000-0000-0000-000000000003'})CREATE (lnA)-[:PositionedRelation { idAB: '00000000-0000-0000-0003-000639755219', idBA: '00000000-0000-0000-0003-000191058579',    positionOnA: 0,    positionOnB: 0,   navigability: 'Both'}]->(lnB);
MATCH (lnA:LinearElement {uuidKey: 'uno-00000000-0000-0000-0000-000000000002'}) MATCH (lnB:LinearElement {uuidKey: 'uno-00000000-0000-0000-0000-000000000001'})CREATE (lnA)-[:PositionedRelation { idAB: '00000000-0000-0000-0003-000639755217', idBA: '00000000-0000-0000-0003-000088451857',    positionOnA: 0,    positionOnB: 0,   navigability: 'Both'}]->(lnB);
MATCH (lnA:LinearElement {uuidKey: 'uno-00000000-0000-0000-0000-000000000003'}) MATCH (lnB:LinearElement {uuidKey: 'uno-00000000-0000-0000-0000-000000000005'})CREATE (lnA)-[:PositionedRelation {   positionOnA: 1,    positionOnB: 1,   navigability: 'None'}]->(lnB);
MATCH (lnA:LinearElement {uuidKey: 'uno-00000000-0000-0000-0000-000000000004'}) MATCH (lnB:LinearElement {uuidKey: 'uno-00000000-0000-0000-0000-000000000003'})CREATE (lnA)-[:PositionedRelation { idAB: '00000000-0000-0000-0003-000257638059', idBA: '00000000-0000-0000-0003-000191058581',    positionOnA: 1,    positionOnB: 1,   navigability: 'Both'}]->(lnB);
MATCH (lnA:LinearElement {uuidKey: 'uno-00000000-0000-0000-0000-000000000004'}) MATCH (lnB:LinearElement {uuidKey: 'uno-00000000-0000-0000-0000-000000000005'})CREATE (lnA)-[:PositionedRelation { idAB: '00000000-0000-0000-0003-000257638057', idBA: '00000000-0000-0000-0003-000706334697',    positionOnA: 1,    positionOnB: 1,   navigability: 'Both'}]->(lnB);
CREATE (:TmsGleisknoten:NetEntity {bezeichnung: 'GK-1a', unoWeichenArt: 4, unoGleisknotenId: 1, koordinateX: 46.0, koordinateY: 46.0, id: '00000000-0000-0000-0004-000067849177'});
MATCH (n:TmsGleisknoten {id: '00000000-0000-0000-0004-000067849177'})
MATCH (linearElement:LinearElement {id: '00000000-0000-0000-0000-000000000003'}) 
CREATE (n)-[:locatedAt]->(location:SpotLocationIntrinsic:Rechts)-[association:associatedTo]->(linearElement)
 SET    association.intrinsicCoord = 0.0,   location.applicationDirection = 'both';
MATCH (n:TmsGleisknoten {id: '00000000-0000-0000-0004-000067849177'}) 
MATCH (linearElement:LinearElement {id: '00000000-0000-0000-0000-000000000002'}) 
CREATE (n)-[:locatedAt]->(location:SpotLocationIntrinsic:Spitz)-[association:associatedTo]->(linearElement)
 SET    association.intrinsicCoord = 0.0,   location.applicationDirection = 'both';
MATCH (n:TmsGleisknoten {id: '00000000-0000-0000-0004-000067849177'}) 
MATCH (linearElement:LinearElement {id: '00000000-0000-0000-0000-000000000001'}) 
CREATE (n)-[:locatedAt]->(location:SpotLocationIntrinsic:Links)-[association:associatedTo]->(linearElement)
 SET    association.intrinsicCoord = 0.0,   location.applicationDirection = 'both';
CREATE (:TmsGleisknoten:NetEntity {bezeichnung: 'GK-1b', unoWeichenArt: 4, unoGleisknotenId: 2, koordinateX: 44.0, koordinateY: 44.0, id: '00000000-0000-0000-0004-000067849178'});
MATCH (n:TmsGleisknoten {id: '00000000-0000-0000-0004-000067849178'}) 
MATCH (linearElement:LinearElement {id: '00000000-0000-0000-0000-000000000003'}) 
CREATE (n)-[:locatedAt]->(location:SpotLocationIntrinsic:Links)-[association:associatedTo]->(linearElement)
 SET    association.intrinsicCoord = 1.0,   location.applicationDirection = 'both';
MATCH (n:TmsGleisknoten {id: '00000000-0000-0000-0004-000067849178'}) 
MATCH (linearElement:LinearElement {id: '00000000-0000-0000-0000-000000000004'}) 
CREATE (n)-[:locatedAt]->(location:SpotLocationIntrinsic:Spitz)-[association:associatedTo]->(linearElement)
 SET    association.intrinsicCoord = 1.0,   location.applicationDirection = 'both';
MATCH (n:TmsGleisknoten {id: '00000000-0000-0000-0004-000067849178'}) 
MATCH (linearElement:LinearElement {id: '00000000-0000-0000-0000-000000000005'}) 
CREATE (n)-[:locatedAt]->(location:SpotLocationIntrinsic:Rechts)-[association:associatedTo]->(linearElement)
 SET    association.intrinsicCoord = 1.0,   location.applicationDirection = 'both';
`

Run the following statement (that creates two new nodes): 
`WITH 20000 AS longDistanceMM, 5000 AS shortDistanceMM
MATCH (gknA:TmsGleisknoten {unoWeichenArt: 4})-[:locatedAt]->(:SpotLocationIntrinsic)-[:associatedTo]->(commonLe:LinearElement)
  <-[:associatedTo]-(:SpotLocationIntrinsic)<-[:locatedAt]-(gknB:TmsGleisknoten {unoWeichenArt: 4})
  WHERE NOT exists( (gknA)<-[:isLinkedTo]-(:SaWeiche) ) AND NOT exists( (gknB)<-[:isLinkedTo]-(:SaWeiche) ) 
  AND substring(gknA.bezeichnung, 0, size(gknA.bezeichnung) - 1) = substring(gknB.bezeichnung, 0, size(gknB.bezeichnung) - 1)
  AND gknA.unoGleisknotenId < gknB.unoGleisknotenId
MATCH (gknA)-[:locatedAt]->(:SpotLocationIntrinsic)-[assocA:associatedTo]->(toExtendLongA:LinearElement)-[:PositionedRelation {navigability: 'None'}]-(commonLe)
MATCH (gknB)-[:locatedAt]->(:SpotLocationIntrinsic)-[assocB:associatedTo]->(toExtendLongB:LinearElement)-[:PositionedRelation {navigability: 'None'}]-(commonLe)
MATCH (gknA)-[:locatedAt]->(:Spitz)-[assocSpitzA:associatedTo]->(spitzA:LinearElement)
MATCH (gknB)-[:locatedAt]->(:Spitz)-[assocSpitzB:associatedTo]->(spitzB:LinearElement)
WITH gknA, gknB, longDistanceMM, shortDistanceMM,
 [{
    linearElement: toExtendLongA,
    fromIntrinsic: assocA.intrinsicCoord,
    fromDirection: CASE WHEN assocA.intrinsicCoord = 0.0 THEN 'normal' ELSE 'reverse' END,
    inboundDirection: CASE WHEN assocA.intrinsicCoord = 0.0 THEN 'reverse' ELSE 'normal' END,
    distanceMM: longDistanceMM    
  }, {
    linearElement: toExtendLongB,
    fromIntrinsic: assocB.intrinsicCoord,
    fromDirection: CASE WHEN assocB.intrinsicCoord = 0.0 THEN 'normal' ELSE 'reverse' END,
    inboundDirection: CASE WHEN assocB.intrinsicCoord = 0.0 THEN 'reverse' ELSE 'normal' END,
    distanceMM: longDistanceMM
  }, {
    linearElement: spitzA,
    fromIntrinsic: assocSpitzA.intrinsicCoord,
    fromDirection: CASE WHEN assocSpitzA.intrinsicCoord = 0.0 THEN 'normal' ELSE 'reverse' END,
    inboundDirection: CASE WHEN assocSpitzA.intrinsicCoord = 0.0 THEN 'reverse' ELSE 'normal' END,
    distanceMM: shortDistanceMM
  }, {
    linearElement: spitzB,
    fromIntrinsic: assocSpitzB.intrinsicCoord,
    fromDirection: CASE WHEN assocSpitzB.intrinsicCoord = 0.0 THEN 'normal' ELSE 'reverse' END,
    inboundDirection: CASE WHEN assocSpitzB.intrinsicCoord = 0.0 THEN 'reverse' ELSE 'normal' END,
    distanceMM: shortDistanceMM
  }] AS bounds
CREATE (gknA)<-[:isLinkedTo]-(newSaWeiche:SaWeiche:NetEntity)-[:isLinkedTo]->(gknB)
  SET newSaWeiche = {
    uuidKey: gknA.id + '-' + gknB.id,
    bezeichnung: substring(gknA.bezeichnung, 0, size(gknA.bezeichnung) - 1),
    datenGrundlage: 'TMS_HEURISTIK', 
    typ: 'EKW'
  }
CREATE (newSaWeiche)-[:locatedAt]->(areaLocation:AreaLocationIntrinsic:SaWeicheSicherheitsbereich)
WITH bounds, areaLocation
UNWIND bounds AS bound
WITH areaLocation, bound, bound.linearElement AS linearElement, bound.inboundDirection AS inboundDirection,
  topo.position.intrinsicToRealTms(bound.linearElement, bound.fromIntrinsic, bound.fromDirection) AS tmsPos
WITH areaLocation, bound, linearElement, tmsPos,
  topo.position.addDistanceOnSameElement(tmsPos.positioningSystem, tmsPos.measure, bound.distanceMM, tmsPos.direction) AS boundedTo
WITH areaLocation, bound, linearElement, tmsPos, 
  topo.position.tmsToIntrinsic(tmsPos.positioningSystem, boundedTo, bound.inboundDirection) AS newIntrinsicCoord
CREATE (areaLocation)-[boundRel:boundedBy]->(linearElement)
SET boundRel.inboundDirection = bound.inboundDirection, boundRel.intrinsicCoord = newIntrinsicCoord.intrinsicCoord`

- Expected behavior:
Creates two new nodes

- Actual behavior:
` Found no solution for block with size 0,
Vector() were the selected candidates from the table IDPPlanTable(numberOfPlans=3, largestSolved=1)`

- The execution in a Java Test Case produces the following error: 
`java.lang.RuntimeException: java.lang.IllegalStateException: Found no solution for block with size 0,
Vector() were the selected candidates from the table IDPPlanTable(numberOfPlans=4, largestSolved=2)

	at org.neo4j.ogm.drivers.embedded.request.EmbeddedRequest.executeRequest(EmbeddedRequest.java:159)
	at org.neo4j.ogm.drivers.embedded.request.EmbeddedRequest.execute(EmbeddedRequest.java:143)
	at org.neo4j.ogm.session.delegates.ExecuteQueriesDelegate.lambda$query$0(ExecuteQueriesDelegate.java:108)
	at org.neo4j.ogm.session.Neo4jSession.doInTransaction(Neo4jSession.java:579)
	at org.neo4j.ogm.session.Neo4jSession.doInTransaction(Neo4jSession.java:558)
	at org.neo4j.ogm.session.delegates.ExecuteQueriesDelegate.query(ExecuteQueriesDelegate.java:106)
	at org.neo4j.ogm.session.delegates.ExecuteQueriesDelegate.query(ExecuteQueriesDelegate.java:86)
	at org.neo4j.ogm.session.Neo4jSession.query(Neo4jSession.java:418)
	at sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
	at org.springframework.data.neo4j.transaction.SharedSessionCreator$SharedSessionInvocationHandler.lambda$invoke$0(SharedSessionCreator.java:108)
	at org.springframework.data.neo4j.transaction.SharedSessionCreator$SharedSessionInvocationHandler.invokeInTransaction(SharedSessionCreator.java:139)
	at org.springframework.data.neo4j.transaction.SharedSessionCreator$SharedSessionInvocationHandler.invoke(SharedSessionCreator.java:110)
	at com.sun.proxy.$Proxy160.query(Unknown Source)
	at ch.sbb.tms.topo.gleisnetz.importer.TestImporterSession.query(TestImporterSession.java:97)
	at ch.sbb.tms.topo.gleisnetz.gleisabhaengigkeiten.importer.SaWeicheImportRepository.createSyntheticSaWeichenEinfacheKreuzungsWeichen(SaWeicheImportRepository.java:204)
	at ch.sbb.tms.topo.gleisnetz.gleisabhaengigkeiten.importer.SyntheticEkwSaWeichenImporterIT.generateSyntheticSaWeichenForEinfacheKreuzungsWeichen(SyntheticEkwSaWeichenImporterIT.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalStateException: Found no solution for block with size 0,
Vector() were the selected candidates from the table IDPPlanTable(numberOfPlans=4, largestSolved=2)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPSolver$$anonfun$findBestCandidateInBlock$1$1.apply(IDPSolver.scala:87)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPSolver$$anonfun$findBestCandidateInBlock$1$1.apply(IDPSolver.scala:87)
	at scala.Option.getOrElse(Option.scala:121)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPSolver.findBestCandidateInBlock$1(IDPSolver.scala:86)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPSolver.apply(IDPSolver.scala:108)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.SingleComponentPlanner.planComponent(SingleComponentPlanner.scala:66)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPQueryGraphSolver$$anonfun$planComponents$1.apply(IDPQueryGraphSolver.scala:80)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPQueryGraphSolver$$anonfun$planComponents$1.apply(IDPQueryGraphSolver.scala:79)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPQueryGraphSolver.planComponents(IDPQueryGraphSolver.scala:79)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.idp.IDPQueryGraphSolver.plan(IDPQueryGraphSolver.scala:59)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.planPart$.apply(QueryPlanner.scala:127)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.PlanWithTail.apply(PlanWithTail.scala:43)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.PlanSingleQuery.apply(PlanSingleQuery.scala:57)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:106)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:104)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.QueryPlanner.planQueries(QueryPlanner.scala:104)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.QueryPlanner.plan(QueryPlanner.scala:94)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.QueryPlanner.process(QueryPlanner.scala:72)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.QueryPlanner.process(QueryPlanner.scala:33)
	at org.neo4j.cypher.internal.v3_5.frontend.phases.Phase$$anonfun$transform$1.apply(Phase.scala:36)
	at org.neo4j.cypher.internal.v3_5.frontend.helpers.package$$anonfun$closing$1.apply(package.scala:24)
	at org.neo4j.cypher.internal.v3_5.frontend.helpers.package$$anonfun$closing$1.apply(package.scala:24)
	at org.neo4j.cypher.internal.v3_5.frontend.helpers.package$.using(package.scala:32)
	at org.neo4j.cypher.internal.v3_5.frontend.helpers.package$.closing(package.scala:24)
	at org.neo4j.cypher.internal.v3_5.frontend.phases.Phase$class.transform(Phase.scala:35)
	at org.neo4j.cypher.internal.compiler.v3_5.planner.logical.QueryPlanner.transform(QueryPlanner.scala:33)
	at org.neo4j.cypher.internal.v3_5.frontend.phases.PipeLine.transform(Transformer.scala:60)
	at org.neo4j.cypher.internal.v3_5.frontend.phases.PipeLine.transform(Transformer.scala:60)
	at org.neo4j.cypher.internal.v3_5.frontend.phases.PipeLine.transform(Transformer.scala:60)
	at org.neo4j.cypher.internal.v3_5.frontend.phases.PipeLine.transform(Transformer.scala:60)
	at org.neo4j.cypher.internal.v3_5.frontend.phases.PipeLine.transform(Transformer.scala:64)
	at org.neo4j.cypher.internal.v3_5.frontend.phases.If.transform(Transformer.scala:89)
	at org.neo4j.cypher.internal.v3_5.frontend.phases.PipeLine.transform(Transformer.scala:64)
	at org.neo4j.cypher.internal.compiler.v3_5.CypherPlanner.planPreparedQuery(CypherPlanner.scala:57)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner$$anonfun$parseAndPlan$1.org$neo4j$cypher$internal$compatibility$v3_5$Cypher35Planner$$anonfun$$createPlan$1(Cypher35Planner.scala:162)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner$$anonfun$parseAndPlan$1$$anonfun$7.apply(Cypher35Planner.scala:180)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner$$anonfun$parseAndPlan$1$$anonfun$7.apply(Cypher35Planner.scala:180)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:167)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:126)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner$$anonfun$parseAndPlan$1.apply(Cypher35Planner.scala:178)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner$$anonfun$parseAndPlan$1.apply(Cypher35Planner.scala:124)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner.parseAndPlan(Cypher35Planner.scala:124)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler.compile(CypherCurrentCompiler.scala:83)
	at org.neo4j.cypher.internal.MasterCompiler.innerCompile$1(MasterCompiler.scala:115)
	at org.neo4j.cypher.internal.MasterCompiler.compile(MasterCompiler.scala:150)
	at org.neo4j.cypher.internal.ExecutionEngine$$anonfun$compilers$3.apply(ExecutionEngine.scala:137)
	at org.neo4j.cypher.internal.ExecutionEngine$$anonfun$compilers$3.apply(ExecutionEngine.scala:137)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:167)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:126)
	at org.neo4j.cypher.internal.ExecutionEngine.getOrCompile(ExecutionEngine.scala:157)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:96)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:85)
	at org.neo4j.graphdb.facade.spi.ClassicCoreSPI.executeQuery(ClassicCoreSPI.java:84)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:421)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:404)
	at org.neo4j.ogm.drivers.embedded.request.EmbeddedRequest.executeRequest(EmbeddedRequest.java:155)
	... 49 more
`

**Comment by Hunterness** [comment]
Hi, thanks for reporting. We will look into it

/ Team Cypher

**Comment by gs-npawar1** [comment]
Can you let us know by when this will be fixed? 

We are hitting outage because of this error and are unable to figure out which query caused this issue

**Comment by SaschaPeukert** [comment]
The fix will be included in the upcoming release of 3.5.7.

Thanks again for reporting!

**Comment by ch-egli** [comment]
Thank you. We are looking forward to use a recent version again... :-)
