### ISSUE TITLE
one of neo4j causal cluster - follower node not getting up

### ISSUE THREAD

**Issue by sumitbit2005** [neo4j/neo4j#12220]
Neo4j Version: 3.5.4

When Starting neo4j causual cluster - one of the follower node did not start up.

Below are the log from neo4j.log file:

> 2019-05-15 10:56:25.068+0000 INFO  Discovering other core members in initial members set: [XXX:5000, XXX:5000, XXX:5000]
2019-05-15 10:56:25.166+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1d01dfa5' was successfully initialized, but failed to start. Please see the attached cause exception "Must append in order. Tried to append [index: -1209987662860333837, term: -4675695711336005632] but expected index is 80990972". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1d01dfa5' was successfully initialized, but failed to start. Please see the attached cause exception "Must append in order. Tried to append [index: -1209987662860333837, term: -4675695711336005632] but expected index is 80990972".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1d01dfa5' was successfully initialized, but failed to start. Please see the attached cause exception "Must append in order. Tried to append [index: -1209987662860333837, term: -4675695711336005632] but expected index is 80990972".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:123)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
        at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1d01dfa5' was successfully initialized, but failed to start. Please see the attached cause exception "Must append in order. Tried to append [index: -1209987662860333837, term: -4675695711336005632] but expected index is 80990972".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
        ... 3 more

To make it work - Have to un-bind the follower node and start again to get it added to cluster.

**Comment by sumitmanes** [comment]
Need information -
1.  In what scenerio this Error can come.
2. What is the way to resolve it
3. What actually this Error Means

**Comment by sumitmanes** [comment]
Any update on the issue.

**Comment by sumitmanes** [comment]
please provide update to the issue.

**Comment by RagnarW** [comment]
Closing due to unsupported version
