### ISSUE TITLE
Cannot set port of advertised address

### ISSUE THREAD

**Issue by LarsKumbier** [neo4j/neo4j#12231]
When starting neo4j, I would like to preseed the browser connection url. This is done through the parameter "dbms.connectors.default_advertised_address". However, the server fails to check for a port in the url, so I am unable to change that. This is necessary to e.g. make the browser and neo4j-database accessible through a kubernetes ingress controller and "nodePort" is not an option.

**Neo4j Version:** 3.5.6 (CE)
**Operating System:** Docker Container
**API:** Docker

### Steps to reproduce
1. Pull the image: `docker pull neo4j/neo4j:3.5.6`
2. Start a new container: `docker run --rm -it -e NEO4J_dbms_connectors_default__advertised__address="example.com:80" -p 7474:7474 neo4j/neo4j:3.5.6`

### Expected behavior
The server should start up and the neo4j browser should prefill the connection URL to be "bolt://example.com:80"

### Actual behavior
Server crashed during startup:

```
2019-06-19 08:13:59.716+0000 INFO  ======== Neo4j 3.5.6 ========
2019-06-19 08:13:59.725+0000 INFO  Starting...
2019-06-19 08:14:01.846+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2019-06-19 08:14:03.135+0000 INFO  Started.
2019-06-19 08:14:03.294+0000 INFO  Stopping...
2019-06-19 08:14:03.339+0000 INFO  Stopped.
2019-06-19 08:14:03.340+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@4899799b' was successfully initialized, but failed to start. Please see the attached cause exception "Malformed IPv6 address at index 8: bolt://[example.com:80]:7687". Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@4899799b' was successfully initialized, but failed to start. Please see the attached cause exception "Malformed IPv6 address at index 8: bolt://[example.com:80]:7687".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@4899799b' was successfully initialized, but failed to start. Please see the attached cause exception "Malformed IPv6 address at index 8: bolt://[example.com:80]:7687".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@4899799b' was successfully initialized, but failed to start. Please see the attached cause exception "Malformed IPv6 address at index 8: bolt://[example.com:80]:7687".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
        ... 3 more
Caused by: org.neo4j.graphdb.config.InvalidSettingException: Unable to construct bolt discoverable URI using 'example.com:80' as hostname: Malformed IPv6 address at index 8: bolt://[example.com:80]:7687
        at org.neo4j.server.rest.discovery.DiscoverableURIs$Builder.add(DiscoverableURIs.java:133)
        at org.neo4j.server.rest.discovery.DiscoverableURIs$Builder.lambda$addBoltConnectorFromConfig$1(DiscoverableURIs.java:155)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.neo4j.server.rest.discovery.DiscoverableURIs$Builder.addBoltConnectorFromConfig(DiscoverableURIs.java:145)
        at org.neo4j.server.rest.discovery.CommunityDiscoverableURIs.communityDiscoverableURIs(CommunityDiscoverableURIs.java:38)
        at org.neo4j.server.CommunityNeoServer.lambda$createDBMSModule$0(CommunityNeoServer.java:99)
        at org.neo4j.server.modules.DBMSModule.start(DBMSModule.java:59)
        at org.neo4j.server.AbstractNeoServer.startModules(AbstractNeoServer.java:249)
        at org.neo4j.server.AbstractNeoServer.access$700(AbstractNeoServer.java:102)
        at org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter.start(AbstractNeoServer.java:541)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 5 more
Caused by: java.net.URISyntaxException: Malformed IPv6 address at index 8: bolt://[example.com:80]:7687
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.parseIPv6Reference(URI.java:3469)
        at java.net.URI$Parser.parseServer(URI.java:3219)
        at java.net.URI$Parser.parseAuthority(URI.java:3155)
        at java.net.URI$Parser.parseHierarchical(URI.java:3097)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:673)
        at org.neo4j.server.rest.discovery.DiscoverableURIs$Builder.add(DiscoverableURIs.java:128)
        ... 15 more
2019-06-19 08:14:03.342+0000 INFO  Neo4j Server shutdown initiated by request
```

**Comment by technige** [comment]
Hi @LarsKumbier 

The issue that you're seeing is actually correct behaviour. The `dbms.connectors.default_advertised_address` settings can accept only the host (host name or IP address) portion of the full socket address, since different ports are appended for each protocol.

The exception `Malformed IPv6 address at index 8: bolt://[example.com:80]:7687` is thrown because `example.com:80` contains a colon and is therefore interpreted as an IPv6 address and is consequently enclosed in square brackets in the Bolt URI.

What you probably want to do is set the following instead:
```
dbms.connectors.default_advertised_address=example.com
dbms.connector.http.advertised_address=:80
dbms.connector.bolt.advertised_address=:7687
```

Bear in mind that Bolt and HTTP are served on different ports (by default these are 7687 and 7474 respectively). So connecting to the browser is not the same thing as connecting via a Bolt URI.

All of that said, I would consider this part of our configuration to be unnecessarily confusing; I've actually hit this exact same problem myself and - after an Engineering discussion on this topic this morning - we have decided to take two actions:

1. Improve the documentation on this part of the configuration (at https://neo4j.com/docs/operations-manual/current/configuration/connectors/#connectors-configuration-options)
2. Work on a clearer set of configuration options for our 4.0 release later this year.

Hope this helps.

**Comment by LarsKumbier** [comment]
Thanks, @technige - that makes a lot more sense to me now. I'll try to get it running in the way you described.

It would still be nice to have a separate configuration option for prefilling specifically the browser URL, as this might be different than the cluster addresses. In my specific usecase, I'm making the frontend (Neo4j browser) available through a kubernetes ingress controller. But if I would install a cluster of different Neo4j-instances, those should *not* go through the ingress controller for performance reasons, but rather directly connect as they would when running on VMs or baremetal - or go through the usual clustering extensions of kubernetes itself.

**Comment by LarsKumbier** [comment]
Works as expected. @technige, issue can be closed if you don't want to keep it for reference for the action items you issued?
