### ISSUE TITLE
Upgrading from 3.5.3 to 3.5.7 fails

### ISSUE THREAD

**Issue by aaronjwood** [neo4j/neo4j#12244]
- Neo4j version: 3.5.3 -> 3.5.7
- Operating system: [Debian](https://github.com/kubernetes/kops/blob/master/docs/images.md#debian)
- API/Driver: Cypher
- Environment: Official neo4j container running on kubernetes 1.11.8

## Expected behavior:
Use a stateful set and upgrade the stateful set from 3.5.3 to 3.5.7 without failures.

## Actual behavior: 
When upgrading the stateful set the new pod will continually crash and log these errors:
```
Active database: graph.db
Directories in use:
  home:         /var/lib/neo4j
  config:       /var/lib/neo4j/conf
  logs:         /logs
  plugins:      /var/lib/neo4j/plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/lib/neo4j/run
Starting Neo4j.
2019-07-08 19:33:11.901+0000 WARN  Unknown config option: causal_clustering.discovery_listen_address
2019-07-08 19:33:11.904+0000 WARN  Unknown config option: causal_clustering.raft_advertised_address
2019-07-08 19:33:11.904+0000 WARN  Unknown config option: causal_clustering.raft_listen_address
2019-07-08 19:33:11.904+0000 WARN  Unknown config option: ha.host.coordination
2019-07-08 19:33:11.905+0000 WARN  Unknown config option: causal_clustering.transaction_advertised_address
2019-07-08 19:33:11.905+0000 WARN  Unknown config option: causal_clustering.discovery_advertised_address
2019-07-08 19:33:11.906+0000 WARN  Unknown config option: ha.host.data
2019-07-08 19:33:11.906+0000 WARN  Unknown config option: causal_clustering.transaction_listen_address
2019-07-08 19:33:11.929+0000 INFO  ======== Neo4j 3.5.7 ========
2019-07-08 19:33:11.942+0000 INFO  Starting...
2019-07-08 19:33:13.002+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@38604b81' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: /data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@38604b81' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: /data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@38604b81' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: /data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@38604b81' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: /data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /data/databases
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:230)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:146)
	at org.neo4j.server.database.CommunityGraphFactory.newGraphDatabase(CommunityGraphFactory.java:41)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter@54eb2b70' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: /data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:225)
	... 9 more
Caused by: org.neo4j.kernel.StoreLockException: Unable to obtain lock on store lock file: /data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)
	at org.neo4j.kernel.internal.locker.StoreLocker.storeLockException(StoreLocker.java:116)
	at org.neo4j.kernel.internal.locker.StoreLocker.unableToObtainLockException(StoreLocker.java:109)
	at org.neo4j.kernel.internal.locker.StoreLocker.checkLock(StoreLocker.java:97)
	at org.neo4j.kernel.internal.locker.GlobalStoreLocker.checkLock(GlobalStoreLocker.java:61)
	at org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter.start(StoreLockerLifecycleAdapter.java:36)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 11 more
2019-07-08 19:33:13.003+0000 INFO  Neo4j Server shutdown initiated by request
```

**Comment by browndp08** [comment]
This upgrade path is also failing for my team but we're getting the following error:
```
2019-09-30 14:59:11.645+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@abf688e' was successfully initialized, but failed to start. Please see the attached cause exception "/data/databases/graph.db/neostore.nodestore.db.labels.id (Permission denied)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@abf688e' was successfully initialized, but failed to start. Please see the attached cause exception "/data/databases/graph.db/neostore.nodestore.db.labels.id (Permission denied)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@abf688e' was successfully initialized, but failed to start. Please see the attached cause exception "/data/databases/graph.db/neostore.nodestore.db.labels.id (Permission denied)".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
```

**Comment by linder05** [comment]
We're seeing the same error as the original post, but we've found another strange symptom. When we checked k8s for info we found that the store_lock file is being treated as having different permissions across the two versions. 
` 3.5.12
  -rw-r--r--    1 neo4j    neo4j            0 Oct 22 19:17 store_lock

  3.5.1
  -rwxr-xr-x    1 neo4j    neo4j            0 Oct 22 19:17 store_lock`
Is this expected, or could it be linked to a missing configuration property?

**Comment by CecilLew** [comment]
We are using neo4j enterprise in Kubernetes using a statefulset and had a similiar problem trying to upgrade. Sometimes we got strange errors about a lock file but usually it would hang right after the Starting Neo message. A colleague determined the problem was due to permission errors. **Both the old and new images used "neo4j" user but the actual user id, UID, was different**. The database was using a Persistent Disk and the new image was not able to read the data from the old image.

Our solution required downtime and a backup. First we started up a statefulset using a new database name. This allowed the image to stay running. Then copied the backup into the persistent disk of the statefulset pod using a command like "kubectl cp grapph.db-backup.tgz neo4j-server-xxxx:/data/". Then we exec'ed into the pod, untarred the backup and ran "chown -R neo4j:noe4j graph.db". Since the chown was done on the new (upgraded) image, the correct UID was used. Then we changed the database name in the statefulset manifest to the restored database name, deployed the manifest, and bounced the pod. The upgraded image was able to read and use the new database.

I think this should also work without using backups. Just start it up temporarily using a new database name so that ownership on the original database file structure can be changed. Then re-start pointing to the original database.

**Comment by aaronjwood** [comment]
Thanks for the pointers @CecilLew. I was able to layer my own Dockerfile over the official Neo4j one and use my own image to work around the permissions issue:
```
# The whole reason this Dockerfile exists is to work around https://github.com/neo4j/neo4j/issues/12244
FROM neo4j:3.5.12
RUN userdel _apt && usermod -u 100 neo4j
```

The user `_apt` has UID 100 which is why I'm removing it before assigning 100 back to the user `neo4j`. Pretty hacky right? :)

With this we were able to do a seamless upgrade of Neo4j from 3.5.3 to 3.5.12.

**Comment by klaren** [comment]
Thank you for reporting. This looks like a docker problem. I'm forwarding this to the right team.
