### ISSUE TITLE
Neo4j server not starting

### ISSUE THREAD

**Issue by noorbakerally** [neo4j/neo4j#12253]
I am trying to start the neo4j 3.5.7 server but failing to start on on Ubuntu 18.04. It says the the file /var/lib/neo4j/data/databases/graph.db/neostore  doesn't exist while it does and with the right permission.  Log is below

nohup: ignoring input
2019-08-02 22:01:47.050+0000 INFO  ======== Neo4j 3.5.7 ========
2019-08-02 22:01:47.061+0000 INFO  Starting...
2019-08-02 22:01:48.166+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6475472c' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6475472c' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6475472c' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6475472c' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:230)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:146)
        at org.neo4j.server.database.CommunityGraphFactory.newGraphDatabase(CommunityGraphFactory.java:41)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@32c8e539' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:116)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:225)
        ... 9 more
Caused by: org.neo4j.kernel.impl.store.UnderlyingStorageException: java.io.FileNotFoundException: /var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)
        at org.neo4j.kernel.impl.store.NeoStores.verifyRecordFormat(NeoStores.java:217)
        at org.neo4j.kernel.impl.store.NeoStores.<init>(NeoStores.java:144)
        at org.neo4j.kernel.impl.store.StoreFactory.openNeoStores(StoreFactory.java:129)
        at org.neo4j.kernel.impl.store.StoreFactory.openAllNeoStores(StoreFactory.java:93)
        at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.<init>(RecordStorageEngine.java:187)
        at org.neo4j.kernel.NeoStoreDataSource.buildStorageEngine(NeoStoreDataSource.java:514)
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:367)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 14 more
Caused by: java.io.FileNotFoundException: /var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at org.neo4j.io.fs.DefaultFileSystemAbstraction.open(DefaultFileSystemAbstraction.java:65)
        at org.neo4j.io.fs.DefaultFileSystemAbstraction.open(DefaultFileSystemAbstraction.java:50)
        at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.<init>(SingleFilePageSwapper.java:170)
        at org.neo4j.io.pagecache.impl.SingleFilePageSwapperFactory.createPageSwapper(SingleFilePageSwapperFactory.java:66)
        at org.neo4j.io.pagecache.impl.muninn.MuninnPagedFile.<init>(MuninnPagedFile.java:149)
        at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.map(MuninnPageCache.java:412)
        at org.neo4j.kernel.impl.store.MetaDataStore.getRecord(MetaDataStore.java:285)
        at org.neo4j.kernel.impl.store.NeoStores.verifyRecordFormat(NeoStores.java:198)
        ... 21 more
2019-08-02 22:01:48.167+0000 INFO  Neo4j Server shutdown initiated by request
nohup: ignoring input
2019-08-02 22:03:11.329+0000 INFO  ======== Neo4j 3.5.7 ========
2019-08-02 22:03:11.341+0000 INFO  Starting...
2019-08-02 22:03:12.502+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6475472c' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6475472c' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6475472c' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6475472c' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:230)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:146)
        at org.neo4j.server.database.CommunityGraphFactory.newGraphDatabase(CommunityGraphFactory.java:41)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@32c8e539' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:116)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:225)
        ... 9 more
Caused by: org.neo4j.kernel.impl.store.UnderlyingStorageException: java.io.FileNotFoundException: /var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)
        at org.neo4j.kernel.impl.store.NeoStores.verifyRecordFormat(NeoStores.java:217)
        at org.neo4j.kernel.impl.store.NeoStores.<init>(NeoStores.java:144)
        at org.neo4j.kernel.impl.store.StoreFactory.openNeoStores(StoreFactory.java:129)
        at org.neo4j.kernel.impl.store.StoreFactory.openAllNeoStores(StoreFactory.java:93)
        at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.<init>(RecordStorageEngine.java:187)
        at org.neo4j.kernel.NeoStoreDataSource.buildStorageEngine(NeoStoreDataSource.java:514)
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:367)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 14 more
Caused by: java.io.FileNotFoundException: /var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at org.neo4j.io.fs.DefaultFileSystemAbstraction.open(DefaultFileSystemAbstraction.java:65)
        at org.neo4j.io.fs.DefaultFileSystemAbstraction.open(DefaultFileSystemAbstraction.java:50)
        at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.<init>(SingleFilePageSwapper.java:170)
        at org.neo4j.io.pagecache.impl.SingleFilePageSwapperFactory.createPageSwapper(SingleFilePageSwapperFactory.java:66)
        at org.neo4j.io.pagecache.impl.muninn.MuninnPagedFile.<init>(MuninnPagedFile.java:149)
        at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.map(MuninnPageCache.java:412)
        at org.neo4j.kernel.impl.store.MetaDataStore.getRecord(MetaDataStore.java:285)
        at org.neo4j.kernel.impl.store.NeoStores.verifyRecordFormat(NeoStores.java:198)
        ... 21 more
2019-08-02 22:03:12.504+0000 INFO  Neo4j Server shutdown initiated by request
nohup: ignoring input
2019-08-02 22:06:18.194+0000 INFO  ======== Neo4j 3.5.7 ========
2019-08-02 22:06:18.205+0000 INFO  Starting...
2019-08-02 22:06:19.292+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6475472c' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6475472c' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6475472c' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6475472c' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:230)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:146)
        at org.neo4j.server.database.CommunityGraphFactory.newGraphDatabase(CommunityGraphFactory.java:41)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@32c8e539' was successfully initialized, but failed to start. Please see the attached cause exception "/var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:116)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:225)
        ... 9 more
Caused by: org.neo4j.kernel.impl.store.UnderlyingStorageException: java.io.FileNotFoundException: /var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)
        at org.neo4j.kernel.impl.store.NeoStores.verifyRecordFormat(NeoStores.java:217)
        at org.neo4j.kernel.impl.store.NeoStores.<init>(NeoStores.java:144)
        at org.neo4j.kernel.impl.store.StoreFactory.openNeoStores(StoreFactory.java:129)
        at org.neo4j.kernel.impl.store.StoreFactory.openAllNeoStores(StoreFactory.java:93)
        at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.<init>(RecordStorageEngine.java:187)
        at org.neo4j.kernel.NeoStoreDataSource.buildStorageEngine(NeoStoreDataSource.java:514)
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:367)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 14 more
Caused by: java.io.FileNotFoundException: /var/lib/neo4j/data/databases/graph.db/neostore (Permission denied)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at org.neo4j.io.fs.DefaultFileSystemAbstraction.open(DefaultFileSystemAbstraction.java:65)
        at org.neo4j.io.fs.DefaultFileSystemAbstraction.open(DefaultFileSystemAbstraction.java:50)
        at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.<init>(SingleFilePageSwapper.java:170)
        at org.neo4j.io.pagecache.impl.SingleFilePageSwapperFactory.createPageSwapper(SingleFilePageSwapperFactory.java:66)
        at org.neo4j.io.pagecache.impl.muninn.MuninnPagedFile.<init>(MuninnPagedFile.java:149)
        at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.map(MuninnPageCache.java:412)
        at org.neo4j.kernel.impl.store.MetaDataStore.getRecord(MetaDataStore.java:285)
        at org.neo4j.kernel.impl.store.NeoStores.verifyRecordFormat(NeoStores.java:198)
        ... 21 more
2019-08-02 22:06:19.302+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by klaren** [comment]
The exception is `FileNotFoundException` but the cause of that is `Permission denied`.

If you could provide us with the `debug.log` and the output of 
`ls -al /var/lib/neo4j/data/databases/graph.db/` 
that would help to pinpoint the cause.

Thanks for reporting!

**Comment by klaren** [comment]
Closing due to inactivity. Feel free to reopen if it's still an issue.

**Comment by prashant-shahi** [comment]
I had a similar issue.

Changing the owner of `graph.db` folder resolved it,
```sh
chown -R neo4j.neo4j /path/to/graphdb/graph.db/
```

**Comment by mikaalanwar** [comment]
Thanks a lot, @prashant-shahi, for the suggested solution! In my case, It didn't work right off the bat, but generally, all one needs to do is to ensure that the "neo4j" (parent folder) and the "graph.db" folder have the same user/group assigned. This can be easily checked using the following command in Mac / Linux:

`ls -l`

And in case you spot a difference of ownership between the parent and sub-folder. You can resolve this inconsistency using the following command:

`chown -R <user>:<group> /path/to/graphdb/graph.db/`
