### ISSUE TITLE
Failed to start Neo4j when the neo4j database is stopped

### ISSUE THREAD

**Issue by luanne** [neo4j/neo4j#12275]
Neo4j fails to start up when multiple databases are created (and online), and the neo4j database is stopped, and thereafter, Neo4j is shut down.

- Neo4j version: Neo4j 4.0.0-alpha09mr02
- Operating system: macOS 10.14.5 
- API/Driver: n/a

- **Steps to reproduce**

`create database tweets`
`create database blogs`
`stop database neo4j`

Then stop Neo4j, and try to start it up again.

### Expected behavior

Neo4j starts

### Actual behavior

On the console:
```
Luannes-MacBook-Pro-3:bin luanne$ ./neo4j console
Directories in use:
  home:         /Users/luanne/neo/neo4j-enterprise-4.0.0-alpha09mr02
  config:       /Users/luanne/neo/neo4j-enterprise-4.0.0-alpha09mr02/conf
  logs:         /Users/luanne/neo/neo4j-enterprise-4.0.0-alpha09mr02/logs
  plugins:      /Users/luanne/neo/neo4j-enterprise-4.0.0-alpha09mr02/plugins
  import:       /Users/luanne/neo/neo4j-enterprise-4.0.0-alpha09mr02/import
  data:         /Users/luanne/neo/neo4j-enterprise-4.0.0-alpha09mr02/data
  certificates: /Users/luanne/neo/neo4j-enterprise-4.0.0-alpha09mr02/certificates
  run:          /Users/luanne/neo/neo4j-enterprise-4.0.0-alpha09mr02/run
Starting Neo4j.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.commons.lang3.reflect.FieldUtils (file:/Users/luanne/neo/neo4j-enterprise-4.0.0-alpha09mr02/lib/commons-lang3-3.9.jar) to field sun.nio.ch.FileChannelImpl.fd
WARNING: Please consider reporting this to the maintainers of org.apache.commons.lang3.reflect.FieldUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-08-22 07:53:57.325+0000 WARN  The 'dbms.jvm.additional' setting is overridden. Setting value changed from '-XX:+UseG1GC' to '-XX:-OmitStackTraceInFastThrow'.
2019-08-22 07:53:57.327+0000 WARN  The 'dbms.jvm.additional' setting is overridden. Setting value changed from '-XX:-OmitStackTraceInFastThrow' to '-XX:+AlwaysPreTouch'.
2019-08-22 07:53:57.327+0000 WARN  The 'dbms.jvm.additional' setting is overridden. Setting value changed from '-XX:+AlwaysPreTouch' to '-XX:+UnlockExperimentalVMOptions'.
2019-08-22 07:53:57.327+0000 WARN  The 'dbms.jvm.additional' setting is overridden. Setting value changed from '-XX:+UnlockExperimentalVMOptions' to '-XX:+TrustFinalNonStaticFields'.
2019-08-22 07:53:57.327+0000 WARN  The 'dbms.jvm.additional' setting is overridden. Setting value changed from '-XX:+TrustFinalNonStaticFields' to '-XX:+DisableExplicitGC'.
2019-08-22 07:53:57.327+0000 WARN  The 'dbms.jvm.additional' setting is overridden. Setting value changed from '-XX:+DisableExplicitGC' to '-Djdk.tls.ephemeralDHKeySize=2048'.
2019-08-22 07:53:57.328+0000 WARN  The 'dbms.jvm.additional' setting is overridden. Setting value changed from '-Djdk.tls.ephemeralDHKeySize=2048' to '-Djdk.tls.rejectClientInitiatedRenegotiation=true'.
2019-08-22 07:53:57.348+0000 INFO  ======== Neo4j 4.0.0-alpha09mr02 ========
2019-08-22 07:53:57.350+0000 INFO  Starting...
2019-08-22 07:54:01.952+0000 INFO  Sending metrics to CSV file at /Users/luanne/neo/neo4j-enterprise-4.0.0-alpha09mr02/metrics
2019-08-22 07:54:02.267+0000 INFO  Bolt enabled on localhost:7687.
2019-08-22 07:54:02.267+0000 INFO  Started.
2019-08-22 07:54:02.394+0000 INFO  Mounted REST API at: /db/manage
2019-08-22 07:54:02.482+0000 ERROR Failed to start Neo4j on localhost:7474: null
2019-08-22 07:54:02.483+0000 INFO  Stopping...
2019-08-22 07:54:05.326+0000 INFO  Stopped.
2019-08-22 07:54:05.326+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@6dbeaef8' was successfully initialized, but failed to start. Please see the attached cause exception "null". Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@6dbeaef8' was successfully initialized, but failed to start. Please see the attached cause exception "null".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@6dbeaef8' was successfully initialized, but failed to start. Please see the attached cause exception "null".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:158)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:117)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:89)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@6dbeaef8' was successfully initialized, but failed to start. Please see the attached cause exception "null".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:151)
	... 3 more
Caused by: java.lang.NullPointerException
	at com.neo4j.server.enterprise.CommercialNeoServer.lambda$createWebServer$0(CommercialNeoServer.java:60)
	at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:142)
	at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:252)
	at org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter.start(AbstractNeoServer.java:469)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 5 more
2019-08-22 07:54:05.327+0000 INFO  Neo4j Server shutdown initiated by request
```

**Comment by OliviaYtterbrink** [comment]
Thank you for reporting, a fix for this will be available in the next milestone release.
