### ISSUE TITLE
Maximum id limit for RELATIONSHIP_TYPE_TOKEN has been reached

### ISSUE THREAD

**Issue by karezi** [neo4j/neo4j#12321]
I have a large neo4j database with 11061285 nodes and 13635924 relationships, but cannot show the relationship types with Neo4j because maximum id limit.

** Neo4j version: neo4j-enterprise-3.5.11
** Operating system: MacOS 10.15
** API/Driver: Cypher or Java API

Reproduce and behavior
- Use Cypher
```
$ match (n)-[r]-() RETURN r
```
I got the error:
```
Neo.DatabaseError.General.UnknownError: Kernel API returned non-existent relationship type: 2
```
neo4j.log:
```
2019-10-22 08:55:16.490+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@75d982d3' was successfully initialized, but failed to start. Please see the attached cause exception "Maximum id limit for RELATIONSHIP_TYPE_TOKEN has been reached. Generated id 65536 is out of permitted range [0, 65535].". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@75d982d3' was successfully initialized, but failed to start. Please see the attached cause exception "Maximum id limit for RELATIONSHIP_TYPE_TOKEN has been reached. Generated id 65536 is out of permitted range [0, 65535].".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@75d982d3' was successfully initialized, but failed to start. Please see the attached cause exception "Maximum id limit for RELATIONSHIP_TYPE_TOKEN has been reached. Generated id 65536 is out of permitted range [0, 65535].".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@75d982d3' was successfully initialized, but failed to start. Please see the attached cause exception "Maximum id limit for RELATIONSHIP_TYPE_TOKEN has been reached. Generated id 65536 is out of permitted range [0, 65535].".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /Users/karezi/Desktop/neo4j-enterprise-3.5.11/data/databases
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:232)
	at com.neo4j.commercial.edition.CommercialGraphDatabase.<init>(CommercialGraphDatabase.java:20)
	at com.neo4j.server.database.CommercialGraphFactory.newGraphDatabase(CommercialGraphFactory.java:40)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@4228bf58' was successfully initialized, but failed to start. Please see the attached cause exception "Maximum id limit for RELATIONSHIP_TYPE_TOKEN has been reached. Generated id 65536 is out of permitted range [0, 65535].".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:116)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:227)
	... 9 more
Caused by: java.lang.RuntimeException: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine@3ed7821' was successfully initialized, but failed to start. Please see the attached cause exception "Maximum id limit for RELATIONSHIP_TYPE_TOKEN has been reached. Generated id 65536 is out of permitted range [0, 65535].".
	at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:459)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 14 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine@3ed7821' was successfully initialized, but failed to start. Please see the attached cause exception "Maximum id limit for RELATIONSHIP_TYPE_TOKEN has been reached. Generated id 65536 is out of permitted range [0, 65535].".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:443)
	... 15 more
Caused by: org.neo4j.kernel.impl.store.id.validation.IdCapacityExceededException: Maximum id limit for RELATIONSHIP_TYPE_TOKEN has been reached. Generated id 65536 is out of permitted range [0, 65535].
	at org.neo4j.kernel.impl.store.id.validation.IdValidator.assertIdWithinCapacity(IdValidator.java:90)
	at org.neo4j.kernel.impl.store.id.IdGeneratorImpl.setHighId(IdGeneratorImpl.java:170)
	at org.neo4j.kernel.impl.store.CommonAbstractStore.setHighId(CommonAbstractStore.java:660)
	at org.neo4j.kernel.impl.store.CommonAbstractStore.rebuildIdGenerator(CommonAbstractStore.java:464)
	at org.neo4j.kernel.impl.store.CommonAbstractStore.makeStoreOk(CommonAbstractStore.java:678)
	at org.neo4j.kernel.impl.store.NeoStores.lambda$makeStoreOk$0(NeoStores.java:459)
	at org.neo4j.kernel.impl.store.CommonAbstractStore.visitStore(CommonAbstractStore.java:973)
	at org.neo4j.kernel.impl.store.NeoStores.visitStore(NeoStores.java:504)
	at org.neo4j.kernel.impl.store.NeoStores.makeStoreOk(NeoStores.java:457)
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.start(RecordStorageEngine.java:376)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 17 more
	Suppressed: org.neo4j.kernel.lifecycle.LifecycleException: Exception during graceful attempt to stop partially started component. Please use non suppressed exception to see original component failure.
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:464)
		... 17 more
	Caused by: java.lang.NullPointerException
		at org.neo4j.kernel.impl.storageengine.impl.recordstorage.id.BufferedIdController.stop(BufferedIdController.java:59)
		at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.stop(RecordStorageEngine.java:401)
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:460)
		... 17 more
```

- Use Java API
I tried to connect to db with Java API:
```
import org.neo4j.graphdb.*;
import org.neo4j.graphdb.factory.GraphDatabaseFactory;
import java.io.File;

public class FindRelationType {
    public static void main(String[] args) {
        final GraphDatabaseService gdb = new GraphDatabaseFactory()
                .newEmbeddedDatabase(new File("/Users/karezi/Desktop/neo4j-enterprise-3.5.11/data/databases/graph.db"));
        findRelType(gdb);
        gdb.shutdown();
    }

    private static void findRelType(GraphDatabaseService graphdb) {
        Transaction tx = graphdb.beginTx();
        int count = 0;
        try {
            for (Node n: graphdb.getAllNodes()) {
                if (count++ > 100) {
                    break;
                }
                for(RelationshipType rt: n.getRelationshipTypes()) {
                    System.out.println(rt.name());
                }
            }
        } finally {
            tx.success();
            tx.close();
        }
    }
}
```
I got the following errors:
```
Exception in thread "main" java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /Users/karezi/Desktop/neo4j-enterprise-3.5.11/data/databases
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:232)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:148)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:133)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(GraphDatabaseFactory.java:122)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory$EmbeddedDatabaseCreator.newDatabase(GraphDatabaseFactory.java:178)
	at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:210)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(GraphDatabaseFactory.java:79)
	at org.neo4j.tool.FindRelationType.main(FindRelationType.java:10)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@2a2843ec' was successfully initialized, but failed to start. Please see the attached cause exception "Maximum id limit for RELATIONSHIP_TYPE_TOKEN has been reached. Generated id 65536 is out of permitted range [0, 65535].".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:116)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:227)
	... 7 more
Caused by: java.lang.RuntimeException: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine@81b5db0' was successfully initialized, but failed to start. Please see the attached cause exception "Maximum id limit for RELATIONSHIP_TYPE_TOKEN has been reached. Generated id 65536 is out of permitted range [0, 65535].".
	at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:459)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 12 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine@81b5db0' was successfully initialized, but failed to start. Please see the attached cause exception "Maximum id limit for RELATIONSHIP_TYPE_TOKEN has been reached. Generated id 65536 is out of permitted range [0, 65535].".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:443)
	... 13 more
Caused by: org.neo4j.kernel.impl.store.id.validation.IdCapacityExceededException: Maximum id limit for RELATIONSHIP_TYPE_TOKEN has been reached. Generated id 65536 is out of permitted range [0, 65535].
	at org.neo4j.kernel.impl.store.id.validation.IdValidator.assertIdWithinCapacity(IdValidator.java:90)
	at org.neo4j.kernel.impl.store.id.IdGeneratorImpl.setHighId(IdGeneratorImpl.java:170)
	at org.neo4j.kernel.impl.store.CommonAbstractStore.setHighId(CommonAbstractStore.java:660)
	at org.neo4j.kernel.impl.store.CommonAbstractStore.rebuildIdGenerator(CommonAbstractStore.java:464)
	at org.neo4j.kernel.impl.store.CommonAbstractStore.makeStoreOk(CommonAbstractStore.java:678)
	at org.neo4j.kernel.impl.store.NeoStores.lambda$makeStoreOk$0(NeoStores.java:459)
	at org.neo4j.kernel.impl.store.CommonAbstractStore.visitStore(CommonAbstractStore.java:973)
	at org.neo4j.kernel.impl.store.NeoStores.visitStore(NeoStores.java:504)
	at org.neo4j.kernel.impl.store.NeoStores.makeStoreOk(NeoStores.java:457)
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.start(RecordStorageEngine.java:376)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 15 more
	Suppressed: org.neo4j.kernel.lifecycle.LifecycleException: Exception during graceful attempt to stop partially started component. Please use non suppressed exception to see original component failure.
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:464)
		... 15 more
	Caused by: java.lang.NullPointerException
		at org.neo4j.kernel.impl.storageengine.impl.recordstorage.id.BufferedIdController.stop(BufferedIdController.java:59)
		at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.stop(RecordStorageEngine.java:401)
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:460)
		... 15 more
```

I also tried to use copy-store.sh according to https://neo4j.com/developer/kb/explanation-of-error-record-id-65536-is-out-of-range/, but it just deleted all the relationships in the db and didn't fix my problem.

**Comment by chrisvest** [comment]
@karezi You have run out of the available relationship _types_. This is indicative of a problem with how you model your domain in the graph. Problems like this can show up when people encode relationship properties in their relationship types.

Since changing the data model is a lot of work, you can try upgrading to the `high_limit` format in the mean time, by adding settings like this to your `neo4j.conf`:

```
dbms.allow_upgrade=true
dbms.record_format=high_limit
```

**Comment by karezi** [comment]
@chrisvest Thanks for your helping. I have tried to upgrade my db files using new settings as you say. Unfortunately, new errors occured during upgrading and now I cannot start neo4j.
This is my logs:
```
2019-10-23 08:38:56.748+0000 INFO  Neo4j Server shutdown initiated by request
2019-10-23 08:42:10.946+0000 INFO  ======== Neo4j 3.5.11 ========
2019-10-23 08:42:10.954+0000 INFO  Starting...
2019-10-23 08:42:11.899+0000 INFO  Initiating metrics...
2019-10-23 08:42:12.228+0000 INFO  Starting upgrade of database
2019-10-23 08:42:29.058+0000 INFO  Migrating Indexes (1/5):
2019-10-23 08:42:29.063+0000 INFO    10% completed
2019-10-23 08:42:29.063+0000 INFO    20% completed
2019-10-23 08:42:29.063+0000 INFO    30% completed
2019-10-23 08:42:29.063+0000 INFO    40% completed
2019-10-23 08:42:29.063+0000 INFO    50% completed
2019-10-23 08:42:29.063+0000 INFO    60% completed
2019-10-23 08:42:29.064+0000 INFO    70% completed
2019-10-23 08:42:29.064+0000 INFO    80% completed
2019-10-23 08:42:29.064+0000 INFO    90% completed
2019-10-23 08:42:29.064+0000 INFO    100% completed
2019-10-23 08:42:29.064+0000 INFO  Migrating Explicit indexes (2/5):
2019-10-23 08:42:29.066+0000 INFO    10% completed
2019-10-23 08:42:29.066+0000 INFO    20% completed
2019-10-23 08:42:29.066+0000 INFO    30% completed
2019-10-23 08:42:29.066+0000 INFO    40% completed
2019-10-23 08:42:29.066+0000 INFO    50% completed
2019-10-23 08:42:29.067+0000 INFO    60% completed
2019-10-23 08:42:29.067+0000 INFO    70% completed
2019-10-23 08:42:29.067+0000 INFO    80% completed
2019-10-23 08:42:29.067+0000 INFO    90% completed
2019-10-23 08:42:29.067+0000 INFO    100% completed
2019-10-23 08:42:29.067+0000 INFO  Migrating Store files (3/5):
2019-10-23 08:44:15.901+0000 INFO    10% completed
2019-10-23 08:44:41.936+0000 INFO    20% completed
2019-10-23 08:44:46.702+0000 INFO    30% completed
2019-10-23 08:44:46.703+0000 INFO    40% completed
2019-10-23 08:44:46.703+0000 INFO    50% completed
2019-10-23 08:44:46.703+0000 INFO    60% completed
2019-10-23 08:44:47.704+0000 INFO    70% completed
2019-10-23 08:44:48.705+0000 INFO    80% completed
2019-10-23 08:44:49.705+0000 INFO    90% completed
2019-10-23 08:44:50.708+0000 INFO    100% completed
2019-10-23 08:45:04.495+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@383f1975' was successfully initialized, but failed to start. Please see the attached cause exception "Requested index 631, but length is 1". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@383f1975' was successfully initialized, but failed to start. Please see the attached cause exception "Requested index 631, but length is 1".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@383f1975' was successfully initialized, but failed to start. Please see the attached cause exception "Requested index 631, but length is 1".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@383f1975' was successfully initialized, but failed to start. Please see the attached cause exception "Requested index 631, but length is 1".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /Users/karezi/Desktop/neo4j-enterprise-3.5.11/data/databases
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:232)
	at com.neo4j.commercial.edition.CommercialGraphDatabase.<init>(CommercialGraphDatabase.java:20)
	at com.neo4j.server.database.CommercialGraphFactory.newGraphDatabase(CommercialGraphFactory.java:40)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@629f066f' was successfully initialized, but failed to start. Please see the attached cause exception "Requested index 631, but length is 1".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:116)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:227)
	... 9 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Requested index 631, but length is 1
	at org.neo4j.unsafe.impl.batchimport.cache.OffHeapRegularNumberArray.addressOf(OffHeapRegularNumberArray.java:42)
	at org.neo4j.unsafe.impl.batchimport.cache.OffHeapLongArray.get(OffHeapLongArray.java:43)
	at org.neo4j.unsafe.impl.batchimport.RelationshipCountsProcessor.increment(RelationshipCountsProcessor.java:176)
	at org.neo4j.unsafe.impl.batchimport.RelationshipCountsProcessor.process(RelationshipCountsProcessor.java:84)
	at org.neo4j.unsafe.impl.batchimport.ProcessRelationshipCountsDataStep.process(ProcessRelationshipCountsDataStep.java:98)
	at org.neo4j.unsafe.impl.batchimport.ProcessRelationshipCountsDataStep.process(ProcessRelationshipCountsDataStep.java:42)
	at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.lambda$receive$1(ProcessorStep.java:79)
	at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:224)
	Suppressed: org.neo4j.unsafe.impl.batchimport.executor.TaskExecutionPanicException: Executor has been shut down in panic
		at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.assertHealthy(DynamicTaskExecutor.java:143)
		at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.submit(DynamicTaskExecutor.java:123)
		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.receive(ProcessorStep.java:72)
		at org.neo4j.unsafe.impl.batchimport.staging.Downstream.send(Downstream.java:56)
		at org.neo4j.unsafe.impl.batchimport.staging.SendDownstream.apply(SendDownstream.java:58)
		at org.neo4j.unsafe.impl.batchimport.staging.SendDownstream.apply(SendDownstream.java:26)
		at org.neo4j.util.concurrent.WorkSync.doSynchronizedWork(WorkSync.java:231)
		at org.neo4j.util.concurrent.WorkSync.tryDoWork(WorkSync.java:157)
		at org.neo4j.util.concurrent.WorkSync.applyAsync(WorkSync.java:122)
		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.sendDownstream(ProcessorStep.java:157)
		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.access$100(ProcessorStep.java:42)
		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep$Sender.send(ProcessorStep.java:224)
		at org.neo4j.unsafe.impl.batchimport.staging.ReadRecordsStep.process(ReadRecordsStep.java:97)
		at org.neo4j.unsafe.impl.batchimport.staging.ReadRecordsStep.process(ReadRecordsStep.java:36)
		... 2 more
	Caused by: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Requested index 631, but length is 1
		at org.neo4j.unsafe.impl.batchimport.staging.AbstractStep.issuePanic(AbstractStep.java:155)
		at org.neo4j.unsafe.impl.batchimport.staging.AbstractStep.issuePanic(AbstractStep.java:147)
		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.lambda$receive$1(ProcessorStep.java:94)
		... 1 more
	[CIRCULAR REFERENCE:java.lang.ArrayIndexOutOfBoundsException: Requested index 631, but length is 1]
	Suppressed: java.lang.RuntimeException: org.neo4j.unsafe.impl.batchimport.executor.TaskExecutionPanicException: Executor has been shut down in panic
		at org.neo4j.unsafe.impl.batchimport.staging.AbstractStep.issuePanic(AbstractStep.java:155)
		at org.neo4j.unsafe.impl.batchimport.staging.AbstractStep.issuePanic(AbstractStep.java:147)
		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.sendDownstream(ProcessorStep.java:168)
		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.access$100(ProcessorStep.java:42)
		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep$Sender.send(ProcessorStep.java:224)
		at org.neo4j.unsafe.impl.batchimport.staging.ReadRecordsStep.process(ReadRecordsStep.java:97)
		at org.neo4j.unsafe.impl.batchimport.staging.ReadRecordsStep.process(ReadRecordsStep.java:36)
		... 2 more
	[CIRCULAR REFERENCE:org.neo4j.unsafe.impl.batchimport.executor.TaskExecutionPanicException: Executor has been shut down in panic]
	Suppressed: org.neo4j.unsafe.impl.batchimport.executor.TaskExecutionPanicException: Executor has been shut down in panic
		at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.assertHealthy(DynamicTaskExecutor.java:143)
		at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.submit(DynamicTaskExecutor.java:128)
		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.receive(ProcessorStep.java:72)
		at org.neo4j.unsafe.impl.batchimport.staging.ProducerStep.sendDownstream(ProducerStep.java:82)
		at org.neo4j.unsafe.impl.batchimport.staging.PullingProducerStep.process(PullingProducerStep.java:50)
		at org.neo4j.unsafe.impl.batchimport.staging.ProducerStep$1.run(ProducerStep.java:63)
	Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.neo4j.unsafe.impl.batchimport.executor.TaskExecutionPanicException: Executor has been shut down in panic
		at org.neo4j.unsafe.impl.batchimport.staging.AbstractStep.issuePanic(AbstractStep.java:155)
		at org.neo4j.unsafe.impl.batchimport.staging.AbstractStep.issuePanic(AbstractStep.java:147)
		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.lambda$receive$1(ProcessorStep.java:94)
		at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:224)
	[CIRCULAR REFERENCE:java.lang.RuntimeException: org.neo4j.unsafe.impl.batchimport.executor.TaskExecutionPanicException: Executor has been shut down in panic]
2019-10-23 08:45:04.496+0000 INFO  Neo4j Server shutdown initiated by request
```

**Comment by tinwelint** [comment]
Interestingly `java.lang.ArrayIndexOutOfBoundsException: Requested index 631, but length is 1` <-- `length 1` there indicates that the store thinks that there are no relationship types in it. Would it be possible to get a look at your:

- `neostore.relationshiptypestore.db`
- `neostore.relationshiptypestore.db.id`
- `neostore.relationshiptypestore.db.names`
- `neostore.relationshiptypestore.db.names.id`

files?

**Comment by karezi** [comment]
@tinwelint 
```
-rwxrwxrwx@ 1 karezi  admin   328K  5 11  2019 neostore.relationshiptypestore.db
-rw-r--r--  1 karezi  admin     9B 11 18 02:28 neostore.relationshiptypestore.db.id
-rwxrwxrwx@ 1 karezi  admin   2.4M  5 11  2019 neostore.relationshiptypestore.db.names
-rw-r--r--  1 karezi  admin     9B 11 18 02:28 neostore.relationshiptypestore.db.names.id
```

**Comment by tinwelint** [comment]
Thanks, I meant the actual files, perhaps email me them directly if possible?

**Comment by tinwelint** [comment]
Do you think we can make more progress on this issue, or can we close it?

**Comment by tinwelint** [comment]
You don't have the files then @karezi ?

**Comment by Right-ty** [comment]
Hello, I also encountered the same problem。
ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@383f1975' was successfully initialized, but failed to start. Please see the attached cause exception "Requested index 631, but length is 1".

**Comment by Right-ty** [comment]
@tinwelint 
Hello, I also encountered the same problem, how to solve it?

- Neo4j version: neo4j-enterprise-3.5.20

ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@383f1975' was successfully initialized, but failed to start. Please see the attached cause exception "Requested index 631, but length is 1".

**Comment by Right-ty** [comment]
@tinwelint 
Hello, I also encountered the same problem, how to solve it?

- Neo4j version: neo4j-enterprise-3.5.20

`ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@383f1975' was successfully initialized, but failed to start. Please see the attached cause exception "Requested index 631, but length is 1".`
