### ISSUE TITLE
NPE when setting label during a MERGE with a native + fulltext index

### ISSUE THREAD

**Issue by jgaskins** [neo4j/neo4j#12346]
- Neo4j version: 3.5.12 
- Operating system: macOS Catalina 10.15.1
- API/Driver: [Neo4j.cr](https://github.com/jgaskins/neo4j.cr)

## Steps to reproduce

1. `CALL db.index.fulltext.createNodeIndex('foo', ['Account'], ['id', 'display_name', 'handle'], { analyzer: 'english' })`
2. `CREATE INDEX ON :Person(id)`
3. `MERGE (person:Person { id: "test" }) SET person:Account`

## Expected behavior

It upserts a `Person` node with the given property and then sets the `Account` label on that node

## Actual behavior

`NullPointerException` manifesting as a `Neo.DatabaseError.General.UnknownError` in the driver.

## Notes

The NPE does not seem to occur if I omit the native index or the FTS index, so it does appear to be related to interplay between them.

<details>
  <summary>Click for stack trace</summary>

```
2019-11-16 05:18:27.242+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: null, reference 606e81c5-55cd-424a-80ee-c0dcfffc1833.
java.lang.NullPointerException
	at org.neo4j.values.storable.ValueTuple.hashCode(ValueTuple.java:108)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1099)
	at org.neo4j.kernel.impl.api.state.TxState.getOrCreateIndexUpdatesForSeek(TxState.java:803)
	at org.neo4j.kernel.impl.api.state.TxState.indexDoUpdateEntry(TxState.java:786)
	at org.neo4j.kernel.impl.newapi.IndexTxStateUpdater.onLabelChange(IndexTxStateUpdater.java:87)
	at org.neo4j.kernel.impl.newapi.Operations.checkConstraintsAndAddLabelToNode(Operations.java:306)
	at org.neo4j.kernel.impl.newapi.Operations.nodeAddLabel(Operations.java:276)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$$anonfun$setLabelsOnNode$1.apply$mcIII$sp(TransactionBoundQueryContext.scala:81)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$$anonfun$setLabelsOnNode$1.apply(TransactionBoundQueryContext.scala:80)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$$anonfun$setLabelsOnNode$1.apply(TransactionBoundQueryContext.scala:80)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1334)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.setLabelsOnNode(TransactionBoundQueryContext.scala:80)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext$$anonfun$setLabelsOnNode$1.apply$mcI$sp(ExceptionTranslatingQueryContext.scala:54)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext$$anonfun$setLabelsOnNode$1.apply(ExceptionTranslatingQueryContext.scala:54)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext$$anonfun$setLabelsOnNode$1.apply(ExceptionTranslatingQueryContext.scala:54)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:33)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:42)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext.setLabelsOnNode(ExceptionTranslatingQueryContext.scala:54)
	at org.neo4j.cypher.internal.runtime.interpreted.UpdateCountingQueryContext.setLabelsOnNode(UpdateCountingQueryContext.scala:88)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.SetLabelsOperation.set(SetOperation.scala:315)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.SetPipe$$anonfun$internalCreateResults$1.apply(SetPipe.scala:32)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.SetPipe$$anonfun$internalCreateResults$1.apply(SetPipe.scala:31)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EmptyResultPipe.internalCreateResults(EmptyResultPipe.scala:29)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:76)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:72)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.BaseExecutionResultBuilderFactory$BaseExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:61)
	at org.neo4j.cypher.internal.compatibility.InterpretedRuntime$InterpretedExecutionPlan.run(InterpretedRuntime.scala:84)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$3.apply(CypherCurrentCompiler.scala:205)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$3.apply(CypherCurrentCompiler.scala:190)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery.execute(CypherCurrentCompiler.scala:224)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:101)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:85)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachineV1SPI$BoltResultHandleV1.start(TransactionStateMachineV1SPI.java:189)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.startExecution(TransactionStateMachine.java:506)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.execute(TransactionStateMachine.java:300)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:269)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:110)
	at org.neo4j.bolt.v3.runtime.ReadyState.processRunMessage(ReadyState.java:85)
	at org.neo4j.bolt.v3.runtime.ReadyState.processUnsafe(ReadyState.java:56)
	at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
	at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.lambda$enqueue$0(MetricsReportingBoltConnection.java:68)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
	at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.processNextBatch(MetricsReportingBoltConnection.java:86)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

## Background

Every node with the `Person` label represents a person, but may not be a fully fledged account yet (data hasn't propagated, etc), so it's not eligible for the `Account` label. The `MERGE` query is part of that — it sets the properties and assigns the `Account` label, but we can't do a `MATCH` since the node is not guaranteed to exist yet.

**Comment by chrisvest** [comment]
Thanks. We have already merged a fix for this, which will be part of the next 3.5 release.

**Comment by chrisvest** [comment]
Originally reported in https://github.com/neo4j/neo4j/issues/12249

**Comment by jgaskins** [comment]
I saw that issue but I didn't think it was related. I just had a second look and [this comment](https://github.com/neo4j/neo4j/issues/12249#issuecomment-545075880) does seem to cover it. Thanks!
