### ISSUE TITLE
Access to record Node[] went out of bounds of the page

### ISSUE THREAD

**Issue by Silkjaer** [neo4j/neo4j#12350]
Neo4j shut down unexpectedly during data import using the JS driver and apoc.periodic.iterate. It was importing relations in batches of 2.500.000, divided into smaller batches to avoid parallel deadlock issues, and has been importing billions of relations without any errors.

- Neo4j version: 3.5.11
- Operating system: Ubuntu 18.04.3 LTS

Output from debug.log:
```
2019-11-21 22:10:23.016+0000 WARN [o.n.k.NeoStoreDataSource] Exception occurred while starting the datasource. Attempting to close things down. Component 'org.neo4j.kernel.recovery.Recovery@597f0937' failed to initialize. Please see the attached cause exception "Access to record Node[2042845695,used=false,rel=-1,prop=-1,labels=Inline(0x0:[]),light,secondaryUnitId=-1] went out of bounds of the page. The record size is 16 bytes, and the access was at offset 8176 bytes into page 3989932, and the pages have a capacity of 8192 bytes. The mapped store file in question is /data/neo4j/data/databases/***.db/neostore.nodestore.db".
org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.recovery.Recovery@597f0937' failed to initialize. Please see the attached cause exception "Access to record Node[2042845695,used=false,rel=-1,prop=-1,labels=Inline(0x0:[]),light,secondaryUnitId=-1] went out of bounds of the page. The record size is 16 bytes, and the access was at offset 8176 bytes into page 3989932, and the pages have a capacity of 8192 bytes. The mapped store file in question is /data/neo4j/data/databases/***.db/neostore.nodestore.db".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:434)
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:66)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:102)
	at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:443)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:116)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:227)
	at com.neo4j.commercial.edition.CommercialGraphDatabase.<init>(CommercialGraphDatabase.java:20)
	at com.neo4j.server.database.CommercialGraphFactory.newGraphDatabase(CommercialGraphFactory.java:40)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: java.lang.RuntimeException: Error reading transaction logs, recovery not possible. To force the database to start anyway, you can specify 'unsupported.dbms.tx_log.fail_on_corrupted_log_files=false'. This will try to recover as much as possible and then truncate the corrupt part of the transaction log. Doing this means your database integrity might be compromised, please consider restoring from a consistent backup instead.
	at org.neo4j.kernel.recovery.Recovery.throwUnableToCleanRecover(Recovery.java:160)
	at org.neo4j.kernel.recovery.Recovery.init(Recovery.java:136)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:413)
	... 18 more
Caused by: org.neo4j.kernel.api.exceptions.TransactionApplyKernelException: Failed to apply transaction: Transaction #264597 at log position LogPosition{logVersion=8614, byteOffset=146544210} {started 2019-11-21 18:29:27.017+0000, committed 2019-11-21 18:39:57.359+0000, with 6060122 commands in this transaction, authored by -1, with master id -1, lock session -1, latest committed transaction id when started was 264562, additional header bytes: 
80
70
F5
EA
A4
88
0F
80}
```

**Comment by chrisvest** [comment]
A fix for this has been merged, and will be part of the next 3.5 patch release. Be aware, however, that this bug caused wrong data to be written to the transaction log if you use the high_limit format _and_ have transactions that modify a particular range of a large store. The wrong data only matter if recovery is needed, but when that is the case recovery will break with the exception you see. What has been fixed is the writing to the transaction log, but existing old logs can still break recovery.
