### ISSUE TITLE
neo4j will fail to start when using other's graph

### ISSUE THREAD

**Issue by Jaggar2018** [neo4j/neo4j#12379]
I discover that when I try to open others' graph by use their databases and dbms to overwrite mine, 
neo4j will fail to start. (running on the server)

**Neo4j Version: 3.4.17 
**Operating System: CentOS Linux release 7.5.1804 (Core)

### Steps to reproduce
1. Load others‘graph by using their dmbs and databases file to overwrite my data file.
(PS: I can start the neo4j successfully when I use my own dmbs and databases)
2. Run: neo4j start

3. Here is the neo4j-community-3.4.17/logs/neo4j.log: 
ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3003697' was successfully initialized, but failed to start. Please see the attached cause exception "/home/wangyi/neo4j-community-3.4.17/data/databases/graph.db/schema/index/lucene_native-2.0/9/lucene-1.0/failure-message (Too many open files)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3003697' was successfully initialized, but failed to start. Please see the attached cause exception "/home/wangyi/neo4j-community-3.4.17/data/databases/graph.db/schema/index/lucene_native-2.0/9/lucene-1.0/failure-message (Too many open files)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3003697' was successfully initialized, but failed to start. Please see the attached cause exception "/home/wangyi/neo4j-community-3.4.17/data/databases/graph.db/schema/index/lucene_native-2.0/9/lucene-1.0/failure-message (Too many open files)".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3003697' was successfully initialized, but failed to start. Please see the attached cause exception "/home/wangyi/neo4j-community-3.4.17/data/databases/graph.db/schema/index/lucene_native-2.0/9/lucene-1.0/failure-message (Too many open files)".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /home/wangyi/neo4j-community-3.4.17/data/databases/graph.db

### Expected behavior
the neo4j can be started succesfully

### Actual behavior
ERR_CONNECTION_REFUSED

Thanks a lot if anyone can help

**Comment by sherfert** [comment]
Your error message says "Too many open files". This in an OS problem. Please try following these steps: https://neo4j.com/developer/kb/number-of-open-files/

**Comment by Jaggar2018** [comment]
Solved by setting the open files number limit of server.
Thanks!

**Comment by Jaggar2018** [comment]
Solved by setting the open files number limit of server.
Thanks!
