### ISSUE TITLE
Neo4j 4.0 Java IOException User limit of inotify watches reached 

### ISSUE THREAD

**Issue by benjaminh** [neo4j/neo4j#12380]
On a fresh install of Neo4j 4.0 on an ubuntu 18.04 distrib, I get the following error when starting the server : `java.io.IOException: User limit of inotify watches reached`

- Neo4j version: 4.0.0
- Operating system: Ubuntu 18.04
- **Steps to reproduce**
  * go to neo4j server directory
  * start the server `./bin/neo4j start`
- Expected behavior : server starting and Neo4j browser accessible at `localhost:7474`
- Actual behavior : server seems starting but not available.
```
Starting Neo4j.
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
Started neo4j (pid 14660). It is available at http://localhost:7474/
There may be a short delay until the server is ready.
```
When looking at the logs, the message is explicit
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2020-01-20 12:19:47.583+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabaseService@61874b9d' was successfully initialized, but failed to start. Please see the attached cause exception "User limit of inotify watches reached".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabaseService@61874b9d' was successfully initialized, but failed to start. Please see the attached cause exception "User limit of inotify watches reached".
[...]
Caused by: java.io.IOException: User limit of inotify watches reached
        at java.base/sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:266)
        at java.base/sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:265)
        at java.base/sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:366)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-01-20 12:19:47.589+0000 INFO  Neo4j Server shutdown initiated by request
```
Tell me if you need the full log trace.

I did some research to increase this limitation, but I'm not sure about the way you guys would advise me to proceed. Also, maybe it is possible to get some feedback with an error message instead of going to check logs ?

**Comment by sherfert** [comment]
Did increasing the limit (like described [here](https://stackoverflow.com/questions/47075661/error-user-limit-of-inotify-watches-reached-extreact-build) for example) help?

**Comment by benjaminh** [comment]
I had to delete the content in the data repository (otherwise, the Neo4j server silently crashes again, and the logs tell me that it is complaining about missing transaction logs), but yes, increasing the limit to 524288 (according to your source) does help !

**Comment by sherfert** [comment]
@benjaminh 
That's nice to hear. Is there anything you would want us to investigate with the complaint about missing transaction longs or should we close this issue?

**Comment by benjaminh** [comment]
@sherfert I'm not sure, but wouldn't it be better if the command line output tells that the server crashes rather than saying that it has started and available at `localhost:7474` ? Because if we look at `./bin/neo4j status`, it says that `Neo4j is running` so this is confusing. Looked like an issue to me, but maybe this is just a feature ?
Plus : maybe the installation doc should mention this possible limitation as a requirement ?

Regarding the missing transaction logs : why does this error occurs ? Is it because the server crashes in the first time ? If so, maybe a hint or a more explicit message would help. Also, an error message when trying to start the server would also help :)
