### ISSUE TITLE
Isolation issue in Neo4j 3.5.8

### ISSUE THREAD

**Issue by luanne** [neo4j/neo4j#12382]
**Neo4j Version:** 3.5.8

### Steps to reproduce
1. Set up a test which concurrently executes two Cypher queries under load- one that deletes nodes, and the second that reads nodes and relationships  (we used JMeter and Blazerunner)
2. Record the results

### Expected behavior
Zero failures

### Actual behavior
The read query fails intermittently.

Here are the results of testing on two different databases, with two different sets of queries-

**Database 1:**

Delete query-

```
MATCH (project:BuildingProject {vertex_id: $vertex_id})
OPTIONAL MATCH (project)-[:VIEW]->(project_view:BuildingProjectView)
OPTIONAL MATCH (project)-[:SOURCED]->(bim_project:BimProject)
OPTIONAL MATCH (project)-[:SOURCED]->(tally_project:TallyProject)
OPTIONAL MATCH (project_view)-[:CONTAINS*]->(project_view_label:BuildingProjectViewLabel)
OPTIONAL MATCH (project_view_label)-[:CONTAINS_ELEMENT]->(element:BuildingElement)
DETACH DELETE project, project_view, project_view_label, element, bim_project, tally_project
```

Read query-
```
MATCH (n:BuildingItem)
WHERE NOT coalesce(n.temporary, false) AND NOT n:Archived
MATCH (user:Person)
 WHERE id(user) = $trustee
MATCH (n)<-[*..6 {r: true}]-(user)
WITH DISTINCT n, user
OPTIONAL MATCH (n)<-[:INCLUDES]-(parent:BuildingItem)

OPTIONAL MATCH paths_to_parent = shortestPath((parent)<-[*..6]-(user))
 WHERE ALL(rr IN relationships(paths_to_parent)
   WHERE exists(rr.r))
WITH n, user, size(collect(paths_to_parent)) > 0 AS can_read_parent
 WHERE NOT (n)<-[:INCLUDES]-(:BuildingItem) OR can_read_parent = false
WITH DISTINCT n, user

ORDER BY n.sort_key_type DESC
SKIP $skip LIMIT $limit
WITH n, user
OPTIONAL MATCH paths = shortestPath((n)<-[*..6]-(user))
 WHERE ALL(rr IN relationships(paths)
   WHERE exists(rr.w))
WITH CASE WHEN size(collect(paths)) > 0 THEN 4 ELSE 0 END AS W, n, user
OPTIONAL MATCH paths = shortestPath((n)<-[*..6]-(user))
 WHERE ALL(rr IN relationships(paths)
   WHERE exists(rr.m))
WITH CASE WHEN size(collect(paths)) > 0 THEN 8 ELSE 0 END AS M, n, user, 1 as H, 2 as R, W
OPTIONAL MATCH (n)-[:VIEW]->(view:BuildingProjectView)
WHERE (view)-[:CONTAINS]->(:BuildingProjectViewLabel)
OPTIONAL MATCH (n)<-[:READS|WRITES|MANAGES]-(trustees)
OPTIONAL MATCH (n)<-[:INCLUDES]-(complex:BuildingComplex)
OPTIONAL MATCH (complex)<-[:READS|WRITES|MANAGES]-(complex_trustees)
OPTIONAL MATCH (complex)<-[:INCLUDES]-(campus:BuildingCampus)
OPTIONAL MATCH (campus)<-[:READS|WRITES|MANAGES]-(campus_trustees)
OPTIONAL MATCH (n)<-[:OWNS]-(owner:Person)
RETURN n, owner, apoc.coll.union(apoc.coll.union(collect(trustees), collect(complex_trustees)), collect(campus_trustees))  AS trustees, collect(DISTINCT view) AS views, [H, R, W, M]
```

Failure message in the logs:
```
Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: Node 349272 not found, reference 065f9f43-6a5a-49b6-a3e7-2405ec9416fc. Node 349272 not found
org.neo4j.graphdb.NotFoundException: Node 349272 not found
	at org.neo4j.kernel.impl.core.NodeProxy.getRelationshipSelectionIterator(NodeProxy.java:780)
	at org.neo4j.kernel.impl.core.NodeProxy.lambda$innerGetRelationships$0(NodeProxy.java:157)
	at org.neo4j.graphdb.ResourceIterable.iterator(ResourceIterable.java:76)
	at org.neo4j.graphdb.impl.StandardExpander$AllExpander.doExpand(StandardExpander.java:231)
	at org.neo4j.graphdb.impl.StandardExpander$FilteringExpander.doExpand(StandardExpander.java:590)
	at org.neo4j.graphdb.impl.StandardExpander$RelationshipExpansion.iterator(StandardExpander.java:163)
	at org.neo4j.graphdb.impl.StandardExpander$RelationshipExpansion.iterator(StandardExpander.java:134)
	at org.neo4j.graphalgo.impl.path.ShortestPath$DirectionData$1.createNestedIterator(ShortestPath.java:370)
	at org.neo4j.graphalgo.impl.path.ShortestPath$DirectionData$1.createNestedIterator(ShortestPath.java:365)
	at org.neo4j.helpers.collection.NestingResourceIterator.fetchNextOrNull(NestingResourceIterator.java:49)
	at org.neo4j.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
	at org.neo4j.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
	at org.neo4j.graphalgo.impl.path.ShortestPath$DirectionData.fetchNextRelOrNull(ShortestPath.java:443)
	at org.neo4j.graphalgo.impl.path.ShortestPath$DirectionData.fetchNextOrNull(ShortestPath.java:396)
	at org.neo4j.graphalgo.impl.path.ShortestPath$DirectionData.fetchNextOrNull(ShortestPath.java:319)
	at org.neo4j.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
	at org.neo4j.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
	at org.neo4j.graphalgo.impl.path.ShortestPath.internalPaths(ShortestPath.java:161)
	at org.neo4j.graphalgo.impl.path.ShortestPath.findSinglePath(ShortestPath.java:127)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.singleShortestPath(TransactionBoundQueryContext.scala:961)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext$$anonfun$singleShortestPath$1.apply(ExceptionTranslatingQueryContext.scala:275)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext$$anonfun$singleShortestPath$1.apply(ExceptionTranslatingQueryContext.scala:275)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:33)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:41)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext.singleShortestPath(ExceptionTranslatingQueryContext.scala:275)
	at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.ShortestPathExpression.getMatches(ShortestPathExpression.scala:69)
	at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.ShortestPathExpression.apply(ShortestPathExpression.scala:55)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.ShortestPathPipe$$anonfun$internalCreateResults$1.apply(ShortestPathPipe.scala:48)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.ShortestPathPipe$$anonfun$internalCreateResults$1.apply(ShortestPathPipe.scala:47)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$class.isEmpty(Iterator.scala:331)
	at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1334)
	at org.neo4j.cypher.internal.runtime.slotted.pipes.OptionalSlottedPipe.internalCreateResults(OptionalSlottedPipe.scala:49)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:76)
	at org.neo4j.cypher.internal.runtime.slotted.pipes.ApplySlottedPipe$$anonfun$internalCreateResults$1.apply(ApplySlottedPipe.scala:19)
	at org.neo4j.cypher.internal.runtime.slotted.pipes.ApplySlottedPipe$$anonfun$internalCreateResults$1.apply(ApplySlottedPipe.scala:17)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at org.neo4j.cypher.internal.runtime.slotted.pipes.EagerAggregationSlottedPipe.internalCreateResults(EagerAggregationSlottedPipe.scala:130)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:76)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:72)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:72)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:72)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:72)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:72)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:72)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:72)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:72)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:72)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:72)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.BaseExecutionResultBuilderFactory$BaseExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:61)
	at org.neo4j.cypher.internal.compatibility.InterpretedRuntime$InterpretedExecutionPlan.run(InterpretedRuntime.scala:84)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$3.apply(CypherCurrentCompiler.scala:205)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$3.apply(CypherCurrentCompiler.scala:190)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery.execute(CypherCurrentCompiler.scala:224)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:101)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:85)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachineV1SPI$BoltResultHandleV1.start(TransactionStateMachineV1SPI.java:189)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.startExecution(TransactionStateMachine.java:506)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.execute(TransactionStateMachine.java:300)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:269)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:110)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:98)
	at org.neo4j.bolt.v1.runtime.ReadyState.processRunMessage(ReadyState.java:140)
	at org.neo4j.bolt.v1.runtime.ReadyState.processRunMessage(ReadyState.java:100)
	at org.neo4j.bolt.v1.runtime.ReadyState.process(ReadyState.java:61)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
	at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.lambda$enqueue$0(MetricsReportingBoltConnection.java:68)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
	at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.processNextBatch(MetricsReportingBoltConnection.java:86)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Database 2:**

Delete query-
```
MATCH (n),(m)
WITH n,m
MATCH (n) DETACH DELETE n
```

Read query-
```
MATCH (n),(m)
WITH n,m
MATCH (n)-[r]-()
OPTIONAL MATCH (m)--()
RETURN n.id, type(r),m.id
```

Failure message:

```
2020-01-22 06:57:17.635+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: Kernel API returned non-existent relationship type: -1, reference 6257d614-1d9f-4619-ac52-04c396c5a160. Kernel API returned non-existent relationship type: -1
java.lang.IllegalStateException: Kernel API returned non-existent relationship type: -1
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.getRelationshipTypeById(GraphDatabaseFacade.java:991)
	at org.neo4j.kernel.impl.core.RelationshipProxy.getType(RelationshipProxy.java:222)
	at org.neo4j.kernel.impl.util.RelationshipProxyWrappingValue.type(RelationshipProxyWrappingValue.java:157)
	at org.neo4j.cypher.operations.CypherFunctions.type(CypherFunctions.java:743)
	at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.RelationshipTypeFunction.compute(RelationshipTypeFunction.scala:30)
	at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.NullInNullOutExpression.apply(NullInNullOutExpression.scala:32)
	at org.neo4j.cypher.internal.runtime.slotted.expressions.SlottedCommandProjection$$anonfun$1$$anonfun$apply$1.apply(SlottedCommandProjection.scala:21)
	at org.neo4j.cypher.internal.runtime.slotted.expressions.SlottedCommandProjection$$anonfun$1$$anonfun$apply$1.apply(SlottedCommandProjection.scala:20)
	at org.neo4j.cypher.internal.runtime.slotted.expressions.SlottedCommandProjection$$anonfun$project$1.apply(SlottedCommandProjection.scala:25)
	at org.neo4j.cypher.internal.runtime.slotted.expressions.SlottedCommandProjection$$anonfun$project$1.apply(SlottedCommandProjection.scala:25)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.neo4j.cypher.internal.runtime.slotted.expressions.SlottedCommandProjection.project(SlottedCommandProjection.scala:25)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProjectionPipe$$anonfun$internalCreateResults$1.apply(ProjectionPipe.scala:38)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProjectionPipe$$anonfun$internalCreateResults$1.apply(ProjectionPipe.scala:37)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at org.neo4j.cypher.internal.runtime.RuntimeJavaValueConverter$feedQueryResultRecordIteratorToVisitable.accept(RuntimeJavaValueConverter.scala:64)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.PipeExecutionResult.accept(PipeExecutionResult.scala:74)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.StandardInternalExecutionResult.accept(StandardInternalExecutionResult.scala:192)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply$mcV$sp(ClosingExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$safelyAndClose$1.apply(ClosingExecutionResult.scala:171)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.safelyAndClose(ClosingExecutionResult.scala:174)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.accept(ClosingExecutionResult.scala:157)
	at org.neo4j.bolt.v1.runtime.CypherAdapterStream.accept(CypherAdapterStream.java:73)
	at org.neo4j.bolt.v1.messaging.ResultHandler.onRecords(ResultHandler.java:40)
	at org.neo4j.bolt.v3.runtime.StreamingState.lambda$processStreamResultMessage$0(StreamingState.java:41)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.consumeResult(TransactionStateMachine.java:484)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:328)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:128)
	at org.neo4j.bolt.v3.runtime.StreamingState.processStreamResultMessage(StreamingState.java:40)
	at org.neo4j.bolt.v3.runtime.AbstractStreamingState.processUnsafe(AbstractStreamingState.java:44)
	at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
	at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.lambda$enqueue$0(MetricsReportingBoltConnection.java:68)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
	at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.processNextBatch(MetricsReportingBoltConnection.java:86)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

**Comment by MishaDemianenko** [comment]
Hi, @luanne thx for your report. 
So far described behavior looks quite similar to https://github.com/neo4j/neo4j/issues/12250  Linked issue comes with explanations and describes a way how query execution engine can be configured to execute queries in a snapshot mode.

**Comment by luanne** [comment]
Thanks @MishaDemianenko, I'll try that. It is unfortunate though that this occurs within the boundary of a single Cypher query, and is quite unexpected that the internal detail of MATCH and RETURN being separate reads surface.
