### ISSUE TITLE
Failed to locally commit a transaction that has already been committed to the RAFT log. This server cannot process later transactions and needs to be restarted once the underlying cause has been addressed.

### ISSUE THREAD

**Issue by jsoref** [neo4j/neo4j#12415]
- Neo4j version: 3.5.12
- Operating system: debian
- API/Driver: Cypher/Java API

### Steps to reproduce
Running neo4j in a kubernetes cluster w/ 3 core servers and one read replica
Beyond this, I don't know.

### Expected behavior
1. Don't crash
2. Make it clear what to expect in which log file.

### Actual behavior
[debug.log](https://github.com/neo4j/neo4j/files/4278562/neo4j.debug.log)

```java
2020-03-02 11:11:51.062+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.Transaction.TransactionStartFailed]: The database has encountered a critical error, and needs to be restarted. Please see database logs for more details., reference 796e39ea-6319-4f2e-b9d6-18ad064e40de.
2020-03-02 11:11:51.062+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.Transaction.TransactionStartFailed]: The database has encountered a critical error, and needs to be restarted. Please see database logs for more details., reference 796e39ea-6319-4f2e-b9d6-18ad064e40de. The database has encountered a critical error, and needs to be restarted. Please see database logs for more details.
        at org.neo4j.graphdb.facade.spi.ClassicCoreSPI.beginTransaction(ClassicCoreSPI.java:193)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransactionInternal(GraphDatabaseFacade.java:691)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransaction(GraphDatabaseFacade.java:375)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachineV1SPI.beginTransaction(TransactionStateMachineV1SPI.java:139)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachineV1SPI.beginTransaction(TransactionStateMachineV1SPI.java:98)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.execute(TransactionStateMachine.java:293)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:269)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:110)
        at org.neo4j.bolt.v3.runtime.ReadyState.processRunMessage(ReadyState.java:85)
        at org.neo4j.bolt.v3.runtime.ReadyState.processUnsafe(ReadyState.java:56)
        at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
        at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
        at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
        at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
        at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.lambda$enqueue$0(MetricsReportingBoltConnection.java:68)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
        at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.processNextBatch(MetricsReportingBoltConnection.java:86)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.internal.kernel.api.exceptions.TransactionFailureException: The database has encountered a critical error, and needs to be restarted. Please see database logs for more details.
        at sun.reflect.GeneratedConstructorAccessor60.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.neo4j.kernel.internal.DatabaseHealth.assertHealthy(DatabaseHealth.java:61)
        at org.neo4j.kernel.impl.api.KernelImpl.beginTransaction(KernelImpl.java:88)
        at org.neo4j.graphdb.facade.spi.ClassicCoreSPI.beginTransaction(ClassicCoreSPI.java:186)
        ... 23 more
Caused by: java.lang.IllegalStateException: Failed to locally commit a transaction that has already been committed to the RAFT log. This server cannot process later transactions and needs to be restarted once the underlying cause has been addressed.
        at org.neo4j.causalclustering.core.state.machines.tx.ReplicatedTransactionStateMachine.panicException(ReplicatedTransactionStateMachine.java:165)
        at org.neo4j.causalclustering.core.state.machines.tx.ReplicatedTransactionStateMachine.ensuredApplied(ReplicatedTransactionStateMachine.java:159)
        at org.neo4j.causalclustering.core.state.machines.CoreStateMachines$StateMachineCommandDispatcher.close(CoreStateMachines.java:200)
        at org.neo4j.causalclustering.core.state.CommandApplicationProcess.handleOperations(CommandApplicationProcess.java:256)
        at org.neo4j.causalclustering.core.state.CommandApplicationProcess.applyBatch(CommandApplicationProcess.java:229)
        at org.neo4j.causalclustering.core.state.CommandBatcher.flush(CommandBatcher.java:60)
        at org.neo4j.causalclustering.core.state.CommandApplicationProcess.applyUpTo(CommandApplicationProcess.java:194)
        at org.neo4j.causalclustering.core.state.CommandApplicationProcess.applyJob(CommandApplicationProcess.java:157)
        ... 1 more
Caused by: java.lang.IllegalStateException: Out of order transaction. Expected that 471 < 221
        at org.neo4j.causalclustering.core.state.machines.tx.ReplicatedTransactionStateMachine.lambda$applyCommand$1(ReplicatedTransactionStateMachine.java:119)
        at org.neo4j.kernel.impl.api.TransactionToApply.close(TransactionToApply.java:172)
        at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.close(TransactionRepresentationCommitProcess.java:95)
        at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:56)
        at org.neo4j.causalclustering.core.state.machines.tx.ReplicatedTransactionStateMachine.lambda$installCommitProcess$0(ReplicatedTransactionStateMachine.java:81)
        at org.neo4j.kernel.impl.api.TransactionQueue.empty(TransactionQueue.java:68)
        at org.neo4j.causalclustering.core.state.machines.tx.ReplicatedTransactionStateMachine.ensuredApplied(ReplicatedTransactionStateMachine.java:155)
        ... 7 more
...
```

I suspect that the first line is expected to be a hint to look at the second line, but I'm not really sure. I checked the entire file system and these two instances were the only ones for the reference.

**Comment by RagnarW** [comment]
Closing due to unsupported version
