### ISSUE TITLE
Query returns org.neo4j.cypher.internal.physicalplanning.ast.NullCheckReference 

### ISSUE THREAD

**Issue by conker84** [neo4j/neo4j#12440]
In the Neo4j Spark Connector we have the following query in order to generate a test dataset that always worked:

```
UNWIND range(1,100) as id
CREATE (p:Person {id:id,ids:[id,id]})
WITH collect(p) as people
UNWIND people as p1
UNWIND range(1,10) as friend
WITH p1, people[(p1.id + friend) % size(people)] as p2
CREATE (p1)-[:KNOWS]->(p2)
```

https://github.com/neo4j-contrib/neo4j-spark-connector/blob/0ace7dbf8a7bf8c43800dca3fc6587d7cb9b914c/src/test/scala/org/neo4j/spark/Neo4jSparkTest.scala#L18-L26

**Neo4j Version:** 4.0.2
**Operating System:** Mac OS Catalina, but I used Docker Image `neo4j:enterprise`
**API:** Docker Image `neo4j:enterprise`

### Expected behavior
Generate a dataset according to the query

### Actual behavior
In the Neo4j browser I get the following error:

<img width="1257" alt="Schermata 2020-03-30 alle 11 04 38" src="https://user-images.githubusercontent.com/1833335/77894931-48b8cf00-7276-11ea-8e73-80740ceb32d0.png">

That is consistent with the exception thrown by the java Driver:

```
org.neo4j.driver.exceptions.DatabaseException: org.neo4j.cypher.internal.physicalplanning.ast.NullCheckReference
	at org.neo4j.driver.internal.util.ErrorUtil.newNeo4jError(ErrorUtil.java:84)
	at org.neo4j.driver.internal.async.inbound.InboundMessageDispatcher.handleFailureMessage(InboundMessageDispatcher.java:105)
	at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.unpackFailureMessage(MessageReaderV1.java:83)
	at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.read(MessageReaderV1.java:59)
	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:83)
	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:35)
	at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:47)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:308)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:422)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sherfert** [comment]
Thanks @conker84 
We will look into the problem!

**Comment by sherfert** [comment]
We merged a fix, which will be included in the upcoming 4.0.4 release.

**Comment by conker84** [comment]
@sherfert thanks!

**Comment by rlytleatrel8edto** [comment]
Is there a release date planned for this?  It's fairly significant in scope, failing some pretty simple aggregations after our upgrade to the 4.0 platform.

**Comment by sherfert** [comment]
@rlytleatrel8edto The 4.0.4 release is gonna come sometime next week or the week after. Ill report here again once it is published.

**Comment by nikosantis** [comment]
same error with:

`
const cypher = `
            MATCH (user:User {id: $user.id})
            MATCH (company:Company {id: $company.id})
            CREATE (form:Form)
            MERGE (user)-[:CREATED_A]->(form)
            MERGE (company)-[:HAS_FORM]->(form)
            SET form += $args
            SET form.id = randomUUID()
            SET form.haveCampaign = false
            SET form.createdAt = toString(datetime())
            SET form.updatedAt = toString(datetime())
            WITH $sectionArray AS data
            UNWIND data AS section
            CREATE (sec:FormSection)
            MERGE (form)-[:HAS_SECTION]->(section)
            SET sec.id = randomUUID()
            SET sec.name = section.name
            SET sec.description = section.description
            RETURN form {.*}
          `
`

**Comment by sherfert** [comment]
@rlytleatrel8edto @nikosantis 
[Neo4j 4.0.4](https://neo4j.com/download-center/) has been released. Could you please verify that your bug is fixed in this version?

**Comment by nikosantis** [comment]
@sherfert we are updating our enterprise
Thanks!!!
