### ISSUE TITLE
Failed to receive any data from the connected address

### ISSUE THREAD

**Issue by SantaFlang** [neo4j/neo4j#12460]
I developed an app with using neo4j service at Linux server. And I can normally use browser to access the service. But I discovered that when use java driver in Android app, it throws the error ServiceUnavailableException: Failed to receive any data from the connected address...... I have tried the Windows Neo4j 4.0.1 edition and Linux 4.0.3, 3.5.17edition. They were all reported the same error.

**Neo4j Version:** 3.5.17
**Operating System:** CentOS 7
**API:** Java neo4j driver 1.4.4

### Steps to reproduce
1. Connect to Neo4j: use GraphDatabase.driver("bolt://myaddress:7687", AuthTokens.basic("neo4j","mypassword"));

### Expected behavior
Connection should be done and used normally.

### Actual behavior
Failed to receive any data from the connected address.

## Here is the error
org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Failed to receive any data from the connected address m.y.addre.ss:7687. Please ensure a working connection to the database.        at org.neo4j.driver.internal.security.TLSSocketChannel.channelRead(TLSSocketChannel.java:176)        at org.neo4j.driver.internal.security.TLSSocketChannel.unwrap(TLSSocketChannel.java:235)        at org.neo4j.driver.internal.security.TLSSocketChannel.read(TLSSocketChannel.java:429)        at org.neo4j.driver.internal.net.SocketClient.blockingRead(SocketClient.java:77)        at org.neo4j.driver.internal.net.SocketClient.negotiateProtocol(SocketClient.java:251)        at org.neo4j.driver.internal.net.SocketClient.start(SocketClient.java:128)        at org.neo4j.driver.internal.net.SocketConnection.startSocketClient(SocketConnection.java:92)        at org.neo4j.driver.internal.net.SocketConnection.<init>(SocketConnection.java:67)        at org.neo4j.driver.internal.net.SocketConnector.createConnection(SocketConnector.java:77)        at org.neo4j.driver.internal.net.SocketConnector.connect(SocketConnector.java:50)        at org.neo4j.driver.internal.net.pooling.SocketConnectionPool$ConnectionSupplier.get(SocketConnectionPool.java:216)        at org.neo4j.driver.internal.net.pooling.SocketConnectionPool$ConnectionSupplier.get(SocketConnectionPool.java:198)        at org.neo4j.driver.internal.net.pooling.BlockingPooledConnectionQueue.acquire(BlockingPooledConnectionQueue.java:96)        at org.neo4j.driver.internal.net.pooling.SocketConnectionPool.acquireConnection(SocketConnectionPool.java:149)        at org.neo4j.driver.internal.net.pooling.SocketConnectionPool.acquire(SocketConnectionPool.java:76)        at org.neo4j.driver.internal.DirectConnectionProvider.acquireConnection(DirectConnectionProvider.java:47)        at org.neo4j.driver.internal.DirectConnectionProvider.verifyConnectivity(DirectConnectionProvider.java:67)        at org.neo4j.driver.internal.DirectConnectionProvider.<init>(DirectConnectionProvider.java:41)        at org.neo4j.driver.internal.DriverFactory.createDirectDriver(DriverFactory.java:109)        at org.neo4j.driver.internal.DriverFactory.createDriver(DriverFactory.java:93)        at org.neo4j.driver.internal.DriverFactory.newInstance(DriverFactory.java:67)        at org.neo4j.driver.v1.GraphDatabase.driver(GraphDatabase.java:135)        at org.neo4j.driver.v1.GraphDatabase.driver(GraphDatabase.java:117)        at org.neo4j.driver.v1.GraphDatabase.driver(GraphDatabase.java:92)        at com.stfalcon.chatkit.sample.common.data.fixtures.MessagesFixtures.queryNeo4j(MessagesFixtures.java:134)        at com.stfalcon.chatkit.sample.common.data.fixtures.MessagesFixtures.access$000(MessagesFixtures.java:23)        at com.stfalcon.chatkit.sample.common.data.fixtures.MessagesFixtures$1.run(MessagesFixtures.java:66)        at java.lang.Thread.run(Thread.java:929)

**Comment by SantaFlang** [comment]
Well, it seems like no one would reply me...And finally, by accident, I changed one line in neo4j.conf, dbms.connectors.default_advertised_address = My server's IP address. The connection turned into  perfect. By the way, the default setting is localhost, and you can't use browser to visit Neo4j database remotely. Then when I have changed it into 0.0.0.0, the browser worked well, but bolt connection was failed. I have no idea about this puzzle, maybe I should check the documentation. Just mark down to remind the others.

**Comment by SantaFlang** [comment]
Well, I have solved my problem by using org.neo4j.driver:neo4j-java-driver:1.6.0. I have tried 1.0.5, 1.4.4, 1.5.0, 1.6.1, 1.7.2, 4.0.0 and 4.0.1. Maybe there are limits between the different version. Hope someone can figure this out.

**Comment by sherfert** [comment]
Hi @SantaFlang .
You can find the Java driver compatibility matrix here: https://github.com/neo4j/neo4j-java-driver/wiki

With your Neo4j Version 3.5.17 I would expect it to work _at least_ with Driver 4.0 and 1.7.
Can you confirm that this works?

**Comment by SantaFlang** [comment]
@sherfert Thank you for your advice. 
I have tried Driver 1.7.0 and 4.0.0. The good news is 1.7.0 can work perfectly. However, 4.0.0 can't even build successfully, and it throws the error: neo4j Library source does not match the bytecode for class HandshakeHandler. And when I check I find I can't import io.netty.buffer.ByteBuf, maybe Neo4j Version 3.5.17 doesn't match the Driver 4.0.

**Comment by zhenlineo** [comment]
@SantaFlang It looks like your original problem has already been resolved. But however you are seeing a new error when using java-driver 4.0.0 driver with Neo4j 3.5.17. Could you restate your problem following the issue template such as versions, steps to reproduce, expected behaviour?

**Comment by gjmwoods** [comment]
@SantaFlang Closing this due to inactivity. Please reopen (with the necessary details) if we can help further.
