### ISSUE TITLE
[4.x] Cannot create database with test harness

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j#12506]
## Guidelines

- Neo4j version: 4.0.4
- Operating system: Mac OS
- API/Driver: Test harness

### Steps to reproduce

1. Clone https://github.com/fbiville/neo4j-harness-multi-db
2. Run the test with `mvn test`.

### Expected behavior
I expect a database to be created and the test to pass.

### Actual behavior
The test fails with the following error:
```java
org.neo4j.dbms.api.DatabaseManagementException: org.neo4j.graphdb.QueryExecutionException: Unsupported administration command: CREATE DATABASE `extra`

	at org.neo4j.dbms.database.DatabaseManagementServiceImpl.systemDatabaseExecute(DatabaseManagementServiceImpl.java:154)
	at org.neo4j.dbms.database.DatabaseManagementServiceImpl.createDatabase(DatabaseManagementServiceImpl.java:72)
	at com.acme.MultiDatabaseTest.creates_extra_db(MultiDatabaseTest.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.neo4j.harness.junit.rule.Neo4jRule$1.evaluate(Neo4jRule.java:89)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: org.neo4j.graphdb.QueryExecutionException: Unsupported administration command: CREATE DATABASE `extra`
	at org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(QueryExecutionKernelException.java:35)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:236)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:217)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:211)
	at org.neo4j.dbms.database.DatabaseManagementServiceImpl.systemDatabaseExecute(DatabaseManagementServiceImpl.java:148)
	... 27 more
Caused by: org.neo4j.kernel.impl.query.QueryExecutionKernelException: Unsupported administration command: CREATE DATABASE `extra`
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:125)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:110)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:228)
	... 30 more
Caused by: org.neo4j.exceptions.DatabaseAdministrationException: Unsupported administration command: CREATE DATABASE `extra`
	at org.neo4j.cypher.internal.logical.plans.DatabaseAdministrationLogicalPlan.invalid(MultiDatabaseLogicalPlan.scala:42)
	at org.neo4j.cypher.internal.logical.plans.DatabaseAdministrationLogicalPlan.invalid(MultiDatabaseLogicalPlan.scala:41)
	at org.neo4j.cypher.internal.planning.CypherPlanner.createPlan$1(CypherPlanner.scala:267)
	at org.neo4j.cypher.internal.planning.CypherPlanner.$anonfun$doPlan$6(CypherPlanner.scala:294)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:186)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:128)
	at org.neo4j.cypher.internal.planning.CypherPlanner.doPlan(CypherPlanner.scala:296)
	at org.neo4j.cypher.internal.planning.CypherPlanner.parseAndPlan(CypherPlanner.scala:177)
	at org.neo4j.cypher.internal.CypherCurrentCompiler.compile(CypherCurrentCompiler.scala:112)
	at org.neo4j.cypher.internal.MasterCompiler.compile(MasterCompiler.scala:89)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$compilers$2(ExecutionEngine.scala:245)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:186)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:128)
	at org.neo4j.cypher.internal.ExecutionEngine.getOrCompile(ExecutionEngine.scala:280)
	at org.neo4j.cypher.internal.ExecutionEngine.parseAndCompile$1(ExecutionEngine.scala:212)
	at org.neo4j.cypher.internal.ExecutionEngine.doExecute(ExecutionEngine.scala:229)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$executeSubQuery$1(ExecutionEngine.scala:190)
	at org.neo4j.cypher.internal.ExecutionEngine.closing(ExecutionEngine.scala:195)
	at org.neo4j.cypher.internal.ExecutionEngine.executeSubQuery(ExecutionEngine.scala:188)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:139)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:121)
	... 32 more


org.neo4j.dbms.api.DatabaseManagementException: org.neo4j.graphdb.QueryExecutionException: Unsupported administration command: DROP DATABASE `extra`

	at org.neo4j.dbms.database.DatabaseManagementServiceImpl.systemDatabaseExecute(DatabaseManagementServiceImpl.java:154)
	at org.neo4j.dbms.database.DatabaseManagementServiceImpl.dropDatabase(DatabaseManagementServiceImpl.java:78)
	at com.acme.MultiDatabaseTest.deletes_extra_db(MultiDatabaseTest.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.neo4j.harness.junit.rule.Neo4jRule$1.evaluate(Neo4jRule.java:89)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: org.neo4j.graphdb.QueryExecutionException: Unsupported administration command: DROP DATABASE `extra`
	at org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(QueryExecutionKernelException.java:35)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:236)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:217)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:211)
	at org.neo4j.dbms.database.DatabaseManagementServiceImpl.systemDatabaseExecute(DatabaseManagementServiceImpl.java:148)
	... 26 more
Caused by: org.neo4j.kernel.impl.query.QueryExecutionKernelException: Unsupported administration command: DROP DATABASE `extra`
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:125)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:110)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:228)
	... 29 more
Caused by: org.neo4j.exceptions.DatabaseAdministrationException: Unsupported administration command: DROP DATABASE `extra`
	at org.neo4j.cypher.internal.logical.plans.DatabaseAdministrationLogicalPlan.invalid(MultiDatabaseLogicalPlan.scala:42)
	at org.neo4j.cypher.internal.logical.plans.DatabaseAdministrationLogicalPlan.invalid(MultiDatabaseLogicalPlan.scala:41)
	at org.neo4j.cypher.internal.planning.CypherPlanner.createPlan$1(CypherPlanner.scala:267)
	at org.neo4j.cypher.internal.planning.CypherPlanner.$anonfun$doPlan$6(CypherPlanner.scala:294)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:186)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:128)
	at org.neo4j.cypher.internal.planning.CypherPlanner.doPlan(CypherPlanner.scala:296)
	at org.neo4j.cypher.internal.planning.CypherPlanner.parseAndPlan(CypherPlanner.scala:177)
	at org.neo4j.cypher.internal.CypherCurrentCompiler.compile(CypherCurrentCompiler.scala:112)
	at org.neo4j.cypher.internal.MasterCompiler.compile(MasterCompiler.scala:89)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$compilers$2(ExecutionEngine.scala:245)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:186)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:128)
	at org.neo4j.cypher.internal.ExecutionEngine.getOrCompile(ExecutionEngine.scala:280)
	at org.neo4j.cypher.internal.ExecutionEngine.parseAndCompile$1(ExecutionEngine.scala:212)
	at org.neo4j.cypher.internal.ExecutionEngine.doExecute(ExecutionEngine.scala:229)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$executeSubQuery$1(ExecutionEngine.scala:190)
	at org.neo4j.cypher.internal.ExecutionEngine.closing(ExecutionEngine.scala:195)
	at org.neo4j.cypher.internal.ExecutionEngine.executeSubQuery(ExecutionEngine.scala:188)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:139)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:121)
	... 31 more
```

**Comment by fbiville** [comment]
Silly me, multi-database is an enterprise-only feature.
