### ISSUE TITLE
Unable to build on Mac OS

### ISSUE THREAD

**Issue by xxks-kkk** [neo4j/neo4j#12516]
I try to build neo4j with branch `4.1` with commit ID: b6c5ce3699705b62f2813f321de666b0bda55b24 on Mac OS 10.14.6 with following Java version

```
$ java --version
java 11.0.7 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
```

and Maven version

```
$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.7, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.7.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```

I run the command `mvn clean install -T 8` and obtain the following error:

```
[ERROR] Failed to execute goal org.neo4j:scalastyle-maven-plugin:1.1.1:check (default) on project parent: Execution default of goal org.neo4j:scalastyle-maven-plugin:1.1.1:check failed: A required class was missing while executing org.neo4j:scalastyle-maven-plugin:1.1.1:check: org/codehaus/plexus/util/FileUtils
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.neo4j:scalastyle-maven-plugin:1.1.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/zeyuanhu/.m2/repository/org/neo4j/scalastyle-maven-plugin/1.1.1/scalastyle-maven-plugin-1.1.1.jar
[ERROR] urls[1] = file:/Users/zeyuanhu/.m2/repository/org/scalastyle/scalastyle-maven-plugin/1.0.0/scalastyle-maven-plugin-1.0.0.jar
[ERROR] urls[2] = file:/Users/zeyuanhu/.m2/repository/org/scalastyle/scalastyle_2.11/1.0.0/scalastyle_2.11-1.0.0.jar
[ERROR] urls[3] = file:/Users/zeyuanhu/Documents/neo4j/build-resources/target/build-resources-4.1.0-SNAPSHOT.jar
[ERROR] urls[4] = file:/Users/zeyuanhu/.m2/repository/org/neo4j/scalastyle_2.11/1.1.1/scalastyle_2.11-1.1.1.jar
[ERROR] urls[5] = file:/Users/zeyuanhu/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar
[ERROR] urls[6] = file:/Users/zeyuanhu/.m2/repository/org/scalariform/scalariform_2.11/0.2.7/scalariform_2.11-0.2.7.jar
[ERROR] urls[7] = file:/Users/zeyuanhu/.m2/repository/org/scala-lang/modules/scala-xml_2.11/1.1.1/scala-xml_2.11-1.1.1.jar
[ERROR] urls[8] = file:/Users/zeyuanhu/.m2/repository/org/scala-lang/modules/scala-parser-combinators_2.11/1.1.1/scala-parser-combinators_2.11-1.1.1.jar
[ERROR] urls[9] = file:/Users/zeyuanhu/.m2/repository/com/typesafe/config/1.2.0/config-1.2.0.jar
[ERROR] urls[10] = file:/Users/zeyuanhu/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.4/plexus-component-annotations-1.5.4.jar
[ERROR] urls[11] = file:/Users/zeyuanhu/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[ERROR] urls[12] = file:/Users/zeyuanhu/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
[ERROR] urls[13] = file:/Users/zeyuanhu/.m2/repository/org/codehaus/plexus/plexus-resources/1.0-alpha-7/plexus-resources-1.0-alpha-7.jar
[ERROR] urls[14] = file:/Users/zeyuanhu/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.5/plexus-utils-1.5.5.jar
[ERROR] urls[15] = file:/Users/zeyuanhu/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : org.codehaus.plexus.util.FileUtils
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :parent
```

Do you know what might be the issue here? Thanks!

### Steps to reproduce
See above

### Expected behavior
Build pass

### Actual behavior
Build fail

**Comment by xxks-kkk** [comment]
If I update `pom.xml` like following:

```
$ git diff pom.xml
diff --git a/pom.xml b/pom.xml
index 0b9bf102fc9..207ce30a8aa 100644
--- a/pom.xml
+++ b/pom.xml
@@ -129,7 +129,7 @@
        <amazon-sdk.version>1.11.524</amazon-sdk.version>
     <guava.version>29.0-jre</guava.version>
     <awaitility.version>4.0.2</awaitility.version>
-    <skip-scalastyle>false</skip-scalastyle>
+    <skip-scalastyle>true</skip-scalastyle>
   </properties>

   <modules>
@@ -649,7 +649,7 @@
           <artifactId>maven-assembly-plugin</artifactId>
           <version>3.3.0</version>
           <configuration>
-            <tarLongFileMode>gnu</tarLongFileMode>
+            <tarLongFileMode>posix</tarLongFileMode>
           </configuration>
         </plugin>
         <plugin>
```

Then, I hit the error with `mvn clean install -T 8`

```
neo4j-home/bin/neo4j: line 333: JAVA_OPTS[@]: unbound variable
not ok 4 - should include --version in java args when --version given
#
#	  neo4j-home/bin/neo4j --version && test_expect_java_arg '--version'
#

expecting success:
  neo4j-home/bin/neo4j version && test_expect_java_arg '--version'

neo4j-home/bin/neo4j: line 333: JAVA_OPTS[@]: unbound variable
not ok 5 - should include --version in java args when version given
#
#	  neo4j-home/bin/neo4j version && test_expect_java_arg '--version'
#

# failed 2 among 5 test(s)
1..5
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
<- snip ->

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12:12 min (Wall Clock)
[INFO] Finished at: 2020-05-30T21:12:04-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (shell-script-tests) on project neo4j-standalone: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :neo4j-standalone
```

**Comment by xxks-kkk** [comment]
I disable tests in `/packaging/standalone/src/tests/shell-scripts/run-tests.sh` and
`/packaging/standalone/src/tests/shell-scripts/test-config.sh` 

and it takes roughly takes 12 hours to finish the build (also there is a failure) with MacOS of the following specification

```
  Model Name:                 MacBook Pro
  Model Identifier:           MacBookPro15,2
  Processor Name:             Intel Core i7
  Processor Speed:            2.8 GHz
  Number of Processors:       1
  Total Number of Cores:      4
  L2 Cache (per Core):        256 KB
  L3 Cache:                   8 MB
  Hyper-Threading Technology: Enabled
  Memory:                     16 GB
```

```
[INFO] Neo4j - Build resources ............................ SUCCESS [  1.414 s]
[INFO] Neo4j .............................................. SUCCESS [  9.432 s]
[INFO] Neo4j - Annotation processors ...................... SUCCESS [ 17.835 s]
[INFO] Zstandard .......................................... SUCCESS [  3.135 s]
[INFO] Neo4j - Common ..................................... SUCCESS [ 17.367 s]
[INFO] Neo4j - Unsafe Access .............................. SUCCESS [  4.957 s]
[INFO] Neo4j - Native ..................................... SUCCESS [  5.147 s]
[INFO] Neo4j - Concurrent ................................. SUCCESS [ 33.729 s]
[INFO] Neo4j - IO ......................................... SUCCESS [ 10.536 s]
[INFO] Neo4j - Token API .................................. SUCCESS [ 11.838 s]
[INFO] Neo4j - Locking .................................... SUCCESS [  4.151 s]
[INFO] Neo4j - Resource interface ......................... SUCCESS [  0.777 s]
[INFO] Neo4j - Collections ................................ SUCCESS [ 14.958 s]
[INFO] Neo4j - Graph Database API ......................... SUCCESS [  5.033 s]
[INFO] Neo4j - Exceptions ................................. SUCCESS [  4.688 s]
[INFO] Neo4j - Value ...................................... SUCCESS [ 28.158 s]
[INFO] Neo4j - Testing Utils Parent ....................... SUCCESS [  0.542 s]
[INFO] Neo4j - Test utilities ............................. SUCCESS [ 12.418 s]
[INFO] Neo4j - Random Value ............................... SUCCESS [ 15.234 s]
[INFO] Neo4j - Schema ..................................... SUCCESS [ 20.097 s]
[INFO] Neo4j - Test IO utilities .......................... SUCCESS [ 18.265 s]
[INFO] Neo4j - Logging .................................... SUCCESS [01:22 min]
[INFO] Neo4j - Test logging utilities ..................... SUCCESS [  0.350 s]
[INFO] Neo4j - Configuration .............................. SUCCESS [ 10.061 s]
[INFO] Neo4j - Layout ..................................... SUCCESS [  0.353 s]
[INFO] Neo4j - Diagnostics ................................ SUCCESS [  0.323 s]
[INFO] Neo4j - Native index ............................... SUCCESS [05:38 min]
[INFO] Neo4j - ID Generator ............................... SUCCESS [ 15.957 s]
[INFO] Neo4j - Monitoring ................................. SUCCESS [ 10.004 s]
[INFO] Neo4j - Storage Engine API ......................... SUCCESS [  2.262 s]
[INFO] Neo4j - CSV reading and parsing .................... SUCCESS [ 18.667 s]
[INFO] Neo4j - Import Utilities ........................... SUCCESS [01:08 min]
[INFO] Neo4j - Procedure API .............................. SUCCESS [  0.782 s]
[INFO] Neo4j - Kernel API ................................. SUCCESS [  8.379 s]
[INFO] Neo4j - Database Layout API utilities .............. SUCCESS [  5.102 s]
[INFO] Neo4j - Label index ................................ SUCCESS [ 37.311 s]
[INFO] Neo4j - Storage Engine Test Utilities .............. SUCCESS [  0.178 s]
[INFO] Neo4j - Write-Ahead Log ............................ SUCCESS [  6.001 s]
[INFO] Neo4j - Test Batch Import utilities ................ SUCCESS [  0.219 s]
[INFO] Neo4j - Record storage engine ...................... SUCCESS [02:33 min]
[INFO] Neo4j - Native Spatial Index ....................... SUCCESS [03:10 min]
[INFO] Neo4j - Lucene Index ............................... SUCCESS [02:02 min]
[INFO] Neo4j - Fulltext index ............................. SUCCESS [  6.023 s]
[INFO] Neo4j - Test kernel API utilities .................. SUCCESS [  0.536 s]
[INFO] Neo4j - Write-Ahead Logging Test Utilities ......... SUCCESS [  0.495 s]
[INFO] Neo4j - Graph Database Kernel ...................... SUCCESS [01:27 min]
[INFO] Neo4j - Code Generator ............................. SUCCESS [01:19 min]
[INFO] Neo4j - Community Cypher Build ..................... SUCCESS [  3.284 s]
[INFO] openCypher Front End Parent ........................ SUCCESS [  1.293 s]
[INFO] openCypher Utils ................................... SUCCESS [ 14.630 s]
[INFO] Neo4j - Graph Algorithms ........................... SUCCESS [  9.952 s]
[INFO] openCypher Expressions ............................. SUCCESS [ 11.526 s]
[INFO] openCypher AST for the Cypher Query Language ....... SUCCESS [ 26.287 s]
[INFO] openCypher Parser .................................. SUCCESS [02:36 min]
[INFO] openCypher Rewriting ............................... SUCCESS [ 21.419 s]
[INFO] Neo4j - Cypher Macros .............................. SUCCESS [ 11.383 s]
[INFO] openCypher Front End ............................... SUCCESS [01:03 min]
[INFO] Neo4j - Cypher Intermediate Representation ......... SUCCESS [ 12.954 s]
[INFO] Neo4j - Cypher Logical Plans ....................... SUCCESS [ 17.257 s]
[INFO] Neo4j - Cypher Planner SPI ......................... SUCCESS [  0.777 s]
[INFO] Neo4j - Cypher Runtime Utilities ................... SUCCESS [ 37.747 s]
[INFO] Neo4j - Cypher Interpreted Runtime ................. SUCCESS [01:12 min]
[INFO] Neo4j - Cypher Expression Evaluator ................ SUCCESS [  3.939 s]
[INFO] Neo4j - Cypher Logical Plan Builder ................ SUCCESS [01:25 min]
[INFO] Neo4j - Cypher Planner ............................. SUCCESS [01:19 min]
[INFO] Neo4j - Cypher ..................................... SUCCESS [ 38.902 s]
[INFO] Neo4j - SSL ........................................ SUCCESS [ 13.027 s]
[INFO] Neo4j - Command Line ............................... SUCCESS [  0.721 s]
[INFO] Neo4j - Database Management System ................. SUCCESS [ 14.761 s]
[INFO] Neo4j - Security ................................... SUCCESS [ 11.343 s]
[INFO] Neo4j - Bolt Protocol Version 1 .................... SUCCESS [ 32.378 s]
[INFO] Neo4j - Fabric ..................................... SUCCESS [ 10.339 s]
[INFO] Neo4j - Community Procedures ....................... SUCCESS [ 12.258 s]
[INFO] Neo4j - Data Collector ............................. SUCCESS [  6.493 s]
[INFO] Neo4j - Consistency Checker ........................ SUCCESS [ 22.069 s]
[INFO] Neo4j - Legacy Batch Inserter ...................... SUCCESS [  8.560 s]
[INFO] Neo4j - Import Command Line Tool ................... SUCCESS [ 30.656 s]
[INFO] Neo4j - Server API ................................. SUCCESS [  4.996 s]
[INFO] Neo4j - Server ..................................... SUCCESS [ 25.816 s]
[INFO] Neo4j - Community .................................. SUCCESS [01:18 min]
[INFO] Neo4j - Procedure Compiler Core .................... SUCCESS [ 48.923 s]
[INFO] Neo4j - Community Integration Tests ................ SUCCESS [  0.945 s]
[INFO] Neo4j - Community Integration Test Support ......... SUCCESS [ 44.940 s]
[INFO] Neo4j - Test Harness ............................... SUCCESS [22:23 min]
[INFO] Neo4j - Procedure Compiler Parent POM .............. SUCCESS [  0.514 s]
[INFO] Neo4j - Procedure Compiler Integration Tests ....... SUCCESS [02:07 min]
[INFO] Neo4j - Community (Bill of Materials) .............. SUCCESS [  1.284 s]
[INFO] Neo4j - Record Storage Engine Integration Tests .... SUCCESS [10:56 min]
[INFO] Neo4j - Community Kernel Integration Tests ......... SUCCESS [58:50 min]
[INFO] Neo4j - Legacy Batch Inserter Integration Tests .... SUCCESS [14:58 min]
[INFO] Neo4j - Community Index Integration Tests .......... SKIPPED
[INFO] Neo4j - Community Import Integration Tests ......... SUCCESS [  01:01 h]
[INFO] Neo4j - Community DBMS Integration Tests ........... SUCCESS [15:20 min]
[INFO] Neo4j - Community Graph Algorithms Integration Tests SUCCESS [34:25 min]
[INFO] Neo4j - Community Consistency Checker Integration Tests SUCCESS [  11:21 h]
[INFO] Neo4j - Community Bolt Integration Tests ........... FAILURE [24:30 min]
[INFO] Neo4j - Community Generic Integration Tests ........ SKIPPED
[INFO] Neo4j - Community Cypher Integration Tests ......... SUCCESS [18:10 min]
[INFO] Neo4j - Push To Cloud - Admin command .............. SUCCESS [02:24 min]
[INFO] Neo4j - Cypher Specification Suite Tools ........... SUCCESS [  9.496 s]
[INFO] Neo4j - Cypher Acceptance .......................... SUCCESS [01:09 min]
[INFO] Neo4j - Cypher Compatibility Specification Suite ... SUCCESS [05:36 min]
[INFO] Neo4j - Cypher AST factory ......................... SUCCESS [  3.055 s]
[INFO] Neo4j - Cypher JavaCC based parser ................. SUCCESS [  6.127 s]
[INFO] Neo4j - Neo4j/OpenCypher AST factory ............... SUCCESS [  1.447 s]
[INFO] Neo4j - Cypher Logical Plan Generator .............. SUCCESS [  0.912 s]
[INFO] Neo4j - Cypher Runtime Acceptance .................. SUCCESS [05:41 min]
[INFO] Neo4j - Community Build ............................ SUCCESS [  7.257 s]
[INFO] Neo4j - Server Assembler ........................... SUCCESS [  1.039 s]
[INFO] Neo4j - Community Server Assembler ................. SUCCESS [15:03 min]
[INFO] Neo4j - Packaging Build ............................ SUCCESS [  0.231 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11:50 h (Wall Clock)
[INFO] Finished at: 2020-05-31T14:10:34-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.2:verify (verify) on project bolt-it: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/zeyuanhu/Documents/neo4j/community/community-it/bolt-it/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/zeyuanhu/Documents/neo4j/community/community-it/bolt-it && /Library/Java/JavaVirtualMachines/jdk-11.0.7.jdk/Contents/Home/bin/java -Xmx2G -XX:+UseG1GC -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:+ExitOnOutOfMemoryError -XX:MaxInlineLevel=15 -Djdk.nio.maxCachedBufferSize=262144 -Dio.netty.tryReflectionSetAccessible=true '-XX:HeapDumpPath=target/test data' -Dorg.neo4j.internal.unsafe.UnsafeUtil.DIRTY_MEMORY=true -Dorg.neo4j.test.extension.ThreadLeakageGuardExtension.PRINT_ONLY=false -Dorg.neo4j.internal.unsafe.UnsafeUtil.CHECK_NATIVE_ACCESS=true -Dorg.neo4j.io.pagecache.impl.muninn.usePreciseCursorErrorStackTraces=true -Dorg.neo4j.kernel.impl.api.KernelStatement.trackStatements=true -Dorg.neo4j.kernel.impl.newapi.DefaultCursors.trackCursors=true -Dorg.neo4j.codegen.bytecode.ByteCodeExpressionVisitor.checkByteCode=false -Dorg.neo4j.bolt.transport.NettyServer.shutdownQuietPeriod=0 -Dorg.neo4j.bolt.transport.NettyServer.shutdownTimeout=3 -Djunit.jupiter.extensions.autodetection.enabled=true -Djunit.jupiter.execution.parallel.enabled=true -Djunit.jupiter.execution.timeout.default=20m -Djunit.jupiter.execution.parallel.mode.classes.default=concurrent -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:FlightRecorderOptions=stackdepth=256 -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -jar /Users/zeyuanhu/Documents/neo4j/community/community-it/bolt-it/target/surefire/surefirebooter5894410461785893948.jar /Users/zeyuanhu/Documents/neo4j/community/community-it/bolt-it/target/surefire 2020-05-31T02-19-55_851-jvmRun1 surefire8735781749883618188tmp surefire_6115510214303070017449tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 3
[ERROR] Crashed tests:
[ERROR] org.neo4j.bolt.transport.AuthenticationIT
[ERROR] org.neo4j.bolt.transport.SupportedStructTypesV2IT
[ERROR] org.neo4j.bolt.transport.TransportSessionIT
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:510)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:382)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:297)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:190)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:186)
[ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/zeyuanhu/Documents/neo4j/community/community-it/bolt-it && /Library/Java/JavaVirtualMachines/jdk-11.0.7.jdk/Contents/Home/bin/java -Xmx2G -XX:+UseG1GC -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:+ExitOnOutOfMemoryError -XX:MaxInlineLevel=15 -Djdk.nio.maxCachedBufferSize=262144 -Dio.netty.tryReflectionSetAccessible=true '-XX:HeapDumpPath=target/test data' -Dorg.neo4j.internal.unsafe.UnsafeUtil.DIRTY_MEMORY=true -Dorg.neo4j.test.extension.ThreadLeakageGuardExtension.PRINT_ONLY=false -Dorg.neo4j.internal.unsafe.UnsafeUtil.CHECK_NATIVE_ACCESS=true -Dorg.neo4j.io.pagecache.impl.muninn.usePreciseCursorErrorStackTraces=true -Dorg.neo4j.kernel.impl.api.KernelStatement.trackStatements=true -Dorg.neo4j.kernel.impl.newapi.DefaultCursors.trackCursors=true -Dorg.neo4j.codegen.bytecode.ByteCodeExpressionVisitor.checkByteCode=false -Dorg.neo4j.bolt.transport.NettyServer.shutdownQuietPeriod=0 -Dorg.neo4j.bolt.transport.NettyServer.shutdownTimeout=3 -Djunit.jupiter.extensions.autodetection.enabled=true -Djunit.jupiter.execution.parallel.enabled=true -Djunit.jupiter.execution.timeout.default=20m -Djunit.jupiter.execution.parallel.mode.classes.default=concurrent -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:FlightRecorderOptions=stackdepth=256 -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -jar /Users/zeyuanhu/Documents/neo4j/community/community-it/bolt-it/target/surefire/surefirebooter5894410461785893948.jar /Users/zeyuanhu/Documents/neo4j/community/community-it/bolt-it/target/surefire 2020-05-31T02-19-55_851-jvmRun1 surefire8735781749883618188tmp surefire_6115510214303070017449tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 3
[ERROR] Crashed tests:
[ERROR] org.neo4j.bolt.transport.AuthenticationIT
[ERROR] org.neo4j.bolt.transport.SupportedStructTypesV2IT
[ERROR] org.neo4j.bolt.transport.TransportSessionIT
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:115)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:371)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:347)
[ERROR] 	... 4 more
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :bolt-it
```

Does it take this long to finish the build process? Also, are all these unit tests failure expected?

Thanks!

**Comment by mnd999** [comment]
Closing this very old build failure as the 4.1 branch is no longer supported
