### ISSUE TITLE
Failed to restart discovery system

### ISSUE THREAD

**Issue by ofraiwan** [neo4j/neo4j#12510]
Starting with **neo4j 4**, some core members of the Causal Cluster will hang at some point of time, and cannot be stopped until terminating it from the OS.
I looked over the logs and noticed that a message pointing that the cause cluster discovery system cannot be restarted for some reason.

**Setup**:
Neo4j Version: 4.0.3
Operating System: Ubuntu 18.04.3 LTS
DB Mode: Causal Cluster

Moreover, as you can see in the logs, a memory leak maybe preset, because the JVM running out of memory error is raised.

This issue was not occurring on the previous version **3.5**. This issue causes the whole cluster to hang, until human intervention reloads the neo4j services.

This is the log file [neo4j_4_0_3_logs.txt](https://github.com/neo4j/neo4j/files/4614787/neo4j_4_0_3_logs.txt)

These are the configs used: [neo4j conf.zip](https://github.com/neo4j/neo4j/files/4614843/neo4j.conf.zip)

**Comment by asashour** [comment]
There is `OutOfMemoryError`, did you try to increase the memory?

Please look into [Memory configuration](https://neo4j.com/docs/operations-manual/current/performance/memory-configuration/)

**Comment by ofraiwan** [comment]
> There is `OutOfMemoryError`, did you try to increase the memory?
> 
> Please look into [Memory configuration](https://neo4j.com/docs/operations-manual/current/performance/memory-configuration/)

The default neo4j JVM memory configuration is dynamic based on the running machine, each core server has an 8-GB RAM.

```
# Java Heap Size: by default the Java heap size is dynamically
# calculated based on available system resources.
# Uncomment these lines to set specific initial and maximum
# heap size.
#dbms.memory.heap.initial_size=512m
#dbms.memory.heap.max_size=512m
```

**Comment by JnMik** [comment]
I have the same issue, my cluster just failed me !

Logs for neo4j-core-0  (kubectl logs -f neo4j-v1-core-v1-0-

```
2020-08-18 21:54:10.989+0000 INFO  ======== Neo4j 4.1.1 ========
2020-08-18 21:54:15.115+0000 INFO  Resolved [discovery-neo4j-v1-neo4j-0.neo4j.svc.cluster.local:5000, discovery-neo4j-v1-neo4j-2.neo4j.svc.cluster.local:5000, discovery-neo4j-v1-neo4j-1.neo4j.svc.cluster.local:5000] from Kubernetes API at kubernetes.default.svc:443 namespace neo4j labelSelector neo4j.com/cluster=neo4j-v1-neo4j,neo4j.com/role=CORE,neo4j.com/coreindex in (0, 1, 2)
2020-08-18 21:54:30.448+0000 INFO  Bound database 'system' to raft with id '00000000-0000-0000-0000-000000000001' as member id '7a750860-c83f-4a08-a0ba-44ab3bbf732f', found on disk.
2020-08-18 21:54:30.685+0000 INFO  Connected to discovery-neo4j-v1-neo4j-2.neo4j.svc.cluster.local/10.4.12.7:7000 [raft version:3.0]
2020-08-18 21:54:31.834+0000 INFO  Bound database 'neo4j' to raft with id 'b48bf2db-0f76-42da-b7af-069ae9532ff2' as member id '7a750860-c83f-4a08-a0ba-44ab3bbf732f', found on disk.
2020-08-18 21:54:34.092+0000 INFO  Called db.clearQueryCaches(): Query cache already empty.
2020-08-18 21:54:34.219+0000 INFO  Bound database 'xxxxx' to raft with id '7925cac0-f311-4a31-9c77-6f678473ec8d' as member id '7a750860-c83f-4a08-a0ba-44ab3bbf732f', found on disk.
2020-08-18 21:54:34.312+0000 INFO  Connected to discovery-neo4j-v1-neo4j-1.neo4j.svc.cluster.local/10.4.11.216:7000 [raft version:3.0]
2020-08-18 21:54:34.989+0000 INFO  Called db.clearQueryCaches(): Query cache already empty.
2020-08-18 21:54:39.296+0000 INFO  Bound database 'xxxxxx' to raft with id '3693638a-89a8-44ba-b449-8c0fcd9019b8' as member id '7a750860-c83f-4a08-a0ba-44ab3bbf732f', found on disk.
2020-08-18 21:54:41.125+0000 INFO  Called db.clearQueryCaches(): Query cache already empty.
2020-08-18 21:54:48.716+0000 INFO  Sending metrics to CSV file at /var/lib/neo4j/metrics
2020-08-18 21:54:48.729+0000 INFO  Started publishing Prometheus metrics at http:///0.0.0.0:2004/metrics
2020-08-18 21:54:48.789+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2020-08-18 21:54:50.139+0000 INFO  Remote interface available at http://neo4j-v1-neo4j-core-0.neo4j-v1-neo4j.neo4j.svc.cluster.local:7474/
2020-08-18 21:54:50.139+0000 INFO  Started.
2020-08-18 22:31:34.965+0000 INFO  Lost connection to discovery-neo4j-v1-neo4j-1.neo4j.svc.cluster.local/10.4.11.216:7000 [raft version:3.0]
2020-08-18 22:31:52.601+0000 INFO  Connected to discovery-neo4j-v1-neo4j-1.neo4j.svc.cluster.local/10.4.11.216:7000 [raft version:3.0]
2020-08-18 23:41:44.839+0000 INFO  Lost connection to discovery-neo4j-v1-neo4j-1.neo4j.svc.cluster.local/10.4.11.216:7000 [raft version:3.0]
2020-08-18 23:42:02.030+0000 INFO  Connected to discovery-neo4j-v1-neo4j-1.neo4j.svc.cluster.local/10.4.11.216:7000 [raft version:3.0]
2020-08-19 00:07:34.899+0000 INFO  Lost connection to discovery-neo4j-v1-neo4j-1.neo4j.svc.cluster.local/10.4.11.216:7000 [raft version:3.0]
2020-08-19 00:07:59.780+0000 INFO  Connected to discovery-neo4j-v1-neo4j-1.neo4j.svc.cluster.local/10.4.11.216:7000 [raft version:3.0]
2020-08-19 00:20:14.142+0000 INFO  Lost connection to discovery-neo4j-v1-neo4j-2.neo4j.svc.cluster.local/10.4.12.7:7000 [raft version:3.0]
2020-08-19 00:22:55.949+0000 INFO  Restarting discovery system after probable network partition
2020-08-19 00:25:18.178+0000 WARN  Failed to restart discovery system
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:84)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:84)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.package$.blocking(package.scala:146)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:84)
	at com.neo4j.causalclustering.discovery.akka.system.ActorSystemLifecycle.doShutdown(ActorSystemLifecycle.java:116)
	at com.neo4j.causalclustering.discovery.akka.system.ActorSystemLifecycle.shutdown(ActorSystemLifecycle.java:95)
	at com.neo4j.causalclustering.discovery.akka.AkkaCoreTopologyService.stop0(AkkaCoreTopologyService.java:201)
	at org.neo4j.kernel.lifecycle.SafeLifecycle.transition(SafeLifecycle.java:120)
	at org.neo4j.kernel.lifecycle.SafeLifecycle.stop(SafeLifecycle.java:148)
	at com.neo4j.causalclustering.discovery.akka.AkkaCoreTopologyService.doRestart(AkkaCoreTopologyService.java:279)
	at com.neo4j.causalclustering.discovery.akka.Restarter.restart(Restarter.java:34)
	at com.neo4j.causalclustering.discovery.akka.AkkaCoreTopologyService.restart(AkkaCoreTopologyService.java:272)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

If I run the same command to view the logs but with --previous flag, the last line is

```
Terminating due to java.lang.OutOfMemoryError: Java heap space
```

**Comment by RagnarW** [comment]
Closing due to unsupported version
