### ISSUE TITLE
Database create /drop problem: reconcile state error

### ISSUE THREAD

**Issue by innerforce** [neo4j/neo4j#12553]
- Neo4j version: 4.0.6 Enterprise trial
- Operating system: CentOS-7 
- installation: RPM repo
- **Steps to reproduce**
1. in neo4j browser remove a working test database: drop database xxx 
2. create a new test databases: create database xxx, create database yyy
3. Every new database I create will fail to go “online”, we have now no database to use besides “system”
note: 
some operations before this happened might be relevant:
`i created a new admin user. 
the 1st dropped database is created some days ago which had no such state transition issue. i also made some successful data import before drop it `

- Expected behavior
created database is online 
- Actual behavior
created database is offline with state transient error 
repeat the drop/create will be the same behavior
stop/start neo4j wont fix the issue, error in debug.log as below

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.
2020-07-17 19:22:54.611+0000 ERROR [o.n.m.DatabaseHealth] [pharosdl] Database panic: The database has encountered a critical error, and needs to be restarted. Please see database logs for more details. Encountered error when attempting to reconcile database pharosdl from state 'EnterpriseDatabaseState{databaseId=DatabaseId{f4cb8afb[pharosdl]}, operatorState=STOPPED, failed=false}' to state 'online'
java.lang.IllegalStateException: Encountered error when attempting to reconcile database pharosdl from state 'EnterpriseDatabaseState{databaseId=DatabaseId{f4cb8afb[pharosdl]}, operatorState=STOPPED, failed=false}' to state 'online'
	at com.neo4j.dbms.DbmsReconciler.reportErrorAndPanicDatabase(DbmsReconciler.java:447)
	at com.neo4j.dbms.DbmsReconciler.handleReconciliationErrors(DbmsReconciler.java:432)
	at com.neo4j.dbms.DbmsReconciler.lambda$postReconcile$15(DbmsReconciler.java:381)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at com.neo4j.dbms.DbmsReconciler.postReconcile(DbmsReconciler.java:379)
	at com.neo4j.dbms.DbmsReconciler.lambda$scheduleReconciliationJob$8(DbmsReconciler.java:246)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.neo4j.dbms.api.DatabaseManagementException: An error occurred! Unable to start database with name `phdlprod`.
	at org.neo4j.dbms.database.AbstractDatabaseManager.startDatabase(AbstractDatabaseManager.java:191)
	at com.neo4j.dbms.database.MultiDatabaseManager.forSingleDatabase(MultiDatabaseManager.java:112)
	at com.neo4j.dbms.database.MultiDatabaseManager.startDatabase(MultiDatabaseManager.java:98)
	at com.neo4j.dbms.DbmsReconciler.start(DbmsReconciler.java:549)
	at com.neo4j.dbms.Transitions$TransitionFunction.lambda$prepare$0(Transitions.java:219)
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:347)
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:348)
	at com.neo4j.dbms.DbmsReconciler.doTransitions(DbmsReconciler.java:330)
	at com.neo4j.dbms.DbmsReconciler.lambda$doTransitions$10(DbmsReconciler.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 3 more
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Config has no association with setting: 'dbms.directories.neo4j_home'
	at org.neo4j.kernel.database.Database.start(Database.java:478)
	at org.neo4j.dbms.database.AbstractDatabaseManager.startDatabase(AbstractDatabaseManager.java:187)
	... 12 more
Caused by: java.lang.IllegalArgumentException: Config has no association with setting: 'dbms.directories.neo4j_home'
	at org.neo4j.configuration.Config.getObserver(Config.java:633)
	at org.neo4j.configuration.Config.get(Config.java:622)
	at org.neo4j.io.layout.Neo4jLayout.of(Neo4jLayout.java:89)
	at org.neo4j.io.layout.Neo4jLayout.ofFlat(Neo4jLayout.java:103)
	at org.neo4j.io.layout.DatabaseLayout.ofFlat(DatabaseLayout.java:61)
	at org.neo4j.kernel.impl.storemigration.StoreUpgrader.migrateIfNeeded(StoreUpgrader.java:126)
	at org.neo4j.kernel.impl.storemigration.DatabaseMigrator.migrate(DatabaseMigrator.java:96)
	at org.neo4j.kernel.database.Database.upgradeStore(Database.java:506)
	at org.neo4j.kernel.database.Database.start(Database.java:354)
	... 13 more

**Comment by innerforce** [comment]
it is a root user command "systemctl start neo4j" should not be used on server.  i close the issue.
