### ISSUE TITLE
Checkpoint trigger is shutting down the neo4j server.

### ISSUE THREAD

**Issue by Govidnda** [neo4j/neo4j#12574]
Below is the complete error log from the server, due to this error neo4j server is stopping. Could you please help us to fix this issue. Due to this issue, we are unable to proceed with our development and testing activities. 

Neo4j version : 3.5.12 enterprise

2020-08-28 17:05:26.985+0000 WARN [o.n.b.r.MetricsReportingBoltConnection] The client is unauthorized due to authentication failure.
2020-08-28 17:20:38.649+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Checkpoint triggered by "Scheduled checkpoint for time threshold" @ txId: 250002 checkpoint started...
2020-08-28 17:20:38.662+0000 ERROR [o.n.k.i.t.l.c.CheckPointerImpl] Checkpoint failed Unable to force ContractCheckingIndexProxy -> OnlineIndexProxy[accessor:org.neo4j.kernel.impl.index.schema.fusion.FusionIndexAccessor@72ab20d1, descriptor:IndexRule[id=1, descriptor=Index( UNIQUE, :label[0](property[0]) ), provider={key=lucene, version=1.0}, owner=3]]
org.neo4j.kernel.impl.store.UnderlyingStorageException: Unable to force ContractCheckingIndexProxy -> OnlineIndexProxy[accessor:org.neo4j.kernel.impl.index.schema.fusion.FusionIndexAccessor@72ab20d1, descriptor:IndexRule[id=1, descriptor=Index( UNIQUE, :label[0](property[0]) ), provider={key=lucene, version=1.0}, owner=3]]
	at org.neo4j.kernel.impl.api.index.IndexingService.lambda$indexProxyOperation$f3401ac3$1(IndexingService.java:780)
	at org.eclipse.collections.impl.map.mutable.primitive.LongObjectHashMap.forEachKeyValue(LongObjectHashMap.java:669)
	at org.neo4j.kernel.impl.api.index.IndexMap.forEachIndexProxy(IndexMap.java:133)
	at org.neo4j.kernel.impl.api.index.IndexingService.forceAll(IndexingService.java:764)
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.flushAndForce(RecordStorageEngine.java:415)
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:179)
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.checkPointIfNeeded(CheckPointerImpl.java:153)
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.run(CheckPointScheduler.java:65)
	at org.neo4j.kernel.impl.scheduler.ScheduledJobHandle.lambda$new$0(ScheduledJobHandle.java:83)
	at org.neo4j.kernel.impl.scheduler.ThreadPool.lambda$submit$0(ThreadPool.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.UncheckedIOException: java.nio.file.AccessDeniedException: /var/lib/neo4j/data/databases/devgraph.db/schema/index/lucene/1/1/_6c.cfs
	at org.neo4j.kernel.api.impl.index.AbstractLuceneIndexAccessor.force(AbstractLuceneIndexAccessor.java:91)
	at org.neo4j.kernel.impl.index.schema.fusion.FusionIndexAccessor.lambda$force$1(FusionIndexAccessor.java:77)
	at org.neo4j.kernel.impl.index.schema.fusion.InstanceSelector.consumeAndChainException(InstanceSelector.java:193)
	at org.neo4j.kernel.impl.index.schema.fusion.InstanceSelector.forAll(InstanceSelector.java:134)
	at org.neo4j.kernel.impl.index.schema.fusion.FusionIndexAccessor.force(FusionIndexAccessor.java:77)
	at org.neo4j.kernel.impl.api.index.OnlineIndexProxy.force(OnlineIndexProxy.java:141)
	at org.neo4j.kernel.impl.api.index.AbstractDelegatingIndexProxy.force(AbstractDelegatingIndexProxy.java:79)
	at org.neo4j.kernel.impl.api.index.ContractCheckingIndexProxy.force(ContractCheckingIndexProxy.java:127)
	at org.neo4j.kernel.impl.api.index.IndexingService.lambda$forceAll$10(IndexingService.java:764)
	at org.neo4j.kernel.impl.api.index.IndexingService.lambda$indexProxyOperation$f3401ac3$1(IndexingService.java:773)
	... 14 more
Caused by: java.nio.file.AccessDeniedException: /var/lib/neo4j/data/databases/devgraph.db/schema/index/lucene/1/1/_6c.cfs
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at org.apache.lucene.util.IOUtils.fsync(IOUtils.java:391)
	at org.apache.lucene.store.FSDirectory.fsync(FSDirectory.java:288)
	at org.apache.lucene.store.FSDirectory.sync(FSDirectory.java:232)
	at org.apache.lucene.store.NRTCachingDirectory.sync(NRTCachingDirectory.java:165)
	at org.apache.lucene.store.LockValidatingDirectoryWrapper.sync(LockValidatingDirectoryWrapper.java:62)
	at org.apache.lucene.index.IndexWriter.startCommit(IndexWriter.java:4446)
	at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:2865)
	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:2970)
	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:2935)
	at org.neo4j.kernel.api.impl.index.AbstractLuceneIndex.flush(AbstractLuceneIndex.java:238)
	at org.neo4j.kernel.api.impl.index.AbstractLuceneIndex.markAsOnline(AbstractLuceneIndex.java:460)
	at org.neo4j.kernel.api.impl.index.WritableAbstractDatabaseIndex.markAsOnline(WritableAbstractDatabaseIndex.java:177)
	at org.neo4j.kernel.api.impl.index.AbstractLuceneIndexAccessor.force(AbstractLuceneIndexAccessor.java:85)
	... 23 more
2020-08-28 17:20:48.664+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Checkpoint triggered by "Scheduled checkpoint for time threshold" @ txId: 250064 checkpoint started...
2020-08-28 17:20:48.669+0000 ERROR [o.n.k.i.t.l.c.CheckPointerImpl] Checkpoint failed Unable to force ContractCheckingIndexProxy -> OnlineIndexProxy[accessor:org.neo4j.kernel.impl.index.schema.fusion.FusionIndexAccessor@72ab20d1, descriptor:IndexRule[id=1, descriptor=Index( UNIQUE, :label[0](property[0]) ), provider={key=lucene, version=1.0}, owner=3]]
org.neo4j.kernel.impl.store.UnderlyingStorageException: Unable to force ContractCheckingIndexProxy -> OnlineIndexProxy[accessor:org.neo4j.kernel.impl.index.schema.fusion.FusionIndexAccessor@72ab20d1, descriptor:IndexRule[id=1, descriptor=Index( UNIQUE, :label[0](property[0]) ), provider={key=lucene, version=1.0}, owner=3]]
	at org.neo4j.kernel.impl.api.index.IndexingService.lambda$indexProxyOperation$f3401ac3$1(IndexingService.java:780)
	at org.eclipse.collections.impl.map.mutable.primitive.LongObjectHashMap.forEachKeyValue(LongObjectHashMap.java:669)
	at org.neo4j.kernel.impl.api.index.IndexMap.forEachIndexProxy(IndexMap.java:133)
	at org.neo4j.kernel.impl.api.index.IndexingService.forceAll(IndexingService.java:764)
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.flushAndForce(RecordStorageEngine.java:415)
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:179)
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.checkPointIfNeeded(CheckPointerImpl.java:153)
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.run(CheckPointScheduler.java:65)
	at org.neo4j.kernel.impl.scheduler.ScheduledJobHandle.lambda$new$0(ScheduledJobHandle.java:83)
	at org.neo4j.kernel.impl.scheduler.ThreadPool.lambda$submit$0(ThreadPool.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.UncheckedIOException: java.nio.file.AccessDeniedException: /var/lib/neo4j/data/databases/devgraph.db/schema/index/lucene/1/1/_6c.cfs

**Comment by mnd999** [comment]
Thanks for the report, this looks like it might be a filesystem permissions issue. Does neo4j have write access to those directories?

**Comment by mnd999** [comment]
As we haven't had a response on this issue, I'll close for now. Feel free to reopen if it's still an issue.
