### ISSUE TITLE
Neo4j Test Harness with Scala 2.13

### ISSUE THREAD

**Issue by swakhandekar** [neo4j/neo4j#12585]
- Neo4j test-harness version: 4.1.1
- Operating system: MacOS Catalina
- API/Driver: Java API
- Java version: 11

### Steps to reproduce
1 Create a new Scala project using SBT
2. Run the test using test-harness

build.sbt
```
name := "neo4j-harness-test"

version := "0.1"

scalaVersion := "2.13.3"

libraryDependencies += "org.neo4j.driver" % "neo4j-java-driver" % "4.1.1"

libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.0" % Test
libraryDependencies += "org.scalatest" %% "scalatest-funsuite" % "3.2.0" % Test
libraryDependencies += "org.mockito" %% "mockito-scala" % "1.15.0" % Test
libraryDependencies += "org.neo4j.test" % "neo4j-harness" % "4.1.1" % Test
```

Test.scala:
```
package harness

import org.neo4j.harness.Neo4jBuilders
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec

class Test extends AnyWordSpec with Matchers {
  "should not fail" in  {
    val neo4j = Neo4jBuilders.newInProcessBuilder().build()

    neo4j.boltURI() shouldBe ""
  }
}

```
### Expected behavior
Test should fail with showing actual bolt URL of the created instance

### Actual behavior
Test crashes with following error:
```
[info] Test:
[info] - should not fail *** FAILED ***
[info]   org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabaseService@5caf3446' was successfully initialized, but failed to start. Please see the attached cause exception "scala.Serializable".
[info]   at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
[info]   at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:163)
[info]   at org.neo4j.harness.internal.InProcessNeo4j.start(InProcessNeo4j.java:95)
[info]   at org.neo4j.harness.internal.AbstractInProcessNeo4jBuilder.build(AbstractInProcessNeo4jBuilder.java:160)
[info]   at org.neo4j.harness.internal.AbstractInProcessNeo4jBuilder.build(AbstractInProcessNeo4jBuilder.java:73)
[info]   at harness.Test.$anonfun$new$1(Test.scala:9)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   ...
[info]   Cause: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabaseService@5caf3446' was successfully initialized, but failed to start. Please see the attached cause exception "scala.Serializable".
[info]   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:465)
[info]   at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
[info]   at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:156)
[info]   at org.neo4j.harness.internal.InProcessNeo4j.start(InProcessNeo4j.java:95)
[info]   at org.neo4j.harness.internal.AbstractInProcessNeo4jBuilder.build(AbstractInProcessNeo4jBuilder.java:160)
[info]   at org.neo4j.harness.internal.AbstractInProcessNeo4jBuilder.build(AbstractInProcessNeo4jBuilder.java:73)
[info]   at harness.Test.$anonfun$new$1(Test.scala:9)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[info]   Cause: java.lang.NoClassDefFoundError: scala/Serializable
[info]   at org.neo4j.cypher.internal.evaluator.SimpleInternalExpressionEvaluator.evaluate(SimpleInternalExpressionEvaluator.scala:42)
[info]   at org.neo4j.cypher.internal.evaluator.SimpleExpressionEvaluator.evaluate(SimpleExpressionEvaluator.java:44)
[info]   at org.neo4j.procedure.impl.MapConverter.apply(MapConverter.java:46)
[info]   at org.neo4j.procedure.impl.MapConverter.apply(MapConverter.java:31)
[info]   at org.neo4j.procedure.impl.TypeCheckers$DefaultValueConverter.defaultValue(TypeCheckers.java:321)
[info]   at org.neo4j.procedure.impl.MethodSignatureCompiler.signatureFor(MethodSignatureCompiler.java:84)
[info]   at org.neo4j.procedure.impl.ProcedureCompiler.compileProcedure(ProcedureCompiler.java:251)
[info]   at org.neo4j.procedure.impl.ProcedureCompiler.compileProcedure(ProcedureCompiler.java:225)
[info]   at org.neo4j.procedure.impl.GlobalProceduresRegistry.registerProcedure(GlobalProceduresRegistry.java:176)
[info]   at org.neo4j.procedure.impl.GlobalProceduresRegistry.registerProcedure(GlobalProceduresRegistry.java:164)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: scala.Serializable
[info]   at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[info]   at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:98)
[info]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[info]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[info]   at org.neo4j.cypher.internal.evaluator.SimpleInternalExpressionEvaluator.evaluate(SimpleInternalExpressionEvaluator.scala:42)
[info]   at org.neo4j.cypher.internal.evaluator.SimpleExpressionEvaluator.evaluate(SimpleExpressionEvaluator.java:44)
[info]   at org.neo4j.procedure.impl.MapConverter.apply(MapConverter.java:46)
[info]   at org.neo4j.procedure.impl.MapConverter.apply(MapConverter.java:31)
[info]   at org.neo4j.procedure.impl.TypeCheckers$DefaultValueConverter.defaultValue(TypeCheckers.java:321)
[info]   at org.neo4j.procedure.impl.MethodSignatureCompiler.signatureFor(MethodSignatureCompiler.java:84)
[info]   ...
[info] Run completed in 937 milliseconds.
```

I ran the same test by downgrading the Scala to version `2.12.12` and the test failed as expected without crashing.

**Comment by mnd999** [comment]
Thanks for the issue. The current versions of Neo4j use Scala 2.12. Once the product supports 2.13 the harness will be upgraded to support it as well.

**Comment by LinneaAndersson** [comment]
@swakhandekar I will close this issue as Neo4j 5.x is using Scala 2.13. Let us know if you have any questions or need more information, 
Linnéa
