### ISSUE TITLE
Fail to start neo4j service due to java.util.ServiceConfigurationError

### ISSUE THREAD

**Issue by stone-ts15** [neo4j/neo4j#12593]
I failed to start neo4j service on my Ubuntu server. 

Here is the error message in `neo4j.log` .

```log
Exception in thread "main" java.util.ServiceConfigurationError: org.neo4j.configuration.LoadableConfig: Provider org.neo4j.kernel.configuration.ssl.SslPolicyConfig not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.neo4j.configuration.LoadableConfig.allConfigClasses(LoadableConfig.java:103)
	at org.neo4j.kernel.configuration.Config$Builder.build(Config.java:290)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:95)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
2020-09-28 11:01:46.784+0000 INFO [o.n.s.CommunityBootstrapper] Neo4j Server shutdown initiated by request
```

Some environment information:

**Neo4j Version:** 3.3.3
**Operating System:** Ubuntu 16.04.3 LTS
**Java:** Java 8

There are few discussions about `ServiceConfigurationError` in running neo4j server.

**Comment by mnd999** [comment]
Thanks for the report. Unfortunately Neo4j 3.3.3 is no longer supported. Are you able to try one of the supported versions? See https://neo4j.com/developer/kb/neo4j-supported-versions/

**Comment by stone-ts15** [comment]
@mnd999 Thanks for the reply! I am sorry for reporting a wrong version of Neo4j. I just noticed the actual version above is 3.5.14, but `neo4j 3.3.3` was shown after I typed `neo4j version` .
Now I install Neo4j 3.5.22 instead, but the bug remains. Perhaps this bug is related to Java.

**Comment by mnd999** [comment]
If `neo4j version` is returning 3.3.3 but the package is 3.5.14 it may be that you have two versions (or the remnants of an old version) installed that are conflicting. I would suggest checking for any remaining configuration and jars from 3.3.3 and removing them. 

Our Java requirements for 3.5.x are documented here: https://neo4j.com/docs/operations-manual/3.5/installation/requirements/#_software

**Comment by mnd999** [comment]
We haven't had any updates to this issue for some time, so I will close it for now. If it's still a problem, please feel free to re-open.
