### ISSUE TITLE
neo4j-admin import fails - CursorException: Expected record to be the first unit in the chain

### ISSUE THREAD

**Issue by rom-burner** [neo4j/neo4j#12617]
After I accidentally threadjacked issue #12606 I preprocessed my data to sort and dedup (took 10mins of single threaded runtime and 80G memory, not sure why neo4j-admin import got stuck on that for over a day), but now the import process fails later on with a CursorException, but I'm having a hard time finding from where in the source the thrown error message is coming.

- Neo4j version: 4.1.3 enterprise
- Operating system: Ubuntu 20.04
- Steps to reproduce
```
docker run -it --rm
--ulimit nofile=1048576:1048576
--volume=$HOME/outfiles/data:/data
--volume=$HOME/logs:/logs
--volume=$HOME/infiles:/var/lib/neo4j/import:ro
--user=$(id -u):$(id -g)
--env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
--env NEO4J_AUTH=neo4j/neo4j
--env NEO4J_dbms_memory_heap_initial__size=20g
--env NEO4J_dbms_memory_heap_max__size=20g
--env NEO4J_dbms_memory_pagecache_size=210g
--env NEO4J_dbms_record__format=high_limit
--env NEO4J_dbms_allow__upgrade=false
neo4j:4.1.3-enterprise
neo4j-admin import
--verbose
--database=newdb
--high-io=true
--report-file=/dev/null
--skip-bad-entries-logging=true
--skip-bad-relationships=true
--bad-tolerance=100000000
--nodes=Node=import/nodes_h.csv,import/nodes.csv
--relationships=import/relationships_h.csv,import/relationships.csv
```
After 16+hrs the import process output ends with this error:
```
Available resources:       
  Total machine memory: 249.7GiB
  Free machine memory: 111.0GiB
  Max heap memory : 19.99GiB
  Processors: 32           
  Configured max memory: 207.5GiB
  High-IO: true            
                           
WARNING: 4.909GiB memory may not be sufficient to complete this import. Suggested memory distribution is:
heap size: 2.952GiB        
minimum free and available memory excluding heap size: 89.85GiBWill use double record units for all relationships
Nodes, started 2020-11-01 11:27:05.923+0000
[*Nodes:0B/s 50.67GiB-------------------------------------------------------------------------]6.66B ∆1.39M
Done in 3h 45m 49s 872ms   
Prepare node index, started 2020-11-01 15:14:57.922+0000
[*DEDUPLICATE:81.77GiB------------------------------------------------------------------------]28.6B ∆ 270K
Done in 41m 45s 794ms      
DEDUP, started 2020-11-01 15:56:44.019+0000
[*DEDUP---------------------------------------------------------------------------------------]    0 ∆    0
Done in 1m 6s 325ms        
Relationships, started 2020-11-01 15:57:50.354+0000
[*Relationships:0B/s 81.77GiB-----------------------------------------------------------------]13.2B ∆    0
Done in 6h 4m 32s 63ms     
Node Degrees, started 2020-11-01 22:02:56.108+0000
[*>(32)========================================================================|CALCULATE:63.0]26.3B ∆3.92M
Done in 53m 30s 873ms      
Relationship --> Relationship 1-14/14, started 2020-11-01 22:57:00.643+0000
[*>(30)=======================================|LINK----------------------------------------|v:]26.3B ∆3.72M
Done in 3h 38m 58s 781ms   
RelationshipGroup 1-14/14, started 2020-11-02 02:35:59.445+0000
[*>:53.03MiB/s-----------------------------------------------------------------------|v:53.03M]46.9M ∆ 401K
Done in 27s 136ms          
Node --> Relationship, started 2020-11-02 02:36:26.588+0000
[>:2|*>(32)================================================|LI|v:55.69MiB/s-------------------]6.65B ∆1.70M
Done in 30m 22s 164ms      
Relationship <-- Relationship 1-14/14, started 2020-11-02 03:06:49.556+0000
[*>--------------------------------------------|LINK--------------------------------|v:??-----] 353K ∆ 353K
Done in 182ms              
                           
IMPORT FAILED in 16h 10m 32s 119ms.
Imported:                  
  6665853217 nodes         
  13174533563 relationships
  34047040077 properties   
Peak memory usage: 81.77GiB
Import error: org.neo4j.io.pagecache.CursorException: Expected record to be the first unit in the chain, but record header says it's not                          
Caused by:org.neo4j.io.pagecache.CursorException: Expected record to be the first unit in the chain, but record header says it's not
org.neo4j.kernel.impl.store.InvalidRecordException: org.neo4j.io.pagecache.CursorException: Expected record to be the first unit in the chain, but record header says it's not
        at org.neo4j.kernel.impl.store.record.RecordLoad.clearOrThrowCursorError(RecordLoad.java:86)
        at org.neo4j.kernel.impl.store.CommonAbstractStore.checkForDecodingErrors(CommonAbstractStore.java:1079)
        at org.neo4j.kernel.impl.store.CommonAbstractStore.readRecordFromPage(CommonAbstractStore.java:934)
        at org.neo4j.kernel.impl.store.CommonAbstractStore.readIntoRecord(CommonAbstractStore.java:888)
        at org.neo4j.kernel.impl.store.CommonAbstractStore.getRecordByCursor(CommonAbstractStore.java:869)
        at org.neo4j.internal.batchimport.staging.RecordDataAssembler.append(RecordDataAssembler.java:70)
        at org.neo4j.internal.batchimport.staging.ReadRecordsStep.process(ReadRecordsStep.java:92)
        at org.neo4j.internal.batchimport.staging.ReadRecordsStep.process(ReadRecordsStep.java:38)
        at org.neo4j.internal.batchimport.staging.ProcessorStep.lambda$receive$1(ProcessorStep.java:84)
        at org.neo4j.internal.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:224)
        Suppressed: org.neo4j.internal.batchimport.executor.TaskExecutionPanicException: Executor has been shut down in panic
                at org.neo4j.internal.batchimport.executor.DynamicTaskExecutor.assertHealthy(DynamicTaskExecutor.java:143)
                at org.neo4j.internal.batchimport.executor.DynamicTaskExecutor.submit(DynamicTaskExecutor.java:128)
                at org.neo4j.internal.batchimport.staging.ProcessorStep.receive(ProcessorStep.java:77)
                at org.neo4j.internal.batchimport.staging.ProducerStep.sendDownstream(ProducerStep.java:82)
                at org.neo4j.internal.batchimport.staging.PullingProducerStep.process(PullingProducerStep.java:50)
                at org.neo4j.internal.batchimport.staging.ProducerStep$1.run(ProducerStep.java:63)
        Caused by: java.lang.RuntimeException: org.neo4j.kernel.impl.store.InvalidRecordException: org.neo4j.io.pagecache.CursorException: Expected record to be the first unit in the chain, but record header says it's not
                at org.neo4j.internal.batchimport.staging.AbstractStep.issuePanic(AbstractStep.java:148)
                at org.neo4j.internal.batchimport.staging.AbstractStep.issuePanic(AbstractStep.java:140)
                at org.neo4j.internal.batchimport.staging.ProcessorStep.lambda$receive$1(ProcessorStep.java:99)
                at org.neo4j.internal.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:224)
        Caused by: [CIRCULAR REFERENCE: org.neo4j.kernel.impl.store.InvalidRecordException: org.neo4j.io.pagecache.CursorException: Expected record to be the first unit in the chain, but record header says it's not]
Caused by: org.neo4j.io.pagecache.CursorException: Expected record to be the first unit in the chain, but record header says it's not
        at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.checkAndClearCursorException(MuninnPageCursor.java:1043)
        at org.neo4j.kernel.impl.store.record.RecordLoad.clearOrThrowCursorError(RecordLoad.java:82)
        ... 9 more         
                           
There were bad entries which were skipped and logged into /dev/null
WARNING Import failed. The store files in /data/databases/newdb are left as they are, although they are likely in an unusable state. Starting a database on these store files will likely fail or observe inconsistent records so start at your own risk or delete the store manually                      
org.neo4j.kernel.impl.store.InvalidRecordException: org.neo4j.io.pagecache.CursorException: Expected record to be the first unit in the chain, but record header says it's not
        at org.neo4j.kernel.impl.store.record.RecordLoad.clearOrThrowCursorError(RecordLoad.java:86)
        at org.neo4j.kernel.impl.store.CommonAbstractStore.checkForDecodingErrors(CommonAbstractStore.java:1079)
        at org.neo4j.kernel.impl.store.CommonAbstractStore.readRecordFromPage(CommonAbstractStore.java:934)
        at org.neo4j.kernel.impl.store.CommonAbstractStore.readIntoRecord(CommonAbstractStore.java:888)
        at org.neo4j.kernel.impl.store.CommonAbstractStore.getRecordByCursor(CommonAbstractStore.java:869)
        at org.neo4j.internal.batchimport.staging.RecordDataAssembler.append(RecordDataAssembler.java:70)
        at org.neo4j.internal.batchimport.staging.ReadRecordsStep.process(ReadRecordsStep.java:92)
        at org.neo4j.internal.batchimport.staging.ReadRecordsStep.process(ReadRecordsStep.java:38)
        at org.neo4j.internal.batchimport.staging.ProcessorStep.lambda$receive$1(ProcessorStep.java:84)
        at org.neo4j.internal.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:224)
        Suppressed: org.neo4j.internal.batchimport.executor.TaskExecutionPanicException: Executor has been shut down in panic
                at org.neo4j.internal.batchimport.executor.DynamicTaskExecutor.assertHealthy(DynamicTaskExecutor.java:143)
                at org.neo4j.internal.batchimport.executor.DynamicTaskExecutor.submit(DynamicTaskExecutor.java:128)
                at org.neo4j.internal.batchimport.staging.ProcessorStep.receive(ProcessorStep.java:77)
                at org.neo4j.internal.batchimport.staging.ProducerStep.sendDownstream(ProducerStep.java:82)
                at org.neo4j.internal.batchimport.staging.PullingProducerStep.process(PullingProducerStep.java:50)
                at org.neo4j.internal.batchimport.staging.ProducerStep$1.run(ProducerStep.java:63)
        Caused by: java.lang.RuntimeException: org.neo4j.kernel.impl.store.InvalidRecordException: org.neo4j.io.pagecache.CursorException: Expected record to be the first unit in the chain, but record header says it's not
                at org.neo4j.internal.batchimport.staging.AbstractStep.issuePanic(AbstractStep.java:148)
                at org.neo4j.internal.batchimport.staging.AbstractStep.issuePanic(AbstractStep.java:140)
                at org.neo4j.internal.batchimport.staging.ProcessorStep.lambda$receive$1(ProcessorStep.java:99)
                at org.neo4j.internal.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:224)
        Caused by: [CIRCULAR REFERENCE: org.neo4j.kernel.impl.store.InvalidRecordException: org.neo4j.io.pagecache.CursorException: Expected record to be the first unit in the chain, but record header says it's not]
Caused by: org.neo4j.io.pagecache.CursorException: Expected record to be the first unit in the chain, but record header says it's not
        at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.checkAndClearCursorException(MuninnPageCursor.java:1043)
        at org.neo4j.kernel.impl.store.record.RecordLoad.clearOrThrowCursorError(RecordLoad.java:82)
        ... 9 more
```
The free resources reported and the memory warning at the beginning don't match with the dedicated setup of the machine (256GB ram) or the memory config I've tried to declare.  Import csv files total 2.9TB on separately mounted storage.  Output database is 4.6T at this point.  Trying to spin up the created db unsurprisingly results in 'db unavailable'.  Is this likely to be a memory issue solved with a bigger box or do I need to dig into the raw data?  Or is 6Bnodes / 13Brels just too big to import?

**Comment by rom-burner** [comment]
Well if it wasn't a cosmic bitflip, either throwing a 24xlarge at the import seems to have solved the problem (<10hrs for ref) or changing the record format from high_limit to standard now I know the number of properties isn't pushing the limits.  Peak memory usage on successful import reported as 80GB so not sure where the problem lies.  Issue can be closed unless there's any other insight.

**Comment by tinwelint** [comment]
Hi, I know the cause of this and it will be fixed asap. It's mostly a check in a specific case that got stricter w/o the import code adapting to that properly. It's not a serious thing, although obviously serious enough to fail your import. I'll notify you when a fix is ready.
