### ISSUE TITLE
neo4j-admin import: Unable to parse header when relationship attribute type is specified

### ISSUE THREAD

**Issue by filippomc** [neo4j/neo4j#12642]
When trying to assign attribute types to neo4j-admin headers in relationship I get an error "Unable to parse header".

- Neo4j version: 4.x.x (reproduced in 4.0.5 and 4.2.0)
- Operating system: Linux - Docker image
- API/Driver: neo4j-admin

## Expected behavior
Specifying relationship attributes in headers should work as in nodes: the attributed converted to the type specified and added to relationship.

## Actual behavior

I'm getting the following error:
```
org.neo4j.internal.batchimport.input.HeaderException: Unable to parse header
        at org.neo4j.internal.batchimport.input.csv.DataFactories.parsePropertyType(DataFactories.java:509)
        at org.neo4j.internal.batchimport.input.csv.DataFactories$AbstractDefaultFileHeaderParser.propertyExtractor(DataFactories.java:308)
        at org.neo4j.internal.batchimport.input.csv.DataFactories$DefaultRelationshipFileHeaderParser.entry(DataFactories.java:494)
        at org.neo4j.internal.batchimport.input.csv.DataFactories$AbstractDefaultFileHeaderParser.create(DataFactories.java:235)
        at org.neo4j.internal.batchimport.input.csv.CsvInput.verifyHeaders(CsvInput.java:148)
        at org.neo4j.internal.batchimport.input.csv.CsvInput.<init>(CsvInput.java:115)
        at org.neo4j.internal.batchimport.input.csv.CsvInput.<init>(CsvInput.java:95)
        at org.neo4j.importer.CsvImporter.doImport(CsvImporter.java:154)
        at org.neo4j.importer.ImportCommand.execute(ImportCommand.java:249)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:68)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:34)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at org.neo4j.cli.AdminTool.execute(AdminTool.java:79)
        at org.neo4j.cli.AdminTool.main(AdminTool.java:60)
Caused by: java.lang.IllegalArgumentException: 'VALUE'
        at org.neo4j.csv.reader.Extractors.valueOf(Extractors.java:192)
        at org.neo4j.internal.batchimport.input.csv.DataFactories.parsePropertyType(DataFactories.java:505)
        ... 19 more
The command '/bin/sh -c /var/lib/neo4j/run.sh' returned a non-zero code: 1
```

## Steps to reproduce 

In syntesis, specify a the attribute type when importing relationship attributes (I tried float).

The header being like
```
:START_ID(a-reference),:END_ID(b-reference),value:float,:TYPE
```
(notice that If I specify "value" rather than "value:float" in the header the import is successful).

The data being like
```
1058685,594,3.6157916807089787,PROBE_MEASUREMENT
1058685,2985,2.13807367935382,PROBE_MEASUREMENT
1058685,2801,2.4805415023588107,PROBE_MEASUREMENT
1058685,2273,2.96497183239022,PROBE_MEASUREMENT
1058685,2785,2.67980316976351,PROBE_MEASUREMENT
1058685,2793,1.8562381007421844,PROBE_MEASUREMENT
```

Command used like:
```
#! /bin/bash
neo4j-admin import  --relationships=import/relationships/my_header.csv,import/relationships/my.csv --skip-bad-relationships=true --multiline-fields=true
```

**Comment by filippomc** [comment]
closed: the error was related to other import files
