### ISSUE TITLE
import fails with IndexOutOfBoundsException in idmapping OffHeapByteArray

### ISSUE THREAD

**Issue by titanous** [neo4j/neo4j#12696]
When running `neo4j-admin import`, this error occurs during the node sort phase:

```
java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Wanted to access -1 but range is 0-58682014
        at org.neo4j.internal.batchimport.cache.idmapping.string.Workers.awaitAndThrowOnError(Workers.java:82)
        at org.neo4j.internal.batchimport.cache.idmapping.string.ParallelSort.run(ParallelSort.java:88)
        at org.neo4j.internal.batchimport.cache.idmapping.string.EncodingIdMapper.detectDuplicateInputIds(EncodingIdMapper.java:589)
        at org.neo4j.internal.batchimport.cache.idmapping.string.EncodingIdMapper.buildCollisionInfo(EncodingIdMapper.java:532)
        at org.neo4j.internal.batchimport.cache.idmapping.string.EncodingIdMapper.prepare(EncodingIdMapper.java:247)
        at org.neo4j.internal.batchimport.IdMapperPreparationStep.process(IdMapperPreparationStep.java:54)
        at org.neo4j.internal.batchimport.staging.LonelyProcessingStep.lambda$receive$0(LonelyProcessingStep.java:53)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IndexOutOfBoundsException: Wanted to access -1 but range is 0-58682014
        at org.neo4j.internal.batchimport.cache.OffHeapByteArray.checkBounds(OffHeapByteArray.java:328)
        at org.neo4j.internal.batchimport.cache.OffHeapByteArray.address(OffHeapByteArray.java:319)
        at org.neo4j.internal.batchimport.cache.OffHeapByteArray.get5ByteLong(OffHeapByteArray.java:173)
        at org.neo4j.internal.batchimport.cache.idmapping.string.EncodingIdMapper$2.get(EncodingIdMapper.java:671)
        at org.neo4j.internal.batchimport.cache.idmapping.string.ParallelSort$SortWorker.informedPivot(ParallelSort.java:363)
        at org.neo4j.internal.batchimport.cache.idmapping.string.ParallelSort$SortWorker.qsort(ParallelSort.java:332)
        at org.neo4j.internal.batchimport.cache.idmapping.string.ParallelSort$SortWorker.run(ParallelSort.java:270)
        at org.neo4j.internal.batchimport.cache.idmapping.string.Workers$Worker.run(Workers.java:126)
```

I'm importing a few hundred million nodes, with `--id-type=INTEGER`. I tried increasing the `HEAP_SIZE` to 70G, but the exact same error ocurred. 

**Neo4j Version:** 4.2.3
**Operating System:** Debian buster
**Java:** openjdk 11.0.10

Let me know if there's other information that would be helpful, I can also easily compile and run a patched version to get more debug output if you supply a patch. Thanks!

**Comment by tinwelint** [comment]
Thanks for reporting. First of all, would you mind trying the import without changing any CSV data and no arguments, exception instead using `--id-type=STRING`?

**Comment by tinwelint** [comment]
I'll see if I can hand you a patched version which could provide more insight

**Comment by tinwelint** [comment]
@titanous Did it work with --id-type=STRING?

**Comment by tinwelint** [comment]
@titanous I've gotten no response from you since reporting this in March. I cannot progress if there's no discussion and will close this issue
