### ISSUE TITLE
run in lustrefs?

### ISSUE THREAD

**Issue by zhanghaoipp** [neo4j/neo4j#12698]
- Neo4j version: neo4j-community-3.5.3
- Operating system: Centos7

The file system in my sever is lustrefs, when I run "neo4j console", it alsways showed error below. I checked the manual, NFS is nt recommended, does it mean lustrefs is not availible? I have not root access in the sever, is it any other way to run neo4j in this sever? Thank you very much!

Active database: graph.db
Directories in use:
  home:         /home/zhanghao/software/neo4j-community-3.5.3
  config:       /home/zhanghao/software/neo4j-community-3.5.3/conf
  logs:         /home/zhanghao/software/neo4j-community-3.5.3/logs
  plugins:      /home/zhanghao/software/neo4j-community-3.5.3/plugins
  import:       /home/zhanghao/software/neo4j-community-3.5.3/import
  data:         /home/zhanghao/software/neo4j-community-3.5.3/data
  certificates: /home/zhanghao/software/neo4j-community-3.5.3/certificates
  run:          /home/zhanghao/software/neo4j-community-3.5.3/run
Starting Neo4j.
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
2021-03-31 00:34:13.202+0000 INFO  ======== Neo4j 3.5.3 ========
2021-03-31 00:34:13.212+0000 INFO  Starting...
2021-03-31 00:34:14.862+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6ccdb29f' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: /home/zhanghao/software/neo4j-community-3.5.3/data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6ccdb29f' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: /home/zhanghao/software/neo4j-community-3.5.3/data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6ccdb29f' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: /home/zhanghao/software/neo4j-community-3.5.3/data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:184)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:123)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6ccdb29f' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: /home/zhanghao/software/neo4j-community-3.5.3/data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:177)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /home/zhanghao/software/neo4j-community-3.5.3/data/databases
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:216)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:135)
        at org.neo4j.server.database.CommunityGraphFactory.newGraphDatabase(CommunityGraphFactory.java:40)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:78)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter@1c93f6e1' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: /home/zhanghao/software/neo4j-community-3.5.3/data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
        ... 9 more
Caused by: org.neo4j.kernel.StoreLockException: Unable to obtain lock on store lock file: /home/zhanghao/software/neo4j-community-3.5.3/data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)
        at org.neo4j.kernel.internal.locker.StoreLocker.storeLockException(StoreLocker.java:116)
        at org.neo4j.kernel.internal.locker.StoreLocker.unableToObtainLockException(StoreLocker.java:109)
        at org.neo4j.kernel.internal.locker.StoreLocker.checkLock(StoreLocker.java:97)
        at org.neo4j.kernel.internal.locker.GlobalStoreLocker.checkLock(GlobalStoreLocker.java:61)
        at org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter.start(StoreLockerLifecycleAdapter.java:36)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 11 more
2021-03-31 00:34:14.864+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by mnd999** [comment]
For proper ACID behavior, the filesystem must support flush (fsync, fdatasync), as documented [here](https://neo4j.com/docs/operations-manual/current/installation/requirements/#deployment-requirements-filesystem).

I am not aware of any testing having been done on lustrefs, but do let us know if you have some success. Will close this for now as I think this answers the question, but do feel free to reopen if not. Or reach out on [our community forums](https://community.neo4j.com/) or on our [discord](https://discord.gg/neo4j) and you will likely get a faster response there. Github is more setup for bug reports in the product.
