### ISSUE TITLE
[Neo.ClientError.Statement.EntityNotFound]:Unable to load NODE with id -22.

### ISSUE THREAD

**Issue by varunsharma27** [neo4j/neo4j#12694]
Do you no longer support JDBC for latest Neo4j versions?
- Neo4j version: 4.2.3
- Operating system: Remote Paradise Papers by ICIJ from `sandbox.neo4j.com`
- Client OS: Ubuntu 18.04.4 LTS
- API/Driver: Neo4j JDBC Driver [v4.0.1](https://mvnrepository.com/artifact/org.neo4j/neo4j-jdbc-driver/4.0.1)
- **Steps to reproduce**
  - Use statement: `call db.schema.visualization()`
- Expected behavior
  - Response is received
- Actual behavior
  - `EntityNotFound` exception is thrown.

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.
```java
Caused by: java.sql.SQLException: Some errors occurred : 
[Neo.ClientError.Statement.EntityNotFound]:Unable to load NODE with id -22.

	at org.neo4j.jdbc.http.HttpNeo4jStatement.execute(HttpNeo4jStatement.java:58) ~[?:?]
	at org.neo4j.jdbc.http.HttpNeo4jStatement.executeQuery(HttpNeo4jStatement.java:42) ~[?:?]
	at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:111) ~[?:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
```

**Comment by conker84** [comment]
@varunsharma27 please switch to the jdbc bolt driver in order to overcome that problem

**Comment by conker84** [comment]
@varunsharma27 in order to use the bolt driver you must simply change the connection string from `http://` to `bolt://` or `neo4j://`

**Comment by varunsharma27** [comment]
Well, our connector is designed for Neo4j HttpDriver so bolt connection with `org.neo4j.jdbc.bolt.BoltDriver` causes a fair amount of issues. Would you recommend moving over to a bolt connection rather than http?

Using the `db.schema.visualization()` query:
```java
[2021-04-27T15:14:46,712][WARN ][r.suppressed             ] [siren-node] path: /_siren/connector/datasource/Neo4j%20Panama%20Remote/_sample, params: {id=Neo4j Panama Remote}
org.elasticsearch.ElasticsearchException: Could not execute the datasource query.
	at io.siren.federate.connector.i.w$2$1.onFailure(QueryService.java:355) ~[?:?]
	at io.siren.federate.connector.i.q$1.onFailure(JdbcQueryHandler.java:263) ~[?:?]
	at io.siren.federate.connector.i.q.b(JdbcQueryHandler.java:193) ~[?:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-7.9.2.jar:7.9.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: org.elasticsearch.ElasticsearchException: Could not execute datasource query [Neo4j Panama Remote].
	at io.siren.federate.connector.i.q$1.onFailure(JdbcQueryHandler.java:264) ~[?:?]
	... 5 more
Caused by: org.elasticsearch.ElasticsearchException: Error on JDBC column 1
	at io.siren.federate.connector.i.y.a(ResultSetProcessor.java:197) ~[?:?]
	at io.siren.federate.connector.i.y.a(ResultSetProcessor.java:239) ~[?:?]
	at io.siren.federate.connector.i.y.a(ResultSetProcessor.java:402) ~[?:?]
	at io.siren.federate.connector.i.w$2$1.a(QueryService.java:345) ~[?:?]
	at io.siren.federate.connector.i.w$2$1.onResponse(QueryService.java:338) ~[?:?]
	at io.siren.federate.connector.i.q$1.a(JdbcQueryHandler.java:258) ~[?:?]
	at io.siren.federate.connector.i.q$1.onResponse(JdbcQueryHandler.java:255) ~[?:?]
	at io.siren.federate.connector.i.q.b(JdbcQueryHandler.java:187) ~[?:?]
	... 4 more
Caused by: org.elasticsearch.ElasticsearchException: Non standard JDBC object value: node<-7>.
	at io.siren.federate.connector.i.r.d(JdbcTypeConverter.java:368) ~[?:?]
	at io.siren.federate.connector.i.r.a(JdbcTypeConverter.java:296) ~[?:?]
	at io.siren.federate.connector.i.r$a.a(JdbcTypeConverter.java:247) ~[?:?]
	at io.siren.federate.connector.i.y.a(ResultSetProcessor.java:195) ~[?:?]
	at io.siren.federate.connector.i.y.a(ResultSetProcessor.java:239) ~[?:?]
	at io.siren.federate.connector.i.y.a(ResultSetProcessor.java:402) ~[?:?]
	at io.siren.federate.connector.i.w$2$1.a(QueryService.java:345) ~[?:?]
	at io.siren.federate.connector.i.w$2$1.onResponse(QueryService.java:338) ~[?:?]
	at io.siren.federate.connector.i.q$1.a(JdbcQueryHandler.java:258) ~[?:?]
	at io.siren.federate.connector.i.q$1.onResponse(JdbcQueryHandler.java:255) ~[?:?]
	at io.siren.federate.connector.i.q.b(JdbcQueryHandler.java:187) ~[?:?]
	... 4 more
```

Validate Request (this ):
```java
[2021-04-27T15:07:54,665][INFO ][c.z.h.HikariDataSource   ] [siren-node] Neo4j Panama Remote-pool - Start completed.
[2021-04-27T15:08:03,924][WARN ][r.suppressed             ] [siren-node] path: /_siren/connector/datasource/Neo4j%20Panama%20Remote/_validate, params: {id=Neo4j Panama Remote}
org.elasticsearch.ElasticsearchException: Could not validate datasource [Neo4j Panama Remote].
	at io.siren.federate.connector.i.q.a(JdbcQueryHandler.java:316) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:71) ~[elasticsearch-7.9.2.jar:7.9.2]
	at io.siren.federate.connector.i.q.b(JdbcQueryHandler.java:193) ~[?:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-7.9.2.jar:7.9.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.sql.SQLException: org.neo4j.driver.exceptions.ClientException: Invalid input 'START': expected 
  "RETURN"
  "CREATE"
  "DELETE"
  "SET"
  "REMOVE"
  "DETACH"
  "MATCH"
  "WITH"
  "UNWIND"
  "USE"
  "CALL"
  "LOAD"
  "FROM"
  "FOREACH"
  "MERGE"
  "OPTIONAL"
  "USING" (line 1, column 1 (offset: 0))
"START n=NODE(*) MATCH (n) RETURN COUNT(n)"
 ^
	at org.neo4j.jdbc.bolt.BoltNeo4jUtils.executeInTx(BoltNeo4jUtils.java:67) ~[?:?]
	at org.neo4j.jdbc.bolt.BoltNeo4jUtils.executeInTx(BoltNeo4jUtils.java:74) ~[?:?]
	at org.neo4j.jdbc.bolt.BoltNeo4jStatement.executeInternal(BoltNeo4jStatement.java:102) ~[?:?]
	at org.neo4j.jdbc.bolt.BoltNeo4jStatement.executeQuery(BoltNeo4jStatement.java:65) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.neo4j.jdbc.utils.Neo4jInvocationHandler.invoke(Neo4jInvocationHandler.java:54) ~[?:?]
	at com.sun.proxy.$Proxy61.executeQuery(Unknown Source) ~[?:?]
	at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:111) ~[?:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at io.siren.federate.connector.i.u$1.a(QueryContext.java:233) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
	at io.siren.federate.connector.i.u$1.invoke(QueryContext.java:231) ~[?:?]
	at com.sun.proxy.$Proxy62.executeQuery(Unknown Source) ~[?:?]
	at io.siren.federate.connector.i.q.b(JdbcQueryHandler.java:186) ~[?:?]
	... 4 more
Caused by: org.neo4j.driver.exceptions.ClientException: Invalid input 'START': expected 
  "RETURN"
  "CREATE"
  "DELETE"
  "SET"
  "REMOVE"
  "DETACH"
  "MATCH"
  "WITH"
  "UNWIND"
  "USE"
  "CALL"
  "LOAD"
  "FROM"
  "FOREACH"
  "MERGE"
  "OPTIONAL"
  "USING" (line 1, column 1 (offset: 0))
"START n=NODE(*) MATCH (n) RETURN COUNT(n)"
 ^
	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:143) ~[?:?]
	at org.neo4j.driver.internal.InternalResult.blockingGet(InternalResult.java:128) ~[?:?]
	at org.neo4j.driver.internal.InternalResult.list(InternalResult.java:105) ~[?:?]
	at org.neo4j.jdbc.bolt.BoltNeo4jResultSet.<init>(BoltNeo4jResultSet.java:111) ~[?:?]
	at org.neo4j.jdbc.bolt.BoltNeo4jResultSet.newInstance(BoltNeo4jResultSet.java:142) ~[?:?]
	at org.neo4j.jdbc.bolt.BoltNeo4jStatement.lambda$executeQuery$0(BoltNeo4jStatement.java:66) ~[?:?]
	at org.neo4j.jdbc.bolt.BoltNeo4jUtils.executeInTx(BoltNeo4jUtils.java:60) ~[?:?]
	at org.neo4j.jdbc.bolt.BoltNeo4jUtils.executeInTx(BoltNeo4jUtils.java:74) ~[?:?]
	at org.neo4j.jdbc.bolt.BoltNeo4jStatement.executeInternal(BoltNeo4jStatement.java:102) ~[?:?]
	at org.neo4j.jdbc.bolt.BoltNeo4jStatement.executeQuery(BoltNeo4jStatement.java:65) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.neo4j.jdbc.utils.Neo4jInvocationHandler.invoke(Neo4jInvocationHandler.java:54) ~[?:?]
	at com.sun.proxy.$Proxy61.executeQuery(Unknown Source) ~[?:?]
	at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:111) ~[?:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at io.siren.federate.connector.i.u$1.a(QueryContext.java:233) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
	at io.siren.federate.connector.i.u$1.invoke(QueryContext.java:231) ~[?:?]
	at com.sun.proxy.$Proxy62.executeQuery(Unknown Source) ~[?:?]
	at io.siren.federate.connector.i.q.b(JdbcQueryHandler.java:186) ~[?:?]
	... 4 more
	Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause
		at org.neo4j.driver.internal.util.ErrorUtil.newNeo4jError(ErrorUtil.java:79) ~[?:?]
```

**Comment by conker84** [comment]
@varunsharma27 You cannot use the http driver to make that call because of the limitation of the HTTP endpoint.

Just remove `START n=NODE(*)` from your query

**Comment by gjmwoods** [comment]
Hi @varunsharma27. Since this one has been quiet for a while I will close it for now. Feel free to reopen if you need anything else.
