### ISSUE TITLE
neo4j.service: Main process exited, : java.lang.VerifyError: Cannot inherit from final class

### ISSUE THREAD

**Issue by maniappan** [neo4j/neo4j#12730]
Hi,
Neo4j fails to start after working for couple of days, no change in environment or plugins to Neo4j.

- Neo4j version: 4.1.9 Community edition
- Operating system: Ubuntu 20.04 on a 32GB AWS instance
- Open JDK 11

- **Steps to reproduce**
Installed using the debian package. Service was working fine for couple of days after installation. We started ingesting data and suddenly stopped working. 
Error in syslog
***
May 27 16:03:53 ip-172-31-xx-yyy neo4j[82025]: #011at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:117)
May 27 16:03:53 ip-172-31-xx-yyy neo4j[82025]: #011at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:87)
May 27 16:03:53 ip-172-31-xx-yyy neo4j[82025]: #011at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:35)
May 27 16:03:53 ip-172-31-xx-yyy neo4j[82025]: Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.procedure.impl.GlobalProceduresRegistry@3872bc37' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
May 27 16:03:53 ip-172-31-xx-yyy neo4j[82025]: #011at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:463)
May 27 16:03:53 ip-172-31-xx-yyy neo4j[82025]: #011at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110)
May 27 16:03:53 ip-172-31-xx-yyy neo4j[82025]: #011at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:189)
May 27 16:03:53 ip-172-31-xx-yyy neo4j[82025]: #011... 5 more
May 27 16:03:53 ip-172-31-xx-yyy neo4j[82025]: Caused by: java.lang.VerifyError: Cannot inherit from final class
May 27 16:03:53 ip-172-31-xx-yyy neo4j[82025]: #011at java.base/java.lang.ClassLoader.defineClass1(Native Method)
***

Searched all over, couldn't get any reason, hence this report. Please let know if you need any more information..

**Comment by tinwelint** [comment]
I don't see information about which class this is about, but it has to be some environment change, i.e. some version changed or JDK or the classpath.

**Comment by maniappan** [comment]
We didn't change anything, we just ran it with the add-on's and service stopped, anyway we are past it. Since we didn't any response for this issue in realistic time frame, we have put this DB on standby due to stability reason and went ahead evaluating another one..

Mani.
________________________________

**Comment by Roxling** [comment]
@maniappan The exception ` java.lang.VerifyError: Cannot inherit from final class` thrown from inside the classloader (`java.lang.ClassLoader`) shows that its an issue with incompatible jar files. The component inside Neo4j crashing, the `GlobalProceduresRegistry` is loading any custom plugins and procedures. It is very likely that there is an installed plugin (like apoc or similar) that is compiled against a different version of Neo4j than the one you are using.

**Comment by Roxling** [comment]
Closing due to inactivity

**Comment by eidens** [comment]
@Roxling Here's a minimal working example where the neo4j docker image fails to start with the stacktrace in the original report:

```bash
docker run -it --rm --env NEO4JLABS_PLUGINS='["apoc", "n10s"]' neo4j:4.1
```

It seems to be the specific combination of neo4j:4.1 and the two plugins, apoc & n10s. Change the neo4j image version or remove one of the plugins and it works. The detailed versions are neo4j @ 4.1.10, apoc @ 4.1.0.10 & n10s @ 4.1.0.1 (as seen in the logs below).




Here's the output for the above command:

```
Fetching versions.json for Plugin 'apoc' from https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json
Installing Plugin 'apoc' from https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.1.0.10/apoc-4.1.0.10-all.jar to /var/lib/neo4j/plugins/apoc.jar
Applying default values for plugin apoc to neo4j.conf
Fetching versions.json for Plugin 'n10s' from https://neo4j-labs.github.io/neosemantics/versions.json
Installing Plugin 'n10s' from https://github.com/neo4j-labs/neosemantics/releases/download/4.1.0.1/neosemantics-4.1.0.1.jar to /var/lib/neo4j/plugins/n10s.jar
Applying default values for plugin n10s to neo4j.conf
Directories in use:
  home:         /var/lib/neo4j
  config:       /var/lib/neo4j/conf
  logs:         /logs
  plugins:      /var/lib/neo4j/plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/lib/neo4j/run
Starting Neo4j.
2021-10-04 07:36:48.732+0000 INFO  Starting...
2021-10-04 07:36:50.512+0000 INFO  ======== Neo4j 4.1.10 ========
2021-10-04 07:37:05.448+0000 ERROR Failed to start Neo4j on dbms.connector.http.listen_address, a socket address. If missing port or hostname it is acquired from dbms.default_listen_address. Error starting Neo4j database server at /data/databases
java.lang.RuntimeException: Error starting Neo4j database server at /data/databases
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:198)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:158)
	at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36)
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:117)
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:87)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:35)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.procedure.impl.GlobalProceduresRegistry@93f432e' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:463)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:189)
	... 5 more
Caused by: java.lang.VerifyError: Cannot inherit from final class
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:576)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.neo4j.procedure.impl.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:160)
	at org.neo4j.procedure.impl.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:138)
	at org.neo4j.collection.AbstractPrefetchingRawIterator.peek(AbstractPrefetchingRawIterator.java:50)
	at org.neo4j.collection.AbstractPrefetchingRawIterator.hasNext(AbstractPrefetchingRawIterator.java:36)
	at org.neo4j.procedure.impl.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:111)
	at org.neo4j.procedure.impl.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:85)
	at org.neo4j.procedure.impl.GlobalProceduresRegistry.start(GlobalProceduresRegistry.java:342)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:442)
	... 7 more
2021-10-04 07:37:05.449+0000 INFO  Neo4j Server shutdown initiated by request
```

**Comment by Roxling** [comment]
@eidens Hello! This is not an issue with neo4j, but an incompatibility between those two plugins. Apparently they both depend on (different versions of) `com.google.common.collect.BoundType`. I've reached out to the maintainers of those plugins to and notified them of this issue. If you want you can open issues on the plugins corresponding repositories https://github.com/neo4j-labs/neosemantics/ & https://github.com/neo4j-contrib/neo4j-apoc-procedures
