### ISSUE TITLE
Neo4jError: Connection was closed by server 

### ISSUE THREAD

**Issue by tatva122** [neo4j/neo4j#12749]
I am getting connection was close by server error in some time of intervals.

Here is Node JS console logs.
###Query
MATCH (rbs0:test_Struct {test_struct_id: "Object"})
CALL {
  WITH rbs0
  CALL apoc.path.expandConfig(rbs0, {relationshipFilter: "HAS_TEST_STRUCT_CHILD>"})
      YIELD path
      CALL {
          WITH path
          WITH nodes(path)[-1] AS rbs
          MATCH (rbs)-[:HAS_TEST_STRUCT_STATE]->(rbss:test_Struct_State)
          CALL {
              WITH rbss
              MATCH (rbss)-[:TEST_STRUCT_LANGUAGE_IS]->(lang:Language)
              RETURN lang
          }
        WITH rbss, lang
        RETURN collect(rbss {.test_struct_desc, language: lang.iso_639_1}) AS res_desc_lang
      }
    WITH path, nodes(path) AS n, res_desc_lang, apoc.text.rpad(reduce(a = "", r in relationships(path) | a + apoc.text.lpad(toString(COALESCE(r.order_test_struct,0)),4,"0")),100,"0") AS orders
      CALL {
          WITH n
          WITH n[-1] AS m
          MATCH (m)<-[r1:TEST_BELONGS_TO_STRUCT]-(rb:test)
          WITH rb, rb {.test_id, .test_active} AS rb2 order by r1.order_test_in_struct
          CALL {
              WITH rb
              CALL apoc.path.expandConfig(rb, {relationshipFilter: "HAS_TEST_CHILD>"})
              YIELD path
              CALL {
                WITH path
                WITH nodes(path)[-1] as rb
                MATCH (rb)-[:HAS_TEST_ISSUE]->(rbi:test_Issue)
                WITH rbi ORDER BY rbi.test_issue_no
                CALL {
                  WITH rbi
                  MATCH (rbi)-[:HAS_TEST_ISSUE_STATE]->(rbis:test_Issue_State)-[:TEST_ISSUE_LANGUAGE_IS]->(lang:Language)
                  RETURN rbis, lang
                }
                CALL {
                  WITH rbi
                  OPTIONAL MATCH (rbi)-[:HAS_TEST_TAG]->(rbt:test_Tag)
                  RETURN collect(replace(rbt.test_tag_id, "/", "-") ) as rbTags
                }
              RETURN collect(rbi {.test_issue_no, title_short: rbis.test_issue_title_short, title_popular:rbis.test_issue_popular_title, title_long: rbis.test_issue_title_long, language: lang.iso_639_1, label: labels(rbi), tags: rbTags}) AS res_rbi
            }
          WITH path, nodes(path) AS n, res_rbi, apoc.text.rpad(reduce(a = "", r in relationships(path) | a + apoc.text.lpad(toString(COALESCE(r.order_test_child,0)),4,"0")),100,"0") AS orders
          RETURN n[-1] AS res_rbs, n[-2] AS res_rbs_parent, res_rbi ORDER BY orders
        }
      RETURN collect(res_rbs {.test_id, .test_active, test_parent_id: res_rbs_parent.test_id, res_rbi, label: labels(res_rbs)}) AS rbs_res
    }
  RETURN n[-1] AS res_rbss, n[-2] AS res_rbss_parent, res_desc_lang, rbs_res ORDER BY orders
}
RETURN res_rbss {.test_struct_id, .test_struct_active, test_struct_parent_id: res_rbss_parent.test_struct_id, res_desc_lang, label: labels(res_rbss)} AS rbss_res, rbs_res

Get rule book error Neo4jError: Connection was closed by server

    at captureStacktrace (D:\Projects\example-project\node_modules\neo4j-driver\lib\result.js:277:15)
    at new Result (D:\Projects\example-project\node_modules\neo4j-driver\lib\result.js:68:19)
    at Session._run (D:\Projects\example-project\node_modules\neo4j-driver\lib\session.js:174:14)
    at Session.run (D:\Projects\example-project\node_modules\neo4j-driver\lib\session.js:135:19)
    at module.exports (D:\Projects\example-project\src\graphql\resolver\rule-book-structure\get-rule-book-structure.js:256:34)
    at module.exports (D:\Projects\example-project\src\graphql\resolver\rule-book\get-rule-book.js:252:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'SessionExpired',
  name: 'Neo4jError'
}
Neo4jError: Connection was closed by server

    at captureStacktrace (D:\Projects\example-project\node_modules\neo4j-driver\lib\result.js:277:15)
    at new Result (D:\Projects\example-project\node_modules\neo4j-driver\lib\result.js:68:19)
    at Session._run (D:\Projects\example-project\node_modules\neo4j-driver\lib\session.js:174:14)
    at Session.run (D:\Projects\example-project\node_modules\neo4j-driver\lib\session.js:135:19)
    at module.exports (D:\Projects\example-project\src\graphql\resolver\rule-book-structure\get-rule-book-structure.js:256:34)
    at module.exports (D:\Projects\example-project\src\graphql\resolver\rule-book\get-rule-book.js:252:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  originalMessage: 'Connection was closed by server',
  message: 'Error in resolver Query.getRuleBook\nConnection was closed by server'
}
Get rule book error Neo4jError: Connection was closed by server

    at captureStacktrace (D:\Projects\example-project\node_modules\neo4j-driver\lib\result.js:277:15)
    at new Result (D:\Projects\example-project\node_modules\neo4j-driver\lib\result.js:68:19)
    at Session._run (D:\Projects\example-project\node_modules\neo4j-driver\lib\session.js:174:14)
    at Session.run (D:\Projects\example-project\node_modules\neo4j-driver\lib\session.js:135:19)
    at module.exports (D:\Projects\example-project\src\graphql\resolver\rule-book-structure\get-rule-book-structure.js:256:34)
    at module.exports (D:\Projects\example-project\src\graphql\resolver\rule-book\get-rule-book.js:252:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'SessionExpired',
  name: 'Neo4jError'
}
Neo4jError: Connection was closed by server

    at captureStacktrace (D:\Projects\example-project\node_modules\neo4j-driver\lib\result.js:277:15)
    at new Result (D:\Projects\example-project\node_modules\neo4j-driver\lib\result.js:68:19)
    at Session._run (D:\Projects\example-project\node_modules\neo4j-driver\lib\session.js:174:14)
    at Session.run (D:\Projects\example-project\node_modules\neo4j-driver\lib\session.js:135:19)
    at module.exports (D:\Projects\example-project\src\graphql\resolver\rule-book-structure\get-rule-book-structure.js:256:34)
    at module.exports (D:\Projects\example-project\src\graphql\resolver\rule-book\get-rule-book.js:252:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  originalMessage: 'Connection was closed by server',
  message: 'Error in resolver Query.getRuleBook\nConnection was closed by server'
}
Get rule book error Neo4jError: Connection was closed by server

    at captureStacktrace (D:\Projects\example-project\node_modules\neo4j-driver\lib\result.js:277:15)
    at new Result (D:\Projects\example-project\node_modules\neo4j-driver\lib\result.js:68:19)
    at Session._run (D:\Projects\example-project\node_modules\neo4j-driver\lib\session.js:174:14)
    at Session.run (D:\Projects\example-project\node_modules\neo4j-driver\lib\session.js:135:19)
    at module.exports (D:\Projects\example-project\src\graphql\resolver\rule-book-structure\get-rule-book-structure.js:256:34)
    at module.exports (D:\Projects\example-project\src\graphql\resolver\rule-book\get-rule-book.js:252:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'SessionExpired',
  name: 'Neo4jError'
}
Neo4jError: Connection was closed by server

    at captureStacktrace (D:\Projects\example-project\node_modules\neo4j-driver\lib\result.js:277:15)
    at new Result (D:\Projects\example-project\node_modules\neo4j-driver\lib\result.js:68:19)
    at Session._run (D:\Projects\example-project\node_modules\neo4j-driver\lib\session.js:174:14)
    at Session.run (D:\Projects\example-project\node_modules\neo4j-driver\lib\session.js:135:19)
    at module.exports (D:\Projects\example-project\src\graphql\resolver\rule-book-structure\get-rule-book-structure.js:256:34)
    at module.exports (D:\Projects\example-project\src\graphql\resolver\rule-book\get-rule-book.js:252:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  originalMessage: 'Connection was closed by server',
  message: 'Error in resolver Query.getRuleBook\nConnection was closed by server'
}
Get rule book error Neo4jError: Connection was closed by server

    at captureStacktrace (D:\Projects\example-project\node_modules\neo4j-driver\lib\result.js:277:15)
    at new Result (D:\Projects\example-project\node_modules\neo4j-driver\lib\result.js:68:19)
    at Session._run (D:\Projects\example-project\node_modules\neo4j-driver\lib\session.js:174:14)
    at Session.run (D:\Projects\example-project\node_modules\neo4j-driver\lib\session.js:135:19)
    at module.exports (D:\Projects\example-project\src\graphql\resolver\rule-book-structure\get-rule-book-structure.js:267:43)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (D:\Projects\example-project\src\graphql\resolver\rule-book\get-rule-book.js:252:29) {
  code: 'SessionExpired',
  name: 'Neo4jError'
}
Neo4jError: Connection was closed by server

    at captureStacktrace (D:\Projects\example-project\node_modules\neo4j-driver\lib\result.js:277:15)
    at new Result (D:\Projects\example-project\node_modules\neo4j-driver\lib\result.js:68:19)
    at Session._run (D:\Projects\example-project\node_modules\neo4j-driver\lib\session.js:174:14)
    at Session.run (D:\Projects\example-project\node_modules\neo4j-driver\lib\session.js:135:19)
    at module.exports (D:\Projects\example-project\src\graphql\resolver\rule-book-structure\get-rule-book-structure.js:267:43)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (D:\Projects\example-project\src\graphql\resolver\rule-book\get-rule-book.js:252:29) {
  originalMessage: 'Connection was closed by server',
  message: 'Error in resolver Query.getRuleBook\nConnection was closed by server'
}
 
- Neo4j version: 4.2.0 (Enterprise)
- Operating system: (Ubuntu 16.04)
- API/Driver: (neo4j-driver v4.0.2)

**Comment by gjmwoods** [comment]
Hi @tatva122, The most common cause for seeing this error is if your connection gets interrupted whilst a query is running. We recommend that you use transaction functions: https://neo4j.com/docs/javascript-manual/current/session-api/#js-driver-async-transaction-fn. Using these will allow your transactions to be retried if the connection drops. (For more background see: https://medium.com/neo4j/try-and-then-retry-there-can-be-failure-30bf336383da).

**Comment by gjmwoods** [comment]
Closing due to inactivity. Please reopen if the issue still persists.
