### ISSUE TITLE
Failed to write value Path

### ISSUE THREAD

**Issue by ka1n4t** [neo4j/neo4j#12751]
Hi, I got the following error when I used `call apoc.algo.allSimplePaths()` to query.

```
2021-07-27 09:39:52.418+0000 WARN  [o.n.b.t.p.HouseKeeper] Fatal error occurred when handling a client connection, remote peer unexpectedly closed connection: [id: 0x9b3b6d22, L:/127.0.0.1:11022 - R:/127.0.0.1:54741]
2021-07-27 09:39:52.422+0000 ERROR [o.n.b.v.m.BoltResponseMessageWriterV3] Failed to write value Path{(233621)-[816926]-(236777)-[376977]-(152519)-[818538]-(174873)-[391965]-(64323)-[841776]-(246667)-[297301]-(256762)-[780039]-(162247)-[770017]-(12484)} because: The transaction has been closed.
2021-07-27 09:39:52.422+0000 ERROR [o.n.b.r.s.i.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.Statement.ExecutionFailed]: The transaction has been closed., reference 10bfa615-0c23-41f9-bbf4-29296b71e32d.
2021-07-27 09:39:52.422+0000 ERROR [o.n.b.r.s.i.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.Statement.ExecutionFailed]: The transaction has been closed., reference 10bfa615-0c23-41f9-bbf4-29296b71e32d.
org.neo4j.fabric.executor.FabricException: The transaction has been closed.
    at org.neo4j.fabric.executor.Exceptions.transform(Exceptions.java:51) ~[neo4j-fabric-4.2.1.jar:4.2.1]
    at org.neo4j.fabric.bolt.BoltQueryExecutionImpl$QueryExecutionImpl.request(BoltQueryExecutionImpl.java:204) ~[neo4j-fabric-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.runtime.AbstractCypherAdapterStream.handleRecords(AbstractCypherAdapterStream.java:104) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.v3.messaging.ResultHandler.onPullRecords(ResultHandler.java:41) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.v4.messaging.PullResultConsumer.consume(PullResultConsumer.java:42) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine$State.consumeResult(TransactionStateMachine.java:511) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine$State$2.streamResult(TransactionStateMachine.java:355) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine.streamResult(TransactionStateMachine.java:94) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.v4.runtime.InTransactionState.processStreamResultMessage(InTransactionState.java:73) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.v4.runtime.AbstractStreamingState.processUnsafe(AbstractStreamingState.java:49) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.v4.runtime.InTransactionState.processUnsafe(InTransactionState.java:60) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.runtime.statemachine.impl.AbstractBoltStateMachine.nextState(AbstractBoltStateMachine.java:143) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.runtime.statemachine.impl.AbstractBoltStateMachine.process(AbstractBoltStateMachine.java:91) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:90) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.runtime.DefaultBoltConnection.lambda$enqueue$0(DefaultBoltConnection.java:147) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatchInternal(DefaultBoltConnection.java:236) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:171) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:161) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.runtime.scheduling.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:246) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.runtime.scheduling.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$3(ExecutorBoltScheduler.java:229) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.53.Final.jar:4.1.53.Final]
    at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.neo4j.graphdb.NotInTransactionException: The transaction has been closed.
    at org.neo4j.kernel.impl.coreapi.TransactionImpl.checkInTransaction(TransactionImpl.java:711) ~[neo4j-kernel-4.2.1.jar:4.2.1]
    at org.neo4j.kernel.impl.coreapi.TransactionImpl.kernelTransaction(TransactionImpl.java:592) ~[neo4j-kernel-4.2.1.jar:4.2.1]
    at org.neo4j.kernel.impl.core.NodeEntity.getLabels(NodeEntity.java:620) ~[neo4j-kernel-4.2.1.jar:4.2.1]
    at org.neo4j.kernel.impl.util.NodeEntityWrappingNodeValue.labels(NodeEntityWrappingNodeValue.java:145) ~[neo4j-kernel-4.2.1.jar:4.2.1]
    at org.neo4j.kernel.impl.util.NodeEntityWrappingNodeValue.writeTo(NodeEntityWrappingNodeValue.java:69) ~[neo4j-kernel-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.packstream.Neo4jPackV1$PackerV1.writeNodesForPath(Neo4jPackV1.java:267) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.packstream.Neo4jPackV1$PackerV1.writePath(Neo4jPackV1.java:211) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.values.virtual.PathValue.writeTo(PathValue.java:77) ~[neo4j-values-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.packstream.Neo4jPackV1$PackerV1.pack(Neo4jPackV1.java:115) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.v3.messaging.encoder.RecordMessageEncoder.onField(RecordMessageEncoder.java:53) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.v3.messaging.BoltResponseMessageWriterV3.consumeField(BoltResponseMessageWriterV3.java:156) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.v41.messaging.BoltResponseMessageWriterV41.consumeField(BoltResponseMessageWriterV41.java:111) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.v3.messaging.ResultHandler$RecordWritingBoltResultRecordConsumer.consumeField(ResultHandler.java:67) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.bolt.runtime.statemachine.impl.BoltAdapterSubscriber.onField(BoltAdapterSubscriber.java:55) ~[neo4j-bolt-4.2.1.jar:4.2.1]
    at org.neo4j.fabric.bolt.BoltQueryExecutionImpl$QueryExecutionImpl.publishFields(BoltQueryExecutionImpl.java:212) ~[neo4j-fabric-4.2.1.jar:4.2.1]
    at org.neo4j.fabric.bolt.BoltQueryExecutionImpl$QueryExecutionImpl.request(BoltQueryExecutionImpl.java:189) ~[neo4j-fabric-4.2.1.jar:4.2.1]
    ... 24 more

```

And my neo4j browser turns gray:

![image](https://user-images.githubusercontent.com/22983012/127133782-c5b81fc6-2723-4a3f-858b-0239932524d5.png)

**Comment by mnd999** [comment]
It looks like from the logs, that the browser is disconnecting from the server, so moving this one to browser for now.
