### ISSUE TITLE
Neo4j 4.3.4 Build failure with org.apache.maven.surefire.booter.SurefireBooterForkException

### ISSUE THREAD

**Issue by xxks-kkk** [neo4j/neo4j#12777]
Build Neo4j 4.3.4 with the latest commit 

```
commit 6026ed4d1aa570004132801d2ffd8b00d6527ccb (HEAD, tag: 4.3.4)
Author: Mattias Finné <mattias@neotechnology.com>
Date:   Fri Sep 17 15:46:29 2021 +0200

    Rebuilds counts store on mismatching txId after recovery
    
    If there would be a mismatch between the highest txId
    that has been seen by the counts store and that of the meta data store
    after recovery then trigger a rebuild of the count store.
```
has the following error

```
[WARNING] Tests run: 851, Failures: 0, Errors: 0, Skipped: 8
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:verify (verify) @ bolt-it ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Neo4j 4.3.4-SNAPSHOT:
[INFO] 
[INFO] Neo4j - Build resources ............................ SUCCESS [  0.314 s]
[INFO] Neo4j .............................................. SUCCESS [  0.879 s]
[INFO] Neo4j - Annotation processors ...................... SUCCESS [  2.878 s]
[INFO] Zstandard .......................................... SUCCESS [  0.066 s]
[INFO] Neo4j - Common ..................................... SUCCESS [  4.699 s]
[INFO] Neo4j - Unsafe Access .............................. SUCCESS [  1.218 s]
[INFO] Neo4j - Native ..................................... SUCCESS [  0.800 s]
[INFO] Neo4j - Concurrent ................................. SUCCESS [  3.630 s]
[INFO] Neo4j - IO ......................................... SUCCESS [  2.725 s]
[INFO] Neo4j - Token API .................................. SUCCESS [  1.388 s]
[INFO] Neo4j - Locking .................................... SUCCESS [  0.954 s]
[INFO] Neo4j - Resource interface ......................... SUCCESS [  0.168 s]
[INFO] Neo4j - Collections ................................ SUCCESS [  2.223 s]
[INFO] Neo4j - Graph Database API ......................... SUCCESS [  1.406 s]
[INFO] Neo4j - Exceptions ................................. SUCCESS [  0.934 s]
[INFO] Neo4j - Value ...................................... SUCCESS [  4.361 s]
[INFO] Neo4j - Testing Utils Parent ....................... SUCCESS [  0.031 s]
[INFO] Neo4j - Test utilities ............................. SUCCESS [  2.515 s]
[INFO] Neo4j - Random Value ............................... SUCCESS [  1.546 s]
[INFO] Neo4j - Schema ..................................... SUCCESS [  1.666 s]
[INFO] Neo4j - Test IO utilities .......................... SUCCESS [  4.213 s]
[INFO] Neo4j - Logging .................................... SUCCESS [  1.097 s]
[INFO] Neo4j - Test logging utilities ..................... SUCCESS [  0.260 s]
[INFO] Neo4j - Configuration .............................. SUCCESS [  4.884 s]
[INFO] Neo4j - Layout ..................................... SUCCESS [  0.198 s]
[INFO] Neo4j - Diagnostics ................................ SUCCESS [  0.170 s]
[INFO] Neo4j - Native index ............................... SUCCESS [ 55.515 s]
[INFO] Neo4j - ID Generator ............................... SUCCESS [  7.520 s]
[INFO] Neo4j - Monitoring ................................. SUCCESS [  1.257 s]
[INFO] Neo4j - Storage Engine API ......................... SUCCESS [  1.464 s]
[INFO] Neo4j - CSV reading and parsing .................... SUCCESS [  4.799 s]
[INFO] Neo4j - Import Utilities ........................... SUCCESS [ 23.324 s]
[INFO] Neo4j - Storage Engine Test Utilities .............. SUCCESS [  0.166 s]
[INFO] Neo4j - Write-Ahead Log ............................ SUCCESS [  1.295 s]
[INFO] Neo4j - Procedure API .............................. SUCCESS [  0.219 s]
[INFO] Neo4j - Kernel API ................................. SUCCESS [  1.736 s]
[INFO] Neo4j - Test Batch Import utilities ................ SUCCESS [  0.231 s]
[INFO] Neo4j - Database Layout API utilities .............. SUCCESS [  1.363 s]
[INFO] Neo4j - Record storage engine ...................... SUCCESS [ 22.573 s]
[INFO] Neo4j - Native Spatial Index ....................... SUCCESS [ 19.471 s]
[INFO] Neo4j - Lucene Index ............................... SUCCESS [01:09 min]
[INFO] Neo4j - Fulltext index ............................. SUCCESS [  1.544 s]
[INFO] Neo4j - Test kernel API utilities .................. SUCCESS [  0.240 s]
[INFO] Neo4j - Write-Ahead Logging Test Utilities ......... SUCCESS [  0.165 s]
[INFO] Neo4j - Graph Database Kernel ...................... SUCCESS [ 31.627 s]
[INFO] Neo4j - Community Cypher Build ..................... SUCCESS [  0.132 s]
[INFO] openCypher Front End Parent ........................ SUCCESS [  0.030 s]
[INFO] openCypher Utils ................................... SUCCESS [ 11.603 s]
[INFO] Neo4j - Cypher Configuration ....................... SUCCESS [  8.195 s]
[INFO] Neo4j - Code Generator ............................. SUCCESS [ 17.252 s]
[INFO] openCypher Expressions ............................. SUCCESS [  8.415 s]
[INFO] openCypher AST for the Cypher Query Language ....... SUCCESS [ 18.250 s]
[INFO] Neo4j - Cypher AST factory ......................... SUCCESS [  1.143 s]
[INFO] Neo4j - Cypher JavaCC based parser ................. SUCCESS [  4.098 s]
[INFO] openCypher Parser .................................. SUCCESS [ 35.698 s]
[INFO] Neo4j - Neo4j/OpenCypher AST factory ............... SUCCESS [ 13.858 s]
[INFO] openCypher Rewriting ............................... SUCCESS [ 14.331 s]
[INFO] Neo4j - Cypher Macros .............................. SUCCESS [  4.915 s]
[INFO] openCypher Front End ............................... SUCCESS [ 20.346 s]
[INFO] Neo4j - Cypher Intermediate Representation ......... SUCCESS [ 10.493 s]
[INFO] Neo4j - Cypher Logical Plans ....................... SUCCESS [ 12.143 s]
[INFO] Neo4j - Cypher Planner SPI ......................... SUCCESS [  2.792 s]
[INFO] Neo4j - Cypher Runtime Utilities ................... SUCCESS [ 13.787 s]
[INFO] Neo4j - Graph Algorithms ........................... SUCCESS [  1.642 s]
[INFO] Neo4j - Cypher Interpreted Runtime ................. SUCCESS [ 33.590 s]
[INFO] Neo4j - Cypher Expression Evaluator ................ SUCCESS [  6.073 s]
[INFO] Neo4j - Cypher Logical Plan Builder ................ SUCCESS [ 27.151 s]
[INFO] Neo4j - Cypher Planner ............................. SUCCESS [01:12 min]
[INFO] Neo4j - Cypher ..................................... SUCCESS [ 29.576 s]
[INFO] Neo4j - SSL ........................................ SUCCESS [  2.036 s]
[INFO] Neo4j - Buffers .................................... SUCCESS [  1.000 s]
[INFO] Neo4j - Command Line ............................... SUCCESS [  0.270 s]
[INFO] Neo4j - Database Management System ................. SUCCESS [  2.561 s]
[INFO] Neo4j - Security ................................... SUCCESS [  4.016 s]
[INFO] Neo4j - Bolt Protocol Version 1 .................... SUCCESS [ 14.947 s]
[INFO] Neo4j - Fabric ..................................... SUCCESS [ 15.357 s]
[INFO] Neo4j - Capabilities ............................... SUCCESS [  1.651 s]
[INFO] Neo4j - Community Procedures ....................... SUCCESS [  5.999 s]
[INFO] Neo4j - Data Collector ............................. SUCCESS [  5.614 s]
[INFO] Neo4j - Consistency Checker ........................ SUCCESS [  2.799 s]
[INFO] Neo4j - Legacy Batch Inserter ...................... SUCCESS [  1.398 s]
[INFO] Neo4j - Import Command Line Tool ................... SUCCESS [  3.546 s]
[INFO] Neo4j - Server API ................................. SUCCESS [  1.150 s]
[INFO] Neo4j - Server ..................................... SUCCESS [  7.204 s]
[INFO] Neo4j - Community .................................. SUCCESS [ 18.177 s]
[INFO] Neo4j - Procedure Compiler Core .................... SUCCESS [ 10.935 s]
[INFO] Neo4j - Community Integration Tests ................ SUCCESS [  0.023 s]
[INFO] Neo4j - Community Integration Test Support ......... SUCCESS [  4.981 s]
[INFO] Neo4j - Test Harness ............................... SUCCESS [03:39 min]
[INFO] Neo4j - Procedure Compiler Parent POM .............. SUCCESS [  0.019 s]
[INFO] Neo4j - Procedure Compiler Integration Tests ....... SUCCESS [ 11.547 s]
[INFO] Neo4j - Community (Bill of Materials) .............. SUCCESS [  0.240 s]
[INFO] Neo4j - Record Storage Engine Integration Tests .... SUCCESS [ 12.722 s]
[INFO] Neo4j - Community Kernel Integration Tests ......... SUCCESS [06:43 min]
[INFO] Neo4j - Legacy Batch Inserter Integration Tests .... SUCCESS [ 22.360 s]
[INFO] Neo4j - Community Index Integration Tests .......... SUCCESS [02:16 min]
[INFO] Neo4j - Community Import Integration Tests ......... SUCCESS [ 55.856 s]
[INFO] Neo4j - Community DBMS Integration Tests ........... SUCCESS [ 21.810 s]
[INFO] Neo4j - Community Graph Algorithms Integration Tests SUCCESS [ 30.993 s]
[INFO] Neo4j - Community Consistency Checker Integration Tests SUCCESS [01:35 min]
[INFO] Neo4j - Community Bolt Integration Tests ........... FAILURE [08:39 min]
[INFO] Neo4j - Community Generic Integration Tests ........ SKIPPED
[INFO] Neo4j - Community Fabric Integration Tests ......... SKIPPED
[INFO] Neo4j - Community Security Integration Tests ....... SKIPPED
[INFO] Neo4j - Cypher ..................................... SKIPPED
[INFO] Neo4j - Community Cypher Integration Tests ......... SKIPPED
[INFO] Neo4j - Push To Cloud - Admin command .............. SKIPPED
[INFO] Neo4j - Cypher Specification Suite Tools ........... SKIPPED
[INFO] Neo4j - Cypher Acceptance .......................... SKIPPED
[INFO] Neo4j - Cypher Compatibility Specification Suite ... SKIPPED
[INFO] Neo4j - Cypher Logical Plan Generator .............. SKIPPED
[INFO] Neo4j - Cypher Runtime Acceptance .................. SKIPPED
[INFO] Neo4j - Cypher Literal Interpreter ................. SKIPPED
[INFO] Neo4j - Cypher Shell Parent ........................ SKIPPED
[INFO] Neo4j - Cypher Shell ............................... SKIPPED
[INFO] Neo4j - Cypher Shell Integration Test .............. SKIPPED
[INFO] Neo4j - Community Build ............................ SKIPPED
[INFO] Neo4j - Server Assembler ........................... SKIPPED
[INFO] Neo4j - Community Server Assembler ................. SKIPPED
[INFO] Neo4j - Packaging Build ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  38:11 min
[INFO] Finished at: 2021-10-04T16:54:44-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.2:verify (verify) on project bolt-it: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/zeyuanhu/projects/neo4j/community/community-it/bolt-it/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/zeyuanhu/projects/neo4j/community/community-it/bolt-it && /usr/lib/jvm/java-11-openjdk-amd64/bin/java -Xmx2G -XX:+UseG1GC -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:+ExitOnOutOfMemoryError -XX:MaxInlineLevel=15 -XX:-UseBiasedLocking -Djdk.nio.maxCachedBufferSize=262144 -Dlog4j2.disable.jmx=true -Dio.netty.tryReflectionSetAccessible=true '-XX:HeapDumpPath=target/test data' -Dorg.neo4j.internal.unsafe.UnsafeUtil.DIRTY_MEMORY=true -Dorg.neo4j.test.extension.ThreadLeakageGuardExtension.PRINT_ONLY=false -Dorg.neo4j.test.extension.ThreadLeakageGuardExtension.MAXIMUM_WAIT_TIME_MILLIS=90000 -Dorg.neo4j.internal.unsafe.UnsafeUtil.CHECK_NATIVE_ACCESS=true -Dorg.neo4j.io.pagecache.impl.muninn.usePreciseCursorErrorStackTraces=true -Dorg.neo4j.codegen.bytecode.ByteCodeExpressionVisitor.checkByteCode=false -Dorg.neo4j.kernel.impl.scheduler.ThreadPool.shutdownTimeout=2 -Djunit.jupiter.extensions.autodetection.enabled=true -Djunit.jupiter.execution.parallel.enabled=true -Djunit.jupiter.execution.timeout.default=20m -Djunit.jupiter.execution.parallel.mode.classes.default=concurrent -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:FlightRecorderOptions=stackdepth=256 -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -jar /home/zeyuanhu/projects/neo4j/community/community-it/bolt-it/target/surefire/surefirebooter14020249926957673158.jar /home/zeyuanhu/projects/neo4j/community/community-it/bolt-it/target/surefire 2021-10-04T16-16-34_642-jvmRun17 surefire4821097571498112339tmp surefire_151763522363265825663tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 3
[ERROR] Crashed tests:
[ERROR] org.neo4j.bolt.v4.runtime.ResetFuzzIT
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:510)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:382)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:297)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/zeyuanhu/projects/neo4j/community/community-it/bolt-it && /usr/lib/jvm/java-11-openjdk-amd64/bin/java -Xmx2G -XX:+UseG1GC -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:+ExitOnOutOfMemoryError -XX:MaxInlineLevel=15 -XX:-UseBiasedLocking -Djdk.nio.maxCachedBufferSize=262144 -Dlog4j2.disable.jmx=true -Dio.netty.tryReflectionSetAccessible=true '-XX:HeapDumpPath=target/test data' -Dorg.neo4j.internal.unsafe.UnsafeUtil.DIRTY_MEMORY=true -Dorg.neo4j.test.extension.ThreadLeakageGuardExtension.PRINT_ONLY=false -Dorg.neo4j.test.extension.ThreadLeakageGuardExtension.MAXIMUM_WAIT_TIME_MILLIS=90000 -Dorg.neo4j.internal.unsafe.UnsafeUtil.CHECK_NATIVE_ACCESS=true -Dorg.neo4j.io.pagecache.impl.muninn.usePreciseCursorErrorStackTraces=true -Dorg.neo4j.codegen.bytecode.ByteCodeExpressionVisitor.checkByteCode=false -Dorg.neo4j.kernel.impl.scheduler.ThreadPool.shutdownTimeout=2 -Djunit.jupiter.extensions.autodetection.enabled=true -Djunit.jupiter.execution.parallel.enabled=true -Djunit.jupiter.execution.timeout.default=20m -Djunit.jupiter.execution.parallel.mode.classes.default=concurrent -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:FlightRecorderOptions=stackdepth=256 -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -jar /home/zeyuanhu/projects/neo4j/community/community-it/bolt-it/target/surefire/surefirebooter14020249926957673158.jar /home/zeyuanhu/projects/neo4j/community/community-it/bolt-it/target/surefire 2021-10-04T16-16-34_642-jvmRun17 surefire4821097571498112339tmp surefire_151763522363265825663tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 3
[ERROR] Crashed tests:
[ERROR] org.neo4j.bolt.v4.runtime.ResetFuzzIT
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:115)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:371)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:347)
[ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :bolt-it
```

Platform

- Ubuntu 20.04
- java version

```
java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```
- maven version

```
$ mvn --version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.11.0-36-generic", arch: "amd64", family: "unix"
```

### Steps to reproduce
1. Download the latest source code with tag 4.3.4
2. `mvn clean install`

### Expected behavior
Build pass

### Actual behavior
Build fail

**Comment by mnd999** [comment]
Closing this very old build failure, as 4.3 branch is no longer supported.
