### ISSUE TITLE
Neo4j-admin import failed

### ISSUE THREAD

**Issue by iyuiasd7** [neo4j/neo4j#12778]
I used the neo4j-admin command to import the csv file to initialize the database, but an exception occurred when I executed the command. The exception message indicates that the **:TYPE** column is a empty value, but I checked all the csv files, and no empty value was found.

**Neo4j Version:** 4.3.2-enterprise
**Operating System:** RHEL7 (physical server)
**JDK:** 11.0.12, Name:OpenJDK 64-Bit Server VM, Vendor:Red Hat, Inc

### Expected behavior

Imported successfully

### Actual behavior

I'm getting the following error:

    WARNING Import failed. The store files in /opt/neo4j-enterprise-4.3.2/data/databases/neo4j are left as they are, although they are likely in an unusable state. Starting a database on these store files will likely fail or observe inconsistent records so start at your own risk or delete the store manually
    java.lang.IllegalArgumentException: org.neo4j.internal.kernel.api.exceptions.schema.IllegalTokenNameException: '' is not a valid token name. Token names cannot be empty or contain any null-bytes.
        at org.neo4j.internal.batchimport.store.BatchingTokenRepository.getOrCreateId(BatchingTokenRepository.java:94)
        at org.neo4j.internal.batchimport.store.BatchingTokenRepository.getOrCreateId(BatchingTokenRepository.java:76)
        at org.neo4j.internal.batchimport.RelationshipImporter.type(RelationshipImporter.java:155)
        at org.neo4j.internal.batchimport.input.InputEntity.replayOnto(InputEntity.java:354)
        at org.neo4j.internal.batchimport.input.csv.EagerCsvInputChunk.next(EagerCsvInputChunk.java:45)
        at org.neo4j.internal.batchimport.input.csv.CsvInputChunkProxy.next(CsvInputChunkProxy.java:75)
        at org.neo4j.internal.batchimport.ExhaustingEntityImporterRunnable.run(ExhaustingEntityImporterRunnable.java:57)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.neo4j.internal.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:110)
    Caused by: org.neo4j.internal.kernel.api.exceptions.schema.IllegalTokenNameException: '' is not a valid token name. Token names cannot be empty or contain any null-bytes.
        at org.neo4j.internal.kernel.api.TokenWrite.checkValidTokenName(TokenWrite.java:139)
        at org.neo4j.internal.batchimport.store.BatchingTokenRepository.getOrCreateId(BatchingTokenRepository.java:90)
        ... 12 more    

### Steps to reproduce

The header being like

    ID,Address,_source_id,_target_id,:START_ID,:END_ID,:TYPE

The data being like
   
    XXXXXXXX1,"#12-11 XXXX XXXXX XXXX XXXXX, XXXXX XXXXX",XXXXXXXX1,"#12-11 XXXX XXXXX XXXX XXXXX, XXXXX XXXXX",XXXXXXXX1,"#12-11 XXXX XXXXX XXXX XXXXX, XXXXX XXXXX",Address
    XXXXXXXX2,"#35-00 XXXX XXXXX XXXX XXXXX, XXXXX XXXXX",XXXXXXXX2,"#35-00 XXXX XXXXX XXXX XXXXX, XXXXX XXXXX",XXXXXXXX2,"#35-00 XXXX XXXXX XXXX XXXXX, XXXXX XXXXX",Address

Command used like:

    neo4j-admin import --database=neo4j --multiline-fields=true --skip-bad-relationships=true --skip-duplicate-nodes=true --nodes import/tmp0dxbylxm.csv,import/tmp7e7712_l.csv --relationships import/tmpagndf1k5.csv,import/tmp51gid3pj.csv,import/tmpb669w63v.csv

### Additional information

Sorry that the original data cannot be provided for security reasons.
I can be sure that the type column in the csv is not empty, but there will be spaces between words.
All csv is generated based on the to_csv method of the pandas library in python.
 `dataframe.to_csv(temp_file,
                         sep=',',
                         header=True,
                         index=False,
                         encoding='utf-8',
                         quotechar='"')`
I will be very appreciate if you can provide more information that may cause the exception.

**Comment by iyuiasd7** [comment]
sorry for that, I missed a file and there are some carriage returns in this file. Import is successful after removing the carriage return

**Comment by wttsxd** [comment]
你好，能不能帮看一下类似的错误
