### ISSUE TITLE
Neo4j fails to start on a FIPS environment

### ISSUE THREAD

**Issue by geoghegk** [neo4j/neo4j#12799]
Neo4j fails to start on an environment that has FIPS enabled. 
An exception (see below) is thrown suggesting an issue related to the JDK.

Neo4j version: 4.3.7
Operating system: Red Hat Enterprise Linux CoreOS release 4.8 (Worker node on RedHat OpenShift OCP 4+  with FIPS enabled)
API/Driver: Docker

Based on the issue referenced below, I suspect this is not limited to Neo4J container running on RedHat OpenShift OCP with FIPs enabled, but rather a general problem with Open JDK on a FIPS environment.

### Steps to reproduce

- Deploy Neo4J container on RedHat OpenShift OCP 4+ which has FIPS enabled
- View logs of Neo4J container

### Expected behavior

- NeoJ starts normally without errors or warnings

### Actual behavior

Neo4J fails to start and the following exception is shown in the logs: 

```
Selecting JVM - Version:11.0.13, Name:OpenJDK 64-Bit Server VM, Vendor:Red Hat, Inc.
Changed password for user 'neo4j'.
helloleo
Directories in use:
home: /var/lib/neo4j
config: /var/lib/neo4j/conf
logs: /logs
plugins: /var/lib/neo4j/plugins
import: /var/lib/neo4j/import
data: /var/lib/neo4j/data
certificates: /var/lib/neo4j/certificates
licenses: /var/lib/neo4j/licenses
run: /var/lib/neo4j/run
Starting Neo4j.
2021-11-26 09:40:07.947+0000 INFO Starting...
2021-11-26 09:40:10.464+0000 INFO ======== Neo4j 4.3.7 ========
2021-11-26 09:40:10.688+0000 ERROR Failed to start Neo4j on dbms.connector.http.listen_address, a socket address. If missing port or hostname it is acquired from dbms.default_listen_address.
java.lang.RuntimeException: Error starting Neo4j database server at /var/lib/neo4j/data/databases
at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:214) ~[neo4j-4.3.7.jar:4.3.7]
at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:170) ~[neo4j-4.3.7.jar:4.3.7]
at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36) ~[neo4j-4.3.7.jar:4.3.7]
at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:134) [neo4j-4.3.7.jar:4.3.7]
at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:90) [neo4j-4.3.7.jar:4.3.7]
at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:34) [neo4j-4.3.7.jar:4.3.7]
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.bolt.BoltServer@2b458cd6' failed to initialize. Please see the attached cause exception "CKR_ATTRIBUTE_VALUE_INVALID".
at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:424) ~[neo4j-common-4.3.7.jar:4.3.7]
at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:65) ~[neo4j-common-4.3.7.jar:4.3.7]
at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:101) ~[neo4j-common-4.3.7.jar:4.3.7]
at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:205) ~[neo4j-4.3.7.jar:4.3.7]
... 5 more
Caused by: java.lang.RuntimeException: Failed to initialize SSL encryption support, which is required to start this connector. Error was: failed to initialize the server-side SSL context
at org.neo4j.bolt.BoltServer.createSslContext(BoltServer.java:395) ~[neo4j-bolt-4.3.7.jar:4.3.7]
at org.neo4j.bolt.BoltServer.createExternalProtocolInitializer(BoltServer.java:343) ~[neo4j-bolt-4.3.7.jar:4.3.7]
at org.neo4j.bolt.BoltServer.init(BoltServer.java:196) ~[neo4j-bolt-4.3.7.jar:4.3.7]
at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:403) ~[neo4j-common-4.3.7.jar:4.3.7]
at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:65) ~[neo4j-common-4.3.7.jar:4.3.7]
at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:101) ~[neo4j-common-4.3.7.jar:4.3.7]
at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:205) ~[neo4j-4.3.7.jar:4.3.7]
... 5 more
Caused by: javax.net.ssl.SSLException: failed to initialize the server-side SSL context
at io.netty.handler.ssl.JdkSslServerContext.newSSLContext(JdkSslServerContext.java:289) ~[netty-handler-4.1.69.Final.jar:4.1.69.Final]
at io.netty.handler.ssl.JdkSslServerContext.(JdkSslServerContext.java:247) ~[netty-handler-4.1.69.Final.jar:4.1.69.Final]
at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:467) ~[netty-handler-4.1.69.Final.jar:4.1.69.Final]
at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:606) ~[netty-handler-4.1.69.Final.jar:4.1.69.Final]
at org.neo4j.ssl.SslPolicy.nettyServerContext(SslPolicy.java:82) ~[neo4j-ssl-4.3.7.jar:4.3.7]
at org.neo4j.bolt.BoltServer.createSslContext(BoltServer.java:390) ~[neo4j-bolt-4.3.7.jar:4.3.7]
at org.neo4j.bolt.BoltServer.createExternalProtocolInitializer(BoltServer.java:343) ~[neo4j-bolt-4.3.7.jar:4.3.7]
at org.neo4j.bolt.BoltServer.init(BoltServer.java:196) ~[neo4j-bolt-4.3.7.jar:4.3.7]
at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:403) ~[neo4j-common-4.3.7.jar:4.3.7]
at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:65) ~[neo4j-common-4.3.7.jar:4.3.7]
at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:101) ~[neo4j-common-4.3.7.jar:4.3.7]
at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:205) ~[neo4j-4.3.7.jar:4.3.7]
... 5 more
Caused by: java.security.KeyStoreException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_VALUE_INVALID
at sun.security.pkcs11.P11KeyStore.engineSetEntry(P11KeyStore.java:1111) ~[jdk.crypto.cryptoki:?]
at sun.security.pkcs11.P11KeyStore.engineSetKeyEntry(P11KeyStore.java:456) ~[jdk.crypto.cryptoki:?]
at java.security.KeyStore.setKeyEntry(KeyStore.java:1174) ~[?:?]
at io.netty.handler.ssl.SslContext.buildKeyStore(SslContext.java:1112) ~[netty-handler-4.1.69.Final.jar:4.1.69.Final]
at io.netty.handler.ssl.SslContext.buildKeyManagerFactory(SslContext.java:1280) ~[netty-handler-4.1.69.Final.jar:4.1.69.Final]
at io.netty.handler.ssl.JdkSslServerContext.newSSLContext(JdkSslServerContext.java:266) ~[netty-handler-4.1.69.Final.jar:4.1.69.Final]
at io.netty.handler.ssl.JdkSslServerContext.(JdkSslServerContext.java:247) ~[netty-handler-4.1.69.Final.jar:4.1.69.Final]
at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:467) ~[netty-handler-4.1.69.Final.jar:4.1.69.Final]
at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:606) ~[netty-handler-4.1.69.Final.jar:4.1.69.Final]
at org.neo4j.ssl.SslPolicy.nettyServerContext(SslPolicy.java:82) ~[neo4j-ssl-4.3.7.jar:4.3.7]
at org.neo4j.bolt.BoltServer.createSslContext(BoltServer.java:390) ~[neo4j-bolt-4.3.7.jar:4.3.7]
at org.neo4j.bolt.BoltServer.createExternalProtocolInitializer(BoltServer.java:343) ~[neo4j-bolt-4.3.7.jar:4.3.7]
at org.neo4j.bolt.BoltServer.init(BoltServer.java:196) ~[neo4j-bolt-4.3.7.jar:4.3.7]
at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:403) ~[neo4j-common-4.3.7.jar:4.3.7]
at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:65) ~[neo4j-common-4.3.7.jar:4.3.7]
at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:101) ~[neo4j-common-4.3.7.jar:4.3.7]
at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:205) ~[neo4j-4.3.7.jar:4.3.7]
... 5 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_VALUE_INVALID
at sun.security.pkcs11.wrapper.PKCS11.C_CreateObject(Native Method) ~[jdk.crypto.cryptoki:?]
at sun.security.pkcs11.P11KeyStore.storePkey(P11KeyStore.java:1803) ~[jdk.crypto.cryptoki:?]
at sun.security.pkcs11.P11KeyStore.engineSetEntry(P11KeyStore.java:1107) ~[jdk.crypto.cryptoki:?]
at sun.security.pkcs11.P11KeyStore.engineSetKeyEntry(P11KeyStore.java:456) ~[jdk.crypto.cryptoki:?]
at java.security.KeyStore.setKeyEntry(KeyStore.java:1174) ~[?:?]
at io.netty.handler.ssl.SslContext.buildKeyStore(SslContext.java:1112) ~[netty-handler-4.1.69.Final.jar:4.1.69.Final]
at io.netty.handler.ssl.SslContext.buildKeyManagerFactory(SslContext.java:1280) ~[netty-handler-4.1.69.Final.jar:4.1.69.Final]
at io.netty.handler.ssl.JdkSslServerContext.newSSLContext(JdkSslServerContext.java:266) ~[netty-handler-4.1.69.Final.jar:4.1.69.Final]
at io.netty.handler.ssl.JdkSslServerContext.(JdkSslServerContext.java:247) ~[netty-handler-4.1.69.Final.jar:4.1.69.Final]
at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:467) ~[netty-handler-4.1.69.Final.jar:4.1.69.Final]
at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:606) ~[netty-handler-4.1.69.Final.jar:4.1.69.Final]
at org.neo4j.ssl.SslPolicy.nettyServerContext(SslPolicy.java:82) ~[neo4j-ssl-4.3.7.jar:4.3.7]
at org.neo4j.bolt.BoltServer.createSslContext(BoltServer.java:390) ~[neo4j-bolt-4.3.7.jar:4.3.7]
at org.neo4j.bolt.BoltServer.createExternalProtocolInitializer(BoltServer.java:343) ~[neo4j-bolt-4.3.7.jar:4.3.7]
at org.neo4j.bolt.BoltServer.init(BoltServer.java:196) ~[neo4j-bolt-4.3.7.jar:4.3.7]
at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:403) ~[neo4j-common-4.3.7.jar:4.3.7]
at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:65) ~[neo4j-common-4.3.7.jar:4.3.7]
at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:101) ~[neo4j-common-4.3.7.jar:4.3.7]
at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:205) ~[neo4j-4.3.7.jar:4.3.7]
... 5 more
2021-11-26 09:40:10.692+0000 INFO Neo4j Server shutdown initiated by request
2021-11-26 09:40:10.692+0000 INFO Stopped.
Unexpected process failure. See log for info.
```

This looks similar to (but not identical to) the following issue related to using Open JDK on a FIPS environment.
https://access.redhat.com/solutions/6224161

I tried using IBM Java 11 (AKA Semeru) (from https://www.ibm.com/support/pages/java-sdk-downloads) instead of the Open JDK and it works, i.e. Neo4J starts and functions as expected on a FIPS environment. This would be a satisfactory resolution, but it appears from this issue https://github.com/neo4j/neo4j/issues/12791 that Semeru is not officially supported by Neo4J.

**Comment by gjmwoods** [comment]
Hi @geoghegk, apologies for the long delay on this one. Since you first opened this ticket there's been a lot of movement with FIPS and Neo4j. You can find a detailed guide on how to configure Neo4j to run in a FIPS environment here: https://neo4j.com/docs/operations-manual/current/security/ssl-fips-compatibility/.

I will close down this issue but please feel free to open a new one if you run into any trouble with the guide.
