### ISSUE TITLE
Regex throws an unexpected internal error

### ISSUE THREAD

**Issue by InverseIntegral** [neo4j/neo4j#12866]
[The documentation on regular expressions](https://neo4j.com/docs/cypher-manual/current/clauses/where/#query-where-regex) states that the syntax is inherited from the Java regular expressions. Therefore, I would assume the following query to be valid:

```
CREATE ({ p: "" =~ "\\" })
```

However, it  throws an "Unexpected internal error". My intuition is that this has to do with encoding of `\` or it might simply be an edge case that is not documented. I would assume that an unexpected internal error is something serious and that it should never occur, though.

**Neo4j Version:** 4.4.5
**Operating System:** 5.16.16 Arch
**API:** Java

### Expected behavior
No exception should be thrown according to the specification.

### Actual behavior
A `QueryExecutionException` is thrown.

```
Caused by: org.neo4j.kernel.impl.query.QueryExecutionKernelException: Invalid Regex: Unexpected internal error near index 1
\
	... 13 more
Caused by: org.neo4j.exceptions.InvalidSemanticsException: Invalid Regex: Unexpected internal error near index 1
\
	at org.neo4j.cypher.operations.CypherBoolean.regex(CypherBoolean.java:133)
	at org.neo4j.cypher.internal.runtime.interpreted.commands.predicates.RegularExpression.isMatch(Predicate.scala:365)
	at org.neo4j.cypher.internal.runtime.interpreted.commands.predicates.Predicate.apply(Predicate.scala:53)
	at org.neo4j.cypher.internal.runtime.interpreted.commands.predicates.Predicate.apply(Predicate.scala:51)
	at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.LiteralMap.$anonfun$apply$1(LiteralMap.scala:36)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:192)
	at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.LiteralMap.apply(LiteralMap.scala:35)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.BaseCreatePipe.setProperties(CreatePipe.scala:53)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EntityCreatePipe.$anonfun$createNode$2(CreatePipe.scala:94)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EntityCreatePipe.$anonfun$createNode$2$adapted(CreatePipe.scala:94)
	at scala.Option.foreach(Option.scala:407)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EntityCreatePipe.createNode(CreatePipe.scala:94)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.CreatePipe.$anonfun$internalCreateResults$2(CreatePipe.scala:138)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.CreatePipe.$anonfun$internalCreateResults$2$adapted(CreatePipe.scala:137)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.CreatePipe.$anonfun$internalCreateResults$1(CreatePipe.scala:137)
	at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$3.next(ClosingIterator.scala:154)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EmptyResultPipe.internalCreateResults(EmptyResultPipe.scala:30)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:82)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:78)
	at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.request(PipeExecutionResult.scala:69)
	at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.request(StandardInternalExecutionResult.scala:90)
	at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.initiate(StandardInternalExecutionResult.scala:53)
	at org.neo4j.cypher.internal.result.ClosingExecutionResult.$anonfun$initiate$1(ClosingExecutionResult.scala:58)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.neo4j.cypher.internal.result.ClosingExecutionResult.safely(ClosingExecutionResult.scala:99)
	at org.neo4j.cypher.internal.result.ClosingExecutionResult.initiate(ClosingExecutionResult.scala:58)
	at org.neo4j.cypher.internal.result.ClosingExecutionResult$.wrapAndInitiate(ClosingExecutionResult.scala:183)
	at org.neo4j.cypher.internal.CypherCurrentCompiler$CypherExecutableQuery.innerExecute(CypherCurrentCompiler.scala:442)
	at org.neo4j.cypher.internal.CypherCurrentCompiler$CypherExecutableQuery.execute(CypherCurrentCompiler.scala:379)
	at org.neo4j.cypher.internal.ExecutionEngine.doExecute(ExecutionEngine.scala:217)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$executeSubquery$1(ExecutionEngine.scala:178)
	at org.neo4j.cypher.internal.ExecutionEngine.closing(ExecutionEngine.scala:183)
	at org.neo4j.cypher.internal.ExecutionEngine.executeSubquery(ExecutionEngine.scala:175)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:125)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:127)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:115)
	... 9 more
```

**Comment by HannesSandberg** [comment]
Thank you for your report! We will look into this and report back to you.

**Comment by loveleif** [comment]
Hi @InverseIntegral, backslashes needs to be escaped in Cypher strings. To get `\` you need `\\`. So your query becomes `CREATE ({ p: "" =~ "\\\\" })`.
