### ISSUE TITLE
failed to create sample dbms

### ISSUE THREAD

**Issue by noxchaos** [neo4j/neo4j#12870]
[2022-04-21 08:59:24.395] [info]  Starting Neo4j Desktop 1.4.15 @ Windows_NT 10.0.22000
[2022-04-21 08:59:24.539] [info]  Initializing persistence
[2022-04-21 08:59:24.540] [info]  GraphQL server is running @ http://127.0.0.1:11001
[2022-04-21 08:59:24.543] [info]  Creating persistent store - projects
[2022-04-21 08:59:24.548] [info]  Creating persistent store - databases
[2022-04-21 08:59:24.551] [info]  Creating persistent store - userData
[2022-04-21 08:59:24.554] [info]  Creating persistent store - graphApps
[2022-04-21 08:59:24.557] [info]  Creating persistent store - plugins
[2022-04-21 08:59:24.560] [info]  Creating persistent store - distributions
[2022-04-21 08:59:24.563] [info]  Creating persistent store - licenses
[2022-04-21 08:59:24.566] [info]  Creating persistent store - notifications
[2022-04-21 08:59:24.569] [info]  Creating persistent store - karhu
[2022-04-21 08:59:24.574] [info]  Creating persistent store - permissions
[2022-04-21 08:59:24.577] [info]  Creating persistent store - certificates
[2022-04-21 08:59:24.579] [info]  Configuring crash reporting
[2022-04-21 08:59:24.580] [info]  Creating new client ID
[2022-04-21 08:59:24.581] [info]  Reading settings
[2022-04-21 08:59:24.582] [info]  PowerShell compatibility check
[2022-04-21 08:59:24.805] [info]  PowerShell version: 5. Required version: 5.
[2022-04-21 08:59:24.914] [info]  PowerShell language mode: FullLanguage
[2022-04-21 08:59:24.916] [info]  Reading bundled resources C:\Program Files\Neo4j Desktop\resources
[2022-04-21 08:59:24.917] [info]  Distribution folder for java should exist
[2022-04-21 08:59:24.918] [info]  Will copy [
  'zulu11.54.25-ca-jdk11.0.14.1-win_x64.zip',
  'zulu8.48.0.53-ca-jdk8.0.265-win_x64.zip'
]
[2022-04-21 08:59:30.365] [info]  Distribution folder for neo4j should exist
[2022-04-21 08:59:30.369] [info]  Will copy [ 'neo4j-enterprise-4.4.5-windows.zip' ]
[2022-04-21 08:59:30.459] [info]  Reading bundled resources C:\Program Files\Neo4j Desktop\resources
[2022-04-21 08:59:30.461] [info]  Distribution folder for graphApps should exist
[2022-04-21 08:59:30.462] [info]  Will copy [ 'neo4j-bloom-2.1.1.tar.gz', 'neo4j-browser-4.4.3.tar.gz' ]
[2022-04-21 08:59:30.520] [info]  Copying C:\Program Files\Neo4j Desktop\resources\offline\plugins to C:\Users\NoxCh\AppData\Local\Neo4j\Relate\Cache\plugin
[2022-04-21 08:59:30.521] [info]  Copying C:\Program Files\Neo4j Desktop\resources\offline\plugin-versions to C:\Users\NoxCh\.Neo4jDesktop\relate-data\plugin-versions
[2022-04-21 08:59:30.537] [info]  Starting Nest application... NestFactory
[2022-04-21 08:59:30.549] [info]  ElectronModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.550] [info]  s dependencies initialized InstanceLoader
[2022-04-21 08:59:30.550] [info]  ConfigHostModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.551] [info]  WebModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.551] [info]  WebModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.551] [info]  ConfigModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.551] [info]  ConfigModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.552] [info]  SystemModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.552] [info]  SystemModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.558] [info]  GraphQLSchemaBuilderModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.559] [info]  WindowModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.559] [info]  n dependencies initialized InstanceLoader
[2022-04-21 08:59:30.559] [info]  FilesModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.559] [info]  AuthModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.560] [info]  HealthModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.560] [info]  DBMSModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.560] [info]  DBMSPluginsModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.560] [info]  DBModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.560] [info]  ExtensionModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.561] [info]  ProjectModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.561] [info]  GraphQLModule dependencies initialized InstanceLoader
[2022-04-21 08:59:30.736] [info]  Nest application successfully started NestApplication
[2022-04-21 08:59:30.737] [info]  Relate management API is running @ http://127.0.0.1:12028
[2022-04-21 08:59:30.737] [info]  Configuring proxy: NO_PROXY
[2022-04-21 08:59:30.744] [info]  Online check request: https://dist.neo4j.org/neo4j-desktop/win/latest.yml
[2022-04-21 08:59:34.555] [info]  Online check response: 200 version: 1.4.15
file
[2022-04-21 08:59:34.556] [info]  Stopping any running DBMSs
[2022-04-21 08:59:34.556] [warn]  C:\Users\NoxCh\.Neo4jDesktop\neo4jDatabases not found
[2022-04-21 08:59:34.556] [info]  Registering listener for protocolManager/arguments/changed
[2022-04-21 08:59:34.563] [info]  Opening main window
[2022-04-21 08:59:34.583] [error] Protocol Manager type error: url must be string. url = undefined
[2022-04-21 08:59:34.664] [info]  Registering IPC listeners
[2022-04-21 08:59:34.664] [info]  Online check request: https://dist.neo4j.org/neo4j-desktop/win/latest.yml
[2022-04-21 08:59:35.535] [info]  Online check response: 200 version: 1.4.15
file
[2022-04-21 08:59:37.178] [info]  Initiating Mixpanel: Name = Desktop Project; pId = 2556a08ecb18f6fe0a0d5488e704927e ; uId = client-053ae85c-4481-4b9e-b5a6-8c045ff9d5b7
[2022-04-21 08:59:37.187] [info]  Initiating Segment
[2022-04-21 08:59:37.187] [info]  Creating new analytics tracking id
[2022-04-21 08:59:39.067] [warn]  ERROR: {"error":"Fetch status [404]","url":"https://neo4j.com/release-notes/neo4j-3.5.32/"}
[2022-04-21 09:00:14.675] [info]  Online check request: https://dist.neo4j.org/neo4j-desktop/win/latest.yml
[2022-04-21 09:00:15.019] [info]  Online check response: 200 version: 1.4.15
file
[2022-04-21 09:00:54.690] [info]  Online check request: https://dist.neo4j.org/neo4j-desktop/win/latest.yml
[2022-04-21 09:00:55.082] [info]  Online check response: 200 version: 1.4.15
file
[2022-04-21 09:01:17.059] [info]  App quit with 0 code
[2022-04-21 09:01:18.833] [info]  Starting Neo4j Desktop 1.4.15 @ Windows_NT 10.0.22000
[2022-04-21 09:01:18.952] [info]  Initializing persistence
[2022-04-21 09:01:18.953] [info]  GraphQL server is running @ http://127.0.0.1:11001
[2022-04-21 09:01:18.985] [info]  Configuring crash reporting
[2022-04-21 09:01:18.986] [info]  Reading settings
[2022-04-21 09:01:18.986] [info]  PowerShell compatibility check
[2022-04-21 09:01:19.195] [info]  PowerShell version: 5. Required version: 5.
[2022-04-21 09:01:19.302] [info]  PowerShell language mode: FullLanguage
[2022-04-21 09:01:19.303] [info]  Reading bundled resources C:\Program Files\Neo4j Desktop\resources
[2022-04-21 09:01:19.305] [info]  Distribution folder for java should exist
[2022-04-21 09:01:20.415] [info]  Will copy []
[2022-04-21 09:01:20.422] [info]  Distribution folder for neo4j should exist
[2022-04-21 09:01:21.239] [info]  Will copy []
[2022-04-21 09:01:21.240] [info]  Reading bundled resources C:\Program Files\Neo4j Desktop\resources
[2022-04-21 09:01:21.245] [info]  Distribution folder for graphApps should exist
[2022-04-21 09:01:21.248] [warn]  Failed to read installed 'neo4j-bloom', will replace with bundled distribution Error: Graph-App[neo4j-bloom] does not contain package.json
    at c (C:\Program Files\Neo4j Desktop\resources\app.asar\dist\main.prod.js:1:55736)
    at async d (C:\Program Files\Neo4j Desktop\resources\app.asar\dist\main.prod.js:1:42923)
    at async C:\Program Files\Neo4j Desktop\resources\app.asar\dist\main.prod.js:1:81886
    at async Promise.all (index 0)
    at async w (C:\Program Files\Neo4j Desktop\resources\app.asar\dist\main.prod.js:1:81755)
    at async C:\Program Files\Neo4j Desktop\resources\app.asar\dist\main.prod.js:1:83669
    at async t.default (C:\Program Files\Neo4j Desktop\resources\app.asar\dist\main.prod.js:1:83953)
    at async App.<anonymous> (C:\Program Files\Neo4j Desktop\resources\app.asar\dist\main.prod.js:1:230777)
[2022-04-21 09:01:21.249] [warn]  Failed to read installed 'neo4j-browser', will replace with bundled distribution Error: Graph-App[neo4j-browser] does not contain package.json
    at c (C:\Program Files\Neo4j Desktop\resources\app.asar\dist\main.prod.js:1:55736)
    at async d (C:\Program Files\Neo4j Desktop\resources\app.asar\dist\main.prod.js:1:42923)
    at async C:\Program Files\Neo4j Desktop\resources\app.asar\dist\main.prod.js:1:81886
    at async Promise.all (index 1)
    at async w (C:\Program Files\Neo4j Desktop\resources\app.asar\dist\main.prod.js:1:81755)
    at async C:\Program Files\Neo4j Desktop\resources\app.asar\dist\main.prod.js:1:83669
    at async t.default (C:\Program Files\Neo4j Desktop\resources\app.asar\dist\main.prod.js:1:83953)
    at async App.<anonymous> (C:\Program Files\Neo4j Desktop\resources\app.asar\dist\main.prod.js:1:230777)
[2022-04-21 09:01:21.249] [info]  Will copy [ 'neo4j-bloom-2.1.1.tar.gz', 'neo4j-browser-4.4.3.tar.gz' ]
[2022-04-21 09:01:21.298] [info]  Copying C:\Program Files\Neo4j Desktop\resources\offline\plugins to C:\Users\NoxCh\AppData\Local\Neo4j\Relate\Cache\plugin
[2022-04-21 09:01:21.299] [info]  Copying C:\Program Files\Neo4j Desktop\resources\offline\plugin-versions to C:\Users\NoxCh\.Neo4jDesktop\relate-data\plugin-versions
[2022-04-21 09:01:21.314] [info]  Starting Nest application... NestFactory
[2022-04-21 09:01:21.325] [info]  ElectronModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.326] [info]  s dependencies initialized InstanceLoader
[2022-04-21 09:01:21.326] [info]  ConfigHostModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.326] [info]  WebModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.327] [info]  WebModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.327] [info]  ConfigModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.327] [info]  ConfigModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.327] [info]  SystemModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.328] [info]  SystemModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.333] [info]  GraphQLSchemaBuilderModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.334] [info]  WindowModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.334] [info]  n dependencies initialized InstanceLoader
[2022-04-21 09:01:21.334] [info]  FilesModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.334] [info]  AuthModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.335] [info]  HealthModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.335] [info]  DBMSModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.335] [info]  DBMSPluginsModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.335] [info]  DBModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.335] [info]  ExtensionModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.336] [info]  ProjectModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.336] [info]  GraphQLModule dependencies initialized InstanceLoader
[2022-04-21 09:01:21.454] [info]  Nest application successfully started NestApplication
[2022-04-21 09:01:21.455] [info]  Relate management API is running @ http://127.0.0.1:12231
[2022-04-21 09:01:21.456] [info]  Configuring proxy: NO_PROXY
[2022-04-21 09:01:21.460] [info]  Online check request: https://dist.neo4j.org/neo4j-desktop/win/latest.yml
[2022-04-21 09:01:21.950] [info]  Online check response: 200 version: 1.4.15
file
[2022-04-21 09:01:21.950] [info]  Stopping any running DBMSs
[2022-04-21 09:01:21.951] [warn]  C:\Users\NoxCh\.Neo4jDesktop\neo4jDatabases not found
[2022-04-21 09:01:21.951] [info]  Registering listener for protocolManager/arguments/changed
[2022-04-21 09:01:21.957] [info]  Opening main window
[2022-04-21 09:01:21.976] [error] Protocol Manager type error: url must be string. url = undefined
[2022-04-21 09:01:22.041] [info]  Registering IPC listeners
[2022-04-21 09:01:22.041] [info]  Online check request: https://dist.neo4j.org/neo4j-desktop/win/latest.yml
[2022-04-21 09:01:22.886] [info]  Online check response: 200 version: 1.4.15
file
[2022-04-21 09:01:24.948] [info]  Initiating Mixpanel: Name = Desktop Project; pId = 2556a08ecb18f6fe0a0d5488e704927e ; uId = client-053ae85c-4481-4b9e-b5a6-8c045ff9d5b7
[2022-04-21 09:01:24.956] [info]  Initiating Segment
[2022-04-21 09:01:27.561] [warn]  ERROR: {"error":"Fetch status [404]","url":"https://neo4j.com/release-notes/neo4j-3.5.32/"}
[2022-04-21 09:01:27.646] [info]  Online check request: https://dist.neo4j.org/neo4j-desktop/win/latest.yml
[2022-04-21 09:01:27.647] [info]  Buffering metrics until application is online
[2022-04-21 09:01:27.648] [info]  Buffering metrics until application is online
[2022-04-21 09:01:27.732] [info]  Buffering metrics until application is online
[2022-04-21 09:01:27.733] [info]  Buffering metrics until application is online
[2022-04-21 09:01:27.738] [info]  Neo4j Download check
[2022-04-21 09:01:28.985] [info]  Online check response: 200 version: 1.4.15
file
[2022-04-21 09:01:30.516] [warn]  ERROR: {"error":"Fetch status [404]","url":"https://neo4j.com/release-notes/neo4j-3.5.32/"}
[2022-04-21 09:01:36.245] [info]  Graph App[neo4j-browser]: decompressing to restore state
[2022-04-21 09:01:36.245] [info]  Graph App[neo4j-bloom]: decompressing to restore state

**Comment by lyydd** [comment]
Have you solve this problem? I also find the problem in the log file. Any idea what went wrong and how to fix this?
Best

**Comment by vinhqdang** [comment]
I found the same issue with the latest neo4j
