### ISSUE TITLE
Exception is thrown with null message

### ISSUE THREAD

**Issue by InverseIntegral** [neo4j/neo4j#12874]
When I run the following code something rather strange happens:

```java
while (true) {
    try {
        executeQuery("RETURN 1/0");
    } catch (Exception e) {
        if (e.getMessage() == null)  {
            System.out.print("1");
        } else {
            System.out.print("0");
        }
    }
}
```

Initially, the query throws a `QueryExecutionException` with the message `/ by zero` as to be expected. But after a while the message of the exception becomes `null` and stays like that. So the above code always prints a sequence of `1`s followed by only `0`s. I would, however, expect the same query to throw the same exception.

I run the above on a new Neo4J database and each query is executed in its own transaction:

```java
public static void executeQuery(String query) {
    try (Transaction transaction = this.databaseService.beginTx()) {
        transaction.execute(query);
        transaction.commit();
    }
}
```

**Neo4j Version:** 4.4.5
**Operating System:** 5.16.16 Arch
**API:** Java

### Expected behavior
I would expect the exception to always be the same and not contain `null` as its message.

### Actual behavior
After some time the message field of the exception becomes `null`.

**Comment by HannesSandberg** [comment]
Thank you for the report, we will look into this and come back to you.

**Comment by pontusmelke** [comment]
Hi @InverseIntegral 
I am not able to reproduce this one. If you replace `System.out.println("1")` with `throw e` what is being thrown?
Regards,
Pontus

**Comment by InverseIntegral** [comment]
If I replace it, then I get the following exception:
```
Exception in thread "main" org.neo4j.graphdb.QueryExecutionException
	at org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(QueryExecutionKernelException.java:35)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:293)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:274)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:268)
Caused by: org.neo4j.kernel.impl.query.QueryExecutionKernelException
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:131)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:115)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:285)
	... 4 more
Caused by: org.neo4j.exceptions.ArithmeticException
	at org.neo4j.cypher.internal.compiler.Neo4jCypherExceptionFactory.arithmeticException(SyntaxExceptionCreator.scala:33)
	at org.neo4j.cypher.internal.compiler.Neo4jCypherExceptionFactory.arithmeticException(SyntaxExceptionCreator.scala:31)
	at org.neo4j.cypher.internal.rewriting.rewriters.foldConstants.apply(foldConstants.scala:59)
	at org.neo4j.cypher.internal.util.Rewritable$RewritableAny$.rewrite$extension0(Rewritable.scala:111)
	at org.neo4j.cypher.internal.util.inSequence$InSequenceRewriter.apply(Rewritable.scala:142)
	at org.neo4j.cypher.internal.util.Rewritable$RewritableAny$.rewrite$extension0(Rewritable.scala:111)
	at org.neo4j.cypher.internal.util.Rewritable$RewritableAny$.endoRewrite$extension(Rewritable.scala:120)
	at org.neo4j.cypher.internal.frontend.phases.ASTRewriter$.rewrite(ASTRewriter.scala:91)
	at org.neo4j.cypher.internal.frontend.phases.AstRewriting.process(AstRewriting.scala:38)
	at org.neo4j.cypher.internal.frontend.phases.AstRewriting.process(AstRewriting.scala:33)
	at org.neo4j.cypher.internal.frontend.phases.Phase.$anonfun$transform$1(Phase.scala:36)
	at org.neo4j.cypher.internal.frontend.helpers.package$.$anonfun$closing$1(package.scala:24)
	at org.neo4j.cypher.internal.frontend.helpers.package$.using(package.scala:32)
	at org.neo4j.cypher.internal.frontend.helpers.package$.closing(package.scala:24)
	at org.neo4j.cypher.internal.frontend.phases.Phase.transform(Phase.scala:35)
	at org.neo4j.cypher.internal.frontend.phases.Phase.transform$(Phase.scala:33)
	at org.neo4j.cypher.internal.frontend.phases.AstRewriting.transform(AstRewriting.scala:33)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:79)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78)
	at org.neo4j.cypher.internal.compiler.CypherPlanner.parseQuery(CypherPlanner.scala:97)
	at org.neo4j.cypher.internal.planning.CypherPlanner.$anonfun$getOrParse$1(CypherPlanner.scala:238)
	at scala.Option.getOrElse(Option.scala:189)
	at org.neo4j.cypher.internal.planning.CypherPlanner.getOrParse(CypherPlanner.scala:229)
	at org.neo4j.cypher.internal.planning.CypherPlanner.parseAndPlan(CypherPlanner.scala:262)
	at org.neo4j.cypher.internal.CypherCurrentCompiler.compile(CypherCurrentCompiler.scala:152)
	at org.neo4j.cypher.internal.MasterCompiler.compile(MasterCompiler.scala:86)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$compilerWithExpressionCodeGenOption$2(ExecutionEngine.scala:229)
	at org.neo4j.cypher.internal.ExecutionEngine$$anon$2.compile(ExecutionEngine.scala:237)
	at org.neo4j.cypher.internal.ExecutionEngine$$anon$2.compile(ExecutionEngine.scala:231)
	at org.neo4j.cypher.internal.QueryCache.$anonfun$compileAndCache$1(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.compileOrCompileWithExpressionCodeGenAndCache(QueryCache.scala:304)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:193)
	at org.neo4j.cypher.internal.ExecutionEngine.getOrCompile(ExecutionEngine.scala:287)
	at org.neo4j.cypher.internal.ExecutionEngine.doExecute(ExecutionEngine.scala:200)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$executeSubquery$1(ExecutionEngine.scala:178)
	at org.neo4j.cypher.internal.ExecutionEngine.closing(ExecutionEngine.scala:183)
	at org.neo4j.cypher.internal.ExecutionEngine.executeSubquery(ExecutionEngine.scala:175)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:125)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:127)
	... 6 more
Caused by: java.lang.ArithmeticException
```

**Comment by pontusmelke** [comment]
I think what you are seeing is the jit compiler kicking in and optimizing away the stack trace. See [here](https://www.oracle.com/java/technologies/javase/release-notes-introduction.html) for example:

> The compiler in the server VM now provides correct stack backtraces for all "cold" built-in exceptions. For performance purposes, when such an exception is thrown a few times, the method may be recompiled. After recompilation, the compiler may choose a faster tactic using preallocated exceptions that do not provide a stack trace. To disable completely the use of preallocated exceptions, use this new flag: -XX:-OmitStackTraceInFastThrow.

See also:

- https://stackoverflow.com/questions/6538792/why-does-throwable-getmessage-occasionally-return-null
- https://stackoverflow.com/questions/1076191/nullpointerexception-stack-trace-not-available-without-debug-agent

**Comment by InverseIntegral** [comment]
Thank you @pontusmelke, this indeed seems to be the issue. Thank you for finding this.
