### ISSUE TITLE
UnsupportedOperationException: TEXT index has no value capability

### ISSUE THREAD

**Issue by InverseIntegral** [neo4j/neo4j#12879]
When I run the following queries:

```
CREATE TEXT INDEX FOR (n:L) ON (n.p)
CREATE INDEX IF NOT EXISTS FOR (n:L) ON (n.p)
CREATE (:L {p: "test"})
MATCH (n:L) WHERE (n.p =~ "") XOR (n.p ENDS WITH "") RETURN n
```

An `UnsupportedOperationException` is thrown:

```
Caused by: java.lang.UnsupportedOperationException: TEXT index has no value capability
	at org.neo4j.kernel.impl.newapi.Read.validateConstraints(Read.java:441)
	at org.neo4j.kernel.impl.newapi.Read.nodeIndexSeek(Read.java:103)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundReadQueryContext.innerNodeIndexSeek(TransactionBoundQueryContext.scala:664)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundReadQueryContext.nodeIndexSeekByEndsWith(TransactionBoundQueryContext.scala:714)
	at org.neo4j.cypher.internal.planning.ExceptionTranslatingReadQueryContext.nodeIndexSeekByEndsWith(ExceptionTranslatingQueryContext.scala:296)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.NodeIndexEndsWithScanPipe.queryContextCall(NodeIndexStringScanPipe.scala:88)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.AbstractNodeIndexStringScanPipe.internalCreateResults(NodeIndexStringScanPipe.scala:49)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.Pipe.createResults(Pipe.scala:43)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.Pipe.createResults$(Pipe.scala:40)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.AbstractNodeIndexStringScanPipe.createResults(NodeIndexStringScanPipe.scala:34)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.UnionPipe.$anonfun$internalCreateResults$1(UnionPipe.scala:29)
	at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$5.eagerThat$lzycompute(ClosingIterator.scala:186)
	at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$5.eagerThat(ClosingIterator.scala:186)
	at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$5.innerHasNext(ClosingIterator.scala:194)
	at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:93)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.DistinctPipe$$anon$1.produceNext(DistinctPipe.scala:48)
	at org.neo4j.cypher.internal.runtime.PrefetchingIterator.pullNextElementFromSource(PrefetchingIterator.scala:44)
	at org.neo4j.cypher.internal.runtime.PrefetchingIterator.innerHasNext(PrefetchingIterator.scala:29)
	at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:93)
	at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$2.innerHasNext(ClosingIterator.scala:138)
	at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:93)
	at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$3.innerHasNext(ClosingIterator.scala:152)
	at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:93)
	at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.serveResults(PipeExecutionResult.scala:85)
	at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.request(PipeExecutionResult.scala:73)
	at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.request(StandardInternalExecutionResult.scala:90)
	at org.neo4j.cypher.internal.result.ClosingExecutionResult.request(ClosingExecutionResult.scala:144)
	at org.neo4j.cypher.internal.javacompat.ResultSubscriber.fetchResults(ResultSubscriber.java:362)
	at org.neo4j.cypher.internal.javacompat.ResultSubscriber.nextFromSubscriber(ResultSubscriber.java:330)
	at org.neo4j.cypher.internal.javacompat.ResultSubscriber.fetchNextOrNull(ResultSubscriber.java:301)
	at org.neo4j.cypher.internal.javacompat.ResultSubscriber.fetchNextOrNull(ResultSubscriber.java:58)
	at org.neo4j.internal.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
	at org.neo4j.internal.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	... 3 more
	Suppressed: java.io.IOException: Exception closing multiple resources.
		at org.neo4j.io.IOUtils.close(IOUtils.java:159)
		at org.neo4j.io.IOUtils.closeAll(IOUtils.java:56)
		at org.neo4j.cypher.internal.runtime.ClosingIterator.close(ClosingIterator.scala:85)
		at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.close(PipeExecutionResult.scala:53)
		at org.neo4j.cypher.internal.CypherCurrentCompiler$CypherExecutableQuery.$anonfun$innerExecute$2(CypherCurrentCompiler.scala:426)
		at org.neo4j.cypher.internal.CypherCurrentCompiler$CypherExecutableQuery.$anonfun$innerExecute$2$adapted(CypherCurrentCompiler.scala:426)
		at org.neo4j.cypher.internal.util.TaskCloser.close(TaskCloser.scala:44)
		at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.close(StandardInternalExecutionResult.scala:87)
		at org.neo4j.cypher.internal.result.ClosingExecutionResult.close(ClosingExecutionResult.scala:78)
		at org.neo4j.cypher.internal.result.ClosingExecutionResult.closeAndCallOnError(ClosingExecutionResult.scala:117)
		at org.neo4j.cypher.internal.result.ClosingExecutionResult.request(ClosingExecutionResult.scala:146)
		... 18 more
	Caused by: java.io.IOException: Exception closing multiple resources.
		at org.neo4j.io.IOUtils.close(IOUtils.java:159)
		at org.neo4j.io.IOUtils.closeAll(IOUtils.java:56)
		at org.neo4j.cypher.internal.runtime.ClosingIterator.close(ClosingIterator.scala:85)
		at org.neo4j.io.IOUtils.close(IOUtils.java:152)
		... 28 more
	Caused by: java.io.IOException: Exception closing multiple resources.
		at org.neo4j.io.IOUtils.close(IOUtils.java:159)
		at org.neo4j.io.IOUtils.closeAll(IOUtils.java:56)
		at org.neo4j.cypher.internal.runtime.ClosingIterator.close(ClosingIterator.scala:85)
		at org.neo4j.io.IOUtils.close(IOUtils.java:152)
		... 31 more
	Caused by: java.lang.UnsupportedOperationException: TEXT index has no value capability
		at org.neo4j.kernel.impl.newapi.Read.validateConstraints(Read.java:441)
		at org.neo4j.kernel.impl.newapi.Read.nodeIndexSeek(Read.java:103)
		at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundReadQueryContext.innerNodeIndexSeek(TransactionBoundQueryContext.scala:664)
		at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundReadQueryContext.nodeIndexSeekByEndsWith(TransactionBoundQueryContext.scala:714)
		at org.neo4j.cypher.internal.planning.ExceptionTranslatingReadQueryContext.nodeIndexSeekByEndsWith(ExceptionTranslatingQueryContext.scala:296)
		at org.neo4j.cypher.internal.runtime.interpreted.pipes.NodeIndexEndsWithScanPipe.queryContextCall(NodeIndexStringScanPipe.scala:88)
		at org.neo4j.cypher.internal.runtime.interpreted.pipes.AbstractNodeIndexStringScanPipe.internalCreateResults(NodeIndexStringScanPipe.scala:49)
		at org.neo4j.cypher.internal.runtime.interpreted.pipes.Pipe.createResults(Pipe.scala:43)
		at org.neo4j.cypher.internal.runtime.interpreted.pipes.Pipe.createResults$(Pipe.scala:40)
		at org.neo4j.cypher.internal.runtime.interpreted.pipes.AbstractNodeIndexStringScanPipe.createResults(NodeIndexStringScanPipe.scala:34)
		at org.neo4j.cypher.internal.runtime.interpreted.pipes.UnionPipe.$anonfun$internalCreateResults$1(UnionPipe.scala:29)
		at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$5.eagerThat$lzycompute(ClosingIterator.scala:186)
		at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$5.eagerThat(ClosingIterator.scala:186)
		at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$5.closeMore(ClosingIterator.scala:205)
		at org.neo4j.cypher.internal.runtime.ClosingIterator.close(ClosingIterator.scala:87)
		at org.neo4j.io.IOUtils.close(IOUtils.java:152)
		... 34 more
```

Based on the tests that I performed it seems to have to do with the two indices on the same property. I'm not sure if this is simply not allowed or if the second index creation should in fact not create a new index.

**Neo4j Version:** 4.4.6
**Operating System:** 5.17.3 Arch Linux
**API:** Java

### Expected behavior
I would expect the queries not to thrown any exception.

### Actual behavior
An exception is thrown when executing the last query.

**Comment by HannesSandberg** [comment]
Thank you for the report. We will look into this and come back to you.

**Comment by blouerat** [comment]
Thank you for raising the issue, I've just merged a fix for it, will be out with the next release
