### ISSUE TITLE
IllegalStateException: Did not find any type information for expression

### ISSUE THREAD

**Issue by InverseIntegral** [neo4j/neo4j#12881]
When I run the following query on an empty database:

```
MATCH (n:L) WHERE n.a OR (((""=~"") AND NOT(true)) >= n.a) RETURN n
```

An `IllegalStateException` is thrown:

```
Caused by: java.lang.IllegalStateException: Did not find any type information for expression Ands(List(RegexMatch(AutoExtractedParameter(  AUTOSTRING0,String,StringLiteral(),None),AutoExtractedParameter(  AUTOSTRING1,String,StringLiteral(),None)), Not(True())))
	at org.neo4j.cypher.internal.ast.semantics.SemanticTable.$anonfun$getActualTypeFor$1(SemanticTable.scala:67)
	at scala.collection.MapLike.getOrElse(MapLike.scala:131)
	at scala.collection.MapLike.getOrElse$(MapLike.scala:129)
	at org.neo4j.cypher.internal.ast.ASTAnnotationMap.getOrElse(ASTAnnotationMap.scala:29)
	at org.neo4j.cypher.internal.ast.semantics.SemanticTable.getActualTypeFor(SemanticTable.scala:67)
	at org.neo4j.cypher.internal.compiler.planner.logical.plans.InequalityRangeSeekable.$anonfun$propertyValueType$4(Sargable.scala:384)
	at org.neo4j.cypher.internal.util.NonEmptyList.map(NonEmptyList.scala:179)
	at org.neo4j.cypher.internal.util.NonEmptyList.map$(NonEmptyList.scala:177)
	at org.neo4j.cypher.internal.util.Last.map(NonEmptyList.scala:368)
	at org.neo4j.cypher.internal.compiler.planner.logical.plans.InequalityRangeSeekable.propertyValueType(Sargable.scala:384)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.index.IndexCompatiblePredicatesProvider$$anonfun$1.applyOrElse(IndexCompatiblePredicatesProvider.scala:108)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.index.IndexCompatiblePredicatesProvider$$anonfun$1.applyOrElse(IndexCompatiblePredicatesProvider.scala:78)
	at scala.PartialFunction.$anonfun$runWith$1$adapted(PartialFunction.scala:145)
	at scala.collection.immutable.Set$Set2.foreach(Set.scala:181)
	at scala.collection.TraversableLike.collect(TraversableLike.scala:407)
	at scala.collection.TraversableLike.collect$(TraversableLike.scala:405)
	at scala.collection.AbstractTraversable.collect(Traversable.scala:108)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.index.IndexCompatiblePredicatesProvider.findIndexCompatiblePredicates(IndexCompatiblePredicatesProvider.scala:78)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.index.IndexCompatiblePredicatesProvider.findIndexCompatiblePredicates$(IndexCompatiblePredicatesProvider.scala:66)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.index.NodeIndexLeafPlanner$.findIndexCompatiblePredicates(NodeIndexLeafPlanner.scala:117)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.index.NodeIndexLeafPlanner$.findIndexMatchesForQueryGraph(NodeIndexLeafPlanner.scala:176)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.index.NodeIndexLeafPlanner.apply(NodeIndexLeafPlanner.scala:69)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.OrLeafPlanner.$anonfun$apply$6(OrLeafPlanner.scala:323)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.OrLeafPlanner.$anonfun$apply$5(OrLeafPlanner.scala:323)
	at scala.collection.immutable.List.map(List.scala:297)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.OrLeafPlanner.findPlansPerPredicate$1(OrLeafPlanner.scala:319)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.OrLeafPlanner.$anonfun$apply$23(OrLeafPlanner.scala:387)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.OrLeafPlanner.$anonfun$apply$22(OrLeafPlanner.scala:386)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.immutable.Set$Set2.foreach(Set.scala:181)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.OrLeafPlanner.apply(OrLeafPlanner.scala:385)
	at org.neo4j.cypher.internal.compiler.planner.logical.LeafPlannerList.$anonfun$candidates$1(LeafPlannerIterable.scala:43)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at org.neo4j.cypher.internal.compiler.planner.logical.LeafPlannerList.candidates(LeafPlannerIterable.scala:43)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.leafPlanOptions$.apply(leafPlanOptions.scala:58)
	at org.neo4j.cypher.internal.compiler.planner.logical.idp.SingleComponentPlanner.planComponent(SingleComponentPlanner.scala:53)
	at org.neo4j.cypher.internal.compiler.planner.logical.idp.IDPQueryGraphSolver.$anonfun$planComponents$1(IDPQueryGraphSolver.scala:131)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.neo4j.cypher.internal.compiler.planner.logical.idp.IDPQueryGraphSolver.planComponents(IDPQueryGraphSolver.scala:130)
	at org.neo4j.cypher.internal.compiler.planner.logical.idp.IDPQueryGraphSolver.plan(IDPQueryGraphSolver.scala:110)
	at org.neo4j.cypher.internal.compiler.planner.logical.planMatch$.doPlan(planMatch.scala:38)
	at org.neo4j.cypher.internal.compiler.planner.logical.MatchPlanner.plan(PlanSingleQuery.scala:104)
	at org.neo4j.cypher.internal.compiler.planner.logical.MatchPlanner.plan$(PlanSingleQuery.scala:103)
	at org.neo4j.cypher.internal.compiler.planner.logical.planMatch$.plan(planMatch.scala:26)
	at org.neo4j.cypher.internal.compiler.planner.logical.PlanHead.plan(PlanHead.scala:47)
	at org.neo4j.cypher.internal.compiler.planner.logical.PlanSingleQuery.plan(PlanSingleQuery.scala:49)
	at org.neo4j.cypher.internal.compiler.planner.logical.plannerQueryPartPlanner$.plan(QueryPlanner.scala:161)
	at org.neo4j.cypher.internal.compiler.planner.logical.QueryPlanner$.plan(QueryPlanner.scala:113)
	at org.neo4j.cypher.internal.compiler.planner.logical.QueryPlanner$.process(QueryPlanner.scala:63)
	at org.neo4j.cypher.internal.compiler.planner.logical.QueryPlanner$.process(QueryPlanner.scala:51)
	at org.neo4j.cypher.internal.frontend.phases.Phase.$anonfun$transform$1(Phase.scala:36)
	at org.neo4j.cypher.internal.frontend.helpers.package$.$anonfun$closing$1(package.scala:24)
	at org.neo4j.cypher.internal.frontend.helpers.package$.using(package.scala:32)
	at org.neo4j.cypher.internal.frontend.helpers.package$.closing(package.scala:24)
	at org.neo4j.cypher.internal.frontend.phases.Phase.transform(Phase.scala:35)
	at org.neo4j.cypher.internal.frontend.phases.Phase.transform$(Phase.scala:33)
	at org.neo4j.cypher.internal.compiler.planner.logical.QueryPlanner$.transform(QueryPlanner.scala:51)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:79)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78)
	at org.neo4j.cypher.internal.frontend.phases.If.transform(Transformer.scala:96)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:79)
	at org.neo4j.cypher.internal.compiler.CypherPlanner.planPreparedQuery(CypherPlanner.scala:70)
	at org.neo4j.cypher.internal.planning.CypherPlanner.doCreatePlan(CypherPlanner.scala:404)
	at org.neo4j.cypher.internal.planning.CypherPlanner.org$neo4j$cypher$internal$planning$CypherPlanner$$createPlan$1(CypherPlanner.scala:352)
	at org.neo4j.cypher.internal.planning.CypherPlanner$$anon$1.compile(CypherPlanner.scala:361)
	at org.neo4j.cypher.internal.planning.CypherPlanner$$anon$1.compile(CypherPlanner.scala:360)
	at org.neo4j.cypher.internal.QueryCache.$anonfun$compileAndCache$1(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.compileOrCompileWithExpressionCodeGenAndCache(QueryCache.scala:304)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:193)
	at org.neo4j.cypher.internal.planning.CypherPlanner.doPlan(CypherPlanner.scala:379)
	at org.neo4j.cypher.internal.planning.CypherPlanner.parseAndPlan(CypherPlanner.scala:269)
	at org.neo4j.cypher.internal.CypherCurrentCompiler.compile(CypherCurrentCompiler.scala:152)
	at org.neo4j.cypher.internal.MasterCompiler.compile(MasterCompiler.scala:86)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$compilerWithExpressionCodeGenOption$2(ExecutionEngine.scala:229)
	at org.neo4j.cypher.internal.ExecutionEngine$$anon$2.compile(ExecutionEngine.scala:237)
	at org.neo4j.cypher.internal.ExecutionEngine$$anon$2.compile(ExecutionEngine.scala:231)
	at org.neo4j.cypher.internal.QueryCache.$anonfun$compileAndCache$1(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.compileOrCompileWithExpressionCodeGenAndCache(QueryCache.scala:304)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:193)
	at org.neo4j.cypher.internal.ExecutionEngine.getOrCompile(ExecutionEngine.scala:287)
	at org.neo4j.cypher.internal.ExecutionEngine.doExecute(ExecutionEngine.scala:200)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$executeSubquery$1(ExecutionEngine.scala:178)
	at org.neo4j.cypher.internal.ExecutionEngine.closing(ExecutionEngine.scala:183)
	at org.neo4j.cypher.internal.ExecutionEngine.executeSubquery(ExecutionEngine.scala:175)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:125)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:127)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:115)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:285)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:274)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:268)
	... 3 more
```

**Neo4j Version:** 4.4.6
**Operating System:** 5.17.3 Arch Linux
**API:** Java

### Expected behavior
I would expect the query not to thrown any exception.

### Actual behavior
An exception is thrown when executing the query.

**Comment by HannesSandberg** [comment]
Thank you! We will look into this and come back to you.
