### ISSUE TITLE
IllegalArgumentException: Comparison method violates its general contract

### ISSUE THREAD

**Issue by InverseIntegral** [neo4j/neo4j#12880]
When I run the following query on an empty database:

```
MATCH (n:S) WHERE NOT((((NOT(toBooleanOrNull(0.8)))) XOR (toUpper("") CONTAINS right("",3))) AND ((("" CONTAINS "") XOR NOT(false)) XOR (n.aF <> n.aF) XOR true)) RETURN n
```

An `IllegalArgumentException` is thrown:

```
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
	at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
	at java.base/java.util.TimSort.sort(TimSort.java:245)
	at java.base/java.util.Arrays.sort(Arrays.java:1441)
	at scala.collection.SeqLike.sorted(SeqLike.scala:659)
	at scala.collection.SeqLike.sorted$(SeqLike.scala:647)
	at scala.collection.AbstractSeq.sorted(Seq.scala:45)
	at scala.collection.SeqLike.sortBy(SeqLike.scala:634)
	at scala.collection.SeqLike.sortBy$(SeqLike.scala:634)
	at scala.collection.AbstractSeq.sortBy(Seq.scala:45)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.LogicalPlanProducer$.sortPredicatesBySelectivity(LogicalPlanProducer.scala:1926)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.InsertCachedProperties.resortSelectionPredicates(InsertCachedProperties.scala:354)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.InsertCachedProperties$$anonfun$2.applyOrElse(InsertCachedProperties.scala:333)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at org.neo4j.cypher.internal.util.Rewritable$RewritableAny$.rewrite$extension0(Rewritable.scala:111)
	at org.neo4j.cypher.internal.util.bottomUp$BottomUpRewriter.rec(Rewritable.scala:293)
	at org.neo4j.cypher.internal.util.bottomUp$BottomUpRewriter.apply(Rewritable.scala:277)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.InsertCachedProperties.process(InsertCachedProperties.scala:337)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.InsertCachedProperties.process(InsertCachedProperties.scala:73)
	at org.neo4j.cypher.internal.frontend.phases.Phase.$anonfun$transform$1(Phase.scala:36)
	at org.neo4j.cypher.internal.frontend.helpers.package$.$anonfun$closing$1(package.scala:24)
	at org.neo4j.cypher.internal.frontend.helpers.package$.using(package.scala:32)
	at org.neo4j.cypher.internal.frontend.helpers.package$.closing(package.scala:24)
	at org.neo4j.cypher.internal.frontend.phases.Phase.transform(Phase.scala:35)
	at org.neo4j.cypher.internal.frontend.phases.Phase.transform$(Phase.scala:33)
	at org.neo4j.cypher.internal.compiler.planner.logical.steps.InsertCachedProperties.transform(InsertCachedProperties.scala:73)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:79)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78)
	at org.neo4j.cypher.internal.frontend.phases.If.transform(Transformer.scala:96)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:79)
	at org.neo4j.cypher.internal.compiler.CypherPlanner.planPreparedQuery(CypherPlanner.scala:70)
	at org.neo4j.cypher.internal.planning.CypherPlanner.doCreatePlan(CypherPlanner.scala:404)
	at org.neo4j.cypher.internal.planning.CypherPlanner.org$neo4j$cypher$internal$planning$CypherPlanner$$createPlan$1(CypherPlanner.scala:352)
	at org.neo4j.cypher.internal.planning.CypherPlanner$$anon$1.compile(CypherPlanner.scala:361)
	at org.neo4j.cypher.internal.planning.CypherPlanner$$anon$1.compile(CypherPlanner.scala:360)
	at org.neo4j.cypher.internal.QueryCache.$anonfun$compileAndCache$1(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.compileOrCompileWithExpressionCodeGenAndCache(QueryCache.scala:304)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:193)
	at org.neo4j.cypher.internal.planning.CypherPlanner.doPlan(CypherPlanner.scala:379)
	at org.neo4j.cypher.internal.planning.CypherPlanner.parseAndPlan(CypherPlanner.scala:269)
	at org.neo4j.cypher.internal.CypherCurrentCompiler.compile(CypherCurrentCompiler.scala:152)
	at org.neo4j.cypher.internal.MasterCompiler.compile(MasterCompiler.scala:86)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$compilerWithExpressionCodeGenOption$2(ExecutionEngine.scala:229)
	at org.neo4j.cypher.internal.ExecutionEngine$$anon$2.compile(ExecutionEngine.scala:237)
	at org.neo4j.cypher.internal.ExecutionEngine$$anon$2.compile(ExecutionEngine.scala:231)
	at org.neo4j.cypher.internal.QueryCache.$anonfun$compileAndCache$1(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.compileOrCompileWithExpressionCodeGenAndCache(QueryCache.scala:304)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:193)
	at org.neo4j.cypher.internal.ExecutionEngine.getOrCompile(ExecutionEngine.scala:287)
	at org.neo4j.cypher.internal.ExecutionEngine.doExecute(ExecutionEngine.scala:200)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$executeSubquery$1(ExecutionEngine.scala:178)
	at org.neo4j.cypher.internal.ExecutionEngine.closing(ExecutionEngine.scala:183)
	at org.neo4j.cypher.internal.ExecutionEngine.executeSubquery(ExecutionEngine.scala:175)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:125)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:127)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:115)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:285)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:274)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:268)
	... 3 more
```

**Neo4j Version:** 4.4.6
**Operating System:** 5.17.3 Arch Linux
**API:** Java

### Expected behavior
I would expect the query not to thrown any exception.

### Actual behavior
An exception is thrown when executing the query.

**Comment by HannesSandberg** [comment]
Thank you! We will look into this.

**Comment by inmost-light** [comment]
Thanks for reporting @InverseIntegral. A fix has been implemented and should be available in the next patch release.
