### ISSUE TITLE
When using neo4j-admin to import from csv get "Unexpected node header type 'START_ID'"

### ISSUE THREAD

**Issue by umayaml** [neo4j/neo4j#12915]
- Neo4j version: 4.4.9
- Operating system: Ubuntu 16.04

Attempting to build neo4j database from csv files I previously used in neo4j 3.5.2.
Headers for node file is:
bodyID:ID(Body-ID),bodyId:long,pre:int,post:int,:LABEL
Relationship file is:
:START_ID(Body-ID),weight:int,:END_ID(Body-ID)
I get this error when using 4.4.9:
`org.neo4j.internal.batchimport.input.HeaderException: Unexpected node header type 'START_ID'
	at org.neo4j.internal.batchimport.input.csv.DataFactories$DefaultNodeFileHeaderParser.entry(DataFactories.java:427)
	at org.neo4j.internal.batchimport.input.csv.DataFactories$AbstractDefaultFileHeaderParser.lambda$new$0(DataFactories.java:246)
	at org.neo4j.internal.batchimport.input.csv.DataFactories.parseHeaderEntries(DataFactories.java:219)
	at org.neo4j.internal.batchimport.input.csv.DataFactories$AbstractDefaultFileHeaderParser.create(DataFactories.java:253)
	at org.neo4j.internal.batchimport.input.csv.CsvInput.verifyHeaders(CsvInput.java:143)
	at org.neo4j.internal.batchimport.input.csv.CsvInput.<init>(CsvInput.java:120)
	at org.neo4j.internal.batchimport.input.csv.CsvInput.<init>(CsvInput.java:98)
	at org.neo4j.importer.CsvImporter.doImport(CsvImporter.java:168)
	at org.neo4j.importer.ImportCommand.execute(ImportCommand.java:268)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:71)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:34)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.neo4j.cli.AdminTool.execute(AdminTool.java:93)
	at org.neo4j.cli.AdminTool.main(AdminTool.java:79)`
Headers work fine using neo4j 3.5.2 .

**Comment by Mkang1204** [comment]
Just wanted to add that I met the same error using admin import - 

Neo4j version: 4.3.7
Operating system: macOS 12.6.1 (21G217)

Can anyone help? Thank you!

**Comment by BITAClw** [comment]
I am a novice.I met the same error. I used the 'apoc' to export my data.When I import it by 'neo4j-admin', the error happend. I found that when we use 'neo4j admin', the ID must be name of entities, not real ID.I think the reason is that when we import relations,the code did not know the ID of entities.
