### ISSUE TITLE
Illegal reflective access using Lookup on org.neo4j.internal.unsafe.UnsafeUtil

### ISSUE THREAD

**Issue by TWiStErRob** [neo4j/neo4j#12932]
I was looking at my CI logs when I noticed this. Not entirely sure what's happening, or why. I'm reporting this because it wasn't mentioned before.

- Neo4j version: 4.4.10
- Operating system: Windows 10
- Java version: java-11.0.2-x64-openjdk
- API/Driver: `Neo4jBuilders.newInProcessBuilder().build().boltURI()` (I guess)

### Steps to reproduce
1. Clone https://github.com/TWiStErRob/net.twisterrob.cinema
2. Checkout commit [ea9b92](https://github.com/TWiStErRob/net.twisterrob.cinema/commit/ea9b92b12478eb4a3f8bf5addde9f5d4a2c6c0d7)
3. Run `gradlew :backend:database:test --tests "net.twisterrob.cinema.database.model.CinemaIntgTest.new cinema can be loaded back and contains all data"`

### Expected behavior
No warnings.

### Actual behavior
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on org.neo4j.internal.unsafe.UnsafeUtil (gradle/caches/modules-2/files-2.1/org.neo4j/neo4j-unsafe/4.4.10/31166140952e732a4e7043303245bda81ba2063f/neo4j-unsafe-4.4.10.jar) to class java.nio.Buffer
WARNING: Please consider reporting this to the maintainers of org.neo4j.internal.unsafe.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

### Logs
If you run repro steps from IntelliJ IDEA `TRACE` level logs are enabled. There's a lot of output from `Neo4jDriverIO`. The last line before this is printed (if stdout/stderr are not messing with me):
```
TRACE [Neo4jDriverIO-2-2] org.neo4j.driver.internal.logging.ChannelErrorLogger(Slf4jLogger.java:76) [0x4c815d1d][127.0.0.1:65496][bolt-0] Closing channel because of a failure
```
but this might be a red herring.

**Comment by klaren** [comment]
Hello and thanks for reporting,

This is somewhat expected behavior and is related to https://openjdk.org/jeps/261#Relaxed-strong-encapsulation

Neo4j and the libraries we use do access some internal classes to optimize performance, not doing this would result in significant degradation. Unless the JDK evolves to accommodate these cases(which is happening, we are not there yet though) there is not much we can do.

There is a way to instruct the JVM to allow this, you can have a look at https://github.com/neo4j/neo4j/blob/4.4/pom.xml#L846

Passing 
```
--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.http=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED
```
to the java executable will remove this warning.

**Comment by TWiStErRob** [comment]
Do you know where this particular access is coming from? Is it only in `newInProcessBuilder` or that's a red herring? -- oh, never mind, [rtfm](https://openjdk.org/jeps/261#Relaxed-strong-encapsulation) 🎉:
```gradle
tasks.withType<Test>().configureEach { jvmArgs("--illegal-access=debug") }
```

```
WARNING: Illegal reflective access using Lookup on org.neo4j.internal.unsafe.UnsafeUtil (file:/P:/caches/gradle/caches/modules-2/files-2.1/org.neo4j/neo4j-unsafe/4.4.10/31166140952e732a4e7043303245bda81ba2063f/neo4j-unsafe-4.4.10.jar) to class java.nio.Buffer
        at org.neo4j.internal.unsafe.UnsafeUtil.<clinit>(UnsafeUtil.java:111)
        at org.neo4j.memory.RuntimeInternals.guessHeaderSize(RuntimeInternals.java:158)
        at org.neo4j.memory.RuntimeInternals.<clinit>(RuntimeInternals.java:53)
        at org.neo4j.memory.HeapEstimator.<clinit>(HeapEstimator.java:103)
        at org.neo4j.internal.collector.RecentQueryBuffer.<clinit>(RecentQueryBuffer.java:37)
        at org.neo4j.graphdb.factory.module.GlobalModule.<init>(GlobalModule.java:212)
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.createGlobalModule(DatabaseManagementServiceFactory.java:272)
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:133)
        at org.neo4j.harness.internal.InProcessNeo4jBuilder.createNeo(InProcessNeo4jBuilder.java:50)
        at org.neo4j.harness.internal.AbstractInProcessNeo4jBuilder.build(AbstractInProcessNeo4jBuilder.java:163)
        at org.neo4j.harness.internal.AbstractInProcessNeo4jBuilder.build(AbstractInProcessNeo4jBuilder.java:69)
        at net.twisterrob.cinema.database.model.test.ModelIntgTestExtension.beforeEach(ModelIntgTestExtension.kt:48)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$2(TestMethodTestDescriptor.java:166)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$6(TestMethodTestDescriptor.java:202)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:202)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:165)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:132)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
        at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:129)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
```
and it also showed another one:
```
WARNING: Illegal reflective access using Lookup on org.neo4j.internal.unsafe.UnsafeUtil (file:/P:/caches/gradle/caches/modules-2/files-2.1/org.neo4j/neo4j-unsafe/4.4.10/31166140952e732a4e7043303245bda81ba2063f/neo4j-unsafe-4.4.10.jar) to class java.nio.DirectBy
teBuffer
        at org.neo4j.internal.unsafe.UnsafeUtil.<clinit>(UnsafeUtil.java:119)
        at org.neo4j.memory.RuntimeInternals.guessHeaderSize(RuntimeInternals.java:158)
        at org.neo4j.memory.RuntimeInternals.<clinit>(RuntimeInternals.java:53)
        at org.neo4j.memory.HeapEstimator.<clinit>(HeapEstimator.java:103)
        at org.neo4j.internal.collector.RecentQueryBuffer.<clinit>(RecentQueryBuffer.java:37)
        at org.neo4j.graphdb.factory.module.GlobalModule.<init>(GlobalModule.java:212)
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.createGlobalModule(DatabaseManagementServiceFactory.java:272)
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:133)
        at org.neo4j.harness.internal.InProcessNeo4jBuilder.createNeo(InProcessNeo4jBuilder.java:50)
        at org.neo4j.harness.internal.AbstractInProcessNeo4jBuilder.build(AbstractInProcessNeo4jBuilder.java:163)
        at org.neo4j.harness.internal.AbstractInProcessNeo4jBuilder.build(AbstractInProcessNeo4jBuilder.java:69)
        at net.twisterrob.cinema.database.model.test.ModelIntgTestExtension.beforeEach(ModelIntgTestExtension.kt:48)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$2(TestMethodTestDescriptor.java:166)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$6(TestMethodTestDescriptor.java:202)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:202)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:165)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:132)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
        at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:129)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
```

**Comment by TWiStErRob** [comment]
Note: it would be nice if we could write `--add-opens java.base/java.nio=neo4j`, so that it doesn't hide all the warnings, and it's possible to find and report other usages to other libraries.

**Comment by klaren** [comment]
You could do that, the module in question would be `org.neo4j.unsafe`, i.e. 
```
--add-opens java.base/java.nio=org.neo4j.unsafe
```
You can get the module name with `jar --file <jarFile> -d`.

My guess is that all library developers are well aware of this issue since they would also need to suppress the warnings in their builds. But for finding issues in your own code maybe you could do that.

Also, `All illegal access operations will be denied in a future release` is still there in java 18, so the future is still not here :(

**Comment by TWiStErRob** [comment]
Thank you so much for the pointers, I learned 2 new things (`--illegal-access=debug` and `jar -d`) in this short interaction!

> so the future is still not here :(

That's a good thing, builds would be breaking left and right I think.
