### ISSUE TITLE
Failed to build from current git source,PublicApi.txt, does not match the old signature in.....

### ISSUE THREAD

**Issue by buyvtuygJW** [neo4j/neo4j#12933]
To help us understand your issue, please specify important details, primarily:

- Neo4j version: direct git copy
- Operating system: Win10
- API/Driver: --
- **Steps to reproduce**
- Expected behavior compile perfectly
- Actual behavior,
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project neo4j-graphdb-api: Compilation failure
[ERROR] Public API signature mismatch.

## Example bug report
[INFO] Neo4j - Build resources ............................ SUCCESS [  7.634 s]
[INFO] Neo4j .............................................. SUCCESS [01:07 min]
[INFO] Neo4j - Annotation processors ...................... SUCCESS [01:03 min]
[INFO] Zstandard .......................................... SUCCESS [  6.384 s]
[INFO] Neo4j - Common ..................................... SUCCESS [ 32.835 s]
[INFO] Neo4j - Unsafe Access .............................. SUCCESS [ 10.491 s]
[INFO] Neo4j - Native ..................................... SUCCESS [  4.649 s]
[INFO] Neo4j - Concurrent ................................. SUCCESS [ 11.210 s]
[INFO] Neo4j - IO ......................................... SUCCESS [ 18.170 s]
[INFO] Neo4j - Token API .................................. SUCCESS [  8.756 s]
[INFO] Neo4j - Locking .................................... SUCCESS [  4.594 s]
[INFO] Neo4j - Resource interface ......................... SUCCESS [  1.486 s]
[INFO] Neo4j - Collections ................................ SUCCESS [ 14.906 s]
[INFO] Neo4j - Graph Database API ......................... FAILURE [  2.912 s]
[INFO] Neo4j - Exceptions ................................. SKIPPED
.........
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project neo4j-graphdb-api: Compilation failure
[ERROR] Public API signature mismatch. The generated signature, D:\testbuildneo4j\neo4j-4.4\community\graphdb-api\target\classes\META-INF\PublicApi.txt, does not match the old signature in D:\testbuildneo4j\neo4j-4.4\community\graphdb-api\PublicApi.txt.
[ERROR]   Specify `-Doverwrite` to maven to replace it. Changed public elements, compared to the committed PublicApi.txt:
[ERROR]   -org.neo4j.graphdb.ResourceIterable<T extends java.lang.Object> public abstract interface implements java.lang.Iterable<T>
[ERROR]   -org.neo4j.graphdb.ResourceIterator<T>::stream() java.util.stream.Stream<T> public default
[ERROR]   

### Steps to reproduce
1. clone https://github.com/neo4j/neo4j
2. extract and ready the java env and the maven build tools
3. run:mvn clean install

### Expected behavior
should compile perfectly.

### Actual behavior
error due to api checking.I guess maybe there is some api changes recently?or it the current master branch unstable?need build from releases?

**Comment by mnd999** [comment]
Can you check the Java version you are using? Neo4j 4.x requires Java 11.

**Comment by buyvtuygJW** [comment]
i use ri jdk18
>java -version
openjdk version "18" 2022-03-22
OpenJDK Runtime Environment (build 18+36-2087)
OpenJDK 64-Bit Server VM (build 18+36-2087, mixed mode, sharing)

**Comment by mnd999** [comment]
You need to use Java 11 (exactly that version) to build Neo4j 4.x. These errors are expected with other versions as the public API of JDK superclasses and interfaces changes on other JDK versions and this will affect the checks. There are also other incompatibilities on later Java versions.

**Comment by buyvtuygJW** [comment]
after using JDK11 also still has error. but not public api problem.
>
.....
[WARNING] Tests run: 23, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 1.729 s - in org.neo4j.configuration.SettingMigratorsTest
[WARNING] Tests run: 20, Failures: 0, Errors: 0, Skipped: 3, Time elapsed: 1.856 s - in org.neo4j.configuration.GraphDatabaseSettingsTest
[ERROR] Tests run: 26, Failures: 0, Errors: 1, Skipped: 6, Time elapsed: 3.895 s <<< FAILURE! - in org.neo4j.configuration.ConfigTest
[ERROR] canReadK8sStyleConfigDir  Time elapsed: 0.017 s  <<< ERROR!
java.nio.file.FileSystemException:
D:\testbuildneo4j\neo4j-4.4\community\configuration\target\test data\org.neo4j.conf~.ConfigTest\test7bede2908adcafeb92016d4ab5bdfc77\neo4j.conf\..data: A required privilege is not held by the client.

        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:581)
        at java.base/java.nio.file.Files.createSymbolicLink(Files.java:1058)
        at org.neo4j.configuration.ConfigTest.createK8sStyleConfigDir(ConfigTest.java:769)
        at org.neo4j.configuration.ConfigTest.canReadK8sStyleConfigDir(ConfigTest.java:726)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:46)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
        at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
        at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:155)
        at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   ConfigTest.canReadK8sStyleConfigDir:726->createK8sStyleConfigDir:769 ≫ FileSystem
[INFO]
[ERROR] Tests run: 242, Failures: 0, Errors: 1, Skipped: 13
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Neo4j 4.4.11-SNAPSHOT:
[INFO]
[INFO] Neo4j - Build resources ............................ SUCCESS [  2.002 s]
[INFO] Neo4j .............................................. SUCCESS [  6.711 s]
[INFO] Neo4j - Annotation processors ...................... SUCCESS [ 18.242 s]
[INFO] Zstandard .......................................... SUCCESS [  0.596 s]
[INFO] Neo4j - Common ..................................... SUCCESS [ 24.219 s]
[INFO] Neo4j - Unsafe Access .............................. SUCCESS [  6.545 s]
[INFO] Neo4j - Native ..................................... SUCCESS [  3.986 s]
[INFO] Neo4j - Concurrent ................................. SUCCESS [  9.783 s]
[INFO] Neo4j - IO ......................................... SUCCESS [ 16.320 s]
[INFO] Neo4j - Token API .................................. SUCCESS [  6.896 s]
[INFO] Neo4j - Locking .................................... SUCCESS [  4.300 s]
[INFO] Neo4j - Resource interface ......................... SUCCESS [  1.116 s]
[INFO] Neo4j - Collections ................................ SUCCESS [ 12.427 s]
[INFO] Neo4j - Graph Database API ......................... SUCCESS [  8.922 s]
[INFO] Neo4j - Exceptions ................................. SUCCESS [  6.405 s]
[INFO] Neo4j - Value ...................................... SUCCESS [ 26.530 s]
[INFO] Neo4j - Testing Utils Parent ....................... SUCCESS [  0.412 s]
[INFO] Neo4j - Test utilities ............................. SUCCESS [ 14.445 s]
[INFO] Neo4j - Random Value ............................... SUCCESS [ 12.855 s]
[INFO] Neo4j - Schema ..................................... SUCCESS [ 10.275 s]
[INFO] Neo4j - Test IO utilities .......................... SUCCESS [ 14.861 s]
[INFO] Neo4j - Logging .................................... SUCCESS [  6.559 s]
[INFO] Neo4j - Test logging utilities ..................... SUCCESS [  7.712 s]
[INFO] Neo4j - Configuration .............................. FAILURE [ 19.077 s]
.....

**Comment by mnd999** [comment]
I would suggest building Neo4j with -DskipTests, as it will be significantly faster, and you will avoid platform issues and/or flakiness with some of the tests such as the above which seems to be caused by a permissions issue around creating symbolic links.

**Comment by RESDXChgfore9hing** [comment]
it now has this new error instead>
[INFO] Neo4j - Community Cypher Build ..................... SUCCESS [  1.387 s]
[INFO] openCypher Front End Parent ........................ SUCCESS [  0.576 s]
[INFO] openCypher Test Utils .............................. FAILURE [  0.457 s]
[INFO] openCypher Utils ................................... SKIPPED
.....
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.4.0:compile (scala-compile) on project neo4j-test-util: wrap: java.io.IOException: Cannot run program ""F:\Prog\RIJDKcollec\win"\jdk-11\bin\java" (in directory "."): CreateProcess error=5, Access is denied -> [Help 1]
[ERROR]

i suspect it is similar to issue,but in this case if not powershell problem> https://github.com/neo4j/neo4j/issues/12934

Fun fact I actually reinstalled the jdk.i guess it didnt help.

I will try other graph db and keep track of this issue once in a while.

**Comment by RESDXChgfore9hing** [comment]
the command with logs>mvn clean install -DskipTests
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Neo4j - Build resources                                            [jar]
[INFO] Neo4j                                                              [pom]

**Comment by mnd999** [comment]
If you're just looking to try the database out, and do not intend to hack on it, I would suggest you give "[Neo4j Desktop](https://neo4j.com/product/developer-tools/)" a try, or [Neo4j Aura Free ](https://neo4j.com/cloud/aura-free/) for a cloud hosted managed environment.

**Comment by RESDXChgfore9hing** [comment]
yeah i wanted to try the database out first,but I intend to call it from my homemade desktop app in future.I also plan to use it daily so I think having the knowledge to build it from source is critical.

**Comment by mnd999** [comment]
It seems from the above error that you have a permissions issue preventing the build from running a java virtual machine. I'm not a Windows expert unfortunately, so I don't think I can assist with this. I am able to build community locally on Windows using maven in powershell though.

If your working on an application that embeds Neo4j, we do publish releases to Maven central so you should be able to pick up dependencies from there. See the instructions [here](https://neo4j.com/docs/java-reference/current/java-embedded/setup/#_adding_neo4j_as_a_dependency)

**Comment by RESDXChgfore9hing** [comment]
noted ,i guess its one of those windows suck reason.
will try out the maven deps way and maybe using fedora to build in future.
