### ISSUE TITLE
Unexpected error: out of bounds for object

### ISSUE THREAD

**Issue by YuanchengJiang** [neo4j/neo4j#13041]
Neo4j version: 5.4.0
Operating system: Ubuntu 20.04
API/Driver: Cypher
Dataset: https://github.com/neo4j-graph-examples/cybersecurity

To reproduce:
```
neo4j@neo4j> MATCH (a:Domain)-[*1..2]-(b:OU) WHERE id(b)>=0.0 AND id(a)>=0.0 AND id(b)>=0.0 RETURN count(b) ORDER BY 1;
+----------+
| count(b) |
+----------+
arraycopy: last destination index 2 out of bounds for object array[1]
```

Server logs:
```
2023-02-11 06:55:32.608+0000 ERROR [o.n.b.p.c.f.StateMachineSPIImpl] Client triggered an unexpected error [Neo.DatabaseError.Statement.ExecutionFailed]: arraycopy: last destination index 2 out of bounds for object array[1], reference ecec1ca4-5f11-4c2b-af6c-5f13fec2e033.
org.neo4j.fabric.executor.FabricException: arraycopy: last destination index 2 out of bounds for object array[1]
	at org.neo4j.fabric.executor.Exceptions.transform(Exceptions.java:56) ~[neo4j-fabric-5.4.0.jar:5.4.0]
	at org.neo4j.fabric.executor.Exceptions.transform(Exceptions.java:32) ~[neo4j-fabric-5.4.0.jar:5.4.0]
	at org.neo4j.fabric.stream.Rx2SyncStream.readRecord(Rx2SyncStream.java:59) ~[neo4j-fabric-5.4.0.jar:5.4.0]
	at org.neo4j.fabric.bolt.BoltQueryExecutionImpl$QueryExecutionImpl.request(BoltQueryExecutionImpl.java:151) ~[neo4j-fabric-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.protocol.common.transaction.AbstractCypherAdapterStream.handleRecords(AbstractCypherAdapterStream.java:96) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.protocol.common.transaction.result.ResultHandler.onPullRecords(ResultHandler.java:64) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.protocol.v40.messaging.result.PullResultConsumer.consume(PullResultConsumer.java:39) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.protocol.common.transaction.TransactionStateMachine$State.consumeResult(TransactionStateMachine.java:517) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.protocol.common.transaction.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:276) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.protocol.common.transaction.TransactionStateMachine.streamResult(TransactionStateMachine.java:107) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.transaction.StatementProcessorTxManager.streamResults(StatementProcessorTxManager.java:226) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.transaction.StatementProcessorTxManager.pullData(StatementProcessorTxManager.java:117) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.protocol.v40.fsm.AutoCommitState.processStreamPullResultMessage(AutoCommitState.java:43) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.protocol.v40.fsm.AbstractStreamingState.processUnsafe(AbstractStreamingState.java:47) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.protocol.v40.fsm.FailSafeState.process(FailSafeState.java:44) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.protocol.common.fsm.AbstractStateMachine.nextState(AbstractStateMachine.java:136) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.protocol.common.fsm.AbstractStateMachine.process(AbstractStateMachine.java:96) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.lambda$submit$4(AtomicSchedulingConnection.java:113) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.executeJob(AtomicSchedulingConnection.java:336) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.doExecuteJobs(AtomicSchedulingConnection.java:270) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.executeJobs(AtomicSchedulingConnection.java:212) ~[neo4j-bolt-5.4.0.jar:5.4.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 2 out of bounds for object array[1]
	at org.neo4j.cypher.internal.runtime.slotted.SlottedRow.copyFromSlotted(SlottedRow.scala:203) ~[neo4j-cypher-slotted-runtime-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.slotted.SlottedRow.copyFromOffset(SlottedRow.scala:169) ~[neo4j-cypher-slotted-runtime-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.slotted.pipes.CartesianProductSlottedPipe.$anonfun$internalCreateResults$2(CartesianProductSlottedPipe.scala:51) ~[neo4j-cypher-slotted-runtime-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$4.next(ClosingIterator.scala:201) ~[neo4j-cypher-runtime-util-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$2.next(ClosingIterator.scala:161) ~[neo4j-cypher-runtime-util-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$2.nextCur(ClosingIterator.scala:149) ~[neo4j-cypher-runtime-util-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$2.innerHasNext(ClosingIterator.scala:155) ~[neo4j-cypher-runtime-util-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:135) ~[neo4j-cypher-runtime-util-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EagerAggregationPipe.internalCreateResults(EagerAggregationPipe.scala:39) ~[neo4j-cypher-interpreted-runtime-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.computeDecoratedResult(Pipe.scala:92) ~[neo4j-cypher-interpreted-runtime-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:81) ~[neo4j-cypher-interpreted-runtime-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.computeDecoratedResult(Pipe.scala:91) ~[neo4j-cypher-interpreted-runtime-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:81) ~[neo4j-cypher-interpreted-runtime-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.computeDecoratedResult(Pipe.scala:91) ~[neo4j-cypher-interpreted-runtime-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:81) ~[neo4j-cypher-interpreted-runtime-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.computeDecoratedResult(Pipe.scala:91) ~[neo4j-cypher-interpreted-runtime-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:81) ~[neo4j-cypher-interpreted-runtime-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.request(PipeExecutionResult.scala:74) ~[neo4j-cypher-interpreted-runtime-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.request(StandardInternalExecutionResult.scala:103) ~[neo4j-cypher-5.4.0.jar:5.4.0]
	at org.neo4j.cypher.internal.result.ClosingExecutionResult.request(ClosingExecutionResult.scala:149) ~[neo4j-cypher-5.4.0.jar:5.4.0]
	at org.neo4j.fabric.stream.QuerySubject$BasicQuerySubject$1.doRequest(QuerySubject.java:155) ~[neo4j-fabric-5.4.0.jar:5.4.0]
	at org.neo4j.fabric.stream.QuerySubject$BasicQuerySubject$1.request(QuerySubject.java:143) ~[neo4j-fabric-5.4.0.jar:5.4.0]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.25.jar:3.4.25]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.25.jar:3.4.25]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.25.jar:3.4.25]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.25.jar:3.4.25]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.25.jar:3.4.25]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2123) ~[reactor-core-3.4.25.jar:3.4.25]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.25.jar:3.4.25]
	at reactor.core.publisher.StrictSubscriber.request(StrictSubscriber.java:138) ~[reactor-core-3.4.25.jar:3.4.25]
	at org.neo4j.fabric.stream.Rx2SyncStream$RecordSubscriber.request(Rx2SyncStream.java:109) ~[neo4j-fabric-5.4.0.jar:5.4.0]
	at org.neo4j.fabric.stream.Rx2SyncStream.maybeRequest(Rx2SyncStream.java:77) ~[neo4j-fabric-5.4.0.jar:5.4.0]
	at org.neo4j.fabric.stream.Rx2SyncStream.readRecord(Rx2SyncStream.java:45) ~[neo4j-fabric-5.4.0.jar:5.4.0]
```

**Comment by HannesSandberg** [comment]
Hi! Thank you for your report, we will investigate this!

**Comment by YuanchengJiang** [comment]
@sherfert May I know what happened to this issue? Thanks

**Comment by sherfert** [comment]
Hi @YuanchengJiang 

We have merged a fix for this bug, and it will be part of version 5.7
