### ISSUE TITLE
Composite database stops successful login to Neo4j Bloom

### ISSUE THREAD

**Issue by martynscn** [neo4j/neo4j#13126]
### Summary

I discovered that when neo4j DBMS has a composite database, I am unable to login to Neo4j Bloom

- Neo4j version: 5.3.0
- Operating system: Ubuntu 22.04.1 LTS
- API/Driver: Cypher

### Steps to reproduce
- Create a Composite Database
- Create aliases for the composite database
- Try logging in to Bloom

### Expected behavior
- Login to Bloom is successful

### Actual behavior
- Login to Bloom keeps on loading

![image](https://user-images.githubusercontent.com/29147664/230774398-1ab347fa-19e5-4c03-9c44-b2870c4ec63e.png)

**Error log info is shown below**
 14:52:10.180 ERROR (ROOT) Neo4jError: Transaction operations are not supported on composite databases.

    at aSt (/bloom/assets/index.e6a6bab5.js:39:98231)
    at new e (/bloom/assets/index.e6a6bab5.js:39:91773)
    at wx (/bloom/assets/index.e6a6bab5.js:40:10909)
    at Object.run (/bloom/assets/index.e6a6bab5.js:40:7820)
    at e.run (/bloom/assets/index.e6a6bab5.js:40:5031)
    at /bloom/assets/index.e6a6bab5.js:122:40407
    at e._safeExecuteTransactionWork (/bloom/assets/index.e6a6bab5.js:39:78591)
    at e.<anonymous> (/bloom/assets/index.e6a6bab5.js:39:78349)
    at u (/bloom/assets/index.e6a6bab5.js:39:76672)
    at Object.next (/bloom/assets/index.e6a6bab5.js:39:75976)
    at l (/bloom/assets/index.e6a6bab5.js:39:75533)
    at a (/bloom/assets/index.e6a6bab5.js:35:31297)
    at /bloom/assets/index.e6a6bab5.js:35:31446
    at MutationObserver.r (/bloom/assets/index.e6a6bab5.js:35:29442)

![image](https://user-images.githubusercontent.com/29147664/230774832-7da761b6-102d-410d-8462-21e723720596.png)

**Extra information**
When the neo4j composite database (and aliases prefixed with the composite database) are removed, I am able to login to Neo4j Bloom successfully

**Comment by AzuObs** [comment]
Hello Martyns,

Thank you for reporting this bug to us. Others have also noticed it, and the team is aware and there already exists a [private tracker](https://trello.com/c/bvwatHvf) for this issue. I have asked the team to get in touch with you as soon as it is resolved.

Warm thanks,

**Comment by jonaselreweny** [comment]
@martynscn The 2.8.0 release of Bloom addresses this problem
