### ISSUE TITLE
Unable to perform incremental import: No batch importers found

### ISSUE THREAD

**Issue by remort** [neo4j/neo4j#13183]
## Issue
I am importing CSV files to the empty database via `neo4j-admin`. It works. Created the DB I need to incrementally update it with data. I create new CSV files and do the `incremental` import via `neo4j-admin` and receive the error no matter which run options I try:

```
Import error: No batch importers found
Caused by:No batch importers found
java.util.NoSuchElementException: No batch importers found
	at org.neo4j.internal.batchimport.IncrementalBatchImporterFactory.lambda$withHighestPriority$1(IncrementalBatchImporterFactory.java:75)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.neo4j.internal.batchimport.IncrementalBatchImporterFactory.withHighestPriority(IncrementalBatchImporterFactory.java:75)
	at org.neo4j.internal.recordstorage.RecordStorageEngineFactory.incrementalBatchImporter(RecordStorageEngineFactory.java:708)
	at org.neo4j.importer.CsvImporter.doImport(CsvImporter.java:215)
	at org.neo4j.importer.CsvImporter.doImport(CsvImporter.java:182)
	at org.neo4j.importer.ImportCommand$Base.doExecute(ImportCommand.java:391)
	at org.neo4j.importer.ImportCommand$Incremental.execute(ImportCommand.java:548)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:92)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.neo4j.cli.AdminTool.execute(AdminTool.java:94)
	at org.neo4j.cli.AdminTool.main(AdminTool.java:82)

WARNING Import failed. The store files in /data/databases/neo4j are left as they are, although they are likely in an unusable state. Starting a database on these store files will likely fail or observe inconsistent records so start at your own risk or delete the store manually
java.util.NoSuchElementException: No batch importers found
	at org.neo4j.internal.batchimport.IncrementalBatchImporterFactory.lambda$withHighestPriority$1(IncrementalBatchImporterFactory.java:75)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.neo4j.internal.batchimport.IncrementalBatchImporterFactory.withHighestPriority(IncrementalBatchImporterFactory.java:75)
	at org.neo4j.internal.recordstorage.RecordStorageEngineFactory.incrementalBatchImporter(RecordStorageEngineFactory.java:708)
	at org.neo4j.importer.CsvImporter.doImport(CsvImporter.java:215)
	at org.neo4j.importer.CsvImporter.doImport(CsvImporter.java:182)
	at org.neo4j.importer.ImportCommand$Base.doExecute(ImportCommand.java:391)
	at org.neo4j.importer.ImportCommand$Incremental.execute(ImportCommand.java:548)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:92)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.neo4j.cli.AdminTool.execute(AdminTool.java:94)
	at org.neo4j.cli.AdminTool.main(AdminTool.java:82)
```

The simplest command that imports one single node to an already existing DB to get an error on my setup is:

```
neo4j-admin database import \
  incremental --force \
  --verbose \
  --skip-duplicate-nodes \
  --skip-bad-relationships \
  --report-file /tmp/import-report.txt \
  --nodes=Address="/path/to/addresses_headers.csv,/path_to/addresses.txt"
  neo4j
```

addresses_headers.csv:
`hash:ID(Address)`

addresses.txt:
`0x0000000000000000000000000000000000000000`

I tried to stop DB (`neo4j-admin server stop`) and use flags `--stage=all|prepare|build|merge`: no effect.

### My setup:
- Neo4j version: 5.7.0, community edition
- Operating system: official docker images of versions 5.7.0 (latest) and 5.6.0
- API/Driver: neo4j-admin

### Expected behavior
Import address node into an existing database

### Actual behavior
Import command fails with error: `java.util.NoSuchElementException: No batch importers found`

PS: Desktop version (installed in the OS, not within the container) behavior is the same.

**Comment by remort** [comment]
Hi! Any updates on this one?

**Comment by emmaholmbergohlsson** [comment]
Hi @remort , sorry for the late reply.
The incremental import is in the Enterprise edition, which means it won't work on Community
This exception does not make that clear at all though, and I can see the documentation does not mention it either.
We will make sure to update that, sorry for the inconvenience

**Comment by remort** [comment]
Thanks for the reply, Emma. No further questions.
