### ISSUE TITLE
Neo4J Load/Import Error: Caused by: java.lang.IllegalStateException: Can not read store version of database

### ISSUE THREAD

**Issue by swapnil-hkg** [neo4j/neo4j#13206]
## Neo4J Load/Import Error: Caused by: java.lang.IllegalStateException: Can not read store version of database

I am having trouble importing a dump file into a neo4j database version 5.6.0 in MacOS Ventura 13.2.1.

**Neo4j Version:** 5.6.0 (installed via homebrew)
**Operating System:** MacOS 13.2.1
**API:** native (homebrew installation)
**Java Version:** openjdk version "11.0.6" 2020-01-14

### Steps to reproduce
1. Pull the image: Install neo4j@5.6.0 via home brew. `brew install neo4j@5.6.0`
2. dump folder created in neo4j home `mkdir /opt/homebrew/Cellar/neo4j/5.6.0/libexec/dump-files`
3. The .dump files in dump-files folder in home directory has the same name as the database.
4. Run neo4j-admin load command `neo4j-admin database load --from-path=/opt/homebrew/Cellar/neo4j/5.6.0/libexec/dump-files/ graph-db --overwrite-destination=true`

### Expected behavior
Successfull import into database.

### Actual behavior
 
```
WARNING! You are using an unsupported Java runtime.
* Please use Oracle(R) Java(TM) 17, OpenJDK(TM) 17 to run Neo4j.
* Please see https://neo4j.com/docs/ for Neo4j installation instructions.
Executing command line: /opt/homebrew/opt/openjdk/bin/java -cp /opt/homebrew/Cellar/neo4j/5.6.0/libexec/plugins/*:/opt/homebrew/Cellar/neo4j/5.6.0/libexec/conf/*:/opt/homebrew/Cellar/neo4j/5.6.0/libexec/lib/* -XX:+UseParallelGC -XX:-OmitStackTraceInFastThrow -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:+DisableExplicitGC -Djdk.nio.maxCachedBufferSize=1024 -Dio.netty.tryReflectionSetAccessible=true -XX:+ExitOnOutOfMemoryError -Djdk.tls.ephemeralDHKeySize=2048 -XX:FlightRecorderOptions=stackdepth=256 -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED -Dlog4j2.disable.jmx=true -Dfile.encoding=UTF-8 org.neo4j.cli.AdminTool database load --overwrite-destination=true --from-path=/Users/swapnil/Downloads/ckg-dump mydatabase --verbose
neo4j 5.6.0
VM Name: OpenJDK 64-Bit Server VM
VM Vendor: Homebrew
VM Version: 20
JIT compiler: HotSpot 64-Bit Tiered Compilers
VM Arguments: [-XX:+UseParallelGC, -XX:-OmitStackTraceInFastThrow, -XX:+UnlockExperimentalVMOptions, -XX:+TrustFinalNonStaticFields, -XX:+DisableExplicitGC, -Djdk.nio.maxCachedBufferSize=1024, -Dio.netty.tryReflectionSetAccessible=true, -XX:+ExitOnOutOfMemoryError, -Djdk.tls.ephemeralDHKeySize=2048, -XX:FlightRecorderOptions=stackdepth=256, -XX:+UnlockDiagnosticVMOptions, -XX:+DebugNonSafepoints, --add-opens=java.base/java.nio=ALL-UNNAMED, --add-opens=java.base/java.io=ALL-UNNAMED, --add-opens=java.base/sun.nio.ch=ALL-UNNAMED, -Dlog4j2.disable.jmx=true, -Dfile.encoding=UTF-8]
Configuration files used (ordered by priority):
/opt/homebrew/Cellar/neo4j/5.6.0/libexec/conf/neo4j-admin.conf
/opt/homebrew/Cellar/neo4j/5.6.0/libexec/conf/neo4j.conf
--------------------
Done: 185 files, 17.37GiB processed.
Failed to load database 'mydatabase': Can not read store version of database mydatabaseLoad failed for databases: 'mydatabase'
org.neo4j.cli.CommandFailedException: Load failed for databases: 'mydatabase'
	at org.neo4j.commandline.dbms.LoadCommand.checkFailure(LoadCommand.java:219)
	at org.neo4j.commandline.dbms.LoadCommand.loadDump(LoadCommand.java:207)
	at org.neo4j.commandline.dbms.LoadCommand.execute(LoadCommand.java:150)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:92)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.neo4j.cli.AdminTool.execute(AdminTool.java:94)
	at org.neo4j.cli.AdminTool.main(AdminTool.java:82)
Caused by: java.lang.IllegalStateException: Can not read store version of database mydatabase
	at org.neo4j.commandline.dbms.StoreVersionLoader.loadStoreVersion(StoreVersionLoader.java:88)
	at org.neo4j.dbms.archive.Loader.getStoreVersion(Loader.java:131)
	at org.neo4j.commandline.dbms.LoadDumpExecutor.execute(LoadDumpExecutor.java:84)
	at org.neo4j.commandline.dbms.LoadCommand.loadDump(LoadCommand.java:197)
	... 13 more
```

**Comment by parnmatt** [comment]
I notice you're attempting to run Neo4j 5 on an unsupported Java runtime.

You are using Java 11, when Java 17 is required for Neo4j 5. This is indicated in the first line of your error message.

Please update the version of Java you are using in this environment, and try again, and let's see if that fixes things.

It doesn't have to be a global change, you can point to a different java version using environment variables, or use a tool like sdkman to help install and manage java versions, and even automatically switch depending on which directory you're in.

**Comment by parnmatt** [comment]
I hope that you were able to get things working on your end @swapnil-hkg
We've not heard anything from you in regard to the issue in a few weeks, so I am going to close this issue.
If however you feel it is not resolved, and you're still having related issues, please feel free to reopen the issue.
Have a pleasant day.
