### ISSUE TITLE
No label was specified for the node index in xyz:ID(xyz-id-space)

### ISSUE THREAD

**Issue by nvedansh** [neo4j/neo4j#13224]
## Guidelines

I am trying to do an incremental import from neo4j-admin import option by running the following command:

`bin/neo4j-admin database import incremental --force --stage=ALL --nodes person.csv --skip-duplicate-nodes mdm`

I get the following stacktrace as error:

```
Import error: No label was specified for the node index in 'xyz:ID(xyz-id-space)'
Caused by:No label was specified for the node index in 'xyz:ID(xyz-id-space)'
java.lang.IllegalStateException: No label was specified for the node index in 'xyz:ID(xyz-id-space)'
	at org.neo4j.util.Preconditions.checkState(Preconditions.java:195)
	at org.neo4j.internal.batchimport.input.csv.CsvInput.lambda$collectReferencedNodeSchemaFromHeader$12(CsvInput.java:401)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.neo4j.internal.batchimport.input.csv.CsvInput.collectReferencedNodeSchemaFromHeader(CsvInput.java:398)
	at org.neo4j.internal.batchimport.input.csv.CsvInput.referencedNodeSchema(CsvInput.java:384)
	at com.neo4j.internal.batchimport.ParallelIncrementalBatchImporter.prepare(ParallelIncrementalBatchImporter.java:360)
	at org.neo4j.importer.CsvImporter.doImport(CsvImporter.java:238)
	at org.neo4j.importer.CsvImporter.doImport(CsvImporter.java:181)
	at org.neo4j.importer.ImportCommand$Base.doExecute(ImportCommand.java:405)
	at org.neo4j.importer.ImportCommand$Incremental.execute(ImportCommand.java:562)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:92)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.neo4j.cli.AdminTool.execute(AdminTool.java:94)
	at org.neo4j.cli.AdminTool.main(AdminTool.java:82)

WARNING Import failed. The store files in /Users/vedanshgurunathan/Downloads/neo4j-enterprise-5.9.0/data/databases/mdm are left as they are, although they are likely in an unusable state. Starting a database on these store files will likely fail or observe inconsistent records so start at your own risk or delete the store manually
java.lang.IllegalStateException: No label was specified for the node index in 'xyz:ID(xyz-id-space)'
	at org.neo4j.util.Preconditions.checkState(Preconditions.java:195)
	at org.neo4j.internal.batchimport.input.csv.CsvInput.lambda$collectReferencedNodeSchemaFromHeader$12(CsvInput.java:401)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.neo4j.internal.batchimport.input.csv.CsvInput.collectReferencedNodeSchemaFromHeader(CsvInput.java:398)
	at org.neo4j.internal.batchimport.input.csv.CsvInput.referencedNodeSchema(CsvInput.java:384)
	at com.neo4j.internal.batchimport.ParallelIncrementalBatchImporter.prepare(ParallelIncrementalBatchImporter.java:360)
	at org.neo4j.importer.CsvImporter.doImport(CsvImporter.java:238)
	at org.neo4j.importer.CsvImporter.doImport(CsvImporter.java:181)
	at org.neo4j.importer.ImportCommand$Base.doExecute(ImportCommand.java:405)
	at org.neo4j.importer.ImportCommand$Incremental.execute(ImportCommand.java:562)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:92)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.neo4j.cli.AdminTool.execute(AdminTool.java:94)
	at org.neo4j.cli.AdminTool.main(AdminTool.java:82)
```

The CSV headers are as below:
```
xyz:ID(xyz-id-space),name,abc,pqrs,:LABEL
```

To help us understand your issue, please specify important details, primarily:

- Neo4j version: 5.9.0-Enterprise Version
- Operating system: Mac OS
- API/Driver: Neo4j-Admin Command

- Expected behavior: Import to be done successfully
- Actual behavior
The stack trace shown as above

**Comment by chuanshuoy** [comment]
how to solve

**Comment by klaren** [comment]
@chuanshuoy If you experience a similar issue, could you open a new issue with your specific case?
