### ISSUE TITLE
NullPointerException on Deleting relationship from a dense node

### ISSUE THREAD

**Issue by olavoholanda** [neo4j/neo4j#13231]
### Possible Bug report

** Neo4j version: 5.9.0 - Community Edition (Used inside Docker) 
** Operating system: Fedora 37
** API/Driver: Cypher

Hello everyone, 

I have a 1B nodes graph running in an Ec2 instance on AWS. I'm trying to perform some updates to the data stored in the graph, but I'm unable to delete specific relationships. When I execute a simple CYPHER like this:

```
MATCH (s:Entity {id: '123'})-[r:`Is Linked To`]-(t:Entity {id: '456'}) DELETE r
```

I get a Transaction Failure from the UI browser and I noticed that this happens if one of the nodes is a **dense** node. This is what I get on the debug logs:

```
Suppressed: org.neo4j.fabric.executor.FabricException: Unable to complete transaction.
		at org.neo4j.fabric.executor.Exceptions.transform(Exceptions.java:56) ~[neo4j-fabric-5.9.0.jar:5.9.0]
		at org.neo4j.fabric.executor.Exceptions.transform(Exceptions.java:32) ~[neo4j-fabric-5.9.0.jar:5.9.0]
		at org.neo4j.fabric.transaction.parent.AbstractCompoundTransaction.throwIfNonEmpty(AbstractCompoundTransaction.java:340) ~[neo4j-fabric-5.9.0.jar:5.9.0]
		at org.neo4j.fabric.transaction.parent.AbstractCompoundTransaction.commit(AbstractCompoundTransaction.java:194) ~[neo4j-fabric-5.9.0.jar:5.9.0]
		at org.neo4j.fabric.bolt.BoltFabricDatabaseService$BoltTransactionImpl.commit(BoltFabricDatabaseService.java:136) ~[neo4j-fabric-5.9.0.jar:5.9.0]
		at org.neo4j.bolt.tx.TransactionImpl.commit(TransactionImpl.java:159) ~[neo4j-bolt-5.9.0.jar:5.9.0]
		at org.neo4j.bolt.protocol.common.fsm.state.AbstractStreamingState.commit(AbstractStreamingState.java:152) ~[neo4j-bolt-5.9.0.jar:5.9.0]
		at org.neo4j.bolt.protocol.v40.fsm.state.InTransactionState.processCommitMessage(InTransactionState.java:88) ~[neo4j-bolt-5.9.0.jar:5.9.0]
		at org.neo4j.bolt.protocol.v44.fsm.state.InTransactionState.processCommitMessage(InTransactionState.java:33) ~[neo4j-bolt-5.9.0.jar:5.9.0]
		at org.neo4j.bolt.protocol.v40.fsm.state.InTransactionState.processUnsafe(InTransactionState.java:43) ~[neo4j-bolt-5.9.0.jar:5.9.0]
		at org.neo4j.bolt.protocol.common.fsm.state.AbstractState.process(AbstractState.java:41) ~[neo4j-bolt-5.9.0.jar:5.9.0]
		at org.neo4j.bolt.protocol.common.fsm.AbstractStateMachine.nextState(AbstractStateMachine.java:125) ~[neo4j-bolt-5.9.0.jar:5.9.0]
		at org.neo4j.bolt.protocol.common.fsm.AbstractStateMachine.process(AbstractStateMachine.java:85) ~[neo4j-bolt-5.9.0.jar:5.9.0]
		at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.lambda$submit$4(AtomicSchedulingConnection.java:122) ~[neo4j-bolt-5.9.0.jar:5.9.0]
		at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.executeJob(AtomicSchedulingConnection.java:344) ~[neo4j-bolt-5.9.0.jar:5.9.0]
		at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.doExecuteJobs(AtomicSchedulingConnection.java:314) ~[neo4j-bolt-5.9.0.jar:5.9.0]
		at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.executeJobs(AtomicSchedulingConnection.java:221) ~[neo4j-bolt-5.9.0.jar:5.9.0]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
		at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
	Caused by: org.neo4j.graphdb.TransactionFailureException: Unable to complete transaction.
		at org.neo4j.fabric.executor.FabricLocalExecutor$LocalTransactionContext.transformTerminalOperationError(FabricLocalExecutor.java:210) ~[neo4j-fabric-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.coreapi.TransactionImpl.safeTerminalOperation(TransactionImpl.java:337) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.coreapi.TransactionImpl.commit(TransactionImpl.java:175) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.coreapi.TransactionImpl.commit(TransactionImpl.java:170) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.fabric.executor.FabricKernelTransaction.commit(FabricKernelTransaction.java:142) ~[neo4j-fabric-5.9.0.jar:5.9.0]
		at org.neo4j.fabric.executor.FabricLocalExecutor$KernelTxWrapper.doCommit(FabricLocalExecutor.java:240) ~[neo4j-fabric-5.9.0.jar:5.9.0]
		at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:73) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:32) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:127) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4470) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:427) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:201) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2545) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onSubscribe(FluxConcatArray.java:193) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4485) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:258) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:78) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4485) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.Mono.block(Mono.java:1709) ~[reactor-core-3.5.5.jar:3.5.5]
		at org.neo4j.fabric.transaction.parent.AbstractCompoundTransaction.doOnChildren(AbstractCompoundTransaction.java:327) ~[neo4j-fabric-5.9.0.jar:5.9.0]
		at org.neo4j.fabric.transaction.parent.AbstractCompoundTransaction.commit(AbstractCompoundTransaction.java:184) ~[neo4j-fabric-5.9.0.jar:5.9.0]
		... 18 more
	Caused by: java.lang.NullPointerException: Cannot invoke "org.neo4j.internal.recordstorage.RecordAccess$RecordProxy.getKey()" because "group" is null
		at org.neo4j.internal.recordstorage.NodeContext$DenseContext.setGroup(NodeContext.java:185) ~[neo4j-record-storage-engine-5.9.0.jar:5.9.0]
		at org.neo4j.internal.recordstorage.NodeContext$DenseContext.getOrLoadGroup(NodeContext.java:175) ~[neo4j-record-storage-engine-5.9.0.jar:5.9.0]
		at org.neo4j.internal.recordstorage.RelationshipModifier.lambda$acquireMostOfTheNodeAndGroupsLocks$2(RelationshipModifier.java:251) ~[neo4j-record-storage-engine-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.api.state.RelationshipChangesForNode.visitIdsSplit(RelationshipChangesForNode.java:242) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.api.state.NodeStateImpl.visitRemovedIdsSplit(NodeStateImpl.java:294) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.api.state.StateNodeRelationshipIds.forEachDeletionSplitInterruptible(StateNodeRelationshipIds.java:88) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.internal.recordstorage.RelationshipModifier.lambda$acquireMostOfTheNodeAndGroupsLocks$4(RelationshipModifier.java:249) ~[neo4j-record-storage-engine-5.9.0.jar:5.9.0]
		at org.neo4j.collection.trackable.HeapTrackingArrayList.forEach(HeapTrackingArrayList.java:425) ~[neo4j-collections-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.api.state.TxState$1.forEachSplit(TxState.java:176) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.internal.recordstorage.RelationshipModifier.acquireMostOfTheNodeAndGroupsLocks(RelationshipModifier.java:131) ~[neo4j-record-storage-engine-5.9.0.jar:5.9.0]
		at org.neo4j.internal.recordstorage.RelationshipModifier.modifyRelationships(RelationshipModifier.java:105) ~[neo4j-record-storage-engine-5.9.0.jar:5.9.0]
		at org.neo4j.internal.recordstorage.TransactionRecordState.relModify(TransactionRecordState.java:330) ~[neo4j-record-storage-engine-5.9.0.jar:5.9.0]
		at org.neo4j.internal.recordstorage.TransactionToRecordStateVisitor.visitRelationshipModifications(TransactionToRecordStateVisitor.java:89) ~[neo4j-record-storage-engine-5.9.0.jar:5.9.0]
		at org.neo4j.storageengine.api.txstate.TxStateVisitor$Delegator.visitRelationshipModifications(TxStateVisitor.java:153) ~[neo4j-kernel-api-5.9.0.jar:5.9.0]
		at org.neo4j.storageengine.api.txstate.TransactionCountingStateVisitor.visitRelationshipModifications(TransactionCountingStateVisitor.java:119) ~[neo4j-storage-engine-util-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.api.state.TxState.accept(TxState.java:173) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.internal.recordstorage.RecordStorageEngine.createCommands(RecordStorageEngine.java:490) ~[neo4j-record-storage-engine-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.api.KernelTransactionImplementation.extractCommands(KernelTransactionImplementation.java:1047) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.api.commit.DefaultCommitter.commit(DefaultCommitter.java:85) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commitTransaction(KernelTransactionImplementation.java:1016) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:892) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:865) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.coreapi.TransactionImpl.lambda$commit$0(TransactionImpl.java:175) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.coreapi.TransactionImpl.safeTerminalOperation(TransactionImpl.java:322) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.coreapi.TransactionImpl.commit(TransactionImpl.java:175) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.kernel.impl.coreapi.TransactionImpl.commit(TransactionImpl.java:170) ~[neo4j-kernel-5.9.0.jar:5.9.0]
		at org.neo4j.fabric.executor.FabricKernelTransaction.commit(FabricKernelTransaction.java:142) ~[neo4j-fabric-5.9.0.jar:5.9.0]
		at org.neo4j.fabric.executor.FabricLocalExecutor$KernelTxWrapper.doCommit(FabricLocalExecutor.java:240) ~[neo4j-fabric-5.9.0.jar:5.9.0]
		at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:73) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:32) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:127) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4470) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:427) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:201) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2545) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onSubscribe(FluxConcatArray.java:193) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4485) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:258) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:78) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4485) ~[reactor-core-3.5.5.jar:3.5.5]
		at reactor.core.publisher.Mono.block(Mono.java:1709) ~[reactor-core-3.5.5.jar:3.5.5]
		at org.neo4j.fabric.transaction.parent.AbstractCompoundTransaction.doOnChildren(AbstractCompoundTransaction.java:327) ~[neo4j-fabric-5.9.0.jar:5.9.0]
		at org.neo4j.fabric.transaction.parent.AbstractCompoundTransaction.commit(AbstractCompoundTransaction.java:184) ~[neo4j-fabric-5.9.0.jar:5.9.0]
		... 18 more
```

Any suggestions?

**Comment by tinwelint** [comment]
@olavoholanda I realize this is a quite late response, but did you overcome this problem? It almost looks like some internal linking problem in the storage where the dense node cannot find its internal "group record" for that particular relationship type. These group records  serves as a means to splitting up relationships for that dense node based on type and direction. Were there concurrent deletions running when getting this error? That of course should not be a problem due to locking taking care of that in principle. Otherwise there could be some other internal inconsistency. You could try to run a consistency check on the database to see if all these links are intact.

**Comment by olavoholanda** [comment]
@tinwelint sorry for the late response from me too. We still have the same problem, we just don't use neo4j anymore as a source of truth and times to time we need to resync the whole data from scratch. 

> Were there concurrent deletions running when getting this error?

No, but we send several sequential update commands. They are only sent by a single processor, like an ETL job.

> You could try to run a consistency check on the database to see if all these links are intact.

I will try that, but what could cause an inconsistency on the database? Could it be possible from Neo4j crashing during an update/delete/insert operation?

**Comment by klaren** [comment]
Closing due to inactivity. Feel free to reopen if the problem resurfaces.
