### ISSUE TITLE
Neo4j Admin Import - Tool - Option to Upload Nodes Before Starting To Upload Relationships

### ISSUE THREAD

**Issue by sking115422** [neo4j/neo4j#13281]
**Is your feature request related to a problem? Please describe.**

I am not sure if this is related to another problem. If so I have not be able to find it. So I will explain my issue here. I am trying to create a graph database of the entire Bitcoin Ledger. I have prepared all the necessary CSV files, and I am trying to leverage to the speed of the Neo4j Admin Import Tool to import lots of data very quickly. It works very well for most nodes and relationships. However, due to the parallels nature of the tool. It begins to upload relationship for which no nodes exist yet. I really need the tool to upload nodes first then relationships. This may be possible already, I just cannot figure out how to achieve it. 

**Describe the solution you'd like**
I would love the ability to in some way be able to upload nodes first to ensure that they all exist then relationships.

**Describe alternatives you've considered**
I can and will just write my own custom upload solution in Scala if need, but I think this may be something that would benefit the neo4j audience more generally. 

**Additional context**

TOOL OUTPUT 

Selecting JVM - Version:11.0.20+8-post-Ubuntu-1ubuntu122.04, Name:OpenJDK 64-Bit Server VM, Vendor:Ubuntu
Executing command line: /usr/lib/jvm/java-11-openjdk-amd64/bin/java -cp /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/plugins/*:/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/conf/*:/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/lib/* -XX:+UseG1GC -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:+DisableExplicitGC -XX:MaxInlineLevel=15 -XX:-UseBiasedLocking -Djdk.nio.maxCachedBufferSize=262144 -Dio.netty.tryReflectionSetAccessible=true -Djdk.tls.ephemeralDHKeySize=2048 -Djdk.tls.rejectClientInitiatedRenegotiation=true -XX:FlightRecorderOptions=stackdepth=256 -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -Dlog4j2.disable.jmx=true -Dfile.encoding=UTF-8 org.neo4j.cli.AdminTool import --database=BtcBlockChainGraphDB --nodes=/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/block.csv --nodes=/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/coinbase.csv --nodes=/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/tx.csv --nodes=/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/io.csv --nodes=/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/address.csv --relationships=/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/CHAINS_TO.csv --relationships=/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/REWARDS.csv --relationships=/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/SEEDS.csv --relationships=/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/BELONGS.csv --relationships=/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/PRODUCES.csv --relationships=/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/LOCKS.csv --relationships=/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/UNLOCKED_FROM.csv --relationships=/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/CONSUMED_BY.csv --verbose
neo4j 4.4.24
VM Name: OpenJDK 64-Bit Server VM
VM Vendor: Ubuntu
VM Version: 11.0.20+8-post-Ubuntu-1ubuntu122.04
JIT compiler: HotSpot 64-Bit Tiered Compilers
VM Arguments: [-XX:+UseG1GC, -XX:-OmitStackTraceInFastThrow, -XX:+AlwaysPreTouch, -XX:+UnlockExperimentalVMOptions, -XX:+TrustFinalNonStaticFields, -XX:+DisableExplicitGC, -XX:MaxInlineLevel=15, -XX:-UseBiasedLocking, -Djdk.nio.maxCachedBufferSize=262144, -Dio.netty.tryReflectionSetAccessible=true, -Djdk.tls.ephemeralDHKeySize=2048, -Djdk.tls.rejectClientInitiatedRenegotiation=true, -XX:FlightRecorderOptions=stackdepth=256, -XX:+UnlockDiagnosticVMOptions, -XX:+DebugNonSafepoints, -Dlog4j2.disable.jmx=true, -Dfile.encoding=UTF-8]
Neo4j version: 4.4.24
Importing the contents of these files into /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/data/databases/btcblockchaingraphdb:
Nodes:
  /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/block.csv
  /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/coinbase.csv
  /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/tx.csv
  /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/io.csv
  /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/address.csv

Relationships:
  /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/CHAINS_TO.csv
  /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/REWARDS.csv
  /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/SEEDS.csv
  /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/BELONGS.csv
  /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/PRODUCES.csv
  /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/LOCKS.csv
  /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/UNLOCKED_FROM.csv
  /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/CONSUMED_BY.csv

Available resources:
  Total machine memory: 251.8GiB
  Free machine memory: 240.9GiB
  Max heap memory : 29.97GiB
  Processors: 40
  Configured max memory: 199.7GiB
  High-IO: true

Type normalization:
  Property type of 'size' normalized from 'int' --> 'long' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/block.csv
  Property type of 'version' normalized from 'int' --> 'long' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/block.csv
  Property type of 'unixTime' normalized from 'int' --> 'long' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/block.csv
  Property type of 'difficulty' normalized from 'int' --> 'long' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/block.csv
  Property type of 'nonce' normalized from 'int' --> 'long' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/block.csv
  Property type of 'numTx' normalized from 'int' --> 'long' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/block.csv
  Property type of 'blkNum' normalized from 'int' --> 'long' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/block.csv
  Property type of 'value' normalized from 'float' --> 'double' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/coinbase.csv
  Property type of 'blkNum' normalized from 'int' --> 'long' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/coinbase.csv
  Property type of 'version' normalized from 'int' --> 'long' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/tx.csv
  Property type of 'locktime' normalized from 'int' --> 'long' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/tx.csv
  Property type of 'numOutput' normalized from 'int' --> 'long' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/tx.csv
  Property type of 'blkNum' normalized from 'int' --> 'long' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/tx.csv
  Property type of 'ioNum' normalized from 'int' --> 'long' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/io.csv
  Property type of 'value' normalized from 'float' --> 'double' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/io.csv
  Property type of 'blkNum' normalized from 'int' --> 'long' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/io.csv
  Property type of 'blkNum' normalized from 'int' --> 'long' in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/address.csv
Nodes, started 2023-08-17 19:39:49.399+0000
[*Nodes:0B/s 1.004GiB-------------------------------------------------------------------------] 750K ∆ 750K
Done in 1s 170ms
Prepare node index, started 2023-08-17 19:39:50.598+0000
[*DETECT:1.006GiB-----------------------------------------------------------------------------]2.48M ∆2.48M
Done in 850ms
Relationships, started 2023-08-17 19:39:51.455+0000
Critical error occurred! Shutting down the import...
[*Relationships:?? 1.006GiB-------------------------------------------------------------------] 160K ∆ 160K
IMPORT FAILED in 3s 861ms. 
Data statistics is not available.
Peak memory usage: 1.006GiB
Error in input data
Caused by:ERROR in input
  data source: BufferedCharSeeker[source:/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/LOCKS.csv, position:49, line:1]
  in field: :TYPE:3
  for header: [:START_ID, :END_ID, :TYPE]
  raw field value: LOCKS
  original error: io-757 (global id space)-[LOCKS]->12higDjoCCNXSA95xZMWUdPvXNmkAduhWv (global id space) referring to missing node 12higDjoCCNXSA95xZMWUdPvXNmkAduhWv
org.neo4j.internal.batchimport.input.InputException: ERROR in input
  data source: BufferedCharSeeker[source:/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/LOCKS.csv, position:49, line:1]
  in field: :TYPE:3
  for header: [:START_ID, :END_ID, :TYPE]
  raw field value: LOCKS
  original error: io-757 (global id space)-[LOCKS]->12higDjoCCNXSA95xZMWUdPvXNmkAduhWv (global id space) referring to missing node 12higDjoCCNXSA95xZMWUdPvXNmkAduhWv
        at org.neo4j.internal.batchimport.input.BadCollector$RelationshipsProblemReporter.exception(BadCollector.java:237)
        at org.neo4j.internal.batchimport.input.BadCollector.collect(BadCollector.java:170)
        at org.neo4j.internal.batchimport.input.BadCollector.collectBadRelationship(BadCollector.java:125)
        at org.neo4j.internal.batchimport.RelationshipImporter.endOfEntity(RelationshipImporter.java:196)
        at org.neo4j.internal.batchimport.input.InputEntityVisitor$Delegate.endOfEntity(InputEntityVisitor.java:258)
        at org.neo4j.internal.batchimport.input.InputEntityDecorators$RelationshipTypeDecorator.endOfEntity(InputEntityDecorators.java:159)
        at org.neo4j.internal.batchimport.input.csv.CsvInputParser.next(CsvInputParser.java:202)
        at org.neo4j.internal.batchimport.input.csv.LazyCsvInputChunk.next(LazyCsvInputChunk.java:98)
        at org.neo4j.internal.batchimport.input.csv.CsvInputChunkProxy.next(CsvInputChunkProxy.java:75)
        at org.neo4j.internal.batchimport.ExhaustingEntityImporterRunnable.run(ExhaustingEntityImporterRunnable.java:57)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.neo4j.internal.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:110)
        Suppressed: org.neo4j.internal.batchimport.input.InputException: ERROR in input
  data source: BufferedCharSeeker[source:/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/LOCKS.csv, position:51, line:1]
  in field: :TYPE:3
  for header: [:START_ID, :END_ID, :TYPE]
  raw field value: LOCKS
  original error: io-175864 (global id space)-[LOCKS]->1HKppbK2m2imX9u5zSh3TYm7nTgn4jSLk9 (global id space) referring to missing node 1HKppbK2m2imX9u5zSh3TYm7nTgn4jSLk9
                ... 16 more

WARNING Import failed. The store files in /mnt/sdb1/data/neo4j/neo4j-community-4.4.24/data/databases/btcblockchaingraphdb are left as they are, although they are likely in an unusable state. Starting a database on these store files will likely fail or observe inconsistent records so start at your own risk or delete the store manually
org.neo4j.internal.batchimport.input.InputException: ERROR in input
  data source: BufferedCharSeeker[source:/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/LOCKS.csv, position:49, line:1]
  in field: :TYPE:3
  for header: [:START_ID, :END_ID, :TYPE]
  raw field value: LOCKS
  original error: io-757 (global id space)-[LOCKS]->12higDjoCCNXSA95xZMWUdPvXNmkAduhWv (global id space) referring to missing node 12higDjoCCNXSA95xZMWUdPvXNmkAduhWv
        at org.neo4j.internal.batchimport.input.BadCollector$RelationshipsProblemReporter.exception(BadCollector.java:237)
        at org.neo4j.internal.batchimport.input.BadCollector.collect(BadCollector.java:170)
        at org.neo4j.internal.batchimport.input.BadCollector.collectBadRelationship(BadCollector.java:125)
        at org.neo4j.internal.batchimport.RelationshipImporter.endOfEntity(RelationshipImporter.java:196)
        at org.neo4j.internal.batchimport.input.InputEntityVisitor$Delegate.endOfEntity(InputEntityVisitor.java:258)
        at org.neo4j.internal.batchimport.input.InputEntityDecorators$RelationshipTypeDecorator.endOfEntity(InputEntityDecorators.java:159)
        at org.neo4j.internal.batchimport.input.csv.CsvInputParser.next(CsvInputParser.java:202)
        at org.neo4j.internal.batchimport.input.csv.LazyCsvInputChunk.next(LazyCsvInputChunk.java:98)
        at org.neo4j.internal.batchimport.input.csv.CsvInputChunkProxy.next(CsvInputChunkProxy.java:75)
        at org.neo4j.internal.batchimport.ExhaustingEntityImporterRunnable.run(ExhaustingEntityImporterRunnable.java:57)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.neo4j.internal.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:110)
        Suppressed: org.neo4j.internal.batchimport.input.InputException: ERROR in input
  data source: BufferedCharSeeker[source:/mnt/sdb1/data/neo4j/neo4j-community-4.4.24/import/LOCKS.csv, position:51, line:1]
  in field: :TYPE:3
  for header: [:START_ID, :END_ID, :TYPE]
  raw field value: LOCKS
  original error: io-175864 (global id space)-[LOCKS]->1HKppbK2m2imX9u5zSh3TYm7nTgn4jSLk9 (global id space) referring to missing node 1HKppbK2m2imX9u5zSh3TYm7nTgn4jSLk9
                ... 16 more

**To be clear, in the above case the node 12higDjoCCNXSA95xZMWUdPvXNmkAduhWv is definitely note missing just does not exist yet so the program fails.**

**Comment by tinwelint** [comment]
Hi @sking115422 all nodes of an import are always processed before any of the relationships. So if there are relationships that refer to nodes that do not exist it may be problems in the relationship CSV data.

It's very common that exported CSV data like this have inconsistencies or "garbage" and the import tool therefor has options to skip those. E.g. in your case if you add the `--skip-bad-relationships` option any such relationship would be skipped and the import would continue. There's a threshold for how many "bad" data entries it tolerates before aborting anyway. This threshold can be controlled with `--bad-tolerance` and defaults to `1000`. So to increase it you could add e.g. `--bad-tolerance=10000`.

**Comment by sking115422** [comment]
Hi @tinwelint, 

Thank for the reply!

This is strange because I have verified that all nodes the failed relationships refer too should exist if the nodes are all imported before the relationship imports begins. If this is truly the case, I do not understand where this error comes from. I will try increasing the --bad-tolerance value and see if that at least lets the import finish.

**Comment by tinwelint** [comment]
@sking115422 Hmm, you know what... I see a bug fix to the internal node ID mapping data structure during import. This bug fix was made in 5.x, but never back-ported to 4.4. This could very well be it!

Even if it obviously haven't verified that this is indeed the issue you're running into I'll do this back-port and hopefully you can try again on the next patch release. Or if you can try the import on 5.6 or later this mentioned fix should be in it.

**Comment by sking115422** [comment]
@tinwelint Ah okay. This would make sense because I am using 4.4.24. I will try the latest 5.6 version in the mean time to see if this is in fact the issue. When would the next patch release be?

**Comment by sking115422** [comment]
It may be a week or so before I get a chance to test this, but I will response with the results here.

**Comment by tinwelint** [comment]
@sking115422 The cadence could be a couple of weeks, depending on amount of fixes pending in that version.

Ok great, and if you're going for 5.x you can might as well go for the latest available when trying it out. The versioning in 5.x is a bit different, with fewer patch releases (the z in x.y.z) and more frequent minor version releases (the y in x.y.z). Currently latest version is 5.11.

**Comment by sking115422** [comment]
@tinwelint Got it. Thanks a lot!

**Comment by sking115422** [comment]
@tinwelint By the way, I got a chance to test the theory tonight. However, it turns out the root of the problem had nothing to do with the Neo4j versioning. I assigned the ID to the wrong column header. Your suggestion of adding --skip-bad-relationships and --bad-tolerance helped me to realize that every relationship had been skipped which lead me to the source of the error. 

I really apologize for wasting your time with such a simple mistake, but you saved me from being stumped. I find sometimes (ironically) the simplest error are the hardest to find. lol. Anyway, thank you very much again for you help!

**Comment by tinwelint** [comment]
An honest mistake, it happens to all of us :)

I'm glad you got it sorted out and that I could be of some kind of service. Good luck with the continuation of this work!
