### ISSUE TITLE
causal clustering errors with transaction logs

### ISSUE THREAD

**Issue by jbkc85** [neo4j/neo4j#13297]
to whom it may concern,

We run a 4.4.x neo4j instance that is in `SINGLE` mode, however we attach a read replica to it.  Recently this read replica just randomly died and we come to find out we are receiving errors such as:

```
Caused by: org.neo4j.kernel.impl.transaction.log.NoSuchTransactionException: Unable to find transaction 455257799 in any of my logical logs: Couldn't find any log c
ontaining 455257799
        at org.neo4j.kernel.impl.transaction.log.PhysicalLogicalTransactionStore$LogVersionLocator.getLogPosition(PhysicalLogicalTransactionStore.java:188) ~[neo4j-
kernel-4.4.15.jar:4.4.15]
        at org.neo4j.kernel.impl.transaction.log.PhysicalLogicalTransactionStore.getTransactions(PhysicalLogicalTransactionStore.java:98) ~[neo4j-kernel-4.4.15.jar:
4.4.15]
        at org.neo4j.kernel.api.database.transaction.TransactionLogServiceImpl.getLogPosition(TransactionLogServiceImpl.java:139) ~[neo4j-kernel-4.4.15.jar:4.4.15]
        ... 96 more
2023-09-12 07:51:34.044+0000 ERROR [c.n.c.p.i.ServerChannelInitializer] [catchup-server] Exception in inbound for channel: [id: 0x28ebc214, L:/172.17.0.2:6000 - R:/
10.20.5.188:37894]
java.lang.IllegalArgumentException: Transaction id 455257799 not found in transaction logs.
```

Starting with a fresh read replica does not resolve this issue, and we are unable to really figure out why.  With that being said we wanted to restart the `SINGLE` node but were afraid of any potential corruption it contained from transaction logs etc, and upon taking an online backup we received the following:

```
2023-09-13 04:36:17.812+0000 INFO  [c.n.b.v.BackupOutputMonitor] Finished, took 2h 40m 32s 424ms
2023-09-13 04:36:17.812+0000 ERROR [c.n.b.v.OnlineBackupExecutor] Error in database neo4j
com.neo4j.backup.v1.BackupExecutionException: com.neo4j.causalclustering.catchup.storecopy.StoreCopyFailedException: com.neo4j.causalclustering.catchup.storecopy.StoreCopyFailedException: Pulling tx failed consecutively without progress
        at com.neo4j.backup.v1.OnlineDatabaseBackup.backup(OnlineDatabaseBackup.java:83) ~[neo4j-backup-4.4.15.jar:4.4.15]
        at com.neo4j.backup.v1.OnlineBackupExecutor.executeBackups(OnlineBackupExecutor.java:97) [neo4j-backup-4.4.15.jar:4.4.15]
        at com.neo4j.backup.v1.OnlineBackupCommand.execute(OnlineBackupCommand.java:163) [neo4j-backup-4.4.15.jar:4.4.15]
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:71) [neo4j-command-line-4.4.15.jar:4.4.15]
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:34) [neo4j-command-line-4.4.15.jar:4.4.15]
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
        at picocli.CommandLine.access$1300(CommandLine.java:145) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
        at picocli.CommandLine.execute(CommandLine.java:2078) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
        at org.neo4j.cli.AdminTool.execute(AdminTool.java:93) [neo4j-command-line-4.4.15.jar:4.4.15]
        at org.neo4j.cli.AdminTool.main(AdminTool.java:79) [neo4j-command-line-4.4.15.jar:4.4.15]
Caused by: com.neo4j.causalclustering.catchup.storecopy.StoreCopyFailedException: com.neo4j.causalclustering.catchup.storecopy.StoreCopyFailedException: Pulling tx failed consecutively without progress
        at com.neo4j.causalclustering.catchup.storecopy.RemoteStore.pullTransactions(RemoteStore.java:193) ~[neo4j-causal-clustering-4.4.15.jar:4.4.15]
        at com.neo4j.causalclustering.catchup.storecopy.RemoteStore.copy(RemoteStore.java:142) ~[neo4j-causal-clustering-4.4.15.jar:4.4.15]
        at com.neo4j.causalclustering.catchup.storecopy.RemoteStore.copy(RemoteStore.java:124) ~[neo4j-causal-clustering-4.4.15.jar:4.4.15]
        at com.neo4j.backup.v1.remote.BackupClient.fullStoreCopy(BackupClient.java:209) ~[neo4j-backup-4.4.15.jar:4.4.15]
        at com.neo4j.backup.v1.OnlineDatabaseBackup.retrieveRemoteStore(OnlineDatabaseBackup.java:124) ~[neo4j-backup-4.4.15.jar:4.4.15]
        at com.neo4j.backup.v1.OnlineDatabaseBackup.backup(OnlineDatabaseBackup.java:62) ~[neo4j-backup-4.4.15.jar:4.4.15]
        ... 13 more
Caused by: com.neo4j.causalclustering.catchup.storecopy.StoreCopyFailedException: Pulling tx failed consecutively without progress
        at com.neo4j.causalclustering.catchup.storecopy.TxPuller.checkProgress(TxPuller.java:195) ~[neo4j-causal-clustering-4.4.15.jar:4.4.15]
        at com.neo4j.causalclustering.catchup.storecopy.TxPuller.updateState(TxPuller.java:174) ~[neo4j-causal-clustering-4.4.15.jar:4.4.15]
        at com.neo4j.causalclustering.catchup.storecopy.TxPuller.pullTransactions(TxPuller.java:84) ~[neo4j-causal-clustering-4.4.15.jar:4.4.15]
        at com.neo4j.causalclustering.catchup.storecopy.RemoteStore.pullTransactions(RemoteStore.java:186) ~[neo4j-causal-clustering-4.4.15.jar:4.4.15]
        at com.neo4j.causalclustering.catchup.storecopy.RemoteStore.copy(RemoteStore.java:142) ~[neo4j-causal-clustering-4.4.15.jar:4.4.15]
        at com.neo4j.causalclustering.catchup.storecopy.RemoteStore.copy(RemoteStore.java:124) ~[neo4j-causal-clustering-4.4.15.jar:4.4.15]
        at com.neo4j.backup.v1.remote.BackupClient.fullStoreCopy(BackupClient.java:209) ~[neo4j-backup-4.4.15.jar:4.4.15]
        at com.neo4j.backup.v1.OnlineDatabaseBackup.retrieveRemoteStore(OnlineDatabaseBackup.java:124) ~[neo4j-backup-4.4.15.jar:4.4.15]
        at com.neo4j.backup.v1.OnlineDatabaseBackup.backup(OnlineDatabaseBackup.java:62) ~[neo4j-backup-4.4.15.jar:4.4.15]
        ... 13 more
org.neo4j.cli.CommandFailedException: Execution of backup failed. Pulling tx failed consecutively without progress
        at com.neo4j.backup.v1.OnlineBackupCommand.execute(OnlineBackupCommand.java:172)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:71)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:34)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.neo4j.cli.AdminTool.execute(AdminTool.java:93)
        at org.neo4j.cli.AdminTool.main(AdminTool.java:79)
Caused by: com.neo4j.backup.v1.BackupExecutionException: com.neo4j.causalclustering.catchup.storecopy.StoreCopyFailedException: com.neo4j.causalclustering.catchup.storecopy.StoreCopyFailedException: Pulling tx failed consecutively without progress
        at com.neo4j.backup.v1.OnlineDatabaseBackup.backup(OnlineDatabaseBackup.java:83)
        at com.neo4j.backup.v1.OnlineBackupExecutor.executeBackups(OnlineBackupExecutor.java:97)
        at com.neo4j.backup.v1.OnlineBackupCommand.execute(OnlineBackupCommand.java:163)
        ... 11 more
Caused by: com.neo4j.causalclustering.catchup.storecopy.StoreCopyFailedException: com.neo4j.causalclustering.catchup.storecopy.StoreCopyFailedException: Pulling tx failed consecutively without progress
        at com.neo4j.causalclustering.catchup.storecopy.RemoteStore.pullTransactions(RemoteStore.java:193)
        at com.neo4j.causalclustering.catchup.storecopy.RemoteStore.copy(RemoteStore.java:142)
        at com.neo4j.causalclustering.catchup.storecopy.RemoteStore.copy(RemoteStore.java:124)
        at com.neo4j.backup.v1.remote.BackupClient.fullStoreCopy(BackupClient.java:209)
        at com.neo4j.backup.v1.OnlineDatabaseBackup.retrieveRemoteStore(OnlineDatabaseBackup.java:124)
        at com.neo4j.backup.v1.OnlineDatabaseBackup.backup(OnlineDatabaseBackup.java:62)
        ... 13 more
Caused by: com.neo4j.causalclustering.catchup.storecopy.StoreCopyFailedException: Pulling tx failed consecutively without progress
        at com.neo4j.causalclustering.catchup.storecopy.TxPuller.checkProgress(TxPuller.java:195)
        at com.neo4j.causalclustering.catchup.storecopy.TxPuller.updateState(TxPuller.java:174)
        at com.neo4j.causalclustering.catchup.storecopy.TxPuller.pullTransactions(TxPuller.java:84)
        at com.neo4j.causalclustering.catchup.storecopy.RemoteStore.pullTransactions(RemoteStore.java:186)
        ... 18 more
```

My question is - is it safe to restart the main database?  What would be the cause of the `catchup` part of Causal Clustering becoming corrupted and how exactly do we fix this?

Thanks in advance and please let me know if there are any additional details we can provide!

**Comment by jbkc85** [comment]
one note:

our data store is roughly 1.1TB.  The setting https://neo4j.com/docs/operations-manual/4.4/configuration/configuration-settings/#config_causal_clustering.store_copy_max_retry_time_per_request is default, so set to 20m, so im wondering...is this error actually a timeout?

**Comment by jbkc85** [comment]
from the note above, it still doesn't explain the `online` backup i took and the errors that came from it.  So I am still confused :-).

**Comment by jbkc85** [comment]
another note: I am looking at the incremental backup strategies currently.  We are using `UNBOUNDED` but have a very high throughput environment, on top of the fact that we have a very high volume of data, meaning that it could be possible our transactions disappear or are rotated prior to a backup being complete.  I am not sure if this will help the catch up process.

**Comment by jbkc85** [comment]
all, the issue actually is with the fact that the `dbms.tx_log.rotation.retention_policy` setting (we set it to `1 hours`) was not set long enough for the causal cluster read_replica to join and read the available transactions.  Given the process takes roughly 2-3 hours over the catch up process, the transactions had to be set to be retained long enough for after the neo4j backup/restore/integrity checks were passed on the read_replica.  I ended up setting the `dbms.tx_log.rotation.retention_policy` to `6 hours` and things worked out as expected.

The original error, commenting about 'unable to find transaction' makes a bit more sense now.

That being said, the error that came from the `neo4j-admin backup` (second collection of logs) is extremely confusing for this particular issue - if it is related as i have yet to test the backup with the log retention being past the amount of time it needs for a backup.

Furthermore, back to the original issue w/ causal clustering - im curious on why the current transaction logs are not copied over during the initial restore to 'backup' the TX's in the situation that the log rotation on the cluster's nodes (SINGLE or CORE deployments) dont delete the TX's in the middle of a given process as we have seen here.

**Comment by RagnarW** [comment]
Hey, @jbkc85 . I am know this answer is very late and I apologise for that.

It's great to see that you where able to configure the retention policies.

On your final note, the backup service does not stop any configured log pruning from happening so its important that the production system keep a history of logs to allow your diff (or incremental) backups to keep up.

Again sorry for the late reply. I will close this issue now.
