### ISSUE TITLE
Neo4j stops accepting connections

### ISSUE THREAD

**Issue by awatertrevi** [neo4j/neo4j#13310]
When running our systems after a unspecified amount of time we see the following stacktrace:

```
2023-09-25 09:51:07.448+0000 ERROR [bolt-678] Terminating connection due to unexpected error
org.neo4j.bolt.protocol.error.streaming.BoltStreamingWriteException: Failed to transmit operation result: Response write failure
	at org.neo4j.bolt.protocol.common.fsm.response.NetworkResponseHandler.onSuccess(NetworkResponseHandler.java:184) ~[neo4j-bolt-5.10.0.jar:5.10.0]
	at org.neo4j.bolt.protocol.common.fsm.AbstractStateMachine.after(AbstractStateMachine.java:112) ~[neo4j-bolt-5.10.0.jar:5.10.0]
	at org.neo4j.bolt.protocol.common.fsm.AbstractStateMachine.process(AbstractStateMachine.java:88) ~[neo4j-bolt-5.10.0.jar:5.10.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.lambda$submit$4(AtomicSchedulingConnection.java:122) ~[neo4j-bolt-5.10.0.jar:5.10.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.executeJob(AtomicSchedulingConnection.java:344) ~[neo4j-bolt-5.10.0.jar:5.10.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.doExecuteJobs(AtomicSchedulingConnection.java:279) ~[neo4j-bolt-5.10.0.jar:5.10.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.executeJobs(AtomicSchedulingConnection.java:221) ~[neo4j-bolt-5.10.0.jar:5.10.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.93.Final.jar:4.1.93.Final]
2023-09-25 09:51:21.114+0000 ERROR Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: Cannot invoke "org.neo4j.packstream.codec.transport.ChunkFrameDecoder.unlimited()" because "oldDecoder" is null, reference 02ccb4f4-3976-469c-9dbb-0e402823f3e0.
2023-09-25 09:51:21.114+0000 ERROR Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: org.neo4j.bolt.protocol.common.handler.AuthenticationTimeoutHandler, reference 16c348bd-cc13-4da1-bc30-9df539eda58b.
2023-09-25 09:51:21.114+0000 ERROR Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: org.neo4j.bolt.protocol.common.handler.AuthenticationTimeoutHandler, reference 108d6cad-cdce-4e0c-bab8-c762d8c707f5.
```

# Setup:

- Neo4j version: 5.10.0
- Operating system: Ubuntu 16.04
- API/Driver: https://github.com/DotNet4Neo4j/Neo4jClient
- Expected behavior: Don't crash
- Actual behavior: Unable to create connections to the database, from both the driver/browser.

**Comment by awatertrevi** [comment]
Upgraded Neo4j to 5.12.0, issue still persists.

**Comment by TheAnarchoX** [comment]
I work with @awatertrevi , and thought I'd give some insight in how this database is hosted.

We run 1 instance with 2 databases (dev/prod) ĳon 1 Standard E16ads v5 Azure VM (16 vCPU, 128GB Ram). Connections happen over Bolt. We have a cron job which backs up the primary of the 2 databases, which results in a bit of high CPU usage but the failures don't correlate with them. 

Our data drive is an attached Premium SSD 1TB drive from Azure (5K IOPS, 200mbps throughput).

We use the Neo4J Ops Manager to keep an eye on the system but it hasn't really been helpful, could just be we are not utilizing the logs search in the most efficient way.

@awatertrevi can provide our neo4j.conf for reference if necessary

**Comment by thelonelyvulpes** [comment]
Hello,

The exception that is occurring is happening at very interesting point, during authentication. 
What authentication mechanisms are you using? 
Would you be able to provide debug logging? 

Could you provide any context when this issue started occurring:
- New application deployed which started seeing errors
- New driver version
- New Server

**Comment by TheAnarchoX** [comment]
We narrowed the issue down to being a combination of transient connections to the database and (insanely) large bulk inserts of a specific node type which went way over our allocated memory. We resolved the issue by implementing batching on inserts for the node type,

**Comment by awatertrevi** [comment]
In addition to @TheAnarchoX , while the query was indeed huge. There was also a mistake in the query itself, we were somehow trying to assingn an object to a propert. Normaly Neo4j throws a proper error when attempting to do this. But strangly enough not with our huge query.

**Comment by thelonelyvulpes** [comment]
I'm glad to hear you have resolved the issue with connections @awatertrevi & @TheAnarchoX are we okay to close this issue?
If you want to open an issue regarding a large query not correctly raising errors that would be helpful to avoid this issue becoming confusing.

**Comment by TheAnarchoX** [comment]
Yes this can be closed
