### ISSUE TITLE
HttpConnector in embedded db with Spring Boot brings ClassNotFoundException

### ISSUE THREAD

**Issue by Podbrushkin** [neo4j/neo4j#13346]
HttpConnector doesn't work in embedded database in Spring Boot application. Example below uses SDN, but I think it doesn't work with raw Spring Boot also.

### Steps to reproduce

1. Get this sample project: https://github.com/spring-guides/gs-accessing-data-neo4j/tree/main/complete
2. To `pom.xml` add:
```
<dependency>
	<groupId>org.neo4j</groupId>
	<artifactId>neo4j</artifactId>
	<version>5.13.0</version>
</dependency>
```
3. To `AccessingDataNeo4jApplication.java` add embedded server startup logic:
```
@Bean
public Configuration cypherDslConfiguration() {
	return Configuration.newConfig().withDialect(Dialect.NEO4J_5).build();
}

@Bean
public DatabaseManagementService databaseManagementService() {
	DatabaseManagementService managementService = new 
		DatabaseManagementServiceBuilder(new File("target/mydb").toPath())
			.setConfig(GraphDatabaseSettings.transaction_timeout, Duration.ofSeconds( 60 ) )
			.setConfig( BoltConnector.enabled, true )
			// .setConfig( BoltConnector.listen_address, new SocketAddress( "localhost", 7687 ) )
			.setConfig(BoltConnector.encryption_level, BoltConnector.EncryptionLevel.DISABLED)
			// Uncomment this and you will get `java.lang.ClassNotFoundException: javax.servlet.Filter`:
			// .setConfig(HttpConnector.enabled, true)
			// .setConfig(HttpConnector.listen_address, new SocketAddress("localhost", 7474))
			.build();
	
	registerShutdownHook(managementService);
	return managementService;
}

@Bean
public GraphDatabaseService graphDatabaseService(DatabaseManagementService managementService) {
	// managementService.createDatabase("mydb");
	GraphDatabaseService graphDb =
		managementService.database(GraphDatabaseSettings.DEFAULT_DATABASE_NAME);
	log.info("Neo4j database Embedded instance is available: {}", graphDb.isAvailable());
	return graphDb;
}

/* @Bean
public Driver neo4jDriver() {
	return GraphDatabase.driver("http://localhost:7687");
} */

private static void registerShutdownHook(final DatabaseManagementService managementService) {
	Runtime.getRuntime().addShutdownHook(new Thread() {
		@Override
		public void run() {
			managementService.shutdown();
		}
	});
}
```
4. Start it - everything works fine. Stop it.
5. Uncomment `.setConfig(HttpConnector.enabled, true)`
6. Enjoy `java.lang.ClassNotFoundException: javax.servlet.Filter`:
<details>
<summary>Exception stack trace</summary>

```
2023-11-17T14:49:06.206+03:00  WARN 10848 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'databaseManagementService' defined in com.example.accessingdataneo4j.AccessingDataNeo4jApplication: Failed to instantiate [org.neo4j.dbms.api.DatabaseManagementService]: Factory method 'databaseManagementService' threw exception with message: Error starting Neo4j database server at C:\Users\user\Desktop\delmeSpringDataNeo4jRepo\target\mydb\data\databases
2023-11-17T14:49:06.211+03:00  INFO 10848 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger :

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-11-17T14:49:06.220+03:00 ERROR 10848 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'databaseManagementService' defined in com.example.accessingdataneo4j.AccessingDataNeo4jApplication: Failed to instantiate [org.neo4j.dbms.api.DatabaseManagementService]: Factory method 'databaseManagementService' threw exception with message: Error starting Neo4j database server at C:\Users\user\Desktop\delmeSpringDataNeo4jRepo\target\mydb\data\databases
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659) ~[spring-beans-6.0.9.jar:6.0.9]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:493) ~[spring-beans-6.0.9.jar:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332) ~[spring-beans-6.0.9.jar:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162) ~[spring-beans-6.0.9.jar:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.9.jar:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.9.jar:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.9.jar:6.0.9]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.9.jar:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.9.jar:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.9.jar:6.0.9]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.9.jar:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:941) ~[spring-context-6.0.9.jar:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[spring-context-6.0.9.jar:6.0.9]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733) ~[spring-boot-3.1.0.jar:3.1.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435) ~[spring-boot-3.1.0.jar:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[spring-boot-3.1.0.jar:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305) ~[spring-boot-3.1.0.jar:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294) ~[spring-boot-3.1.0.jar:3.1.0]
        at com.example.accessingdataneo4j.AccessingDataNeo4jApplication.main(AccessingDataNeo4jApplication.java:32) ~[classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.neo4j.dbms.api.DatabaseManagementService]: Factory method 'databaseManagementService' threw exception with message: Error starting Neo4j database server at C:\Users\user\Desktop\delmeSpringDataNeo4jRepo\target\mydb\data\databases
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.9.jar:6.0.9]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-6.0.9.jar:6.0.9]
        ... 18 common frames omitted
Caused by: java.lang.RuntimeException: Error starting Neo4j database server at C:\Users\user\Desktop\delmeSpringDataNeo4jRepo\target\mydb\data\databases
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:272) ~[neo4j-5.13.0.jar:5.13.0]
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:208) ~[neo4j-5.13.0.jar:5.13.0]
        at org.neo4j.dbms.api.DatabaseManagementServiceBuilderImplementation.newDatabaseManagementService(DatabaseManagementServiceBuilderImplementation.java:84) ~[neo4j-5.13.0.jar:5.13.0]
        at org.neo4j.dbms.api.DatabaseManagementServiceBuilderImplementation.build(DatabaseManagementServiceBuilderImplementation.java:79) ~[neo4j-5.13.0.jar:5.13.0]
        at org.neo4j.dbms.api.DatabaseManagementServiceBuilder.build(DatabaseManagementServiceBuilder.java:42) ~[neo4j-5.13.0.jar:5.13.0]
        at com.example.accessingdataneo4j.AccessingDataNeo4jApplication.databaseManagementService(AccessingDataNeo4jApplication.java:52) ~[classes/:na]
        at com.example.accessingdataneo4j.AccessingDataNeo4jApplication$$SpringCGLIB$$0.CGLIB$databaseManagementService$0(<generated>) ~[classes/:na]
        at com.example.accessingdataneo4j.AccessingDataNeo4jApplication$$SpringCGLIB$$2.invoke(<generated>) ~[classes/:na]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.0.9.jar:6.0.9]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-6.0.9.jar:6.0.9]
        at com.example.accessingdataneo4j.AccessingDataNeo4jApplication$$SpringCGLIB$$0.databaseManagementService(<generated>) ~[classes/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.9.jar:6.0.9]
        ... 19 common frames omitted
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.AbstractNeoWebServer$ServerComponentsLifecycleAdapter@39ae6408' failed to initialize. Please see the attached cause exception "javax.servlet.Filter".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:335) ~[neo4j-common-5.13.0.jar:5.13.0]
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:57) ~[neo4j-common-5.13.0.jar:5.13.0]
        at org.neo4j.server.AbstractNeoWebServer.init(AbstractNeoWebServer.java:184) ~[neo4j-server-5.13.0.jar:5.13.0]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:318) ~[neo4j-common-5.13.0.jar:5.13.0]
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:57) ~[neo4j-common-5.13.0.jar:5.13.0]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:86) ~[neo4j-common-5.13.0.jar:5.13.0]
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:263) ~[neo4j-5.13.0.jar:5.13.0]
        ... 32 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/servlet/Filter
        at org.neo4j.server.CommunityNeoWebServer.createWebServer(CommunityNeoWebServer.java:97) ~[neo4j-server-5.13.0.jar:5.13.0]
        at org.neo4j.server.AbstractNeoWebServer$ServerComponentsLifecycleAdapter.init(AbstractNeoWebServer.java:423) ~[neo4j-server-5.13.0.jar:5.13.0]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:318) ~[neo4j-common-5.13.0.jar:5.13.0]
        ... 38 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.servlet.Filter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
        ... 41 common frames omitted
```

</details>

**Comment by michael-simons** [comment]
Using the http connector inside another web environment such as Spring Boot is not recommended. You might get it to work using Spring Boot Webmvc with Jetty instead of tomcat. 

Here you’ll run into the fact that Boot made the switch to Jakarta EE and we didn’t yet. 

Also the driver that you commented out does not connect over http anyway. If your end goal is to use the driver, stick to Bolt please.
