### ISSUE TITLE
Java driver hangs with manual transaction handling

### ISSUE THREAD

**Issue by dsukhoroslov** [neo4j/neo4j#13353]
Hi,

- tried with neo4j-java-driver v4.4.x and 5.3.0. neo4j-java-driver-spring-boot-starter v4.3.6.0 and neo4j-harness v4.4.10 are also used. 
- on DB side tried with Neo4J 4.4.12 docker image and Embedded Neo4J.
- tested on Windows 10 laptop.

I need Neo4J Java Driver to participate in Spring Transactions, together with regular RDBMS (Hibernate/Postgres). As there is no Spring Tx support in this Spring Boot Starter I'm trying to get required behavior with Spring 
`TransactionSynchronizationManager`. I register a custom `TransactionSynchronization` (synchronizer) class in `TransactionSynchronizationManager` resources, it gets `Session` from `Driver` instance, begins new `Transaction` and caches it. Then all subsequent requests are handled with this `Transaction` instance. When global Spring transaction is complete, the synchronizer instance is invoked in `beforeCompletion/afterCompletion` methods. Here we can commit/rollback current Neo4j transaction, then Neo4J `Session` is closed and synchronizer is unbound from `TransactionSynchronizationManager`. 

With simple updates it works fine: Neo4j transaction started, then updates applied to DB and transaction commited, see app logs:
```
2022-12-14 11:20:55.060 DEBUG 14832 --- [main] e.g.d.f.c.s.g.impl.Neo4jGraphStore       : registerTxSynchronizer.enter; found resources: {org.hibernate.internal.SessionFactoryImpl@37a53e65=org.springframework.orm.hibernate5.SessionHolder@28f63018, io.zonky.test.db.provider.support.BlockingDatabaseWrapper@2cf7ada5=org.springframework.jdbc.datasource.ConnectionHolder@56cdf69b}
2022-12-14 11:20:55.063 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.async.pool.NettyChannelTracker   : Channel [0xc5dc5abd] acquired from the pool. Local address: /127.0.0.1:4636, remote address: localhost/127.0.0.1:7687
2022-12-14 11:20:55.068 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.o.OutboundMessageHandler       : [0xc5dc5abd][localhost:7687][bolt-14989] C: BEGIN {}
2022-12-14 11:20:55.076 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.i.InboundMessageDispatcher     : [0xc5dc5abd][localhost:7687][bolt-14989] S: SUCCESS {}
2022-12-14 11:20:55.077 DEBUG 14832 --- [main] e.g.d.f.c.s.g.impl.Neo4jGraphStore       : registerTxSynchronizer.exit; returning new synch: eu.gaiax.difs.fc.core.service.graphdb.impl.Neo4jTxSynchronizer@28062c6a
2022-12-14 11:20:55.109 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.o.OutboundMessageHandler       : [0xc5dc5abd][localhost:7687][bolt-14989] C: RUN "CALL n10s.rdf.import.inline($payload, "N-Triples");" {payload="<did:example:credSub> <http://w3id.org/gaia-x/service#claimsGraphUri> \"did:example:issuer\" .
<did:example:credSub> <http://xmlns.com/foaf/0.1/givenname> \"Fredrik\" .
<did:example:credSub> <http://xmlns.com/foaf/0.1/family_name> \"Str&#246;mberg\" .
<did:example:credSub> <http://schema.org/birthdate> \"1949-01-22\" .
<did:example:credSub> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://w3id.org/gaia-x/participant#LegalPerson> .
"} {}
2022-12-14 11:20:55.109 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.o.OutboundMessageHandler       : [0xc5dc5abd][localhost:7687][bolt-14989] C: PULL {n=1000}
2022-12-14 11:20:55.119 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.i.InboundMessageDispatcher     : [0xc5dc5abd][localhost:7687][bolt-14989] S: SUCCESS {t_first=0, fields=["terminationStatus", "triplesLoaded", "triplesParsed", "namespaces", "extraInfo", "callParams"], qid=0}
2022-12-14 11:20:55.120 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.i.InboundMessageDispatcher     : [0xc5dc5abd][localhost:7687][bolt-14989] S: RECORD ["OK", 5, 5, NULL, "", {}]
2022-12-14 11:20:55.122 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.i.InboundMessageDispatcher     : [0xc5dc5abd][localhost:7687][bolt-14989] S: SUCCESS {type="rw", t_last=4, db="neo4j"}
2022-12-14 11:20:55.240 DEBUG 14832 --- [main] e.g.d.f.c.s.g.impl.Neo4jTxSynchronizer   : beforeCommit.enter; readOnly: false, failed: false
2022-12-14 11:20:55.240 DEBUG 14832 --- [main] e.g.d.f.c.s.g.impl.Neo4jTxSynchronizer   : beforeCompletion.enter;
2022-12-14 11:20:55.240 DEBUG 14832 --- [main] o.s.o.h.HibernateTransactionManager      : Initiating transaction commit
2022-12-14 11:20:55.240 DEBUG 14832 --- [main] o.s.o.h.HibernateTransactionManager      : Committing Hibernate transaction on Session [SessionImpl(938948679<open>)]
2022-12-14 11:20:55.240 DEBUG 14832 --- [main] e.g.d.f.c.s.g.impl.Neo4jTxSynchronizer   : afterCommit.enter;
2022-12-14 11:20:55.241 DEBUG 14832 --- [main] e.g.d.f.c.s.g.impl.Neo4jTxSynchronizer   : afterCompletion.enter; status: 0, tx open: true
2022-12-14 11:20:55.246 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.o.OutboundMessageHandler       : [0xc5dc5abd][localhost:7687][bolt-14989] C: COMMIT
2022-12-14 11:20:55.249 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.i.InboundMessageDispatcher     : [0xc5dc5abd][localhost:7687][bolt-14989] S: SUCCESS {bookmark="FB:kcwQYo/aYX5YS42X1xOfO+qjljGQ"}
2022-12-14 11:20:55.250 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.o.OutboundMessageHandler       : [0xc5dc5abd][localhost:7687][bolt-14989] C: RESET
2022-12-14 11:20:55.254 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.i.InboundMessageDispatcher     : [0xc5dc5abd][localhost:7687][bolt-14989] S: SUCCESS {}
2022-12-14 11:20:55.254 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.async.pool.NettyChannelTracker   : Channel [0xc5dc5abd] released back to the pool
2022-12-14 11:20:55.255 DEBUG 14832 --- [main] e.g.d.f.c.s.g.impl.Neo4jTxSynchronizer   : afterCompletion.exit; 
```

With several updates (delete, update, insert) affecting same node it hangs:
```
2022-12-14 11:20:56.436 DEBUG 14832 --- [main] o.s.o.h.HibernateTransactionManager      : Found thread-bound Session [SessionImpl(1668901401<open>)] for Hibernate transaction
2022-12-14 11:20:56.436 DEBUG 14832 --- [main] o.s.o.h.HibernateTransactionManager      : Participating in existing transaction
2022-12-14 11:20:56.489 DEBUG 14832 --- [main] o.s.o.h.HibernateTransactionManager      : Found thread-bound Session [SessionImpl(1668901401<open>)] for Hibernate transaction
2022-12-14 11:20:56.489 DEBUG 14832 --- [main] o.s.o.h.HibernateTransactionManager      : Participating in existing transaction
2022-12-14 11:20:56.489 DEBUG 14832 --- [main] e.g.d.f.c.s.g.impl.Neo4jGraphStore       : registerTxSynchronizer.enter; found resources: {org.hibernate.internal.SessionFactoryImpl@37a53e65=org.springframework.orm.hibernate5.SessionHolder@26104214, io.zonky.test.db.provider.support.BlockingDatabaseWrapper@2cf7ada5=org.springframework.jdbc.datasource.ConnectionHolder@654d7914}
2022-12-14 11:20:56.490 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.async.pool.NettyChannelTracker   : Channel [0xc5dc5abd] acquired from the pool. Local address: /127.0.0.1:4636, remote address: localhost/127.0.0.1:7687
2022-12-14 11:20:56.491 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.o.OutboundMessageHandler       : [0xc5dc5abd][localhost:7687][bolt-14989] C: BEGIN {}
2022-12-14 11:20:56.495 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.i.InboundMessageDispatcher     : [0xc5dc5abd][localhost:7687][bolt-14989] S: SUCCESS {}
2022-12-14 11:20:56.495 DEBUG 14832 --- [main] e.g.d.f.c.s.g.impl.Neo4jGraphStore       : registerTxSynchronizer.exit; returning new synch: eu.gaiax.difs.fc.core.service.graphdb.impl.Neo4jTxSynchronizer@44798d81
2022-12-14 11:20:56.496 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.o.OutboundMessageHandler       : [0xc5dc5abd][localhost:7687][bolt-14989] C: RUN "MATCH (n {claimsGraphUri: [$uri]})
DETACH DELETE n;" {uri="did:example:issuer"} {}
2022-12-14 11:20:56.496 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.o.OutboundMessageHandler       : [0xc5dc5abd][localhost:7687][bolt-14989] C: PULL {n=1000}
2022-12-14 11:20:56.504 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.i.InboundMessageDispatcher     : [0xc5dc5abd][localhost:7687][bolt-14989] S: SUCCESS {t_first=4, fields=[], qid=0}
2022-12-14 11:20:56.506 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.i.InboundMessageDispatcher     : [0xc5dc5abd][localhost:7687][bolt-14989] S: SUCCESS {type="w", stats={contains-updates: TRUE, nodes-deleted: 1}, t_last=0, db="neo4j"}
2022-12-14 11:20:56.522 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.o.OutboundMessageHandler       : [0xc5dc5abd][localhost:7687][bolt-14989] C: RUN "MATCH (n) WHERE $uri IN n.claimsGraphUri
SET n.claimsGraphUri = [g IN n.claimsGraphUri WHERE g <> $uri];" {uri="did:example:issuer"} {}
2022-12-14 11:20:56.523 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.o.OutboundMessageHandler       : [0xc5dc5abd][localhost:7687][bolt-14989] C: PULL {n=1000}
2022-12-14 11:20:56.529 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.i.InboundMessageDispatcher     : [0xc5dc5abd][localhost:7687][bolt-14989] S: SUCCESS {t_first=1, fields=[], qid=1}
2022-12-14 11:20:56.530 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.i.InboundMessageDispatcher     : [0xc5dc5abd][localhost:7687][bolt-14989] S: SUCCESS {type="w", t_last=0, db="neo4j"}
2022-12-14 11:20:56.530 DEBUG 14832 --- [main] o.s.o.h.HibernateTransactionManager      : Found thread-bound Session [SessionImpl(1668901401<open>)] for Hibernate transaction
2022-12-14 11:20:56.530 DEBUG 14832 --- [main] o.s.o.h.HibernateTransactionManager      : Participating in existing transaction
2022-12-14 11:20:56.530 DEBUG 14832 --- [main] e.g.d.f.c.s.g.impl.Neo4jGraphStore       : registerTxSynchronizer.enter; found resources: {org.hibernate.internal.SessionFactoryImpl@37a53e65=org.springframework.orm.hibernate5.SessionHolder@26104214, neo4j=eu.gaiax.difs.fc.core.service.graphdb.impl.Neo4jTxSynchronizer@44798d81, io.zonky.test.db.provider.support.BlockingDatabaseWrapper@2cf7ada5=org.springframework.jdbc.datasource.ConnectionHolder@654d7914}
2022-12-14 11:20:56.530 DEBUG 14832 --- [main] e.g.d.f.c.s.g.impl.Neo4jGraphStore       : registerTxSynchronizer.exit; returning existing synch: eu.gaiax.difs.fc.core.service.graphdb.impl.Neo4jTxSynchronizer@44798d81
2022-12-14 11:20:56.534 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.o.OutboundMessageHandler       : [0xc5dc5abd][localhost:7687][bolt-14989] C: RUN "CALL n10s.rdf.import.inline($payload, "N-Triples");" {payload="<did:example:credSub> <http://w3id.org/gaia-x/service#claimsGraphUri> \"did:example:issuer\" .
<did:example:credSub> <http://xmlns.com/foaf/0.1/givenname> \"Fredrik\" .
<did:example:credSub> <http://xmlns.com/foaf/0.1/family_name> \"Str&#246;mberg\" .
<did:example:credSub> <http://schema.org/birthdate> \"1949-01-22\" .
<did:example:credSub> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://w3id.org/gaia-x/participant#LegalPerson> .
"} {}
2022-12-14 11:20:56.535 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.o.OutboundMessageHandler       : [0xc5dc5abd][localhost:7687][bolt-14989] C: PULL {n=1000}
2022-12-14 11:22:39.845 DEBUG 14832 --- [Neo4jDriverIO-2-4] o.n.d.i.a.i.InboundMessageDispatcher     : [0xc5dc5abd][localhost:7687][bolt-14989] S: SUCCESS {t_first=1, fields=["terminationStatus", "triplesLoaded", "triplesParsed", "namespaces", "extraInfo", "callParams"], qid=2}
```
on the last call to insert new triples main thread hangs waiting for results from Neo4JDriverIO thread. And Neo4JDriverIO thread remains in running state, but doesn't provide expected results:
```
"Neo4jDriverIO-2-4" - Thread t@28
   java.lang.Thread.State: RUNNABLE
	at java.base@11.0.14/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at java.base@11.0.14/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:357)
	at java.base@11.0.14/sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:182)
	at java.base@11.0.14/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
	- locked <2e266f3d> (a org.neo4j.driver.internal.shaded.io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <31e8c77f> (a sun.nio.ch.WindowsSelectorImpl)
	at java.base@11.0.14/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:141)
	at app//org.neo4j.driver.internal.shaded.io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
	at app//org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:813)
	at app//org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at app//org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at app//org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at app//org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.14/java.lang.Thread.run(Thread.java:834)

   Locked ownable synchronizers:
	- None

"main" - Thread t@1
   java.lang.Thread.State: WAITING
	at java.base@11.0.14/jdk.internal.misc.Unsafe.park(Native Method)
	- parking to wait for <6fd40f2> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.base@11.0.14/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.14/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
	at java.base@11.0.14/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
	at java.base@11.0.14/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
	at java.base@11.0.14/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998)
	at app//org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:129)
	at app//org.neo4j.driver.internal.InternalResult.blockingGet(InternalResult.java:122)
	at app//org.neo4j.driver.internal.InternalResult.consume(InternalResult.java:111)
	at app//eu.gaiax.difs.fc.core.service.graphdb.impl.Neo4jGraphStore.addClaims(Neo4jGraphStore.java:99)
```
There are no any errors in server logs. 

Please help me to make it working.

**Comment by injectives** [comment]
Hello.

Thanks for your message. This issue has been transferred to the server repository as it looks like the driver waits for a response to the `PULL` message that does not come based on the following logs:
```
C: RUN "CALL n10s.rdf.import.inline($payload, "N-Triples");" {payload="<did:example:credSub> <http://w3id.org/gaia-x/service#claimsGraphUri> \"did:example:issuer\" .
<did:example:credSub> <http://xmlns.com/foaf/0.1/givenname> \"Fredrik\" .
<did:example:credSub> <http://xmlns.com/foaf/0.1/family_name> \"Str&#246;mberg\" .
<did:example:credSub> <http://schema.org/birthdate> \"1949-01-22\" .
<did:example:credSub> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://w3id.org/gaia-x/participant#LegalPerson> .
"} {}
C: PULL {n=1000}
S: SUCCESS {t_first=1, fields=["terminationStatus", "triplesLoaded", "triplesParsed", "namespaces", "extraInfo", "callParams"], qid=2}
```

Thanks.
