### ISSUE TITLE
Exception stacktraces are not printed through log output

### ISSUE THREAD

**Issue by TomVanWemmel** [neo4j/neo4j#13367]
We use Json format for our logging and have discovered that stacktraces are showing up in our server output. 

https://github.com/neo4j/neo4j/blob/5.14.0/community/bolt/src/main/java/org/neo4j/bolt/fsm/StateMachineImpl.java#L180

**Neo4j Version:** 5.14.0

### Steps to reproduce
Execute invalid Cypher or call an unknown procedure
 `CALL an.unknown.procedure()` 

### Expected behavior
Exception is logged in accordance with the logging configuration.

### Actual behavior
In Neo4j 5.13.0 nothing is logged for the above query
In Neo4j 5.14.0 a Stacktrace is printed on `System.err` by [StateMachineImpl](https://github.com/neo4j/neo4j/blob/5.14.0/community/bolt/src/main/java/org/neo4j/bolt/fsm/StateMachineImpl.java#L180)

```
org.neo4j.bolt.protocol.common.fsm.error.TransactionStateTransitionException: There is no procedure with the name `an.unknown.procedure` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
	at org.neo4j.bolt.protocol.common.fsm.transition.transaction.CreateStatementStateTransition.process(CreateStatementStateTransition.java:56)
	at org.neo4j.bolt.protocol.common.fsm.transition.transaction.CreateStatementStateTransition.process(CreateStatementStateTransition.java:32)
	at org.neo4j.bolt.protocol.common.fsm.transition.transaction.TransactionalStateTransition.process(TransactionalStateTransition.java:42)
	at org.neo4j.bolt.fsm.state.MultiTransitionState.process(MultiTransitionState.java:53)
	at org.neo4j.bolt.fsm.StateMachineImpl.process(StateMachineImpl.java:151)
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.lambda$submit$4(AtomicSchedulingConnection.java:122)
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.executeJob(AtomicSchedulingConnection.java:336)
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.doExecuteJobs(AtomicSchedulingConnection.java:315)
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.executeJobs(AtomicSchedulingConnection.java:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by dotStart** [comment]
Hey,
thanks for reporting this. Sadly this little debug statement has slipped through the cracks.

A fix for this has already been merged two weeks ago and is part of the 5.15 release, which should hopefully be available shortly. Sorry for the inconvenience.
