### ISSUE TITLE
Neo4j Load Error: Caused by: java.lang.IllegalStateException: Can not read store version of database

### ISSUE THREAD

**Issue by GSTovey** [neo4j/neo4j#13383]
I'm having trouble loading a dump file into neo4j database version5.15.0 in Windows 10

Neo4j Version:5.15.0
OS: Windows 10
Java Version:java 17.0.9 2023-10-17 LTS;Java(TM) SE Runtime Environment (build 17.0.9+11-LTS-201)

I run the command
 `neo4j-admin database load --from-path=C:/Users/86158/Desktop/Neo4jbackup neo4j-20230613 --overwrite-destination=true` 
and the error result is
`Failed to load database 'neo4j-20230613': Can not read store version of database neo4j-20230613Load failed for databases: 'neo4j-20230613'
org.neo4j.cli.CommandFailedException: Load failed for databases: 'neo4j-20230613'
        at org.neo4j.commandline.dbms.LoadCommand.checkFailure(LoadCommand.java:224)
        at org.neo4j.commandline.dbms.LoadCommand.loadDump(LoadCommand.java:212)
        at org.neo4j.commandline.dbms.LoadCommand.execute(LoadCommand.java:150)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:92)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.neo4j.cli.AdminTool.execute(AdminTool.java:94)
        at org.neo4j.cli.AdminTool.main(AdminTool.java:82)
Caused by: java.lang.IllegalStateException: Can not read store version of database neo4j-20230613
        at org.neo4j.commandline.dbms.StoreVersionLoader.loadStoreVersionAndCheckDowngrade(StoreVersionLoader.java:95)
        at org.neo4j.dbms.archive.Loader.getStoreVersion(Loader.java:132)
        at org.neo4j.commandline.dbms.LoadDumpExecutor.execute(LoadDumpExecutor.java:82)
        at org.neo4j.commandline.dbms.LoadCommand.loadDump(LoadCommand.java:202)
        ... 13 more
Caused by: java.lang.IllegalArgumentException: Unable to read store with version 'SF4.0.0'. Please make sure that database is migrated properly to be supported by current version of neo4j.
        at org.neo4j.kernel.impl.store.LegacyMetadataHandler.storeIdFromLegacyMetadata(LegacyMetadataHandler.java:146)
        at org.neo4j.kernel.impl.store.LegacyMetadataHandler.readMetadata44FromStore(LegacyMetadataHandler.java:98)
        at org.neo4j.kernel.impl.storemigration.RecordStoreVersionCheck.readVersion(RecordStoreVersionCheck.java:74)
        at org.neo4j.kernel.impl.storemigration.RecordStoreVersionCheck.getAndCheckUpgradeTargetVersion(RecordStoreVersionCheck.java:143)
        at org.neo4j.commandline.dbms.StoreVersionLoader.loadStoreVersionAndCheckDowngrade(StoreVersionLoader.java:92)
        ... 16 more`

I want to load the file successfully, thanks for your help!

**Comment by emmaholmbergohlsson** [comment]
Hey @GSTovey , looks like your dump was created on a version before 4.4. It is not supported to go directly from a version before 4.4 to 5.x.
You need to start a dbms of neo4j version 4.4, load the dump there and start the database with `dbms.allow_upgrade=true` set which will make the database migrate on the start up. And from there you can follow the 4->5 migration path to get your database into your 5.15 instance

For the dump -> 4.4 it is like this section but with load instead of restore https://neo4j.com/docs/upgrade-migration-guide/current/version-4/supported-paths/#restore-user-db
For 4.4->5 the documentation is here https://neo4j.com/docs/upgrade-migration-guide/current/version-5/migration/

**Comment by GSTovey** [comment]
Thanks for your reply!
It is indeed because my software version is too high that this error occurs, when I switched to a lower version of neo4j, everything ran normally.

**Comment by emmaholmbergohlsson** [comment]
Great that it solved the problem :tada: 
I'll close this issue then, feel free to create a new one if you run into more problems
