### ISSUE TITLE
Dump from Aura 5.22 cannot be loaded into desktop 5.21.2

### ISSUE THREAD

**Issue by nrouyer** [neo4j/neo4j#13494]
Details:
- Neo4j version: 5.21.2
- Aura version: 5.22-aura
- Operating system: MacOS

Steps to reproduce:
- take snapshot from Aura console
- use neo4j-admin database load CLI to load the dump

Expected behaviour:
- dump is loaded
Actual behaviour:
- error message **"The loaded database '<database>' is of a newer version than the current binaries."**
`./bin/neo4j-admin database load --from-path=/Users/nicolasrouyer/Documents/neo4j/demos/genai/assurance/insurance/assurance --overwrite-destination=true --verbose assurance
Executing command line: /Library/Java/JavaVirtualMachines/openjdk-21.jdk/Contents/Home/bin/java -cp /Users/nicolasrouyer/Library/Application Support/Neo4j Desktop/Application/relate-data/dbmss/dbms-85798d26-7ab2-4bde-99e2-36841024e327/plugins/*:/Users/nicolasrouyer/Library/Application Support/Neo4j Desktop/Application/relate-data/dbmss/dbms-85798d26-7ab2-4bde-99e2-36841024e327/conf/*:/Users/nicolasrouyer/Library/Application Support/Neo4j Desktop/Application/relate-data/dbmss/dbms-85798d26-7ab2-4bde-99e2-36841024e327/lib/* -XX:+UseParallelGC -XX:-OmitStackTraceInFastThrow -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:+DisableExplicitGC -Djdk.nio.maxCachedBufferSize=1024 -Dio.netty.tryReflectionSetAccessible=true -XX:+ExitOnOutOfMemoryError -Djdk.tls.ephemeralDHKeySize=2048 -XX:FlightRecorderOptions=stackdepth=256 -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED -Dlog4j2.disable.jmx=true -Dfile.encoding=UTF-8 -Xmx1048576k org.neo4j.cli.AdminTool database load --from-path=/Users/nicolasrouyer/Documents/neo4j/demos/genai/assurance/insurance/assurance --overwrite-destination=true --verbose assurance
neo4j 5.21.2
VM Name: OpenJDK 64-Bit Server VM
VM Vendor: Homebrew
VM Version: 21.0.4
JIT compiler: HotSpot 64-Bit Tiered Compilers
VM Arguments: [-XX:+UseParallelGC, -XX:-OmitStackTraceInFastThrow, -XX:+UnlockExperimentalVMOptions, -XX:+TrustFinalNonStaticFields, -XX:+DisableExplicitGC, -Djdk.nio.maxCachedBufferSize=1024, -Dio.netty.tryReflectionSetAccessible=true, -XX:+ExitOnOutOfMemoryError, -Djdk.tls.ephemeralDHKeySize=2048, -XX:FlightRecorderOptions=stackdepth=256, -XX:+UnlockDiagnosticVMOptions, -XX:+DebugNonSafepoints, --add-opens=java.base/java.nio=ALL-UNNAMED, --add-opens=java.base/java.io=ALL-UNNAMED, --add-opens=java.base/sun.nio.ch=ALL-UNNAMED, -Dlog4j2.disable.jmx=true, -Dfile.encoding=UTF-8, -Xmx1048576k]
Configuration files used (ordered by priority):
/Users/nicolasrouyer/Library/Application Support/Neo4j Desktop/Application/relate-data/dbmss/dbms-85798d26-7ab2-4bde-99e2-36841024e327/conf/neo4j-admin.conf
/Users/nicolasrouyer/Library/Application Support/Neo4j Desktop/Application/relate-data/dbmss/dbms-85798d26-7ab2-4bde-99e2-36841024e327/conf/neo4j.conf
--------------------
Done: 54 files, 5.800MiB processed.
Failed to load database 'assurance': The loaded database 'assurance' is of a newer version than the current binaries. Downgrade is not supported.
Load failed for databases: 'assurance'
org.neo4j.cli.CommandFailedException: Load failed for databases: 'assurance'
        at org.neo4j.commandline.dbms.LoadCommand.checkFailure(LoadCommand.java:300)
        at org.neo4j.commandline.dbms.LoadCommand.loadDump(LoadCommand.java:283)
        at com.neo4j.commandline.dbms.EnterpriseLoadCommand.loadDump(EnterpriseLoadCommand.java:31)
        at org.neo4j.commandline.dbms.LoadCommand.loadDump(LoadCommand.java:241)
        at org.neo4j.commandline.dbms.LoadCommand.execute(LoadCommand.java:169)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:92)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.neo4j.cli.AdminTool.execute(AdminTool.java:94)
        at org.neo4j.cli.AdminTool.main(AdminTool.java:82)
Caused by: java.lang.IllegalStateException: The loaded database 'assurance' is of a newer version than the current binaries. Downgrade is not supported.
        at org.neo4j.commandline.dbms.StoreVersionLoader.checkDowngrade(StoreVersionLoader.java:135)
        at org.neo4j.commandline.dbms.StoreVersionLoader.loadStoreVersionAndCheckDowngrade(StoreVersionLoader.java:98)
        at org.neo4j.dbms.archive.Loader.getStoreVersion(Loader.java:133)
        at org.neo4j.commandline.dbms.LoadDumpExecutor.execute(LoadDumpExecutor.java:90)
        at org.neo4j.commandline.dbms.LoadCommand.loadDump(LoadCommand.java:274)
        ... 15 more
Caused by: org.neo4j.kernel.impl.transaction.log.entry.UnsupportedLogVersionException: Log file contains entries with prefix 18, and the highest supported Kernel Version is KernelVersion{V5_20,version=17}. This indicates that the log files originates from an newer version of neo4j, which we don't support downgrading from.
        at org.neo4j.kernel.impl.transaction.log.entry.UnsupportedLogVersionException.unsupported(UnsupportedLogVersionException.java:57)
        at org.neo4j.kernel.impl.transaction.log.files.checkpoint.DetachedLogTailScanner.verifyKernelVersion(DetachedLogTailScanner.java:156)
        at org.neo4j.kernel.impl.transaction.log.files.checkpoint.DetachedLogTailScanner.findLogTail(DetachedLogTailScanner.java:121)
        at org.neo4j.kernel.impl.transaction.log.files.checkpoint.DetachedLogTailScanner.getTailMetadata(DetachedLogTailScanner.java:586)
        at org.neo4j.kernel.impl.transaction.log.files.checkpoint.CheckpointLogFile.getTailMetadata(CheckpointLogFile.java:327)
        at org.neo4j.kernel.impl.transaction.log.files.TransactionLogFiles.getTailMetadata(TransactionLogFiles.java:92)
        at org.neo4j.kernel.recovery.LogTailExtractor.getTailMetadata(LogTailExtractor.java:78)
        at org.neo4j.commandline.dbms.StoreVersionLoader.checkDowngrade(StoreVersionLoader.java:116)
        ... 19 more`

**Comment by yabetancourt** [comment]
Hello @nrouyer,

Today, I encountered the same error. I found this resource on the Neo4j site that might be helpful: [Loading locally to Neo4j on-prem with a Dump from Aura](https://support.neo4j.com/s/article/4402057623187-Loading-locally-to-Neo4j-on-prem-with-a-Dump-from-Aura). I am getting an error very similar to yours:

```
bin\neo4j-admin database load --overwrite-destination=true --from-path=C:\Users\User\.Neo4jDesktop\projects\project-9364aa4b-7e33-4ae2-a141-35286af57762 --verbose neo4j  
Executing command line: C:\Users\User\.Neo4jDesktop\distributions\java\zulu17.50.19-ca-jdk17.0.11\bin\java.exe -cp C:\Users\User\.Neo4jDesktop\relate-data\dbmss\dbms-75095b57-4245-4b30-9963-fb98c38038c2\plugins\*;C:\Users\User\.Neo4jDesktop\relate-data\dbmss\dbms-75095b57-4245-4b30-9963-fb98c38038c2\conf\*;C:\Users\User\.Neo4jDesktop\relate-data\dbmss\dbms-75095b57-4245-4b30-9963-fb98c38038c2\lib\* -XX:+UseParallelGC -XX:-OmitStackTraceInFastThrow -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:+DisableExplicitGC -Djdk.nio.maxCachedBufferSize=1024 -Dio.netty.tryReflectionSetAccessible=true -XX:+ExitOnOutOfMemoryError -Djdk.tls.ephemeralDHKeySize=2048 -XX:FlightRecorderOptions=stackdepth=256 -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED -Dlog4j2.disable.jmx=true -Dfile.encoding=UTF-8 -Xmx1048576k org.neo4j.cli.AdminTool database load --overwrite-destination=true --from-path=C:\Users\User\.Neo4jDesktop\projects\project-9364aa4b-7e33-4ae2-a141-35286af57762 --verbose neo4j
neo4j 5.21.2
VM Name: OpenJDK 64-Bit Server VM
VM Vendor: Azul Systems, Inc.
VM Version: 17.0.11+9-LTS
JIT compiler: HotSpot 64-Bit Tiered Compilers
VM Arguments: [-XX:+UseParallelGC, -XX:-OmitStackTraceInFastThrow, -XX:+UnlockExperimentalVMOptions, -XX:+TrustFinalNonStaticFields, -XX:+DisableExplicitGC, -Djdk.nio.maxCachedBufferSize=1024, -Dio.netty.tryReflectionSetAccessible=true, -XX:+ExitOnOutOfMemoryError, -Djdk.tls.ephemeralDHKeySize=2048, -XX:FlightRecorderOptions=stackdepth=256, -XX:+UnlockDiagnosticVMOptions, -XX:+DebugNonSafepoints, --add-opens=java.base/java.nio=ALL-UNNAMED, --add-opens=java.base/java.io=ALL-UNNAMED, --add-opens=java.base/sun.nio.ch=ALL-UNNAMED, -Dlog4j2.disable.jmx=true, -Dfile.encoding=UTF-8, -Xmx1048576k]
Configuration files used (ordered by priority):
C:\Users\User\.Neo4jDesktop\relate-data\dbmss\dbms-75095b57-4245-4b30-9963-fb98c38038c2\conf\neo4j-admin.conf
C:\Users\User\.Neo4jDesktop\relate-data\dbmss\dbms-75095b57-4245-4b30-9963-fb98c38038c2\conf\neo4j.conf
--------------------
Done: 54 files, 1.026MiB processed.
Failed to load database 'neo4j': The loaded database 'neo4j' is of a newer version than the current binaries. Downgrade is not supported.
Load failed for databases: 'neo4j'
org.neo4j.cli.CommandFailedException: Load failed for databases: 'neo4j'
        at org.neo4j.commandline.dbms.LoadCommand.checkFailure(LoadCommand.java:300)
        at org.neo4j.commandline.dbms.LoadCommand.loadDump(LoadCommand.java:283)    
        at com.neo4j.commandline.dbms.EnterpriseLoadCommand.loadDump(EnterpriseLoadCommand.java:31)
        at org.neo4j.commandline.dbms.LoadCommand.loadDump(LoadCommand.java:241)    
        at org.neo4j.commandline.dbms.LoadCommand.execute(LoadCommand.java:169)     
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:92)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.neo4j.cli.AdminTool.execute(AdminTool.java:94)
        at org.neo4j.cli.AdminTool.main(AdminTool.java:82)
Caused by: java.lang.IllegalStateException: The loaded database 'neo4j' is of a newer version than the current binaries. Downgrade is not supported.
        at org.neo4j.commandline.dbms.StoreVersionLoader.checkDowngrade(StoreVersionLoader.java:135)
        at org.neo4j.commandline.dbms.StoreVersionLoader.loadStoreVersionAndCheckDowngrade(StoreVersionLoader.java:98)
        at org.neo4j.dbms.archive.Loader.getStoreVersion(Loader.java:133)
        at org.neo4j.commandline.dbms.LoadDumpExecutor.execute(LoadDumpExecutor.java:90)
        at org.neo4j.commandline.dbms.LoadCommand.loadDump(LoadCommand.java:274)    
        ... 15 more
Caused by: org.neo4j.kernel.impl.transaction.log.entry.UnsupportedLogVersionException: Log file contains entries with prefix 18, and the highest supported Kernel Version is KernelVersion{V5_20,version=17}. This indicates that the log files originates from an newer version of neo4j, which we don't support downgrading from.
        at org.neo4j.kernel.impl.transaction.log.entry.UnsupportedLogVersionException.unsupported(UnsupportedLogVersionException.java:57)
        at org.neo4j.kernel.impl.transaction.log.files.checkpoint.DetachedLogTailScanner.verifyKernelVersion(DetachedLogTailScanner.java:156)
        at org.neo4j.kernel.impl.transaction.log.files.checkpoint.DetachedLogTailScanner.findLogTail(DetachedLogTailScanner.java:121)
        at org.neo4j.kernel.impl.transaction.log.files.checkpoint.DetachedLogTailScanner.getTailMetadata(DetachedLogTailScanner.java:586)
        at org.neo4j.kernel.impl.transaction.log.files.checkpoint.CheckpointLogFile.getTailMetadata(CheckpointLogFile.java:327)
        at org.neo4j.kernel.impl.transaction.log.files.TransactionLogFiles.getTailMetadata(TransactionLogFiles.java:92)
        at org.neo4j.kernel.recovery.LogTailExtractor.getTailMetadata(LogTailExtractor.java:78)
        at org.neo4j.commandline.dbms.StoreVersionLoader.checkDowngrade(StoreVersionLoader.java:116)
        ... 19 more
```

I hope we can find a solution to this together.

**Comment by emmaholmbergohlsson** [comment]
Hello @nrouyer and @yabetancourt . The error message `The loaded database is of a newer version than the current binaries. Downgrade is not supported.` is saying that a 5.22 database can not be opened with the 5.21 binaries, it needs 5.22 binaries.

I can see that the download center has not been updated with 5.22 yet though. I'm looking into it

**Comment by emmaholmbergohlsson** [comment]
Hello again @nrouyer and @yabetancourt , the deployment center has now been updated with the 5.22 release. If you switch from 5.21.2 to 5.22 loading your dumps should be possible again

**Comment by Dcanzano** [comment]
@nrouyer @yabetancourt also 5.22 should now be available via Neo4j Desktop as well

**Comment by yabetancourt** [comment]
@Dcanzano @emmaholmbergohlsson Thanks, I'll be testing soon.

**Comment by emmaholmbergohlsson** [comment]
Closing this issue as a solution was given and we haven't heard about any additional problems in almost a year. Feel free to open a new issue if needed
