### ISSUE TITLE
Load/Export Neo4j dump from/to AWS s3

### ISSUE THREAD

**Issue by chasemc** [neo4j/neo4j#13497]
I'm working to put some Neo4j dump files on AWS S3 for public use but I'm struggling to get the examples in the Neo4j documentation to work.

I am trying to follow the documentation for loading or exporting a dump file from S3 (e.g. https://neo4j.com/docs/operations-manual/current/backup-restore/offline-backup/#offline-backup-cloud-storage). However I just get `java.nio.file.ProviderMismatchException: No storage system found for scheme: s3`. I'm not convinced I haven't done something wrong but AWS CLI v2 shows the bucket and can read/write to it.

**Neo4j Version:** 5.22.0
**Operating System:** Ubuntu 
**API:** Docker

### Steps to reproduce

The error within docker below is the same as what I get on the locally installed Neo4j  where AWS CLI v2 is configured

```
docker run -it neo4j:5.22.0-community bash

neo4j-admin database dump neo4j --to-path=s3://neo4jtest/mydirectory/
    
java.nio.file.ProviderMismatchException: No storage system found for scheme: s3
        at org.neo4j.cloud.storage.SchemeFileSystemAbstraction.internalResolve(SchemeFileSystemAbstraction.java:391)
        at org.neo4j.cloud.storage.SchemeFileSystemAbstraction.resolve(SchemeFileSystemAbstraction.java:142)
        at org.neo4j.commandline.dbms.DumpCommand.execute(DumpCommand.java:126)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:92)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at org.neo4j.cli.AdminTool.execute(AdminTool.java:94)
        at org.neo4j.cli.AdminTool.main(AdminTool.java:82)
```

**Comment by fabiim** [comment]
Hi @chasemc unfortunely cloud storage support isn't available in community. We will update our docs to reflect that, apologies.

**Comment by chasemc** [comment]
Thanks, that stinks, I was hoping it would be an easier path for getting people interested in using the data and Neo4j.

I successfully tested it with Enterprise and got it to work, so will add it to the data's documentation. Do you know if there's a size limit where this starts to fail? The largest `.dump` we have is >200GB

**Comment by fabiim** [comment]
@chasemc It should only be limited by the backend (i.e., s3 limits in your case)

**Comment by chasemc** [comment]
Thanks @fabiim
