### ISSUE TITLE
version 3.5.35 , The docker container will report an error the first time it is started :java.io.FileNotFoundException: /data/databases/graph.db/neostore.counts.db.b (No such file or directory) 

### ISSUE THREAD

**Issue by haoran721** [neo4j/neo4j#13496]
The docker container will report an error the first time it is started, 

2024-07-25 01:44:47.044+0000 ERROR [o.n.k.i.s.c.CountsTracker] Failed to rotate counts store at transaction 16 to [/data/databases/graph.db/neostore.counts.db.b], from [/data/databases/graph.db/neostore.counts.db.a]. /data/databases/graph.db/neostore.counts.db.b (No such file or directory)
java.io.FileNotFoundException: /data/databases/graph.db/neostore.counts.db.b (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.neo4j.io.fs.DefaultFileSystemAbstraction.openAsOutputStream(DefaultFileSystemAbstraction.java:72)
        at org.neo4j.kernel.impl.store.kvstore.KeyValueWriter$Writer.create(KeyValueWriter.java:266)
        at org.neo4j.kernel.impl.store.kvstore.KeyValueWriter.create(KeyValueWriter.java:46)
        at org.neo4j.kernel.impl.store.kvstore.KeyValueStoreFileFormat.newWriter(KeyValueStoreFileFormat.java:215)
        at org.neo4j.kernel.impl.store.kvstore.KeyValueStoreFileFormat.create(KeyValueStoreFileFormat.java:166)
        at org.neo4j.kernel.impl.store.kvstore.KeyValueStoreFileFormat.createStore(KeyValueStoreFileFormat.java:60)
        at org.neo4j.kernel.impl.store.kvstore.RotationStrategy.next(RotationStrategy.java:107)
        at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:92)
        at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:51)
        at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:317)
        at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:294)
        at org.neo4j.kernel.impl.store.counts.CountsTracker.rotate(CountsTracker.java:126)
        at org.neo4j.kernel.impl.store.NeoStores.flush(NeoStores.java:251)
        at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.flushAndForce(RecordStorageEngine.java:425)
        at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:177)
        at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.checkPointIfNeeded(CheckPointerImpl.java:151)
        at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.run(CheckPointScheduler.java:65)
        at org.neo4j.kernel.impl.scheduler.ScheduledJobHandle.lambda$new$0(ScheduledJobHandle.java:83)
        at org.neo4j.kernel.impl.scheduler.ThreadPool.lambda$submit$0(ThreadPool.java:61)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

Here is my docker-compose:
version: "3.7"
services:
  neo4j:
    image: middleware/neo4j:latest
    container_name: neo4j
    volumes:
      - ${ROOT_PATH}/plugins:/var/lib/neo4j/plugins:rw
      - ${ROOT_PATH}/conf:/var/lib/neo4j/conf
      - ${ROOT_PATH}/data:/data:rw
      - ${ROOT_PATH}/logs:/var/lib/neo4j/logs:rw
    restart: always
    ports:
      - ${http_port}:7474
      - ${bolt_port}:7687
    environment:
      # - NEO4J_dbms_memory_heap_maxSize=4G
      - NEO4J_AUTH=neo4j/${password} #修改默认用户密码,最低8位
    networks:
      - scalaops
networks:
  scalaops:
    external: true

**Comment by brunobuss** [comment]
Hey @haoran721,

Neo4j 3.5.35 is quite old and unsupported now.
Would you be able to try using our (latest) official image from https://hub.docker.com/_/neo4j?
