### ISSUE TITLE
Transaction Commit Failure When Using cypher.lenient_create_relationship=true in Neo4j 4.4

### ISSUE THREAD

**Issue by gooneraki** [neo4j/neo4j#13504]
## Issue Summary
After updating from Neo4j 4.1 to Neo4j 4.4, a query that previously worked has started failing. The issue appears to be related to the use of the `cypher.lenient_create_relationship=true` configuration, particularly when used within transactions. The transaction fails to commit, resulting in an error that did not occur in the previous Neo4j version.

## Steps to Reproduce
1. Update Neo4j from version 4.1 to 4.4.
2. Enable `cypher.lenient_create_relationship=true` in `neo4j.conf`.
3. Run a query that creates relationships within a transaction.

### Logs without `cypher.lenient_create_relationship=true`:
2024-08-10 14:07:08 backend | Transaction started
2024-08-10 14:07:08 backend | --- [FUNCTION_1] ---
2024-08-10 14:07:08 backend |
2024-08-10 14:07:12 backend | ScorilyDBError [ScorilyDbError]: Failed to create relationship UNNAMED11, node [NODE_1] is missing. If you prefer to simply ignore rows where a relationship node is missing, set 'cypher.lenient_create_relationship = true' in neo4j.conf
2024-08-10 14:07:12 backend | at NeoHelper.execute (/app/src/helpers/NeoHelper.ts:112:10)
2024-08-10 14:07:12 backend | at processTicksAndRejections (node
/process/task_queues:95:5)
2024-08-10 14:07:12 backend | at NeoHelper.executeWrite (/app/src/helpers/NeoHelper.ts:85:19)
2024-08-10 14:07:12 backend | at [GRAPH_CLASS].[FUNCTION_1] (/app/src/db-neo/[GRAPH_FILE.ts]:2776:19)
2024-08-10 14:07:12 backend | at [GRAPH_CLASS].[PARENT_FUNCTION] (/app/src/db-neo/[GRAPH_FILE.ts]:2952:25)
2024-08-10 14:07:12 backend | at [CONTROLLER].[CONTROLLER_FUNCTION] (/app/src/controllers/[CONTROLLER_FILE]:301:10)
2024-08-10 14:07:12 backend | at Object.[MUTATION] (/app/src/api/graphql/[RESOLVER_PATH]/resolvers.ts:6:27)
2024-08-10 14:07:12 backend | at middleware (/app/node_modules/graphql-shield/cjs/generator.js:30:24) {
2024-08-10 14:07:12 backend | extensions: { code: '[DATABASE_ERROR]' }
2024-08-10 14:07:12 backend | }
2024-08-10 14:07:12 backend | 10-Aug-2024 11:07:12 +00:00 error: Failed to create relationship UNNAMED11, node [NODE_1] is missing. If you prefer to simply ignore rows where a relationship node is missing, set 'cypher.lenient_create_relationship = true' in neo4j.conf path: [MUTATION]

### Logs with `cypher.lenient_create_relationship=true`:
2024-08-10 13:55:59 backend | Transaction started
2024-08-10 13:55:59 backend | --- [FUNCTION_1] ---
2024-08-10 13:55:59 backend |
2024-08-10 13:56:00 backend | note: successful completion
2024-08-10 13:56:00 backend | --- [FUNCTION_2] ---
2024-08-10 13:56:00 backend |
2024-08-10 13:56:00 backend | note: successful completion
2024-08-10 13:56:00 backend | Neo4jError: Unable to complete transaction.
2024-08-10 13:56:00 backend | :
2024-08-10 13:56:00 backend | at captureStacktrace (/app/node_modules/neo4j-driver-core/lib/result.js:624:17)
2024-08-10 13:56:00 backend | at new Result (/app/node_modules/neo4j-driver-core/lib/result.js:112:23)
2024-08-10 13:56:00 backend | at finishTransaction (/app/node_modules/neo4j-driver-core/lib/transaction.js:510:12)
2024-08-10 13:56:00 backend | at Object.commit (/app/node_modules/neo4j-driver-core/lib/transaction.js:323:25)
2024-08-10 13:56:00 backend | at TransactionPromise.Transaction.commit (/app/node_modules/neo4j-driver-core/lib/transaction.js:204:37)
2024-08-10 13:56:00 backend | at [GRAPH_CLASS].[PARENT_FUNCTION] (/app/src/db-neo/[GRAPH_FILE.ts]:2956:22)
2024-08-10 13:56:00 backend | at processTicksAndRejections (node
/process/task_queues:95:5)
2024-08-10 13:56:00 backend | at [CONTROLLER].[CONTROLLER_FUNCTION] (/app/src/controllers/[CONTROLLER_FILE]:301:10)
2024-08-10 13:56:00 backend | at Object.[MUTATION] (/app/src/api/graphql/[RESOLVER_PATH]/resolvers.ts:6:27)
2024-08-10 13:56:00 backend | at middleware (/app/node_modules/graphql-shield/cjs/generator.js:30:24) {
2024-08-10 13:56:00 backend | constructor: [Function: Neo4jError] { isRetriable: [Function (anonymous)] },
2024-08-10 13:56:00 backend | code: 'Neo.DatabaseError.Transaction.TransactionCommitFailed',
2024-08-10 13:56:00 backend | retriable: false
2024-08-10 13:56:00 backend | }
2024-08-10 13:56:00 backend | 10-Aug-2024 10:56:00 +00:00 error: Unable to complete transaction. path: [MUTATION]

### Expected Behavior
The transaction should successfully commit when using `cypher.lenient_create_relationship=true`, as it did in version 4.1.

### Actual Behavior
The transaction fails to commit with the error code `Neo.DatabaseError.Transaction.TransactionCommitFailed`.

## Environment
- **Neo4j Version:** 4.4
- **Operating System:** Ubuntu 24.04 (Docker container)
- **API/Driver:** neo4j-driver: ^5.23.0
- **Node.js Version:** 20.16

## Additional Information
The application is built using Node.js and Docker, with the following key configurations:
- `cypher.lenient_create_relationship=true` is enabled in the Neo4j configuration.

Given the pervasive use of `cypher.lenient_create_relationship=true` in the codebase, refactoring is not a feasible option. This issue critically affects the application's functionality, and a resolution is urgently needed.

**Comment by gooneraki** [comment]
Well I cleaned things up a bit and removed the transaction and I still get the same error `2024-08-10 15:49:59 backend    | 10-Aug-2024 12:49:59 +00:00 error: Unable to complete transaction. path: [MUTATION]`.

So I guess there is a general issue with `cypher.lenient_create_relationship=true` and `Neo4j-4.4`

**Comment by gooneraki** [comment]
Ok finally, I actually noticed it works in most cases. It breaks when the query is too long ... 

I changed some **other pieces** of the same query e.g.
```
MATCH (j)-[rel:REL]->(j)
DELETE rel
```
to 
`FOREACH (rel IN [(j)-[anyRel:REL]->(k) | anyRel] | DELETE rel)` and the whole query then worked.
