### ISSUE TITLE
Neo4j unexpectedly terminates connection with Java 

### ISSUE THREAD

**Issue by GravityBender** [neo4j/neo4j#13508]
While the service that maintains Neo4j as it's database is running, the database unexpectedly terminates the connection to the service. I haven't really been able to replicate the error on my own as this termination occurs completely randomly but they generally follow after the service tries to write data into the db.

These are the logs from the `debug.logs` file at the time of error.

```
2024-08-21 06:52:33.116+0000 WARN  [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=8902, gcTime=9101, gcCount=2}
2024-08-21 06:52:42.755+0000 WARN  [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=9439, gcTime=9636, gcCount=2}
2024-08-21 06:52:52.610+0000 WARN  [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=9654, gcTime=9850, gcCount=2}
2024-08-21 06:53:02.251+0000 WARN  [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=9441, gcTime=9641, gcCount=2}
2024-08-21 06:53:13.151+0000 WARN  [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=10699, gcTime=10896, gcCount=2}
2024-08-21 06:54:55.081+0000 WARN  [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=27996, gcTime=101911, gcCount=22}
2024-08-21 06:53:51.152+0000 ERROR [o.n.b.p.c.h.HouseKeeperHandler] Fatal error occurred when handling a client connection: [id: 0xc1ae3c32, L:/172.31.19.69:7687 ! R:/172.31.59.78:40758]
org.neo4j.bolt.runtime.BoltConnectionFatality: Terminated connection 'bolt-3465' ([id: 0xc1ae3c32, L:/172.31.19.69:7687 ! R:/172.31.59.78:40758]) as the client failed to authenticate within 30000 ms.
	at org.neo4j.bolt.protocol.common.handler.AuthenticationTimeoutHandler.channelIdle(AuthenticationTimeoutHandler.java:84) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:503) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:475) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
2024-08-21 06:55:02.349+0000 WARN  [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=80801, gcTime=7268, gcCount=2}
2024-08-21 06:55:21.105+0000 ERROR [o.n.b.p.c.h.HouseKeeperHandler] Fatal error occurred when handling a client connection: [id: 0xda6cd895, L:/172.31.19.69:7687 ! R:/172.31.59.78:53230]
org.neo4j.bolt.runtime.BoltConnectionFatality: Terminated connection 'bolt-3468' ([id: 0xda6cd895, L:/172.31.19.69:7687 ! R:/172.31.59.78:53230]) as the server failed to handle an authentication request within 30000 ms.
	at org.neo4j.bolt.protocol.common.handler.AuthenticationTimeoutHandler.channelIdle(AuthenticationTimeoutHandler.java:77) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:503) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:475) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
2024-08-21 06:55:38.485+0000 WARN  [i.n.c.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
2024-08-21 06:55:38.485+0000 WARN  [i.n.c.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
2024-08-21 06:55:38.485+0000 WARN  [i.n.c.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
2024-08-21 06:55:38.485+0000 WARN  [i.n.c.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
```
This is the stack trace from the `neo4j.logs` file:

```
2024-08-21 07:09:52.144+0000 ERROR [bolt-3503] Terminating connection due to unexpected error
org.neo4j.bolt.protocol.error.streaming.BoltStreamingWriteException: Failed to finalize batch: Cannot write result response
	at org.neo4j.bolt.protocol.common.transaction.result.ResultHandler.onFinish(ResultHandler.java:116) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.fsm.AbstractStateMachine.after(AbstractStateMachine.java:126) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.fsm.AbstractStateMachine.process(AbstractStateMachine.java:99) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.lambda$submit$4(AtomicSchedulingConnection.java:113) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.executeJob(AtomicSchedulingConnection.java:336) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.doExecuteJobs(AtomicSchedulingConnection.java:306) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.executeJobs(AtomicSchedulingConnection.java:212) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
2024-08-21 07:27:02.904+0000 ERROR Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: org.neo4j.bolt.protocol.common.handler.AuthenticationTimeoutHandler, reference c9b9e113-5815-4e3f-a26d-c64f5e125faf.
2024-08-21 07:27:02.904+0000 ERROR [bolt-3545] Terminating connection due to unexpected error
org.neo4j.bolt.runtime.BoltConnectionFatality: Failed to process a bolt message
	at org.neo4j.bolt.protocol.common.fsm.AbstractStateMachine.handleFailure(AbstractStateMachine.java:293) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.fsm.StateMachineContextImpl.handleFailure(StateMachineContextImpl.java:92) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.v40.fsm.ConnectedState.processAuthentication(ConnectedState.java:106) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.v40.fsm.ConnectedState.process(ConnectedState.java:57) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.fsm.AbstractStateMachine.nextState(AbstractStateMachine.java:136) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.fsm.AbstractStateMachine.process(AbstractStateMachine.java:96) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.lambda$submit$4(AtomicSchedulingConnection.java:113) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.executeJob(AtomicSchedulingConnection.java:336) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.doExecuteJobs(AtomicSchedulingConnection.java:270) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.executeJobs(AtomicSchedulingConnection.java:212) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.NoSuchElementException: org.neo4j.bolt.protocol.common.handler.AuthenticationTimeoutHandler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1082) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:417) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at org.neo4j.bolt.protocol.common.connector.connection.listener.AuthenticationTimeoutConnectionListener.onAuthenticated(AuthenticationTimeoutConnectionListener.java:85) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AbstractConnection.lambda$authenticate$2(AbstractConnection.java:355) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at org.neo4j.bolt.protocol.common.connector.connection.AbstractConnection.notifyListeners(AbstractConnection.java:173) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AbstractConnection.authenticate(AbstractConnection.java:355) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.v40.fsm.ConnectedState.processAuthentication(ConnectedState.java:99) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	... 12 more
2024-08-21 07:55:54.691+0000 ERROR [bolt-3606] Terminating connection due to unexpected error
org.neo4j.bolt.protocol.error.streaming.BoltStreamingWriteException: Failed to finalize batch: Cannot write result response
	at org.neo4j.bolt.protocol.common.transaction.result.ResultHandler.onFinish(ResultHandler.java:116) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.fsm.AbstractStateMachine.after(AbstractStateMachine.java:126) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.fsm.AbstractStateMachine.process(AbstractStateMachine.java:99) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.lambda$submit$4(AtomicSchedulingConnection.java:113) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.executeJob(AtomicSchedulingConnection.java:336) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.doExecuteJobs(AtomicSchedulingConnection.java:270) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection.executeJobs(AtomicSchedulingConnection.java:212) ~[neo4j-bolt-5.3.0.jar:5.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]

```

This is the stack trace in the logs of the Spring application when the application was trying to insert data into the db. However, after restarting the database and trying to insert the same data it didn't throw any error.

```org.springframework.transaction.TransactionSystemException:   Could not open a new Neo4j session: Unable to establish connection in   30000ms; nested exception is   org.neo4j.driver.exceptions.ServiceUnavailableException: Unable to establish   connection in 30000ms
at   org.springframework.data.neo4j.core.transaction.Neo4jTransactionManager.doBegin(Neo4jTransactionManager.java:313)
at   org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
at   org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
at   org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:595)
at   org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:382)
at   org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
at   org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at   org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
at   org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at   org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
at   org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at   org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
at   com.sun.proxy.$Proxy118.findById(Unknown Source)
at   com.ew.neo4jtransactionprocessor.repository.nodes.TransactionRepository.getOrCreateNode(TransactionRepository.java:45)
at   com.ew.neo4jtransactionprocessor.services.Neo4jTransactionWriterService.createOrUpdateTransactionNodeAndVersion(Neo4jTransactionWriterService.java:33)
at   com.ew.neo4jtransactionprocessor.services.Neo4jTransactionWriterService.createOrUpdateTransaction(Neo4jTransactionWriterService.java:107)
at   com.ew.neo4jtransactionprocessor.controllers.IFTTTController.nodeCreateOrUpdate(IFTTTController.java:89)
at   jdk.internal.reflect.GeneratedMethodAccessor143.invoke(Unknown Source)
at   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at   java.base/java.lang.reflect.Method.invoke(Method.java:566)
at   org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
at   org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
at   org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
at   org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
at   org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
at   org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
at   org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)
at   org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)
at   org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
at   org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
at   javax.servlet.http.HttpServlet.service(HttpServlet.java:696)
at   org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
at   javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at   org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at   org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:71)
at   org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:31)
at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at   org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
at   org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
at   org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
at   org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at   org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
at   org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at   org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
at   org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at   org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:71)
at   org.zalando.logbook.servlet.SecureLogbookFilter.doFilter(SecureLogbookFilter.java:32)
at   org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:31)
at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at   org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
at   org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at   org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
at   org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
at   org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
at   org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
at   org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at   org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
at   org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
at   org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
at   org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
at   org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
at   org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
at   org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at   org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
at   org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
at   org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at   java.base/java.lang.Thread.run(Thread.java:829)
Caused by:   org.neo4j.driver.exceptions.ServiceUnavailableException: Unable to establish   connection in 30000ms
at   org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:111)
at   org.neo4j.driver.internal.InternalSession.beginTransaction(InternalSession.java:90)
at   org.springframework.data.neo4j.core.transaction.Neo4jTransactionManager.doBegin(Neo4jTransactionManager.java:304)
... 80 more
Suppressed:   org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause
at   org.neo4j.driver.internal.async.inbound.ConnectTimeoutHandler.unableToConnectError(ConnectTimeoutHandler.java:49)
at   org.neo4j.driver.internal.async.inbound.ConnectTimeoutHandler.readTimedOut(ConnectTimeoutHandler.java:44)
at   org.neo4j.driver.internal.shaded.io.netty.handler.timeout.ReadTimeoutHandler.channelIdle(ReadTimeoutHandler.java:90)
at   org.neo4j.driver.internal.shaded.io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:503)
at   org.neo4j.driver.internal.shaded.io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:475)
at   org.neo4j.driver.internal.shaded.io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
at   org.neo4j.driver.internal.shaded.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
at   org.neo4j.driver.internal.shaded.io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
at   org.neo4j.driver.internal.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
at   org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
at   org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
at   org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at   org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at   org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
... 1 more
```

### Setup
**Neo4j Version:** 5.3.0 Community Edition
**Operating System:** Centos 7 on AWS EC2
**API:** [Neo4j driver for Java](https://github.com/neo4j/neo4j-java-driver)

The database contains approximately 1.2 million nodes and 5.1 million relationships. If this information is of any help.

### Expected behavior
Shouldn't crash randomly while insertion of data.

### Actual behavior
Unable to create connections to the database, from both the driver/browser.

**Comment by mnd999** [comment]
Looks like you were tight on memory as you are seeing long garbage collection pauses:
`Detected VM stop-the-world pause: {pauseTime=27996, gcTime=101911, gcCount=22}`

How is the data being inserted? Like many transactional systems, good practice is to batch your inserts so as to not generate large transactions which can use a lot of memory. See [batching](https://neo4j.com/docs/cypher-manual/current/subqueries/subqueries-in-transactions/#batching) for an example of this.

**Comment by mnd999** [comment]
We haven't head anything back on this for some time, so I will close for now. If it's still an issue please feel free to reopen.
