### ISSUE TITLE
Unable to force ContractCheckingIndexProxy - AccessDeniedException

### ISSUE THREAD

**Issue by ClancyDamon** [neo4j/neo4j#13503]
- Neo4j version: 3.5.35
- Operating system: Alpine Linux 3.20.2 (Docker Container created from build file)
- API/Driver: Java API V3.5.35
- JVM: OpenJDK 11.0.24

Starting recently, I've been getting failures for a Neo4j GraphDB included inside of an application that I'm utilizing - https://sourceforge.net/projects/kuwaiba/

It's an AccessDeniedException on the Lucene Index.

[db_debug.log](https://github.com/user-attachments/files/16552832/db_debug.log)

```
2024-08-07 17:10:22.965+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Checkpoint triggered by scheduler for time threshold @ txId: 40833 checkpoint started...
2024-08-07 17:10:22.976+0000 ERROR [o.n.k.i.t.l.c.CheckPointerImpl] Checkpoint failed Unable to force ContractCheckingIndexProxy -> OnlineIndexProxy[accessor:org.neo4j.kernel.impl.index.schema.fusion.FusionIndexAccessor@2042aef, descriptor:IndexRule[id=1, descriptor=Index( GENERAL, :label[47](property[0]) ), provider={key=lucene+native, version=1.0}]]
org.neo4j.kernel.impl.store.UnderlyingStorageException: Unable to force ContractCheckingIndexProxy -> OnlineIndexProxy[accessor:org.neo4j.kernel.impl.index.schema.fusion.FusionIndexAccessor@2042aef, descriptor:IndexRule[id=1, descriptor=Index( GENERAL, :label[47](property[0]) ), provider={key=lucene+native, version=1.0}]]
	at org.neo4j.kernel.impl.api.index.IndexingService.lambda$indexProxyOperation$f3401ac3$1(IndexingService.java:743)
	at org.eclipse.collections.impl.map.mutable.primitive.LongObjectHashMap.forEachKeyValue(LongObjectHashMap.java:669)
	at org.neo4j.kernel.impl.api.index.IndexMap.forEachIndexProxy(IndexMap.java:133)
	at org.neo4j.kernel.impl.api.index.IndexingService.forceAll(IndexingService.java:727)
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.flushAndForce(RecordStorageEngine.java:415)
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:163)
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.checkPointIfNeeded(CheckPointerImpl.java:137)
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.run(CheckPointScheduler.java:65)
	at org.neo4j.kernel.impl.scheduler.ScheduledJobHandle.lambda$new$0(ScheduledJobHandle.java:83)
	at org.neo4j.kernel.impl.scheduler.ThreadPool.lambda$submit$0(ThreadPool.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.UncheckedIOException: java.nio.file.AccessDeniedException: /data/db/kuwaiba.db/schema/index/lucene_native-1.0/1/lucene-1.0/1/_e.si
	at org.neo4j.kernel.api.impl.index.AbstractLuceneIndexAccessor.force(AbstractLuceneIndexAccessor.java:90)
	at org.neo4j.kernel.impl.index.schema.fusion.FusionIndexAccessor.lambda$force$1(FusionIndexAccessor.java:73)
	at org.neo4j.kernel.impl.index.schema.fusion.InstanceSelector.consumeAndChainException(InstanceSelector.java:193)
	at org.neo4j.kernel.impl.index.schema.fusion.InstanceSelector.forAll(InstanceSelector.java:134)
	at org.neo4j.kernel.impl.index.schema.fusion.FusionIndexAccessor.force(FusionIndexAccessor.java:73)
	at org.neo4j.kernel.impl.api.index.OnlineIndexProxy.force(OnlineIndexProxy.java:140)
	at org.neo4j.kernel.impl.api.index.AbstractDelegatingIndexProxy.force(AbstractDelegatingIndexProxy.java:78)
	at org.neo4j.kernel.impl.api.index.ContractCheckingIndexProxy.force(ContractCheckingIndexProxy.java:127)
	at org.neo4j.kernel.impl.api.index.IndexingService.lambda$forceAll$10(IndexingService.java:727)
	at org.neo4j.kernel.impl.api.index.IndexingService.lambda$indexProxyOperation$f3401ac3$1(IndexingService.java:736)
	... 14 more
Caused by: java.nio.file.AccessDeniedException: /data/db/kuwaiba.db/schema/index/lucene_native-1.0/1/lucene-1.0/1/_e.si
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
	at org.apache.lucene.util.IOUtils.fsync(IOUtils.java:391)
	at org.apache.lucene.store.FSDirectory.fsync(FSDirectory.java:288)
	at org.apache.lucene.store.FSDirectory.sync(FSDirectory.java:232)
	at org.apache.lucene.store.NRTCachingDirectory.sync(NRTCachingDirectory.java:165)
	at org.apache.lucene.store.LockValidatingDirectoryWrapper.sync(LockValidatingDirectoryWrapper.java:62)
	at org.apache.lucene.index.IndexWriter.startCommit(IndexWriter.java:4446)
	at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:2865)
	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:2970)
	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:2935)
	at org.neo4j.kernel.api.impl.index.AbstractLuceneIndex.flush(AbstractLuceneIndex.java:238)
	at org.neo4j.kernel.api.impl.index.AbstractLuceneIndex.markAsOnline(AbstractLuceneIndex.java:460)
	at org.neo4j.kernel.api.impl.index.WritableAbstractDatabaseIndex.markAsOnline(WritableAbstractDatabaseIndex.java:177)
	at org.neo4j.kernel.api.impl.index.AbstractLuceneIndexAccessor.force(AbstractLuceneIndexAccessor.java:84)
	... 23 more
```

There are unfortunately no steps to reproduce near as we can tell. It seems to just happen randomly after running for several hours, with nothing preceding the error. 

The closest related issue I've found is here - https://github.com/neo4j/neo4j/issues/11955 - but that doesn't seem to have any resolution. I know 3.5.x is very old and I'm looking into migrating, but according to the most recent post in 11955, the same thing was still happening in 4.2.3.

The application and database is deployed via a Docker container, and we should have tons available space and RAM, according to the diagnostics at startup.

```

2024-08-07 02:00:51.827+0000 INFO [o.n.i.d.DiagnosticsManager] --- STARTED diagnostics for KernelDiagnostics:StoreFiles START ---
2024-08-07 02:00:51.827+0000 INFO [o.n.i.d.DiagnosticsManager] Disk space on partition (Total / Free / Free %): 75125227520 / 35242549248 / 46
...
2024-08-07 02:00:51.840+0000 INFO [o.n.i.d.DiagnosticsManager] Storage summary: 
2024-08-07 02:00:51.840+0000 INFO [o.n.i.d.DiagnosticsManager]   Total size of store: 42.49 MB
2024-08-07 02:00:51.840+0000 INFO [o.n.i.d.DiagnosticsManager]   Total size of mapped files: 8.53 MB

```

The database is running embedded within the application, started and stopped with the application itself:

```

String dbPathString = configuration.getProperty("dbPath", DEFAULT_DB_PATH);
String dbHost = configuration.getProperty("dbHost", DEFAULT_DB_HOST);
int dbPort = (Integer)(configuration.getOrDefault("dbPort", DEFAULT_DB_PORT));

File dbFile = new File(dbPathString);
if (!dbFile.exists() || !dbFile.canWrite())
	throw new Exception(String.format("Path %s does not exist or is not writeable", dbFile.getAbsolutePath()));
BoltConnector bolt = new BoltConnector();
graphDb = new GraphDatabaseFactory()
			.newEmbeddedDatabaseBuilder(dbFile)
			.setConfig(bolt.type, "BOLT")
			.setConfig(bolt.enabled, "true")
			.setConfig(bolt.listen_address,  dbHost + ":" + dbPort)
			.setConfig(udc_enabled, "false")
			.newGraphDatabase();

```

We were originally using 3.5.5 as the driver, but this issue looked similar - https://github.com/neo4j/neo4j/issues/12201 - so we upgraded to 3.5.35, but we're still encountering the same intermittent access denied errors. 

What's bizarre is that this only recently started to happen. We were fine for a few months, and now we are forced to restart things every day. Restarting the Docker Container (and thus the application and DB) does temporarily resolve the issue. So if it was simply a matter of the user not having rights to the db folders/files, we'd expect there to be immediate failure.

**Comment by klaren** [comment]
The cause of the error is:
```
Caused by: java.nio.file.AccessDeniedException: /data/db/kuwaiba.db/schema/index/lucene_native-1.0/1/lucene-1.0/1/_e.si
```
which comes from `java.nio.channels.FileChannel.open(...)`. This indicates that Lucene failed to create or open a file due to an OS restriction. This restriction could be due to file permission, limits on the number of open files, limits on the total number of files, etc.

Also, Neo4j 3.5 is no longer supported, I recommend upgrading to a later version.

**Comment by klaren** [comment]
Closing due to inactivity, feel free to reopen if you are still experiencing the problem.
