### ISSUE TITLE
 java.lang.NoSuchMethodError when loading dump

### ISSUE THREAD

**Issue by canelson314** [neo4j/neo4j#13530]
I'm getting this error when loading my dump. The same command worked on our other server.

sudo neo4j-admin database load --from-path=V6/ my_db --overwrite-destination=true --verbose

Executing command line: /opt/jdk-21.0.3/bin/java -cp /var/lib/neo4j/plugins/*:/etc/neo4j/*:/usr/share/neo4j/lib/* -XX:+UseParallelGC -XX:-OmitStackTraceInFastThrow -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:+DisableExplicitGC -Djdk.nio.maxCachedBufferSize=1024 -Dio.netty.tryReflectionSetAccessible=true -XX:+ExitOnOutOfMemoryError -Djdk.tls.ephemeralDHKeySize=2048 -XX:FlightRecorderOptions=stackdepth=256 -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --enable-native-access=ALL-UNNAMED -Dlog4j2.disable.jmx=true -Dfile.encoding=UTF-8 org.neo4j.cli.AdminTool database load --from-path=V6/ my_db --overwrite-destination=true --verbose
neo4j 5.23.0
VM Name: Java HotSpot(TM) 64-Bit Server VM
VM Vendor: Oracle Corporation
VM Version: 21.0.3+7-LTS-152
JIT compiler: HotSpot 64-Bit Tiered Compilers
VM Arguments: [-XX:+UseParallelGC, -XX:-OmitStackTraceInFastThrow, -XX:+UnlockExperimentalVMOptions, -XX:+TrustFinalNonStaticFields, -XX:+DisableExplicitGC, -Djdk.nio.maxCachedBufferSize=1024, -Dio.netty.tryReflectionSetAccessible=true, -XX:+ExitOnOutOfMemoryError, -Djdk.tls.ephemeralDHKeySize=2048, -XX:FlightRecorderOptions=stackdepth=256, -XX:+UnlockDiagnosticVMOptions, -XX:+DebugNonSafepoints, --add-opens=java.base/java.nio=ALL-UNNAMED, --add-opens=java.base/java.io=ALL-UNNAMED, --add-opens=java.base/sun.nio.ch=ALL-UNNAMED, --enable-native-access=ALL-UNNAMED, -Dlog4j2.disable.jmx=true, -Dfile.encoding=UTF-8]
Configuration files used (ordered by priority):
/etc/neo4j/neo4j-admin.conf
/etc/neo4j/neo4j.conf
--------------------
Done: 0 files, 0B processed.
Exception in thread "main" java.lang.NoSuchMethodError: 'long org.apache.commons.io.IOUtils.skip(java.io.InputStream, long, java.util.function.Supplier)'
	at org.apache.commons.compress.utils.IOUtils.skip(IOUtils.java:282)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:409)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:389)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.paxHeaders(TarArchiveInputStream.java:580)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:464)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:389)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:49)
	at org.neo4j.dbms.archive.Loader.nextEntry(Loader.java:188)
	at org.neo4j.dbms.archive.Loader.load(Loader.java:120)
	at org.neo4j.commandline.dbms.LoadDumpExecutor.load(LoadDumpExecutor.java:103)
	at org.neo4j.commandline.dbms.LoadDumpExecutor.execute(LoadDumpExecutor.java:80)
	at org.neo4j.commandline.dbms.LoadCommand.loadDump(LoadCommand.java:274)
	at com.neo4j.commandline.dbms.EnterpriseLoadCommand.loadDump(EnterpriseLoadCommand.java:31)
	at org.neo4j.commandline.dbms.LoadCommand.loadDump(LoadCommand.java:241)
	at org.neo4j.commandline.dbms.LoadCommand.execute(LoadCommand.java:169)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:92)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at org.neo4j.cli.AdminTool.execute(AdminTool.java:94)
	at org.neo4j.cli.AdminTool.main(AdminTool.java:82)

**Comment by klaren** [comment]
It loads the classes from `/usr/share/neo4j/lib/*`, are you sure this directory contains the expected version of neo4j?

**Comment by canelson314** [comment]
We have the exact same classes in /usr/share/neo4j/lib/* on both servers.

**Comment by klaren** [comment]
Could you provide a list of all the jar files present in both directories?

**Comment by klaren** [comment]
Closing due to inactivity. Feel free to reopen if you are still experiencing the same problem.

**Comment by purohitsumit** [comment]
I am getting the same error while loading a dump from local machine to server. 
On the server i have following common.x.jar files
`commons-codec-1.17.1.jar 
commons-compress-1.27.1.jar 
commons-configuration2-2.11.0.jar 
commons-io-2.17.0.jar 
commons-lang3-3.17.0.jar
commons-logging-1.3.4.jar
commons-text-1.12.0.jar`

Error:
`Done: 0 files, 0B processed in 0.009 seconds.
Exception in thread "main" java.lang.NoSuchMethodError: 'long org.apache.commons.io.IOUtils.skip(java.io.InputStream, long, java.util.function.Supplier)'
        at org.apache.commons.compress.utils.IOUtils.skip(IOUtils.java:282)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:409)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:389)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.paxHeaders(TarArchiveInputStream.java:580)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:464)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:389)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:49)`

Thanks
