### ISSUE TITLE
Unable to load CSV via https private URL neo4j 5.18

### ISSUE THREAD

**Issue by selaaa-online** [neo4j/neo4j#13548]
LOAD CSV WITH HEADERS FROM "https://mySample/api/File/DownloadFile/mysample.csv" AS row fails with error

Cypher Neo4j Couldn't load the external resource from URL https://mySample/api/File/DownloadFile/mysample.csv

 stacktraces:
 
 Caused by: org.neo4j.exceptions.CypherExecutionException: Failed to parse query `LOAD CSV FROM "https://mySample/api/File/DownloadFile/mysample.csv".
                at org.neo4j.cypher.internal.ast.factory.neo4j.JavaCCParser$.parse(JavaCCParser.scala:61) ~[neo4j-cypher-ast-factory-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.Parse$.process(Parse.scala:38) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.Parse$.process(Parse.scala:31) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.Phase.$anonfun$transform$1(Phase.scala:36) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.helpers.package$.$anonfun$closing$1(package.scala:25) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.helpers.package$.using(package.scala:34) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.helpers.package$.closing(package.scala:25) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.Phase.transform(Phase.scala:35) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.Phase.transform$(Phase.scala:33) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.Parse$.transform(Parse.scala:31) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78) ~[neo4j-front-end-5.18.1.jar:5.18.1]
                at org.neo4j.cypher.internal.compiler.CypherParsing.parseQuery(CypherParsing.scala:80) ~[neo4j-cypher-planner-5.18.1.jar:5.18.1]
                at org.neo4j.router.impl.query.QueryProcessorImpl.parse(QueryProcessorImpl.java:271) ~[neo4j-query-router-5.18.1.jar:5.18.1]
                at org.neo4j.router.impl.query.QueryProcessorImpl.prepareQueryForCache(QueryProcessorImpl.java:160) ~[neo4j-query-router-5.18.1.jar:5.18.1]
                at org.neo4j.router.impl.query.QueryProcessorImpl.getFromCache(QueryProcessorImpl.java:144) ~[neo4j-query-router-5.18.1.jar:5.18.1]
                at org.neo4j.router.impl.query.QueryProcessorImpl.processQuery(QueryProcessorImpl.java:104) ~[neo4j-query-router-5.18.1.jar:5.18.1]
                at org.neo4j.router.impl.QueryRouterImpl.executeQuery(QueryRouterImpl.java:198) ~[neo4j-query-router-5.18.1.jar:5.18.1]
                at org.neo4j.router.impl.bolt.QueryRouterBoltSpi$Transaction.executeQuery(QueryRouterBoltSpi.java:162) ~[neo4j-query-router-5.18.1.jar:5.18.1]
                at org.neo4j.bolt.tx.TransactionImpl.run(TransactionImpl.java:136) ~[neo4j-bolt-5.18.1.jar:5.18.1]
                at org.neo4j.bolt.protocol.common.fsm.transition.transaction.CreateStatementStateTransition.process(CreateStatementStateTransition.java:48) ~[neo4j-bolt-5.18.1.jar:5.18.1]

### Expected behavior
neo4j 5.18 should load the csv file from the given private URL

### Actual behavior
Unable load neo4j 5.18 from the given private URL

Note:

Same private URL gets downloaded via accessing the browser.
Also other public csv url's gets loaded from neo4j as well.

**Comment by mnd999** [comment]
Hi @selaa-online, I think there is more to this. The stack trace you provide indicates a parsing issue, and thus seems to me me to be unrelated to the the failing query, since if it would not parse, it would not know that it is a LOAD CSV. It looks like maybe on that attempt, a closing `"` was missed. 

You sat that it works via browser, what client are you using where you see the failure? And in what environment (
e.g. docker locally, Aura, standalone server, embedded?  For LOAD CSV to work, the Neo4j server will need to be able to reach the private URL to read the CSV. It does not go via the client.

**Comment by selaaa-online** [comment]
Hi @mnd999  Thanks for the prompt response. Apologies for missing typo for `"` 

This is the exact query used :

`LOAD CSV FROM "https://sampleurl-INTERNAL-URL.com/api/File/DownloadFile/sample.csv" AS row return row`

The above query gives the error. But the below URL from public work fine.

`LOAD CSV FROM "https://sample-PUBLIC-url.com/api/File/DownloadFile/sample.csv" AS row return row`

Error occurs in  neo4j versions higher than 5.12. Both the above queries works in neo4j 5.12 community version installed as windows service.

What I meant by it works via browser is that the file served via the above given URLs downloads a csv file successfully without any issue when you copy and paste the both above URL in the google chrome (browser address bar). But it isnt loading via LOAD CSV query in neo4j

**Comment by loveleif** [comment]
Thanks for the report. Do your URL have redirects to another protocol (for example https => http)? That's not allowed for security reasons (see https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/#_import_from_a_remote_location). You can check this with `curl -L -I <url>`. If that is the case you need to use the redirected URL in your query.

**Comment by selaaa-online** [comment]
Hi @loveleif Yes this was tested with the curl call as well. there is no redirect from HTTPS to HTTP. both DB server and APP server is on HTTPS. And yes we are trying to load a CSV from remote location.

**Comment by selaaa-online** [comment]
Hi @loveleif @mnd999 

Does the above issue have anything to do with load privileges mentioned [here](https://neo4j.com/docs/operations-manual/5/authentication-authorization/load-privileges/).

If so is there any workaround available for loading privileges for the version 5.18 community

**Comment by mnd999** [comment]
I don't think we have enough information to know what the problem is. There were some changes made to support the load privileges, but these should not impact the community edition since there are no RBAC privileges there. 

I think we would need to understand a bit more how the file is being accessed. Anything you have from the logs, or some verbose output from curl (ideally from the Neo4j server) would help to understand what it's trying to do and why it is failing. As I said, I don't think the above stack trace is relevent, it's due to parsing.

**Comment by selaaa-online** [comment]
Closing the issue as it is being resolved via an HTTPS binding in IIS server.
Working as expected.
