### ISSUE TITLE
2.0.0-RC1 server start failed in Cloud9

### ISSUE THREAD

**Issue by richard-tian** [neo4j/neo4j#1596]
Try to start neo4j in Cloud9 Terminal, but failed. plz check, thanks

Version
----------------------
neo4j-community-2.0.0-RC1
jre1.7.0_45 

Configure
----------------------
org.neo4j.server.webserver.address="127.12.149.129" # from environment var, also tried without quotation mark
org.neo4j.server.webserver.port=16500
org.neo4j.server.webserver.https.port=16600

Log
----------------------
Nov 30, 2013 2:54:58 AM org.neo4j.server.logging.Logger log
SEVERE: Failed to start Neo Server on port [16500]
Nov 30, 2013 3:03:23 AM org.neo4j.server.logging.Logger log
INFO: Setting startup timeout to: 120000ms based on -1
Nov 30, 2013 3:03:35 AM org.neo4j.server.logging.Logger log
SEVERE: Failed to start database.
Nov 30, 2013 3:03:35 AM org.neo4j.server.logging.Logger log
SEVERE: 
org.neo4j.server.ServerStartupException: Starting Neo4j Server failed: Error starting org.neo4j.kernel.EmbeddedGraphDatabase, /var/lib/stickshift/52969a18500446517f000042/app-root/data/695281/temp/neo4j-community-2.0.0-RC1/data/graph.db
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:209)
	at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:87)
	at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:50)
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.EmbeddedGraphDatabase, /var/lib/stickshift/52969a18500446517f000042/app-root/data/695281/temp/neo4j-community-2.0.0-RC1/data/graph.db
	at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:324)
	at org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:63)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:92)
	at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:198)
	at org.neo4j.server.database.CommunityDatabase.createDb(CommunityDatabase.java:62)
	at org.neo4j.server.database.CommunityDatabase.start(CommunityDatabase.java:120)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:150)
	... 2 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@43c0f4d5' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:504)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115)
	at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:301)
	... 8 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.shell.impl.ShellServerKernelExtension@64f995bd' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:504)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115)
	at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:118)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:498)
	... 10 more
Caused by: java.rmi.server.ExportException: Port already in use: 0; nested exception is: 
	java.net.BindException: Permission denied
	at sun.rmi.transport.tcp.TCPTransport.listen(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport.exportObject(Unknown Source)
	at sun.rmi.transport.tcp.TCPEndpoint.exportObject(Unknown Source)
	at sun.rmi.transport.LiveRef.exportObject(Unknown Source)
	at sun.rmi.server.UnicastServerRef.exportObject(Unknown Source)
	at java.rmi.server.UnicastRemoteObject.exportObject(Unknown Source)
	at java.rmi.server.UnicastRemoteObject.exportObject(Unknown Source)
	at java.rmi.server.UnicastRemoteObject.<init>(Unknown Source)
	at java.rmi.server.UnicastRemoteObject.<init>(Unknown Source)
	at org.neo4j.shell.impl.RemotelyAvailableServer.<init>(RemotelyAvailableServer.java:46)
	at org.neo4j.shell.impl.SimpleAppServer.makeRemotelyAvailable(SimpleAppServer.java:182)
	at org.neo4j.shell.impl.ShellBootstrap.enable(ShellBootstrap.java:122)
	at org.neo4j.shell.impl.ShellBootstrap.load(ShellBootstrap.java:112)
	at org.neo4j.shell.impl.ShellServerKernelExtension.start(ShellServerKernelExtension.java:47)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:498)
	... 13 more
Caused by: java.net.BindException: Permission denied
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.net.ServerSocket.bind(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createServerSocket(Unknown Source)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createServerSocket(Unknown Source)
	at sun.rmi.transport.tcp.TCPEndpoint.newServerSocket(Unknown Source)
	... 28 more

Nov 30, 2013 3:03:36 AM org.neo4j.server.logging.Logger log
SEVERE: Failed to start Neo Server on port [16500]

net status
----------------------
checked using netstat, 16500 port is available
(master) $ netstat -nptl|grep 16
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 10.144.6.165:8443           0.0.0.0:*                   LISTEN      -                   
tcp        0      0 127.10.210.1:16379          0.0.0.0:*                   LISTEN      -                   
tcp        0      0 10.144.6.165:2303           0.0.0.0:*                   LISTEN      -                   
tcp        0      0 10.144.6.165:2304           0.0.0.0:*                   LISTEN      -                   
tcp        0      0 10.144.6.165:8000           0.0.0.0:*                   LISTEN      -                   
tcp        0      0 10.144.6.165:2305           0.0.0.0:*                   LISTEN      -                   
tcp        0      0 10.144.6.165:2306           0.0.0.0:*                   LISTEN      -                   
tcp        0      0 10.144.6.165:10050          0.0.0.0:*                   LISTEN      -                   
tcp        0      0 10.144.6.165:2307           0.0.0.0:*                   LISTEN      -                   
tcp        0      0 10.144.6.165:2308           0.0.0.0:*                   LISTEN      -  

test port availability again with node.js
----------------------
var net = require('net');
var server = net.createServer(function(c) { //'connection' listener
  console.log('server connected');
  c.on('end', function() {
    console.log('server disconnected');
  });
  c.write('hello\r\n');
  c.pipe(c);
});
server.listen(16500, '127.12.149.129', function() { //'listening' listener
  console.log('server bound');
});

test result below
$ node node.js/test.js
server bound

**Comment by jakewins** [comment]
This has now been resolved, the host can be configured using `remote_shell_host`
