### ISSUE TITLE
Full text indexing using the REST server: IOException: Response header too large

### ISSUE THREAD

**Issue by leosoto** [neo4j/neo4j#1807]
We are using a lucene fulltext search within neo4j (v2.0.0 enterprise) mostly successfully, except for relatively large text content (observed cases range from 5k to 27k). When posting to `/db/data/index/node/<index_name>` and such large values we are getting 500 errors and the following exception is logged on console.log:

```
java.io.IOException: Response header too large
        at org.eclipse.jetty.http.HttpGenerator.generateResponse(HttpGenerator.java:382) ~[jetty-http-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.HttpConnection$CommitCallback.process(HttpConnection.java:636) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:79) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:349) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:626) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:661) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:210) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at java.io.OutputStream.write(OutputStream.java:75) ~[na:1.7.0_25]
        at com.sun.jersey.spi.container.servlet.WebComponent$Writer.write(WebComponent.java:299) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.ContainerResponse$CommittingOutputStream.write(ContainerResponse.java:128) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.core.impl.provider.entity.ByteArrayProvider.writeTo(ByteArrayProvider.java:95) ~[jersey-core-1.9.jar:1.9]
        at com.sun.jersey.core.impl.provider.entity.ByteArrayProvider.writeTo(ByteArrayProvider.java:59) ~[jersey-core-1.9.jar:1.9]
        at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1437) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699) ~[jersey-server-1.9.jar:1.9]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201112011016.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1506) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.neo4j.server.rest.security.SecurityFilter.doFilter(SecurityFilter.java:112) ~[neo4j-server-2.0.0.jar:2.0.0]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1477) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:211) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.Server.handle(Server.java:445) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) ~[jetty-io-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
Caused by: java.nio.BufferOverflowException: null
        at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:183) ~[na:1.7.0_25]
        at java.nio.ByteBuffer.put(ByteBuffer.java:832) ~[na:1.7.0_25]
        at org.eclipse.jetty.http.HttpField.putTo(HttpField.java:213) ~[jetty-http-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.http.HttpGenerator.generateHeaders(HttpGenerator.java:680) ~[jetty-http-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.http.HttpGenerator.generateResponse(HttpGenerator.java:367) ~[jetty-http-9.0.5.v20130815.jar:9.0.5.v20130815]
        ... 39 common frames omitted
```

[Seems like this is related to #1232, but I wonder why 5kb of indexed text still trigger the problem given that the fix for #1232 commited in cd0cc83b6d0700f553dad127860c9ad543d1754a sets a 20kb limit on the buffer ]

**Comment by technige** [comment]
Closing as this applies to an old, unsupported product.
