### ISSUE TITLE
Neo4j - Generic shell - TEST FAIL

### ISSUE THREAD

**Issue by lc3t35** [neo4j/neo4j#1820]
mvn -v
Apache Maven 3.0.3 (r1075438; 2011-02-28 18:31:09+0100)
Maven home: /usr/share/maven
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.8.5", arch: "x86_64", family: "mac"

command:
mvn clean install -DfullBuild

```
[INFO] Building Neo4j - Generic shell 2.0-SNAPSHOT
/.../
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.neo4j.shell.impl.BashVariableInterpreterTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.398 sec - in org.neo4j.shell.impl.BashVariableInterpreterTest
Running org.neo4j.shell.impl.ShellBootstrapTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.069 sec - in org.neo4j.shell.impl.ShellBootstrapTest
Running org.neo4j.shell.impl.TestShellServerExtension
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.633 sec - in org.neo4j.shell.impl.TestShellServerExtension
Running org.neo4j.shell.kernel.apps.CdTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.144 sec - in org.neo4j.shell.kernel.apps.CdTest
Running org.neo4j.shell.OutputAsWriterTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in org.neo4j.shell.OutputAsWriterTest
Running org.neo4j.shell.ServerClientInteractionTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.238 sec <<< FAILURE! - in org.neo4j.shell.ServerClientInteractionTest
shouldConsiderAndInterpretCustomClientPrompt(org.neo4j.shell.ServerClientInteractionTest)  Time elapsed: 0.238 sec  <<< FAILURE!
java.lang.AssertionError: Prompt from server 'MyPrompt dim. janv. 12 19:14:04$ ' didn't match pattern 'MyPrompt .{1,3} .{1,3} \d{1,2} \d{2}:\d{2}:\d{2}\$'
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.neo4j.shell.ServerClientInteractionTest.shouldConsiderAndInterpretCustomClientPrompt(ServerClientInteractionTest.java:55)

Running org.neo4j.shell.SessionTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in org.neo4j.shell.SessionTest
Running org.neo4j.shell.ShellDocTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.262 sec - in org.neo4j.shell.ShellDocTest
Running org.neo4j.shell.StartClientTest
+-------------------+
| No data returned. |
+-------------------+
/.../
Results :

Failed tests: 
  ServerClientInteractionTest.shouldConsiderAndInterpretCustomClientPrompt:55 Prompt from server 
'MyPrompt dim. janv. 12 19:14:04$ ' didn't match pattern 'MyPrompt .{1,3} .{1,3} \d{1,2} \d{2}:\d{2}:\d{2}\$'

Tests run: 109, Failures: 1, Errors: 0, Skipped: 1
/.../
[INFO] Reactor Summary:
[INFO] 
[INFO] Neo4j ............................................. SUCCESS [2.004s]
[INFO] Licensing configuration ........................... SUCCESS [0.884s]
[INFO] Neo4j - Graph Database Kernel ..................... SUCCESS [2:25.109s]
[INFO] Neo4j - JMX support ............................... SUCCESS [9.738s]
[INFO] Neo4j - Usage Data Collection ..................... SUCCESS [29.262s]
[INFO] Neo4j - Graphviz generation ....................... SUCCESS [9.557s]
[INFO] Neo4j - Lucene Index .............................. SUCCESS [1:39.615s]
[INFO] Neo4j - Graph Algorithms .......................... SUCCESS [10.482s]
[INFO] Neo4j - Graph Matching ............................ SUCCESS [6.846s]
[INFO] Neo4j Community Cypher Build ...................... SUCCESS [4:23.114s]
[INFO] Neo4j - Cypher Commons ............................ SUCCESS [32.610s]
[INFO] Neo4j - Cypher Compiler 1.9 ....................... SUCCESS [1:38.046s]
[INFO] Neo4j - Cypher Compiler 2.0 ....................... SUCCESS [2:18.120s]
[INFO] Neo4j - Cypher .................................... SUCCESS [2:54.849s]
[INFO] Neo4j - Cypher Documentation ...................... SUCCESS [1:43.396s]
[INFO] Neo4j Community ................................... SUCCESS [2:07.265s]
[INFO] Neo4j Community ................................... SUCCESS [16.164s]
[INFO] Neo4j - Generic shell ............................. FAILURE [22.216s]
```

**Comment by antonio-castellon** [comment]
Hi @jexp ,
I have the same problem, I change the locale and in the Test appears the same error than @lc3t35 .
```
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)
Maven home: C:\SDK\JAVA\apache-maven-3.2.3
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: C:\SDK\JAVA\jdk1.8.0_25\jre
Default locale: en -duser.country=en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

Any idea?

**Comment by craigtaverner** [comment]
Neo4j-shell has been deprecated since Neo4j 3.0 and removed from the code base in Neo4j 3.5.
