### ISSUE TITLE
Can't start a slave in Read-Only mode (ServerStartupException in neo4j-enterprise 2.0.1)

### ISSUE THREAD

**Issue by dcolebatch** [neo4j/neo4j#2280]
We need to be able to easily mark a slave in a cluster as Read Only, to support the typical use-case of a reporting / ad-hoc query server. When we set one of the slave instances in the cluster to `read_only=true`, it bombs on startup with the below exception.  

Of course we have also tried with the combination of `slave_only=true` AND `read_only=true`, but to no avail.

```
org.neo4j.server.ServerStartupException: Starting Neo4j Server failed: org.neo4j.kernel.impl.transaction.ReadOnlyTxManager cannot be cast to org.neo4j.kernel.impl.transaction.TxManager
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:218) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:87) [neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:50) [neo4j-server-2.0.1.jar:2.0.1]
Caused by: java.lang.ClassCastException: org.neo4j.kernel.impl.transaction.ReadOnlyTxManager cannot be cast to org.neo4j.kernel.impl.transaction.TxManager
        at org.neo4j.kernel.ha.HighlyAvailableGraphDatabase.create(HighlyAvailableGraphDatabase.java:153) ~[neo4j-ha-2.0.1.jar:2.0.1]
        at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:301) ~[neo4j-kernel-2.0.1.jar:2.0.1]
        at org.neo4j.kernel.ha.HighlyAvailableGraphDatabase.<init>(HighlyAvailableGraphDatabase.java:140) ~[neo4j-ha-2.0.1.jar:2.0.1]
        at org.neo4j.graphdb.factory.HighlyAvailableGraphDatabaseFactory$1.newDatabase(HighlyAvailableGraphDatabaseFactory.java:47) ~[neo4j-ha-2.0.1.jar:2.0.1]
        at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:198) ~[neo4j-kernel-2.0.1.jar:2.0.1]
        at org.neo4j.server.enterprise.EnterpriseDatabase$DatabaseMode$2.createDatabase(EnterpriseDatabase.java:52) ~[neo4j-server-enterprise-2.0.1.jar:2.0.1]
        at org.neo4j.server.enterprise.EnterpriseDatabase.createDb(EnterpriseDatabase.java:74) ~[neo4j-server-enterprise-2.0.1.jar:2.0.1]
        at org.neo4j.server.database.CommunityDatabase.start(CommunityDatabase.java:120) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:158) ~[neo4j-server-2.0.1.jar:2.0.1]
        ... 2 common frames omitted
```

**Comment by chrisvest** [comment]
This was fixed in 2.2.0 by aaea4e1c8c3b42109ed7da966d49f1bac11b6c2c
