### ISSUE TITLE
backup not writing to stderr when a connection cannot be made

### ISSUE THREAD

**Issue by wouterv** [neo4j/neo4j#2296]
We have a backup script that checks whether there are any errors during backup and it does so by looking at stderr. However when neo4j-backup cannot connect to the host it needs to backup from, it does not output anything to stderr, instead it dumps a stacktrace to stdout.

So something like:

    # bin/neo4j-backup -from single://foobar -to /tmp/foo 2> /tmp/testerror
    Performing full backup from 'single://foobar'
    Couldn't connect to 'single://foobar'
    org.neo4j.com.ComException: BackupClient could not connect to foobar:6362
	    at org.neo4j.com.Client$1.create(Client.java:143)
	    at org.neo4j.com.Client$1.create(Client.java:125)
	    at org.neo4j.com.ResourcePool.acquire(ResourcePool.java:175)
	    at org.neo4j.com.Client.getChannel(Client.java:308)
	    at org.neo4j.com.Client.sendRequest(Client.java:211)
	    at org.neo4j.com.Client.sendRequest(Client.java:198)
	    at org.neo4j.backup.BackupClient.fullBackup(BackupClient.java:50)
	    at org.neo4j.backup.BackupService.doFullBackup(BackupService.java:110)
	    at org.neo4j.backup.BackupTool.doBackupFull(BackupTool.java:230)
	    at org.neo4j.backup.BackupTool.doBackup(BackupTool.java:217)
	    at org.neo4j.backup.BackupTool.run(BackupTool.java:156)
	    at org.neo4j.backup.BackupTool.main(BackupTool.java:70)
    # cat /tmp/testerror 

nothing is shown

**Comment by benbc** [comment]
@wouterv From 3.1, backup is provided by `neo4j-admin backup` which, among other things, addresses the problems here. This will be available in a 3.1 milestone soon.
