### ISSUE TITLE
NullPointerException in castOrFail(CastSupport.scala:41)

### ISSUE THREAD

**Issue by lbuczkow** [neo4j/neo4j#2490]
The following query against neo4j 2.1 database embedded in a Java app raises an exception:

OPTIONAL MATCH (friend:FacebookFriend {id: {id}})
SET friend:User

({id} is a string like '100001234567890')

```
java.lang.NullPointerException
    at org.neo4j.cypher.internal.helpers.CastSupport$.castOrFail(CastSupport.scala:41)
    at org.neo4j.cypher.internal.compiler.v2_1.commands.LabelAction.exec(LabelAction.scala:46)
    at org.neo4j.cypher.internal.compiler.v2_1.pipes.ExecuteUpdateCommandsPipe.org$neo4j$cypher$internal$compiler$v2_1$pipes$ExecuteUpdateCommandsPipe$$exec(ExecuteUpdateCommandsPipe.scala:55)
    at org.neo4j.cypher.internal.compiler.v2_1.pipes.ExecuteUpdateCommandsPi$$$$1019fdff8b266d7d9d5647386930b3d8$$$$ands$1$$anonfun$apply$2.apply(ExecuteUpdateCommandsPipe.scala:44)
    at org.neo4j.cypher.internal.compiler.v2_1.pipes.ExecuteUpdateCommandsPi$$$$1019fdff8b266d7d9d5647386930b3d8$$$$ands$1$$anonfun$apply$2.apply(ExecuteUpdateCommandsPipe.scala:44)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.builders.QueryStateSettingIterator.hasNext(QueryStateSettingIterator.scala:27)
    at scala.collection.Iterator$class.isEmpty(Iterator.scala:256)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.builders.QueryStateSettingIterator.isEmpty(QueryStateSettingIterator.scala:25)
    at scala.collection.TraversableOnce$class.nonEmpty(TraversableOnce.scala:109)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.builders.QueryStateSettingIterator.nonEmpty(QueryStateSettingIterator.scala:25)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.builders.IfElseIterator.fillBuffer(IfElseIterator.scala:56)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.builders.IfElseIterator.hasNext(IfElseIterator.scala:37)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.builders.IfElseIterator.foreach(IfElseIterator.scala:28)
    at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
    at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:176)
    at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
    at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.builders.IfElseIterator.to(IfElseIterator.scala:28)
    at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:257)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.builders.IfElseIterator.toList(IfElseIterator.scala:28)
    at org.neo4j.cypher.internal.compiler.v2_1.pipes.EagerPipe.internalCreateResults(EagerPipe.scala:31)
    at org.neo4j.cypher.internal.compiler.v2_1.pipes.PipeWithSource.createResults(Pipe.scala:98)
    at org.neo4j.cypher.internal.compiler.v2_1.pipes.PipeWithSource.createResults(Pipe.scala:95)
    at org.neo4j.cypher.internal.compiler.v2_1.pipes.PipeWithSource.createResults(Pipe.scala:95)
    at org.neo4j.cypher.internal.compiler.v2_1.pipes.PipeWithSource.createResults(Pipe.scala:95)
    at org.neo4j.cypher.internal.compiler.v2_1.pipes.PipeWithSource.createResults(Pipe.scala:95)
    at org.neo4j.cypher.internal.compiler.v2_1.pipes.PipeWithSource.createResults(Pipe.scala:95)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1$$anonfun$apply$2.apply(ExecutionPlanBuilder.scala:119)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1$$anonfun$apply$2.apply(ExecutionPlanBuilder.scala:118)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.ExecutionWorkflowBuilder.runWithQueryState(ExecutionPlanBuilder.scala:169)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:117)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:102)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.ExecutionPlanBuilder$$anon$1.execute(ExecutionPlanBuilder.scala:68)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.ExecutionPlanBuilder$$anon$1.execute(ExecutionPlanBuilder.scala:67)
    at org.neo4j.cypher.internal.ExecutionPlanWrapperForV2_1.execute(CypherCompiler.scala:126)
    at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:75)
    at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:69)
    at org.neo4j.cypher.javacompat.ExecutionEngine.execute(ExecutionEngine.java:84)
```

**Comment by Mats-SX** [comment]
Long since fixed.
