### ISSUE TITLE
Neo4j 2.1.2 Nested collection function doesn't work with parameters

### ISSUE THREAD

**Issue by MatAtBread** [neo4j/neo4j#2618]
The following query:

````
match (g:TagGroup)<-[t:TAGGED]-(p:Product)-[:OFFERED]->(o:Offer)<-[offers:OFFERS]-(u:User) 
where not has(g.hidden) and g.numProducts>3 
with distinct g,u, sum(o.mass)^1.6/g.numProducts^0.6 as n order by n desc 
with g.name as tag,collect(u.fingerprint)[0..4] as fps,collect(u)[0..4] as user 
with tag,fps,user,filter(fp in ["I5aJXcRLfqx"] where fp in fps) as inter
where length(inter)>0
return tag,user

````

....doesn't parse when the hard-coded array in the filter statement is replaced with a (correctly supplied) array of strings as a map parameter. The environment is an embedded Java instance. The full trace is:

````

Error: Error running instance method
...Unknown identifier `  AGGREGATION459`
...Unknown identifier `tag`.
...Unknown identifier `user`.
...	at org.neo4j.cypher.internal.compiler.v2_1.executionplan.LegacyPipeBuilder.produceAndThrowException(LegacyPipeBuilder.scala:109)
...	at org.neo4j.cypher.internal.compiler.v2_1.executionplan.LegacyPipeBuilder.buildQuery(LegacyPipeBuilder.scala:78)
...	at org.neo4j.cypher.internal.compiler.v2_1.executionplan.LegacyPipeBuilder.producePlan(LegacyPipeBuilder.scala:42)
...	at org.neo4j.cypher.internal.compiler.v2_1.executionplan.ExecutionPlanBuilder.build(ExecutionPlanBuilder.scala:62)
...	at org.neo4j.cypher.internal.compiler.v2_1.CypherCompiler$$anonfun$3.apply(CypherCompiler.scala:110)
...	at org.neo4j.cypher.internal.compiler.v2_1.CypherCompiler$$anonfun$3.apply(CypherCompiler.scala:110)
...	at org.neo4j.cypher.internal.compiler.v2_1.MonitoringCacheAccessor$$anonfun$1.apply(CacheAccessor.scala:36)
...	at org.neo4j.cypher.internal.LRUCache.getOrElseUpdate(LRUCache.scala:35)
...	at org.neo4j.cypher.internal.LRUCache.apply(LRUCache.scala:61)
...	at org.neo4j.cypher.internal.LRUCache.apply(LRUCache.scala:25)
...	at org.neo4j.cypher.internal.compiler.v2_1.MonitoringCacheAccessor.getOrElseUpdate(CacheAccessor.scala:34)
...	at org.neo4j.cypher.internal.compiler.v2_1.CypherCompiler.prepare(CypherCompiler.scala:109)
...	at org.neo4j.cypher.internal.CypherCompiler.prepare(CypherCompiler.scala:73)
...	at org.neo4j.cypher.ExecutionEngine$$anonfun$liftedTree1$1$1.apply(ExecutionEngine.scala:95)
...	at org.neo4j.cypher.ExecutionEngine$$anonfun$liftedTree1$1$1.apply(ExecutionEngine.scala:93)
...	at org.neo4j.cypher.internal.compiler.v2_1.MonitoringCacheAccessor$$anonfun$1.apply(CacheAccessor.scala:36)
...	at org.neo4j.cypher.internal.LRUCache.getOrElseUpdate(LRUCache.scala:35)
...	at org.neo4j.cypher.internal.LRUCache.apply(LRUCache.scala:61)
...	at org.neo4j.cypher.internal.LRUCache.apply(LRUCache.scala:25)
...	at org.neo4j.cypher.internal.compiler.v2_1.MonitoringCacheAccessor.getOrElseUpdate(CacheAccessor.scala:34)
...	at org.neo4j.cypher.ExecutionEngine.liftedTree1$1(ExecutionEngine.scala:93)
...	at org.neo4j.cypher.ExecutionEngine.prepare(ExecutionEngine.scala:87)
...	at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:74)
...	at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:69)
...	at org.neo4j.cypher.javacompat.ExecutionEngine.execute(ExecutionEngine.java:84)
...	at Neo4jWrapper.execMapQuery(Neo4jWrapper.java:278)
...	at Neo4jWrapper.cypher(Neo4jWrapper.java:258)
...	at sun.reflect.GeneratedMethodAccessor125.invoke(Unknown Source)
...	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...	at java.lang.reflect.Method.invoke(Method.java:606)

````

**Comment by Mats-SX** [comment]
Closing this as the reported version is old enough to not be considered for fixing. If this can be reproduced on `2.3` or later, please open a new issue.
