### ISSUE TITLE
Cypher Parser Error for shortestPath() without path length in 2.1.2, but not in 2.0.0

### ISSUE THREAD

**Issue by klti** [neo4j/neo4j#2644]
The following query executes in 2.0.0, but gives a strange Syntax error in 2.1.2:
```
MATCH (m:MANDATOR {IDENTIFIER: '0'}), (m)<-[:BELONGS_TO]-(begin:STOP {IDENTIFIER: '130'}), (m)<-[:BELONGS_TO]-(dest:STOP {IDENTIFIER: '164'}), (begin)-[:BOARD]-(l), p=shortestPath((l)-[:GOES_TO|ARRIVE]->(dest)) RETURN l;
```

The Error message on 2.1.2 is as follows:
```
        SyntaxException: Unknown identifier `  UNNAMED183`
Unknown identifier `l`.
Unknown identifier `  UNNAMED183`
Unknown identifier `l`.
        at org.neo4j.cypher.internal.compiler.v2_1.executionplan.LegacyPipeBuilder.produceAndThrowException(LegacyPipeBuilder.scala:109)
        at org.neo4j.cypher.internal.compiler.v2_1.executionplan.LegacyPipeBuilder.buildQuery(LegacyPipeBuilder.scala:78)
        at org.neo4j.cypher.internal.compiler.v2_1.executionplan.LegacyPipeBuilder.producePlan(LegacyPipeBuilder.scala:42)
        at org.neo4j.cypher.internal.compiler.v2_1.executionplan.ExecutionPlanBuilder.build(ExecutionPlanBuilder.scala:62)
        at org.neo4j.cypher.internal.compiler.v2_1.CypherCompiler$$anonfun$3.apply(CypherCompiler.scala:110)
        at org.neo4j.cypher.internal.compiler.v2_1.CypherCompiler$$anonfun$3.apply(CypherCompiler.scala:110)
        at org.neo4j.cypher.internal.compiler.v2_1.MonitoringCacheAccessor$$anonfun$1.apply(CacheAccessor.scala:36)
        at org.neo4j.cypher.internal.LRUCache.getOrElseUpdate(LRUCache.scala:35)
        at org.neo4j.cypher.internal.LRUCache.apply(LRUCache.scala:61)
        at org.neo4j.cypher.internal.LRUCache.apply(LRUCache.scala:25)
        at org.neo4j.cypher.internal.compiler.v2_1.MonitoringCacheAccessor.getOrElseUpdate(CacheAccessor.scala:34)
        at org.neo4j.cypher.internal.compiler.v2_1.CypherCompiler.prepare(CypherCompiler.scala:109)
        at org.neo4j.cypher.internal.CypherCompiler.prepare(CypherCompiler.scala:73)
        at org.neo4j.cypher.ExecutionEngine$$anonfun$liftedTree1$1$1.apply(ExecutionEngine.scala:95)
        at org.neo4j.cypher.ExecutionEngine$$anonfun$liftedTree1$1$1.apply(ExecutionEngine.scala:93)
        at org.neo4j.cypher.internal.compiler.v2_1.MonitoringCacheAccessor$$anonfun$1.apply(CacheAccessor.scala:36)
        at org.neo4j.cypher.internal.LRUCache.getOrElseUpdate(LRUCache.scala:35)
        at org.neo4j.cypher.internal.LRUCache.apply(LRUCache.scala:61)
        at org.neo4j.cypher.internal.LRUCache.apply(LRUCache.scala:25)
        at org.neo4j.cypher.internal.compiler.v2_1.MonitoringCacheAccessor.getOrElseUpdate(CacheAccessor.scala:34)
        at org.neo4j.cypher.ExecutionEngine.liftedTree1$1(ExecutionEngine.scala:93)
        at org.neo4j.cypher.ExecutionEngine.prepare(ExecutionEngine.scala:87)
        at org.neo4j.cypher.ExecutionEngine.profile(ExecutionEngine.scala:61)
        at org.neo4j.cypher.ExecutionEngine.profile(ExecutionEngine.scala:56)
        at org.neo4j.cypher.javacompat.ExecutionEngine.profile(ExecutionEngine.java:117)
        at org.neo4j.shell.kernel.apps.cypher.Profile.exec(Profile.java:63)
        at org.neo4j.shell.kernel.apps.TransactionProvidingApp.execute(TransactionProvidingApp.java:222)
        at org.neo4j.shell.impl.AbstractAppServer.interpretLine(AbstractAppServer.java:117)
        at org.neo4j.shell.kernel.GraphDatabaseShellServer.interpretLine(GraphDatabaseShellServer.java:93)
        at org.neo4j.shell.impl.RemotelyAvailableServer.interpretLine(RemotelyAvailableServer.java:60)
        at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322)
        at sun.rmi.transport.Transport$1.run(Transport.java:177)
        at sun.rmi.transport.Transport$1.run(Transport.java:174)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:173)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:556)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:811)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:670)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

When executed with ```CYPHER 2.0 [...]``` on Neo4J 2.1.2, it as accepted as well, so this really seems to be a Cypher 2.1 issue. When issued with a path length ```[...] p=shortestPath((l)-[:GOES_TO|ARRIVE*..15]->(dest)) [...]```, it is accepted by Cypher 2.1 as well.

At the very least, this is a case of very unhelpfull error message, but it really looks unexpected behavior to me.

This issue can be reproduced on servers without the related data.

**Comment by jakewins** [comment]
As per http://console.neo4j.org/r/v029fb this has been resolved.
