### ISSUE TITLE
Relationship isn't deleted

### ISSUE THREAD

**Issue by eunkyungkim** [neo4j/neo4j#2959]
Hi~
I'm using v2.1.3

Relationship isn't deleted.(not every relationships)

[Properties of the relationship]
summary	:     18444_47806_17916
strength   :     201408130100, 201408130300, 201408130500, 201408130700, 201408131300, 201408131500, 201408180100, 201408180317, 201408180551, 201408180923, 201408181542, 201408182100
midst_strength : 100, 100, 100, 100, 100, 111, 100, 100, 100, 100
display_strength : 1
group : netstat

[StartNode properties]
name: 	search-img-ser26
ip: 	xxx.xxx.xxx.xxx
type: 	host
updated_at:	1408321035
created_at:	1393233081
custom_group:	false
id:	18444
cpu:	Intel(R) Xeon(R) CPU E5620 @ 2.40GHz [4 core] * 2 N,
memory:	DDR3 [1333 MHz] 2048 * 2, DDR3 [1333 MHz] 4096 * 7, Unknown [1333 MHz] 4096 * 1,
disk:	[RAID 1+0] 546.8 GB * 1, [Smart Array P410i in Slot 0 (Embedded) [5.06] (512 MB :Unknown)] - [-] : 146.0 GB * 8,
status:	서비스
service:	이미지엔진검색
system:	DL360G7
team:	검색엔진팀
teamcode:	012202
installed_at:	1313938800
listen_ports:	60000, 5666, 53572, 39908, 48613, 1031, 199, 38344, 34124, 65101, 2381, 65102, 65103, 65199, 5679, 57232, 65104, 65105, 65106, 57331, 65107, 55796, 2580, 21, 22, 23, 43770, 2301, 52286, 34303, 65108, 48940, 35828, 48537, 58621
os	Linux

[EndNode properties]
name:	search-img-ser34
ip:	xxx.xxx.xxx.xxx
type:	host
updated_at:	1408321035
created_at:	1403504853
custom_group:	false
id:	17916
cpu:	Intel(R) Xeon(R) CPU E5620 @ 2.40GHz [4 core] * 2 N,
memory:	DDR3 [1333 MHz] 4096 * 7, DDR3 [1333 MHz] 2048 * 2, Unknown [1333 MHz] 4096 * 1,
disk:	[RAID 1+0] 546.8 GB * 1, [Smart Array P410i in Slot 0 (Embedded) [5.06] (512 MB :Unknown)] - [-] : 146.0 GB * 8,
status:	서비스
service:	이미지엔진검색
system:	DL360G7
team:	검색엔진팀
teamcode:	012202
installed_at:	1313938800
listen_ports:	60000, 5666, 1031, 53480, 45609, 5258, 65101, 2381, 65102, 52110, 65103, 5679, 54096, 65105, 65106, 54034, 65107, 49971, 65108, 2580, 40821, 21, 22, 23, 33432, 56665, 38106, 37883, 44764, 42141, 36125, 2301, 47806, 55748, 42470, 41179, 45758
os:	Linux

java.lang.NullPointerException: null
at org.neo4j.kernel.impl.nioneo.xa.RelationshipDeleter.updateNodesForDeletedRelationship(RelationshipDeleter.java:137) ~[neo4j-kernel-2.1.3.jar:2.1.3]
at org.neo4j.kernel.impl.nioneo.xa.RelationshipDeleter.relDelete(RelationshipDeleter.java:67) ~[neo4j-kernel-2.1.3.jar:2.1.3]
at org.neo4j.kernel.impl.nioneo.xa.NeoStoreTransactionContext.relationshipDelete(NeoStoreTransactionContext.java:84) ~[neo4j-kernel-2.1.3.jar:2.1.3]
at org.neo4j.kernel.impl.nioneo.xa.NeoStoreTransaction.relDelete(NeoStoreTransaction.java:832) ~[neo4j-kernel-2.1.3.jar:2.1.3]
at org.neo4j.kernel.impl.persistence.PersistenceManager.relDelete(PersistenceManager.java:140) ~[neo4j-kernel-2.1.3.jar:2.1.3]
at org.neo4j.kernel.impl.core.NodeManager.deleteRelationship(NodeManager.java:750) ~[neo4j-kernel-2.1.3.jar:2.1.3]
at org.neo4j.kernel.impl.api.state.OldTxStateBridgeImpl.deleteRelationship(OldTxStateBridgeImpl.java:164) ~[neo4j-kernel-2.1.3.jar:2.1.3]
at org.neo4j.kernel.impl.api.state.TxStateImpl.relationshipDoDelete(TxStateImpl.java:434) ~[neo4j-kernel-2.1.3.jar:2.1.3]
at org.neo4j.kernel.impl.api.StateHandlingStatementOperations$1.visit(StateHandlingStatementOperations.java:140) ~[neo4j-kernel-2.1.3.jar:2.1.3]
at org.neo4j.kernel.impl.api.store.CacheLayer.visit(CacheLayer.java:477) ~[neo4j-kernel-2.1.3.jar:2.1.3]
at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.relationshipDelete(StateHandlingStatementOperations.java:135) ~[neo4j-kernel-2.1.3.jar:2.1.3]
at org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.relationshipDelete(ConstraintEnforcingEntityOperations.java:159) ~[neo4j-kernel-2.1.3.jar:2.1.3]
at org.neo4j.kernel.impl.api.LockingStatementOperations.relationshipDelete(LockingStatementOperations.java:223) ~[neo4j-kernel-2.1.3.jar:2.1.3]
at org.neo4j.kernel.impl.api.OperationsFacade.relationshipDelete(OperationsFacade.java:522) ~[neo4j-kernel-2.1.3.jar:2.1.3]
at org.neo4j.kernel.impl.core.RelationshipProxy.delete(RelationshipProxy.java:84) ~[neo4j-kernel-2.1.3.jar:2.1.3]
at org.neo4j.server.rest.web.DatabaseActions.deleteRelationship(DatabaseActions.java:579) ~[neo4j-server-2.1.3.jar:2.1.3]
at org.neo4j.server.rest.web.RestfulGraphDatabase.deleteRelationship(RestfulGraphDatabase.java:642) ~[neo4j-server-2.1.3.jar:2.1.3]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_51]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_51]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.9.jar:1.9]
at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[jersey-server-1.9.jar:1.9]
at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-server-1.9.jar:1.9]
at org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139) ~[neo4j-server-2.1.3.jar:2.1.3]
at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288) ~[jersey-server-1.9.jar:1.9]
at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.9.jar:1.9]
at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[jersey-server-1.9.jar:1.9]
at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.9.jar:1.9]
at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[jersey-server-1.9.jar:1.9]
at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469) ~[jersey-server-1.9.jar:1.9]
at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400) ~[jersey-server-1.9.jar:1.9]
at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349) ~[jersey-server-1.9.jar:1.9]
at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339) ~[jersey-server-1.9.jar:1.9]
at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416) ~[jersey-server-1.9.jar:1.9]
at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537) ~[jersey-server-1.9.jar:1.9]
at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699) ~[jersey-server-1.9.jar:1.9]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201112011016.jar:na]
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:211) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
at org.eclipse.jetty.server.Server.handle(Server.java:445) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [jetty-io-9.0.5.v20130815.jar:9.0.5.v20130815]
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]

**Comment by jakewins** [comment]
The XA subsystem, where this error is coming from, has been removed entirely in 2.2. This should no longer be an issue if you upgrade to the latest version of Neo4j.
