### ISSUE TITLE
Need Urgent help  : Neo4j stop runnin at production

### ISSUE THREAD

**Issue by dppatel03** [neo4j/neo4j#3169]
I am getting following error while I start my neo4j in my production environment.
It was working fine just y'day and today my users complain that my production server is down.
I just check in realized that neo4j is down, and when I am trying to start server I am getting following error.

(1) message.log (found under database folder structure)

2014-09-29 08:19:49.946+0000 INFO  [o.n.k.i.n.s.StoreFactory]: [/data/gd/graph.db/neostore.schemastore.db] brickCount=0 brickSize=0b mappedMem=0b (storeSize=64b)
2014-09-29 08:19:49.947+0000 INFO  [o.n.k.i.n.s.StoreFactory]: [/data/gd/graph.db/neostore] brickCount=0 brickSize=0b mappedMem=0b (storeSize=63b)
2014-09-29 08:19:49.978+0000 INFO  [o.n.k.i.t.x.XaLogicalLog]: Opened logical log [/data/gd/graph.db/nioneo_logical.log.1] version=7, lastTxId=35049 (clean)
2014-09-29 08:19:49.981+0000 INFO  [o.n.k.i.t.TxManager]: TM opening log: /data/gd/graph.db/tm_tx_log.1
2014-09-29 08:19:49.982+0000 INFO  [o.n.k.i.t.KernelHealth]: Kernel health set to OK
-------------------
2014-09-29 08:21:57.515+0000 ERROR [o.n.k.i.t.XaDataSourceManager]: Failed when notifying registering listener
org.neo4j.kernel.impl.nioneo.store.UnderlyingStorageException: Unable to load position[1] @[9]
        at org.neo4j.kernel.impl.nioneo.store.PersistenceRow.readFullWindow(PersistenceRow.java:162) ~[neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.impl.nioneo.store.PersistenceRow$State$1.transition(PersistenceRow.java:114) ~[neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.impl.nioneo.store.PersistenceRow.lock(PersistenceRow.java:58) ~[neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.impl.nioneo.store.PersistenceWindowPool.acquire(PersistenceWindowPool.java:197) ~[neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.impl.nioneo.store.CommonAbstractStore.acquireWindow(CommonAbstractStore.java:430) ~[neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.impl.nioneo.store.NeoStore.getRecord(NeoStore.java:501) ~[neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.impl.nioneo.store.NeoStore.getRandomNumber(NeoStore.java:414) ~[neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.impl.nioneo.xa.NeoStoreXaDataSource.getRandomIdentifier(NeoStoreXaDataSource.java:643) ~[neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.ext.udc.impl.DefaultUdcInformationCollector$1.registeredDataSource(DefaultUdcInformationCollector.java:81) ~[neo4j-udc-2.0.3.jar:na]
        at org.neo4j.kernel.impl.transaction.XaDataSourceManager.addDataSourceRegistrationListener(XaDataSourceManager.java:128) ~[neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.ext.udc.impl.DefaultUdcInformationCollector.<init>(DefaultUdcInformationCollector.java:73) [neo4j-udc-2.0.3.jar:na]
        at org.neo4j.ext.udc.impl.UdcKernelExtension.start(UdcKernelExtension.java:71) [neo4j-udc-2.0.3.jar:na]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:118) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:328) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:56) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:90) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:199) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.server.database.CommunityDatabase.createDb(CommunityDatabase.java:66) [neo4j-server-2.0.3.jar:2.0.3]
        at org.neo4j.server.database.CommunityDatabase.start(CommunityDatabase.java:130) [neo4j-server-2.0.3.jar:2.0.3]
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:166) [neo4j-server-2.0.3.jar:2.0.3]
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:103) [neo4j-server-2.0.3.jar:2.0.3]
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:57) [neo4j-server-2.0.3.jar:2.0.3]
Caused by: java.nio.channels.ClosedByInterruptException: null
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202) ~[na:1.7.0_65]
        at sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:706) ~[na:1.7.0_65]
        at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:685) ~[na:1.7.0_65]
        at org.neo4j.kernel.impl.nioneo.store.StoreFileChannel.read(StoreFileChannel.java:83) ~[neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.impl.nioneo.store.PersistenceRow.readFullWindow(PersistenceRow.java:157) ~[neo4j-kernel-2.0.3.jar:2.0.3]
        ... 25 common frames omitted
2014-09-29 08:21:57.531+0000 ERROR [o.n.k.i.t.TxManager]: Unable to close tx log[/data/gd/graph.db/tm_tx_log.1]
java.nio.channels.ClosedByInterruptException: null
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202) ~[na:1.7.0_65]
        at sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:744) ~[na:1.7.0_65]
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:724) ~[na:1.7.0_65]
        at org.neo4j.kernel.impl.nioneo.store.StoreFileChannel.write(StoreFileChannel.java:51) ~[neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.impl.transaction.xaframework.DirectMappedLogBuffer.writeOut(DirectMappedLogBuffer.java:164) ~[neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.impl.transaction.xaframework.DirectMappedLogBuffer.force(DirectMappedLogBuffer.java:178) ~[neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.impl.transaction.TxLog.close(TxLog.java:166) ~[neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.impl.transaction.TxManager.closeLog(TxManager.java:276) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.impl.transaction.TxManager.stop(TxManager.java:233) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:123) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:328) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:56) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:90) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:199) [neo4j-kernel-2.0.3.jar:2.0.3]
        at org.neo4j.server.database.CommunityDatabase.createDb(CommunityDatabase.java:66) [neo4j-server-2.0.3.jar:2.0.3]
        at org.neo4j.server.database.CommunityDatabase.start(CommunityDatabase.java:130) [neo4j-server-2.0.3.jar:2.0.3]
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:166) [neo4j-server-2.0.3.jar:2.0.3]
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:103) [neo4j-server-2.0.3.jar:2.0.3]
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:57) [neo4j-server-2.0.3.jar:2.0.3]
2014-09-29 08:21:57.532+0000 INFO  [o.n.k.i.t.TxManager]: TM shutting down
2014-09-29 08:21:57.538+0000 INFO  [o.n.k.i.DiagnosticsManager]: --- STOPPING diagnostics START ---
2014-09-29 08:21:57.538+0000 INFO  [o.n.k.i.DiagnosticsManager]: --- STOPPING diagnostics END ---
2014-09-29 08:21:57.552+0000 ERROR [o.n.k.EmbeddedGraphDatabase]: Startup failed: Component 'org.neo4j.kernel.impl.transaction.XaDataSourceManager@2bab3b6a' failed to stop. Please see attached cause exception.: Component 'org.neo4j.kernel.impl.nioneo.xa.NeoStoreXaDataSource@497f6a92' failed to stop. Please see attached cause exception.: java.nio.channels.ClosedByInterruptException: null: Component 'org.neo4j.kernel.extension.KernelExtensions@703601d7' was successfully initialized, but failed to start. Please see attached cause exception.: Component 'org.neo4j.index.lucene.LuceneKernelExtension@52b2093d' was successfully initialized, but failed to start. Please see attached cause exception.: Component 'org.neo4j.index.impl.lucene.LuceneDataSource@5d6fbc47' was successfully initialized, but failed to start. Please see attached cause exception.: java.nio.channels.ClosedByInterruptException: null
2014-09-29 08:21:57.552+0000 INFO  [o.n.k.EmbeddedGraphDatabase]: Shutdown started

(2) consol.log

08:26:03.537 [main] WARN  org.neo4j.kernel.info.JvmChecker - You are using an unsupported Java runtime. Please use Oracle(R) Java(TM) Runtime Environment 7.
08:26:03.886 [main] INFO  org.neo4j.server.CommunityNeoServer - Setting startup timeout to: 120000ms based on -1
Detected incorrectly shut down database, performing recovery..
08:26:04.127 [main] WARN  o.neo4j.kernel.EmbeddedGraphDatabase - You are using an unsupported Java runtime. Please use Oracle(R) Java(TM) Runtime Environment 7.
2014-09-29 08:28:14.639+0000 ERROR [org.neo4j]: Exception when stopping org.neo4j.kernel.impl.nioneo.xa.NeoStoreXaDataSource@497f6a92 java.nio.channels.ClosedByInterruptException
java.lang.RuntimeException: java.nio.channels.ClosedByInterruptException
        at org.neo4j.kernel.impl.transaction.xaframework.LogBackedXaDataSource.stop(LogBackedXaDataSource.java:73)
        at org.neo4j.kernel.impl.nioneo.xa.NeoStoreXaDataSource.stop(NeoStoreXaDataSource.java:468)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
        at org.neo4j.kernel.impl.transaction.XaDataSourceManager.stop(XaDataSourceManager.java:185)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:123)
        at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:328)
        at org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:56)
        at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:90)
        at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:199)
        at org.neo4j.server.database.CommunityDatabase.createDb(CommunityDatabase.java:66)
        at org.neo4j.server.database.CommunityDatabase.start(CommunityDatabase.java:130)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:166)
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:103)
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:57)
Caused by: java.nio.channels.ClosedByInterruptException
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
        at sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:744)
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:724)
        at org.neo4j.kernel.impl.nioneo.store.StoreFileChannel.write(StoreFileChannel.java:51)
        at org.neo4j.kernel.impl.transaction.xaframework.DirectMappedLogBuffer.writeOut(DirectMappedLogBuffer.java:164)
        at org.neo4j.kernel.impl.transaction.xaframework.DirectMappedLogBuffer.force(DirectMappedLogBuffer.java:178)
        at org.neo4j.kernel.impl.transaction.xaframework.XaLogicalLog.releaseCurrentLogFile(XaLogicalLog.java:706)
        at org.neo4j.kernel.impl.transaction.xaframework.XaLogicalLog.close(XaLogicalLog.java:731)
        at org.neo4j.kernel.impl.transaction.xaframework.LogBackedXaDataSource.stop(LogBackedXaDataSource.java:69)
        ... 16 more
2014-09-29 08:28:14.643+0000 ERROR [org.neo4j]: Exception when stopping org.neo4j.kernel.impl.transaction.XaDataSourceManager@76c9c28b Component 'org.neo4j.kernel.impl.nioneo.xa.NeoStoreXaDataSource@497f6a92' failed to stop. Please see attached cause exception.
org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.nioneo.xa.NeoStoreXaDataSource@497f6a92' failed to stop. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:532)
        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
        at org.neo4j.kernel.impl.transaction.XaDataSourceManager.stop(XaDataSourceManager.java:185)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:123)
        at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:328)
        at org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:56)
        at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:90)
        at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:199)
        at org.neo4j.server.database.CommunityDatabase.createDb(CommunityDatabase.java:66)
        at org.neo4j.server.database.CommunityDatabase.start(CommunityDatabase.java:130)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:166)
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:103)
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:57)
Caused by: java.lang.RuntimeException: java.nio.channels.ClosedByInterruptException
        at org.neo4j.kernel.impl.transaction.xaframework.LogBackedXaDataSource.stop(LogBackedXaDataSource.java:73)
        at org.neo4j.kernel.impl.nioneo.xa.NeoStoreXaDataSource.stop(NeoStoreXaDataSource.java:468)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
        ... 14 more
Caused by: java.nio.channels.ClosedByInterruptException
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
        at sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:744)
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:724)
        at org.neo4j.kernel.impl.nioneo.store.StoreFileChannel.write(StoreFileChannel.java:51)
        at org.neo4j.kernel.impl.transaction.xaframework.DirectMappedLogBuffer.writeOut(DirectMappedLogBuffer.java:164)
        at org.neo4j.kernel.impl.transaction.xaframework.DirectMappedLogBuffer.force(DirectMappedLogBuffer.java:178)
        at org.neo4j.kernel.impl.transaction.xaframework.XaLogicalLog.releaseCurrentLogFile(XaLogicalLog.java:706)
        at org.neo4j.kernel.impl.transaction.xaframework.XaLogicalLog.close(XaLogicalLog.java:731)
        at org.neo4j.kernel.impl.transaction.xaframework.LogBackedXaDataSource.stop(LogBackedXaDataSource.java:69)
        ... 16 more
2014-09-29 08:28:14.661+0000 ERROR [org.neo4j]: Lifecycle exception Component 'org.neo4j.kernel.impl.transaction.XaDataSourceManager@76c9c28b' failed to stop. Please see attached cause exception.
org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.transaction.XaDataSourceManager@76c9c28b' failed to stop. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:532)
        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:123)
        at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:328)
        at org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:56)
        at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:90)
        at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:199)
        at org.neo4j.server.database.CommunityDatabase.createDb(CommunityDatabase.java:66)
        at org.neo4j.server.database.CommunityDatabase.start(CommunityDatabase.java:130)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:166)
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:103)
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:57)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.nioneo.xa.NeoStoreXaDataSource@497f6a92' failed to stop. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:532)
        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
        at org.neo4j.kernel.impl.transaction.XaDataSourceManager.stop(XaDataSourceManager.java:185)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
        ... 11 more
Caused by: java.lang.RuntimeException: java.nio.channels.ClosedByInterruptException
        at org.neo4j.kernel.impl.transaction.xaframework.LogBackedXaDataSource.stop(LogBackedXaDataSource.java:73)
        at org.neo4j.kernel.impl.nioneo.xa.NeoStoreXaDataSource.stop(NeoStoreXaDataSource.java:468)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
        ... 14 more
Caused by: java.nio.channels.ClosedByInterruptException
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
        at sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:744)
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:724)
        at org.neo4j.kernel.impl.nioneo.store.StoreFileChannel.write(StoreFileChannel.java:51)
        at org.neo4j.kernel.impl.transaction.xaframework.DirectMappedLogBuffer.writeOut(DirectMappedLogBuffer.java:164)
        at org.neo4j.kernel.impl.transaction.xaframework.DirectMappedLogBuffer.force(DirectMappedLogBuffer.java:178)
        at org.neo4j.kernel.impl.transaction.xaframework.XaLogicalLog.releaseCurrentLogFile(XaLogicalLog.java:706)
        at org.neo4j.kernel.impl.transaction.xaframework.XaLogicalLog.close(XaLogicalLog.java:731)
        at org.neo4j.kernel.impl.transaction.xaframework.LogBackedXaDataSource.stop(LogBackedXaDataSource.java:69)
        ... 16 more
2014-09-29 08:28:14.664+0000 ERROR [org.neo4j]: Chained lifecycle exception Component 'org.neo4j.kernel.extension.KernelExtensions@703601d7' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@703601d7' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:513)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115)
        at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:328)
        at org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:56)
        at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:90)
        at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:199)
        at org.neo4j.server.database.CommunityDatabase.createDb(CommunityDatabase.java:66)
        at org.neo4j.server.database.CommunityDatabase.start(CommunityDatabase.java:130)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:166)
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:103)
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:57)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.index.lucene.LuceneKernelExtension@267cae35' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:513)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115)
        at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:118)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507)
        ... 10 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.index.impl.lucene.LuceneDataSource@52b2093d' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:513)
        at org.neo4j.kernel.lifecycle.LifeSupport.bringToState(LifeSupport.java:415)
        at org.neo4j.kernel.lifecycle.LifeSupport.add(LifeSupport.java:326)
        at org.neo4j.kernel.impl.transaction.XaDataSourceManager.registerDataSource(XaDataSourceManager.java:236)
        at org.neo4j.index.lucene.LuceneKernelExtension.start(LuceneKernelExtension.java:79)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507)
        ... 13 more
Caused by: java.lang.RuntimeException: java.nio.channels.ClosedByInterruptException
        at org.neo4j.kernel.impl.index.IndexProviderStore.<init>(IndexProviderStore.java:85)
        at org.neo4j.index.impl.lucene.LuceneDataSource.newIndexStore(LuceneDataSource.java:302)
        at org.neo4j.index.impl.lucene.LuceneDataSource.start(LuceneDataSource.java:215)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507)
        ... 18 more
Caused by: java.nio.channels.ClosedByInterruptException
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
        at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:155)
        at org.neo4j.kernel.impl.nioneo.store.StoreFileChannel.read(StoreFileChannel.java:95)
        at org.neo4j.kernel.impl.index.IndexProviderStore.readRecordsWithNullDefaults(IndexProviderStore.java:130)
        at org.neo4j.kernel.impl.index.IndexProviderStore.<init>(IndexProviderStore.java:65)
        ... 21 more

**Comment by henry74** [comment]
I just started getting this exact same error running Neo4j 1.9.9 over the holiday weekend.  Any resolution on this?

**Comment by lutovich** [comment]
Hi guys,

PR https://github.com/neo4j/neo4j/pull/3450 is not related to this problem but has a long discussion underneath that helped to discover logging issue, which was fixed with https://github.com/neo4j/neo4j/pull/3634. Basically we tried to log startup error when logger was not yet initialized, so NPE masked a real problem.
In that particular case real startup exception was about insufficient permissions. Could you please check if permissions are ok in your installation?

Thanks!

**Comment by henry74** [comment]
I installed Neo4j service running as root user just to be sure it wasn't a permissions issue.  The neo4j directory is owned by root and I sudo chown -R root:root just in case on the entire directory.  I also added the max files 40000 to the security file under root and I do not get the 1024 warning message when starting the server.

Is there anything else I can check from a permission standpoint?

Not sure why this would start happening on a Neo4j instance which was running fine which is when it first occurred.  I recreated the issue on a fresh install on a fresh Ubuntu server after following the installation steps.

**Comment by Davidmylove** [comment]
To late  thank you

**Comment by Davidmylove** [comment]
Ya 2 late

**Comment by spacecowboy** [comment]
Closing since issue was fixed
