### ISSUE TITLE
ThisShouldNotHappenError node does not exist

### ISSUE THREAD

**Issue by ganeshshell** [neo4j/neo4j#3231]
I am getting a strange ThisShouldNotHappenError when I try to find a Node to update or insert,  after a purge job that deletes all the node and its relationship.

Step1: Cyper Query for purge:
match (n:Alpha) optional match (n)<-[r:AlphaBeta]-(m:Beta) delete n,r

Step 2:
Node alreadyExists = EmbeddedDBService.getInstance().findNode(Alpha.class, Alpha.PLAN_ID,
                                123456789);

org.neo4j.helpers.ThisShouldNotHappenError: Developer: Chris claims that: An index claims a node by id 1574225 has the value. However, it looks like that node does not exist.
at org.neo4j.kernel.impl.api.StateHandlingStatementOperations$3.accept(StateHandlingStatementOperations.java:571)
at org.neo4j.collection.primitive.PrimitiveLongCollections$5.accept(PrimitiveLongCollections.java:249)
at org.neo4j.collection.primitive.PrimitiveLongCollections$PrimitiveLongFilteringIterator.fetchNext(PrimitiveLongCollections.java:315)
at org.neo4j.collection.primitive.PrimitiveLongCollections$PrimitiveLongBaseIterator.hasNext(PrimitiveLongCollections.java:52)
at org.neo4j.collection.primitive.PrimitiveLongCollections$13.hasNext(PrimitiveLongCollections.java:706)
at org.neo4j.kernel.impl.api.store.CacheLayer.nodeGetProperty(CacheLayer.java:266)
at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.__AW_nodeGetProperty(StateHandlingStatementOperations.java:708)
at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.nodeGetProperty(StateHandlingStatementOperations.java)
at org.neo4j.kernel.impl.api.StateHandlingStatementOperations$3.accept(StateHandlingStatementOperations.java:567)

We are using Neo4j 2.1.3 community version. Is it a problem with cypher optional match delete that doesn't update the index properly? Appreciate any help on this. Thanks.

**Comment by yeago** [comment]
what kind of whacky error messaging is that
