### ISSUE TITLE
Backup instance fails to leave cluster in 2.1.5

### ISSUE THREAD

**Issue by bradnussbaum** [neo4j/neo4j#3267]
My backup instance reported a failure to leave the cluster. I saw this message in the backup logs.

2014-10-12 04:51:38.249+0000 WARN  [o.n.c.p.c.ClusterState]: Failed to leave. Cluster may consider this instance still a member

A cluster slave instance reported the following:

2014-10-12 04:51:08.253+0000 INFO  [o.n.c.p.c.ClusterConfiguration]: Instance -1 is leaving the cluster
2014-10-12 04:51:08.254+0000 WARN  [o.n.c.p.e.ClusterLeaveReelectionListener]: Demoting member -1 because it left the cluster
2014-10-12 04:51:08.254+0000 INFO  [o.n.k.h.HighAvailabilityConsoleLogger]: Instance -1  has left the cluster

And the master instance was tracing out errors:

2014-10-12 04:51:52.452+0000 WARN  [o.n.b.BackupServer]: Exception from Netty
java.nio.channels.ClosedChannelException: null
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:381) ~[netty-3.6.3.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:349) ~[netty-3.6.3.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:93) ~[netty-3.6.3.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107) ~[netty-3.6.3.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) ~[netty-3.6.3.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88) ~[netty-3.6.3.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.6.3.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_67]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]

Trying the backup, the backup tool reported the following:
Another backup client is currently performing backup; concurrent backups are not allowed

While the master instance showed the following message in the logs:
2014-10-12 05:29:02.103+0000 INFO  [o.n.c.p.c.ClusterState]: Denying entry to instance -1 because another instance is currently joining with the same id.

**Comment by martinfurmanski** [comment]
I don't know if this still is an issue, but it is unlikely to be fixed and it has been over 3 years, so I am closing it.
