### ISSUE TITLE
Neo4j 1.9.9 fails to start with relative path if directory does not exist

### ISSUE THREAD

**Issue by pangloss** [neo4j/neo4j#3423]
This issue appeared between 1.9.8 and 1.9.9 releases. The simplest repro is as follows, using pacer-neo4j on 1.9.9, where the local directory x does not exist.

```ruby
Pacer.neo4j 'x'
```
```
ArgumentError: Constructor invocation failed: org.neo4j.kernel.impl.cache.GCResistantCache.put(Lorg/neo4j/kernel/impl/cache/EntityWithSizeObject;)Lorg/neo4j/kernel/impl/cache/EntityWithSizeObject;
	from /Volumes/xn_dev/xn/pacer-neo4j/lib/pacer-neo4j.rb:57:in `neo4j'
	from org/jruby/RubyProc.java:271:in `call'
	from /Volumes/xn_dev/xn/pacer/lib/pacer/graph/pacer_graph.rb:47:in `reopen'
	from /Volumes/xn_dev/xn/pacer/lib/pacer/graph/pacer_graph.rb:24:in `initialize'
	from /Volumes/xn_dev/xn/pacer-neo4j/lib/pacer-neo4j.rb:69:in `neo4j'
	from (irb):2:in `evaluate'
	from org/jruby/RubyKernel.java:1101:in `eval'
	from org/jruby/RubyKernel.java:1501:in `loop'
	from org/jruby/RubyKernel.java:1264:in `catch'
	from org/jruby/RubyKernel.java:1264:in `catch'
	from /Users/dw/.rvm/rubies/jruby-1.7.14/bin/irb:13:in `(root)'
```

If I run `mkdir x` and retry, it works.

**Comment by jakewins** [comment]
The cache where this exception originates has been removed in Neo4j 2.2, meaning this should no longer be an issue.
