### ISSUE TITLE
Neo4j hangs up on simultaneous write & delete.

### ISSUE THREAD

**Issue by FylmTM** [neo4j/neo4j#3537]
We have database with ~7.000.000 nodes.
In this database we have 10.000 nodes, which we are going to delete. 

So, we run Cypher query, to delete them. 

```
MATCH (o:Object) 
WHERE LEFT(o.identifier, 6) = '_temp_'
DELETE m
```

This will run database "fullscan".

While cypher execution is in process, we start creating nodes, which we delete now. Nodes are created via Java API in extension. So, now we have:
- Running Cypher query, that deletes nodes
- Extension, that creates nodes same nodes, which we delete. 

And, after some time we notice that database became unresponsive (on 7474 port). Cluster doesn't notice anything, it continues think that database is OK.

---

If we look into java thread dump, then can find a lot of stacktraces, like this:

```
Thread 18569: (state = BLOCKED)
 - java.lang.Thread.sleep(long) @bci=0 (Compiled frame; information may be imprecise)
 - java.lang.Thread.sleep(long, int) @bci=57, line=340 (Compiled frame)
 - org.neo4j.kernel.impl.util.concurrent.LockWaitStrategies$3.apply(long) @bci=43, line=69 (Compiled frame)
 - org.neo4j.kernel.ha.lock.forseti.ForsetiClient.acquireExclusive(org.neo4j.kernel.impl.locking.Locks$ResourceType, long[]) @bci=180, line=189 (Compiled frame)
 - org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.validateNoExistingNodeWithLabelAndProperty(org.neo4j.kernel.impl.api.KernelStatement, int, org.neo4j.kernel.api
.properties.DefinedProperty, long) @bci=54, line=109 (Compiled frame)
 - org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.nodeSetProperty(org.neo4j.kernel.impl.api.KernelStatement, long, org.neo4j.kernel.api.properties.DefinedPropert
y) @bci=72, line=94 (Compiled frame)
 - org.neo4j.kernel.impl.api.LockingStatementOperations.nodeSetProperty(org.neo4j.kernel.impl.api.KernelStatement, long, org.neo4j.kernel.api.properties.DefinedProperty) @bci=4
8, line=280 (Compiled frame)
 - org.neo4j.kernel.impl.api.OperationsFacade.nodeSetProperty(long, org.neo4j.kernel.api.properties.DefinedProperty) @bci=17, line=551 (Compiled frame)
 - org.neo4j.kernel.impl.core.NodeProxy.setProperty(java.lang.String, java.lang.Object) @bci=46, line=254 (Compiled frame)
 - com.extension.rest.ImportResource.createNode(java.lang.String, java.lang.String) @bci=33, line=152 (Compiled frame)
 - com.extension.rest.ImportResource.processLine(java.lang.String) @bci=107, line=138 (Compiled frame)
 - com.extension.rest.ImportResource.synchronizedJob(boolean, int, java.lang.String) @bci=70, line=112 (Compiled frame)
...
```

---

Neo4j: 2.1.5 Enterprise
OS: CentOS 6.5

**Comment by xghrbc1001** [comment]
@jakewins  my neo4j's version is 2.2.5,I use the transaction like this

```
try(Transaction tx = db.beginTx())
{
    // Things
    tx.success();
}
```

,but ,I got jstack from neo4j as the below:

```
"qtp1880519262-298" #298 prio=5 os_prio=0 tid=0x00007fb0cc722000 nid=0x6367 sleeping[0x00007fafa7c78000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
    at java.lang.Thread.sleep(Native Method)
    at java.lang.Thread.sleep(Thread.java:340)
    at org.neo4j.kernel.impl.util.concurrent.LockWaitStrategies$3.apply(LockWaitStrategies.java:69)
    at org.neo4j.kernel.ha.lock.forseti.ForsetiClient.acquireExclusive(ForsetiClient.java:229)
    at org.neo4j.kernel.impl.api.LockingStatementOperations.nodeRemoveProperty(LockingStatementOperations.java:331)
    at org.neo4j.kernel.impl.api.GuardingStatementOperations.nodeRemoveProperty(GuardingStatementOperations.java:129)
    at org.neo4j.kernel.impl.api.OperationsFacade.nodeRemoveProperty(OperationsFacade.java:678)
    at org.neo4j.kernel.impl.core.NodeProxy.removeProperty(NodeProxy.java:320)
    at com.jindi.neo4j.plugin.knitter.service.KnitterService.setPro(KnitterService.java:239)
    at com.jindi.neo4j.plugin.knitter.service.KnitterService.getKniNode(KnitterService.java:261)
    at com.jindi.neo4j.plugin.knitter.service.KnitterService.setOwn(KnitterService.java:299)
    at com.jindi.neo4j.plugin.knitter.service.KnitterService.realWork(KnitterService.java:173)
    at com.jindi.neo4j.plugin.web.resource.KnitterResource.rstart(KnitterResource.java:75)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
    at org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139)
```

neo4j's transaction use Thread.sleep to got lock?

**Comment by chrisvest** [comment]
Answered on #5950
