### ISSUE TITLE
cannot instantiate the Lucene StandardAnalyzer through a index configuration

### ISSUE THREAD

**Issue by sbodese** [neo4j/neo4j#3708]
if i use this formal way: 

```
graphDbService.index().forNodes(FULL_TEXT_INDEX, 
                    MapUtil.stringMap( IndexManager.PROVIDER, "lucene",
                            "type", "fulltext",
                            "to_lower_case","false", 
                            "analyzer", StandardAnalyzer.class.getName())); 

java.lang.RuntimeException: java.lang.InstantiationException: org.apache.lucene.analysis.standard.StandardAnalyzer
    at org.neo4j.index.impl.lucene.IndexType.getByClassName(IndexType.java:272)
    at org.neo4j.index.impl.lucene.IndexType.getCustomAnalyzer(IndexType.java:258)
    at org.neo4j.index.impl.lucene.IndexType.getIndexType(IndexType.java:203)
    at org.neo4j.index.impl.lucene.IndexTypeCache.getIndexType(IndexTypeCache.java:54)
    at org.neo4j.index.impl.lucene.LuceneDataSource.getType(LuceneDataSource.java:313)
    at org.neo4j.index.impl.lucene.LuceneIndex.<init>(LuceneIndex.java:82)
    at org.neo4j.index.impl.lucene.LuceneIndex$NodeIndex.<init>(LuceneIndex.java:484)
    at org.neo4j.index.impl.lucene.LuceneDataSource.nodeIndex(LuceneDataSource.java:363)
    at org.neo4j.index.impl.lucene.LuceneIndexImplementation.nodeIndex(LuceneIndexImplementation.java:82)
    at org.neo4j.kernel.impl.coreapi.IndexManagerImpl.getOrCreateNodeIndex(IndexManagerImpl.java:318)
    at org.neo4j.kernel.impl.coreapi.IndexManagerImpl.forNodes(IndexManagerImpl.java:302)
    at de.pangaea.featurecatalogue.neo4j.PanNeo4jServiceImpl.prepareIndexes(PanNeo4jServiceImpl.java:94)
    at de.pangaea.featurecatalogue.neo4j.PanNeo4jServiceImpl.startDB(PanNeo4jServiceImpl.java:79)
    at de.pangaea.featurecatalogue.neo4j.PanNeo4jServiceImpl.<init>(PanNeo4jServiceImpl.java:64)
    at de.pangaea.featurecatalogue.neo4j.Neo4jV2Test.setUpBeforeClass(Neo4jV2Test.java:20)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.InstantiationException: org.apache.lucene.analysis.standard.StandardAnalyzer
    at java.lang.Class.newInstance(Class.java:359)
    at org.neo4j.index.impl.lucene.IndexType.getByClassName(IndexType.java:268)
    ... 30 more
```

The reason for this that most of all Lucene analyzer do not have a default ctor anymore (since Lucene 3.0)

**Comment by klaren** [comment]
Our current Lucene version is 5.5.0 where analyzers do have a default ctor. I'm closing this since it's not relevant anymore. Sorry for the late answer.
