### ISSUE TITLE
Unable to LOAD CSV file with blank cell (2.2.0-M02)

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4j/neo4j#3712]
Error and stack trace below.

[Import script](https://github.com/neo4jrb/lapd_incidents/blob/cc82f5f83e4f45ebc51e5d908f11d12c572bd9c5/load_csv.cql)

[first 10 lines CSV which replicate the issue](https://github.com/neo4jrb/lapd_incidents/blob/cc82f5f83e4f45ebc51e5d908f11d12c572bd9c5/db/test.csv)

It gets through the indexes/constraints and then fails as soon as it tries to import CSV.  This PR seems to be related:

https://github.com/neo4j/neo4j/pull/3612

```
	String didn't extract value for Mark[line:4, from:524, to:524]. For values which are optional please use tryExtract method instead
java.lang.IllegalStateException: String didn't extract value for Mark[line:4, from:524, to:524]. For values which are optional please use tryExtract method instead
	at org.neo4j.csv.reader.BufferedCharSeeker.extract(BufferedCharSeeker.java:197)
	at org.neo4j.cypher.internal.compiler.v2_2.spi.CSVResources$$anon$1$$anonfun$readNextRow$1.apply$mcV$sp(CSVResources.scala:58)
	at scala.util.control.Breaks.breakable(Breaks.scala:37)
	at org.neo4j.cypher.internal.compiler.v2_2.spi.CSVResources$$anon$1.readNextRow(CSVResources.scala:56)
	at org.neo4j.cypher.internal.compiler.v2_2.spi.CSVResources$$anon$1.next(CSVResources.scala:76)
	at org.neo4j.cypher.internal.compiler.v2_2.spi.CSVResources$$anon$1.next(CSVResources.scala:53)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.LoadCsvIterator.next(LoadCsvIterator.scala:30)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.LoadCsvIterator.next(LoadCsvIterator.scala:24)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$13.next(Iterator.scala:372)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.EmptyResultPipe.internalCreateResults(EmptyResultPipe.scala:29)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.createResults(DefaultExecutionResultBuilderFactory.scala:92)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:64)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:121)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:106)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.ExecutionPlanBuilder$$anon$1.execute(ExecutionPlanBuilder.scala:70)
	at org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper$$anonfun$execute$1.apply(CompatibilityFor2_2.scala:141)
	at org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper$$anonfun$execute$1.apply(CompatibilityFor2_2.scala:141)
	at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_2$.runSafely(CompatibilityFor2_2.scala:97)
	at org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper.execute(CompatibilityFor2_2.scala:140)
	at org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper.execute(CompatibilityFor2_2.scala:127)
	at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:84)
	at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:79)
	at org.neo4j.cypher.javacompat.ExecutionEngine.execute(ExecutionEngine.java:87)
	at org.neo4j.cypher.javacompat.internal.ServerExecutionEngine.executeQuery(ServerExecutionEngine.java:59)
	at org.neo4j.shell.kernel.apps.cypher.Start.getResult(Start.java:85)
	at org.neo4j.shell.kernel.apps.cypher.Using.getResult(Using.java:53)
	at org.neo4j.shell.kernel.apps.cypher.Start.exec(Start.java:67)
	at org.neo4j.shell.kernel.apps.TransactionProvidingApp.execute(TransactionProvidingApp.java:223)
	at org.neo4j.shell.impl.AbstractAppServer.interpretLine(AbstractAppServer.java:117)
	at org.neo4j.shell.kernel.GraphDatabaseShellServer.interpretLine(GraphDatabaseShellServer.java:93)
	at org.neo4j.shell.impl.RemotelyAvailableServer.interpretLine(RemotelyAvailableServer.java:60)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
	at sun.rmi.transport.Transport$1.run(Transport.java:178)
	at sun.rmi.transport.Transport$1.run(Transport.java:175)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:174)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:557)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:812)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:671)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
[load_csv.cql | uploaded via ZenHub](https://files.zenhub.io/549451305db8bc2b388578c6)

**Comment by spacecowboy** [comment]
Fixed. Verified on 2.3.2 (2.3.1-218-gdf557c2 to be exact)
