### ISSUE TITLE
Neo4j 2.2.0 M2 Cypher query fails with java.lang.ClassCastException

### ISSUE THREAD

**Issue by bunkat** [neo4j/neo4j#3828]
The following query works in Neo4j 2.1.5 but fails with Neo4j 2.2.0.

**Query**

  MATCH
    (u:user { id: { p01 } }), (p:project { id: { p02 } })
  WITH u, p

  MATCH
    (u)-[:CONTACT]->(c:contact)
  WITH c, p

  OPTIONAL MATCH
    (c)-[:CONTACT*1..3]->(r:projectrole)-[:CONTACT*0..2]->(:projectcontacts)-->(p)
  WITH p, COLLECT({accessedby: c.id, accessedrole: r.name}) AS rs
  WITH p, (
    CASE 
    WHEN ANY(r IN rs WHERE r.accessedrole = "ProjectAdmins")
      THEN HEAD(FILTER(r IN rs WHERE r.accessedrole = "ProjectAdmins"))
    WHEN ANY(r IN rs WHERE r.accessedrole = "ProjectClients")
      THEN HEAD(FILTER(r IN rs WHERE r.accessedrole = "ProjectClients"))
    WHEN ANY(r IN rs WHERE r.accessedrole = "ProjectContacts")
      THEN HEAD(FILTER(r IN rs WHERE r.accessedrole = "ProjectContacts"))
    ELSE HEAD(rs)
    END
    ) AS r

   
  OPTIONAL MATCH (p)-[:CREATED]->(a:activity)
  WITH p, {
    accessedrole: r.accessedrole, accessedby: r.accessedby,
    createdat: a.createdat, createdby: {id: a.contactid, object: "contact"}
    } AS r

  OPTIONAL MATCH (p)-[:HISTORY]->(a:activity)
  WITH p, {
    accessedrole: r.accessedrole, accessedby: r.accessedby,
    createdat: r.createdat, createdby: r.createdby,
    updatedat: a.createdat, updatedby: {id: a.contactid, object: "contact"}
    } AS r

  WITH DISTINCT p, r

  OPTIONAL MATCH (c:contact)-[:CONTACT]->(:projectadmins)-[:CONTACT*1..3]->p
  WITH p, COLLECT(c) AS cs, r
  WITH p, {
    accessedrole: r.accessedrole, accessedby: r.accessedby,
    createdat: r.createdat, createdby: r.createdby,
    updatedat: r.updatedat, updatedby: r.updatedby,
    admins: [c in cs | {id: c.id, object: c.object}]
    } AS r

  OPTIONAL MATCH (c:contact)-[:CONTACT]->(:projectclients)-[:CONTACT*1..3]->p
  WITH p, COLLECT(c) AS cs, r
  WITH p, {
    accessedrole: r.accessedrole, accessedby: r.accessedby,
    createdat: r.createdat, createdby: r.createdby,
    updatedat: r.updatedat, updatedby: r.updatedby,
    admins: r.admins,
    clients: [c in cs | {id: c.id, object: c.object}]
    } AS r

  OPTIONAL MATCH (c:contact)-[:CONTACT]->(:projectcontacts)-[:CONTACT*1..3]->p
  WITH p, COLLECT(c) AS cs, r
  WITH p, {
    accessedrole: r.accessedrole, accessedby: r.accessedby,
    createdat: r.createdat, createdby: r.createdby,
    updatedat: r.updatedat, updatedby: r.updatedby,
    admins: r.admins, clients: r.clients,
    contacts: [c in cs | {id: c.id, object: c.object}]
    } AS r

  OPTIONAL MATCH (p)-[:AREA]->(:areas)-[:AREA]->(x:area)
  WITH p, COLLECT(x) AS xs, r
  WITH p, {
    accessedrole: r.accessedrole, accessedby: r.accessedby,
    createdat: r.createdat, createdby: r.createdby,
    updatedat: r.updatedat, updatedby: r.updatedby,
    admins: r.admins, clients: r.clients, contacts: r.contacts,
    areas: [a IN xs | {id: a.id, object: a.object, name: a.name,
      description: a.description, abbr: a.abbr }]
    } AS r

  OPTIONAL MATCH p-[:PROJECTPHASE|TAG]->(x)
  WITH p, COLLECT(x) AS xs, r
  WITH p, {
    accessedrole: r.accessedrole, accessedby: r.accessedby,
    createdat: r.createdat, createdby: r.createdby,
    updatedat: r.updatedat, updatedby: r.updatedby,
    admins: r.admins, clients: r.clients, contacts: r.contacts,
    areas: r.areas,
    projectphase: HEAD([x in xs WHERE x.object = "projectphase" | {id: x.id,
      object: x.object, teamid: x.teamid, name: x.name,
      description: x.description, color: x.color }]),
    tags: [x in xs WHERE x.object = "tag" | {id: x.id, object: x.object, name: x.name}]
    } AS r

  RETURN COLLECT({
    id: p.id, object: p.object, status: p.status,
    teamid: p.teamid, no: p.no, name: p.name, description: p.description,
    street: p.street, locality: p.locality, region: p.region,
    postcode: p.postcode, country: p.country, neighborhood: p.neighborhood,
    latlnglocation: p.latlnglocation,
    imageurl: p.imageurl, workhours: p.workhours, startat: p.startat,
    endat: p.endat, budget: p.budget, isfixedcost: p.isfixedcost,
    deposit: p.deposit, depositreceivedat: p.depositreceivedat,
    depositnote: p.depositnote, timezone: p.timezone,
    materialmarkup: p.materialmarkup, isbid: p.isbid, salestax: p.salestax,
    notes: p.notes, terms: p.terms,
    accessedrole: r.accessedrole, accessedby: r.accessedby,
    createdat: r.createdat, createdby: r.createdby,
    updatedat: r.updatedat, updatedby: r.updatedby,
    admins: r.admins, clients: r.clients, contacts: r.contacts,
    areas: r.areas, projectphase: r.projectphase, tags: r.tags
    }) AS r

**Results from running query with neo4j-shell -v**

ERROR (-v for expanded information):
	java.lang.ClassCastException@773d30eb
java.lang.IllegalArgumentException: java.lang.ClassCastException@773d30eb
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.neo4j.cypher.internal.compiler.v2_2.ast.ASTNode$class.dup(ASTNode.scala:51)
	at org.neo4j.cypher.internal.compiler.v2_2.ast.AliasedReturnItem.dup(ReturnItem.scala:68)
	at org.neo4j.cypher.internal.compiler.v2_2.ast.AliasedReturnItem.dup(ReturnItem.scala:68)
	at org.neo4j.cypher.internal.compiler.v2_2.Rewritable$DuplicatableAny$.dup$extension(Rewritable.scala:48)
	at org.neo4j.cypher.internal.compiler.v2_2.bottomUp$BottomUpRewriter.apply(Rewritable.scala:166)
	at org.neo4j.cypher.internal.compiler.v2_2.bottomUp$BottomUpRewriter.apply(Rewritable.scala:162)
	at org.neo4j.cypher.internal.compiler.v2_2.bottomUp$BottomUpRewriter.apply(Rewritable.scala:162)
	at org.neo4j.cypher.internal.compiler.v2_2.bottomUp$BottomUpRewriter.apply(Rewritable.scala:162)
	at org.neo4j.cypher.internal.compiler.v2_2.TypedRewriter.apply(Rewritable.scala:95)
	at org.neo4j.cypher.internal.compiler.v2_2.ast.rewriters.inlineProjections$$anonfun$1$$anonfun$2.applyOrElse(inlineProjections.scala:63)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:162)
	at org.neo4j.cypher.internal.compiler.v2_2.Rewritable$RewritableAny$.rewrite$extension(Rewritable.scala:89)
	at org.neo4j.cypher.internal.compiler.v2_2.topDown$TopDownRewriter.apply(Rewritable.scala:130)
	at org.neo4j.cypher.internal.compiler.v2_2.topDown$TopDownRewriter.apply(Rewritable.scala:138)
	at org.neo4j.cypher.internal.compiler.v2_2.topDown$TopDownRewriter.apply(Rewritable.scala:138)
	at org.neo4j.cypher.internal.compiler.v2_2.topDown$TopDownRewriter.apply(Rewritable.scala:138)
	at org.neo4j.cypher.internal.compiler.v2_2.topDown$TopDownRewriter.apply(Rewritable.scala:138)
	at org.neo4j.cypher.internal.compiler.v2_2.topDown$TopDownRewriter.apply(Rewritable.scala:138)
	at org.neo4j.cypher.internal.compiler.v2_2.topDown$TopDownRewriter.apply(Rewritable.scala:138)
	at org.neo4j.cypher.internal.compiler.v2_2.topDown$TopDownRewriter.apply(Rewritable.scala:138)
	at org.neo4j.cypher.internal.compiler.v2_2.topDown$TopDownRewriter.apply(Rewritable.scala:138)
	at org.neo4j.cypher.internal.compiler.v2_2.topDown$TopDownRewriter.apply(Rewritable.scala:138)
	at org.neo4j.cypher.internal.compiler.v2_2.topDown$TopDownRewriter.apply(Rewritable.scala:138)
	at org.neo4j.cypher.internal.compiler.v2_2.topDown$TopDownRewriter.apply(Rewritable.scala:138)
	at org.neo4j.cypher.internal.compiler.v2_2.topDown$TopDownRewriter.apply(Rewritable.scala:138)
	at org.neo4j.cypher.internal.compiler.v2_2.topDown$TopDownRewriter.apply(Rewritable.scala:138)
	at org.neo4j.cypher.internal.compiler.v2_2.topDown$TopDownRewriter.apply(Rewritable.scala:138)
	at org.neo4j.cypher.internal.compiler.v2_2.Rewritable$RewritableAny$.rewrite$extension(Rewritable.scala:89)
	at org.neo4j.cypher.internal.compiler.v2_2.Rewritable$RewritableAny$.endoRewrite$extension(Rewritable.scala:90)
	at org.neo4j.cypher.internal.compiler.v2_2.ast.rewriters.inlineProjections$$anonfun$1.applyOrElse(inlineProjections.scala:66)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:162)
	at org.neo4j.cypher.internal.compiler.v2_2.ast.rewriters.inlineProjections$.apply(inlineProjections.scala:29)
	at org.neo4j.cypher.internal.compiler.v2_2.Rewritable$RewritableAny$.rewrite$extension(Rewritable.scala:89)
	at org.neo4j.cypher.internal.compiler.v2_2.inSequence$InSequenceRewriter.apply(Rewritable.scala:114)
	at org.neo4j.cypher.internal.compiler.v2_2.Rewritable$RewritableAny$.rewrite$extension(Rewritable.scala:89)
	at org.neo4j.cypher.internal.compiler.v2_2.Rewritable$RewritableAny$.endoRewrite$extension(Rewritable.scala:90)
	at org.neo4j.cypher.internal.compiler.v2_2.planner.Planner$.rewriteStatement(Planner.scala:105)
	at org.neo4j.cypher.internal.compiler.v2_2.planner.Planner$.rewriteStatement(Planner.scala:85)
	at org.neo4j.cypher.internal.compiler.v2_2.planner.Planner.producePlan(Planner.scala:53)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.LegacyVsNewPipeBuilder.producePlan(LegacyVsNewPipeBuilder.scala:33)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.ExecutionPlanBuilder.build(ExecutionPlanBuilder.scala:59)
	at org.neo4j.cypher.internal.compiler.v2_2.CypherCompiler$$anonfun$3$$anonfun$apply$1.apply(CypherCompiler.scala:137)
	at org.neo4j.cypher.internal.compiler.v2_2.CypherCompiler$$anonfun$3$$anonfun$apply$1.apply(CypherCompiler.scala:135)
	at org.neo4j.cypher.internal.compiler.v2_2.MonitoringCacheAccessor$$anonfun$1.apply(CacheAccessor.scala:35)
	at org.neo4j.cypher.internal.LRUCache.getOrElseUpdate(LRUCache.scala:34)
	at org.neo4j.cypher.internal.LRUCache.apply(LRUCache.scala:62)
	at org.neo4j.cypher.internal.compiler.v2_2.MonitoringCacheAccessor.getOrElseUpdate(CacheAccessor.scala:33)
	at org.neo4j.cypher.internal.compiler.v2_2.CypherCompiler$$anonfun$3.apply(CypherCompiler.scala:135)
	at org.neo4j.cypher.internal.compiler.v2_2.CypherCompiler$$anonfun$3.apply(CypherCompiler.scala:135)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$13.next(Iterator.scala:372)
	at org.neo4j.cypher.internal.compiler.v2_2.CypherCompiler.planPreparedQuery(CypherCompiler.scala:146)
	at org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$$anon$2$$anonfun$plan$1.apply(CompatibilityFor2_2.scala:122)
	at org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$$anon$2$$anonfun$plan$1.apply(CompatibilityFor2_2.scala:120)
	at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_2$.runSafely(CompatibilityFor2_2.scala:97)
	at org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$$anon$2.plan(CompatibilityFor2_2.scala:120)
	at org.neo4j.cypher.ExecutionEngine$$anonfun$liftedTree1$1$1$$anonfun$apply$1.apply(ExecutionEngine.scala:113)
	at org.neo4j.cypher.ExecutionEngine$$anonfun$liftedTree1$1$1$$anonfun$apply$1.apply(ExecutionEngine.scala:110)
	at org.neo4j.cypher.internal.compiler.v2_2.MonitoringCacheAccessor$$anonfun$1.apply(CacheAccessor.scala:35)
	at org.neo4j.cypher.internal.LRUCache.getOrElseUpdate(LRUCache.scala:34)
	at org.neo4j.cypher.internal.LRUCache.apply(LRUCache.scala:62)
	at org.neo4j.cypher.internal.compiler.v2_2.MonitoringCacheAccessor.getOrElseUpdate(CacheAccessor.scala:33)
	at org.neo4j.cypher.ExecutionEngine$$anonfun$liftedTree1$1$1.apply(ExecutionEngine.scala:110)
	at org.neo4j.cypher.ExecutionEngine$$anonfun$liftedTree1$1$1.apply(ExecutionEngine.scala:110)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$13.next(Iterator.scala:372)
	at org.neo4j.cypher.ExecutionEngine.liftedTree1$1(ExecutionEngine.scala:122)
	at org.neo4j.cypher.ExecutionEngine.planQuery(ExecutionEngine.scala:102)
	at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:83)
	at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:79)
	at org.neo4j.cypher.javacompat.ExecutionEngine.execute(ExecutionEngine.java:87)
	at org.neo4j.cypher.javacompat.internal.ServerExecutionEngine.executeQuery(ServerExecutionEngine.java:59)
	at org.neo4j.shell.kernel.apps.cypher.Start.getResult(Start.java:85)
	at org.neo4j.shell.kernel.apps.cypher.Start.exec(Start.java:67)
	at org.neo4j.shell.kernel.apps.TransactionProvidingApp.execute(TransactionProvidingApp.java:223)
	at org.neo4j.shell.impl.AbstractAppServer.interpretLine(AbstractAppServer.java:117)
	at org.neo4j.shell.kernel.GraphDatabaseShellServer.interpretLine(GraphDatabaseShellServer.java:93)
	at org.neo4j.shell.impl.RemotelyAvailableServer.interpretLine(RemotelyAvailableServer.java:60)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322)
	at sun.rmi.transport.Transport$1.run(Transport.java:177)
	at sun.rmi.transport.Transport$1.run(Transport.java:174)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:173)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:556)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:811)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:670)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

**Comment by systay** [comment]
Thanks @bunkat. Looking at it now.

**Comment by bunkat** [comment]
Confirmed that this has been fixed in 2.2.0.
