### ISSUE TITLE
Improve execute() Cypher error when node property in a param of CREATE is null

### ISSUE THREAD

**Issue by ceefour** [neo4j/neo4j#3870]
This:

``` groovy
# literalProps.t is null
final literalProps = [t: literal.literalDatatypeURI, v: literalValue]
final merge = """
MERGE (subj:Resource {href: {subjectHref}})
CREATE (subj) -[:$relName {relProps}]-> (lit:Literal {literalProps})
"""
final params = [subjectHref: subjectHref,
    relProps   : relProps, literalProps: literalProps] as Map<String, Object>
exec.execute(merge, params)
```

throws:

```
java.lang.RuntimeException: Cannot execute: «
MERGE (subj:Resource {href: {subjectHref}})
CREATE (subj) -[:yago_isPreferredMeaningOf {relProps}]-> (lit:Literal {literalProps})
» params: [subjectHref:yago:Dr._Kuno_Struck_House, relProps:[f:yago:id_893bmq_nyg_18f46ch], literalProps:[t:null, v:Dr. Kuno Struck House, l:eng]]
    at id.ac.itb.lumen.persistence.LumenPersistenceImportApp$_importFile_closure1$_closure2.doCall(LumenPersistenceImportApp.groovy:159)
    at id.ac.itb.lumen.persistence.LumenPersistenceImportApp$_importFile_closure1$_closure2.call(LumenPersistenceImportApp.groovy)
    at org.codehaus.groovy.runtime.IOGroovyMethods.withCloseable(IOGroovyMethods.java:1618)
    at id.ac.itb.lumen.persistence.LumenPersistenceImportApp$_importFile_closure1.doCall(LumenPersistenceImportApp.groovy:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1017)
    at groovy.lang.Closure.call(Closure.java:423)
    at groovy.lang.Closure.call(Closure.java:439)
    at org.codehaus.groovy.runtime.IOGroovyMethods.withReader(IOGroovyMethods.java:1179)
    at id.ac.itb.lumen.persistence.LumenPersistenceImportApp.importFile(LumenPersistenceImportApp.groovy:67)
    at id.ac.itb.lumen.persistence.LumenPersistenceImportApp.run(LumenPersistenceImportApp.groovy:234)
    at org.springframework.boot.SpringApplication.runCommandLineRunners(SpringApplication.java:677)
    ... 9 common frames omitted
Caused by: scala.MatchError: (t,null) (of class scala.Tuple2)
    at org.neo4j.cypher.internal.compiler.v2_1.mutation.CreateNode$$anonfun$org$$$$cc5e771a9d2ffdf71ac346e6f5f9cb3$$$$e$$fromAnyToLiteral$1$1.apply(CreateNode.scala:41)
    at org.neo4j.cypher.internal.compiler.v2_1.mutation.CreateNode$$anonfun$org$$$$cc5e771a9d2ffdf71ac346e6f5f9cb3$$$$e$$fromAnyToLiteral$1$1.apply(CreateNode.scala:41)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at org.neo4j.cypher.internal.compiler.v2_1.mutation.CreateNode.org$neo4j$cypher$internal$compiler$v2_1$mutation$CreateNode$$fromAnyToLiteral$1(CreateNode.scala:41)
    at org.neo4j.cypher.internal.compiler.v2_1.mutation.CreateNode$$anonfun$exec$1.apply(CreateNode.scala:78)
    at org.neo4j.cypher.internal.compiler.v2_1.mutation.CreateNode$$anonfun$exec$1.apply(CreateNode.scala:74)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at org.neo4j.cypher.internal.helpers.CollectionSupport$$anon$1.next(CollectionSupport.scala:52)
    at scala.collection.Iterator$$anon$13.next(Iterator.scala:372)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at org.neo4j.cypher.internal.compiler.v2_1.pipes.EmptyResultPipe.internalCreateResults(EmptyResultPipe.scala:29)
    at org.neo4j.cypher.internal.compiler.v2_1.pipes.PipeWithSource.createResults(Pipe.scala:105)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1$$anonfun$apply$2.apply(ExecutionPlanBuilder.scala:120)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1$$anonfun$apply$2.apply(ExecutionPlanBuilder.scala:119)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.ExecutionWorkflowBuilder.runWithQueryState(ExecutionPlanBuilder.scala:168)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:118)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:103)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.ExecutionPlanBuilder$$anon$1.execute(ExecutionPlanBuilder.scala:68)
    at org.neo4j.cypher.internal.compiler.v2_1.executionplan.ExecutionPlanBuilder$$anon$1.execute(ExecutionPlanBuilder.scala:67)
    at org.neo4j.cypher.internal.ExecutionPlanWrapperForV2_1.execute(CypherCompiler.scala:159)
    at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:76)
    at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:71)
    at org.neo4j.cypher.javacompat.ExecutionEngine.execute(ExecutionEngine.java:84)
    at id.ac.itb.lumen.persistence.LumenPersistenceImportApp$_importFile_closure1$_closure2.doCall(LumenPersistenceImportApp.groovy:156)
    ... 26 common frames omitted
```

It should be handled by mentioning something like: `Invalid value 'null' for parameter 'literalProps.t'. Cannot execute Cypher query: <query> params: <params>`

**Comment by aseemk** [comment]
I'd like to +1 for at least a better error message.

From the REST API, the returned error today is a bit cryptic:

```json
{
    "code": "Neo.DatabaseError.Statement.ExecutionFailure", 
    "message": "(foo,null) (of class scala.Tuple2)", 
    "stackTrace": "scala.MatchError: (foo,null) (of class scala.Tuple2)\n\tat ..."
}
```

But interestingly, I've noticed that `null` values are actually allowed now in a number of other cases:

```cypher
// works:
CREATE (n {foo: null})

// works:
SET n.foo = null

// works, incl. when {props} contains a null property:
SET n.foo = {props}

// it's only this that doesn't:
CREATE (n {props})
```

So I'm guessing the current error is more of an oversight now than by-design?

Thanks!

**Comment by aseemk** [comment]
Repro using [HTTPie](http://httpie.org/):

```
http POST localhost:7474/db/data/transaction/commit \
statements:='[{"statement":"CREATE (n {props})", "parameters": {"props": {"foo": null}}}]'
```

**Comment by smcclstocks** [comment]
+1

**Comment by aseemk** [comment]
My colleague @linuxfreakus just found a great workaround:

``` cypher
// reminder - this doesn't work if there's a `null` property:
CREATE (n {props})

// but apparently this does!
CREATE (n)
SET n = {props}

// (as does this)
CREATE (n)
SET n += {props}
```

We're using Neo4j 2.2.8 btw. Not sure if all this is the same in Neo4j 2.3.

**Comment by gpierrick** [comment]
That's great! @aseemk is the node driver going to still strip the null value?

**Comment by aseemk** [comment]
@gpierrick: The node driver doesn't touch the params at all. What are you seeing?

**Comment by aseemk** [comment]
(We can move node driver discussion to the driver repo btw; feel free to create an issue, or Slack.)
