### ISSUE TITLE
Build failure in Cypher Documentation module

### ISSUE THREAD

**Issue by antonio-castellon** [neo4j/neo4j#3883]
Dear Developers,

I'm trying to compile from the last changes in the master repository and now it throws an exception just when it try to compile the *Cypher Documentation*. 

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:java (parse-graphgist) on project neo4j-cypher-docs: An exception occured while executing the Java class. null: InvocationTarge
tException: Failed while executing file: import-csv-with-cypher.asciidoc in the directory C:\DEV\github\fork\neo4j\community\cypher\docs\cypher-docs\target\docs\parsed-graphgists: java.sql.SQLExceptio
n: No suitable driver found for jdbc:hsqldb:mem:graphgist;shutdown=true -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:java (parse-graphgist) on project neo4j-cypher-docs: An exception occured while
 executing the Java class. null
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An exception occured while executing the Java class. null
        at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:345)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Failed while executing file: import-csv-with-cypher.asciidoc in the directory C:\DEV\github\fork\neo4j\community\cypher\docs\cypher-docs\target\docs\parsed-graph
gists
        at org.neo4j.doc.cypherdoc.Main.executeDirectory(Main.java:100)
        at org.neo4j.doc.cypherdoc.Main.executeDirectory(Main.java:90)
        at org.neo4j.doc.cypherdoc.Main.main(Main.java:68)
        ... 6 more
Caused by: java.lang.RuntimeException: java.sql.SQLException: No suitable driver found for jdbc:hsqldb:mem:graphgist;shutdown=true
        at org.neo4j.doc.cypherdoc.CypherDoc.parse(CypherDoc.java:89)
        at org.neo4j.doc.cypherdoc.Main.executeFile(Main.java:129)
        at org.neo4j.doc.cypherdoc.Main.executeDirectory(Main.java:96)
        ... 8 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:hsqldb:mem:graphgist;shutdown=true
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at org.neo4j.doc.cypherdoc.CypherDoc.parse(CypherDoc.java:78)
        ... 10 more

```

I see that the driver version was not indicated into the `pom.xml` from the cypher documents, but if I put it by hand the error persist. :/

It was fine few days ago, but not now.... maybe will be fine if someone introduce something like `-Ddocuments.skip` in order to skip this build from Windows environments.

Thanks in advance,
Antonio

**Comment by nawroth** [comment]
Which version of Maven are you using?

**Comment by antonio-castellon** [comment]
Hi @nawroth , 
```
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)
Maven home: C:\SDK\JAVA\apache-maven-3.2.3
Java version: 1.7.0_71, vendor: Oracle Corporation
Java home: C:\SDK\JAVA\jdk1.7.0_71.x86\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"
```

**Comment by nawroth** [comment]
That Maven version should be fine. I've seen this problem, and did a workaround for it which works fine on our linux/windows/osx build servers. Somehow Maven doesn't get the plugin dependencies right in your case.

**Comment by jjaderberg** [comment]
Closing this as it is very old and the docs build has moved. @antonio-castellon feel free to reopen this issue or any future issues at https://github.com/neo4j/neo4j-documentation
