### ISSUE TITLE
Graph Database Kernel TEST failure

### ISSUE THREAD

**Issue by antonio-castellon** [neo4j/neo4j#3899]
Dear Neo4j Team,

When I execute the compilation with the test cases, it fails when arrive to the Graph Database Kernel .

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.596 sec <<< FAILURE! - in org.neo4j.qa.tooling.DumpProcessInformationTest
shouldDumpProcessInformation(org.neo4j.qa.tooling.DumpProcessInformationTest)  Time elapsed: 0.596 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.neo4j.qa.tooling.DumpProcessInformationTest.shouldDumpProcessInformation(DumpProcessInformationTest.java:66)

```
Any ideas about how to fix it?

Note: I'm on Windows environment, sorry ... it was not my choice.

**Comment by chrisvest** [comment]
The test is trying to verify some feature for creating thread-dumps of other java processes. It is looking for the string "traceableMethod" in a dump-file it puts in `community\kernel\target\test-data\org.neo4j.qa.tooling.DumpProcessInformationTest\dump`. Perhaps that directory is either missing or empty, or the files in it are formatted in unexpected ways?

**Comment by antonio-castellon** [comment]
Dear @chrisvest 

I checked and this folder not exist ... 

```
C:\DEV\github\fork\neo4j\community\kernel\target>cd test-data

C:\DEV\github\fork\neo4j\community\kernel\target\test-data>dir
 Volume in drive C has no label.
 Volume Serial Number is 029F-A083

 Directory of C:\DEV\github\fork\neo4j\community\kernel\target\test-data

29.01.2015  09:40    <DIR>          .
29.01.2015  09:40    <DIR>          ..
29.01.2015  09:38                40 index-provider-store
29.01.2015  09:37    <DIR>          org.neo4j.kernel.api.index.ProviderMetaTest
29.01.2015  09:37    <DIR>          org.neo4j.kernel.api.index.UniqueConstraintCompatibility
29.01.2015  09:38    <DIR>          org.neo4j.kernel.impl.core.TestDenseNodeRelChainPositionIT
29.01.2015  09:38    <DIR>          org.neo4j.kernel.impl.store.counts.CountsComputerTest
29.01.2015  09:38    <DIR>          org.neo4j.kernel.impl.store.counts.CountsRotationTest
29.01.2015  09:38    <DIR>          org.neo4j.kernel.impl.store.RelationshipGroupStoreTest
29.01.2015  09:38    <DIR>          org.neo4j.kernel.impl.store.TestArrayStore
29.01.2015  09:38    <DIR>          org.neo4j.kernel.impl.store.TestBrokenStoreRecovery
29.01.2015  09:39    <DIR>          org.neo4j.kernel.impl.store.TestGraphProperties
29.01.2015  09:39    <DIR>          org.neo4j.kernel.impl.store.TestNeoStore
29.01.2015  09:39    <DIR>          org.neo4j.kernel.impl.store.TestOsSpecificLocks
29.01.2015  09:39    <DIR>          org.neo4j.kernel.impl.storemigration.legacystore.v19.Legacy19NodeStoreReaderTest
29.01.2015  09:39    <DIR>          org.neo4j.kernel.impl.storemigration.legacystore.v19.Legacy19RelationshipStoreReaderTest
29.01.2015  09:39    <DIR>          org.neo4j.kernel.impl.storemigration.legacystore.v19.Legacy19Store
29.01.2015  09:39    <DIR>          org.neo4j.kernel.impl.storemigration.legacystore.v20.Legacy20NodeStoreReader
29.01.2015  09:39    <DIR>          org.neo4j.kernel.impl.storemigration.legacystore.v20.Legacy20Store
29.01.2015  09:39    <DIR>          org.neo4j.kernel.impl.storemigration.legacystore.v21.Legacy21Store
29.01.2015  09:39    <DIR>          org.neo4j.kernel.impl.storemigration.legacystore.v21.propertydeduplication.IndexLookupTest
29.01.2015  09:39    <DIR>          org.neo4j.kernel.impl.transaction.CommitContentionTests
29.01.2015  09:39    <DIR>          org.neo4j.kernel.impl.transaction.log.PhysicalLogFileTest
29.01.2015  09:39    <DIR>          org.neo4j.kernel.impl.transaction.log.PhysicalWritableLogChannelTest
29.01.2015  09:39    <DIR>          org.neo4j.kernel.impl.transaction.PhysicalLogicalTransactionStoreTest
29.01.2015  09:39    <DIR>          org.neo4j.kernel.impl.transaction.ReadAheadLogChannelTest
29.01.2015  09:39    <DIR>          org.neo4j.kernel.impl.transaction.state.NeoStoreIndexStoreViewTest
29.01.2015  09:40    <DIR>          org.neo4j.kernel.impl.util.StringLoggerTest
29.01.2015  09:40    <DIR>          org.neo4j.kernel.impl.util.TestFileUtils
29.01.2015  09:40    <DIR>          org.neo4j.kernel.RecoveryTest
29.01.2015  09:40    <DIR>          org.neo4j.kernel.StoreLockerLifecycleAdapterTest
29.01.2015  09:40    <DIR>          org.neo4j.kernel.StoreLockerTest
29.01.2015  09:40    <DIR>          org.neo4j.metatest.AsciiDocGeneratorTest
29.01.2015  09:40    <DIR>          org.neo4j.metatest.TargetDirectoryTest
29.01.2015  09:40    <DIR>          org.neo4j.metatest.TestJavaTestDocsGenerator
29.01.2015  09:40    <DIR>          org.neo4j.qa.tooling.DumpProcessInformationTest
29.01.2015  09:40    <DIR>          org.neo4j.unsafe.batchinsert.BatchInserterImplTest
29.01.2015  09:40    <DIR>          org.neo4j.unsafe.batchinsert.BatchInsertTest
29.01.2015  09:40    <DIR>          org.neo4j.unsafe.impl.batchimport.input.csv.CsvInputTest
29.01.2015  09:40    <DIR>          org.neo4j.unsafe.impl.batchimport.store.BatchingPageCacheTest

```

Any idea what I can do it ( I'm preparing now just a Virtual Machine with Ubuntu, to check if it happens exactly in the same way on Linux environment.

Thanks a lot
Antonio

**Comment by chrisvest** [comment]
Looks like you do have the folder for the test `29.01.2015  09:40    <DIR>          org.neo4j.qa.tooling.DumpProcessInformationTest` but I guess it's empty? You can try running the test in a debugger and check that the `DumpableProcess` starts up correctly, waits for its signal correctly, where the `DumpProcessInformation` class attempts to write a file, and so on. Could be that the file is created in a wrong location.

**Comment by antonio-castellon** [comment]
Ops! I can see... it's into the correct folder with the name : `08_40_13_012-threaddump-564-org.neo4j.qa.tooling.DumpableProcess` , but it's empty. ????

**Comment by chrisvest** [comment]
I just tried on a Windows 8.1 machine, and the test passed just fine. It's also passing on our Windows Server 2008 build agent. Do you have `jps` and `jstack` on your path, such that you can run them from a console? This is what the `DumpProcessInformation` class does under the hood, and then it just writes the output of the `jstack` program to that file. There might be something particular to your environment that prevents this from working.

**Comment by antonio-castellon** [comment]
Hi @chrisvest 

My computer is  a Windows 7 pro `64 bits`
It's strange, because I have access by command to this applications

```
C:\DEV\github\fork\neo4j\community\kernel\target\test-data>jps
3616 RemoteMavenServer
7136 Main
2024 Jps
7336 ClientEngine

C:\DEV\github\fork\neo4j\community\kernel\target\test-data>jstack
Usage:
    jstack [-l] <pid>
        (to connect to running process)
    jstack -F [-m] [-l] <pid>
        (to connect to a hung process)
    jstack [-m] [-l] <executable> <core>
        (to connect to a core file)
    jstack [-m] [-l] [server_id@]<remote server IP or hostname>
        (to connect to a remote debug server)

Options:
    -F  to force a thread dump. Use when jstack <pid> does not respond (process is hung)
    -m  to print both java and native frames (mixed mode)
    -l  long listing. Prints additional information about locks
    -h or -help to print this help message
```
Any idea?

Note: I'm just compiling into ubuntu (requires time, because it's a VM), I inform you when it finish about the results.

**Comment by chrisvest** [comment]
The only suggestion I have at this point, is to try stepping through the test in a debugger.

**Comment by antonio-castellon** [comment]
well... finally my new linux environment have not this problem. Therefore..I don't want to lose more time with this issue. Maybe is an issue from 64 bits.

**Comment by antonio-castellon** [comment]
Catched!!! 
with JDK 1.8 `64 bits` the use of this tools `jsp` and `jstack` are not exactly the we expected, always returns empty in the execution code,
but If I compile with the JDK 1.7 `32 bits`..everything is fine

maybe the error is from the different implementations from 32 to 64 bits..or maybe the JDK version 1.8 / 1.7

I can test it if I have more time.

Regards,
Antonio

**Comment by antonio-castellon** [comment]
Now, the TEST from Lucene Index fails ... it's a nightmare to try to compile everything with the Test Cases on Windows! ..therefore I want to close this issue because I don't want to lose more tiem with the environment issues ... I will execute the Test cases always on Linux environment. :(
BR,
