### ISSUE TITLE
Build failure (org.neo4j.cypher.internal.compiler.v2_2.ast.rewriters.InlineProjectionsTest)

### ISSUE THREAD

**Issue by antonio-castellon** [neo4j/neo4j#3911]
I'm trying to build the code (with tests) into a new Linux environment (Ubuntu 32 bits, OpenJDK 1.7) because at the moment I can't do it on Windows environment (Build failure in Cypher Documentation module #3883)  and I found this error:

```
match n where id(n) IN [0,1,2,3] with n.division AS `n.division`, max(n.age) AS `max(n.age)` with `n.division` AS `n.division`, `max(n.age)` AS `max(n.age)` RETURN `n.division` AS `n.division`, `max(n.age)` AS `max(n.age)` order by `max(n.age)`(org.neo4j.cypher.internal.compiler.v2_2.ast.rewriters.InlineProjectionsTest)  Time elapsed: 0.027 sec  <<< ERROR!
org.scalatest.exceptions.TestFailedException: Query(None,SingleQuery(List(Match(false,Pattern(List(EveryPath(NodePattern(Some(Identifier(n)),List(),None,true)))),List(),Some(Where(In(FunctionInvocation(FunctionName(id),false,Vector(Identifier(n))),Collection(List(SignedDecimalIntegerLiteral(0), SignedDecimalIntegerLiteral(1), SignedDecimalIntegerLiteral(2), SignedDecimalIntegerLiteral(3))))))), With(false,ReturnItems(false,Vector(AliasedReturnItem(Property(Identifier(n),PropertyKeyName(division)),Identifier(n.division)), AliasedReturnItem(FunctionInvocation(FunctionName(max),false,Vector(Property(Identifier(n),PropertyKeyName(age)))),Identifier(max(n.age))))),None,None,None,None), With(false,ReturnItems(false,Vector(AliasedReturnItem(Identifier(n.division),Identifier(n.division)), AliasedReturnItem(Identifier(max(n.age)),Identifier(max(n.age))))),None,None,None,None), With(false,ReturnItems(false,Vector(AliasedReturnItem(Identifier(n.division),Identifier(n.division)), AliasedReturnItem(Identifier(max(n.age)),Identifier(  FRESHID197)))),Some(OrderBy(List(AscSortItem(Identifier(  FRESHID197))))),None,None,None), Return(false,ReturnItems(false,List(AliasedReturnItem(Identifier(n.division),Identifier(n.division)), AliasedReturnItem(Identifier(  FRESHID197),Identifier(max(n.age))))),None,None,None)))) did not equal Query(None,SingleQuery(List(Match(false,Pattern(List(EveryPath(NodePattern(Some(Identifier(n)),List(),None,true)))),List(),Some(Where(In(FunctionInvocation(FunctionName(id),false,Vector(Identifier(n))),Collection(List(SignedDecimalIntegerLiteral(0), SignedDecimalIntegerLiteral(1), SignedDecimalIntegerLiteral(2), SignedDecimalIntegerLiteral(3))))))), With(false,ReturnItems(false,Vector(AliasedReturnItem(Property(Identifier(n),PropertyKeyName(division)),Identifier(n.division)), AliasedReturnItem(FunctionInvocation(FunctionName(max),false,Vector(Property(Identifier(n),PropertyKeyName(age)))),Identifier(max(n.age))))),None,None,None,None), With(false,ReturnItems(false,Vector(AliasedReturnItem(Identifier(n.division),Identifier(n.division)), AliasedReturnItem(Identifier(max(n.age)),Identifier(max(n.age))))),None,None,None,None), With(false,ReturnItems(false,Vector(AliasedReturnItem(Identifier(n.division),Identifier(n.division)), AliasedReturnItem(Identifier(max(n.age)),Identifier(  FRESHID194)))),Some(OrderBy(List(AscSortItem(Identifier(  FRESHID194))))),None,None,None), Return(false,ReturnItems(false,List(AliasedReturnItem(Identifier(n.division),Identifier(n.division)), AliasedReturnItem(Identifier(  FRESHID194),Identifier(max(n.age))))),None,None,None))))
        at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
        at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:5980)
        at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6026)
        at org.neo4j.cypher.internal.compiler.v2_2.ast.rewriters.InlineProjectionsTest$$anonfun$26.apply$mcV$sp(InlineProjectionsTest.scala:376)
        at org.neo4j.cypher.internal.compiler.v2_2.ast.rewriters.InlineProjectionsTest$$anonfun$26.apply(InlineProjectionsTest.scala:366)
        at org.neo4j.cypher.internal.compiler.v2_2.ast.rewriters.InlineProjectionsTest$$anonfun$26.apply(InlineProjectionsTest.scala:366)
        at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
        at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
        at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
        at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
        at org.scalatest.Transformer.apply(Transformer.scala:22)
        at org.scalatest.Transformer.apply(Transformer.scala:20)
        at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:158)
        at org.scalatest.Suite$class.withFixture(Suite.scala:1121)
        at org.neo4j.cypher.internal.commons.CypherFunSuite.withFixture(CypherFunSuite.scala:28)
        at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:155)
        at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
        at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
        at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
        at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:167)
        at org.neo4j.cypher.internal.commons.CypherFunSuite.org$scalatest$BeforeAndAfterEach$$super$runTest(CypherFunSuite.scala:28)
        at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:255)
        at org.neo4j.cypher.internal.commons.CypherFunSuite.runTest(CypherFunSuite.scala:28)
        at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:199)
        at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:199)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
        at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
        at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
        at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:199)
        at org.neo4j.cypher.internal.commons.CypherFunSuite.runTests(CypherFunSuite.scala:28)
        at org.scalatest.Suite$class.run(Suite.scala:1423)
        at org.neo4j.cypher.internal.commons.CypherFunSuite.org$scalatest$FunSuiteLike$$super$run(CypherFunSuite.scala:28)
        at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:203)
        at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:203)
        at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
        at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:203)
        at org.neo4j.cypher.internal.commons.CypherFunSuite.run(CypherFunSuite.scala:28)
        at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:99)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

```

```
[INFO] Neo4j - Cypher Compiler 2.2 ....................... FAILURE [3:50.376s]
[INFO] Neo4j - Cypher .................................... SKIPPED
```

After this error log also appears more test errors ... 

Any ideas? because I checked the same source folder compiling with other Windows Environment and I have no Test Case errors on `Cypher-Compiler-2.2`.

```
Results :

Tests run: 2236, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ neo4j-cypher-compiler-2.2 ---
```

**Comment by davidegrohmann** [comment]
Hi @antonio-castellon,

the test failure you are seen is related to this note: https://github.com/neo4j/neo4j/blob/master/community/cypher/cypher-compiler-2.2/src/test/scala/org/neo4j/cypher/internal/compiler/v2_2/ast/rewriters/InlineProjectionsTest.scala#L374

Can you please provide the output string of `System.getProperty("os.name").toLowerCase()` as in https://github.com/neo4j/neo4j/blob/master/community/kernel/src/main/java/org/neo4j/helpers/Platforms.java#L24 ?

I am afraid that your system is wrongly recognized as Windows and hence the test fails.

Thanks in advance.

**Comment by antonio-castellon** [comment]
Dear @davidegrohmann , I check it and it shows: "linux"
:(

**Comment by sherfert** [comment]
@antonio-castellon Sorry for replying so late. Is this still an issue we can help with? If yes, please reopen.
