### ISSUE TITLE
Neo4j server in embedded mode gets killed completely death by Interupted exception.

### ISSUE THREAD

**Issue by PavelNiedoba** [neo4j/neo4j#3977]
I have simple executor which access neo4j. The Callable has timeout set. When the timeout occurs the embedded server dies for good. 
```java
                Callable<Exception> callable = new Callable() {
                    @Override
                    public Object call() throws Exception {
                        try {
                            tool.execute(null);
                            return null;
                        } catch (Exception e) {
                            log.error(getName() + " callable in processor failed", e);
                            return e;
                        }
                    }
                };
                log.info(getName() + " Executing " + periodicalTask);
                periodicalTask.setStart(new Date());
                ExecutorService executor = Executors.newSingleThreadExecutor();
                List<Future<Exception>> futures = executor.invokeAll(Arrays.asList(callable), periodicalTask.getTimeout(), TimeUnit.SECONDS);
                executor.shutdown();
```
After timeout I need to restart tomcat. Nothing else helps. Exception chain is:
Is there any any defense to this? Thought every thread can be interrupted eventually, one transaction could fail, but why does whole db needs to die ?

```
java.lang.RuntimeException: failed in queryManyOrdered
	....................
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.neo4j.graphdb.TransactionFailureException: Unable to get transaction.
	at org.neo4j.kernel.InternalAbstractGraphDatabase.transactionRunning(InternalAbstractGraphDatabase.java:1064)
	at org.neo4j.kernel.InternalAbstractGraphDatabase.beginTx(InternalAbstractGraphDatabase.java:1037)
	at org.neo4j.kernel.TransactionBuilderImpl.begin(TransactionBuilderImpl.java:43)
	at org.neo4j.kernel.InternalAbstractGraphDatabase.beginTx(InternalAbstractGraphDatabase.java:1024)
	at cz.simplecoin.neo.Db.queryManyOrdered(Db.java:160)
	... 9 more
Caused by: javax.transaction.SystemException: Kernel has encountered some problem, please perform neccesary action (tx recovery/restart)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.neo4j.kernel.impl.transaction.KernelHealth.assertHealthy(KernelHealth.java:61)
	at org.neo4j.kernel.impl.transaction.TxManager.assertTmOk(TxManager.java:339)
	at org.neo4j.kernel.impl.transaction.TxManager.getTransaction(TxManager.java:725)
	at org.neo4j.kernel.InternalAbstractGraphDatabase.transactionRunning(InternalAbstractGraphDatabase.java:1060)
	... 13 more
Caused by: javax.transaction.xa.XAException
	at org.neo4j.kernel.impl.transaction.TransactionImpl.doCommit(TransactionImpl.java:560)
	at org.neo4j.kernel.impl.transaction.TxManager.commit(TxManager.java:448)
	at org.neo4j.kernel.impl.transaction.TxManager.commit(TxManager.java:385)
	at org.neo4j.kernel.TopLevelTransaction.close(TopLevelTransaction.java:126)
	...................
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	... 3 more
Caused by: org.neo4j.kernel.impl.nioneo.store.UnderlyingStorageException: Unable to write record[3] @[27]
	at org.neo4j.kernel.impl.nioneo.store.PersistenceRow.writeContents(PersistenceRow.java:198)
	at org.neo4j.kernel.impl.nioneo.store.PersistenceRow.force(PersistenceRow.java:214)
	at org.neo4j.kernel.impl.nioneo.store.LockableWindow.writeOutAndClose(LockableWindow.java:60)
	at org.neo4j.kernel.impl.nioneo.store.LockableWindow.writeOutAndCloseIfFree(LockableWindow.java:162)
	at org.neo4j.kernel.impl.nioneo.store.PersistenceWindowPool.release(PersistenceWindowPool.java:241)
	at org.neo4j.kernel.impl.nioneo.store.CommonAbstractStore.releaseWindow(CommonAbstractStore.java:546)
	at org.neo4j.kernel.impl.nioneo.store.NeoStore.setRecord(NeoStore.java:577)
	at org.neo4j.kernel.impl.nioneo.store.NeoStore.setLastCommittedTx(NeoStore.java:486)
	at org.neo4j.kernel.impl.nioneo.xa.NeoStoreTransaction.applyCommit(NeoStoreTransaction.java:739)
	at org.neo4j.kernel.impl.nioneo.xa.NeoStoreTransaction.doCommit(NeoStoreTransaction.java:624)
	at org.neo4j.kernel.impl.transaction.xaframework.XaTransaction.commit(XaTransaction.java:327)
	at org.neo4j.kernel.impl.transaction.xaframework.XaResourceManager.commitWriteTx(XaResourceManager.java:632)
	at org.neo4j.kernel.impl.transaction.xaframework.XaResourceManager.commit(XaResourceManager.java:533)
	at org.neo4j.kernel.impl.transaction.xaframework.XaResourceHelpImpl.commit(XaResourceHelpImpl.java:64)
	at org.neo4j.kernel.impl.transaction.TransactionImpl.doCommit(TransactionImpl.java:548)
	... 12 more
Caused by: java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:743)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:723)
	at org.neo4j.kernel.impl.nioneo.store.StoreFileChannel.write(StoreFileChannel.java:51)
	at org.neo4j.kernel.impl.nioneo.store.PersistenceRow.writeContents(PersistenceRow.java:186)
	... 26 more

```

**Comment by mneedham** [comment]
@PavelNiedoba can you post your whole code sample to make it easier for us to reproduce?

**Comment by PavelNiedoba** [comment]
```java
import org.junit.Test;
import org.neo4j.graphdb.DynamicLabel;
import org.neo4j.graphdb.GraphDatabaseService;
import org.neo4j.graphdb.Transaction;
import org.neo4j.graphdb.factory.GraphDatabaseFactory;
import org.neo4j.graphdb.factory.GraphDatabaseSettings;

/**
 * Created by pavel on 10.2.15.
 */
public class TestInterupt {


    GraphDatabaseService getDb() {
        return  new GraphDatabaseFactory()
                .newEmbeddedDatabaseBuilder("/tmp/testDb")
                .setConfig(GraphDatabaseSettings.nodestore_mapped_memory_size, "10M")
                .setConfig(GraphDatabaseSettings.string_block_size, "60")
                .setConfig(GraphDatabaseSettings.array_block_size, "300")
                .newGraphDatabase();
    }

    @Test
    public void testInterruptedDb() throws InterruptedException {

        final GraphDatabaseService graphDatabaseService = getDb();

        Thread t = new Thread(){
            @Override
            public void run() {
                try (Transaction tx= graphDatabaseService.beginTx()) {
                    for (int i=0; i<10000; i++) {
                        graphDatabaseService.createNode(DynamicLabel.label("whatever"));
                    }
                 }
                catch (Exception e){
                    System.out.println("This is okay");
                }
            }
        };
        t.start();
        t.interrupt();

        try (Transaction tx= graphDatabaseService.beginTx()) {
            graphDatabaseService.createNode(DynamicLabel.label("whateverNow"));
        }catch (Exception e){
            System.out.println("This is not okay");
            e.printStackTrace();
        }

        try (Transaction tx= graphDatabaseService.beginTx()) {
            graphDatabaseService.createNode(DynamicLabel.label("whateverNow"));
        }catch (Exception e){
            System.out.println("This is again not okay");
            e.printStackTrace();
        }
    }
}


```

**Comment by mneedham** [comment]
Hi,

This `Thread#interrupt` actually results in the JDK NIO libraries that Neo4j uses closing down file channels which is why you see the `java.nio.channels.ClosedByInterruptException` type exceptions.

Is there another way you can setup your job so that it doesn't time out or times out in a more friendly way which you have control over?

**Comment by PavelNiedoba** [comment]
Hallo 

  In general no. The task is supposed to be abstract part of framework, prepared for periodical launching. Therefore timeout is required. I found solution which I'll post later, but the question is if Neo should survive interrupt (beside five shots in chest).

**Comment by PavelNiedoba** [comment]
After reading http://stackoverflow.com/questions/21263446/interrupting-a-thread-running-a-cypher-query-causes-exceptions I realize that only feasible solution would be thread decoupling similar way Orientdb does it. 

  I interact with db using such class:

```java
public abstract class SafeTrans<T> extends Thread implements LogFactory {

    private T result;
    private Exception fail;
    private Logger logger;


    public abstract T doSome() throws Exception;

    public SafeTrans() {
        getLogger().trace("New Async");
    }


    @Override
    public void run() {
        Logger sub = logger.getSubLogger();
        sub.trace("Async thread Start");
        Transaction ltx = Db.get().beginTx();
        try {
            if (!isInterrupted())
                result = doSome();
            if (!isInterrupted()) {
                ltx.success();
                sub.trace("Async sucess");
            } else
                sub.trace("Async interrupted");

        } catch (Exception e) {
            fail = e;
            sub.debug("Async Catch", e);
        } finally {
            sub.trace("Async finally");
            try {
                if (ltx != null)
                    ltx.close();
            }catch (Exception e){
                fail = e;
                sub.trace("failed to commit");
            }
        }
    }


    public T waitForResult() {
        try {
            if (Thread.currentThread() instanceof SafeTrans) {

                getLogger().trace("Running within parent trn");
                if (!Thread.currentThread().isInterrupted())
                    return doSome();
                else
                    getLogger().trace("Running within parent trn");

            }
            getLogger().trace("Async waiting");
            start();
            join();
            getLogger().trace("Async finished wait");
        } catch (Exception e) {
            throw new RuntimeException("Async", e);
        }

        if (fail != null)
            throw new RuntimeException("Async", fail);
        return result;
    }

    @Override
    public Logger getLogger() {
        if (logger == null)
            if (Thread.currentThread() instanceof LogFactory)
                logger= ((LogFactory) Thread.currentThread()).getLogger().getSubLogger();
            else
                logger = Logger.getLogger();
        return logger;
    }
}
```

the usage is:
```java
public <PT> PT getProperty(final String name) {
        return new SafeTrans<PT>() {
            @Override
            public PT doSome() throws Exception {
                if (neoNode.hasProperty(name))
                    return (PT) neoNode.getProperty(name);
                else
                    return null;
            }
        }.waitForResult();
}
```

**Comment by jakewins** [comment]
Just like you suspect, that Java interrupts are treated in the JVM IO systems as fatal and causes open file channels and other IO resources to close.

If you want to interrupt a running Neo4j transaction, the correct approach is to use the `Transaction#terminate()` method, which uses Neo4j's own interrupt mechanism.
