### ISSUE TITLE
AssertionError when setting certain GraphProperties

### ISSUE THREAD

**Issue by bachmanm** [neo4j/neo4j#4415]
Aware of the fact that this isn't for public use, still think you guys might want to know about this. Does not seem to affect nodes and relationships.

```
    @Test
    public void bugDemo() {
        GraphDatabaseService database = new TestGraphDatabaseFactory().newImpermanentDatabase();

        GraphProperties graphProperties = ((GraphDatabaseAPI) database).getDependencyResolver().resolveDependency(NodeManager.class).newGraphProperties();

        try (Transaction tx = database.beginTx()) {
            graphProperties.setProperty("a", new String[]{"A","B","C","D","E","F"});
            graphProperties.setProperty("b", true);
            graphProperties.setProperty("c", "C");
            tx.success();
        }

        try (Transaction tx = database.beginTx()) {
            graphProperties.setProperty("d", new String[]{"A","F"});
            graphProperties.setProperty("e", true);
            graphProperties.setProperty("f", "F");
            tx.success();
        }


        try (Transaction tx = database.beginTx()) {
            graphProperties.setProperty("g", new String[]{"F"});
            graphProperties.setProperty("h", false);
            graphProperties.setProperty("i", "I");
            tx.success(); //fails here
        }

        try (Transaction tx = database.beginTx()) {
            assertFalse((boolean) graphProperties.getProperty("h"));
            tx.success();
        }
    }
```

Fails with:

```
java.lang.AssertionError: NeoStoreRecord[used=true,prop=0]->[Property[0,used=true,prev=1,next=-1,PropertyBlock[blocks=1,ARRAY,key=0,firstDynamic=1],PropertyBlock[blocks=1,BOOL,key=1,value=true],PropertyBlock[blocks=1,SHORT_STRING,key=2,value=C],PropertyBlock[blocks=1,ARRAY,key=3,firstDynamic=2]]]
    at org.neo4j.kernel.impl.transaction.state.PropertyTraverser.assertPropertyChain(PropertyTraverser.java:93)
    at org.neo4j.kernel.impl.transaction.state.PropertyCreator.primitiveAddProperty(PropertyCreator.java:121)
    at org.neo4j.kernel.impl.transaction.state.NeoStoreTransactionContext.primitiveAddProperty(NeoStoreTransactionContext.java:112)
    at org.neo4j.kernel.impl.transaction.state.TransactionRecordState.graphAddProperty(TransactionRecordState.java:508)
    at org.neo4j.kernel.impl.api.KernelTransactionImplementation$TransactionToRecordStateVisitor.visitGraphPropertyChanges(KernelTransactionImplementation.java:753)
    at org.neo4j.kernel.impl.api.state.TxState$12.visitPropertyChanges(TxState.java:370)
    at org.neo4j.kernel.impl.api.state.PropertyContainerState$Mutable.accept(PropertyContainerState.java:231)
    at org.neo4j.kernel.impl.api.state.TxState.accept(TxState.java:180)
    at org.neo4j.kernel.impl.api.KernelTransactionImplementation.prepareRecordChangesFromTransactionState(KernelTransactionImplementation.java:367)
    at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:466)
    at org.neo4j.kernel.impl.api.KernelTransactionImplementation.close(KernelTransactionImplementation.java:417)
    at org.neo4j.kernel.TopLevelTransaction.close(TopLevelTransaction.java:112)
    at com.graphaware.BugTest.demoBug(BugTest.java:47)
```

**Comment by bachmanm** [comment]
magically fixed in 2.3.1, thanks!
