### ISSUE TITLE
HTTP transactionnal Endpoint fails on SharedBlockingCallback$BlockerTimeoutException

### ISSUE THREAD

**Issue by davidrapin** [neo4j/neo4j#4430]
While **streaming** a large amount of edges from neo4j 2.2.0 (using the "rows" result format) we got this error (which breaks the JSON stream):

```
2015-04-03 22:57:17.320+0000 ERROR [o.n.s.r.t.TransactionFacade]: Failed to generate JSON output.
java.io.IOException: org.eclipse.jetty.util.SharedBlockingCallback$BlockerTimeoutException
at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:234) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:133) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:347) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at com.sun.jersey.spi.container.servlet.WebComponent$Writer.write(WebComponent.java:300) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at com.sun.jersey.spi.container.ContainerResponse$CommittingOutputStream.write(ContainerResponse.java:135) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at org.neo4j.server.rest.web.TransactionalService$InterruptingOutputStream.write(TransactionalService.java:303) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at org.codehaus.jackson.impl.Utf8Generator._flushBuffer(Utf8Generator.java:1754) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at org.codehaus.jackson.impl.Utf8Generator.flush(Utf8Generator.java:1088) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at org.codehaus.jackson.map.ObjectMapper.writeValue(ObjectMapper.java:1615) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at org.neo4j.server.rest.transactional.Neo4jJsonCodec.writeValue(Neo4jJsonCodec.java:66) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at org.codehaus.jackson.impl.JsonGeneratorBase.writeObject(JsonGeneratorBase.java:314) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at org.codehaus.jackson.JsonGenerator.writeObjectField(JsonGenerator.java:1090) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at org.neo4j.server.rest.transactional.Neo4jJsonCodec.writePropertyContainer(Neo4jJsonCodec.java:128) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at org.neo4j.server.rest.transactional.Neo4jJsonCodec.writeValue(Neo4jJsonCodec.java:46) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at org.codehaus.jackson.impl.JsonGeneratorBase.writeObject(JsonGeneratorBase.java:314) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at org.neo4j.server.rest.transactional.RowWriter.write(RowWriter.java:37) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at org.neo4j.server.rest.transactional.ExecutionResultSerializer.writeRows(ExecutionResultSerializer.java:378) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at org.neo4j.server.rest.transactional.ExecutionResultSerializer.statementResult(ExecutionResultSerializer.java:108) ~[neo4j-desktop-2.2.0.jar:2.2.0]
at org.neo4j.server.rest.transactional.TransactionHandle.executeStatements(TransactionHandle.java:329) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:146) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.neo4j.server.rest.web.TransactionalService$2.write(TransactionalService.java:211) [neo4j-desktop-2.2.0.jar:2.2.0]
at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71) [neo4j-desktop-2.2.0.jar:2.2.0]
at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57) [neo4j-desktop-2.2.0.jar:2.2.0]
at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302) [neo4j-desktop-2.2.0.jar:2.2.0]
at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510) [neo4j-desktop-2.2.0.jar:2.2.0]
at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [neo4j-desktop-2.2.0.jar:2.2.0]
at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [neo4j-desktop-2.2.0.jar:2.2.0]
at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [neo4j-desktop-2.2.0.jar:2.2.0]
at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540) [neo4j-desktop-2.2.0.jar:2.2.0]
at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715) [neo4j-desktop-2.2.0.jar:2.2.0]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.neo4j.server.rest.dbms.AuthorizationFilter.doFilter(AuthorizationFilter.java:120) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.server.Server.handle(Server.java:497) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620) [neo4j-desktop-2.2.0.jar:2.2.0]
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540) [neo4j-desktop-2.2.0.jar:2.2.0]
at java.lang.Thread.run(Unknown Source) [na:1.7.0_45]
Caused by: org.eclipse.jetty.util.SharedBlockingCallback$BlockerTimeoutException: null
at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:216) ~[neo4j-desktop-2.2.0.jar:2.2.0]
... 50 common frames omitted
```

**Comment by technige** [comment]
Hi @davidrapin. Sorry but only just seeing this. Given this was against Neo4j 2.2, is this still relevant?

**Comment by davidrapin** [comment]
Haven't had this issue since, but I haven't tested 2.2 in a while.
Working daily with v2.1.6, 3.0.x and 3.3.x, never reproduced.

**Comment by zhenlineo** [comment]
Pls be free to reopen the issue if it still exists in more recent neo4j versions.
