### ISSUE TITLE
Batch: Illegal character in path

### ISSUE THREAD

**Issue by armatys** [neo4j/neo4j#4482]
Tested with 2.2.0 and 2.3.0-M01

Executing the following Cypher query, e.g. in browser console fails `:POST /db/data/batch [{"body":null,"id":1,"method":"POST","to":"/node"}, {"body":null, "id":1, "method":"GET","to":"{1}"}, {"body":null, "id":3, "method":"GET", "to":"{2}/properties"}]`

From the `console.log`:

```
2015-04-21 14:03:48.116 WARN  Error executing batch request  Illegal character in path at index 2: ./{2}/properties
java.lang.IllegalArgumentException: Illegal character in path at index 2: ./{2}/properties
    at java.net.URI.create(URI.java:859)
    at java.net.URI.resolve(URI.java:1043)
    at org.neo4j.server.rest.batch.BatchOperations.calculateTargetUri(BatchOperations.java:105)
    at org.neo4j.server.rest.batch.BatchOperations.performRequest(BatchOperations.java:197)
    at org.neo4j.server.rest.batch.BatchOperations.parseAndPerform(BatchOperations.java:173)
    at org.neo4j.server.rest.web.StreamingBatchOperations.readAndExecuteOperations(StreamingBatchOperations.java:59)
    at org.neo4j.server.rest.web.BatchOperationService$1.write(BatchOperationService.java:120)
    at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
    at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
    at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
    at org.neo4j.server.rest.dbms.AuthorizationFilter.doFilter(AuthorizationFilter.java:121)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:497)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Illegal character in path at index 2: ./{2}/properties
    at java.net.URI$Parser.fail(URI.java:2829)
    at java.net.URI$Parser.checkChars(URI.java:3002)
    at java.net.URI$Parser.parseHierarchical(URI.java:3086)
    at java.net.URI$Parser.parse(URI.java:3044)
    at java.net.URI.<init>(URI.java:595)
    at java.net.URI.create(URI.java:857)
    ... 36 more
```

**Comment by jexp** [comment]
- You have twice id: "1"
- You can only refer to nodes that were created from an operation that creates data, i.e. sets a Location Header
- you don't need your second command at all

```
[{"body":null,"id":1,"method":"POST","to":"/node"}, 
 {"body":null, "id":3, "method":"GET", "to":"{1}/properties"}]
```
