### ISSUE TITLE
Killing threads during transaction commits results in database corruption.

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#4539]
I've got a test that reproduces this almost certainly. After the test finishes as failed, `messages.log` contains these lines:

```
2015-04-28 10:26:59.265+0000 ERROR [o.n.k.KernelHealth]: setting TM not OK. Kernel has encountered some problem, please perform neccesary action (tx recovery/restart)
java.lang.ThreadDeath: null
at java.lang.Thread.stop(Thread.java:850) [na:1.8.0_45]
at ontrack.bush.util.Neo4jFeaturesTest.lambda$null$7(Neo4jFeaturesTest.java:111) ~[test-classes/:na]
at ontrack.bush.util.Neo4jFeaturesTest$$Lambda$23/1838897200.run(Unknown Source) ~[na:na]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_45]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_45]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_45]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

After that, restarting the database result in a successful recovery:

```
2015-04-28 10:37:55.740+0000 INFO  [o.n.k.i.DiagnosticsManager]: --- INITIALIZED diagnostics END ---
2015-04-28 10:37:56.050+0000 INFO  [o.n.k.i.a.i.IndexingService]: IndexingService.init: index 1 on :label[0](property[0]) is ONLINE
2015-04-28 10:37:56.180+0000 INFO  [o.n.k.i.a.i.IndexingService]: IndexingService.init: index 2 on :label[0](property[1]) is ONLINE
2015-04-28 10:37:56.183+0000 INFO  [o.n.k.i.a.i.IndexingService]: IndexingService.init: index 3 on :label[1](property[2]) is ONLINE
2015-04-28 10:37:56.185+0000 INFO  [o.n.k.i.a.i.IndexingService]: IndexingService.init: index 4 on :label[2](property[3]) is ONLINE
2015-04-28 10:37:56.186+0000 INFO  [o.n.k.a.i.i.LuceneLabelScanStore]: No lucene scan store index found, this might just be first use. Preparing to rebuild.
2015-04-28 10:37:56.194+0000 INFO  [o.n.k.NeoStoreDataSource]: Recovery required for log with version 0
2015-04-28 10:37:56.454+0000 INFO  [o.n.k.i.s.StoreFactory]: About to rotate counts store at transaction 307 to [/tmp/NFT/neostore.counts.db.b], from [/tmp/NFT/neostore.counts.db.a].
2015-04-28 10:37:56.459+0000 INFO  [o.n.k.i.s.StoreFactory]: Successfully rotated counts store at transaction 307 to [/tmp/NFT/neostore.counts.db.b], from [/tmp/NFT/neostore.counts.db.a].
2015-04-28 10:37:56.493+0000 INFO  [o.n.k.i.a.i.IndexingService]: IndexingService.start: index 1 on :Root(treeName) is ONLINE
2015-04-28 10:37:56.493+0000 INFO  [o.n.k.i.a.i.IndexingService]: IndexingService.start: index 2 on :Root(treeId) is ONLINE
2015-04-28 10:37:56.493+0000 INFO  [o.n.k.i.a.i.IndexingService]: IndexingService.start: index 3 on :Node(id) is ONLINE
2015-04-28 10:37:56.493+0000 INFO  [o.n.k.i.a.i.IndexingService]: IndexingService.start: index 4 on :IdProv(idProvOffset) is ONLINE
2015-04-28 10:37:56.494+0000 WARN  [o.n.k.i.a.i.s.IndexSamplingController]: Recovering index sampling for index :Root(treeName)
2015-04-28 10:37:56.497+0000 INFO  [o.n.k.i.a.i.s.OnlineIndexSamplingJob]: Sampled index :Root(treeName) with 0 unique values in sample of avg size 0 taken from index containing 0 entries
2015-04-28 10:37:56.497+0000 WARN  [o.n.k.i.a.i.s.IndexSamplingController]: Recovering index sampling for index :Root(treeId)
2015-04-28 10:37:56.498+0000 INFO  [o.n.k.i.a.i.s.OnlineIndexSamplingJob]: Sampled index :Root(treeId) with 0 unique values in sample of avg size 0 taken from index containing 0 entries
2015-04-28 10:37:56.498+0000 WARN  [o.n.k.i.a.i.s.IndexSamplingController]: Recovering index sampling for index :Node(id)
2015-04-28 10:37:56.498+0000 INFO  [o.n.k.i.a.i.s.OnlineIndexSamplingJob]: Sampled index :Node(id) with 0 unique values in sample of avg size 0 taken from index containing 0 entries
2015-04-28 10:37:56.498+0000 WARN  [o.n.k.i.a.i.s.IndexSamplingController]: Recovering index sampling for index :IdProv(idProvOffset)
2015-04-28 10:37:56.498+0000 INFO  [o.n.k.i.a.i.s.OnlineIndexSamplingJob]: Sampled index :IdProv(idProvOffset) with 1 unique values in sample of avg size 1 taken from index containing 1 entries
2015-04-28 10:37:56.501+0000 INFO  [o.n.k.a.i.i.LuceneLabelScanStore]: Rebuilding lucene scan store, this may take a while
2015-04-28 10:37:56.512+0000 INFO  [o.n.k.a.i.i.LuceneLabelScanStore]: Lucene scan store rebuilt (roughly 292 nodes)
2015-04-28 10:37:56.517+0000 INFO  [o.n.k.NeoStoreDataSource]: Recovery completed. 306 transactions, first:2, last:307 recovered
2015-04-28 10:37:56.517+0000 INFO  [o.n.k.KernelHealth]: Kernel health set to OK
```

A note concerning the test: it might have been smaller and less clumsy, but I wrote it just as a proof-of-statement, so here it is:

```
@Test
public void testThreadDeathAndTransactionRecovery() throws Exception {
    Runnable r = () -> {
        AtomicInteger cnt = new AtomicInteger(0);
        CyclicBarrier barrier = new CyclicBarrier(2);
        AtomicReference<Thread> t = new AtomicReference<>();
        Future<?> f1 = Executors.newSingleThreadExecutor().submit(() -> {
            try {
                barrier.await();
                t.get().stop();
            } catch (InterruptedException | BrokenBarrierException e) {
                e.printStackTrace();
            }
        });
        for (; cnt.get() < 8; cnt.incrementAndGet()) {
            try {
                Executors.newSingleThreadExecutor().submit(() -> {
                    sleep(100, TimeUnit.MILLISECONDS);
                    Transaction tx = db.beginTx();
                    db.createNode();
                    tx.success();
                    if (cnt.get() == 4) {
                        try {
                            t.set(Thread.currentThread());
                            barrier.await();
                            tx.close();
                        } catch (InterruptedException | BrokenBarrierException e) {
                            e.printStackTrace();
                        }
                    }
                    if (cnt.get() != 4) {
                        tx.close();
                    }
                }).get();
            } catch (Throwable ignored) {
            }
        }
        try {
            f1.get();
        } catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
        }
        System.out.println("OK");
    };
    ExecutorService e = Executors.newFixedThreadPool(100);
    for (int i = 0; i < 100; i++) {
        e.execute(r);
    }
    e.shutdown();
    e.awaitTermination(1, TimeUnit.MINUTES);

    if (db.isAvailable(TimeUnit.MINUTES.toMillis(1))) {
        try (Transaction tx = db.beginTx()) { // FAILS HERE
            db.createNode(() -> "QWERTY").setProperty("sdf", 1241465423L);
            tx.success();
        }
        db.shutdown();
    }
}
```

To recover the database afterwards nothing special has to be done.

I'm not sure if this is actually a bug, because it's possible to recover the data, but since I can easily corrupt the transaction logs (or whatever it is corrupted), I hope you could spare some time to look into the issue.

P.S. Or (at least) an exception message could be changed from `(tx recovery/restart)` to something about the database restart procedure.

**Comment by thobe** [comment]
If the database is able to recover properly, I don't see the problem.

If the transaction logs were corrupted the database would most likely not be able to recover.

What is this corruption of which you speak? I see no evidence of it in the traces you have reported. If you have been able to find something that corrupts data, or makes the database unable to start, I would want to investigate that. But I can't see anything of the sort in your report.

From what I can see the database is behaving as expected. You are abusing the runtime, by stopping threads (an unsupported operation, documented as ["This method is inherently unsafe."](http://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#stop%28%29)). This results in the database not trusting the internal state of the runtime, and electing to shut down, blocking all future transactions until a restart takes place. ("TM" is short for "Transaction Manager", and setting it to "not OK" means refusing further transactions)

I agree that the exception message could be better. But what you are doing is not something that is possible to support in a better way, and your data does appear to be safe.

**Comment by tkroman** [comment]
I'm aware of the unsupported status of the `Thread#stop()` method and that I'm abusing the database. Just as I said, I'm not sure that's a bug: I'm confused about the fact that it's so easy to render the database inconsistent while at the same time getting it back up and running is relatively simple as well. Plus, we have to bring the database down for this, which is a negative factor too.

**Comment by thobe** [comment]
You keep making me worried when you say that the database is inconsistent or corrupt. What is it that is inconsistent?

**Comment by tkroman** [comment]
I'm sorry, perhaps I'm using the wrong term. I'm referring to the state from which it is impossible to interact with the database unless it's restarted.

**Comment by chrisvest** [comment]
> Plus, we have to bring the database down for this, which is a negative factor too.

By this you mean that the database has to be restarted after being hit with `ThreadDeath`, before it can be used again?

I'm curious as to why you are calling `Thread#stop()` in the first place. We have a method for terminating transactions from other threads, if that's what you need:
http://neo4j.com/docs/2.2.1/javadocs/org/neo4j/graphdb/Transaction.html#terminate()

**Comment by tkroman** [comment]
Yes, I do mean the restarting thing. This is my main concern - if the recovery process is relatively simply, why should it be a shutdown at all? Or is there any way to bring the database back up without affecting all the connected clients? If someone made this request that resulted it the bad kernel health status, is it possible to deal with the issue so that other clients would see this as just a delay in servicing requests, not a whole log of error messages and a dead databse?

Of course I'm not calling `Thread#stop()`, that would be a mauvais ton :) An application that this instance is embedded into has this weird way of terminating long-running (exceeding their limit) tasks. Now that I think of it more, I understand that I'm trying to get _you_ to deal with _my_ problems.

**Comment by chrisvest** [comment]
Errors like `ThreadDeath`, `StackOverflowError` and `OutOfMemoryError` can happen at any point in the code - even in any recovery code that would try to cope with these errors. It's just not possible for us to gracefully tolerate them and recover in the general case. Ideally we would like to just crash the entire process, but we can't even make that decision because we don't know what kind of process we might be embedded in. The best we can do is to "stop the line" and prevent any disaster from spreading, which is exactly what the "TM not OK" is about. That's just how it is when you're and embedded database written in Java.
