### ISSUE TITLE
Concurrent Write - random crashes for more then 2 threads

### ISSUE THREAD

**Issue by Bryksin** [neo4j/neo4j#4543]
Hello

I was testing performance of neo4j database and got unexpected crashed during concurrent write while I was filling database with random dummy data

The code I used for the test can be checked out here: https://github.com/Briksins/neo4j-stress-test

Basically I have machine with 4 cores + 4 HT = 8 cores in total
If I write in all 8 concurrent threads, or even anything more than 1 threads - im getting the following random crashes:

```
***<omitted>*** 
[stress-worker-6] ERROR test.DatabaseManager$ - Hospitals and Doctors insert error: 
java.sql.SQLException: Error executing query MATCH (a:doctor),(b:hospital) WHERE a.name = 'doctor_1_from_hospital_0_6' AND b.name = 'hospital_0_6' CREATE (a)-[r:employed_at]->(b)
 with params {}
    at org.neo4j.jdbc.internal.Neo4jConnection.executeQuery(Neo4jConnection.java:379)
***<omitted>***
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Error during parsing
    at org.neo4j.jdbc.internal.rest.StreamingParser$ParserState.nextToken(StreamingParser.java:71)
***<omitted>***
    ... 15 more
Caused by: java.io.IOException: Attempted read from closed stream.
    at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:154)
***<omitted>***
Error while handling an HTTP client call
***<omitted>***
java.lang.ArrayIndexOutOfBoundsException
    at java.net.SocketInputStream.read(SocketInputStream.java:162)
***<omitted>***
```

**Comment by jexp** [comment]
That's rather an issue with the JDBC driver not with Neo4j. Can you raise it there please?

http://github.com/neo4j-contrib/neo4j-jdbc/issues

The JDBC driver is not yet the most performant implementation I wanted to work on that.

I can try to use your test to drive out the issue there.

If you just want to do stress testing try a raw (pooled) http connection posting queries to `/db/data/transaction/commit`.
