### ISSUE TITLE
Neo4j browser (Community 2.2.1) does not load in Chrome 43.0.2357.65 (64-bit)

### ISSUE THREAD

**Issue by subvertallchris** [neo4j/neo4j#4651]
Just verified on two computers here in my office. It worked fine on mine when I was running the last build of 42, then I ran the auto-update, restarted the browser, and it won't load.

Chrome inspector shows:

```
Uncaught SyntaxError: Unexpected token ILLEGAL
9af5a995.scripts.js:1 Uncaught ReferenceError: CodeMirror is not defined
3dd12436.components.js:8 Uncaught Error: [$injector:modulerr] Failed to instantiate module neo4jApp due to:
Error: [$injector:nomod] Module 'neo4jApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.10/$injector/nomod?p0=neo4jApp
    at http://localhost:7475/browser/scripts/3dd12436.components.js:7:18216
    at http://localhost:7475/browser/scripts/3dd12436.components.js:7:31626
    at ensure (http://localhost:7475/browser/scripts/3dd12436.components.js:7:30881)
    at http://localhost:7475/browser/scripts/3dd12436.components.js:7:31394
    at http://localhost:7475/browser/scripts/3dd12436.components.js:8:14061
    at forEach (http://localhost:7475/browser/scripts/3dd12436.components.js:7:18860)
    at loadModules (http://localhost:7475/browser/scripts/3dd12436.components.js:8:13587)
    at createInjector (http://localhost:7475/browser/scripts/3dd12436.components.js:8:16810)
    at doBootstrap (http://localhost:7475/browser/scripts/3dd12436.components.js:7:27816)
    at bootstrap (http://localhost:7475/browser/scripts/3dd12436.components.js:7:28345)
http://errors.angularjs.org/1.3.10/$injector/modulerr?p0=neo4jApp&p1=Error%…Flocalhost%3A7475%2Fbrowser%2Fscripts%2F3dd12436.components.js%3A7%3A28345)
http://localhost:7475/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
```

Both computers are Macs running 10.10.3.

**Comment by oskarhane** [comment]
Thanks @subvertallchris, I can confirm this on my machine.
Starting investigation.

**Comment by oskarhane** [comment]
This should be fixed with https://github.com/neo4j/neo4j/commit/202a24597021febeaf798e628d3e6bbf6a36f6b9.
Going out in the next release.
