### ISSUE TITLE
Internal server error using /batch/ endpoint

### ISSUE THREAD

**Issue by area** [neo4j/neo4j#4671]
While the following works correctly on ~~2.2.0~~ 2.1.7, it does not on 2.2.1. On a clean database, POSTing the following to /db/data/batch:

```
[{"id":0,"method":"POST","to":"/cypher","body":{"query":"MATCH (n:user) RETURN n"}}]
```

fails, returning a 500 error code, with the following stacktrace:

```
{ "exception" : "NullPointerException", "fullname" : "java.lang.NullPointerException", "stackTrace" : [ "org.neo4j.server.web.Jetty9WebServer.invokeDirectly(Jetty9WebServer.java:341)", "org.neo4j.server.rest.batch.NonStreamingBatchOperations.invoke(NonStreamingBatchOperations.java:56)", "org.neo4j.server.rest.batch.BatchOperations.performRequest(BatchOperations.java:205)", "org.neo4j.server.rest.batch.BatchOperations.parseAndPerform(BatchOperations.java:173)", "org.neo4j.server.rest.batch.NonStreamingBatchOperations.performBatchJobs(NonStreamingBatchOperations.java:49)", "org.neo4j.server.rest.web.BatchOperationService.batchProcess(BatchOperationService.java:148)", "org.neo4j.server.rest.web.BatchOperationService.performBatchOperations(BatchOperationService.java:78)", "java.lang.reflect.Method.invoke(Method.java:606)", "org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139)", "ch.qos.logback.access.servlet.TeeFilter.doFilter(TeeFilter.java:55)", "org.neo4j.server.rest.dbms.AuthorizationFilter.doFilter(AuthorizationFilter.java:120)", "java.lang.Thread.run(Thread.java:745)" ], "errors" : [ { "message" : null, "code" : "Neo.DatabaseError.General.UnknownFailure", "stackTrace" : "java.lang.NullPointerException  
    at org.eclipse.jetty.server.Request.getHttpChannelState(Request.java:410)   
    at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:107)    
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)   
    at org.neo4j.server.web.Jetty9WebServer.invokeDirectly(Jetty9WebServer.java:341)    
    at org.neo4j.server.rest.batch.NonStreamingBatchOperations.invoke(NonStreamingBatchOperations.java:56)  
    at org.neo4j.server.rest.batch.BatchOperations.performRequest(BatchOperations.java:205) 
    at org.neo4j.server.rest.batch.BatchOperations.parseAndPerform(BatchOperations.java:173)    
    at org.neo4j.server.rest.batch.NonStreamingBatchOperations.performBatchJobs(NonStreamingBatchOperations.java:49)    
    at org.neo4j.server.rest.web.BatchOperationService.batchProcess(BatchOperationService.java:148) 
    at org.neo4j.server.rest.web.BatchOperationService.performBatchOperations(BatchOperationService.java:78)    
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)    
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)    
    at java.lang.reflect.Method.invoke(Method.java:606) 
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) 
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)    
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) 
    at org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139) 
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)  
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)    
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)    
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) 
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)   
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)   
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)    
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)    
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) 
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540) 
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715) 
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) 
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)   
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)  
    at ch.qos.logback.access.servlet.TeeFilter.doFilter(TeeFilter.java:55)  
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)  
    at org.neo4j.server.rest.dbms.AuthorizationFilter.doFilter(AuthorizationFilter.java:120)    
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)  
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)   
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)    
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)   
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)    
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) 
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)    
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)    
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) 
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)   
    at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95) 
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)   
    at org.eclipse.jetty.server.Server.handle(Server.java:497)  
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)    
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)  
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)   
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620) 
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)  
    at java.lang.Thread.run(Thread.java:745)\n" } ] }
```

For completeness, I am on OSX 10.10.3, with neo4j installed via homebrew.

**Comment by area** [comment]
After some prodding around, I think it is unlikely that this is an issue with only Neo4J; I have tested on another OSX machine, and everything worked fine. I have found a very similar stacktrace encountered by a user on Ubuntu nearly a year ago ( https://gist.github.com/maggit/28d190488616477a960e ), though no solution or explanation was posted. In addition, tunnelling my database connection to another machine works, as one might expect. 

I managed to get the above stack trace on 2.1.7 as well; it seems as if running my test suite seems to (sometimes) get neo4j into a state where the above stacktrace is seen when using the batched endpoint; even deleting shutting down neo4j, deleting graph.db and restarting does not get it out of this state. Deleting the whole neo4j installation, and starting afresh from the .tar.gz does work (thankfully!), until I manage to get it into this state again.

I am rather at a loss.

**Comment by lutovich** [comment]
Hello @area,

Sorry, it took us quite some time to fix this issue. Hope you've not suffered a lot.
It should be fixed by https://github.com/neo4j/neo4j/pull/5049 and released with neo4j 2.2.4.

Would be great if you could try out the fix.

**Comment by igorclark** [comment]
Hi there, I just came up against the same problem in `2.2.0`, even a single entity in the batch causes a `500 Server Error`.

I'd love to try the fix in `2.2.4` but all our build mechanisms use `neo4j` `.deb` files from the `debian.neo4j.org` repo - and AFAICT, the repo only has up to version `2.2.3` in it. Will `2.2.4` make it into the debian repo soon?

Thanks,
Igor

**Comment by lutovich** [comment]
Hello @igorclark,

Neo4j 2.2.4 is not released yet, but it'll definitely appear in debian repository as part of the release.
Could you please check if http logging is enabled in `neo4j-server.properties`?
Relevant property is `org.neo4j.server.http.log.enabled`.

**Comment by igorclark** [comment]
Hey @lutovich, thanks - http logging was enabled, and switching it to `false` seems to have made it work! Cool. Thanks.

This is since I upgraded to `2.2.3` to check what was in the repo. Will switching off http logging work around this bug in `2.2.0` as well?

**Comment by lutovich** [comment]
Yes, this should help.
Neo4j 2.2.4 should be released soon. I'll update this ticket about the release.

## 

Best regards,
Konstantin

**Comment by igorclark** [comment]
Thank you Konstantin, that's great. Appreciate your help :+1:

**Comment by lutovich** [comment]
Hello @area, @igorclark.
Neo4j 2.2.4 with mentioned fix is now released. Would be great if you could check it out.
Thanks for help!

**Comment by igorclark** [comment]
Hey @lutovich, thanks! Our VM build system needs a release of the spatial plugin tied to the neo version, so I can't do an auto-build until there's a neo4j-spatial-0.15-neo4j-2.2.4.jar - and a big part of the batch upload process we needed to work uses the spatial plugin. Argh.

Will try to run it on a plain VM if I have time, and let you know how it goes. The "don't log HTTP" workaround is working fine for us at the moment though.

Thanks again Konstantin,
Igor
