### ISSUE TITLE
java.lang.StackOverflowError: null at org.neo4j.cypher.internal.compiler.v2_2.ast.rewriters.expandStar$$anonfun$1$$anonfun$apply$1.apply(expandStar.scala:35)

### ISSUE THREAD

**Issue by ceefour** [neo4j/neo4j#4783]
neo4j 2.2.2

Error:

```
java.lang.StackOverflowError: null
    at org.neo4j.cypher.internal.compiler.v2_2.ast.rewriters.expandStar$$anonfun$1$$anonfun$apply$1.apply(expandStar.scala:35)
    at org.neo4j.cypher.internal.compiler.v2_2.replace.apply(Rewritable.scala:208)
    at org.neo4j.cypher.internal.compiler.v2_2.replace$$anon$2.expand(Rewritable.scala:198)
    at org.neo4j.cypher.internal.compiler.v2_2.ast.rewriters.expandStar$$anonfun$1$$anonfun$apply$1.apply(expandStar.scala:35)
...REPEATS...
    at org.neo4j.cypher.internal.compiler.v2_2.replace.apply(Rewritable.scala:208)
    at org.neo4j.cypher.internal.compiler.v2_2.replace$$anon$2.expand(Rewritable.scala:198)
    at org.neo4j.cypher.internal.compiler.v2_2.ast.rewriters.expandStar$$anonfun$1$$anonfun$apply$1.apply(expandStar.scala:35)
```

How to reproduce:
1. Clone https://github.com/ceefour/opencog-neo4j/tree/cypher-2.2.2-stackoverflow tag **cypher-2.2.2-stackoverflow**
2. Grab the file https://gist.github.com/ceefour/b546d8636766a3bc5056
3. Run `ImportBio2App` main class using arguments: `Lifespan-observations_2015-02-21.scm ~/tmp/lifespan.neo4j`

It will generate the error.

**Comment by jexp** [comment]
Does it generate a gigantic cypher statement (which is not recommended anyway) or many smaller ones?

**Comment by ceefour** [comment]
Yups, a gigantic Cypher

**Comment by jexp** [comment]
I think the parser was never meant to parse gigantic statements, and it will be very inefficient to plan and execute.

I very much recommend splitting it into many small similar, parametrized statements which can be executed in a batch (e.g. 1k simple statements http-request) but also concurrently (with 2.2.x concurrent write load is really high).

**Comment by ceefour** [comment]
It's not using HTTP though, but embedded.

What's the best practice when using smaller statements? 10000 statements in 1 transaction, or 10000 statements in 10000 transactions?

**Comment by jexp** [comment]
10k statements per tx are fine. 
If you can write concurrently you can also do 1k statements per tx and then use 12 to 32 concurrent write threads.
