### ISSUE TITLE
Getting relationship details in TransactionData while using a kernel extension

### ISSUE THREAD

**Issue by ducky427** [neo4j/neo4j#4785]
I am trying to get the `startNode`, the `endNode` and the `type` for a Relationship in a `TransactionEventHandler` with the `TransactionData` `state` object. I am trying to extract that information in the `afterCommit` method.

I get the following stacktrace:

```
ERROR [o.n.s.r.t.TransactionFacade]: Failed to commit transaction.
java.lang.IllegalStateException: This transaction has already been completed.
    at org.neo4j.kernel.impl.api.KernelTransactionImplementation.assertTransactionOpen(KernelTransactionImplementation.java:376) ~[neo4j-kernel-2.2.2.jar:2.2.2]
    at org.neo4j.kernel.impl.api.KernelTransactionImplementation.acquireStatement(KernelTransactionImplementation.java:261) ~[neo4j-kernel-2.2.2.jar:2.2.2]
    at org.neo4j.kernel.impl.api.KernelTransactionImplementation.acquireStatement(KernelTransactionImplementation.java:80) ~[neo4j-kernel-2.2.2.jar:2.2.2]
    at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.instance(ThreadToStatementContextBridge.java:64) ~[neo4j-kernel-2.2.2.jar:2.2.2]
    at org.neo4j.kernel.InternalAbstractGraphDatabase$7.statement(InternalAbstractGraphDatabase.java:765) ~[neo4j-kernel-2.2.2.jar:2.2.2]
    at org.neo4j.kernel.impl.core.RelationshipProxy.initializeData(RelationshipProxy.java:101) ~[neo4j-kernel-2.2.2.jar:2.2.2]
    at org.neo4j.kernel.impl.core.RelationshipProxy.sourceId(RelationshipProxy.java:127) ~[neo4j-kernel-2.2.2.jar:2.2.2]
    at org.neo4j.kernel.impl.core.RelationshipProxy.getStartNode(RelationshipProxy.java:197) ~[neo4j-kernel-2.2.2.jar:2.2.2]
```

I know that I can get that information without any issue if I were to use the `beforeCommit` method.  

I think given the you can get all the information about a Node in `afterCommit`, there should be parity in functionality relating to a Relationship.

Thanks!

**Comment by jexp** [comment]
You will have to start a new read-transaction to access the data.

Can you get all outgoing relationships etc. of a node?

**Comment by ducky427** [comment]
Thanks @jexp. Thats what I will do in my app. But I thought that this should be added to the `TransactionData` object to make sure you don't need to have the complexity of managing a transaction.

Looking on SO, I found a [comment](http://stackoverflow.com/a/30288485/1224343) by @sarmbruster, which suggests that the intent of `TransactionData` was to provide the user with all the information about what has been added/deleted/updated.

So you can get all the information about all the changes (addition/deleting/updation) happening to a node  but with relationships, you have information about the ID and the properties but crucially you don't have access to the start/end node and the type of the relationship without being in a transaction.

So it feels like the API could be improved when it comes to relationship.

**Comment by jexp** [comment]
So it is really just about start-node-id,end-node-id,type ?

**Comment by ducky427** [comment]
Exactly. just that.

Given those pieces of info, collecting the creates/updates/deletes, you have all the information about the graph - nodes and relationships.

**Comment by spacecowboy** [comment]
Fixed in https://github.com/neo4j/neo4j/pull/4814
