### ISSUE TITLE
EigenVector Centrality is giving null, if first node's degree is 0

### ISSUE THREAD

**Issue by iandecks45** [neo4j/neo4j#4847]
Hi there,

I am using neo4j-graph-algo-2.2.2 library for EigenVector centrality. But, I guess there is a bug. For example, if your first node (or vertex) is not connected to others (degree is 0), the calculation is giving null exception. There is something with first node's degree.

Please help me

NodeID Degree
1  0
2  1
4  3
Exception in thread "main" java.lang.NullPointerException
    at org.neo4j.graphalgo.impl.centrality.EigenvectorCentralityPower.runIterations(EigenvectorCentralityPower.java:180)
    at org.neo4j.graphalgo.impl.centrality.EigenvectorCentralityPower.calculate(EigenvectorCentralityPower.java:126)
    at org.neo4j.graphalgo.impl.centrality.EigenvectorCentralityPower.getCentrality(EigenvectorCentralityPower.java:93)
    at neo4j.Neo4jEssentials.getEigenVectorCentralityForAllNodes(Neo4jEssentials.java:304)
    at neo4j.ShortestPathTest.runEverythingResults(ShortestPathTest.java:124)
    at neo4j.ShortestPathTest.main(ShortestPathTest.java:50)

**Comment by jexp** [comment]
I reported it to the team, but if you have time and the means we would also be happy about a pull request.

**Comment by burqen** [comment]
Issue solved by https://github.com/burqen/neo4j/commit/4712de476aabe69cd762233c9641dd3cf9f8361b

**Comment by burqen** [comment]
Issue solved by https://github.com/neo4j/neo4j/pull/5018
