### ISSUE TITLE
BUG in Result::columnAs(String name) - NotFoundException is never raised.

### ISSUE THREAD

**Issue by bHacklv** [neo4j/neo4j#4907]
Hi,
`Result::columnAs(String name)` JavaDocs point out that it has to throw **org.neo4j.graphdb.NotFoundException** _when the column name does not appear in the original query_.

I've tested multiple times and it's not the case.. 
This is my Cypher query i've used - `"MATCH (n)-[r]->() RETURN n,r"`.
If I try to do

```
public ResourceIterator<Object> executeTypedCypher(String query, String column) {
        Result queryResult = db.execute(query, new HashMap<String, Object>());
        return queryResult.columnAs(column);
    }

where [column] is set as "m"
```

it returns empty iterator instead. The bug must be somewhere in **scala** after `ExecutionResult::columnAs(String n)` call, as it is transforming scala object to java...

**Comment by FylmTM** [comment]
Hi,

A bit more info on this issue.

Code example:

``` java
try (Transaction tx = db.beginTx()) {
    String query = "MATCH (n)-[r]->() RETURN n,r";
    try (Result queryResult = db.execute(query)) {
        try(ResourceIterator<Node> objectResourceIterator = queryResult.columnAs("nonexisting")) {
            // do nothing
        }
    }
    tx.success();
}
```

JavaDoc for `columnAs()` states that:

```
/**
* @throws org.neo4j.graphdb.NotFoundException when the column name does not appear in the original query
*/
```

But, we receive:

```

java.lang.Exception: Unexpected exception, expected<org.neo4j.graphdb.NotFoundException> but was<org.neo4j.cypher.internal.compiler.v2_3.EntityNotFoundException>
    at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at com.neueda.neo4j.driver.tests.integration.util.runner.IntegrationTestRunner.gentlyRunChild(IntegrationTestRunner.java:107)
    at com.neueda.neo4j.driver.tests.integration.util.runner.IntegrationTestRunner.runChild(IntegrationTestRunner.java:76)
    at com.neueda.neo4j.driver.tests.integration.util.runner.IntegrationTestRunner.runChild(IntegrationTestRunner.java:31)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: org.neo4j.cypher.internal.compiler.v2_3.EntityNotFoundException
    at org.neo4j.cypher.internal.compiler.v2_3.PipeExecutionResult$$an$$$$99d1a0b12a354489c77d6a81a41a99$$$$nResult$$getAnyColumn$1.apply(PipeExecutionResult.scala:85)
    at org.neo4j.cypher.internal.compiler.v2_3.PipeExecutionResult$$an$$$$99d1a0b12a354489c77d6a81a41a99$$$$nResult$$getAnyColumn$1.apply(PipeExecutionResult.scala:85)
    at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
    at scala.collection.AbstractMap.getOrElse(Map.scala:58)
    at org.neo4j.cypher.internal.compiler.v2_3.PipeExecutionResult.org$neo4j$cypher$internal$compiler$v2_3$PipeExecutionResult$$getAnyColumn(PipeExecutionResult.scala:84)
    at org.neo4j.cypher.internal.compiler.v2_3.PipeExecutionResult$$anon$1.next(PipeExecutionResult.scala:61)
    at org.neo4j.cypher.javacompat.ExecutionResult$ExceptionConversion.next(ExecutionResult.java:336)
    at com.google.common.collect.Iterators.addAll(Iterators.java:362)
    at com.google.common.collect.Lists.newArrayList(Lists.java:160)
    at com.neueda.neo4j.driver.tests.integration.util.helpers.DatabaseHelper.executeTypedCypher(DatabaseHelper.java:139)
    at com.neueda.neo4j.driver.tests.integration.cypher.ExecuteTest.testThrowNotFoundExceptionWhenColumnNotFound(ExecuteTest.java:330)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
    ... 22 more
```

**Comment by cleishm** [comment]
Hi @bHacklv (& @FylmTM),

Thanks for reporting this issue. I've triaged it to our team and we'll look into it.

Cheers,
Chris

**Comment by Mats-SX** [comment]
Hello @bHacklv and @FylmTM.

I am curious about under what scenario you are able to receive the stacktrace from above? I am only able to reproduce this with receiving empty iterators.

EDIT: Also, just to be sure, this is 2.3 that you are running, right?

**Comment by bHacklv** [comment]
Hi @Mats-SX 
We are using '2.3.0-M01'.

This exception is thrown if we try to return `Lists.newArrayList(objectResourceIterator);`

while iterating over the Result#columnsAs(noin-existing-column).
Code example:

``` java
try (final ResourceIterator<T> objectResourceIterator = queryResult.columnAs(column)) {
    return Lists.newArrayList(objectResourceIterator);  // <<----- this will throw that exception FylmTM posted
}
```

The problem is that `queryResult.columnAs(column)` should have already thrown `org.neo4j.graphdb.NotFoundException` straight away, however it returns non-empty transformed iterator. Transformation happens in deprecated ExecutionResult + Scala classes.

**Comment by craigtaverner** [comment]
Fixed by https://github.com/neo4j/neo4j/pull/5124
