### ISSUE TITLE
Embedded upgrade to 2.2(.3) causes instance to refuse start up due to /data/dbms/auth

### ISSUE THREAD

**Issue by jensenmo** [neo4j/neo4j#4949]
When attempting to start a Java service with an embedded Neo4j 2.2.3 upgraded from 2.1 it fails to start - see exception stack trace at bottom. This does not happen when starting same neo4j database standalone (using neo4j start).

I found 2 possible workarounds:
1) Create the /data (yes, in root of file system) directory and chown it to the owner of the embedded neo4j process (it will then take care to create /data/dbms/auth at first start-up)
2) Set the dbms.security.auth_enabled=false property in neo4j-server.properties <- so effectively disable authentication; however we do not use nor provide access to the web interface anyway

There appears to be no way to override the location, e.g. via a setting, of this file. My understanding is that auth file _should_ be located relative to the database path in data/dbms/auth; at least according to documentation: http://neo4j.com/docs/stable/security-server.html#security-server-auth

Stack trace:

org.neo4j.server.ServerStartupException: Starting Neo4j Server failed: Component 'org.neo4j.server.security.auth.AuthManager@50db599f' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:258)
        at com.citizenme.pdxuser.dao.GraphDAOFactory.init(GraphDAOFactory.java:61)
        at com.citizenme.pdxuser.verticle.PdxService.start(PdxService.java:53)
        at org.vertx.java.platform.Verticle.start(Verticle.java:82)
        at org.vertx.java.platform.impl.DefaultPlatformManager$22.run(DefaultPlatformManager.java:1765)
        at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.security.auth.AuthManager@50db599f' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:513)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:203)
        ... 9 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.security.auth.AuthManager@50db599f' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:513)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:203)
        ... 9 more
Caused by: java.nio.file.AccessDeniedException: /data
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:383)
        at java.nio.file.Files.createDirectory(Files.java:630)
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:734)
        at java.nio.file.Files.createDirectories(Files.java:720)
        at org.neo4j.server.security.auth.FileUserRepository.saveUsersToFile(FileUserRepository.java:192)
        at org.neo4j.server.security.auth.FileUserRepository.create(FileUserRepository.java:99)
        at org.neo4j.server.security.auth.AuthManager.newUser(AuthManager.java:95)
        at org.neo4j.server.security.auth.AuthManager.start(AuthManager.java:62)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507)
        ... 11 more

**Comment by cleishm** [comment]
Hi @jensenmo,

The auth file is only created when using Neo4j server: it shouldn't exist at all if you're using the embedded APIs. You said it works when started as a server (via `neo4j start`), and I assume the file is created inside the data directory of the server install? If so, it seems that there is no bug here.

That stack trace suggests you are probably using the internal server components in your app, rather than the embedded APIs. There's good documentation to explain which libraries to include in your app and how to start an embedded database here: http://neo4j.com/docs/2.2.3/tutorials-java-embedded-setup.html

Cheers,
Chris
