### ISSUE TITLE
Access type of a deleted relationship from another transaction

### ISSUE THREAD

**Issue by Nghi93** [neo4j/neo4j#5006]
How am I supposed to access the type of a deleted relationship from another transaction than
the one in which the relationship got deleted?

``` java
    TransactionData data;

        graphDb.registerTransactionEventHandler(new TransactionEventHandler<Object>(){
            @Override
            public void afterCommit(TransactionData arg0, Object arg1) {
                data = arg0;

            }   
        });

        try(Transaction tx = graphDb.beginTx()){
            engine.execute("match (n:Add)-[r]-(m) DELETe r");
            tx.success();
        }

        try(Transaction tx = graphDb.beginTx()){
            for(Relationship r : data.deletedRelationships()){
                System.out.println(r.getType());
            }
            tx.success();
        }
    } 
```

This will cause:
org.neo4j.graphdb.NotFoundException: Relationship 0 not found
    at org.neo4j.kernel.impl.core.NodeManager.getRelationshipForProxy(NodeManager.java:554)
    at org.neo4j.kernel.InternalAbstractGraphDatabase$6.lookupRelationship(InternalAbstractGraphDatabase.java:870)
    at org.neo4j.kernel.impl.core.RelationshipProxy.getType(RelationshipProxy.java:146)
    at graph.test.GraphTestWithNeo4j.bla(GraphTestWithNeo4j.java:720)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

When I try to access the type inside the afterCommit block, it works, but I need to do it in another transaction.

**Comment by jexp** [comment]
You are not expected to access this data outside of the `afterCommit` block.

**Comment by Nghi93** [comment]
I found a solution:
You have to add this into the afterCommit block to provoke caching??:

``` java
for(Relationship r : transactionData.deletedRelationships()){
    r.getType();
}
```
