### ISSUE TITLE
InvalidRecordException: DynamicRecord Not in use

### ISSUE THREAD

**Issue by arikan** [neo4j/neo4j#5055]
Hi there,

We're on Neo4j 2.2.1 on Ubuntu EC2 instance.

We're stuck with `InvalidRecordException: DynamicRecord Not in use` error. This is extremely urgent as it is a live database. 

Among our User records, two of them somehow got corrupt property `user.encrypted_password`, any time we try to access them we get the error below: 

```
org.neo4j.kernel.impl.store.InvalidRecordException: DynamicRecord Not in use, blockId[54752]
```

To demonstrate: 

```
MATCH (u:User)
WHERE u.email IN ['...@gmail.com', '...@hotmail.com']
RETURN u.email
```

returns: 

```
u.email
...@gmail.com
...@hotmail.com
```

```
MATCH (u:User)
WHERE u.email IN ['...@gmail.com', '...@hotmail.com']
RETURN u.encrypted_password
```

returns:

```
org.neo4j.kernel.impl.store.InvalidRecordException: DynamicRecord Not in use, blockId[85070]
 Neo.DatabaseError.Statement.ExecutionFailure
```

We cannot delete this node, change its fault property, or remove its label: 

```
MATCH (u:User)
WHERE u.email IN ['...@gmail.com', '...@hotmail.com']
SET u:UserFault
```

returns:

```
org.neo4j.kernel.api.exceptions.TransactionFailureException: Validation of index updates failed
 Neo.DatabaseError.Transaction.CouldNotCommit
```

When we look at the `graph.db/messages.log` we see this error is caused by the `DynamicRecord Not in Use` as well. 

We also restarted the database incase it recovers, no luck. 

We opened the database in  Neo4j 2.2.3, no luck, getting the same errors. 

It seems a relevant issue is also not closed here https://github.com/neo4j/neo4j/issues/4391

This is urgent, so any help to recover from this is appretiated. Thanks!

**Comment by tkroman** [comment]
Yup. We still get these sporadically as well.

**Comment by jexp** [comment]
Hey @arikan perhaps this tool can help you to copy the store and skip these records: 

https://github.com/jexp/store-utils

Otherwise if you have a support contract please raise a zendesk issue, otherwise please send an email to info@neotechnology.com with request for support.

**Comment by arikan** [comment]
We've done exceptions for the fault data, but the metastasis is quite deep that our surgery cannot completely heal the database.

We are ready to leave behind the fault data and migrate to a new database instance. However we couldn't sucessfully run the store-utils https://github.com/jexp/store-utils

**Comment by arikan** [comment]
We're trying the store-utils, it throws the same error that we get in the fault database. See the stack trace below, it occurs when new embedded database is created.

Sorry we are not posting this on the store-utils repo, but we think this is relevant to this issue as well. Any help is appretiated. Thanks.

```
java.lang.RuntimeException: Error starting org.neo4j.kernel.EmbeddedGraphDatabase, /home/ahmetkizilay/WORK/TOOLS/neo4j-community-2.2.1/data/graph.db
    at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:334)
    at org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:59)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:108)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:95)
    at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:176)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(GraphDatabaseFactory.java:67)
    at org.neo4j.tool.StoreCopy.getHighestNodeId(StoreCopy.java:94)
    at org.neo4j.tool.StoreCopy.copyStore(StoreCopy.java:75)
    at org.neo4j.tool.StoreCopy.main(StoreCopy.java:57)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:290)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.transaction.state.DataSourceManager@45c23e8' was successfully initialized, but failed to start. Please see attached cause exception.
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:513)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115)
    at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:329)
    ... 14 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@631b0ab5' was successfully initialized, but failed to start. Please see attached cause exception.
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:513)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115)
    at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:117)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507)
    ... 16 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.api.index.IndexingService@f968933' was successfully initialized, but failed to start. Please see attached cause exception.
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:513)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115)
    at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:526)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507)
    ... 19 more
Caused by: org.neo4j.kernel.impl.store.InvalidRecordException: DynamicRecord Not in use, blockId[84964]
    at org.neo4j.kernel.impl.store.AbstractDynamicStore.checkForInUse(AbstractDynamicStore.java:424)
    at org.neo4j.kernel.impl.store.AbstractDynamicStore.getRecords(AbstractDynamicStore.java:407)
    at org.neo4j.kernel.impl.store.AbstractDynamicStore.getLightRecords(AbstractDynamicStore.java:379)
    at org.neo4j.kernel.impl.store.PropertyStore.ensureHeavy(PropertyStore.java:295)
    at org.neo4j.kernel.impl.store.PropertyStore.getStringFor(PropertyStore.java:601)
    at org.neo4j.kernel.impl.store.PropertyType$9.getValue(PropertyType.java:213)
    at org.neo4j.kernel.impl.store.PropertyType$9.getValue(PropertyType.java:190)
    at org.neo4j.kernel.impl.transaction.state.NeoStoreIndexStoreView.nodeAsUpdates(NeoStoreIndexStoreView.java:210)
    at org.neo4j.kernel.impl.api.index.IndexingService$4.visited(IndexingService.java:580)
    at org.neo4j.collection.primitive.hopscotch.AbstractLongHopScotchCollection.visitKeys(AbstractLongHopScotchCollection.java:48)
    at org.neo4j.kernel.impl.api.index.IndexingService.readRecoveredUpdatesFromStore(IndexingService.java:575)
    at org.neo4j.kernel.impl.api.index.IndexingService.applyRecoveredUpdates(IndexingService.java:556)
    at org.neo4j.kernel.impl.api.index.IndexingService.start(IndexingService.java:253)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507)
    ... 22 more
```

**Comment by jexp** [comment]
I presume you try this on a backup. You could remove the existing transaction logs from that database.

The error occurs when it tries to recover those tx-logs.

**Comment by arikan** [comment]
Thanks Michael, 

After deleting the transaction logs and putting a try catch block for fault data, we were able to run it. 

However, the copied data worked well, until tried the create the Constraints. There was a repeating _id for two different nodes, whose _id should be unique. We checked the original data and find that this issue does not exist there. So most likely something happened during the store-utils copy...

Also we were not able to delete either of these nodes with the same _id:

```
org.neo4j.kernel.api.exceptions.TransactionFailureException: Node record Node[172917,used=false,rel=1002808,prop=-1,labels=Inline(0x0:[]),light] still has relationships
 Neo.DatabaseError.Transaction.CouldNotCommit
```

**Comment by arikan** [comment]
Also, we are trying store-utils in a more recent backup data, which freezes [on the line](https://github.com/graphcommons/store-utils/blob/22/src/main/java/org/neo4j/tool/StoreCopy.java#L96) `api.shutdown()` in `storecopy.java` 

Any idea why does it freeze here?

**Comment by arikan** [comment]
After stopping the neo4j and copying the data folder, the `api.shutdown` freeze is eliminated, it was something to do with the locks. Anyway, now the store-utils works fine. 

However, the constraint uniqe issue remains, somehow store-utils generates repeating _ids for the same node.

**Comment by jexp** [comment]
That's really weird would you be able to share your store with me? Just put it on dropbox and send me an personal email.

You should NEVER run this on a live db, only on a clean backup.

Michael

**Comment by jexp** [comment]
Hmm do you have an example for the source db-structure so that I could test it with store-utils?

Or share your pre-copied database with me personally so I can have a look michael at neo4j.com

Thanks

**Comment by rickardoberg** [comment]
@arikan I think I've found the issue, but want to confirm with you: did this happen after you took a backup, then used that backup in production? Or is it the production database that just went bad on its own?

**Comment by xiongjiezk** [comment]
I want to know when the broken node would come into being,how can I avoid it happen
