### ISSUE TITLE
[SOLVED] Problem compiling neo4j

### ISSUE THREAD

**Issue by alsoba13** [neo4j/neo4j#5068]
Hey team,
I'm doing a project with neo4j, and I need to tweak some lines of code.
I downloaded the github .zip in my mac and did the following steps:

> $ brew install graphviz libtool maven node.js
> $ npm install grunt-cli
> $ mvn clean install

In the Reactor Summary, I got this error:

```
[INFO] Neo4j - Graph Database Kernel ..................... FAILURE [1.267s]
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.13:revision (generate-git-hash) on project neo4j-kernel: .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
```

I set up an Ubuntu in VirtualBox and I got the same error:

```
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.13:revision (generate-git-hash) on project neo4j-kernel: .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.13:revision (generate-git-hash) on project neo4j-kernel: .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml
    at pl.project13.maven.git.GitCommitIdMojo.throwWhenRequiredDirectoryNotFound(GitCommitIdMojo.java:432)
    at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:337)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more
```

Is there something wrong with the neo4j .zip I downloaded?
Here is my java version in Ubuntu:

```
neo4j@neo4j-VirtualBox:~/Escriptori/neo4j-2.3$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK Client VM (build 24.79-b02, mixed mode, sharing)
```

Thanks in advance

**Comment by chrisvest** [comment]
You need a Git check-out, because the specific revision used for the build is recorded in the produced artefacts.

**Comment by alsoba13** [comment]
Thanks for the quick answer.

**Comment by alsoba13** [comment]
Thanks for the quick answer.
I'm new to repositories. Do you mean that there are some branches that can be build while the 2.3 branch can't? Which is the branch I need to do the check-out to?

edit: I managed to do it! Thank you!
