### ISSUE TITLE
Silently skip erroneous records while iterating through primitives.

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#5142]
This is similar to https://github.com/jexp/batch-import/issues/65.

Here's an excerpt from the log:

```
Caused by: org.neo4j.kernel.impl.store.InvalidRecordException: RelationshipRecord[227] not in use
    at org.neo4j.kernel.impl.store.RelationshipStore.fillRecord(RelationshipStore.java:145) ~[bochka-latest-jar-with-dependencies.jar:na]
    at org.neo4j.kernel.impl.api.StoreRelationshipIterable$DenseIterator.fetchNext(StoreRelationshipIterable.java:250) ~[bochka-latest-jar-with-dependencies.jar:na]
    at org.neo4j.collection.primitive.PrimitiveLongCollections$PrimitiveLongBaseIterator.hasNext(PrimitiveLongCollections.java:55) ~[bochka-latest-jar-with-dependencies.jar:na]
    at org.neo4j.kernel.impl.api.StateHandlingStatementOperations$RelationshipCursor.next(StateHandlingStatementOperations.java:972) ~[bochka-latest-jar-with-dependencies.jar:na]
    at org.neo4j.kernel.impl.core.RelationshipConversion.hasNext(RelationshipConversion.java:51) ~[bochka-latest-jar-with-dependencies.jar:na]
    at org.neo4j.kernel.impl.traversal.TraversalBranchImpl.next(TraversalBranchImpl.java:136) ~[bochka-latest-jar-with-dependencies.jar:na]
    at org.neo4j.kernel.impl.traversal.TraversalBranchWithState.next(TraversalBranchWithState.java:32) ~[bochka-latest-jar-with-dependencies.jar:na]
    at org.neo4j.graphdb.traversal.PreorderDepthFirstSelector.next(PreorderDepthFirstSelector.java:49) ~[bochka-latest-jar-with-dependencies.jar:na]
    at org.neo4j.kernel.impl.traversal.MonoDirectionalTraverserIterator.fetchNextOrNull(MonoDirectionalTraverserIterator.java:70) ~[bochka-latest-jar-with-dependencies.jar:na]
    at org.neo4j.kernel.impl.traversal.MonoDirectionalTraverserIterator.fetchNextOrNull(MonoDirectionalTraverserIterator.java:36) ~[bochka-latest-jar-with-dependencies.jar:na]
    at org.neo4j.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60) ~[bochka-latest-jar-with-dependencies.jar:na]
    at org.neo4j.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46) ~[bochka-latest-jar-with-dependencies.jar:na]
    at org.neo4j.kernel.impl.traversal.DefaultTraverser$ResourcePathIterableWrapper$1.fetchNextOrNull(DefaultTraverser.java:140) ~[bochka-latest-jar-with-dependencies.jar:na]
    at org.neo4j.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60) ~[bochka-latest-jar-with-dependencies.jar:na]
    at org.neo4j.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46) ~[bochka-latest-jar-with-dependencies.jar:na]
    at java.lang.Iterable.forEach(Iterable.java:74) ~[na:1.8.0_45]
```

Calling the same code again resulted in normal execution (no exceptions, integrity is preserved).

I'm not sure what's causing this, but in any case, wouldn't it be more convenient if those records were just skipped without failing the whole transaction?

**Comment by jexp** [comment]
From which blog?
Which Neo4j version?
What exactly did you run?
Can you run a consistency check on your store? http://www.markhneedham.com/blog/2014/01/22/neo4j-backup-store-copy-and-consistency-check/

**Comment by tkroman** [comment]
@jexp, this is a log of an embedded neo4j application. I did some traversal via the Traversal framework (the whole enclosing transaction is read-only). I don't have the storage files, but this very query succeeded the next time, so I believe, the storage was consistent.

**Comment by spacecowboy** [comment]
@tkroman is this still an issue? If so, could you please provide the details @jexp asked for? Otherwise there is nothing we can do.

**Comment by ehx-v1** [comment]
from what I get, question 3 is answered with Java API traversal, and question 4 is replied to with "not necessary as intuitively consistent", but answering question 1 (if you get it, I don't) and (most important I suppose) 2 is still necessary

**Comment by jjaderberg** [comment]
Over a year without response; closing.
