### ISSUE TITLE
[INFO] Neo4j - Communication Package ..................... FAILURE [1:16.977s]

### ISSUE THREAD

**Issue by dbl001** [neo4j/neo4j#5158]
I am running on an Amazon EC2 server with an Ubuntu 14.04.2 LTS kernel.
I've opened port 7474 for Neo4j.  Anything else I need to do?

Thanks!

Tests in error: 
  TestCommunication.internalProtocolVersionsMustMatchMultiJvm:255 » Runtime Coul...
  TestCommunication.communicateBetweenJvms:168 » Runtime Couldn't start server, ...
  TestCommunication.applicationProtocolVersionsMustMatchMultiJvm:218 » Runtime C...

Tests run: 44, Failures: 0, Errors: 3, Skipped: 0

---
##  T E S T S

Running org.neo4j.com.TestCommunication
Tests run: 21, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 64.733 sec <<< FAILURE! - in org.neo4j.com.TestCommunication
internalProtocolVersionsMustMatchMultiJvm(org.neo4j.com.TestCommunication)  Time elapsed: 20.44 sec  <<< ERROR!
java.lang.RuntimeException: Couldn't start server, wait timeout
    at org.neo4j.com.MadeUpServerProcess.awaitStarted(MadeUpServerProcess.java:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.neo4j.test.subprocess.SubProcess$DispatcherImpl.dispatch(SubProcess.java:1051)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322)
    at sun.rmi.transport.Transport$2.run(Transport.java:202)
    at sun.rmi.transport.Transport$2.run(Transport.java:199)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:198)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:567)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.access$400(TCPTransport.java:619)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$1.run(TCPTransport.java:684)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$1.run(TCPTransport.java:681)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:681)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:275)
    at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:252)
    at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
    at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:217)
    at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:171)
    at org.neo4j.test.subprocess.$Proxy8.dispatch(Unknown Source)
    at org.neo4j.test.subprocess.SubProcess$Handler.dispatch(SubProcess.java:1027)
    at org.neo4j.test.subprocess.SubProcess$Handler.invoke(SubProcess.java:998)
    at com.sun.proxy.$Proxy9.awaitStarted(Unknown Source)
    at org.neo4j.com.TestCommunication$Builder.serverInOtherJvm(TestCommunication.java:599)
    at org.neo4j.com.TestCommunication.internalProtocolVersionsMustMatchMultiJvm(TestCommunication.java:255)

communicateBetweenJvms(org.neo4j.com.TestCommunication)  Time elapsed: 20.294 sec  <<< ERROR!
java.lang.RuntimeException: Couldn't start server, wait timeout
    at org.neo4j.com.MadeUpServerProcess.awaitStarted(MadeUpServerProcess.java:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.neo4j.test.subprocess.SubProcess$DispatcherImpl.dispatch(SubProcess.java:1051)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322)
    at sun.rmi.transport.Transport$2.run(Transport.java:202)
    at sun.rmi.transport.Transport$2.run(Transport.java:199)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:198)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:567)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.access$400(TCPTransport.java:619)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$1.run(TCPTransport.java:684)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$1.run(TCPTransport.java:681)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:681)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:275)
    at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:252)
    at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
    at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:217)
    at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:171)
    at org.neo4j.test.subprocess.$Proxy8.dispatch(Unknown Source)
    at org.neo4j.test.subprocess.SubProcess$Handler.dispatch(SubProcess.java:1027)
    at org.neo4j.test.subprocess.SubProcess$Handler.invoke(SubProcess.java:998)
    at com.sun.proxy.$Proxy9.awaitStarted(Unknown Source)
    at org.neo4j.com.TestCommunication$Builder.serverInOtherJvm(TestCommunication.java:599)
    at org.neo4j.com.TestCommunication.communicateBetweenJvms(TestCommunication.java:168)

applicationProtocolVersionsMustMatchMultiJvm(org.neo4j.com.TestCommunication)  Time elapsed: 20.294 sec  <<< ERROR!
java.lang.RuntimeException: Couldn't start server, wait timeout
    at org.neo4j.com.MadeUpServerProcess.awaitStarted(MadeUpServerProcess.java:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.neo4j.test.subprocess.SubProcess$DispatcherImpl.dispatch(SubProcess.java:1051)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322)
    at sun.rmi.transport.Transport$2.run(Transport.java:202)
    at sun.rmi.transport.Transport$2.run(Transport.java:199)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:198)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:567)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.access$400(TCPTransport.java:619)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$1.run(TCPTransport.java:684)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$1.run(TCPTransport.java:681)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:681)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:275)
    at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:252)
    at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
    at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:217)
    at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:171)
    at org.neo4j.test.subprocess.$Proxy8.dispatch(Unknown Source)
    at org.neo4j.test.subprocess.SubProcess$Handler.dispatch(SubProcess.java:1027)
    at org.neo4j.test.subprocess.SubProcess$Handler.invoke(SubProcess.java:998)
    at com.sun.proxy.$Proxy9.awaitStarted(Unknown Source)
    at org.neo4j.com.TestCommunication$Builder.serverInOtherJvm(TestCommunication.java:599)
    at org.neo4j.com.TestCommunication.applicationProtocolVersionsMustMatchMultiJvm(TestCommunication.java:218)

Running org.neo4j.com.TestSlaveContext
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in org.neo4j.com.TestSlaveContext
Running org.neo4j.com.storecopy.StoreCopyClientTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.845 sec - in org.neo4j.com.storecopy.StoreCopyClientTest
Running org.neo4j.com.storecopy.TransactionCommittingResponseUnpackerTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.195 sec - in org.neo4j.com.storecopy.TransactionCommittingResponseUnpackerTest
Running org.neo4j.com.storecopy.ResponsePackerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.neo4j.com.storecopy.ResponsePackerTest
Running org.neo4j.com.LoggingResourcePoolMonitorTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec - in org.neo4j.com.LoggingResourcePoolMonitorTest
Running org.neo4j.com.ProtocolTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.neo4j.com.ProtocolTest
Running org.neo4j.com.ResourcePoolTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.565 sec - in org.neo4j.com.ResourcePoolTest
Running org.neo4j.com.ServerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.045 sec - in org.neo4j.com.ServerTest

Results :

Tests in error: 
  TestCommunication.internalProtocolVersionsMustMatchMultiJvm:255 » Runtime Coul...
  TestCommunication.communicateBetweenJvms:168 » Runtime Couldn't start server, ...
  TestCommunication.applicationProtocolVersionsMustMatchMultiJvm:218 » Runtime C...

Tests run: 44, Failures: 0, Errors: 3, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Neo4j - Communication Package ..................... FAILURE [1:16.977s]
[INFO] Neo4j - Clustering Infrastructure ................. SKIPPED
[INFO] Neo4j - Backup Tool ............................... SKIPPED
[INFO] Neo4j - High Availability ......................... SKIPPED
[INFO] Neo4j - Enterprise ................................ SKIPPED
[INFO] Neo4j - Enterprise Server ......................... SKIPPED
[INFO] Neo4j - Enterprise Performance Tests .............. SKIPPED
[INFO] Neo4j - Enterprise Build .......................... SKIPPED
[INFO] Neo4j - Integration Tests ......................... SKIPPED
[INFO] Neo4j - Stress Tests .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:22.385s
[INFO] Finished at: Sun Aug 16 18:01:04 UTC 2015
[INFO] Final Memory: 35M/289M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test (default-test) on project neo4j-com: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/ubuntu/neo4j/enterprise/com/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
ubuntu@ip-10-0-1-195:~/neo4j$ 
ubuntu@ip-10-0-1-195:~/neo4j$

**Comment by jexp** [comment]
What was the build command you ran?

Which version/branch did you build?

**Comment by spacecowboy** [comment]
Closing since reporter did not respond.
