### ISSUE TITLE
Logical log[/apps/UCA-EBC/var/instances/default/neo4j/nioneo_logical.log.1] not found

### ISSUE THREAD

**Issue by wuzhen0808** [neo4j/neo4j#5272]
Any idea for this issue. Neo4j not work after this exception and it was OK after restart.

The information in messages.log:

2015-08-26 08:20:16.589+0000 ERROR [org.neo4j]: setting TM not OK null
javax.transaction.xa.XAException
    at org.neo4j.kernel.impl.transaction.TransactionImpl.doCommit(TransactionImpl.java:581)
    at org.neo4j.kernel.impl.transaction.TxManager.commit(TxManager.java:398)
    at org.neo4j.kernel.impl.transaction.TxManager.commit(TxManager.java:351)
    at org.neo4j.kernel.impl.transaction.TransactionImpl.commit(TransactionImpl.java:131)
    at org.neo4j.kernel.TopLevelTransaction.finish(TopLevelTransaction.java:127)
    at org.neo4j.loader.csv.CsvFile$$anonfun$loadInDb$2.apply(CsvFile.scala:125)
    at org.neo4j.loader.csv.CsvFile$$anonfun$loadInDb$2.apply(CsvFile.scala:119)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1156)
    at org.neo4j.loader.csv.CsvFile.loadInDb(CsvFile.scala:119)
    at org.neo4j.loader.csv.CsvFile.timedLoad(CsvFile.scala:83)
    at org.neo4j.loader.csv.FileManager.loadFile(FileManager.scala:97)
    at org.neo4j.loader.csv.FileManager$$anonfun$loadFiles$2.apply(FileManager.scala:92)
    at org.neo4j.loader.csv.FileManager$$anonfun$loadFiles$2.apply(FileManager.scala:92)
    at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:722)
    at scala.collection.immutable.List.foreach(List.scala:309)
    at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:721)
    at org.neo4j.loader.csv.FileManager.loadFiles(FileManager.scala:92)
    at org.neo4j.loader.csv.FileManager.loadNodeFiles(FileManager.scala:100)
    at org.neo4j.loader.csv.Loader.insertNodes(Loader.scala:15)
    at org.neo4j.loader.csv.Loader.loadAll(Loader.scala:30)
    at org.neo4j.loader.csv.plugin.Runner$.doLoad(Runner.scala:30)
    at org.neo4j.loader.csv.plugin.LoadCsv.loadAll(LoadCsv.scala:24)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.neo4j.server.plugins.PluginMethod.invoke(PluginMethod.java:57)
    at org.neo4j.server.plugins.PluginManager.invoke(PluginManager.java:168)
    at org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:300)
    at org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:122)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.neo4j.server.rest.security.SecurityFilter.doFilter(SecurityFilter.java:112)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: org.neo4j.graphdb.TransactionFailureException: Unable to write command to logical log.
    at org.neo4j.kernel.impl.transaction.xaframework.XaTransaction.addCommand(XaTransaction.java:249)
    at org.neo4j.kernel.impl.nioneo.xa.WriteTransaction.doPrepare(WriteTransaction.java:218)
    at org.neo4j.kernel.impl.transaction.xaframework.XaTransaction.prepare(XaTransaction.java:302)
    at org.neo4j.kernel.impl.transaction.xaframework.XaResourceManager.commit(XaResourceManager.java:453)
    at org.neo4j.kernel.impl.transaction.xaframework.XaResourceHelpImpl.commit(XaResourceHelpImpl.java:64)
    at org.neo4j.kernel.impl.transaction.TransactionImpl.doCommit(TransactionImpl.java:575)
    ... 67 more
Caused by: java.io.IOException: Logical log[/apps/UCA-EBC/var/instances/default/neo4j/nioneo_logical.log.1] not found
    at org.neo4j.kernel.impl.transaction.xaframework.XaLogicalLog.renameLogFileToRightVersion(XaLogicalLog.java:651)
    at org.neo4j.kernel.impl.transaction.xaframework.XaLogicalLog.rotate(XaLogicalLog.java:1411)
    at org.neo4j.kernel.impl.transaction.xaframework.XaLogicalLog.checkLogRotation(XaLogicalLog.java:604)
    at org.neo4j.kernel.impl.transaction.xaframework.XaLogicalLog.writeCommand(XaLogicalLog.java:422)
    at org.neo4j.kernel.impl.transaction.xaframework.XaTransaction.addCommand(XaTransaction.java:245)
    ... 72 more

**Comment by jexp** [comment]
Did you check things like disk space? Anything else that happens on the filesystem? Like copying files from the Neo4j store?

Which version of Neo4j do you use?

Where is this class from ? `org.neo4j.loader.csv.plugin.LoadCsv`

**Comment by jexp** [comment]
@wuzhen0808 Please respond, otherwise I have to close the issue due to lack of information.

**Comment by jakewins** [comment]
As per above, closing this pending more info, please don't hesitate to reopen if the issue remains.

Overall though: XAException does not exist in recent versions of Neo4j, and we've completely overhauled the transaction log management. If you upgrade to the latest version of Neo4j, this should no longer be an issue.
