### ISSUE TITLE
InvalidRecordException while traversing relationships

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#5542]
Encountered this while our app was running tests. 

```
org.neo4j.kernel.impl.store.InvalidRecordException: While loading relationships for Node[2] a Relationship[942038] was encountered that had startNode: 477342 and endNode: 668973, i.e. which had neither start nor end node as the node we're loading relationships for
at org.neo4j.kernel.impl.api.store.StoreNodeRelationshipCursor.next(StoreNodeRelationshipCursor.java:172) ~[bochka-latest-jar-with-dependencies.jar:na]
at org.neo4j.kernel.impl.api.store.CursorRelationshipIterator.nextCursor(CursorRelationshipIterator.java:52) ~[bochka-latest-jar-with-dependencies.jar:na]
at org.neo4j.kernel.impl.api.store.CursorRelationshipIterator.<init>(CursorRelationshipIterator.java:45) ~[bochka-latest-jar-with-dependencies.jar:na]
at org.neo4j.kernel.api.cursor.NodeItem$NodeItemHelper.getRelationships(NodeItem.java:81) ~[bochka-latest-jar-with-dependencies.jar:na]
at org.neo4j.kernel.impl.api.OperationsFacade.nodeGetRelationships(OperationsFacade.java:319) ~[bochka-latest-jar-with-dependencies.jar:na]
at org.neo4j.kernel.impl.core.NodeProxy$2.iterator(NodeProxy.java:201) ~[bochka-latest-jar-with-dependencies.jar:na]
at org.neo4j.kernel.impl.core.NodeProxy$2.iterator(NodeProxy.java:193) ~[bochka-latest-jar-with-dependencies.jar:na]
...
```

As I understand, this is quite weird. Are there any ways I could provide you with more information?

**Comment by tinwelint** [comment]
Was this a temporary condition or is it still the case? If I could get my hands on the database including all transaction logs I could try and do a root cause analysis on it. That would be most helpful.

**Comment by tkroman** [comment]
@tinwelint, the database size is some ~15-17GB, so that's not an easy task.
Since the time this bug first appeared I learned that the test server running that instance has been rebooted a couple times, so that might be just the storage corruption. 
I'll try to upload at least more important files or maybe reproduce this with a smaller data set on weekend.

**Comment by tinwelint** [comment]
Any progress?

**Comment by jakewins** [comment]
Since it's been a month with no update, tentatively closing this pending more information - @tkroman please simply reopen this ticket when you're able to provide more detailed debugging information as per @tinwelint above.

**Comment by dosumis** [comment]
I have encountered a similar issue (using neo4J 3.0)

$MATCH p=()-[r:Related]->() RETURN p LIMIT 25 
=>
While loading relationships for Node[364] a Relationship[185403] was encountered that had startNode: -1 and endNode: -1, i.e. which had neither start nor end node as the node we're loading relationships for

Perhaps not surprisingly
$MATCH (s)-[r]-(z) WHERE ID(r) = 185403 return r
=> no rows

So, no obvious way to match and delete the offending relationship.

Would a zip of the DB help?

**Comment by tinwelint** [comment]
@dosumis yes having access to the db always helps and has a potential to uncovered a bug somewhere.

**Comment by lazdmx** [comment]
Same issue:

```
While loading relationships for Node[24] a Relationship[0] was encountered that had startNode: 12 
and endNode: 75, i.e. which had neither start nor end node as the node we're loading relationships 
for
```

Cypher:

`MATCH (n) OPTIONAL MATCH (n)-[r]-() DELETE n, r`

DBVer: 3.0.3

**Comment by lazdmx** [comment]
@tinwelint there is a sample db ([graph.db.zip](https://github.com/neo4j/neo4j/files/368695/graph.db.zip)) which allow you to reproduce an error. Easiest way is to run `MATCH (n) OPTIONAL MATCH (n)-[r]-() DELETE n, r`

**Comment by lazdmx** [comment]
any progress on this issue? It is very uncomfortable to know that db may become unworkable just after regular start/stop operations.

**Comment by tinwelint** [comment]
I'm looking at it right now, and thanks for the database, although it's lacking the `debug.log` which would contain information about restarts and some state at every startup which could give some more clues. It's difficult w/o it.

**Comment by tinwelint** [comment]
There seems to be some issue with handling of free ids, did you have only clean shutdowns during your testing?

**Comment by codyAnivive** [comment]
I have encountered a similar issue, here is the debug.log stack trace related to the issue

```
2017-11-20 16:04:53.644+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: Node 292317 neither start nor end node of Relationship[161303805,used=false,source=0,target=0,type=0,sPrev=0,sNext=0,tPrev=0,tNext=0,prop=0,secondaryUnitId=-1,!sFirst,!tFirst], reference 41b5ce17-0d69-444e-9493-3fb197ec664c. Node 292317 neither start
org.neo4j.kernel.impl.store.InvalidRecordException: Node 292317 neither start nor end node of Relationship[161303805,used=false,source=0,target=0,type=0,sPrev=0,sNext=0,tPrev=0,tNext=0,prop=0,secondaryUnitId=-1,!sFirst,!tFirst]
        at org.neo4j.kernel.impl.api.store.DegreeCounter.countByFirstPrevPointer(DegreeCounter.java:54)
        at org.neo4j.kernel.impl.api.store.DegreeCounter.nodeDegreeByDirection(DegreeCounter.java:89)
        at org.neo4j.kernel.impl.api.store.DegreeCounter.countRelationshipsInGroup(DegreeCounter.java:66)
        at org.neo4j.kernel.impl.api.store.StorageLayer.degreeRelationshipsInGroup(StorageLayer.java:589)
        at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.computeDegree(StateHandlingStatementOperations.java:1781)
        at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.degree(StateHandlingStatementOperations.java:1769)
        at org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.degree(ConstraintEnforcingEntityOperations.java:664)
        at org.neo4j.kernel.impl.api.OperationsFacade.nodeGetDegree(OperationsFacade.java:344)
        at org.neo4j.cypher.internal.spi.v3_3.TransactionBoundQueryContext.nodeGetDegree(TransactionBoundQueryContext.scala:322)
        at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext$$anonfun$nodeGetDegree$2.apply$mcI$sp(ExceptionTranslatingQueryContext.scala:120)
        at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext$$anonfun$nodeGetDegree$2.apply(ExceptionTranslatingQueryContext.scala:120)
        at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext$$anonfun$nodeGetDegree$2.apply(ExceptionTranslatingQueryContext.scala:120)
        at org.neo4j.cypher.internal.spi.v3_3.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:32)
        at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:39)
        at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext.nodeGetDegree(ExceptionTranslatingQueryContext.scala:120)
        at org.neo4j.cypher.internal.spi.v3_3.DelegatingQueryContext.nodeGetDegree(DelegatingQueryContext.scala:180)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.CachingExpandInto$$anonfun$getDegree$2.apply(CachingExpandInto.scala:115)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.CachingExpandInto$$anonfun$getDegree$2.apply(CachingExpandInto.scala:113)
        at scala.Option.map(Option.scala:146)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.CachingExpandInto$class.getDegree(CachingExpandInto.scala:113)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.CachingExpandInto$class.findRelationships(CachingExpandInto.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.ExpandIntoPipe.findRelationships(ExpandIntoPipe.scala:38)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.ExpandIntoPipe$$anonfun$internalCreateResults$1$$anonfun$1.apply(ExpandIntoPipe.scala:64)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.ExpandIntoPipe$$anonfun$internalCreateResults$1$$anonfun$1.apply(ExpandIntoPipe.scala:64)
        at scala.Option.getOrElse(Option.scala:121)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.ExpandIntoPipe$$anonfun$internalCreateResults$1.apply(ExpandIntoPipe.scala:64)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.ExpandIntoPipe$$anonfun$internalCreateResults$1.apply(ExpandIntoPipe.scala:54)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
        at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:732)
        at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:708)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
        at scala.collection.AbstractIterator.to(Iterator.scala:1334)
        at scala.collection.TraversableOnce$class.toIndexedSeq(TraversableOnce.scala:300)
        at scala.collection.AbstractIterator.toIndexedSeq(Iterator.scala:1334)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.EagerPipe.internalCreateResults(EagerPipe.scala:29)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:62)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.createResults(DefaultExecutionResultBuilderFactory.scala:102)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:74)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.BuildInterpretedExecutionPlan$$anonfun$getExecutionPlanFunction$1.apply(BuildInterpretedExecutionPlan.scala:111)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.BuildInterpretedExecutionPlan$$anonfun$getExecutionPlanFunction$1.apply(BuildInterpretedExecutionPlan.scala:94)
        at org.neo4j.cypher.internal.compatibility.v3_3.runtime.BuildInterpretedExecutionPlan$$anon$1.run(BuildInterpretedExecutionPlan.scala:62)
        at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(Compatibility.scala:182)
        at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(Compatibility.scala:178)
        at org.neo4j.cypher.internal.compatibility.v3_3.exceptionHandler$runSafely$.apply(exceptionHandler.scala:90)
        at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$ExecutionPlanWrapper.run(Compatibility.scala:178)
        at org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:29)
        at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:116)
        at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:62)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachineSPI$1.start(TransactionStateMachineSPI.java:146)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$2.run(TransactionStateMachine.java:285)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:77)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$2.run(BoltStateMachine.java:398)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.run(BoltStateMachine.java:200)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onRun$3(BoltMessageRouter.java:93)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:134)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:91)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
        at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)
```

**Comment by dsevero** [comment]
Just got a similar error:

`While loading relationships for Node[79] a Relationship[414474] was encountered that had startNode: 0 and endNode: 0, i.e. which had neither start nor end node as the node we're loading relationships for`

query: 

```cql
MATCH p=({id: $id})-[r]->() RETURN p
```

**Comment by jakewins** [comment]
@daniel-severo while the error message is similar, ~~that is likely a different issue than this ticket. Would you mind opening a separate ticket, and include~~ Edit: Scratch that, you were totally right to add that note here. Could you please provide the following info to help further this ticket along:

- OS version (`uname -a` if you're on linux)
- JVM version (java -version)
- Output from running the Neo4j Consistency Checker (`neo4j-admin check-consistency`, see https://neo4j.com/docs/operations-manual/current/tools/consistency-checker/)

**Comment by jakewins** [comment]
@daniel-severo actually, I'm wrong, sorry - there's no reason to think your issue has a different cause, I'd forgotten the background to this ticket; don't open a new ticket. If you could supply the info here from the bullet list above it'd be super helpful,.

**Comment by dsevero** [comment]
```
> uname -a
Linux shannon 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

> java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

Found something strange that I will investigate:

```
> docker exec recsys bin/neo4j-admin check-consistency
2018-02-08 20:13:26.128+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Unable to read store format: Externally locked: /data/databases/graph.db/neostore
unexpected error: org.neo4j.io.pagecache.impl.FileLockException: Externally locked: /data/databases/graph.db/neostore
```

But when I run

```
> docker exec recsys bin/neo4j status
Neo4j is not running
```

Also, there were a few inconsistency reports in the docker workspace, the latest being [inconsistencies-2018-02-08.20.11.00.report](https://gist.githubusercontent.com/daniel-severo/6c1ddf213ec8ce1aa9d7ca6d39948c6d/raw/dee51c73206a5cfbc113bccbd3515b49cc6c3d3a/inconsistencies-2018-02-08.20.11.00.report)

**Comment by chrisvest** [comment]
I'm closing this because I believe the original issue was about not handling concurrently deleted records at runtime, and then another issue was mentioned about free id reuse being buggy. We've fixed bugs in both of these areas.

@daniel-severo You problem is an inconsistent store, and the inconsistencies cause exceptions to pop up that look like the other exceptions in this thread. However, the underlying cause is the inconsistencies, so I don't think it's relevant to this particular thread. If you still have this problem, then you can try running @jexp's store-copy tool on your database: https://github.com/jexp/store-utils — it'll copy the consistent parts of your data to a new store, leaving the inconsistencies behind. I think that's the best way work around store inconsistencies for those who don't have a support contract. If you find an exception in your `debug.log` that you believe might be the original cause of the inconsistencies, then please open a separate issue with that.
