### ISSUE TITLE
"Not supported a.t.m" when importing CSV with neo4j-import

### ISSUE THREAD

**Issue by cosimosimeoneTR** [neo4j/neo4j#5620]
Hi there!!!
Given those very very stupid CSVs

```
==> companies.csv <==
companyId:ID(Company),:LABEL,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
0,Cmp_0,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
1,Cmp_1,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
2,Cmp_2,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
3,Cmp_3,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
4,Cmp_4,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
5,Cmp_5,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
6,Cmp_6,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
7,Cmp_7,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
8,Cmp_8,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
[...]

==> companiesproducts.csv <==
:START_ID(Company),:END_ID(product),:TYPE,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
0,233719,PRODUCES,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
1,5467,PRODUCES,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
2,121301,PRODUCES,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
3,143568,PRODUCES,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
4,104787,PRODUCES,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
5,134018,PRODUCES,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
6,58676,PRODUCES,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
7,197679,PRODUCES,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
8,190304,PRODUCES,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
[...]

==> products.csv <==
productId:ID(product),:LABEL,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
0,Drg_0,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
1,Drg_1,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
2,Drg_2,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
3,Drg_3,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
4,Drg_4,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
5,Drg_5,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
6,Drg_6,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
7,Drg_7,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
8,Drg_8,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
[...]
```

I receive 

```
2015-10-13 16:51:11.525+0000 INFO  [org.neo4j]: Import starting
2015-10-13 16:51:11.585+0000 INFO  [org.neo4j]: Creating new db @ /tmp/load-test/neostore
2015-10-13 16:51:11.942+0000 WARN  [org.neo4j]: Missing counts store, rebuilding it.
2015-10-13 16:51:28.112+0000 INFO  [org.neo4j]: About to rotate counts store at transaction 1 to [/tmp/load-test/neostore.counts.db.b], from [/tmp/load-test/neostore.counts.db.a].
2015-10-13 16:51:28.906+0000 INFO  [org.neo4j]: Successfully rotated counts store at transaction 1 to [/tmp/load-test/neostore.counts.db.b], from [/tmp/load-test/neostore.counts.db.a].
2015-10-13 16:51:32.772+0000 ERROR [org.neo4j]: Error during import Executor has been shut down
java.lang.IllegalStateException: Executor has been shut down
        at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.assertHealthy(DynamicTaskExecutor.java:153)
        at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.submit(DynamicTaskExecutor.java:138)
        at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.receive(ProcessorStep.java:101)
        at org.neo4j.unsafe.impl.batchimport.staging.ProducerStep.process(ProducerStep.java:77)
        at org.neo4j.unsafe.impl.batchimport.staging.ProducerStep$1.run(ProducerStep.java:54)
Caused by: java.lang.UnsupportedOperationException: Not supported a.t.m
        at org.neo4j.unsafe.impl.batchimport.Utils.safeCastLongToInt(Utils.java:36)
        at org.neo4j.unsafe.impl.batchimport.cache.NumberArrayFactory$1.newLongArray(NumberArrayFactory.java:98)
        at org.neo4j.unsafe.impl.batchimport.cache.NumberArrayFactory$Auto.newLongArray(NumberArrayFactory.java:154)
        at org.neo4j.unsafe.impl.batchimport.RelationshipCountsProcessor.<init>(RelationshipCountsProcessor.java:60)
        at org.neo4j.unsafe.impl.batchimport.ProcessRelationshipCountsDataStep.processor(ProcessRelationshipCountsDataStep.java:73)
        at org.neo4j.unsafe.impl.batchimport.ProcessRelationshipCountsDataStep.process(ProcessRelationshipCountsDataStep.java:60)
        at org.neo4j.unsafe.impl.batchimport.ProcessRelationshipCountsDataStep.process(ProcessRelationshipCountsDataStep.java:36)
        at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep$4.run(ProcessorStep.java:120)
        at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep$4.run(ProcessorStep.java:102)
        at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:237)
2015-10-13 16:57:13.419+0000 INFO  [org.neo4j]: Import starting
2015-10-13 16:57:13.480+0000 INFO  [org.neo4j]: Creating new db @ /tmp/load-test/neostore
2015-10-13 16:57:13.797+0000 WARN  [org.neo4j]: Missing counts store, rebuilding it.
2015-10-13 16:57:30.309+0000 INFO  [org.neo4j]: About to rotate counts store at transaction 1 to [/tmp/load-test/neostore.counts.db.b], from [/tmp/load-test/neostore.counts.db.a].
2015-10-13 16:57:31.101+0000 INFO  [org.neo4j]: Successfully rotated counts store at transaction 1 to [/tmp/load-test/neostore.counts.db.b], from [/tmp/load-test/neostore.counts.db.a].
2015-10-13 16:57:35.122+0000 ERROR [org.neo4j]: Error during import Executor has been shut down
java.lang.IllegalStateException: Executor has been shut down
        at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.assertHealthy(DynamicTaskExecutor.java:153)
        at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.submit(DynamicTaskExecutor.java:138)
        at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.receive(ProcessorStep.java:101)
        at org.neo4j.unsafe.impl.batchimport.staging.ProducerStep.process(ProducerStep.java:77)
        at org.neo4j.unsafe.impl.batchimport.staging.ProducerStep$1.run(ProducerStep.java:54)
Caused by: java.lang.UnsupportedOperationException: Not supported a.t.m
        at org.neo4j.unsafe.impl.batchimport.Utils.safeCastLongToInt(Utils.java:36)
        at org.neo4j.unsafe.impl.batchimport.cache.NumberArrayFactory$1.newLongArray(NumberArrayFactory.java:98)
        at org.neo4j.unsafe.impl.batchimport.cache.NumberArrayFactory$Auto.newLongArray(NumberArrayFactory.java:154)
        at org.neo4j.unsafe.impl.batchimport.RelationshipCountsProcessor.<init>(RelationshipCountsProcessor.java:60)
        at org.neo4j.unsafe.impl.batchimport.ProcessRelationshipCountsDataStep.processor(ProcessRelationshipCountsDataStep.java:73)
        at org.neo4j.unsafe.impl.batchimport.ProcessRelationshipCountsDataStep.process(ProcessRelationshipCountsDataStep.java:60)
        at org.neo4j.unsafe.impl.batchimport.ProcessRelationshipCountsDataStep.process(ProcessRelationshipCountsDataStep.java:36)
        at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep$4.run(ProcessorStep.java:120)
        at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep$4.run(ProcessorStep.java:102)
        at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:237)
```

Useful details:

```
admin@ip-172-31-18-192 ~
16:59:01$ uname -a
Linux ip-172-31-18-192 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux

admin@ip-172-31-18-192 ~
16:59:04$ less /etc/debian_version

admin@ip-172-31-18-192 ~
16:59:09$ cat /etc/debian_version
8.2

admin@ip-172-31-18-192 ~
16:59:13$ uname -a
Linux ip-172-31-18-192 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux

admin@ip-172-31-18-192 ~
16:59:14$ dpkg -l neo4j
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                          Version                             Architecture                        Description
+++-=============================================================-===================================-===================================-================================================================================================================================
ii  neo4j                                                         2.2.5                               all                                 graph database server

admin@ip-172-31-18-192 ~
16:59:29$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

```

Where am i doing wrong? :-)

**Comment by jexp** [comment]
What is the actual call that you execute.
How long are your CSVs?

Also how many different labels and rel-types do they contain?

**Comment by cosimosimeoneTR** [comment]
Hi there!
I attach you a "screenshot" of all i did
(sorry, cannot attach file)

```
admin@ip-172-31-20-91 ~
07:07:16$ wc -l DONTBACKUP/*csv
    1002 DONTBACKUP/companies.csv
  250001 DONTBACKUP/companiesdrugs.csv
  250002 DONTBACKUP/drugs.csv
  501005 total

admin@ip-172-31-20-91 ~
07:07:19$ head -3 DONTBACKUP/*csv
==> DONTBACKUP/companies.csv <==
id:ID(Company),:LABEL,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
0,Cmp_0,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
1,Cmp_1,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9

==> DONTBACKUP/companiesdrugs.csv <==
:START_ID(Company),:END_ID(Drug),:TYPE,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
1000,0,PRODUCES,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
1000,1,PRODUCES,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9

==> DONTBACKUP/drugs.csv <==
id:ID(Drug),:LABEL,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
0,Drg_0,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
1,Drg_1,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9

admin@ip-172-31-20-91 ~
07:07:26$ grep org.neo4j.server.database.location /etc/neo4j/neo4j-server.properties
org.neo4j.server.database.location=data/graph.db


admin@ip-172-31-20-91 ~
07:08:32$ cat neo4jPartialImport.sh
rm -rf DONTBACKUP/load-test && \
time neo4j-import --into DONTBACKUP/load-test --id-type INTEGER \
  --nodes DONTBACKUP/companies.csv --nodes DONTBACKUP/drugs.csv \
  --relationships DONTBACKUP/companiesdrugs.csv

admin@ip-172-31-20-91 ~
07:08:38$ ./neo4jPartialImport.sh
Importing the contents of these files into DONTBACKUP/load-test:
Nodes:
  /home/admin/DONTBACKUP/companies.csv

  /home/admin/DONTBACKUP/drugs.csv
Relationships:
  /home/admin/DONTBACKUP/companiesdrugs.csv

Available memory:
  Free machine memory: 117.50 GB
  Max heap memory : 26.52 GB

Nodes
[>:??------|PROPERTIE|NODE|*LABEL SCAN----------------------------------------------|v:15.50 MB]260k
Done in 4s 42ms
Prepare node index
[*DETECT:8.59 MB-------------------------------------------------------------------------------]250k
Done in 194ms
Calculate dense nodes
[*>:??--------------------------------------------------------|PREPARE(3)================|CALCU]320k
Done in 377ms
Relationships
[>:22.57 MB/s---------------|PREPARE-------------------|*PROPERTIES------------------|RE|v:49.0]250k
Done in 1s 556ms
Node --> Relationship
[*>:??------------------------------------------|LINK-------------------|v:??------------------]260k
Done in 71ms
Relationship --> Relationship
[>:??---------------------------|*LINK-----------------------------------------|v:??-----------]250k
Done in 112ms
Node counts
[*COUNT:76.29 MB-------------------------------------------------------------------------------]260k
Done in 7s 349ms
Relationship counts
[*>:??-----------------------------------------------------------------------------------------]   0Import error: Executor has been shut down


real    0m45.379s
user    0m38.052s
sys     0m2.424s

admin@ip-172-31-20-91 ~
07:09:34$ cat DONTBACKUP/load-test/messages.log
2015-10-14 07:08:49.061+0000 INFO  [org.neo4j]: Import starting
2015-10-14 07:08:49.121+0000 INFO  [org.neo4j]: Creating new db @ /home/admin/DONTBACKUP/load-test/neostore
2015-10-14 07:08:49.640+0000 WARN  [org.neo4j]: Missing counts store, rebuilding it.
2015-10-14 07:08:49.785+0000 INFO  [org.neo4j]: No lucene scan store index found, this might just be first use. Preparing to rebuild.
2015-10-14 07:08:49.807+0000 INFO  [org.neo4j]: No lucene scan store index found, this might just be first use. Preparing to rebuild.
2015-10-14 07:08:49.925+0000 INFO  [org.neo4j]: Rebuilding lucene scan store, this may take a while
2015-10-14 07:08:49.926+0000 INFO  [org.neo4j]: Lucene scan store rebuilt (roughly -1 nodes)
2015-10-14 07:09:05.421+0000 INFO  [org.neo4j]: About to rotate counts store at transaction 1 to [/home/admin/DONTBACKUP/load-test/neostore.counts.db.b], from [/home/admin/DONTBACKUP/load-test/neostore.counts.db.a].
2015-10-14 07:09:06.254+0000 INFO  [org.neo4j]: Successfully rotated counts store at transaction 1 to [/home/admin/DONTBACKUP/load-test/neostore.counts.db.b], from [/home/admin/DONTBACKUP/load-test/neostore.counts.db.a].
2015-10-14 07:09:33.938+0000 ERROR [org.neo4j]: Error during import Executor has been shut down
java.lang.IllegalStateException: Executor has been shut down
        at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.assertHealthy(DynamicTaskExecutor.java:153)
        at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.submit(DynamicTaskExecutor.java:138)
        at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.receive(ProcessorStep.java:101)
        at org.neo4j.unsafe.impl.batchimport.staging.ProducerStep.process(ProducerStep.java:77)
        at org.neo4j.unsafe.impl.batchimport.staging.ProducerStep$1.run(ProducerStep.java:54)
Caused by: java.lang.UnsupportedOperationException: Not supported a.t.m
        at org.neo4j.unsafe.impl.batchimport.Utils.safeCastLongToInt(Utils.java:36)
        at org.neo4j.unsafe.impl.batchimport.cache.NumberArrayFactory$1.newLongArray(NumberArrayFactory.java:98)
        at org.neo4j.unsafe.impl.batchimport.cache.NumberArrayFactory$Auto.newLongArray(NumberArrayFactory.java:154)
        at org.neo4j.unsafe.impl.batchimport.RelationshipCountsProcessor.<init>(RelationshipCountsProcessor.java:60)
        at org.neo4j.unsafe.impl.batchimport.ProcessRelationshipCountsDataStep.processor(ProcessRelationshipCountsDataStep.java:73)
        at org.neo4j.unsafe.impl.batchimport.ProcessRelationshipCountsDataStep.process(ProcessRelationshipCountsDataStep.java:60)
        at org.neo4j.unsafe.impl.batchimport.ProcessRelationshipCountsDataStep.process(ProcessRelationshipCountsDataStep.java:36)
        at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep$4.run(ProcessorStep.java:120)
        at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep$4.run(ProcessorStep.java:102)
        at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:237)

admin@ip-172-31-20-91 ~
07:10:12$ sudo service neo4j status
? neo4j-service.service - LSB: Neo4j Graph Database server
   Loaded: loaded (/etc/init.d/neo4j-service)
   Active: active (running) since Wed 2015-10-14 07:06:52 UTC; 3min 40s ago
  Process: 490 ExecStart=/etc/init.d/neo4j-service start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/neo4j-service.service
           +-649 /usr/bin/java -cp /var/lib/neo4j/lib/concurrentlinkedhashmap-lru-1.4.jar:/var/lib/neo4j/lib/lucene-core-3.6.2.jar:/var/lib/neo4j/lib/neo4j-consistency-check-2.2.5.jar:/var/lib/neo4j/lib/neo4j-csv-2.2.5.jar:/var/lib/neo4j/lib/neo4j-cypher-2.2.5.jar:/va...

Oct 14 07:05:30 ip-172-31-20-91 neo4j-service[490]: WARNING: Max 1024 open files allowed, minimum of 40 000 recommended. See the Neo4j manual.
Oct 14 07:05:39 ip-172-31-20-91 neo4j-service[490]: Starting Neo4j Server...WARNING: not changing user
Oct 14 07:06:52 ip-172-31-20-91 neo4j-service[490]: process [649]... waiting for server to be ready.......................................................................... OK.
Oct 14 07:06:52 ip-172-31-20-91 neo4j-service[490]: http://localhost:7474/ is ready.
Oct 14 07:06:52 ip-172-31-20-91 systemd[1]: Started LSB: Neo4j Graph Database server.

```

**Comment by spacecowboy** [comment]
@cosimosimeoneTR Can you say how many relationships are in your csv file? Or simply the number of lines in each file?

**Comment by cosimosimeoneTR** [comment]
P.s.: just to let you know that with the very same approach, with 

```
admin@ip-172-31-20-91 ~
07:49:08$ wc -l DONTBACKUP/*csv
   1000 DONTBACKUP/companies.csv
  25000 DONTBACKUP/companiesdrugs.csv
  25000 DONTBACKUP/drugs.csv
  51000 total
```

it worked

```
Importing the contents of these files into DONTBACKUP/load-test:
Nodes:
  /home/admin/DONTBACKUP/companies.csv

  /home/admin/DONTBACKUP/drugs.csv
Relationships:
  /home/admin/DONTBACKUP/companiesdrugs.csv

Available memory:
  Free machine memory: 117.48 GB
  Max heap memory : 26.52 GB

Nodes
[>:??-----------------|PROPERT|NODE:7.6|*LABEL SCAN-----------------------|v:5.74 MB/s---------] 30k
Done in 1s 190ms
Prepare node index
[*DETECT:7.73 MB-------------------------------------------------------------------------------] 30k
Done in 116ms
Calculate dense nodes
[>:??-----------------------------|*PREPARE---------------------------------------------|DIV|CA]110k
Done in 202ms
Relationships
[>:??---------|PREPARE|PROPERT|RELATIONSHIP-----------|*v:??-----------------------------------] 30k
Done in 200ms
Node --> Relationship
[*>:??------------------------------------------------|LINK-------------|v:??------------------] 30k
Done in 41ms
Relationship --> Relationship
[*>:??---------------------------------------|LINK-----------------------------------|v:??-----] 30k
Done in 71ms
Node counts
[*COUNT:76.29 MB-------------------------------------------------------------------------------] 30k
Done in 181ms
Relationship counts
[>:|*COUNT(16)=================================================================================] 30k
Done in 8s 745ms

IMPORT DONE in 12s 427ms. Imported:
  25998 nodes
  24999 relationships
  535968 properties
```

But with

```
admin@ip-172-31-20-91 ~
07:52:07$ wc -l DONTBACKUP/*csv
    1000 DONTBACKUP/companies.csv
  250000 DONTBACKUP/companiesdrugs.csv
  250000 DONTBACKUP/drugs.csv
  501000 total
```

I receive

```
[...]
[*COUNT:76.29 MB-------------------------------------------------------------------------------]260k
Done in 7s 341ms
Relationship counts
Import error: Panic called, so exiting
```

with 

```
Caused by: java.lang.UnsupportedOperationException: Not supported a.t.m
```

@spacecowboy not sure i understood, i sent a `wc -l`of each file

Thanks all for help guys!

**Comment by cosimosimeoneTR** [comment]
I might have found.

```
id:ID(Company),:LABEL,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
0,Cmp_0,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
```

is wrong, since :LABEL is not a "label"...

```
id:ID(Company),:LABEL,companyName,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
0,Company,Cmp_0,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9
```

Is way better...

**Comment by majensen** [comment]
In case someone happens on this (like I did):

Note the trace:
```
Caused by: java.lang.UnsupportedOperationException: Not supported a.t.m
        at org.neo4j.unsafe.impl.batchimport.Utils.safeCastLongToInt(Utils.java:36)
```

In my case, the offending column (file_size) was declared 'int' (i.e.)
```
...,file_size:int,...
```
but there were big numbers in there. When I declared it 'long' instead
```
...,file_size:long,...
```
problem was gone.
