### ISSUE TITLE
when my program run newEmbeddedDatabase("C:/TPNeo4jDB"); i get error like......

### ISSUE THREAD

**Issue by pangguoming** [neo4j/neo4j#5637]
When my program run 
GraphDatabaseService db = dbFactory.newEmbeddedDatabase("C:/TPNeo4jDB");

I get error:
Exception in thread "main" java.lang.NullPointerException
    at org.neo4j.kernel.impl.factory.CommunityEditionModule.determineEdition(CommunityEditionModule.java:142)
    at org.neo4j.kernel.impl.factory.CommunityEditionModule.publishEditionInfo(CommunityEditionModule.java:132)
    at org.neo4j.kernel.impl.factory.CommunityEditionModule.<init>(CommunityEditionModule.java:122)
    at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.createEdition(CommunityFacadeFactory.java:50)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:125)
    at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:43)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:129)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:117)
    at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:185)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(GraphDatabaseFactory.java:79)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(GraphDatabaseFactory.java:74)
    at com.gongjiaolaile.view.Test.main(Test.java:9)

**Comment by thobe** [comment]
Hi @pangguoming, I have a few questions for you in order to properly diagnose this:
1. Which version of Neo4j are you using? From the look of that stacktrace, I would guess one of the pre-releases of 2.3, but which one?
2. What Java version and distribution are you using?
3. Are you loading Neo4j through the bootstrap classpath?

**Comment by pangguoming** [comment]
Hey,@thobe
1.my java version:java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
2. my Neo4j version: neo4j-community-2.3.0-RC1
3.I imported  all jar files in  'neo4j-community-2.3.0-RC1\lib'  direcory  to classpath with Eclipse
4.i can find the messages.log file in "C:/TPNeo4jDB" ,the log is: 
2015-10-15 06:19:03.151+0000 INFO  [o.n.k.i.f.CommunityFacadeFactory] No locking implementation specified, defaulting to 'community'

I use windows 8 now

**Comment by pangguoming** [comment]
Hey,@thobe
With the same code , it works good on Ubuntu system

**Comment by tinwelint** [comment]
What do you mean with (3)? Do you put the neo4j jars on the classpath of the JVM that Eclipse runs?

**Comment by pangguoming** [comment]
@tinwelint yes,i did

**Comment by tinwelint** [comment]
That sounds like the cause. Why do you do it like that? What does Neo4j have to do with the Eclipse JVM? Normally you start a new JVM from within Eclipse that runs Neo4j.

**Comment by pangguoming** [comment]
ok,i will try another way, thanks

**Comment by Sobitan** [comment]
Yes this really helped.
Its solves the error "java.lang.NoSuchMethodError" or "No Source Found Error" in eclipse.
Which occurs on the method newEmbeddedDatabase.
The clear solution is use the pom.xml file to add all the required neo4j dependencies as opposed to adding them manually to the external libraries in the project. The pom.xml fill will automatically download them and your code will work perfectly.
Thanks for this post.

Note: The dependencies tag should not be placed inside the plugin tag in the pom.xml that was the cause of my error.
