### ISSUE TITLE
IndexOutOfBoundsException on Relationship Iterator

### ISSUE THREAD

**Issue by jzarrelli** [neo4j/neo4j#5691]
I’m getting the following error upon switching from the community version 2.2.5 to the Enterprise evaluation version 2.3.0, is this perhaps a bug in the new version?

```
    try (Transaction tx = db.beginTx()) {
        Set<Node> nodesToClean = new HashSet<>();
        try (ResourceIterator<Node> nodes  = GenericQueries.getMatchesFromNodeLabel(GeneralLabels.FEATURE)) { // This just calls GraphDatabaseService.findNodes(label) on the db.
            while (nodes.hasNext()) {
                Node node = nodes.next();
                if (!node.getRelationships(Direction.OUTGOING, RelationshipTypes.HAS_INSTANCE).iterator().hasNext()) {  // <---- The error is thrown on this line.
                    nodesToClean.add(node);
                }
            }
        }
          //I’ve excluded the remaining code, as it is never reached. 
    }
```

Exception in thread "main" java.lang.IndexOutOfBoundsException
                at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.setOffset(MuninnPageCursor.java:419)
                at org.neo4j.kernel.impl.store.RelationshipGroupStore.readRecord(RelationshipGroupStore.java:143)
                at org.neo4j.kernel.impl.store.RelationshipGroupStore.forceGetRecord(RelationshipGroupStore.java:106)
                at org.neo4j.kernel.impl.api.store.StoreNodeRelationshipCursor.init(StoreNodeRelationshipCursor.java:89)
                at org.neo4j.kernel.impl.api.store.StoreAbstractNodeCursor.relationships(StoreAbstractNodeCursor.java:203)
                at org.neo4j.kernel.api.cursor.NodeItem$NodeItemHelper.getRelationships(NodeItem.java:81)
                at org.neo4j.kernel.impl.api.OperationsFacade.nodeGetRelationships(OperationsFacade.java:319)
                at org.neo4j.kernel.impl.core.NodeProxy$2.iterator(NodeProxy.java:201)
                at org.neo4j.kernel.impl.core.NodeProxy$2.iterator(NodeProxy.java:193)

**Comment by tinwelint** [comment]
This looks like an introduced bug for sure, will assess and see if we can target a fix for 2.3.1

**Comment by tinwelint** [comment]
See https://github.com/neo4j/neo4j/pull/5694

**Comment by djvs** [comment]
Is there a binary release for this yet, esp. Ubuntu 14.04?

**Comment by djvs** [comment]
Possibly related? https://github.com/neo4j/neo4j/issues/5735
