### ISSUE TITLE
Neo4jIntegrationTestRule throws ClassNotFound exception

### ISSUE THREAD

**Issue by brnagendra** [neo4j/neo4j#5708]
Hi,
I am using neo4j-ogm library and following the instruction to test my service using the strategy as decribed in http://neo4j.com/docs/ogm/java/stable/#reference_programming-model_testing
I am getting below error in my test class. 

java.lang.NoClassDefFoundError: org/neo4j/test/Digests
    at org.neo4j.harness.internal.InProcessServerBuilder.randomFolderName(InProcessServerBuilder.java:185)
    at org.neo4j.harness.internal.InProcessServerBuilder.<init>(InProcessServerBuilder.java:71)
    at org.neo4j.harness.internal.InProcessServerBuilder.<init>(InProcessServerBuilder.java:66)
    at org.neo4j.harness.TestServerBuilders.newInProcessBuilder(TestServerBuilders.java:37)
    at org.neo4j.ogm.testutil.TestServer.<init>(TestServer.java:39)
    at org.neo4j.ogm.testutil.Neo4jIntegrationTestRule.<init>(Neo4jIntegrationTestRule.java:55)
    at com.bovotech.profile.services.ProfileServiceImplTest.<clinit>(ProfileServiceImplTest.java:24)
    at sun.misc.Unsafe.ensureClassInitialized(Native Method)
    at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
    at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
    at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
    at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
    at java.lang.reflect.Field.get(Field.java:393)
    at org.junit.runners.model.FrameworkField.get(FrameworkField.java:69)
    at org.junit.runners.model.TestClass.getAnnotatedFieldValues(TestClass.java:156)
    at org.junit.runners.ParentRunner.classRules(ParentRunner.java:215)
    at org.junit.runners.ParentRunner.withClassRules(ParentRunner.java:203)
    at org.junit.runners.ParentRunner.classBlock(ParentRunner.java:163)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:308)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
Caused by: java.lang.ClassNotFoundException: org.neo4j.test.Digests
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 23 more

Regards,
Nagendra B.R

**Comment by jexp** [comment]
There are additional dependencies:

```
        <dependency>
            <groupId>org.neo4j.test</groupId>
            <artifactId>neo4j-harness</artifactId>
      <version>${neo4j.version}</version>
            <scope>test</scope>
        </dependency>

    <dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>neo4j-kernel</artifactId>
      <version>${neo4j.version}</version>
      <type>test-jar</type>
            <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>neo4j-io</artifactId>
      <version>${neo4j.version}</version>
      <type>test-jar</type>
            <scope>test</scope>
    </dependency>
```

**Comment by brnagendra** [comment]
Added all the required dependencies. I am using Play 2 Framework and SBT as a build tool. Now, I am getting below error:

[error] Test com.bovotech.profile.services.ProfileServiceImplTest failed: java.lang.ExceptionInInitializerError: null, took 0.0 sec
[error]     at sun.misc.Unsafe.ensureClassInitialized(Native Method)
[error]     ...
[error] Caused by: java.lang.RuntimeException: Error starting in-process server
[error]     at org.neo4j.ogm.testutil.TestServer.<init>(TestServer.java:46)
[error]     at org.neo4j.ogm.testutil.Neo4jIntegrationTestRule.<init>(Neo4jIntegrationTestRule.java:55)
[error]     at com.bovotech.profile.services.ProfileServiceImplTest.<clinit>(ProfileServiceImplTest.java:25)
[error]     ... 29 more
[error] Caused by: org.neo4j.server.ServerStartupException: Starting Neo4j Server failed: org.neo4j.kernel.impl.query.NoQueryEngine cannot be cast to org.neo4j.cypher.javacompat.internal.ServerExecutionEngine
[error]     at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:258)
[error]     at org.neo4j.harness.internal.InProcessServerControls.start(InProcessServerControls.java:59)
[error]     at org.neo4j.harness.internal.InProcessServerBuilder.newServer(InProcessServerBuilder.java:72)
[error]     at org.neo4j.ogm.testutil.TestServer.<init>(TestServer.java:39)
[error]     ... 31 more
[error] Caused by: java.lang.ClassCastException: org.neo4j.kernel.impl.query.NoQueryEngine cannot be cast to org.neo4j.cypher.javacompat.internal.ServerExecutionEngine
[error]     at org.neo4j.server.database.CypherExecutor.start(CypherExecutor.java:44)
[error]     at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:226)
[error]     ... 34 more
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error]         com.bovotech.profile.services.ProfileServiceImplTest
[error](profile/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 20 s, completed Oct 24, 2015 12:04:03 AM

**Dependencies Added:**
libraryDependencies += "org.neo4j" % "neo4j-ogm" % "1.1.3"
libraryDependencies += "org.neo4j.test" % "neo4j-harness" % "2.2.5" % Test
libraryDependencies += "org.neo4j" % "neo4j-ogm" % "1.1.3" % "test" classifier "tests"
libraryDependencies += "org.neo4j" % "neo4j-kernel" % "2.2.5" % "test" classifier "tests"
libraryDependencies += "org.neo4j" % "neo4j-io" % "2.2.5" % "test" classifier "tests"
libraryDependencies += "org.neo4j.app" % "neo4j-server" % "2.2.5" % "test" classifier "tests"
libraryDependencies += "com.sun.jersey" % "jersey-client" % "1.19" % Test
libraryDependencies += "com.sun.jersey" % "jersey-server" % "1.19" % Test
libraryDependencies += "com.sun.jersey" % "jersey-servlet" % "1.19" % Test
libraryDependencies += "com.sun.jersey" % "jersey-core" % "1.19" % Test

**Comment by brnagendra** [comment]
I was able to resolve the above exception by upgrading the dependencies to the latest jar files and also added 
libraryDependencies += "org.neo4j" % "neo4j" % "2.3.0" % Test
dependency.
