### ISSUE TITLE
[3.0.0] Truncating database with Cypher leads to NPE

### ISSUE THREAD

**Issue by FylmTM** [neo4j/neo4j#5742]
Neo4j version: 3.0.0 (most recent snapshot)

Code:

``` java
public final class TestNullPointer {

    public TestNullPointer() {
    }

    public static void main(final String[] args) {
        new TestNullPointer().run();
    }

    public void run() {
        final File dir = Files.createTempDir();
        final GraphDatabaseService db = new GraphDatabaseFactory().newEmbeddedDatabase(dir);

        try (final Transaction transaction = db.beginTx()) {
            db.createNode();
            transaction.success();
        }

        try (final Transaction transaction = db.beginTx()) {
            final String truncateQuery = "MATCH (n) OPTIONAL MATCH (n)-[r]-() DELETE n,r";
            try (final Result result = db.execute(truncateQuery)) {
                // do nothing
            }
            transaction.success();
        }
    }
}

```

Stacktrace:

```
Exception in thread "main" java.lang.NullPointerException
    at org.neo4j.cypher.internal.compiler.v3_0.pipes.DeleteRelationshipPipe$$anonfun$internalCreateResults$1.apply(DeleteRelationshipPipe.scala:41)
    at org.neo4j.cypher.internal.compiler.v3_0.pipes.DeleteRelationshipPipe$$anonfun$internalCreateResults$1.apply(DeleteRelationshipPipe.scala:35)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:370)
    at org.neo4j.cypher.internal.compiler.v3_0.pipes.EmptyResultPipe.internalCreateResults(EmptyResultPipe.scala:32)
    at org.neo4j.cypher.internal.compiler.v3_0.pipes.PipeWithSource.createResults(Pipe.scala:127)
    at org.neo4j.cypher.internal.compiler.v3_0.pipes.PipeWithSource.createResults(Pipe.scala:124)
    at org.neo4j.cypher.internal.compiler.v3_0.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.createResults(DefaultExecutionResultBuilderFactory.scala:95)
    at org.neo4j.cypher.internal.compiler.v3_0.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:65)
    at org.neo4j.cypher.internal.compiler.v3_0.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:230)
    at org.neo4j.cypher.internal.compiler.v3_0.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:214)
    at org.neo4j.cypher.internal.compiler.v3_0.executionplan.ExecutionPlanBuilder$$anon$3.run(ExecutionPlanBuilder.scala:172)
    at org.neo4j.cypher.internal.compatibility.CompatibilityFor3_0$ExecutionPlanWrapper$$anonfun$run$1.apply(CompatibilityFor3_0.scala:193)
    at org.neo4j.cypher.internal.compatibility.CompatibilityFor3_0$ExecutionPlanWrapper$$anonfun$run$1.apply(CompatibilityFor3_0.scala:193)
    at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor3_0$.runSafely(CompatibilityFor3_0.scala:115)
    at org.neo4j.cypher.internal.compatibility.CompatibilityFor3_0$ExecutionPlanWrapper.run(CompatibilityFor3_0.scala:192)
    at org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:27)
    at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:118)
    at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:112)
    at org.neo4j.cypher.javacompat.internal.ServerExecutionEngine.executeQuery(ServerExecutionEngine.java:62)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:333)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:323)
    at me.vrublevsky.TestNullPointer.run(TestNullPointer.java:45)
    at me.vrublevsky.TestNullPointer.main(TestNullPointer.java:31)
```

**Comment by ikwattro** [comment]
Might be related to the IndexOutOfBound current issue on relationshipIterator that expects at least one relationship on non-marked sparse nodes. 

However using `MATCH (n) DETACH DELETE n` works though.

Fix upcoming in 2.3.1 and next nightly builds.

**Comment by FylmTM** [comment]
@ikwattro Okey! We have our nigthly builds, which tests agains latest Neo4j 3.0.0 release. I will close this issue when build will be fixed. Or comment if not fixed after several nightly builds (3 days).

**Comment by ikwattro** [comment]
Yeah I'm waiting too. Especially because the relationshipIterator issue is breaking most of our modules :(

Are you using this url too ? http://alpha.neohq.net/dist/neo4j-enterprise-3.0.0-M01-NIGHTLY-unix.tar.gz

**Comment by FylmTM** [comment]
Still fails. 

@ikwattro - We are using `neo4j-harness`.
And this snapshot repostory:

``` xml
<repository>
    <id>neo4j-nexus-snapshot</id>
    <url>http://m2.neo4j.org/content/repositories/snapshots</url>
    <snapshots><enabled>true</enabled></snapshots>
</repository>
```

**Comment by henriknyman** [comment]
This is a new issue in 3.0 and is unrelated with the IndexOutOfBound-issue mentioned above
