### ISSUE TITLE
BatchOperation failed 

### ISSUE THREAD

**Issue by ncoronges** [neo4j/neo4j#5813]
We are using py2neo and getting an error on calls to push() - which call the batch REST endpoints (PUT node/{id}/properties). On the server, running neo4j enterprise 2.2.3, we see a BatchOperationFailedException caused by NullPointerException - stack trace below. 

The python code that causes the error on the server is below.  Any calls to Node.push() or Graph.push(Node) result in same exception on server. (I would post this as a py2neo issue, but the same py2neo code works against other neo4j servers). 

``` python
    project_node = graph.find_one("PROJECT", "ID", 33725)
    logger.debug ("updating project "+project_node['name'])
    project_node.properties["tester"] = "Six"
    watch("py2neo.batch")
    project_node.push()
```

The POST looks like:

> Sending batch request with 2 jobs
> {0} PUT node/5992/properties {"start_date":"Fiver","tester2":"Five","code":"C4102","name":"Offline RZN Ball Recommender2","office":"New York","leadproducer":"Eric Lee","tester":"Six","ID":33725,"projstartdate":"09/17/2014","currentenddate":"12/16/2014","leademail":"-"}
> {1} PUT node/5992/labels ["PROJECT"]
> < Received batch response for 2 jobs
> < {0} 500

Exception on server (/var/lib/neo4j/messages.log): 

```
2015-11-02 07:30:50.789+0000 WARN  [o.n.s.r.w.BatchOperationService]: Error executing batch request 
org.neo4j.server.rest.domain.BatchOperationFailedException: null
    at org.neo4j.server.rest.web.StreamingBatchOperations.invoke(StreamingBatchOperations.java:75) ~[neo4j-server-2.2.3.jar:2.2.3]
    at org.neo4j.server.rest.batch.BatchOperations.performRequest(BatchOperations.java:205) ~[neo4j-server-2.2.3.jar:2.2.3]
    at org.neo4j.server.rest.batch.BatchOperations.parseAndPerform(BatchOperations.java:173) ~[neo4j-server-2.2.3.jar:2.2.3]
    at org.neo4j.server.rest.web.StreamingBatchOperations.readAndExecuteOperations(StreamingBatchOperations.java:59) ~[neo4j-server-2.2.3.jar:2.2.3]
    at org.neo4j.server.rest.web.BatchOperationService$1.write(BatchOperationService.java:120) ~[neo4j-server-2.2.3.jar:2.2.3]
    at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71) [jersey-core-1.19.jar:1.19]
    at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57) [jersey-core-1.19.jar:1.19]
    at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302) [jersey-server-1.19.jar:1.19]
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510) [jersey-server-1.19.jar:1.19]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [jersey-server-1.19.jar:1.19]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [jersey-server-1.19.jar:1.19]
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [jersey-servlet-1.19.jar:1.19]
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558) [jersey-servlet-1.19.jar:1.19]
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733) [jersey-servlet-1.19.jar:1.19]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800) [jetty-servlet-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [jetty-servlet-9.2.4.v20141103.jar:9.2.4.v20141103]
    at ch.qos.logback.access.servlet.TeeFilter.doFilter(TeeFilter.java:55) [logback-access-1.1.2.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.neo4j.server.rest.dbms.AuthorizationFilter.doFilter(AuthorizationFilter.java:120) [neo4j-server-2.2.3.jar:2.2.3]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221) [jetty-server-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125) [jetty-server-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059) [jetty-server-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95) [jetty-server-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.server.Server.handle(Server.java:497) [jetty-server-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248) [jetty-server-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620) [jetty-util-9.2.4.v20141103.jar:9.2.4.v20141103]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540) [jetty-util-9.2.4.v20141103.jar:9.2.4.v20141103]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_91]
Caused by: java.lang.NullPointerException: null
```

Note we are using the CloudFormation installation for ec2 (https://github.com/neo4j-contrib/ec2neo) running over https. 

Any help appreciated.

**Comment by ncoronges** [comment]
I upgraded to 2.3.0 and this resolved the issue.
