### ISSUE TITLE
transaction  sleep

### ISSUE THREAD

**Issue by xghrbc1001** [neo4j/neo4j#5950]
my neo4j's version is 2.2.5,I use the transaction like this

```
try(Transaction tx = db.beginTx())
{
    // Things
    tx.success();
}
```

,but ,I got jstack from neo4j as the below:

```
"qtp1880519262-298" #298 prio=5 os_prio=0 tid=0x00007fb0cc722000 nid=0x6367 sleeping[0x00007fafa7c78000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
    at java.lang.Thread.sleep(Native Method)
    at java.lang.Thread.sleep(Thread.java:340)
    at org.neo4j.kernel.impl.util.concurrent.LockWaitStrategies$3.apply(LockWaitStrategies.java:69)
    at org.neo4j.kernel.ha.lock.forseti.ForsetiClient.acquireExclusive(ForsetiClient.java:229)
    at org.neo4j.kernel.impl.api.LockingStatementOperations.nodeRemoveProperty(LockingStatementOperations.java:331)
    at org.neo4j.kernel.impl.api.GuardingStatementOperations.nodeRemoveProperty(GuardingStatementOperations.java:129)
    at org.neo4j.kernel.impl.api.OperationsFacade.nodeRemoveProperty(OperationsFacade.java:678)
    ey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
    at org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139)
```

neo4j's transaction use Thread.sleep to got lock?

**Comment by chrisvest** [comment]
In Enterprise Edition It does spinning with incremental back-off into short sleeps. This works well when transactions are short and the dataset size is large. Set `lock_manager=community` in your `neo4j.properties` if object monitor based locks better serve your workload.

**Comment by xghrbc1001** [comment]
thank you @chrisvest , but I found jstack sleeping all the time.

```
"qtp1880519262-294" #294 prio=5 os_prio=0 tid=0x00007f746fb09800 nid=0x7795 sleeping[0x00007f71c5c99000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
    at java.lang.Thread.sleep(Native Method)
    at java.lang.Thread.sleep(Thread.java:340)
    at org.neo4j.kernel.impl.util.concurrent.LockWaitStrategies$3.apply(LockWaitStrategies.java:69)
```

LockWaitStrategies.java

```
Thread.sleep( 0, 500 );
```

but LockWaitStrategies.java was only sleep 500ns.

I don't know the reason.

**Comment by chrisvest** [comment]
It checks the lock state in a loop. If the lock is unavailable, the LockWaitStrategy is applied.
