### ISSUE TITLE
UnixEnvironment doesn't support Desktop.Actions.BROWSE

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#6043]
There is a longstanding bug (https://bugs.openjdk.java.net/browse/JDK-6428599) that states that for some Linux distributions `Desktop#isSupported(Desktop.Actions.BROWSE)` will return false. In my case, it's a 64-bit Ubuntu/KDE environment. Using `UnixEnvironment`, when clicking on the `Browse to [link]`, I get the following:

```
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: Cannot browse to URL: http://localhost:7474/
    at org.neo4j.desktop.config.unix.UnixEnvironment.openBrowser(UnixEnvironment.java:39)
    at org.neo4j.desktop.ui.DesktopModel.openBrowser(DesktopModel.java:172)
    at org.neo4j.desktop.ui.OpenBrowserMouseListener.mouseClicked(OpenBrowserMouseListener.java:56)
    at java.awt.Component.processMouseEvent(Component.java:6538)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)

```

I understand that this is a matter of portability, but since all distributions that use X-server support the `xdg-open [url]`, perhaps using it as a fallback measure would be appropriate? 
Of course, I didn't test this on a wide range of distributions, but if you consider the possibility, I could run tests on various versions of [K|X]Ubuntu/Arch/Mint etc. myself.

**Comment by jotomo** [comment]
@tkroman The linked bug reports is about running a 32-bit JVM on a 64-bit system - is anybody still doing that?
 I got a very similiar stacktrace with Intellij (message said _Operation not supported_, but otherwise the exception looked very similiar) recently on my Arch 64-bit (KDE) system. This was fixed by installing the package _libgnome2_ (_libgnome2-0_ in Ubuntu). Maybe give that a try? I know JavaFX uses _gtk2-libs_ for Desktop-specific stuff, I'm assuming Swing does so too, hence the issue on KDE (or systems running with just gtk3)

**Comment by tkroman** [comment]
I agree on the high-and-dry state of the bug's origin. Perhaps this particular issue could be at least somehow documented if not solved in a suggested way?
Also, I understand that using GUI to launch neo4j on Linux is a rare case, but the point of having a  GUI is to provide those unwilling to use shell tools with an easy alternative, and having to resort to stacktrace inspection kind of contradicts the whole idea. Just a thought, anyway :)

BTW, I've already got libgnome2 installed - no luck.

**Comment by benbc** [comment]
Hello @tkroman. I'm afraid that the Neo4j Desktop isn't supported on Linux and we have no plans to support it in the future.

If you fix this problem you are likely to run into others. And since the combination is not supported we don't test it, so it's likely to break at any point in the future.

**Comment by tkroman** [comment]
@benbc, ah, I see. Okay then, thanks for the swift response.
