### ISSUE TITLE
Can't share index-backed ResourceIterable between transactions

### ISSUE THREAD

**Issue by bachmanm** [neo4j/neo4j#6087]
Let's say we're trying to add `SecondLabel` to every node with `FirstLabel`. What's the right way of doing this on a very large database? What we have been doing is something along the lines in the test below. However, any number above 131,000 nodes with `FirstLabel` fails the test with 

```
org.apache.lucene.store.AlreadyClosedException: this IndexReader is closed
    at org.apache.lucene.index.IndexReader.ensureOpen(IndexReader.java:245)
    at org.apache.lucene.index.IndexReader.getSequentialSubReaders(IndexReader.java:1602)
    at org.apache.lucene.util.ReaderUtil$Gather.run(ReaderUtil.java:78)
    at org.apache.lucene.util.ReaderUtil$Gather.run(ReaderUtil.java:87)
    at org.apache.lucene.util.ReaderUtil$Gather.run(ReaderUtil.java:70)
    at org.apache.lucene.search.TermQuery$TermWeight.<init>(TermQuery.java:53)
    at org.apache.lucene.search.TermQuery.createWeight(TermQuery.java:199)
    at org.apache.lucene.search.Searcher.createNormalizedWeight(Searcher.java:168)
    at org.apache.lucene.search.IndexSearcher.createNormalizedWeight(IndexSearcher.java:664)
    at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:319)
    at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:305)
    at org.neo4j.kernel.api.impl.index.PageOfRangesIterator.fetchNextOrNull(PageOfRangesIterator.java:67)
    at org.neo4j.kernel.api.impl.index.PageOfRangesIterator.fetchNextOrNull(PageOfRangesIterator.java:35)
    at org.neo4j.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
    at org.neo4j.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
    at org.neo4j.collection.primitive.PrimitiveLongCollections$PrimitiveLongConcatingIterator.fetchNext(PrimitiveLongCollections.java:196)
    at org.neo4j.collection.primitive.PrimitiveLongCollections$PrimitiveLongBaseIterator.hasNext(PrimitiveLongCollections.java:56)
    at org.neo4j.collection.primitive.PrimitiveLongCollections$14.hasNext(PrimitiveLongCollections.java:740)
    at org.neo4j.helpers.collection.ResourceClosingIterator.hasNext(ResourceClosingIterator.java:61)
    at com.graphaware.tx.executor.batch.IndexBug.processBatch(IndexBug.java:90)
```

Is there any way to iterate over all nodes with label without having to do it in a single transaction? Thanks

The test

``` java
public class IndexBug {

    private static final int NUMBER_OF_NODES = 132_000;
    private static final int BATCH_SIZE = 1_000;
    private GraphDatabaseService database;

    @Before
    public void setUp() throws Exception {
        database = new TestGraphDatabaseFactory()
                .newImpermanentDatabaseBuilder()
                .newGraphDatabase();

        try (Transaction tx = database.beginTx()) {
            for (int i = 0; i < NUMBER_OF_NODES; i++) {
                Node node = database.createNode();
                node.addLabel(DynamicLabel.label("FirstLabel"));
            }
            tx.success();
        }
    }

    @After
    public void tearDown() throws Exception {
        database.shutdown();
    }

    @Test
    public void testLabelsCanBeAddedInBatch() {
        Iterator<Node> allNodes;

        try (Transaction tx = database.beginTx()) {
            allNodes = Iterables.asResourceIterable(database.findNodes(DynamicLabel.label("FirstLabel"))).iterator();
            tx.success();
        }

        int counter = 0;
        while (processBatch(allNodes)) {
            System.out.println("Processed Batch "+ ++counter);
        }

        int i = 0;
        try (Transaction tx = database.beginTx()) {
            ResourceIterator<Node> nodes = database.findNodes(DynamicLabel.label("SecondLabel"));
            while (nodes.hasNext()) {
                i++;
                nodes.next();
            }

            tx.success();
        }

        assertEquals(NUMBER_OF_NODES, i);
    }

    private boolean processBatch(Iterator<Node> allNodes) {
        boolean result = true;

        try (Transaction tx = database.beginTx()) {
            for (int i = 0; i < BATCH_SIZE; i++) {
                if (!allNodes.hasNext()) {
                    result = false;
                    break;
                }

                Node next = allNodes.next();
                next.addLabel(DynamicLabel.label("SecondLabel"));
            }
            tx.success();
        }

        return result;
    }
}
```

Tested on Neo4j 2.3.1

**Comment by spacecowboy** [comment]
Thanks for the report.

I am unable to reproduce this issue with the test you included. I tried on 2.2.7, 2.3.1 and 3.0-alpha. Is there any configuration, JVM options, or anything else required to reproduce the issue?

**Comment by bachmanm** [comment]
Could you try to change the NUMBER_OF_NODES constant to, say, 1_000_000 and try again? In the meantime, I'll provide more info about JVM settings, Java version, etc

**Comment by bachmanm** [comment]
Neo4j 2.3.1, jdk1.7.0_79, all settings default

**Comment by bachmanm** [comment]
If you still can't reproduce, I'll create a fresh github repo and let it build & test with Travis

**Comment by bachmanm** [comment]
Hi guys, any updates on this? Have you been able to reproduce? Cheers!

**Comment by spacecowboy** [comment]
@bachmanm Sorry for the delay. Didn't catch your replies.

Decided to re-run it today and was able to reproduce it without changing `NUMBER_OF_NODES` on latest neo4j-2.3.2-SNAPSHOT and jdk8. 

I have raised this internally.

**Comment by spacecowboy** [comment]
@bachmanm This is actually working as intended. Here is an alternate batch solution:

``` java
public class IndexBugFix
{

    private static final int NUMBER_OF_NODES = 132_000;
    private static final int BATCH_SIZE = 1_000;
    private GraphDatabaseService database;

    @Before
    public void setUp() throws Exception
    {
        database = new TestGraphDatabaseFactory()
                .newImpermanentDatabaseBuilder()
                .newGraphDatabase();

        try ( Transaction tx = database.beginTx() )
        {
            for ( int i = 0; i < NUMBER_OF_NODES; i++ )
            {
                Node node = database.createNode();
                node.addLabel( DynamicLabel.label( "FirstLabel" ) );
            }
            tx.success();
        }
    }

    @After
    public void tearDown() throws Exception
    {
        database.shutdown();
    }

    @Test
    public void testLabelsCanBeAddedInBatch() throws InterruptedException
    {
        ExecutorService executor = Executors.newSingleThreadExecutor();

        try ( Transaction tx = database.beginTx() )
        {
            ResourceIterator<Node> nodes = database.findNodes( DynamicLabel.label( "FirstLabel" ) );

            List<Node> batch = new ArrayList<>( BATCH_SIZE );
            while ( nodes.hasNext() )
            {
                batch.add( nodes.next() );
                boolean processed = processBatchIfNeeded( batch, executor );
                if ( processed )
                {
                    batch = new ArrayList<>();
                }
            }
            processBatch( batch, executor );
            tx.success();
        }
        finally
        {
            executor.shutdown();
            executor.awaitTermination( 5, TimeUnit.MINUTES );
        }
    }

    private boolean processBatchIfNeeded( final List<Node> batch, ExecutorService executor )
    {
        if ( batch.size() == BATCH_SIZE )
        {
            processBatch( batch, executor );
            return true;
        }
        return false;
    }

    private void processBatch( final List<Node> batch, ExecutorService executor )
    {
        executor.execute( new Runnable()
        {
            @Override
            public void run()
            {
                try ( Transaction tx = database.beginTx() )
                {
                    for ( Node node : batch )
                    {
                        node.addLabel( DynamicLabel.label( "SecondLabel" ) );
                    }
                    tx.success();
                }
            }
        } );

        batch.clear();
    }
}
```

**Comment by bachmanm** [comment]
Thanks @spacecowboy! Will the fact that all `Node`s are iterated over in a single transaction cause them not to be garbage collected until the transaction finished? The point of batching things in the first place was to avoid GC pauses when doing these kinds of operations on large databases.

Cheers!

Michal

**Comment by spacecowboy** [comment]
I'm not 100% sure but I don't think that the GC behavior of this code is drastically different from the original version.
