### ISSUE TITLE
Neo4J Enterprise 2.2.8 (Cypher 2.0) simple DELETE query returns NoSuchMethodError

### ISSUE THREAD

**Issue by jjaburke91** [neo4j/neo4j#6183]
This question looks like a duplicate of https://github.com/neo4j/neo4j/issues/3872 , however I'm unable to upgrade neo4j any further than 2.2.8.

A basic query to return the searched Node works correctly, however when I try to delete the node with DELETE, I get the following error:

```
org.neo4j.kernel.impl.core.NodeManager.isDeleted(Lorg/neo4j/graphdb/Node;)Z
```

A sample of the query I'm using is as follows (the queried node definitely exists):

```
MATCH (n {comment:"Adding subbcomment to midland"})
DELETE n
```

I've tested this behaviour across Neo4J Enterprise 2.2.1 and 2.2.8, and the error occurs across both. I've also re-downloaded the packages and the error persists.

Noteable behaviour: through the webadmin, if I click and examine the returned node and click the 'Delete' button, it is successfully deleted.

Is there some sort of dependency or JAR that I am missing perhaps? Any help is greatly appreciated.

**Comment by jexp** [comment]
Hi @jjaburke91 
it seems like a version mismatch of libraries. How do you update / download your installation?

**Comment by jjaburke91** [comment]
Downloaded the 2.2.8 package from here http://neo4j.com/download/other-releases/ , then I copy my data/ folder over.

**Comment by jjaburke91** [comment]
This problem still persists with a completely fresh installation (nothing copied into the data folder), and I manually create a node and attempt to delete it.

**Comment by jexp** [comment]
Just tried it and it works for me.
Which OS are you on?
Do you use browser or webadmin for the delete statement?
Might the node still have relationships?

```
wuqour:Downloads mh$ cd neo4j-enterprise-2.2.8
wuqour:neo4j-enterprise-2.2.8 mh$ bin/neo4j-shell -path test2.db
NOTE: Local Neo4j graph database service at 'test2.db'
Welcome to the Neo4j Shell! Enter 'help' for a list of commands


neo4j-sh (?)$ create (n {name:"Foo"});        
+-------------------+
| No data returned. |
+-------------------+
Nodes created: 1
Properties set: 1
1294 ms
neo4j-sh (?)$ match (n {name:"Foo"}) return n;
+---------------------+
| n                   |
+---------------------+
| Node[0]{name:"Foo"} |
+---------------------+
1 row
393 ms
neo4j-sh (?)$ match (n {name:"Foo"}) delete n;
+-------------------+
| No data returned. |
+-------------------+
Nodes deleted: 1
96 ms
```

**Comment by jexp** [comment]
Oh also, could you list the content of your `lib`  and `system/lib` directory? and share it?

And can you share the full error message with stacktrace, which should probably be in either data/log/console.log or data/graph.db/messages.log ?

**Comment by jjaburke91** [comment]
I'm using Mac (OS X El Capitan v10.11.2). I've used both the browser and webadmin and both fail to execute.

I considered the Node might have relationships however given the problem still occurs with a clean database, on a new node without any relationships, I feel this wouldn't be the issue. I'd have expected the error message to be different if that were the case as well.

Contents of `lib` as follows:

```
README.txt
concurrentlinkedhashmap-lru-1.4.jar
lucene-core-3.6.2.jar
neo4j-backup-2.2.8.jar
neo4j-cluster-2.2.8.jar
neo4j-com-2.2.8.jar
neo4j-consistency-check-2.2.8.jar
neo4j-csv-2.2.8.jar
neo4j-cypher-2.2.8.jar
neo4j-cypher-compiler-1.9-2.0.4.jar
neo4j-cypher-compiler-2.0-2.0.4.jar
neo4j-cypher-compiler-2.1-2.1.8.jar
neo4j-cypher-compiler-2.2-2.2.8.jar
neo4j-graph-algo-2.2.8.jar
neo4j-graph-matching-2.2.8.jar
neo4j-ha-2.2.8.jar
neo4j-import-tool-2.2.8.jar
neo4j-io-2.2.8.jar
neo4j-jmx-2.2.8.jar
neo4j-kernel-2.2.8.jar
neo4j-lucene-index-2.2.8.jar
neo4j-management-2.2.8.jar
neo4j-primitive-collections-2.2.8.jar
neo4j-query-logging-2.2.8.jar
neo4j-shell-2.2.8.jar
neo4j-udc-2.2.8.jar
neo4j-unsafe-2.2.8.jar
netty-3.6.3.Final.jar
opencsv-2.3.jar
org.apache.servicemix.bundles.jline-0.9.94_1.jar
parboiled-core-1.1.7.jar
parboiled-scala_2.10-1.1.7.jar
scala-library-2.10.5.jar
server-api-2.2.8.jar
slf4j-api-1.7.7.jar
```

Contents of `system/lib`:

```
README.txt
bcprov-jdk16-140.jar
commons-beanutils-1.8.3.jar
commons-compiler-2.6.1.jar
commons-configuration-1.10.jar
commons-digester-2.1.jar
commons-io-2.4.jar
commons-lang-2.6.jar
commons-logging-1.1.1.jar
jackson-core-asl-1.9.13.jar
jackson-jaxrs-1.9.13.jar
jackson-mapper-asl-1.9.13.jar
janino-2.6.1.jar
javax.servlet-api-3.1.0.jar
jcl-over-slf4j-1.7.7.jar
jersey-core-1.19.jar
jersey-multipart-1.19.jar
jersey-server-1.19.jar
jersey-servlet-1.19.jar
jetty-http-9.2.4.v20141103.jar
jetty-io-9.2.4.v20141103.jar
jetty-security-9.2.4.v20141103.jar
jetty-server-9.2.4.v20141103.jar
jetty-servlet-9.2.4.v20141103.jar
jetty-util-9.2.4.v20141103.jar
jetty-webapp-9.2.4.v20141103.jar
jetty-xml-9.2.4.v20141103.jar
jsr311-api-1.1.2.r612.jar
logback-access-1.1.2.jar
logback-classic-1.1.2.jar
logback-core-1.1.2.jar
mimepull-1.9.3.jar
neo4j-browser-2.2.8.jar
neo4j-server-2.2.8-static-web.jar
neo4j-server-2.2.8.jar
neo4j-server-advanced-2.2.8.jar
neo4j-server-enterprise-2.2.8.jar
rhino-1.7R4.jar
rrd4j-2.2.jar
scala-reflect-2.10.5.jar
```

Searching for the error log just now...

**Comment by jjaburke91** [comment]
Seems an error log isn't written as none of the logs are updated with anything upon executing the query.

**Comment by jexp** [comment]
Could you do me a favor and try the same with neo4j-shell like I did above?
And see if it happens there too?

You can get the stacktraces by running this in shell before

`export STACKTRACES=true`

That would be very helpful, thanks a lot.

**Comment by jexp** [comment]
Oh, which java version do you have? Would you also be able to share the full messages.log? You can attach it to the comment.

**Comment by jjaburke91** [comment]
Error is consistent across Java 1.7 and 1.8. 

Did the same commands with neo4j-shell however no change.

[messages.txt](https://github.com/neo4j/neo4j/files/79873/messages.txt)

Export the stack traces but haven't seen any changes, looking into this just now.

**Comment by jjaburke91** [comment]
Setting the STACKTRACES variable still have no effect on the log outputs. I've changed the log output levels in `logging.properties` to FINE, however still no affect.

**Comment by jexp** [comment]
Sorry, did you set it in the neo4j-shell?

```
bin/neo4j-shell -path test2.db
NOTE: Local Neo4j graph database service at 'test2.db'
Welcome to the Neo4j Shell! Enter 'help' for a list of commands

neo4j-sh (?)$ export STACKTRACES=true
neo4j-sh (?)$ create (n {name:"Foo"});        
neo4j-sh (?)$ match (n {name:"Foo"}) return n;
neo4j-sh (?)$ match (n {name:"Foo"}) delete n;
```

**Comment by jjaburke91** [comment]
Ah apologies, didn't realise you could export in the shell. Stack trace from delete query:

```
QueryStatistics(1,0,1,0,0,0,0,0,0,0,0)755 ms
neo4j-sh (?)$ match (n {name:"Foo"}) return n;
+---------------------+
| n                   |
+---------------------+
| Node[2]{name:"Foo"} |
+---------------------+
1 row
136 ms
neo4j-sh (?)$ match (n {name:"Foo"}) delete n;
java.rmi.ServerError: Error occurred in server thread; nested exception is: 
    java.lang.NoSuchMethodError: org.neo4j.kernel.impl.core.NodeManager.isDeleted(Lorg/neo4j/graphdb/Node;)Z
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:350)
    at sun.rmi.transport.Transport$2.run(Transport.java:202)
    at sun.rmi.transport.Transport$2.run(Transport.java:199)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:198)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:567)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.access$400(TCPTransport.java:619)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$1.run(TCPTransport.java:684)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$1.run(TCPTransport.java:681)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:681)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:275)
    at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:252)
    at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
    at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:194)
    at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:148)
    at com.sun.proxy.$Proxy1.interpretLine(Unknown Source)
    at org.neo4j.shell.impl.AbstractClient.evaluate(AbstractClient.java:149)
    at org.neo4j.shell.impl.AbstractClient.evaluate(AbstractClient.java:133)
    at org.neo4j.shell.impl.AbstractClient.grabPrompt(AbstractClient.java:101)
    at org.neo4j.shell.StartClient.grabPromptOrJustExecuteCommand(StartClient.java:385)
    at org.neo4j.shell.StartClient.startRemote(StartClient.java:332)
    at org.neo4j.shell.StartClient.start(StartClient.java:196)
    at org.neo4j.shell.StartClient.main(StartClient.java:135)
Caused by: java.lang.NoSuchMethodError: org.neo4j.kernel.impl.core.NodeManager.isDeleted(Lorg/neo4j/graphdb/Node;)Z
    at org.neo4j.cypher.internal.compiler.v2_0.mutation.DeleteEntityAction.org$neo4j$cypher$internal$compiler$v2_0$mutation$DeleteEntityAction$$delete(DeleteEntityAction.scala:49)
    at org.neo4j.cypher.internal.compiler.v2_0.mutation.DeleteEntityAction.exec(DeleteEntityAction.scala:36)
    at org.neo4j.cypher.internal.compiler.v2_0.pipes.ExecuteUpdateCommandsPipe.org$neo4j$cypher$internal$compiler$v2_0$pipes$ExecuteUpdateCommandsPipe$$exec(ExecuteUpdateCommandsPipe.scala:56)
    at org.neo4j.cypher.internal.compiler.v2_0.pipes.ExecuteUpdateCommandsPipe$$anonfun$org$neo4j$cypher$internal$compiler$v2_0$pipes$ExecuteUpdateCommandsPipe$$executeMutationCommands$1$$anonfun$apply$2.apply(ExecuteUpdateCommandsPipe.scala:45)
    at org.neo4j.cypher.internal.compiler.v2_0.pipes.ExecuteUpdateCommandsPipe$$anonfun$org$neo4j$cypher$internal$compiler$v2_0$pipes$ExecuteUpdateCommandsPipe$$executeMutationCommands$1$$anonfun$apply$2.apply(ExecuteUpdateCommandsPipe.scala:45)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at org.neo4j.cypher.internal.compiler.v2_0.pipes.EmptyResultPipe.internalCreateResults(EmptyResultPipe.scala:28)
    at org.neo4j.cypher.internal.compiler.v2_0.pipes.PipeWithSource.createResults(Pipe.scala:73)
    at org.neo4j.cypher.internal.compiler.v2_0.executionplan.ExecutionPlanBuilder.org$neo4j$cypher$internal$compiler$v2_0$executionplan$ExecutionPlanBuilder$$prepareStateAndResult(ExecutionPlanBuilder.scala:149)
    at org.neo4j.cypher.internal.compiler.v2_0.executionplan.ExecutionPlanBuilder$$anonfun$3.apply(ExecutionPlanBuilder.scala:136)
    at org.neo4j.cypher.internal.compiler.v2_0.executionplan.ExecutionPlanBuilder$$anonfun$3.apply(ExecutionPlanBuilder.scala:135)
    at org.neo4j.cypher.internal.compiler.v2_0.executionplan.ExecutionPlanBuilder$$anon$6.execute(ExecutionPlanBuilder.scala:50)
    at org.neo4j.cypher.internal.compatibility.CompatibilityFor2_0$ExecutionPlanWrapper.execute(CompatibilityFor2_0.scala:67)
    at org.neo4j.cypher.internal.compatibility.CompatibilityFor2_0$ExecutionPlanWrapper.run(CompatibilityFor2_0.scala:60)
    at org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:28)
    at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:113)
    at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:107)
    at org.neo4j.cypher.javacompat.internal.ServerExecutionEngine.executeQuery(ServerExecutionEngine.java:61)
    at org.neo4j.shell.kernel.apps.cypher.Start.getResult(Start.java:86)
    at org.neo4j.shell.kernel.apps.cypher.Start.exec(Start.java:68)
    at org.neo4j.shell.kernel.apps.TransactionProvidingApp.execute(TransactionProvidingApp.java:223)
    at org.neo4j.shell.impl.AbstractAppServer.interpretLine(AbstractAppServer.java:126)
    at org.neo4j.shell.kernel.GraphDatabaseShellServer.interpretLine(GraphDatabaseShellServer.java:96)
    at org.neo4j.shell.impl.RemotelyAvailableServer.interpretLine(RemotelyAvailableServer.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322)
    at sun.rmi.transport.Transport$2.run(Transport.java:202)
    at sun.rmi.transport.Transport$2.run(Transport.java:199)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:198)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:567)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.access$400(TCPTransport.java:619)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$1.run(TCPTransport.java:684)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$1.run(TCPTransport.java:681)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:681)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

The help is much appreciated by the way!

**Comment by jexp** [comment]
It seems you have somewhere in your config still cypher compiler version 2.0 set

You can see it in your stacktrace here: `.v2_0.`

```
Caused by: java.lang.NoSuchMethodError: org.neo4j.kernel.impl.core.NodeManager.isDeleted(Lorg/neo4j/graphdb/Node;)Z
    at org.neo4j.cypher.internal.compiler.v2_0.mutation.DeleteEntityAction.org$neo4j$cypher$internal$compiler$v2_0$mutation$DeleteEntityAction$$delete(DeleteEntityAction.scala:49)
    at org.neo4j.cypher.internal.compiler.v2_0.mutation.DeleteEntityAction.exec(DeleteEntityAction.scala:36)

```

If I prefix my query in my shell with cypher 2.0 it fails in the same way:

```
cypher 2.0 match (n {name:"Foo"}) delete n;
Exception in thread "main" java.lang.NoSuchMethodError: org.neo4j.kernel.impl.core.NodeManager.isDeleted(Lorg/neo4j/graphdb/Node;)Z
    at org.neo4j.cypher.internal.compiler.v2_0.mutation.DeleteEntityAction.org$neo4j$cypher$internal$compiler$v2_0$mutation$DeleteEntityAction$$delete(DeleteEntityAction.scala:49)
    at org.neo4j.cypher.internal.compiler.v2_0.mutation.DeleteEntityAction.exec(DeleteEntityAction.scala:36)
    at org.neo4j.cypher.internal.compiler.v2_0.pipes.ExecuteUpdateCommandsPipe.org$neo4j$cypher$internal$compiler$v2_0$pipes$ExecuteUpdateCommandsPipe$$exec(ExecuteUpdateCommandsPipe.scala:56)
    at org.neo4j.cypher.internal.compiler.v2_0.pipes.ExecuteUpdateCommandsPipe$$anonfun$org$neo4j$cypher$internal$compiler$v2_0$pipes$ExecuteUpdateCommandsPipe$$executeMutationCommands$1$$anonfun$apply$2.apply(ExecuteUpdateCommandsPipe.scala:45)
    at org.neo4j.cypher.internal.compiler.v2_0.pipes.ExecuteUpdateCommandsPipe$$anonfun$org$neo4j$cypher$internal$compiler$v2_0$pipes$ExecuteUpdateCommandsPipe$$executeMutationCommands$1$$anonfun$apply$2.apply(ExecuteUpdateCommandsPipe.scala:45)
```

**Comment by jjaburke91** [comment]
That's the issue indeed! That's it all sorted now.

Thanks again for your help @jexp, you're a star!

**Comment by Mats-SX** [comment]
Fixed by https://github.com/neo4j/neo4j/pull/6206
