### ISSUE TITLE
InternalBeginTransactionError on 2.2.7 or 2.2.8

### ISSUE THREAD

**Issue by aseemk** [neo4j/neo4j#6196]
We just upgraded from 2.2.7 to 2.2.8, and when we did our master failover (the very last instance to get upgraded), we got a few `Neo.DatabaseError.Transaction.CouldNotBegin` errors.

Full stack trace:

```
org.neo4j.server.rest.transactional.error.InternalBeginTransactionError: Unable to begin transaction.
    at org.neo4j.server.rest.transactional.TransactionHandle.ensureActiveTransaction(TransactionHandle.java:246)
    at org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:143)
    at org.neo4j.server.rest.web.TransactionalService$2.write(TransactionalService.java:211)
    at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
    at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
    at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
    at org.neo4j.server.guard.GuardingRequestFilter.doFilter(GuardingRequestFilter.java:68)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at ch.qos.logback.access.servlet.TeeFilter.doFilter(TeeFilter.java:55)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.neo4j.server.guard.GuardingRequestFilter.doFilter(GuardingRequestFilter.java:68)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:497)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: org.neo4j.kernel.ha.lock.forseti.ForsetiLockManager@12d4590b already closed
    at org.neo4j.kernel.ha.lock.forseti.ForsetiLockManager.newClient(ForsetiLockManager.java:154)
    at org.neo4j.kernel.ha.lock.SlaveLockManager.newClient(SlaveLockManager.java:49)
    at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.neo4j.kernel.ha.DelegateInvocationHandler.proxyInvoke(DelegateInvocationHandler.java:102)
    at org.neo4j.kernel.ha.DelegateInvocationHandler.invoke(DelegateInvocationHandler.java:94)
    at com.sun.proxy.$Proxy25.newClient(Unknown Source)
    at org.neo4j.kernel.impl.api.KernelTransactionImplementation.initialize(KernelTransactionImplementation.java:215)
    at org.neo4j.kernel.impl.api.KernelTransactions.newInstance(KernelTransactions.java:177)
    at org.neo4j.kernel.impl.api.Kernel.newTransaction(Kernel.java:83)
    at org.neo4j.kernel.InternalAbstractGraphDatabase.beginTx(InternalAbstractGraphDatabase.java:949)
    at org.neo4j.kernel.ha.HighlyAvailableGraphDatabase.beginTx(HighlyAvailableGraphDatabase.java:245)
```

I'm not sure yet whether these requests were to the 2.2.7 instance just after being upgraded to 2.2.8, or just before, or to the 2.2.8 instance that took over as master. I'll try to find out.

Even if this error can't be fixed, would it perhaps be good to classify this as a `TransientError`, so clients can automatically retry? (Similar to issue #5257.)

Thanks!

**Comment by spacecowboy** [comment]
Sounds like you did a rolling upgrade which is not supported on 2.2.8 (as mentioned in the manual here: http://neo4j.com/docs/2.2.8/ha-upgrade-guide.html)
To upgrade to 2.2.8, you have to shut down the cluster and upgrade in isolation.

So it seems the error message is in fact correct in that you shouldn't retry the transaction because it won't work.

**Comment by jjaderberg** [comment]
@aseemk From skimming the issue I think this can be closed; please comment if you think there is something actionable that I have missed.
