### ISSUE TITLE
Problem with unmanaged extension

### ISSUE THREAD

**Issue by fabiotarantino** [neo4j/neo4j#6198]
Hi,
i'm experiencing an issue when trying to install an unmanaged extension. It seems something related to jersey: ERROR The ResourceConfig instance does not contain any root resource classes. 
Any idea? Thank you!

My environment: OSX El Capitan, neo4j 2.3.1 (tar version).  
In neo4j-server.properties:
org.neo4j.server.thirdparty_jaxrs_classes=com.bitgears.socialgears.gdb.neo4j.plugin=/socialgears

```
package com.bitgears.socialgears.gdb.neo4j.plugin;
import ...

@Path("/socialgears")
public class SocialGearsSearchNodes {

   private GraphDatabaseService graphDb;
   private final ObjectMapper objectMapper;

   public SocialGearsSearchNodes( @Context GraphDatabaseService graphDb )  {
       this.graphDb = graphDb;
       this.objectMapper = new ObjectMapper();
  }

   @POST
   @Path("/searchnodes")
   @Consumes("application/json")
   @Produces("application/json")
   public Response searchNodes(
           final String query,
           final Map<String, Object> params,
           final SearchJoin mainObj, 
           final SearchJoin[] nestedObjList
           ) {

        StreamingOutput stream = new StreamingOutput()  {

       ....
```

Following are errors on log file:

2016-01-12 01:15:36.323+0100 INFO  Mounted unmanaged extension [com.bitgears.socialgears.gdb.neo4j.plugin] at [/socialgears]
2016-01-12 01:15:36.408+0100 INFO  Mounting static content at /webadmin
2016-01-12 01:15:36.450+0100 INFO  Mounting static content at /browser
2016-01-12 01:15:37.125+0100 ERROR The ResourceConfig instance does not contain any root resource classes.
2016-01-12 01:15:37.125+0100 WARN  unavailable The ResourceConfig instance does not contain any root resource classes.
com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
    at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:99)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1359)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:180)
    at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:799)

**Comment by fabiotarantino** [comment]
i would like to add a note: if you start the server from command line, a wrong (or ambiguous) response is printed

MacBook-Pro-di-Bitgears:bin bitgears$ /Users/bitgears/dev/neo4j-community-2.3.1/bin/neo4j start
Starting Neo4j Server...WARNING: not changing user
process [3130]... waiting for server to be ready...... OK.
http://localhost:17474/ is ready.
MacBook-Pro-di-Bitgears:bin bitgears$ /Users/bitgears/dev/neo4j-community-2.3.1/bin/neo4j stop
ERROR: Neo4j Server not running
MacBook-Pro-di-Bitgears:bin bitgears$

**Comment by jexp** [comment]
In general it looks good. You put the jar with that class any any eventual dependencies into the plugins directory?

Do you have other classes in that package?

**Comment by jexp** [comment]
No answer/feedback from @fabiotarantino for 2 months, closing. Please reopen if you can supply the requested information.
