### ISSUE TITLE
`Neo4jImport --quote \0 ...` wont work

### ISSUE THREAD

**Issue by helt** [neo4j/neo4j#6209]
Importing CSV using `Neo4jImport --quote \0 ...` as indicated by http://stackoverflow.com/a/34111573/978392 wont work, because `\0` are _two_ characters, where only one single character is accepted by the converter.

I forced the error by checking out branch `2.3` and creating a compiled a custom 2.3.2-SNAPSHOT, which includes #6034.

It yields this console output:

```
C:\...\data>Neo4jImport --quote \0 --into xyz.db --delimiter TAB  --id-type string 
--nodes:MyNodeType MyNodes_header.txt,MyNodes.txt 
--relationships:LINKSTO MyLinks_header.txt,MyLinks.txt

WARNING! This batch script has been deprecated. Please use the provided PowerShell scripts instead: http://neo4j.com/docs/stable/powershell.html
The system cannot find the path specified.
Input error: Invalid delimiter '\0', expected one character
Caused by:Invalid delimiter '\0', expected one character
java.lang.IllegalArgumentException: Invalid delimiter '\0', expected one character
        at org.neo4j.kernel.impl.util.Converters$9.apply(Converters.java:149)
        at org.neo4j.kernel.impl.util.Converters$9.apply(Converters.java:143)
        at org.neo4j.helpers.Args.interpretOption(Args.java:533)
        at org.neo4j.tooling.ImportTool.csvConfiguration(ImportTool.java:635)
        at org.neo4j.tooling.ImportTool.main(ImportTool.java:335)
        at org.neo4j.tooling.ImportTool.main(ImportTool.java:279)

```

https://github.com/neo4j/neo4j/blob/2.3/community/kernel/src/main/java/org/neo4j/kernel/impl/util/Converters.java#L149

**Comment by spacecowboy** [comment]
@helt Thank you for the report. We'll get this sorted.
