### ISSUE TITLE
[2.3.1] StackOverflowError on executing large queries.

### ISSUE THREAD

**Issue by FylmTM** [neo4j/neo4j#6239]
Hi,

We receiving `StackOverflowError` on executing large Cypher queries.
Error is thrown during Cypher query parsing.

Code to reproduce problem:

``` java
public class NeoBugTest {

    private static final int NODE_COUNT = 2000;

    @Test
    public void testLargeCreateNodeCypherForEmbedded() throws Exception {
        final GraphDatabaseService db = new GraphDatabaseFactory().newEmbeddedDatabase(Files.createTempDir());
        final Map<String, Object> properties = new HashMap<>();
        final String pattern = "(n%s)";

        // Build large query
        // Example: CREATE (n1),(n2),(n3),(n4)
        final StringBuilder query = new StringBuilder("CREATE ");
        for (int i = 0; i < NODE_COUNT; i++) {
            query.append(String.format(pattern, i));
            if (i < NODE_COUNT - 1) {
                query.append(",");
            }
        }

        try (final Transaction transaction = db.beginTx()) {
            db.execute(query.toString(), properties); // <--- java.lang.StackOverflowError
            transaction.success();
        }
    }
}
```

Stacktrace sample:

```
java.lang.StackOverflowError
    at scala.collection.mutable.ArrayBuilder$.make(ArrayBuilder.scala:37)
    at scala.Array$$anon$2.apply(Array.scala:64)
    at scala.Array$$anon$2.apply(Array.scala:62)
    at scala.collection.package$$anon$1.apply(package.scala:87)
    at scala.collection.SeqLike$class.reverseMap(SeqLike.scala:286)
    at scala.collection.AbstractSeq.reverseMap(Seq.scala:41)
    at scala.collection.mutable.ArrayStack$.apply(ArrayStack.scala:27)
    at org.neo4j.cypher.internal.frontend.v2_3.Foldable$$anonfun$org$neo4j$cypher$internal$frontend$v2_3$Foldable$$treeFoldAcc$1.apply(Foldable.scala:82)
    at org.neo4j.cypher.internal.compiler.v2_3.ast.rewriters.literalReplacement$$anonfun$3$$anonfun$applyOrElse$12.apply(literalReplacement.scala:64)
    at org.neo4j.cypher.internal.compiler.v2_3.ast.rewriters.literalReplacement$$anonfun$3$$anonfun$applyOrElse$12.apply(literalReplacement.scala:64)
    at org.neo4j.cypher.internal.frontend.v2_3.Foldable$.org$neo4j$cypher$internal$frontend$v2_3$Foldable$$treeFoldAcc(Foldable.scala:82)
    at org.neo4j.cypher.internal.frontend.v2_3.Foldable$$anonfun$org$neo4j$cypher$internal$frontend$v2_3$Foldable$$treeFoldAcc$1.apply(Foldable.scala:82)
    at org.neo4j.cypher.internal.compiler.v2_3.ast.rewriters.literalReplacement$$anonfun$3$$anonfun$applyOrElse$12.apply(literalReplacement.scala:64)
    at org.neo4j.cypher.internal.compiler.v2_3.ast.rewriters.literalReplacement$$anonfun$3$$anonfun$applyOrElse$12.apply(literalReplacement.scala:64)
    at org.neo4j.cypher.internal.frontend.v2_3.Foldable$.org$neo4j$cypher$internal$frontend$v2_3$Foldable$$treeFoldAcc(Foldable.scala:82)
    at org.neo4j.cypher.internal.frontend.v2_3.Foldable$$anonfun$org$neo4j$cypher$internal$frontend$v2_3$Foldable$$treeFoldAcc$1.apply(Foldable.scala:82)
    at org.neo4j.cypher.internal.compiler.v2_3.ast.rewriters.literalReplacement$$anonfun$3$$anonfun$applyOrElse$12.apply(literalReplacement.scala:64)
    at org.neo4j.cypher.internal.compiler.v2_3.ast.rewriters.literalReplacement$$anonfun$3$$anonfun$applyOrElse$12.apply(literalReplacement.scala:64)
    at org.neo4j.cypher.internal.frontend.v2_3.Foldable$.org$neo4j$cypher$internal$frontend$v2_3$Foldable$$treeFoldAcc(Foldable.scala:82)
    at org.neo4j.cypher.internal.frontend.v2_3.Foldable$$anonfun$org$neo4j$cypher$internal$frontend$v2_3$Foldable$$treeFoldAcc$1.apply(Foldable.scala:82)
    at org.neo4j.cypher.internal.compiler.v2_3.ast.rewriters.literalReplacement$$anonfun$3$$anonfun$applyOrElse$12.apply(literalReplacement.scala:64)
    at org.neo4j.cypher.internal.compiler.v2_3.ast.rewriters.literalReplacement$$anonfun$3$$anonfun$applyOrElse$12.apply(literalReplacement.scala:64)
    at org.neo4j.cypher.internal.frontend.v2_3.Foldable$.org$neo4j$cypher$internal$frontend$v2_3$Foldable$$treeFoldAcc(Foldable.scala:82)
...
```

Similar errors are thrown (in other places) when query contains:
- Labels: `(n:Label)`
- Parameter `(n:Label {p})`

**Comment by jexp** [comment]
Can you share an example for they query?
How long is it?

The parser is not meant for parsing gigantic queries :)
Or in this case the rewriter.

**Comment by FylmTM** [comment]
@jexp In our use case we have 2000 nodes.

Query example:

```
CREATE (n1), (n2), (n3) ... (n1999), (n2000)
```

Exploring Cypher parser code, looks like that in some places "recursive"-ish algorithms are used to modify/check AST.

**Example:**

Instead of:

``` java
while (iterator.hasNext()) {
  doStuff(iterator.next());
} 
```

It looks like this:

``` java
public void doStuff(iterator) {
  obj = iterator.next();
  if (iterator.hasNext()) {
    doStuff(iterator);       
  }   
}
```

So. For each iterator object new frame is created.
And when we have `Pattern` node with 2000 `PatternPart` child nodes we end up with `StackOverflowError`.

**Comment by Mats-SX** [comment]
Hello @FylmTM. There have been fixes merged to deal with issues like these. When I run your test code above, it does not cause a `StackOverflowException`.

I'm going to close this as fixed, but please correct me if I am wrong and then we can reopen this.
