### ISSUE TITLE
org.neo4j.com.ComException: MasterClient214 could not connect to /192.168.1.127:6001

### ISSUE THREAD

**Issue by xghrbc1001** [neo4j/neo4j#6319]
neo4j version 2.2.5,ha mode,some times this exception occus.

```
org.neo4j.com.ComException: MasterClient214 could not connect to /192.168.1.127:6001
        at org.neo4j.com.Client$1.create(Client.java:151)
        at org.neo4j.com.Client$1.create(Client.java:135)
        at org.neo4j.com.ResourcePool.acquire(ResourcePool.java:176)
        at org.neo4j.com.Client.acquireChannelContext(Client.java:302)
        at org.neo4j.com.Client.sendRequest(Client.java:214)
        at org.neo4j.com.Client.sendRequest(Client.java:207)
        at org.neo4j.kernel.ha.MasterClient210.newLockSession(MasterClient210.java:213)
        at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.neo4j.kernel.ha.DelegateInvocationHandler.proxyInvoke(DelegateInvocationHandler.java:108)
        at org.neo4j.kernel.ha.DelegateInvocationHandler.access$100(DelegateInvocationHandler.java:45)
        at org.neo4j.kernel.ha.DelegateInvocationHandler$Concrete.invoke(DelegateInvocationHandler.java:159)
        at com.sun.proxy.$Proxy4.newLockSession(Unknown Source)
        at org.neo4j.kernel.ha.lock.SlaveLocksClient.makeSureTxHasBeenInitialized(SlaveLocksClient.java:315)
        at org.neo4j.kernel.ha.lock.SlaveLocksClient.acquireExclusiveOnMaster(SlaveLocksClient.java:283)
        at org.neo4j.kernel.ha.lock.SlaveLocksClient.acquireExclusive(SlaveLocksClient.java:123)
        at org.neo4j.kernel.impl.api.LockingStatementOperations.nodeRemoveProperty(LockingStatementOperations.java:331)
        at org.neo4j.kernel.impl.api.OperationsFacade.nodeRemoveProperty(OperationsFacade.java:678)
        at org.neo4j.kernel.impl.core.NodeProxy.removeProperty(NodeProxy.java:320)
```

**Comment by chrisvest** [comment]
This is fixed in 2.2.8: http://neo4j.com/release-notes/neo4j-2-2-8/
