### ISSUE TITLE
NullPointerException in CommonAbstractStore#nextId

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#6335]
```
java.lang.NullPointerException: null
at org.neo4j.kernel.impl.store.CommonAbstractStore.nextId(CommonAbstractStore.java:419)
at org.neo4j.kernel.impl.api.store.DiskLayer.reserveNode(DiskLayer.java:678)
at org.neo4j.kernel.impl.api.store.CacheLayer.reserveNode(CacheLayer.java:457)
at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.nodeCreate(StateHandlingStatementOperations.java:323)
at org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.nodeCreate(ConstraintEnforcingEntityOperations.java:368)
at org.neo4j.kernel.impl.api.LockingStatementOperations.nodeCreate(LockingStatementOperations.java:267)
at org.neo4j.kernel.impl.api.OperationsFacade.nodeCreate(OperationsFacade.java:851)
at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.createNode(GraphDatabaseFacade.java:187)
```

Seeing this for the first time. 

messages.log contains this:

```
2016-02-01 15:05:36.745+0000 ERROR [o.n.k.i.DiagnosticsManager] Failure while logging diagnostics for org.neo4j.kernel.info.DiagnosticsManager$ExtractedDiagnosticsProvider@53d91c95
java.lang.NullPointerException
at org.neo4j.kernel.impl.store.CommonAbstractStore.getNumberOfIdsInUse(CommonAbstractStore.java:701)
at org.neo4j.kernel.impl.store.CommonAbstractStore.logIdUsage(CommonAbstractStore.java:725)
at org.neo4j.kernel.impl.store.NeoStores.logIdUsage(NeoStores.java:648)
at org.neo4j.kernel.NeoStoreDataSource$Diagnostics$2.dump(NeoStoreDataSource.java:276)
at org.neo4j.kernel.NeoStoreDataSource$Diagnostics.dumpDiagnostics(NeoStoreDataSource.java:330)
at org.neo4j.kernel.NeoStoreDataSource$Diagnostics$2.dumpDiagnostics(NeoStoreDataSource.java:271)
at org.neo4j.kernel.info.DiagnosticsManager$ExtractedDiagnosticsProvider.dump(DiagnosticsManager.java:316)
at org.neo4j.kernel.info.DiagnosticsManager.dump(DiagnosticsManager.java:263)
at org.neo4j.kernel.info.DiagnosticsManager.dump(DiagnosticsManager.java:255)
at org.neo4j.kernel.info.DiagnosticsManager.appendProvider(DiagnosticsManager.java:249)
at org.neo4j.kernel.info.DiagnosticsManager.register(DiagnosticsManager.java:225)
at org.neo4j.kernel.info.DiagnosticsManager.registerAll(DiagnosticsManager.java:232)
at org.neo4j.kernel.NeoStoreDataSource.registerDiagnosticsWith(NeoStoreDataSource.java:1288)
at org.neo4j.kernel.impl.factory.EditionModule.doAfterRecoveryAndStartup(EditionModule.java:72)
at org.neo4j.kernel.ha.factory.HighlyAvailableEditionModule.doAfterRecoveryAndStartup(HighlyAvailableEditionModule.java:786)
at org.neo4j.kernel.ha.factory.HighlyAvailableEditionModule$15.doAfterRecoveryAndStartup(HighlyAvailableEditionModule.java:757)
at org.neo4j.kernel.ha.factory.HighlyAvailableEditionModule$15.masterIsAvailable(HighlyAvailableEditionModule.java:734)
at org.neo4j.kernel.ha.cluster.HighAvailabilityMemberStateMachine$StateMachineClusterEventListener$2.notify(HighAvailabilityMemberStateMachine.java:207)
at org.neo4j.kernel.ha.cluster.HighAvailabilityMemberStateMachine$StateMachineClusterEventListener$2.notify(HighAvailabilityMemberStateMachine.java:203)
at org.neo4j.helpers.Listeners.notifyListeners(Listeners.java:64)
at org.neo4j.kernel.ha.cluster.HighAvailabilityMemberStateMachine$StateMachineClusterEventListener.memberIsAvailable(HighAvailabilityMemberStateMachine.java:201)
at org.neo4j.cluster.member.paxos.PaxosClusterMemberEvents$AtomicBroadcastListenerImpl$1.notify(PaxosClusterMemberEvents.java:372)
at org.neo4j.cluster.member.paxos.PaxosClusterMemberEvents$AtomicBroadcastListenerImpl$1.notify(PaxosClusterMemberEvents.java:368)
at org.neo4j.helpers.Listeners.notifyListeners(Listeners.java:64)
at org.neo4j.cluster.member.paxos.PaxosClusterMemberEvents$AtomicBroadcastListenerImpl.receive(PaxosClusterMemberEvents.java:367)
at org.neo4j.cluster.protocol.atomicbroadcast.multipaxos.context.AtomicBroadcastContextImpl$1.notify(AtomicBroadcastContextImpl.java:77)
at org.neo4j.cluster.protocol.atomicbroadcast.multipaxos.context.AtomicBroadcastContextImpl$1.notify(AtomicBroadcastContextImpl.java:73)
at org.neo4j.helpers.Listeners$1.run(Listeners.java:87)
at org.neo4j.cluster.DelayedDirectExecutor.drain(DelayedDirectExecutor.java:93)
at org.neo4j.cluster.StateMachines$1.run(StateMachines.java:216)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:99)

```

But after that:

```
2016-02-01 15:05:36.822+0000 INFO  [o.n.k.h.HighAvailabilityLogger] Database available for write transactions
2016-02-01 15:05:36.822+0000 INFO  [o.n.k.h.f.HighlyAvailableFacadeFactory] Database is now ready

```

Also, :sysinfo show this:
![err](https://i.imgur.com/c7Vp4O7.png)

**Comment by tkroman** [comment]
Restarting the database in a single mode somehow healed IDs. But this is a valid bug still, IMO.

**Comment by spacecowboy** [comment]
Thanks for the report.

What version are you on? Am I correct in assuming you are using HA?

**Comment by tkroman** [comment]
Yes, this is an HA setup (2.3.2). We use a rather weird setup (I can't even tell why, the decision has been made without my participation): one instance is embedded into Java app and the slave is in standalone mode + configured as `slave_only`. We restarted the application and this embedded instance's logs had these lines. I stopped the app again, configured a standalone neo4j distribution to use app's data directory and it reconfigured itself OK. Then I stopped the standalone neo4j, started the app with an embedded DB and everything seems fine.

**Comment by lszumel** [comment]
Was this resolved or root caused?

We have seen the same error using _non-HA_. A restart similarly cleared up the error, but in the meantime our running instance was not functioning (other NPE's in org.neo4j during write transactions, for example allocating a new node id).

`2016-04-17 03:36:59.437+0000 INFO  [o.n.k.i.DiagnosticsManager] --- STARTED diagnostics for NEO_STORE_ID_USAGE START ---
2016-04-17 03:36:59.437+0000 INFO  [o.n.k.i.DiagnosticsManager] Id usage:
2016-04-17 03:36:59.437+0000 INFO  [o.n.k.i.DiagnosticsManager] Id usage:
2016-04-17 03:36:59.437+0000 ERROR [o.n.k.i.DiagnosticsManager] Failure while logging diagnostics for org.neo4j.kernel.info.DiagnosticsManager$ExtractedDiagnosticsProvider@6567b6a0
java.lang.NullPointerException
        at org.neo4j.kernel.impl.store.CommonAbstractStore.getNumberOfIdsInUse(CommonAbstractStore.java:673)
        at org.neo4j.kernel.impl.store.CommonAbstractStore.logIdUsage(CommonAbstractStore.java:697)
        at org.neo4j.kernel.impl.store.NeoStores.logIdUsage(NeoStores.java:648)
        at org.neo4j.kernel.NeoStoreDataSource$Diagnostics$2.dump(NeoStoreDataSource.java:276)
        at org.neo4j.kernel.NeoStoreDataSource$Diagnostics.dumpDiagnostics(NeoStoreDataSource.java:330)
        at org.neo4j.kernel.NeoStoreDataSource$Diagnostics$2.dumpDiagnostics(NeoStoreDataSource.java:271)
        at org.neo4j.kernel.info.DiagnosticsManager$ExtractedDiagnosticsProvider.dump(DiagnosticsManager.java:316)
        at org.neo4j.kernel.info.DiagnosticsManager.dump(DiagnosticsManager.java:263)
        at org.neo4j.kernel.info.DiagnosticsManager.dump(DiagnosticsManager.java:255)
        at org.neo4j.kernel.info.DiagnosticsManager.appendProvider(DiagnosticsManager.java:249)
        at org.neo4j.kernel.info.DiagnosticsManager.register(DiagnosticsManager.java:225)
        at org.neo4j.kernel.info.DiagnosticsManager.registerAll(DiagnosticsManager.java:232)
        at org.neo4j.kernel.NeoStoreDataSource.registerDiagnosticsWith(NeoStoreDataSource.java:1288)
        at org.neo4j.kernel.impl.factory.EditionModule.doAfterRecoveryAndStartup(EditionModule.java:72)
        at org.neo4j.kernel.impl.factory.CommunityEditionModule.doAfterRecoveryAndStartup(CommunityEditionModule.java:270)`

**Comment by spacecowboy** [comment]
@lszumel It fell through the cracks. Fixing it right now.

**Comment by spacecowboy** [comment]
Fix in https://github.com/neo4j/neo4j/pull/7013

**Comment by tinwelint** [comment]
@tkroman have you found a way to reliably reproduce this issue? There's a fix for the NPE, but there's a root cause behind it which I believe hasn't been addressed.

**Comment by andybarilla** [comment]
It happened to me after I ran out of heap space. I stopped the server and then started it again and got the error. The second time I restarted the server everything was fine again.

So to reproduce it I would say try and blow up the heap space.

**Comment by tinwelint** [comment]
We found the issue to be a broken transaction log, for example due to https://github.com/neo4j/neo4j/pull/7213
