### ISSUE TITLE
Invalid usage of PathValueBuilder, Node must be a node in Relationship

### ISSUE THREAD

**Issue by luanne** [neo4j/neo4j#6337]
[Neo4j 2.3.2]
For the following data,

```
create 
(_0:`Node` ),
(_1:`Node` ),
(_2:`Node` ),
(_3:`Node` ),
_0-[:EDGE]->_1,
_1-[:EDGE]->_2,
_2-[:EDGE]->_3
```

this query

```
MATCH ()-[r:`EDGE`]-() 
WITH r 
MATCH p=(n)-[*0..1]-()-[r]-()-[*0..1]-(m) 
RETURN p
```

throws 

```
Caused by:
org.neo4j.helpers.ThisShouldNotHappenError: Developer: pontus claims that: Invalid usage of PathValueBuilder, Node[1] must be a node in Relationship[2]
    at org.neo4j.cypher.internal.compiler.v2_3.commands.expressions.PathValueBuilder$$anonfun$addUndirectedRelationship$1.apply(PathValueBuilder.scala:60)
    at org.neo4j.cypher.internal.compiler.v2_3.commands.expressions.PathValueBuilder$$anonfun$addUndirectedRelationship$1.apply(PathValueBuilder.scala:58)
    at org.neo4j.cypher.internal.compiler.v2_3.commands.expressions.PathValueBuilder.nullCheck(PathValueBuilder.scala:105)
    at org.neo4j.cypher.internal.compiler.v2_3.commands.expressions.PathValueBuilder.addUndirectedRelationship(PathValueBuilder.scala:57)
    at org.neo4j.cypher.internal.compiler.v2_3.commands.expressions.ProjectedPath$singleUndirectedRelationshipProjector.apply(ProjectedPath.scala:53)
    at.......
```

However, limiting to a single relationship (for all values of ID(r)) works fine-

```
MATCH ()-[r:`EDGE`]-()
WHERE ID(r)=2
WITH r
MATCH p=(n)-[*0..1]-()-[r]-()-[*0..1]-(m)
RETURN p
```

**Comment by Mats-SX** [comment]
@luanne Thank you for reporting this.

We have implemented a fix in #6368, which will be included in the soon upcoming `3.0.0-M04`. Please reopen if the problem persists.
