### ISSUE TITLE
NullPointerException in AsyncLogEvent#logEvent

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#6348]
My slave instance is permanently stuck in a loop that looks like this:

```
2016-02-03 15:44:20.964+0000 DEBUG [o.n.c.p.a.m.LearnerState$2] [AsyncLog @ 2016-02-03 15:44:20.964+0000]  LearnerState: learner-[learnTimedout]->learner conversation-id:20/13#
2016-02-03 15:44:20.964+0000 DEBUG [o.n.c.p.h.HeartbeatState$1] [AsyncLog @ 2016-02-03 15:44:20.964+0000]  HeartbeatState: start-[reset_send_heartbeat]->start conversation-id:20/13# payload:10
2016-02-03 15:44:20.975+0000 WARN  [o.n.c.s.StateMachine] [AsyncLog @ 2016-02-03 15:44:20.974+0000]  Exception in message handling Throwable
java.lang.NullPointerException: Throwable
        at java.util.Objects.requireNonNull(Objects.java:228)
        at org.neo4j.logging.async.AsyncLogEvent.logEvent(AsyncLogEvent.java:44)
        at org.neo4j.logging.async.AsyncLog$AsyncLogger.log(AsyncLog.java:99)
        at org.neo4j.logging.AbstractLog.warn(AbstractLog.java:76)
        at org.neo4j.kernel.impl.util.CappedLogger.warn(CappedLogger.java:75)
        at org.neo4j.cluster.protocol.atomicbroadcast.multipaxos.context.LearnerContextImpl.notifyLearnMiss(LearnerContextImpl.java:178)
        at org.neo4j.cluster.protocol.atomicbroadcast.multipaxos.LearnerState$2.handle(LearnerState.java:223)
        at org.neo4j.cluster.protocol.atomicbroadcast.multipaxos.LearnerState$2.handle(LearnerState.java:58)
        at org.neo4j.cluster.statemachine.StateMachine.handle(StateMachine.java:88)
        at org.neo4j.cluster.StateMachines$1.handleMessage(StateMachines.java:222)
        at org.neo4j.cluster.StateMachines$1.run(StateMachines.java:154)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:99)
2016-02-03 15:44:20.975+0000 DEBUG [o.n.c.p.h.HeartbeatState$1] [AsyncLog @ 2016-02-03 15:44:20.975+0000]  HeartbeatState: start-[i_am_alive]->start from:cluster://192.168.4.133:47012 conversation-id:20/13# payl
oad:i_am_alive[10]
2016-02-03 15:44:20.975+0000 WARN  [o.n.c.s.StateMachine] [AsyncLog @ 2016-02-03 15:44:20.975+0000]  Exception in message handling Throwable
java.lang.NullPointerException: Throwable
        at java.util.Objects.requireNonNull(Objects.java:228)
        at org.neo4j.logging.async.AsyncLogEvent.logEvent(AsyncLogEvent.java:44)
        at org.neo4j.logging.async.AsyncLog$AsyncLogger.log(AsyncLog.java:99)
        at org.neo4j.logging.AbstractLog.warn(AbstractLog.java:76)
        at org.neo4j.kernel.impl.util.CappedLogger.warn(CappedLogger.java:75)
        at org.neo4j.cluster.protocol.atomicbroadcast.multipaxos.context.LearnerContextImpl.notifyLearnMiss(LearnerContextImpl.java:178)
        at org.neo4j.cluster.protocol.atomicbroadcast.multipaxos.LearnerState$2.handle(LearnerState.java:223)
        at org.neo4j.cluster.protocol.atomicbroadcast.multipaxos.LearnerState$2.handle(LearnerState.java:58)
        at org.neo4j.cluster.statemachine.StateMachine.handle(StateMachine.java:88)
        at org.neo4j.cluster.StateMachines$1.handleMessage(StateMachines.java:222)
        at org.neo4j.cluster.StateMachines$1.run(StateMachines.java:154)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:99)
```

... and so on. After this the slave instance cannot connect to the master instance and no additional info on how to handle the issue isn't provided.

**Comment by spacecowboy** [comment]
Thank you for the report.

Root cause is this null: https://github.com/neo4j/neo4j/blob/3.0/enterprise/cluster/src/main/java/org/neo4j/cluster/protocol/atomicbroadcast/multipaxos/context/LearnerContextImpl.java#L181

It should work to restart the slave instance (in the worst case, also delete `graph-db` directory so a fresh copy is made directly from master)
