### ISSUE TITLE
Provide a way to perform "tx recovery/restart"

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#6490]
... whatever that might be.

I raised this issue some time ago, and in a brief discussion a suggestion was made that I try to guard threads using neo4j from interruption. While that is certainly the right way to deal with the problem causing this behaviour, I still think that there should be some mechanism that allows for recovery in such cases:

```
org.neo4j.kernel.api.exceptions.TransactionFailureException: Kernel has encountered some problem, please perform necessary action (tx recovery/restart)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.neo4j.kernel.KernelHealth.assertHealthy(KernelHealth.java:61)
    at org.neo4j.kernel.impl.api.Kernel.newTransaction(Kernel.java:81)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTx(GraphDatabaseFacade.java:309)
    ... 32 more
Caused by: java.nio.channels.ClosedByInterruptException
    at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
    at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:216)
    at org.neo4j.io.fs.StoreFileChannel.write(StoreFileChannel.java:153)
    at org.neo4j.kernel.impl.transaction.log.PhysicalLogVersionedStoreChannel.write(PhysicalLogVersionedStoreChannel.java:112)
    at org.neo4j.kernel.impl.transaction.log.PhysicalWritableLogChannel.emptyBufferIntoChannelAndClearIt(PhysicalWritableLogChannel.java:65)
    at org.neo4j.kernel.impl.transaction.log.BatchingTransactionAppender.force(BatchingTransactionAppender.java:402)
    at org.neo4j.kernel.impl.transaction.log.BatchingTransactionAppender.forceLog(BatchingTransactionAppender.java:355)
    at org.neo4j.kernel.impl.transaction.log.BatchingTransactionAppender.forceAfterAppend(BatchingTransactionAppender.java:327)
    at org.neo4j.kernel.impl.transaction.log.BatchingTransactionAppender.append(BatchingTransactionAppender.java:141)
    at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.appendToLog(TransactionRepresentationCommitProcess.java:82)
    at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:57)
    at org.neo4j.kernel.ha.MasterTransactionCommitProcess.commit(MasterTransactionCommitProcess.java:56)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.neo4j.kernel.ha.DelegateInvocationHandler.proxyInvoke(DelegateInvocationHandler.java:103)
    at org.neo4j.kernel.ha.DelegateInvocationHandler.invoke(DelegateInvocationHandler.java:95)
    at com.sun.proxy.$Proxy53.commit(Unknown Source)
    at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:565)
    at org.neo4j.kernel.impl.api.KernelTransactionImplementation.close(KernelTransactionImplementation.java:458)
    at org.neo4j.kernel.TopLevelTransaction.close(TopLevelTransaction.java:97)
```

I wouldn't make such a big deal of this, but the problem is that the channel behind the e.g. transaction log is left in an interrupted state, which results in a general unavailability of the database for normal operation.
I understand that some data loss is imminent (especially in case of interrupts during the `close()` calls), but at the same time I think that there should be some way of 'refreshing' the state of the database without bringing it down so that we could, as exception message says, "perform necessary action (tx recovery/restart)".

Last time we discussed this (https://github.com/neo4j/neo4j/issues/4539#issuecomment-97355262), @chrisvest said that this is the natural way. I myself don't see any 'natural' way to do this (the one that could be general enough to satisfy everyone), but maybe supplying an option for just re-initialising all the NIO spaghetti for those willing to risk that minimal data loss might be an option? 

In case it really isn't, maybe that exception text should be less misleading at least? The reason behind me raising this again is that a colleague of mine came up to me asking what is this tx recovery and how does one do it and left quite confused after I told him to "switch it on and off".

**Comment by chrisvest** [comment]
Yeah, this is only the natural way in NIOs twisted little world; and it's a royal ache in the aft. I'll make sure we're tracking this internally.

**Comment by RodrigoLimasss** [comment]
I had the same problem.

The dir where Neo4j is installed was 100% usage on my Linux.
I simply moved the 'data' folder to another dir with more space and changed the path in the 'conf/ neo4j.conf'.

Then I deleted the 'data/' folder in Neo4j path.

**Comment by chrisvest** [comment]
In 3.3 the error message is now much nicer. Making the transaction log interruption-safe is a bigger story that we are already tracking internally, so I will close this issue.
