### ISSUE TITLE
JsonGenerationException

### ISSUE THREAD

**Issue by rotten** [neo4j/neo4j#6575]
I'm observing this exception in the console log [Community Edition 2.3.2] every now and then.  I'm not certain what is tripping it.  I occasionally have a query "never return",  and I suspect those queries are what causes it. (the subsequent 2 lines from the console.log indicate that may be the case)  While I'm trying to reproduce this exception consistently, I thought I'd report the issue just in case the stack trace by itself is enough of a hint to someone somewhere.  Maybe this is expected behavior?

There is nothing unusual in the messages.log from around that time.  (default logging settings)

```
2016-03-01 14:37:53.507+0000 ERROR Failed to generate JSON output. Current context not an ARRAY but OBJECT
org.codehaus.jackson.JsonGenerationException: Current context not an ARRAY but OBJECT
    at org.codehaus.jackson.impl.JsonGeneratorBase._reportError(JsonGeneratorBase.java:480)
    at org.codehaus.jackson.impl.Utf8Generator.writeEndArray(Utf8Generator.java:354)
    at org.neo4j.server.rest.transactional.RestRepresentationWriter.write(RestRepresentationWriter.java:63)
    at org.neo4j.server.rest.transactional.ExecutionResultSerializer$1.visit(ExecutionResultSerializer.java:444)
    at org.neo4j.cypher.internal.compiler.v2_3.helpers.iteratorToVisitable$.accept(iteratorToVisitable.scala:36)
    at org.neo4j.cypher.internal.compiler.v2_3.PipeExecutionResult.accept(PipeExecutionResult.scala:114)
    at org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor2_3$$anonfun$accept$1.apply$mcV$sp(CompatibilityFor2_3.scala:336)
    at org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor2_3$$anonfun$accept$1.apply(CompatibilityFor2_3.scala:335)
    at org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor2_3$$anonfun$accept$1.apply(CompatibilityFor2_3.scala:335)
    at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_3$.runSafely(CompatibilityFor2_3.scala:116)
    at org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor2_3.accept(CompatibilityFor2_3.scala:335)
    at org.neo4j.cypher.javacompat.ExecutionResult.accept(ExecutionResult.java:309)
    at org.neo4j.server.rest.transactional.ExecutionResultSerializer.writeRows(ExecutionResultSerializer.java:436)
    at org.neo4j.server.rest.transactional.ExecutionResultSerializer.statementResult(ExecutionResultSerializer.java:110)
    at org.neo4j.server.rest.transactional.TransactionHandle.executeStatements(TransactionHandle.java:330)
    at org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:147)
    at org.neo4j.server.rest.web.TransactionalService$2.write(TransactionalService.java:211)
    at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
    at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
    at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
    at org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:497)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
    at java.lang.Thread.run(Thread.java:745)
2016-03-01 14:37:53.517+0000 ERROR Unable to reply to request, because the client has closed the connection (Broken pipe).
2016-03-01 14:37:53.518+0000 ERROR Unable to reply to request, because the client has closed the connection (Broken pipe).
```

messages.log from the same time window:

```
2016-03-01 14:34:29.945+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [250859908]:  Starting check pointing...
2016-03-01 14:34:29.946+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [250859908]:  Starting store flush...
2016-03-01 14:34:29.946+0000 INFO  [o.n.k.i.s.c.CountsTracker] About to rotate counts store at transaction 250859908 to [/home/neo4j/neo4j-community-2.3.2/data/graph.db/neostore.counts.db.a], from [/home/neo4j/neo4j-community-2.3.2/data/graph.db/neostore.counts.db.b].
2016-03-01 14:34:29.951+0000 INFO  [o.n.k.i.s.c.CountsTracker] Successfully rotated counts store at transaction 250859908 to [/home/neo4j/neo4j-community-2.3.2/data/graph.db/neostore.counts.db.a], from [/home/neo4j/neo4j-community-2.3.2/data/graph.db/neostore.counts.db.b].
2016-03-01 14:34:35.782+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [250859908]:  Store flush completed
2016-03-01 14:34:35.782+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [250859908]:  Starting appending check point entry into the tx log...
2016-03-01 14:34:35.783+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [250859908]:  Appending check point entry into the tx log completed
2016-03-01 14:34:35.783+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [250859908]:  Check pointing completed
2016-03-01 14:34:35.783+0000 INFO  [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [1983]:  Starting log pruning.
2016-03-01 14:34:35.783+0000 INFO  [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [1983]:  Log pruning complete.
2016-03-01 14:40:35.790+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [250859909]:  Starting check pointing...
2016-03-01 14:40:35.790+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [250859909]:  Starting store flush...
2016-03-01 14:40:35.791+0000 INFO  [o.n.k.i.s.c.CountsTracker] About to rotate counts store at transaction 250859909 to [/home/neo4j/neo4j-community-2.3.2/data/graph.db/neostore.counts.db.b], from [/home/neo4j/neo4j-community-2.3.2/data/graph.db/neostore.counts.db.a].
2016-03-01 14:40:35.792+0000 INFO  [o.n.k.i.s.c.CountsTracker] Successfully rotated counts store at transaction 250859909 to [/home/neo4j/neo4j-community-2.3.2/data/graph.db/neostore.counts.db.b], from [/home/neo4j/neo4j-community-2.3.2/data/graph.db/neostore.counts.db.a].
```

**Comment by jexp** [comment]
Could you share the query that you run, when this error happens?

You could try to increase the timeout in the client ...

**Comment by rotten** [comment]
I haven't been able to pin it to a specific query.  I do have one query which usually takes several hours (4+) to run -- if it ever returns at all.  Whenever I run it I start singing 'Charlie and the MTA' to myself with "the man who never returns" replaced with "the query who never returns", wish I could feed it as sandwich as it went by.  

It is the one I would suspect the most:
    match (n)-[r]->() where not has(r.some_property) return count(r)

**Comment by jexp** [comment]
That is a very sad query which does a full scan over all nodes and expands them all, is there really no other restriction you can place on it?

you might be a bit faster by using:

`start r=rel(*) WHERE not exists(r.some_property) return count(r)`

(If I run this across 1M rels it takes 3s while your variant takes up to 6s).

Also if you have to run this more often (not sure why) I would recommend to write an server extension, that can parallelize scanning, testing and counting over the relationships with a thread-pool. Which should cut it down further.

if you run enterprise and 2.3 you should be able to create a property-existence constraint on r and the property which would prevent relationships without the prop from being created.

**Comment by craigtaverner** [comment]
Hi @rotten, I see this issue has not been active in a few years. I'm hoping that this issue is no longer occurring for you, and I will close the issue. If you are still experiencing this with a newer version of Neo4j, please feel free to re-open the issue.

**Comment by drpump** [comment]
Have also seen this error today. Specifics in https://github.com/neo4jrb/neo4j/issues/1522 (neo4j ruby gem). TL;DR - it's occurring on the standalone server (v3.4.1) for queries that require serialization of a `datetime` property.

**Comment by drpump** [comment]
From further investigation, v3.5.0 fixes this. It serializes `datetime` and `localdatetime` properties as iso8601 strings, but note that the serialization is dropping the seconds component of `datetime` property values.
