### ISSUE TITLE
[3.0-RC1] YIELD value identifier not unbound after WITH

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#6947]
Hi guys,

```
CALL db.labels() YIELD label
WITH collect(label) as lbls
CALL db.labels() YIELD label
RETURN lbls, collect(label) AS lbls2
```

Trigger : `An unexpected failure occurred, see details in the database logs, reference number 5449a3b4-e5fd-4619-88e4-a073a16f880d.`

However if you alias the second YIELD, it works as exepcted : 

```
CALL db.labels() YIELD label
WITH collect(label) as lbls
CALL db.labels() YIELD label as lbl
RETURN lbls, collect(lbl) AS lbls2
```

Database logs : 

```
2016-04-15 11:48:13.408+0000 ERROR [o.n.b.v.r.i.ErrorReporter] Client triggered an unexpected error: Unexpected error during late semantic checking: Unknown procedure output: `  label@23`. See debug.log for more details.
2016-04-15 11:48:13.408+0000 ERROR [o.n.b.v.r.i.ErrorReporter] org.neo4j.kernel.impl.query.QueryExecutionKernelException: Unexpected error during late semantic checking: Unknown procedure output: `  label@23`
    at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:69)
    at org.neo4j.bolt.v1.runtime.internal.CypherStatementRunner.run(CypherStatementRunner.java:69)
    at org.neo4j.bolt.v1.runtime.internal.StandardStateMachineSPI.run(StandardStateMachineSPI.java:110)
    at org.neo4j.bolt.v1.runtime.internal.SessionStateMachine$State$2.runStatement(SessionStateMachine.java:122)
    at org.neo4j.bolt.v1.runtime.internal.SessionStateMachine.run(SessionStateMachine.java:653)
    at org.neo4j.bolt.v1.runtime.internal.concurrent.SessionWorkerFacade.lambda$run$3(SessionWorkerFacade.java:68)
    at org.neo4j.bolt.v1.runtime.internal.concurrent.SessionWorker.execute(SessionWorker.java:116)
    at org.neo4j.bolt.v1.runtime.internal.concurrent.SessionWorker.executeBatch(SessionWorker.java:102)
    at org.neo4j.bolt.v1.runtime.internal.concurrent.SessionWorker.run(SessionWorker.java:82)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.neo4j.cypher.InternalException: Unexpected error during late semantic checking: Unknown procedure output: `  label@23`
    at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor3_0$.internalException(CompatibilityFor3_0.scala:79)
    at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor3_0$.internalException(CompatibilityFor3_0.scala:61)
    at org.neo4j.cypher.internal.frontend.v3_0.InternalException.mapToPublic(CypherException.scala:70)
    at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor3_0$.runSafely(CompatibilityFor3_0.scala:122)
    at org.neo4j.cypher.internal.compatibility.CompatibilityFor3_0$$anon$2.plan(CompatibilityFor3_0.scala:169)
    at org.neo4j.cypher.internal.ExecutionEngine.org$neo4j$cypher$internal$ExecutionEngine$$producePlan$1(ExecutionEngine.scala:161)
    at org.neo4j.cypher.internal.ExecutionEngine$$anonfun$liftedTree1$1$1.apply(ExecutionEngine.scala:164)
    at org.neo4j.cypher.internal.ExecutionEngine$$anonfun$liftedTree1$1$1.apply(ExecutionEngine.scala:164)
    at org.neo4j.cypher.internal.compiler.v3_0.QueryCache$$anonfun$getOrElseUpdate$1$$anonfun$apply$1.apply(CacheAccessor.scala:36)
    at org.neo4j.cypher.internal.compiler.v3_0.MonitoringCacheAccessor$$anonfun$1.apply(CacheAccessor.scala:57)
    at org.neo4j.cypher.internal.compiler.v3_0.LRUCache.getOrElseUpdate(LRUCache.scala:34)
    at org.neo4j.cypher.internal.compiler.v3_0.LRUCache.apply(LRUCache.scala:64)
    at org.neo4j.cypher.internal.compiler.v3_0.MonitoringCacheAccessor.getOrElseUpdate(CacheAccessor.scala:55)
    at org.neo4j.cypher.internal.compiler.v3_0.QueryCache$$anonfun$getOrElseUpdate$1.apply(CacheAccessor.scala:34)
    at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
    at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
    at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
    at org.neo4j.cypher.internal.compiler.v3_0.QueryCache.getOrElseUpdate(CacheAccessor.scala:46)
    at org.neo4j.cypher.internal.ExecutionEngine.liftedTree1$1(ExecutionEngine.scala:164)
    at org.neo4j.cypher.internal.ExecutionEngine.planQuery(ExecutionEngine.scala:150)
    at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:110)
    at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:65)
    ... 9 more
Caused by: org.neo4j.cypher.internal.frontend.v3_0.InternalException: Unexpected error during late semantic checking: Unknown procedure output: `  label@23`
    at org.neo4j.cypher.internal.compiler.v3_0.planner.CostBasedExecutablePlanBuilder$$anonfun$2.apply(CostBasedExecutablePlanBuilder.scala:124)
    at org.neo4j.cypher.internal.compiler.v3_0.planner.CostBasedExecutablePlanBuilder$$anonfun$2.apply(CostBasedExecutablePlanBuilder.scala:124)
    at org.neo4j.cypher.internal.compiler.v3_0.SemanticChecker$$anonfun$check$1.apply(SemanticChecker.scala:35)
    at org.neo4j.cypher.internal.compiler.v3_0.SemanticChecker$$anonfun$check$1.apply(SemanticChecker.scala:35)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at org.neo4j.cypher.internal.compiler.v3_0.SemanticChecker.check(SemanticChecker.scala:35)
    at org.neo4j.cypher.internal.compiler.v3_0.planner.CostBasedExecutablePlanBuilder$.rewriteStatement(CostBasedExecutablePlanBuilder.scala:124)
    at org.neo4j.cypher.internal.compiler.v3_0.planner.CostBasedExecutablePlanBuilder.producePlan(CostBasedExecutablePlanBuilder.scala:56)
    at org.neo4j.cypher.internal.compiler.v3_0.executionplan.procs.DelegatingProcedureExecutablePlanBuilder.producePlan(DelegatingProcedureExecutablePlanBuilder.scala:98)
    at org.neo4j.cypher.internal.compiler.v3_0.executionplan.FallbackBuilder$class.producePlan(SilentFallbackPlanBuilder.scala:38)
    at org.neo4j.cypher.internal.compiler.v3_0.executionplan.SilentFallbackPlanBuilder.producePlan(SilentFallbackPlanBuilder.scala:61)
    at org.neo4j.cypher.internal.compiler.v3_0.executionplan.ExecutionPlanBuilder.build(ExecutionPlanBuilder.scala:106)
    at org.neo4j.cypher.internal.compiler.v3_0.CypherCompiler$$anonfun$5.apply(CypherCompiler.scala:166)
    at org.neo4j.cypher.internal.compiler.v3_0.CypherCompiler$$anonfun$5.apply(CypherCompiler.scala:166)
    at org.neo4j.cypher.internal.compiler.v3_0.QueryCache$$anonfun$getOrElseUpdate$1$$anonfun$apply$1.apply(CacheAccessor.scala:36)
    at org.neo4j.cypher.internal.compiler.v3_0.MonitoringCacheAccessor$$anonfun$1.apply(CacheAccessor.scala:57)
    at org.neo4j.cypher.internal.compiler.v3_0.LRUCache.getOrElseUpdate(LRUCache.scala:34)
    at org.neo4j.cypher.internal.compiler.v3_0.LRUCache.apply(LRUCache.scala:64)
    at org.neo4j.cypher.internal.compiler.v3_0.MonitoringCacheAccessor.getOrElseUpdate(CacheAccessor.scala:55)
    at org.neo4j.cypher.internal.compiler.v3_0.QueryCache$$anonfun$getOrElseUpdate$1.apply(CacheAccessor.scala:34)
    at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
    at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
    at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
    at org.neo4j.cypher.internal.compiler.v3_0.QueryCache.getOrElseUpdate(CacheAccessor.scala:46)
    at org.neo4j.cypher.internal.compiler.v3_0.CypherCompiler.planPreparedQuery(CypherCompiler.scala:164)
    at org.neo4j.cypher.internal.compatibility.CompatibilityFor3_0$$anon$2$$anonfun$plan$1.apply(CompatibilityFor3_0.scala:172)
    at org.neo4j.cypher.internal.compatibility.CompatibilityFor3_0$$anon$2$$anonfun$plan$1.apply(CompatibilityFor3_0.scala:169)
    at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor3_0$.runSafely(CompatibilityFor3_0.scala:117)
    ... 28 more
```

**Comment by Mats-SX** [comment]
@ikwattro It looks as there has already been a fix merged for this issue, so I am closing it. Please correct me if I am wrong.

**Comment by ikwattro** [comment]
@Mats-SX Yes thanks !!
