### ISSUE TITLE
[3.0-RC1][Procedure] Write only procedures need a RETURN clause if called twice

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#6969]
**Neo4j Version:** 3.0-RC1
### Steps to reproduce

``` java
public class TestProcedure {

    @Context
    public GraphDatabaseService db;

    @Procedure
    @PerformsWrites
    public void createNode() {
        db.createNode();
    }

}
```

``` java
@Test
    public void testCreateNodeProcTwice() {
        try (Transaction tx = getDatabase().beginTx()) {
            getDatabase().execute(
                    "CALL generate.createNode() " +
                    "CALL generate.createNode() "
            );
            tx.success();
        }
    }
```
### Expected behavior

Transaction success
### Actual behavior

```
org.neo4j.graphdb.QueryExecutionException: Query cannot conclude with CALL (must be RETURN or an update clause) (line 1, column 28 (offset: 27))
"CALL generate.createNode() CALL generate.createNode() "
                            ^

    at org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(QueryExecutionKernelException.java:35)
    at org.neo4j.kernel.impl.factory.ClassicCoreSPI.executeQuery(ClassicCoreSPI.java:81)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:357)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:347)
```

**Comment by spacecowboy** [comment]
Thanks for the report, we'll look into it

**Comment by boggle** [comment]
This is intended. The normal way to use `CALL YIELD` is inside a larger Cypher query and therefore needs a trailing `RETURN`. A so called standalone call is just a short cut for making a single procedure call and is the only case where no `RETURN` is needed and also the only case where arguments may be passed via parameters and `YIELD` may be omitted, too.

**Comment by ikwattro** [comment]
@boggle Thanks a lot for the clarification.
