### ISSUE TITLE
[3.0][Procedure] kernel should prevent procedures to return RelationshipType types

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#7069]
- Neo4j version: 3.0.0
- Operating system: OSx Mavericks
- API/Driver: Browser
### **Steps to reproduce**

Create a procedure that returns a RelationshipType, for eg : 

``` java
public CallableProcedure.BasicProcedure getEvents() {
        return new CallableProcedure.BasicProcedure(procedureSignature(getProcedureName("single"))
                .mode(ProcedureSignature.Mode.READ_WRITE)
                .in(PARAMETER_NAME_TIME, Neo4jTypes.NTNumber)
                .in(PARAMETER_NAME_RESOLUTION, Neo4jTypes.NTString)
                .in(PARAMETER_NAME_TIMEZONE, Neo4jTypes.NTString)
                .in(PARAMETER_NAME_RELATIONSHIP_TYPES, Neo4jTypes.NTList(Neo4jTypes.NTString))
                .in(PARAMETER_NAME_DIRECTION, Neo4jTypes.NTString)
                .out(PARAMETER_NAME_NODE, Neo4jTypes.NTNode)
                .out(PARAMETER_NAME_RELATIONSHIP_TYPE, Neo4jTypes.NTRelationship)
                .out(PARAMETER_NAME_DIRECTION, Neo4jTypes.NTString)
                .build()) {

            @Override
            public RawIterator<Object[], ProcedureException> apply(CallableProcedure.Context ctx, Object[] input) throws ProcedureException {
                List<Event> events = timedEventsLogic.getEvents((long) input[0], (String) input[1], (String) input[2], (List<String>) input[3], (String) input[4]);
                List<Object[]> collector = getObjectArray(events);
                return Iterators.asRawIterator(collector.iterator());
            }
        };
    }
```

Yield the values referred as `relationshipType` 

```
CALL ga.timetree.events.single(timestamp(), null, null, null, null) YIELD node, relationshipType, direction
```

Note : 
- Not YIELDING the relationshipType works fine
- Consuming the result with `executeCypher` in java works fine
### Expected behavior

An exception should be thrown on the server side, even during building the packages as a `RelationshipType` type is not supported by the drivers
### Actual behavior

No exception is thrown on the server side, however the browser hangs and output the following in the logs : 

```
2016-05-05 13:57:53.137+0000 ERROR [o.n.b.v.r.i.ErrorReporter] Client triggered an unexpected error [UnknownError]: Unpackable value SENT_ON of type org.neo4j.graphdb.RelationshipType$1. See debug.log for more details, reference 7da927a2-6955-4aec-a9ee-80dbe35c051c.
2016-05-05 13:57:53.137+0000 ERROR [o.n.b.v.r.i.ErrorReporter] Client triggered an unexpected error [UnknownError]: Unpackable value SENT_ON of type org.neo4j.graphdb.RelationshipType$1, reference 7da927a2-6955-4aec-a9ee-80dbe35c051c. Unpackable value SENT_ON of type org.neo4j.graphdb.RelationshipType$1
org.neo4j.bolt.v1.messaging.BoltIOException: Unpackable value SENT_ON of type org.neo4j.graphdb.RelationshipType$1
    at org.neo4j.bolt.v1.messaging.Neo4jPack$Packer.pack(Neo4jPack.java:196)
    at org.neo4j.bolt.v1.messaging.PackStreamMessageFormatV1$Writer.handleRecordMessage(PackStreamMessageFormatV1.java:136)
    at org.neo4j.bolt.v1.messaging.msgprocess.RecordStreamCallback$1.visit(RecordStreamCallback.java:47)
    at org.neo4j.bolt.v1.runtime.internal.CypherAdapterStream.lambda$accept$9(CypherAdapterStream.java:65)
    at org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor3_0$$anon$3.visit(CompatibilityFor3_0.scala:386)
    at org.neo4j.cypher.internal.compiler.v3_0.executionplan.procs.ProcedureExecutionResult$$anonfun$accept$1.apply(ProcedureExecutionResult.scala:69)
    at org.neo4j.cypher.internal.compiler.v3_0.executionplan.procs.ProcedureExecutionResult$$anonfun$accept$1.apply(ProcedureExecutionResult.scala:69)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
    at org.neo4j.cypher.internal.compiler.v3_0.executionplan.procs.ProcedureExecutionResult.accept(ProcedureExecutionResult.scala:69)
    at org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor3_0$$anonfun$accept$1.apply$mcV$sp(CompatibilityFor3_0.scala:381)
    at org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor3_0$$anonfun$accept$1.apply(CompatibilityFor3_0.scala:380)
    at org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor3_0$$anonfun$accept$1.apply(CompatibilityFor3_0.scala:380)
    at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor3_0$.runSafely(CompatibilityFor3_0.scala:117)
    at org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor3_0.accept(CompatibilityFor3_0.scala:380)
    at org.neo4j.cypher.internal.javacompat.ExecutionResult.accept(ExecutionResult.java:317)
    at org.neo4j.bolt.v1.runtime.internal.CypherAdapterStream.accept(CypherAdapterStream.java:64)
    at org.neo4j.bolt.v1.messaging.msgprocess.RecordStreamCallback.result(RecordStreamCallback.java:42)
    at org.neo4j.bolt.v1.messaging.msgprocess.RecordStreamCallback.result(RecordStreamCallback.java:30)
    at org.neo4j.bolt.v1.runtime.internal.SessionStateMachine.result(SessionStateMachine.java:860)
    at org.neo4j.bolt.v1.runtime.internal.SessionStateMachine.access$400(SessionStateMachine.java:59)
    at org.neo4j.bolt.v1.runtime.internal.SessionStateMachine$State$4.pullAll(SessionStateMachine.java:236)
    at org.neo4j.bolt.v1.runtime.internal.SessionStateMachine.pullAll(SessionStateMachine.java:664)
    at org.neo4j.bolt.v1.runtime.internal.concurrent.SessionWorkerFacade.lambda$pullAll$4(SessionWorkerFacade.java:74)
    at org.neo4j.bolt.v1.runtime.internal.concurrent.SessionWorker.execute(SessionWorker.java:116)
    at org.neo4j.bolt.v1.runtime.internal.concurrent.SessionWorker.executeBatch(SessionWorker.java:102)
    at org.neo4j.bolt.v1.runtime.internal.concurrent.SessionWorker.run(SessionWorker.java:82)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by technige** [comment]
Thanks @ikwattro, we've added that to our bug list.

**Comment by pontusmelke** [comment]
Hi @ikwattro 
Extending `CallableProcedure` to implement procedures is only meant for built-in procedures, other procedures should instead be built using annotated java classes. The error handling is done when we load the java class and map the signature to the neo4j type system and the internal `CallableProcedure`,. That is where we would have caught errors like these and we don't want to an extra check in the internal layer below.

Is there a specific reason you are creating your procedure in this way? Also it looks like you are mapping a `RelationshipType` to a `NTRelationship` it should probably be mapped to a `NTString`?

Regards,
Pontus

**Comment by ikwattro** [comment]
Hi @pontusmelke 

Thanks for your reply, yes `NTString` was used since then, sorry about that.

In general, we extended `CallableProcedure` in our framework modules for simplification, it avoids us to create wrapper classes for every type of result you need to return.

I'll close this issue since it has been fixed on our side.
