### ISSUE TITLE
Out of memory issues when using load csv even when using periodic commit

### ISSUE THREAD

**Issue by sztupy** [neo4j/neo4j#7084]
I'm trying to import a fairly large CSV file (~300MB) with the following structure:

```
id,type,internal,data
1,a,true,abc
2,b,false,def
1,a,true,ghi
3,a,true,jkl
4,c,true,mno
...
```

(note: based on the ID value there might be duplicates with different values in the data column, which we are not using)

I'm using the following script:

```
CREATE CONSTRAINT ON (t:Thread) ASSERT t.id IS UNIQUE;
CREATE INDEX ON :Thread(type);

USING PERIODIC COMMIT 1000
LOAD CSV WITH HEADERS FROM 'file:///thread.csv' AS line
MERGE (t:Thread{id:toint(line.id)})
ON CREATE SET
  t.type = line.type,
  t.internal = case line.internal WHEN 'true' THEN true ELSE false END;
```

For some reason no matter what I try, the periodic commit doesn't seem to work, and I usually get a java out of memory error. Also none of the inserts get commited.

If I limit the csv size, for example with a `WITH line LIMIT 100000` then the code works fine, and I get the first 100k lines imported. The same code also works, and can import the whole file with neo4j 2.3 as well.

I'm using the default docker versions for both 2.3 and 3.0 for testing

**Neo4j Version:** neo4j docker, tag 3.0.0
**API:** neo4j-shell, through docker exec
### Steps to reproduce
1. Pull the image: `docker pull neo4j:3.0.0`
2. Create a directory on the host that will be a mount for the data: `mkdir /home/neo4j-data`
3. Start a new container that mounts to this directory: `docker run -d --name neo4j-test -p 7474:7474 -v /home/neo4j:/data neo4j:3.0.0`
4. Generate a large CSV file, with the above mentioned schema
5. Copy the file and the import script over: `docker cp thread.csv neo4j:/var/lib/neo4j/import;
   docker cp load.cyp neo4j:/var/lib/neo4j/import`
6. Start the import process: `docker exec -ti neo4j /var/lib/neo4j/bin/neo4j-shell -file /var/lib/neo4j/import/load.cyp`
### Expected behavior

The data should be imported
### Actual behavior

```
ERROR (-v for expanded information):
        Error occurred in server thread; nested exception is:
        java.lang.OutOfMemoryError: Java heap space
```

**Comment by sztupy** [comment]
As I remember this worked with neo4j milestone, I did recheck, and indeed the import works fine with the following docker image as well: neo4j/neo4j:milestone (image 956e77cf800e), so as a workaround I try to use this image for importing and then try to upgrade to 3.0

**Comment by nickcarenza** [comment]
I am having this problem now as well neo4j 3.2.6. I am using period commit and my file is 4T. I have with no constraints or indices. Smaller sample of the file load fine. I am using default memory settings.

```cypher
USING PERIODIC COMMIT 1000 LOAD CSV FROM 'file:///related.csv' AS line
// Create first person if they don't exist or return them and bind to "a".
MERGE (a:Person { short_id: line[0] })
// Create second person if they don't exist or return them and bind to "b".
MERGE (b:Person { short_id: line[2] })
// Create "RELATED_TO" relationship between "a" and "b" if it doesn't exist.
MERGE (a)-[r:RELATED_TO]->(b);
```

The lines of the file look like:

> 1234,related,5678

The error log from the last failure looks like:

>2017-10-15 07:05:15.014+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 29227ms.
2017-10-15 07:05:44.133+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 29018ms.
2017-10-15 07:06:13.470+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 29236ms.
2017-10-15 07:06:42.679+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 29108ms.
2017-10-15 07:07:11.981+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 29201ms.
2017-10-15 07:07:41.327+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 29245ms.
2017-10-15 07:08:10.465+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 29037ms.
2017-10-15 07:11:10.760+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 116681ms.
>
> ==> /var/log/neo4j/neo4j.log <==
2017-10-15 07:11:10.761+0000 WARN   Java heap space
java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.addWaiter(AbstractQueuedSynchronizer.java:606)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireInterruptibly(AbstractQueuedSynchronizer.java:885)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1222)
        at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
        at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:380)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.idleJobPoll(QueuedThreadPool.java:531)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.access$700(QueuedThreadPool.java:47)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:748)
2017-10-15 07:11:10.761+0000 WARN  Unexpected thread death: {} in {}

I _did_ have a unique constraint on `short_id` when this particular error occurred.

I am currently trying to set max_heap_size to a fixed value close to the machines capacity to see if that solves it. I have also decided to keep the constraint removed for future attempts.

**Comment by nickcarenza** [comment]
I just noticed a warning in the browser ui that warned my merge query would perform poorly if there is no index on my match parameters. I am going to add one without a constraint.
