### ISSUE TITLE
[3.0][Bolt] Specifying wrong port throws non meaningful exception

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#7101]
- Neo4j version: 3.0.0+
- Operating system:Osx
- API/Driver: Java - PHP
### Steps to reproduce

Configure a driver with a wrong port number, for eg `7474` instead of `7687`
### Expected behavior

The exception thrown should tell that a wrong port number is configured
### Actual behavior

```
Exception: Exception in thread "main" org.neo4j.driver.v1.exceptions.ClientException: Protocol error, server suggested unexpected protocol version: 1213486160 at org.neo4j.driver.internal.connector.socket.SocketClient.negotiateProtocol(SocketClient.java:198) at org.neo4j.driver.internal.connector.socket.SocketClient.start(SocketClient.java:73) at org.neo4j.driver.internal.connector.socket.SocketConnection.(SocketConnection.java:63) at org.neo4j.driver.internal.connector.socket.SocketConnector.connect(SocketConnector.java:52) at org.neo4j.driver.internal.pool.InternalConnectionPool$1.allocate(InternalConnectionPool.java:191) at org.neo4j.driver.internal.pool.InternalConnectionPool$1.allocate(InternalConnectionPool.java:180) at org.neo4j.driver.internal.pool.ThreadCachingPool.allocate(ThreadCachingPool.java:212) at org.neo4j.driver.internal.pool.ThreadCachingPool.acquireFromGlobal(ThreadCachingPool.java:164) at org.neo4j.driver.internal.pool.ThreadCachingPool.acquire(ThreadCachingPool.java:118) at org.neo4j.driver.internal.pool.InternalConnectionPool.acquire(InternalConnectionPool.java:109) at org.neo4j.driver.internal.InternalDriver.session(InternalDriver.java:53) at Neo4jMain.boldDriver(Neo4jMain.java:55) at Neo4jMain.main(Neo4jMain.java:30)
```

**Comment by zhenlineo** [comment]
This error is now fixed in all official drivers by giving error message like "Server responded HTTP. Make sure you are not trying to connect to the http endpoint (HTTP defaults to port 7474 whereas BOLT defaults to port 7687)"
