### ISSUE TITLE
Numeric sort in Manual (Legacy) index in Neo4j 3 is not working correctly

### ISSUE THREAD

**Issue by rudisb** [neo4j/neo4j#7216]
I'm using Legacy indexing (now called Manual indexing). After migration from Neo4j 2 to version 3 I have some problems with numeric sorting.

**Neo4j Version:** 3.0.1
**Operating System:** Win 7
**API:** embeded local DB
### Description

Example of correct statement in Neo4j 2:

`queryContext.sort(new Sort(new SortField(AGE, SortField.INT, false)));`

This stament should be changed for Neo4j 3 (Lucene 5):

`queryContext.sort(new Sort(new SortField(AGE, SortField.Type.INT, false)));`

But if you use this sort statement you will get an exception:

```
java.lang.IllegalStateException: unexpected docvalues type SORTED_SET for field 'firstName' (expected=SORTED). Use UninvertingReader or index with docvalues.
at org.apache.lucene.index.DocValues.checkField(DocValues.java:208)
at org.apache.lucene.index.DocValues.getSorted(DocValues.java:264)
at org.apache.lucene.search.FieldComparator$TermOrdValComparator.getSortedDocValues(FieldComparator.java:762)
at org.apache.lucene.search.FieldComparator$TermOrdValComparator.getLeafComparator(FieldComparator.java:767)
at org.apache.lucene.search.FieldValueHitQueue.getComparators(FieldValueHitQueue.java:183)
at org.apache.lucene.search.TopFieldCollector$SimpleFieldCollector.getLeafCollector(TopFieldCollector.java:164)
at org.neo4j.kernel.api.impl.index.collector.DocValuesCollector.replayTo(DocValuesCollector.java:297)
at org.neo4j.kernel.api.impl.index.collector.DocValuesCollector.getTopDocs(DocValuesCollector.java:275)
at org.neo4j.kernel.api.impl.index.collector.DocValuesCollector.getIndexHits(DocValuesCollector.java:150)
at org.neo4j.index.impl.lucene.legacy.LuceneLegacyIndex.search(LuceneLegacyIndex.java:346)
at org.neo4j.index.impl.lucene.legacy.LuceneLegacyIndex.query(LuceneLegacyIndex.java:261)
at org.neo4j.index.impl.lucene.legacy.LuceneLegacyIndex.query(LuceneLegacyIndex.java:205)
at org.neo4j.index.impl.lucene.legacy.LuceneLegacyIndex.query(LuceneLegacyIndex.java:217)
at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.nodeLegacyIndexQuery(StateHandlingStatementOperations.java:1440)
at org.neo4j.kernel.impl.api.OperationsFacade.nodeLegacyIndexQuery(OperationsFacade.java:1162)
at org.neo4j.kernel.impl.coreapi.LegacyIndexProxy$Type$1.query(LegacyIndexProxy.java:83)
at org.neo4j.kernel.impl.coreapi.LegacyIndexProxy.query(LegacyIndexProxy.java:365)
```

I think this is caused by new added statement in Neo4j indexer class (Neo4j is indexing field for sorting automatically now?). See in:

`org.neo4j.index.impl.lucene.legacy.IndexType CustomType addToDocument( Document document, String key, Object value )`

new line:

`document.add( instantiateSortField( key, value ) );`
`and method instantiateSortField is creating SortedSetDocValuesField`

So I changed my code to:

`queryContext.sort(new Sort(new SortedSetSortField(AGE, false)));`

This runs OK but sorting is not working because numbers are sorted as string. I see that "value" parameter is String every time in method "addToDocument". I think the root cause is explained it this old comment:

see comment in class org.neo4j.index.impl.lucene.legacy.IndexType CustomType

```
// TODO We should honor ValueContext instead of doing value.toString() here.
// if changing it, also change #get to honor ValueContext.
```
### Expected behavior

Numeric data are sorted as numeric
### Actual behavior

Numeric data are sorted as strings

Am I missing some new way how to index, search and sort data in Neo4j 3 or this is really problem that values are indexed as string in Neo4j?

Simple unit test for Neo4j 2 and Neo4j 3 can be downloaded

[SortNeo4j2SysTest.java.txt](https://github.com/neo4j/neo4j/files/281049/SortNeo4j2SysTest.java.txt)
[SortNeo4j3SysTest.java.txt](https://github.com/neo4j/neo4j/files/281050/SortNeo4j3SysTest.java.txt)

[stackoverflow question](http://stackoverflow.com/questions/37391263/numeric-sort-in-manual-legacy-index-in-neo4j-3-is-not-working-correctly)

**Comment by spacecowboy** [comment]
Thanks for the report. We'll have a look

**Comment by MishaDemianenko** [comment]
Hi @rudisb I have added 2 tests with sorting examples to show how you can sort by numeric and string property.
Basically to be able to sort by numeric property you need to do something like this:

``` java
index.add( node, numericProperty, new ValueContext( i ).indexNumeric() );
```

Hope this helps.

**Comment by rudisb** [comment]
Hi @MishaDemianenko, works great for me. Thank you.
