### ISSUE TITLE
[Bolt][Cypher] Empty List<Map> parameter throws "Property values can only be of primitive types or arrays thereof"

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#7228]
**Neo4j Version:** 3.0.1
**Operating System:** OSX
**API:** Bolt Java Driver - Bolt PHP Driver

Take the following query : 

```
UNWIND {batches} as batch
MERGE (p:Person {id: batch.id})
SET p += batch.props
WITH p, batch
UNWIND batch.prev as prev
MERGE (o:Person {id: prev.id})
CREATE (p)-[:KNOWS]->(o)
```

This query works fine if all `batch.prev` lists are not empty. However when one of them is empty, the following exception is thrown : 

```
Property values can only be of primitive types or arrays thereof
```

Note that it affects only Bolt, it works fine with http.

Second note: if `batch.prev` would be a list of integers rather than a map and the query part changed to `MERGE (o:Person {id: prev})` it works fine too.
### Steps to reproduce

Here is a reproducable java test : 

``` java
@Test
    public void shouldBeAbleToUnwindEmptyListsWithoutFailure() {
        Map<String, Object> parameters = new HashMap<>();
        List<Map<String, Object>> batches = new ArrayList<>();
        for (int i = 1; i < 10; ++i) {
            batches.add(createBatch(i));
        }
        parameters.put("batches", batches);
        StatementResult result = session.run(
                    "UNWIND {batches} as batch " +
                    "CREATE (a:Node) SET a.id = batch.id, a.login = batch.login " +
                    "WITH a, batch " +
                    "UNWIND batch.prev as prev " +
                    "MERGE (o:Person {id: prev})" +
                    "MERGE (a)-[:RELATES]->(o)", parameters
        );
        result.consume();
    }

    private Map<String, Object> createBatch(int i) {
        Map<String, Object> map = new HashMap<>();
        map.put("id", i);
        map.put("login", "login" + i);
        List<Map<String, Object>> prev = i > 6 ? createPrev() : new ArrayList<Map<String, Object>>();
        map.put("prev", prev);

        return map;
    }

    private List<Map<String, Object>> createPrev() {
        List<Map<String, Object>> prevs = new ArrayList<>();
        for (int i = 1; i < 6; ++i) {
            Map<String, Object> prev = new HashMap<>();
            prev.put("id", i);
            prev.put("second", ++i);
            prevs.add(prev);
        }

        return prevs;
    }
```

```
org.neo4j.driver.v1.exceptions.ClientException: Property values can only be of primitive types or arrays thereof

    at org.neo4j.driver.internal.connector.socket.SocketResponseHandler.handleFailureMessage(SocketResponseHandler.java:68)
    at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:456)
    at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:417)
    at org.neo4j.driver.internal.connector.socket.SocketClient.receiveOne(SocketClient.java:128)
    at org.neo4j.driver.internal.connector.socket.SocketConnection.receiveOne(SocketConnection.java:135)
    at org.neo4j.driver.internal.connector.ConcurrencyGuardingConnection.receiveOne(ConcurrencyGuardingConnection.java:150)
    at org.neo4j.driver.internal.pool.PooledConnection.receiveOne(PooledConnection.java:142)
    at org.neo4j.driver.internal.InternalStatementResult.consume(InternalStatementResult.java:280)
    at org.neo4j.driver.v1.integration.ParametersIT.shouldBeAbleToUnwindEmptyListsWithoutFailure(ParametersIT.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
    at org.neo4j.driver.v1.util.TestNeo4jSession$1.evaluate(TestNeo4jSession.java:72)
    at org.neo4j.driver.v1.util.TestNeo4j$1.evaluate(TestNeo4j.java:64)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```
### Expected behavior

It shouldn't fail
### Actual behavior

```
Property values can only be of primitive types or arrays thereof
```

**Comment by pontusmelke** [comment]
Thanks reporting this, will have it fixed as soon as possible!

**Comment by pontusmelke** [comment]
I have had a look, I get the same error in http, bolt, and embedded. It is actually the other way around, the query works if the list is empty.

The problem in your query is

```
MERGE (o:Person {id: prev})
```

should be

```
MERGE (o:Person {id: prev.id})
```

The reason it works for empty `prev` is just that since it is empty this part will never be executed.

**Comment by ikwattro** [comment]
@pontusmelke Yeah my bad, so stupid :/ .

I guess the issue can be closed.
