### ISSUE TITLE
TransactionFailureException caused by org.apache.lucene.store.AlreadyClosedException (?)

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#7232]
- Neo4j version: 3.1.0-M01
- Operating system: Ubuntu 14.04
- API/Driver: Java API

I'm not sure what is the exact cause for this, so I'll just post a stacktrace here and will provide more information upon requests.

```
org.neo4j.graphdb.TransactionFailureException: Database has encountered some problem, please perform necessary action (tx recovery/restart)
at org.neo4j.kernel.impl.factory.ClassicCoreSPI.beginTransaction(ClassicCoreSPI.java:180)
at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransaction(GraphDatabaseFacade.java:349)
at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTx(GraphDatabaseFacade.java:338)
Caused by: org.neo4j.kernel.api.exceptions.TransactionFailureException: Database has encountered some problem, please perform necessary action (tx recovery/restart)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
at org.neo4j.kernel.internal.DatabaseHealth.assertHealthy(DatabaseHealth.java:62)
at org.neo4j.kernel.impl.api.Kernel.newTransaction(Kernel.java:87)
at org.neo4j.kernel.impl.factory.ClassicCoreSPI.beginTransaction(ClassicCoreSPI.java:173)
... 22 common frames omitted
Caused by: org.neo4j.kernel.impl.store.UnderlyingStorageException: Unable to write defragged id  batch
at org.neo4j.kernel.impl.store.id.FreeIdKeeper.writeIdBatch(FreeIdKeeper.java:237)
at org.neo4j.kernel.impl.store.id.FreeIdKeeper.freeId(FreeIdKeeper.java:91)
at org.neo4j.kernel.impl.store.id.IdGeneratorImpl.freeId(IdGeneratorImpl.java:263)
at org.neo4j.kernel.impl.store.CommonAbstractStore.freeId(CommonAbstractStore.java:596)
at org.neo4j.kernel.impl.store.CommonAbstractStore.updateRecord(CommonAbstractStore.java:1104)
at org.neo4j.kernel.impl.store.NodeStore.updateRecord(NodeStore.java:110)
at org.neo4j.kernel.impl.transaction.command.NeoStoreTransactionApplier.visitNodeCommand(NeoStoreTransactionApplier.java:73)
at org.neo4j.kernel.impl.transaction.command.Command$NodeCommand.handle(Command.java:215)
at org.neo4j.kernel.impl.api.TransactionApplierFacade.visit(TransactionApplierFacade.java:61)
at org.neo4j.kernel.impl.api.TransactionApplierFacade.visit(TransactionApplierFacade.java:35)
at org.neo4j.kernel.impl.transaction.log.PhysicalTransactionRepresentation.accept(PhysicalTransactionRepresentation.java:69)
at org.neo4j.kernel.impl.api.TransactionToApply.accept(TransactionToApply.java:108)
at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:326)
at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:78)
at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:51)
at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:464)
at org.neo4j.kernel.impl.api.KernelTransactionImplementation.close(KernelTransactionImplementation.java:380)
at org.neo4j.kernel.impl.coreapi.TopLevelTransaction.close(TopLevelTransaction.java:76)
Suppressed: org.neo4j.kernel.impl.store.InvalidRecordException: Node[18671280,used=false,rel=38230727,prop=76667610,labels=Inline(0x1000000206:[518]),light,secondaryUnitId=-1] not in use
at org.neo4j.kernel.impl.store.record.RecordLoad$1.verify(RecordLoad.java:55)
at org.neo4j.kernel.impl.store.CommonAbstractStore.verifyAfterReading(CommonAbstractStore.java:1251)
at org.neo4j.kernel.impl.store.CommonAbstractStore.readIntoRecord(CommonAbstractStore.java:1075)
at org.neo4j.kernel.impl.store.CommonAbstractStore.getRecord(CommonAbstractStore.java:1053)
at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates.loadNode(OnlineIndexUpdates.java:191)
at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates.gatherUpdatesFromPropertyCommandsForNode(OnlineIndexUpdates.java:160)
at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates.access$000(OnlineIndexUpdates.java:64)
at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates$1.visited(OnlineIndexUpdates.java:118)
at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates$1.visited(OnlineIndexUpdates.java:114)
at org.neo4j.collection.primitive.hopscotch.PrimitiveLongObjectHashMap.visitEntries(PrimitiveLongObjectHashMap.java:83)
at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates.gatherUpdatesFromPropertyCommands(OnlineIndexUpdates.java:113)
at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates.feed(OnlineIndexUpdates.java:98)
at org.neo4j.kernel.impl.transaction.command.IndexBatchTransactionApplier$SingleTransactionApplier.close(IndexBatchTransactionApplier.java:140)
at org.neo4j.kernel.impl.api.TransactionApplierFacade.close(TransactionApplierFacade.java:52)
at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:327)
... 11 common frames omitted
Suppressed: org.apache.lucene.store.AlreadyClosedException: FileLock invalidated by an external force: NativeFSLock(path=/mnt/ssd/bochka-n4j/schema/index/lucene/1979/1/write.lock,impl=sun.nio.ch.FileLock
Impl[0:9223372036854775807 exclusive invalid],ctime=2016-05-26T12:18:10Z)
at org.apache.lucene.store.NativeFSLockFactory$NativeFSLock.ensureValid(NativeFSLockFactory.java:166)
at org.apache.lucene.store.LockValidatingDirectoryWrapper.deleteFile(LockValidatingDirectoryWrapper.java:37)
at org.apache.lucene.index.IndexFileDeleter.deleteFile(IndexFileDeleter.java:732)
at org.apache.lucene.index.IndexFileDeleter.deletePendingFiles(IndexFileDeleter.java:516)
at org.apache.lucene.index.IndexFileDeleter.decRef(IndexFileDeleter.java:624)
at org.apache.lucene.index.IndexFileDeleter.checkpoint(IndexFileDeleter.java:566)
at org.apache.lucene.index.IndexWriter.checkpoint(IndexWriter.java:2322)
at org.apache.lucene.index.IndexWriter.applyAllDeletesAndUpdates(IndexWriter.java:3163)
at org.apache.lucene.index.IndexWriter.maybeApplyDeletes(IndexWriter.java:3147)
at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:434)
at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:286)
at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:261)
at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:251)
at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:137)
at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:154)
at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
at org.neo4j.kernel.api.impl.index.partition.IndexPartition.maybeRefreshBlocking(IndexPartition.java:87)
at org.neo4j.kernel.api.impl.index.AbstractLuceneIndex.maybeRefreshPartition(AbstractLuceneIndex.java:334)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
at org.neo4j.kernel.api.impl.index.AbstractLuceneIndex.maybeRefreshBlocking(AbstractLuceneIndex.java:318)
at org.neo4j.kernel.api.impl.schema.LuceneIndexAccessor$LuceneIndexUpdater.close(LuceneIndexAccessor.java:154)
at org.neo4j.kernel.impl.api.index.updater.UpdateCountingIndexUpdater.close(UpdateCountingIndexUpdater.java:55)
at org.neo4j.kernel.impl.api.index.FlippableIndexProxy$LockingIndexUpdater.close(FlippableIndexProxy.java:458)
at org.neo4j.kernel.impl.api.index.ContractCheckingIndexProxy$1.close(ContractCheckingIndexProxy.java:104)
at org.neo4j.kernel.impl.api.index.IndexUpdaterMap.close(IndexUpdaterMap.java:84)
at org.neo4j.kernel.impl.api.index.IndexingService.apply(IndexingService.java:471)
at org.neo4j.kernel.impl.api.index.IndexingService.apply(IndexingService.java:407)
at org.neo4j.kernel.impl.transaction.command.IndexUpdatesWork.apply(IndexUpdatesWork.java:63)
at org.neo4j.kernel.impl.transaction.command.IndexUpdatesWork.apply(IndexUpdatesWork.java:42)
at org.neo4j.concurrent.WorkSync.doSynchronizedWork(WorkSync.java:121)
at org.neo4j.concurrent.WorkSync.apply(WorkSync.java:90)
at org.neo4j.kernel.impl.transaction.command.IndexBatchTransactionApplier.applyIndexUpdates(IndexBatchTransactionApplier.java:92)
at org.neo4j.kernel.impl.transaction.command.IndexBatchTransactionApplier.close(IndexBatchTransactionApplier.java:109)
at org.neo4j.kernel.impl.api.BatchTransactionApplierFacade.close(BatchTransactionApplierFacade.java:70)
at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:336)
... 11 common frames omitted
Caused by: java.nio.channels.ClosedChannelException: null
at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:300)
at org.neo4j.io.fs.StoreFileChannel.size(StoreFileChannel.java:165)
at org.neo4j.kernel.impl.store.id.FreeIdKeeper.writeIdBatch(FreeIdKeeper.java:205)
... 23 common frames omitted
```

**Comment by MishaDemianenko** [comment]
Hi @tkroman, that will be super helpful if you can provide some more information about the way how we can reproduce it. Do you have a test case?

**Comment by tkroman** [comment]
@MishaDemianenko I don't have tests as of yet but I'm trying to reproduce this right now or at least to narrow it down. I'll get back if something comes up.

**Comment by chrisvest** [comment]
@tkroman Are there any other exceptions in `debug.log`? The code does not look interruption safe, so it could be that there's a `ClosedByInterruptException` hiding somewhere.

**Comment by tkroman** [comment]
@chrisvest yes, it was. Some thread got interrupted before, which caused the kernel state to be set to "failed", and I overlooked that exception. I guess, this is one of those threads where I whine about how the engine handles interrupts, so it might be closed as well.

On a side note: are there any plans to make `Transaction#terminate` work for cases when the it's called during the waiting on some lock? This is a low-priority judging by the number of times it's encountered, but embedded users would benefit from this.
For instance: we have a transaction wrapper that tries to terminate the long-running/possibly hanging transaction before the thread gets interrupted. In case termination didn't work out (which would be exactly when the code is waiting on a lock), the thread will receive an interrupt and there you go. Allowing transaction termination to be (actively) lock-aware would solve this.
From what I've seen in the code, this can't be done too easily due to loose coupling between the locking mechanism and the transaction API, but maybe sometime in the future you might consider this option?

**Comment by tkroman** [comment]
Man, do I babble a lot when it comes to this topic.

**Comment by lutovich** [comment]
@tkroman we are trying to make locks transaction termination aware: https://github.com/neo4j/neo4j/pull/7168

**Comment by tkroman** [comment]
@lutovich this is amazing! Looking forward for the release with that one. Closing this issue meanwhile.
