### ISSUE TITLE
File has been unmapped NEO4J

### ISSUE THREAD

**Issue by marinhojess** [neo4j/neo4j#7249]
Hi, I'm migrating a tdatabase to Neo4J. The database is large enough, but when I was moving appeared the following error:

> Traceback (most recent call last):
>   File "/home/mushthielv/Área de Trabalho/bdTrmmTest.py", line 37, in <module>
>     results = db.query(q, returns=(client.Node))  
>   File "/usr/local/lib/python2.7/dist-packages/neo4jrestclient/client.py", line 212, in query
>     tx=tx
>   File "/usr/local/lib/python2.7/dist-packages/neo4jrestclient/query.py", line 324, in **init**
>     tx.execute()
>   File "/usr/local/lib/python2.7/dist-packages/neo4jrestclient/query.py", line 936, in execute
>     return self.commit()
>   File "/usr/local/lib/python2.7/dist-packages/neo4jrestclient/query.py", line 948, in commit
>     results = self._execute(url, results=True)
>   File "/usr/local/lib/python2.7/dist-packages/neo4jrestclient/query.py", line 867, in _execute
>     self._manage_errors(content["errors"])
>   File "/usr/local/lib/python2.7/dist-packages/neo4jrestclient/query.py", line 841, in _manage_errors
>     raise TransactionException(200, message)
> neo4jrestclient.exceptions.TransactionException: Code [200]: OK. Request fulfilled, document follows.
> 
> Neo.DatabaseError.Statement.ExecutionFailed:
> File has been unmapped: /var/lib/neo4j/data/databases/graph.db/neostore.counts.db.a
> 
> [Finished in 56552.1s with exit code 1]
> [shell_cmd: python -u "/home/mushthielv/Área de Trabalho/bdTrmmTest.py"]
> [dir: /home/mushthielv/Área de Trabalho]
> [path: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games]

Does anyone know what can it be?

**Comment by jexp** [comment]
Which Neo4j version are you using?
What query are you sending? 
Does this also happen with normal Neo4j interactions in Neo4j-Browser?

**Comment by marinhojess** [comment]
@jexp I'm using the version 3.0.1. I'm using this query 

``` python
q = 'MATCH (s:LaLo) WHERE s.latitude = "%s" AND s.longitude = "%s" RETURN s'%(str(i[0]),str(i[1]))
results = db.query(q, returns=(client.Node))
```

So, the Neo4J insert 20% of database.In Neo4j-Browser the inserts are ok.

**Comment by spacecowboy** [comment]
@mushthielv Which driver are you using? Have you tried using the new Python driver? http://neo4j.com/developer/python/

**Comment by mjr129** [comment]
I also got this error, server wouldn't recover and required shutting down, database was corrupt thereafter, submitted to issue #8681.

**Comment by nblum** [comment]
Same error when trying to migrate from 3.0.4 to 3.0.8 or 3.1.1

```
2017-01-26 08:57:00.610+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4522a087' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4522a087' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4522a087' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:215)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:67)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4522a087' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.CommunityFacadeFactory, /var/lib/neo4j/data/databases/graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:144)
        at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:40)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108)
        at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:55)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.recovery.Recovery@1be23e58' failed to initialize. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:416)
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:511)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:99)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:140)
        ... 10 more
Caused by: org.neo4j.kernel.impl.store.UnderlyingStorageException: No check point found in any log file from version 972091 to 972091
        at org.neo4j.kernel.recovery.PositionToRecoverFrom.apply(PositionToRecoverFrom.java:68)
        at org.neo4j.kernel.recovery.DefaultRecoverySPI.getPositionToRecoverFrom(DefaultRecoverySPI.java:80)
        at org.neo4j.kernel.recovery.Recovery.init(Recovery.java:80)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
        ... 19 more

```

**Comment by spacecowboy** [comment]
@mjr129 @nblum could you possibly describe your setups?

- Operating System
- Installed which package of `.tar.gz`, `.dmg`, `.exe`, `.deb`?
- Did you change anything from the default configuration?
- Does the database refuse to start after upgrade? Or does queries execute and return incorrect data?

**Comment by nblum** [comment]
> Operating System

Debian Wheezy (3.2.0-4-amd64)

Java(TM) SE Runtime Environment (build 1.8.0_121-b13)

> Installed which package of .tar.gz, .dmg, .exe, .deb?

Installed via repo (https://debian.neo4j.org/)

> Did you change anything from the default configuration?

auth.disabled = false
allow.migration = true

> Does the database refuse to start after upgrade? Or does queries execute and return incorrect data?

database refuse to start, the log is from starting after package upgrade

downgrading back to 3.0.4 works fine

**Comment by MishaDemianenko** [comment]
Hi @nblum, is there is any possibility that you can share your transaction logs with us? 
(By default you can find them in a store directory and they have prefix `neostore.transaction.db`).
To make it more private and avoid posting them here you can send them to mikhaylo.demianenko at neotechnology.com so we can investigate what happen there.
Thx in advance!

**Comment by MishaDemianenko** [comment]
@mushthielv do you still have log files (neo4j.log/messages.log/debug.log) for corresponding time period? Can you share them?

**Comment by nblum** [comment]
Hey @MishaDemianenko do you mean the "neostore.transaction.db.<x>" files in the graph.db directory? This files are very huge

**Comment by MishaDemianenko** [comment]
@nblum correct, you can try to zip them - it should help a bit; if that is still too big for email - can you share them in any other way (dropbox, amazon, etc) and just send me the link?

**Comment by marinhojess** [comment]
Guys, I solved this error by using bolt driver. [http://neo4j.com/docs/api/python-driver/current/](url)

@MishaDemianenko I don't have the log anymore :/

**Comment by MishaDemianenko** [comment]
@mushthielv in that case it's impossible to find out what was the reason of your original failure; but it's really nice that you have found a way to solved it :)

**Comment by MishaDemianenko** [comment]
Closing as solved
