### ISSUE TITLE
Cannot open existing database in read-only mode in 1.9.RC1 (worked in 1.8)

### ISSUE THREAD

**Issue by tbroyer** [neo4j/neo4j#728]
Tracked in trello: https://trello.com/c/OeuJdQV3

In a unit-test, I'm creating a `BatchInserter` to a temp folder:
```java
// temp is a org.junit.rules.TemporaryFolder
inserter = BatchInserters.inserter(temp.getRoot().getAbsolutePath());
```
then (after I shut down the inserter) using a read-only database to check the content of the database:
```java
graph = new GraphDatabaseFactory()
    .newEmbeddedDatabaseBuilder(temp.getRoot().getAbsolutePath())
    .setConfig(GraphDatabaseSettings.read_only, "true")
    .newGraphDatabase();
```

This worked in Neo4j 1.8 but fails in 1.9.RC1 (also tried with 1.9.M05 previously):

```
java.lang.RuntimeException: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.StoreLockerLifecycleAdapter@d8a9586' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:282)
	at org.neo4j.kernel.EmbeddedReadOnlyGraphDatabase.<init>(EmbeddedReadOnlyGraphDatabase.java:90)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:80)
	at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:205)
	at [edited]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.StoreLockerLifecycleAdapter@d8a9586' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:497)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:104)
	at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:260)
	... 30 more
Caused by: org.neo4j.kernel.StoreLockException: Unable to lock store as store dir does not exist and instance is in read-only mode
	at org.neo4j.kernel.StoreLocker.checkLock(StoreLocker.java:67)
	at org.neo4j.kernel.StoreLockerLifecycleAdapter.start(StoreLockerLifecycleAdapter.java:40)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:491)
	... 32 more
```

I believe this is a bug as I can't see why I couldn't open an existing database in read-only mode when no-one else has opened (and locked) it.

As I understand it, you added the `store_lock` as a way to prevent databases from sharing the same set of files (which seems to rule out the use-case of opening a “live” database in read-only mode, which IIRC was advertized in the Neoclipse tutorial a while ago). That means that it's simply impossible to use the read-only mode: either the database doesn't exist (fail, expected), or it exists but "cannot be locked" (fail, unexpectedly; my use case), or it's already opened (fail, expected by the new `store_lock` feature).

If my understanding is correct, it means however that a read-only database would have to actually do a write to create the `store_lock`, which wouldn't be possible if the FS is read-only. So maybe there should be another config flag to tell that the FS is read-only, independently of the way you want to open the database?

**Workaround:** do not use the read-only mode.

**Comment by jakewins** [comment]
Fixed by 1c856a4ca2d09088f82a25e9f7cb6dd1ec2cdede
