### ISSUE TITLE
relationship not found error

### ISSUE THREAD

**Issue by Sahasrara** [neo4j/neo4j#7288]
Here is a good forum discussion to follow: https://groups.google.com/forum/#!topic/neo4j/lPFbuxLunn8

I'm hitting my database with one computer with something like 24 threads firing of reads and writes.  I will consistently get these errors. 

Neo4j  2.3.3
OGM 2.0.2
SDN 4.1.1

After updating OGM/SDN, the errors changed to this:

```
Caused by: org.neo4j.ogm.exception.CypherException: Error executing Cypher "Neo.DatabaseError.Statement.ExecutionFailure"
       at org.neo4j.ogm.drivers.http.response.AbstractHttpResponse.initialise(AbstractHttpResponse.java:83)
       at org.neo4j.ogm.drivers.http.response.AbstractHttpResponse.<init>(AbstractHttpResponse.java:74)
       at org.neo4j.ogm.drivers.http.response.GraphModelResponse.<init>(GraphModelResponse.java:31)
       at org.neo4j.ogm.drivers.http.request.HttpRequest.execute(HttpRequest.java:90)
       at org.neo4j.ogm.session.delegates.LoadOneDelegate.load(LoadOneDelegate.java:47)
       at org.neo4j.ogm.session.Neo4jSession.load(Neo4jSession.java:82)
       at org.springframework.data.neo4j.template.Neo4jTemplate.load(Neo4jTemplate.java:82)
       at sun.reflect.GeneratedMethodAccessor203.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
       at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
       at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
       at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
       at com.sun.proxy.$Proxy85.load(Unknown Source)

```

Prior to updating, the exception looked something like this:

```
org.neo4j.graphdb.NotFoundException: Relationship[17659] not found.
    at org.neo4j.kernel.impl.core.NodeManager.getRelForProxy(NodeManager.java:558)
    at org.neo4j.kernel.impl.core.RelationshipProxy.getOtherNode(RelationshipProxy.java:60)
    at org.neo4j.graphmatching.PatternFinder.traverse(PatternFinder.java:222)
    at org.neo4j.graphmatching.PatternFinder.findNextMatch(PatternFinder.java:177)
    at org.neo4j.graphmatching.PatternFinder.hasNext(PatternFinder.java:378)
    at scala.collection.JavaConversions$JIteratorWrapper.hasNext(JavaConversions.scala:574)
    at scala.collection.Iterator$class.foreach(Iterator.scala:652)
    at scala.collection.JavaConversions$JIteratorWrapper.foreach(JavaConversions.scala:573)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:73)
    at scala.collection.JavaConversions$JIterableWrapper.foreach(JavaConversions.scala:587)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:194)
    at scala.collection.JavaConversions$JIterableWrapper.map(JavaConversions.scala:587)
```

**Comment by Sahasrara** [comment]
It succeeds eventually with retry

**Comment by rationalism** [comment]
Possibly related to the issue I had at #6823 ?
