### ISSUE TITLE
Cannot start Neo4j on Fedora 22 or Fedora 23

### ISSUE THREAD

**Issue by Alan-R** [neo4j/neo4j#7330]
## Bug Report
- Neo4j version: 3.0.1
- Operating system: Linux Fedora 22 and 23
- API/Driver: n/a
- Java version: java-1.8.0-openjdk-headless
- **Steps to reproduce**
  - Install Neo4j via tar ball
  - Start Neo4j via bin/neo4j console
- it should start like it does for CentOS7 and Fedora 21. I build both with almost exactly the same Dockerfile.
- it fails to start with mysterious Java messages. Like those below:

```
Step 61 : RUN /usr/sbin/rsyslogd&  $NEOROOT/bin/neo4j console & sleep 20; py.test -rw -v tests
 ---> Running in 8452345ca7c3
Starting Neo4j.
2016-06-07 15:06:25.337+0000 INFO  No SSL certificate found, generating a self-signed certificate..
^[[91mException in thread "main" ^[[0m^[[91mjava.lang.InternalError
^[[0m^[[91m     at sun.security.ec.SunEC.initialize(Native Method)
        at sun.security.ec.SunEC.access$000(SunEC.java:49)
        at sun.security.ec.SunEC$1.run(SunEC.java:61)
        at sun.security.ec.SunEC$1.run(SunEC.java:58)
        at java.security.AccessController.doPrivileged(Native Method)^[[0m^[[91m
        at sun.security.ec.SunEC.<clinit>(SunEC.java:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)^[[0m^[[91m
        at java.lang.Class.newInstance(Class.java:442)^[[0m^[[91m
^[[0m^[[91m     at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:221)
        at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
        at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
        at sun.security.jca.ProviderList.loadAll(ProviderList.java:282)
        at sun.security.jca.ProviderList.removeInvalid(ProviderList.java:299)
        at sun.security.jca.Providers.getFullProviderList(Providers.java:173)
        at java.security.Security.insertProviderAt(Security.java:360)^[[0m^[[91m
        at java.security.Security.addProvider(Security.java:403)^[[0m^[[91m
^[[0m^[[91m     at org.neo4j.bolt.security.ssl.Certificates.<clinit>(Certificates.java:82)^[[0m^[[91m
^[[0m^[[91m     at org.neo4j.server.AbstractNeoServer.createKeyStore(AbstractNeoServer.java:388)
        at org.neo4j.server.AbstractNeoServer.init(AbstractNeoServer.java:173)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:186)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:81)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:60)
^[[0m^[[91m     at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
```

I attached the Dockerfiles I use to reproduce this problem.
[Dockerfile23.txt](https://github.com/neo4j/neo4j/files/302917/Dockerfile23.txt)
[Dockerfile22.txt](https://github.com/neo4j/neo4j/files/302918/Dockerfile22.txt)
[Dockerfile21.txt](https://github.com/neo4j/neo4j/files/302919/Dockerfile21.txt)

the Dockerfile21.txt file works correctly, the other two fail in the fashion described.

**Comment by spacecowboy** [comment]
Thanks for the report. I ran Dockerfile22 and reproduced the error.

**Comment by spacecowboy** [comment]
A more minimal Dockerfile to reproduce:

```
FROM fedora:21

ENV YUM yum -y
ENV NEOPARENT /usr/share
ENV NEOROOT $NEOPARENT/neo4j

RUN $YUM install epel-release pkg-config || true
RUN $YUM install deltarpm glib2 libpcap zlib-devel python   \
    python-devel python-flask which java-1.8.0-openjdk-headless lsof    \
    libsodium-devel gcc cmake make glib2-devel valgrind resource-agents \
    wget libpcap-devel pylint rpm-build iproute

RUN wget -q "https://neo4j.com/artifact.php?name=neo4j-community-3.0.1-unix.tar.gz" -O /tmp/neo4j-community-3.0.1-unix.tar.gz
RUN tar -C $NEOPARENT -xzf /tmp/neo4j-community-3.0.1-unix.tar.gz
RUN rm -f $NEOROOT
RUN mv $NEOPARENT/neo4j-community-3.0.1 $NEOROOT

# This should crash
RUN $NEOROOT/bin/neo4j console
```

Change first two lines (if 22/33, then YUM should be `dnf`) to make it work/fail.

**Comment by Alan-R** [comment]
I appreciate you taking the time to minimize the Dockerfile.

On June 8, 2016 3:07:18 AM MDT, Jonas Kalderstam notifications@github.com wrote:

> A more minimal Dockerfile to reproduce:
> 
> ```
> FROM fedora:21
> 
> ENV YUM yum -y
> ENV NEOPARENT /usr/share
> ENV NEOROOT $NEOPARENT/neo4j
> 
> RUN $YUM install epel-release pkg-config || true
> RUN $YUM install deltarpm glib2 libpcap zlib-devel python  \
>   python-devel python-flask which java-1.8.0-openjdk-headless lsof    \
>   libsodium-devel gcc cmake make glib2-devel valgrind resource-agents \
>   wget libpcap-devel pylint rpm-build iproute
> 
> RUN wget -q
> "https://neo4j.com/artifact.php?name=neo4j-community-3.0.1-unix.tar.gz"
> -O /tmp/neo4j-community-3.0.1-unix.tar.gz
> RUN tar -C $NEOPARENT -xzf /tmp/neo4j-community-3.0.1-unix.tar.gz
> RUN rm -f $NEOROOT
> RUN mv $NEOPARENT/neo4j-community-3.0.1 $NEOROOT
> 
> # This should crash
> RUN $NEOROOT/bin/neo4j console
> ```
> 
> Change first two lines (if 22/33, then YUM should be `dnf`) to make it
> work/fail.
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/neo4j/neo4j/issues/7330#issuecomment-224532177

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by zhenlineo** [comment]
Hi,

It probably due to a problem with nss on fedora. Could you try to upgrade nss on your system to 3.23? For me, if I add `RUN dnf -y update nss` to upgrade nss from v3.21 to v3.23 before starting the server, then I could start neo4j successfully without any error.

REF: 
https://bugzilla.redhat.com/show_bug.cgi?id=1332867
https://bugzilla.redhat.com/show_bug.cgi?id=1332456

**Comment by technige** [comment]
Closing due to inactivity.
