### ISSUE TITLE
relationships has been deleted?

### ISSUE THREAD

**Issue by xghrbc1001** [neo4j/neo4j#7441]
```
org.neo4j.graphdb.NotFoundException: Unable to load one or more relationships from Node[2072603852]. This usually happens when relationships are deleted by someone else just as we are about to load them. Please try again.
```

**Comment by spacecowboy** [comment]
Could you explain what the problem is? All you've done is posted an error message, one that tells you to try again at that.

**Comment by xghrbc1001** [comment]
hello @spacecowboy it's a big problem about me. one node has many relationships ,we update relationship time to time in order to synchronize with mysql . now while use cypher "start n = node(2344180375) match  (n)--(m) return count(1)" to query,this exception occurs. I don't know the reason and how to fix it.  I also try to found solution on stackoverflow,but no results. 

```
org.neo4j.graphdb.NotFoundException: Unable to load one or more relationships from Node[2344180375]. This usually happens when relationships are deleted by someone else just as we are about to load them. Please try again.
        at org.neo4j.kernel.impl.core.NodeImpl.loadMoreRelationships(NodeImpl.java:504)
        at org.neo4j.kernel.impl.core.NodeImpl.getMoreRelationships(NodeImpl.java:461)
        at org.neo4j.kernel.impl.core.RelationshipIterator.computeNext(RelationshipIterator.java:114)
        at org.neo4j.kernel.impl.core.RelationshipIterator.hasNext(RelationshipIterator.java:76)
        at org.neo4j.cypher.internal.helpers.JavaConversionSupport$$anon$1.hasNext(JavaConversionSupport.scala:27)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:29)
        at org.neo4j.kernel.impl.traversal.TraversalBranchImpl.next(TraversalBranchImpl.java:136)
        at org.neo4j.kernel.impl.traversal.TraversalBranchWithState.next(TraversalBranchWithState.java:32)
        at org.neo4j.kernel.impl.traversal.StartNodeTraversalBranch.next(StartNodeTraversalBranch.java:50)
        at org.neo4j.graphdb.traversal.PreorderDepthFirstSelector.next(PreorderDepthFirstSelector.java:49)
        at org.neo4j.kernel.AbstractSelectorOrderer.nextBranchFromSelector(AbstractSelectorOrderer.java:91)
        at org.neo4j.kernel.AbstractSelectorOrderer.nextBranchFromNextSelector(AbstractSelectorOrderer.java:79)
        at org.neo4j.kernel.AlternatingSelectorOrderer.next(AlternatingSelectorOrderer.java:42)
        at org.neo4j.kernel.impl.traversal.BidirectionalTraverserIterator.fetchNextOrNull(BidirectionalTraverserIterator.java:159)
        at org.neo4j.kernel.impl.traversal.BidirectionalTraverserIterator.fetchNextOrNull(BidirectionalTraverserIterator.java:44)
        at org.neo4j.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
        at org.neo4j.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
        at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:41)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at org.neo4j.cypher.internal.compiler.v2_2.ClosingIterator$$anonfun$next$1.apply(ResultIterator.scala:76)
        at org.neo4j.cypher.internal.compiler.v2_2.ClosingIterator$$anonfun$next$1.apply(ResultIterator.scala:71)
        at org.neo4j.cypher.internal.compiler.v2_2.ClosingIterator$$anonfun$failIfThrows$1.apply(ResultIterator.scala:120)
        at org.neo4j.cypher.internal.compiler.v2_2.ClosingIterator.decoratedCypherException(ResultIterator.scala:129)
        at org.neo4j.cypher.internal.compiler.v2_2.ClosingIterator.failIfThrows(ResultIterator.scala:118)
        at org.neo4j.cypher.internal.compiler.v2_2.ClosingIterator.next(ResultIterator.scala:71)
        at org.neo4j.cypher.internal.compiler.v2_2.ClosingIterator.next(ResultIterator.scala:49)
        at org.neo4j.cypher.internal.compiler.v2_2.PipeExecutionResult.next(PipeExecutionResult.scala:74)
        at org.neo4j.cypher.internal.compiler.v2_2.PipeExecutionResult$$anon$1.next(PipeExecutionResult.scala:58)
        at org.neo4j.cypher.javacompat.ExecutionResult$ExceptionConversion.next(ExecutionResult.java:320)
        at com.jindi.neo4j.plugin.web.service.DisServicesEnhance.disEnhanceVersionTwo(DisServicesEnhance.java:211)
        at com.jindi.neo4j.plugin.web.resource.DisResource.getDiscoveredRelationByIdEnhance(DisResource.java:79)
        at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at ch.qos.logback.access.servlet.TeeFilter.doFilter(TeeFilter.java:55)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.neo4j.server.rest.dbms.AuthorizationFilter.doFilter(AuthorizationFilter.java:120)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.neo4j.kernel.impl.store.InvalidRecordException: While loading relationships for Node[2344180375] a Relationship[855117090] was encountered that had startNode: 1989992235 and endNode: 2327388997, i.e. which had neither start nor end node as the node we're loading relationships for
        at org.neo4j.kernel.impl.transaction.state.RelationshipChainLoader.followRelationshipChain(RelationshipChainLoader.java:145)
        at org.neo4j.kernel.impl.transaction.state.RelationshipChainLoader.getMoreRelationships(RelationshipChainLoader.java:126)
        at org.neo4j.kernel.impl.core.RelationshipLoader.getMoreRelationships(RelationshipLoader.java:60)
        at org.neo4j.kernel.impl.core.NodeImpl.loadMoreRelationships(NodeImpl.java:500)
        ... 78 more

{"results":"errors":[{"code":"Neo.DatabaseError.Statement.ExecutionFailure","message":"Unable to load one or more relationships from Node[2344180375]. This usually happens when relationships are deleted by someone else just as we are about to load them. Please try again.","stackTrace":"org.neo4j.graphdb.NotFoundException: Unable to load one or more relationships from Node[2344180375]. This usually happens when relationships are deleted by someone else just as we are about to load them. Please try again.\n\tat org.neo4j.kernel.impl.core.NodeImpl.loadMoreRelationships(NodeImpl.java:504)\n\tat org.neo4j.kernel.impl.core.NodeImpl.getMoreRelationships(NodeImpl.java:461)\n\tat org.neo4j.kernel.impl.core.RelationshipIterator.computeNext(RelationshipIterator.java:114)\n\tat org.neo4j.kernel.impl.core.RelationshipIterator.hasNext(RelationshipIterator.java:76)\n\tat org.neo4j.cypher.internal.helpers.JavaConversionSupport$$anon$1.hasNext(JavaConversionSupport.scala:27)\n\tat scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)\n\tat scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:29)\n\tat org.neo4j.kernel.impl.traversal.TraversalBranchImpl.next(TraversalBranchImpl.java:136)\n\tat org.neo4j.kernel.impl.traversal.TraversalBranchWithState.next(TraversalBranchWithState.java:32)\n\tat org.neo4j.kernel.impl.traversal.StartNodeTraversalBranch.next(StartNodeTraversalBranch.java:50)\n\tat org.neo4j.graphdb.traversal.PreorderDepthFirstSelector.next(PreorderDepthFirstSelector.java:49)\n\tat org.neo4j.kernel.AbstractSelectorOrderer.nextBranchFromSelector(AbstractSelectorOrderer.java:91)\n\tat org.neo4j.kernel.AbstractSelectorOrderer.nextBranchFromNextSelector(AbstractSelectorOrderer.java:79)\n\tat org.neo4j.kernel.AlternatingSelectorOrderer.next(AlternatingSelectorOrderer.java:42)\n\tat org.neo4j.kernel.impl.traversal.BidirectionalTraverserIterator.fetchNextOrNull(BidirectionalTraverserIterator.java:159)\n\tat org.neo4j.kernel.impl.traversal.BidirectionalTraverserIterator.fetchNextOrNull(BidirectionalTraverserIterator.java:44)\n\tat org.neo4j.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)\n\tat org.neo4j.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)\n\tat scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:41)\n\tat scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)\n\tat scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)\n\tat scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)\n\tat org.neo4j.cypher.internal.compiler.v2_2.ClosingIterator$$anonfun$next$1.apply(ResultIterator.scala:76)\n\tat org.neo4j.cypher.internal.compiler.v2_2.ClosingIterator$$anonfun$next$1.apply(ResultIterator.scala:71)\n\tat org.neo4j.cypher.internal.compiler.v2_2.ClosingIterator$$anonfun$failIfThrows$1.apply(ResultIterator.scala:120)\n\tat org.neo4j.cypher.internal.compiler.v2_2.ClosingIterator.decoratedCypherException(ResultIterator.scala:129)\n\tat org.neo4j.cypher.internal.compiler.v2_2.ClosingIterator.failIfThrows(ResultIterator.scala:118)\n\tat org.neo4j.cypher.internal.compiler.v2_2.ClosingIterator.next(ResultIterator.scala:71)\n\tat org.neo4j.cypher.internal.compiler.v2_2.ClosingIterator.next(ResultIterator.scala:49)\n\tat org.neo4j.cypher.internal.compiler.v2_2.PipeExecutionResult.next(PipeExecutionResult.scala:74)\n\tat org.neo4j.cypher.internal.compiler.v2_2.PipeExecutionResult$$anon$2.next(PipeExecutionResult.scala:67)\n\tat org.neo4j.cypher.internal.compiler.v2_2.PipeExecutionResult$$anon$2.next(PipeExecutionResult.scala:65)\n\tat org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor2_2$$anon$1$$anonfun$next$1.apply(CompatibilityFor2_2.scala:210)\n\tat org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor2_2$$anon$1$$anonfun$next$1.apply(CompatibilityFor2_2.scala:210)\n\tat org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_2$.runSafely(CompatibilityFor2_2.scala:108)\n\tat org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor2_2$$anon$1.next(CompatibilityFor2_2.scala:210)\n\tat org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor2_2$$anon$1.next(CompatibilityFor2_2.scala:205)\n\tat org.neo4j.cypher.javacompat.ExecutionResult.next(ExecutionResult.java:214)\n\tat org.neo4j.cypher.javacompat.ExecutionResult.next(ExecutionResult.java:50)\n\tat org.neo4j.server.rest.transactional.ExecutionResultSerializer.writeRows(ExecutionResultSerializer.java:374)\n\tat org.neo4j.server.rest.transactional.ExecutionResultSerializer.statementResult(ExecutionResultSerializer.java:108)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.executeStatements(TransactionHandle.java:329)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:146)\n\tat org.neo4j.server.rest.web.TransactionalService$2.write(TransactionalService.java:211)\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)\n\tat com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)\n\tat com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)\n\tat ch.qos.logback.access.servlet.TeeFilter.doFilter(TeeFilter.java:55)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.neo4j.server.rest.dbms.AuthorizationFilter.doFilter(AuthorizationFilter.java:120)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:497)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: org.neo4j.kernel.impl.store.InvalidRecordException: While loading relationships for Node[2344180375] a Relationship[855117090] was encountered that had startNode: 1989992235 and endNode: 2327388997, i.e. which had neither start nor end node as the node we're loading relationships for\n\tat org.neo4j.kernel.impl.transaction.state.RelationshipChainLoader.followRelationshipChain(RelationshipChainLoader.java:145)\n\tat org.neo4j.kernel.impl.transaction.state.RelationshipChainLoader.getMoreRelationships(RelationshipChainLoader.java:126)\n\tat org.neo4j.kernel.impl.core.RelationshipLoader.getMoreRelationships(RelationshipLoader.java:60)\n\tat org.neo4j.kernel.impl.core.NodeImpl.loadMoreRelationships(NodeImpl.java:500)\n\t... 77 more\n"}]}
```

**Comment by spacecowboy** [comment]
The exception is telling you that `node(2344180375)` does not have any relationships, so that's why your query fails.

Seems like you deleted your relationships at some point.

**Comment by xghrbc1001** [comment]
@spacecowboy  node(2344180375) has  relationships. mybe some relationship has been deleted. do you have some suggestion about how to fixed it ,because it's a online product.

**Comment by xghrbc1001** [comment]
@spacecowboy whether neo4j's cache has relation,but disk not exist?

**Comment by spacecowboy** [comment]
It's a possibility.

Another possibility is that your store is corrupted. Try running the consistency checker to find out: https://neo4j.com/developer/kb/how-do-i-run-consistency-check-manually/

**Comment by xghrbc1001** [comment]
@spacecowboy  we use https://neo4j.com/developer/kb/how-do-i-run-consistency-check-manually/ and found this message. and how to fix it?

```
  2016-06-29 07:14:08.882+0000 INFO  [org.neo4j]: ERROR: The property chain contains multiple properties that have the same property key id, which means that the entity has at least one duplicate property.
        Node[3306276,used=true,rel=868611378,prop=445109383,labels=Inline(0x1000000000:[0]),light]
2016-06-29 07:14:08.884+0000 INFO  [org.neo4j]: ERROR: The property chain contains multiple properties that have the same property key id, which means that the entity has at least one duplicate property.
        Node[3306276,used=true,rel=868611378,prop=445109383,labels=Inline(0x1000000000:[0]),light]
  2016-06-29 07:21:10.616+0000 INFO  [org.neo4j]: ERROR: The property chain contains multiple properties that have the same property key id, which means that the entity has at least one duplicate property.
        Node[10593481,used=true,rel=881067472,prop=942617760,labels=Inline(0x1000000000:[0]),light]
```

**Comment by spacecowboy** [comment]
That's unfortunate :(

You can try and use https://github.com/jexp/store-utils as mentioned in this answer here http://stackoverflow.com/questions/28651194/fixing-neo4j-consistency-errors

Please direct further support questions to stackoverflow or ask in our public slack channel. You'll get much better help there: https://neo4j.com/blog/public-neo4j-users-slack-group/
