### ISSUE TITLE
Problem starting neo4j with imported database

### ISSUE THREAD

**Issue by dimosr** [neo4j/neo4j#7445]
## neo4j startup problems after neo4j-import

The details of my environment are the following:
- Neo4j version: 3.0.3 Community
- Operating system: Ubuntu v14.04
- API/Driver: neo4j-import
### Steps to reproduce
- Setup VM with Ubuntu 14.04 (50GB HDD, 8GB memory)
- Install Java 8 Oracle
- Download neo4j from website from [here](https://neo4j.com/artifact.php?name=neo4j-community-3.0.3-unix.tar.gz)
- Execute the command 
  `bin/neo4j-import --into data/databases/small.db --id-type string --nodes:Domain nodes.csv --relationships:POINTS_TO edges.csv`
- Configure the following property in file "<neo4j-root-folder>/conf/neo4j.conf":
  `dbms.active_database=small.db`
- Start neo4j
  `bin/neo4j start`
### Expected behavior
- Successful import of database with reporting of the imported nodes,relationships,properties
- Successful startup of neo4j
### Actual behavior
- Import of database is successful at the first time. After the first time, however, if I delete the database and re-try importing, the import fails with the following error message:

``` sh
e. Please see attached cause exception.
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:416)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:427)
    at org.neo4j.kernel.lifecycle.LifeSupport.bringToState(LifeSupport.java:316)
    at org.neo4j.kernel.lifecycle.LifeSupport.add(LifeSupport.java:248)
    at org.neo4j.unsafe.impl.batchimport.store.BatchingNeoStores.<init>(BatchingNeoStores.java:150)
    at org.neo4j.unsafe.impl.batchimport.ParallelBatchImporter.doImport(ParallelBatchImporter.java:131)
    at org.neo4j.tooling.ImportTool.main(ImportTool.java:390)
    at org.neo4j.tooling.ImportTool.main(ImportTool.java:292)
Caused by: java.io.IOException: Unable to create directory path [small.db/schema/label/lucene/labelStore] for Neo4j store.
    at org.neo4j.io.fs.DefaultFileSystemAbstraction.mkdirs(DefaultFileSystemAbstraction.java:108)
    at org.neo4j.kernel.api.impl.index.storage.PartitionedIndexStorage.prepareFolder(PartitionedIndexStorage.java:138)
    at org.neo4j.kernel.api.impl.index.AbstractLuceneIndex.create(AbstractLuceneIndex.java:85)
    at org.neo4j.kernel.api.impl.labelscan.LuceneLabelScanStore.init(LuceneLabelScanStore.java:150)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
    ... 7 more
```

Note that if I logout from the VM and login again, then the import works without any other change for the first time again and then fails.
- After successfully importing the database, and starting neo4j server (`bin/neo4j start`), the startup fails with the following error logs (you can also check full logs in the zip):

``` sh
2016-06-24 11:16:08.436+0000 WARN  [o.n.k.NeoStoreDataSource] Exception occurred while setting up store modules. Attempting to close things down. Unable to find high id by scanning backwards /home/ddr15/homedir/Desktop/neo4j/neo4j-community-3.0.3/data/databases/small.db/neostore.nodestore.db.labels
org.neo4j.kernel.impl.store.UnderlyingStorageException: Unable to find high id by scanning backwards /home/ddr15/homedir/Desktop/neo4j/neo4j-community-3.0.3/data/databases/small.db/neostore.nodestore.db.labels
    at org.neo4j.kernel.impl.store.CommonAbstractStore.scanForHighId(CommonAbstractStore.java:725)
    at org.neo4j.kernel.impl.store.CommonAbstractStore.openIdGenerator(CommonAbstractStore.java:665)
    at org.neo4j.kernel.impl.store.CommonAbstractStore.openIdGenerator(CommonAbstractStore.java:652)
    at org.neo4j.kernel.impl.store.CommonAbstractStore.loadIdGenerator(CommonAbstractStore.java:346)
    at org.neo4j.kernel.impl.store.CommonAbstractStore.loadStorage(CommonAbstractStore.java:252)
    at org.neo4j.kernel.impl.store.CommonAbstractStore.initialise(CommonAbstractStore.java:127)
    at org.neo4j.kernel.impl.store.NeoStores.initialize(NeoStores.java:224)
    at org.neo4j.kernel.impl.store.NeoStores.createDynamicArrayStore(NeoStores.java:501)
    at org.neo4j.kernel.impl.store.NeoStores.createDynamicArrayStore(NeoStores.java:491)
    at org.neo4j.kernel.impl.store.StoreType$1.open(StoreType.java:35)
    at org.neo4j.kernel.impl.store.StoreType$1.open(StoreType.java:30)
    at org.neo4j.kernel.impl.store.NeoStores.openStore(NeoStores.java:217)
    at org.neo4j.kernel.impl.store.NeoStores.getOrCreateStore(NeoStores.java:262)
    at org.neo4j.kernel.impl.store.NeoStores.<init>(NeoStores.java:136)
    at org.neo4j.kernel.impl.store.StoreFactory.openNeoStores(StoreFactory.java:158)
    at org.neo4j.kernel.impl.store.StoreFactory.openAllNeoStores(StoreFactory.java:122)
    at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.<init>(RecordStorageEngine.java:210)
    at org.neo4j.kernel.NeoStoreDataSource.buildStorageEngine(NeoStoreDataSource.java:573)
    at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:441)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
    at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:99)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:140)
    at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:40)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108)
    at org.neo4j.server.CommunityNeoServer.lambda$static$31(CommunityNeoServer.java:55)
    at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:189)
    at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:87)
    at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:66)
    at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: java.io.IOException: Input/output error
    at sun.nio.ch.FileDispatcherImpl.pread0(Native Method)
    at sun.nio.ch.FileDispatcherImpl.pread(FileDispatcherImpl.java:52)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:220)
    at sun.nio.ch.IOUtil.read(IOUtil.java:192)
    at sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:741)
    at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:727)
    at org.neo4j.io.fs.StoreFileChannel.read(StoreFileChannel.java:105)
    at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.swapIn(SingleFilePageSwapper.java:240)
    at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.read(SingleFilePageSwapper.java:296)
    at org.neo4j.io.pagecache.impl.muninn.MuninnPage.fault(MuninnPage.java:192)
    at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.pageFault(MuninnPageCursor.java:334)
    at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.initiatePageFault(MuninnPageCursor.java:285)
    at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.uncommonPin(MuninnPageCursor.java:266)
    at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.pin(MuninnPageCursor.java:249)
    at org.neo4j.io.pagecache.impl.muninn.MuninnReadPageCursor.next(MuninnReadPageCursor.java:60)
    at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.next(MuninnPageCursor.java:119)
    at org.neo4j.kernel.impl.store.CommonAbstractStore.scanForHighId(CommonAbstractStore.java:685)
    ... 34 more
```

Note also that I successfully managed to startup neo4j with an empty database and import the same CSV files using `LOAD CSV`.
[files.zip](https://github.com/neo4j/neo4j/files/331767/files.zip)

**All files included in the zip

**Comment by chrisvest** [comment]
`java.io.IOException: Input/output error` often means that there is something wrong with the storage hardware, which is preventing the file system from completing the IO requests.

When you deleted the database after the first import, did you also delete the `small.db` directory, or just its contents? Were any other programs keeping file handles to the old deleted files when you started the second import?
- Please `ls` the contents of the `databases` and the `databases/small.db` directories to verify that the files haven't been misplaced somehow.
- Verify that the user that Neo4j runs with have the appropriate permissions to read and write files, and to create files, in the `databases` and `databases/small.db` directories.
- Check `dmesg` for any indications of problems with storage devices or file systems.
- Check your drive for any SMART errors. Some drives can do more thorough checks than others. The `smartctl` tool is a good place to start looking into this stuff. I'm assuming this is possible to do, but it might not be since you are on a VM. If you have problems with the physical drives, then they might go away anyway if you just boot up a new VM. If you are using networked storage, then a different VM will perhaps not make much difference.
- Check your filesystem integrity with `fsck`.

**Comment by dimosr** [comment]
Please note that I just repeated the same procedure in my local machine and everything worked as expected. The VM I worked on previously, it was provisioned over CloudStack and there are things about the physical machines used that I am not aware of (since it was academic infrastructure), such as the shared storage. So, this issue is probably not related to Neo4j and can be closed. Just for the history, while working in the VM:
- each time I deleted the database I removed the whole folder of `small.db`
- each time I deleted the database, I had previously stopped neo4j server, so there are no processes, I could be "aware" of, keeping file handles.
- I listed all the directories inside the root folder to make sure everything was ok
- The permissions of the folder and all the contents are `rwxr-xr-x` and neo4j is executed with the owner of the files as user
- Made an initial check for problems with storage devices or filesystem integrity and it all seemed ok. However, I will keep you posted if anything new is found.
- I have also tried to copy the successfully imported database from my local machine to the VM and try to start the neo4j instance and it keeps failing with exactly the same logs.

Thanks.
