### ISSUE TITLE
neo4j does not start on freshly rebooted machine; tells port is bound

### ISSUE THREAD

**Issue by chrimobs** [neo4j/neo4j#7459]
I had neo4j previously running on my machine. Eventually, I had a conflict where I tried neo4j console while an instance was running within Firefox. I closed the browser window, but was not able to start neo4j in the console afterwards, however. `netstat -tulp` did not show any bindings to `:7474`, nor did `lsof -i :7474`, nor did `pgrep -fl neo` show any entries.

What I tried:
- deleting an (apparently) orphaned pid file in neo4j/run/ (did not help)
- restarting my X session (did not help)
- restarting the machine (did not help either)

Now, on the freshly rebooted machine, when I try `neo4j console` it still terminates with an exception telling that port `7474` is already bound?
- Neo4j version: 3.0.3 (community)
- Operating system: Kubuntu 14.04
#### Stack Trace

```
2016-06-28 07:06:25.275+0000 INFO  Starting...
2016-06-28 07:06:25.956+0000 INFO  Bolt enabled on localhost:7687.
2016-06-28 07:06:28.939+0000 INFO  Started.
2016-06-28 07:06:30.009+0000 WARN  FAILED ServerConnector@6724fbcd{SSL-HTTP/1.1}{localhost:7474}: java.net.BindException: Die Adresse wird bereits verwendet Die Adresse wird bereits verwendet
java.net.BindException: Die Adresse wird bereits verwendet
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:433)
    at sun.nio.ch.Net.bind(Net.java:425)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
    at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
    at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.server.Server.doStart(Server.java:366)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:353)
    at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:168)
    at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:316)
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:208)
    at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:87)
    at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:66)
    at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
2016-06-28 07:06:30.011+0000 WARN  FAILED org.eclipse.jetty.server.Server@630c31b4: java.net.BindException: Die Adresse wird bereits verwendet Die Adresse wird bereits verwendet
java.net.BindException: Die Adresse wird bereits verwendet
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:433)
    at sun.nio.ch.Net.bind(Net.java:425)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
    at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
    at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.server.Server.doStart(Server.java:366)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:353)
    at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:168)
    at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:316)
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:208)
    at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:87)
```

**Comment by spacecowboy** [comment]
> I closed the browser window

This has zero impact on neo4j.

> nor did lsof -i :7474

You might need to call that as root to actually get any results

``` sh
lsof -i :7474
```

I will assume that you installed the debian package, and so you have a neo4j service running in the background. This is started automatically when the computer boots.

You can start and stop it by doing

``` sh
sudo service neo4j stop
```

and 

``` sh
sudo service neo4j start
```

To be able to call `neo4j console`, you either
- first need to stop the system service
- or change the configuration to bind to a different port

**Comment by chrimobs** [comment]
I did not install the debian package. Just D/L'd the tar.gz from the website, extracted, and called `neo4j start` then.

```
# lsof -i :7474
# service neo4j stop
neo4j: unrecognized service
# ls /etc/init.d/ | grep -i neo
# netstat -tulpn | grep 7474
#
```

**Comment by spacecowboy** [comment]
OK. Does it work if you bind to another port? Change it in you `neo4j.conf` file:

Set for example 

```
dbms.connector.http.address=0.0.0.0:52941
```

**Comment by chrimobs** [comment]
Yes. If I e.g. bind to port `7432` the server starts. However, this is odd:

```
2016-06-28 13:13:38.805+0000 INFO  Starting...
2016-06-28 13:13:39.490+0000 INFO  Bolt enabled on localhost:7687.
2016-06-28 13:13:42.365+0000 INFO  Started.
2016-06-28 13:13:43.436+0000 INFO  Remote interface available at http://localhost:7474/
```

and indeed, the remote interface is available on that address: `http://localhost:7474/browser/`. Should that not be `7432` as well?

(I just `CTRL+c`'d, changed to `7474` in the conf again and started `neo4j` just to see what happens - the error persists. Again on `7432` it starts.

**Comment by spacecowboy** [comment]
that's odd.. Could you paste your entire `neo4j.conf` file?

**Comment by chrimobs** [comment]
Okay - I see the reason. I had a mixup of HTTP and HTTPS config entries enabled that caused the conflict.
