### ISSUE TITLE
Neo4j HA cluster not starting

### ISSUE THREAD

**Issue by ratnesh-ray** [neo4j/neo4j#7591]
The following error was discovered on running Neo4j in HA mode from the Neo4j HA guide/tutorial:

2016-07-17 18:11:45.320+0000 INFO  Starting...
2016-07-17 18:11:46.020+0000 INFO  Write transactions to database disabled
2016-07-17 18:11:46.535+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2016-07-17 18:11:46.566+0000 INFO  Initiating metrics...
2016-07-17 18:11:47.875+0000 INFO  Attempting to join cluster of [52.123.123.123:5001, 52.234.234.234:5001, 52.345.345.345:5001]
2016-07-17 18:13:07.943+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1b38563a' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1b38563a' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1b38563a' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:217)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:87)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:66)
        at org.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1b38563a' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:189)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.ha.factory.HighlyAvailableFacadeFactory, /var/lib/neo4j/data/databases/graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:144)
        at org.neo4j.kernel.ha.factory.HighlyAvailableFacadeFactory.newFacade(HighlyAvailableFacadeFactory.java:42)
        at org.neo4j.kernel.ha.HighlyAvailableGraphDatabase.<init>(HighlyAvailableGraphDatabase.java:41)
        at org.neo4j.server.enterprise.EnterpriseNeoServer.lambda$static$0(EnterpriseNeoServer.java:80)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.cluster.client.ClusterJoin@27564996' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:140)
        ... 10 more
Caused by: java.util.concurrent.TimeoutException
        at org.neo4j.cluster.statemachine.StateMachineProxyFactory$ResponseFuture.get(StateMachineProxyFactory.java:300)
        at org.neo4j.cluster.client.ClusterJoin.joinByConfig(ClusterJoin.java:143)
        at org.neo4j.cluster.client.ClusterJoin.start(ClusterJoin.java:82)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
        ... 14 more

Neo4j version: 3.0.3
Operating system: Linux(Ubuntu)

**Comment by spacecowboy** [comment]
Your IPs look weird

```
Attempting to join cluster of [52.123.123.123:5001, 52.234.234.234:5001, 52.345.345.345:5001]
```

This is not a valid IP address: `52.345.345.345`

What's your network configuration? Any firewalls etc? Local network, virtual machines, etc...

 , and what does your `neo4j.conf` files look like?

**Comment by ghost** [comment]
I have received the same exception when restarting my cluster. It was running okay before and then i changed the pull_interval to 1s  and could not start the cluster after

**Comment by ipolishchuk** [comment]
I have the same problem on 3.0.1. Changed dbms.unmanaged_extension_classes, and cannot restart my cluster anymore.

**Comment by jexp** [comment]
Can you provide more detail

All your configs and debug.log from each machine?

Von meinem iPhone gesendet

**Comment by ipolishchuk** [comment]
Michael,
Thank you for you response. The log files from a single node and configs from an arbiter and two nodes are attached.
Neo4j version 3.0.1
Amazon Linux

 uname -a
Linux node-a2548236 4.1.10-17.31.amzn1.x86_64 #1 SMP Sat Oct 24 01:31:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by spacecowboy** [comment]
@ipolishchuk e-mail attachments do not show up on GitHub. Could you please provide links to the files or actually paste the contents?

**Comment by ghost** [comment]
Michael,
I am attaching my log files and conf files here from my 3 nodes. All my 3 nodes are EC2 instances and the firewall is configured properly since the cluster was running okay before i restarted it. Was not able to figure the actual cause from the exception messages. I also tried cleaning the database directory thinking maybe it was a data issue but that did not solve it.

[neo4j.zip](https://github.com/neo4j/neo4j/files/413710/neo4j.zip)

**Comment by ipolishchuk** [comment]
Sorry guys, I've uploaded the logs and configs here
[neo4j.zip](https://github.com/neo4j/neo4j/files/413850/neo4j.zip)

**Comment by ipolishchuk** [comment]
I've figure some magical sequence of actions that allows me to start the cluster. I have 2 node ha cluster with an arbiter.  My arbiter always fails first, and other two nodes follow. However, if I execute start an all three servers and restart the arbiter two more times while the other two nodes are still trying to start, I'm able to start the entire cluster. This is a ridiculous procedure, but this is the only one I've found so far to start the cluster. And not, it is not a networking issue, because after that elaborate restart, everything is working. It seems that something does not work on arbiter.

**Comment by ipolishchuk** [comment]
I need to restart the arbiter two more times, because after first extra restart everything seems working, but I have this in the neo4j.log on the arbiter: 
2016-08-15 22:06:28.408+0000 INFO  [o.n.c.c.ClusterJoin] Could not join cluster of [10.101.213.127:5001, 10.101.218.82:5001, 10.101.222.137:5001]
2016-08-15 22:06:28.408+0000 INFO  [o.n.c.c.ClusterJoin] Creating new cluster with name [neo4j.ha]...

After the second arbiter restart, I finally see:
2016-08-15 22:08:49.188+0000 INFO  [o.n.c.c.ClusterJoin] Joined cluster: Name:neo4j.ha Nodes:{0=cluster://10.101.213.127:5001, 1=cluster://10.101.218.82:5001, 2=cluster://10.101.222.137:5001} Roles:{coordinator=1}

**Comment by zhangkeke123456** [comment]
I have the same problem on 3.0.7,but I think "Write transactions to database disabled" is the most serious problem .IN single,when start neo4j,the problem is not appeared.

**Comment by elementsean** [comment]
Any resolution here?  

I'm running into a similar issue trying to do a full build of the system from source and would love any ideas as to why.

This is from the git tag "3.1.2".

Thanks,
-S


```
Running org.neo4j.tools.rebuild.RebuildFromLogsTest
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 217.876 sec <<< FAILURE! - in org.neo4j.ha.TestBranchedData
shouldCopyStoreFromMasterIfBranchedInLiveScenario(org.neo4j.ha.TestBranchedData)  Time elapsed: 90.996 sec  <<< ERROR!
org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.ha.ClusterManager@345965f2' was successfully initialized, but failed to start. Please see attached cause exception.
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at org.neo4j.kernel.impl.ha.ClusterManager$HighlyAvailableGraphDatabaseProxy.get(ClusterManager.java:957)
        at org.neo4j.kernel.impl.ha.ClusterManager$ManagedCluster.<init>(ClusterManager.java:1076)
        at org.neo4j.kernel.impl.ha.ClusterManager.start(ClusterManager.java:696)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        at org.neo4j.kernel.lifecycle.LifeSupport.bringToState(LifeSupport.java:315)
        at org.neo4j.kernel.lifecycle.LifeSupport.add(LifeSupport.java:248)
        at org.neo4j.kernel.lifecycle.LifeRule.add(LifeRule.java:83)
        at org.neo4j.ha.TestBranchedData.shouldCopyStoreFromMasterIfBranchedInLiveScenario(TestBranchedData.java:138)
```

**Comment by stormit-vn** [comment]
Hi all,

I also encountering this problem. This problem seem occurs after setting default password using below command
neo4j-admin set-initial-password password

If I create new cluster without running above commant, Neo4j can start without any issue.

Does anyone has any resolution to fix this?

Thanks,
Hoang

**Comment by hodonsky** [comment]
@stormit-vn You need to set your ENV VARs to match
NEO4J_AUTH=username/password

**Comment by stormit-vn** [comment]
@relicmelex  yeah, i figured out the root cause, it is because of the permission issue, I run above comment with root user, hence, neo4j does not have permission on /var/lib/neo4j/data/dbms/, so i have add a script to set permission for neo4j and cluster can run without any errors

**Comment by mnd999** [comment]
HA clustering is obsolete.
