### ISSUE TITLE
Neo4j-import: Option for Skip Header Line for Large Files if Header Files are Used

### ISSUE THREAD

**Issue by graphadvantage** [neo4j/neo4j#7641]
### Feature request

Add an option in neo4j-import to skip the header line in very large CSV files, for use when separate header files are used.
### Scenario

In enterprise data work, it's not unusual to have a data pipeline where one team is doing data extraction and shipping very large CSVs to another team tasked with building the Neo4j graph.  Neo4j-import lets the graph team design compact header files so that the very large CSVs do not have to be opened and edited (which is great!).  Currently, neo4j-import requires that no header line is present in the very large CSVs to be loaded using separate header files.  

The problem is that it's difficult to diagnose extract issues on deep and wide files missing headers when imports fail.  So for very large files, it's a better practice to keep the headers on so that they can be easily validated against the designed header file CSVs that carry the key assignments, data types etc.  Under the current set of options, either the large CSV has to be generated without a header line (adding IT mystery) or the graph team has to go in and remove the header line once the extract is validated (adding Dev hassle).

Currently, if the large CSV has a header row, neo4j-import will attempt to create a node using the header data as property values - which may not always work if conflicting data types are set in the header file. 
### Possible implementation

```
C:/neo4j/bin/neo4j-import --skip-header-line TRUE \
--into graph.db \
--nodes:MyLabel: "My_Header.csv, My_Very_Large_File.csv" 
```

default value would be `--skip-header-line FALSE` to be consistent with basic usage without header CSV files.
### Expected behavior

CSV import would start at first data line of My_Very_Large_File.csv, skipping the header line.
The header values are supplied by My_Header.csv, as per usual.
### Note

A more general case would be:
`--start-import-at-line n`
where n is any arbitrary line number in the file...

Thanks,

Michael

**Comment by yegor-novinsky** [comment]
Hi!
For the last days I've been trying to think up how to add the --start-import-at-line option. Since I'm new to neo4j adding this feature will take rather long. So if anyone else will add this feature it's all right. But, all the same I'd like to work on adding this feature.
It was a preamble...
Now I would like to ask several questions concerning implementation of this feature. I don't think the questions are very smart, but one should begin somewhere...
Here I describe a part of nodes import algorithm as I understand it. I believe changes should be made in this part of the import algorithm.
1. As far as I can see, nodes are imported in batches. Default size of a batch is 10000. 
2. At the first step of the Node stage of import (org.neo4j.unsafe.impl.batchimport.InputIteratorBatcherStep), in the method _process_ of the org.neo4j.unsafe.impl.batchimport.staging.ProducerStep class, nodes are read in batches and each batch is tranfered to the next step.

Here are my proposals:
1. Add option start-import-at-line to the org.neo4j.tooling.ImportTool.Options enumeration.  To me this proposal is obvious.
2. Add method to the org.neo4j.csv.reader.Configuration interface returning start line. This proposal is obvious too.
3. Create class org.neo4j.unsafe.impl.batchimport.NodesInputIteratorBatcherStep<T> extending IteratorBatcherStep<T>. In this new class override the _nextBatchOrNull_ method so that first several lines could be skipped - number of lines to skip is specified in configuration. But lines are to be skipped in the first batch only - to accomplish this the method _process_ of the org.neo4j.unsafe.impl.batchimport.staging.ProducerStep class should be overridden in the NodesInputIteratorBatcherStep class too. I'm not sure in this proposal absolutely. 
4. In construction of object of the NodeStage class add as the first step of Node stage an object of the org.neo4j.unsafe.impl.batchimport.NodesInputIteratorBatcherStep<T> class instead of the org.neo4j.unsafe.impl.batchimport.InputIteratorBatcherStep<T> class . If the proposal 3 is correct this one seems to be correct too.

Could you please comment/criticise the written above. Of course, if you feel that it - commenting/criticising my proposals - makes sense. 
Thanks in advance.
Yegor.

**Comment by jexp** [comment]
Best just state the issue at hand in the main issue and add the rest as a comment 

Is it too difficult to strip the header line?

If you want to generalize the option you could provide a range or ranges of a file to be imported which would also be nice for testing. 

Von meinem iPhone gesendet

**Comment by graphadvantage** [comment]
this seems clean and simple:
1. Add option start-import-at-line to the org.neo4j.tooling.ImportTool.Options enumeration.

**Comment by yegor-novinsky** [comment]
Yes, It is. But it doesn't solve the problem at all.

**Comment by morenobonaventura** [comment]
I agree it would be an un useful feature!

**Comment by graphadvantage** [comment]
here's another reason why this would be good

Suppose the IDs for my data are all integers, and I'd like them typed that way on import.

I also want to use header files

/neo4j/bin/neo4j-import \
  --input-encoding UTF8 --delimiter | \
  --id-type integer \
  --ignore-empty-strings true \
  --ignore-extra-columns true --skip-duplicate-nodes true \
  --skip-bad-relationships true --bad-tolerance 10000000 --stacktrace true \
  --into /Users/ecoreefsmpg/neo4j/data/databases/ean-graph.db \
  --nodes:Property "/neo4j/import/ean/ActivePropertyList.txt.zip", \

import fails, because the first line of the input file is still the header line...and it sees the string.

  raw field value: EANHotelID:ID
  original error: Not an integer: "EANHotelID:ID"

Neo4j version: 3.1.0-M09
Importing the contents of these files into /neo4j/data/databases/ean-graph.db:
Nodes:
  :Property
  /neo4j/import/headers/Header_ActivePropertyList.txt
  /neo4j/import/ean/ActivePropertyList.txt.zip

Available resources:
  Free machine memory: 45.52 GB
  Max heap memory : 14.22 GB
  Processors: 24

Nodes
[*>:??----------------------------------------------------------------------------------------]    0Error in input data
Caused by:ERROR in input
  data source: BufferedCharSeeker[source:/neo4j/import/ean/ActivePropertyList.txt.zip, position:14, line:0]
  in field: EANHotelID:ID:1
  for header: [EANHotelID:ID, SequenceNumber:int, Name:string, Address1:string, Address2:string, City:string, StateProvince:string, PostalCode:string, Country:string, Latitude:float, Longitude:float, AirportCode:string, PropertyCategory:int, PropertyCurrency:string, StarRating:float, Confidence:int, SupplierType:string, Location:string, ChainCodeID:int, RegionID:int, HighRate:float, LowRate:float, CheckInTime:string, CheckOutTime:string]
  raw field value: EANHotelID:ID
  original error: Not an integer: "EANHotelID:ID"
org.neo4j.unsafe.impl.batchimport.input.InputException: ERROR in input
  data source: BufferedCharSeeker[source:/neo4j/import/ean/ActivePropertyList.txt.zip, position:14, line:0]
  in field: EANHotelID:ID:1
  for header: [EANHotelID:ID, SequenceNumber:int, Name:string, Address1:string, Address2:string, City:string, StateProvince:string, PostalCode:string, Country:string, Latitude:float, Longitude:float, AirportCode:string, PropertyCategory:int, PropertyCurrency:string, StarRating:float, Confidence:int, SupplierType:string, Location:string, ChainCodeID:int, RegionID:int, HighRate:float, LowRate:float, CheckInTime:string, CheckOutTime:string]
  raw field value: EANHotelID:ID
  original error: Not an integer: "EANHotelID:ID"
    at org.neo4j.unsafe.impl.batchimport.input.csv.InputEntityDeserializer.deserializeNextFromSource(InputEntityDeserializer.java:179)
    at org.neo4j.unsafe.impl.batchimport.input.csv.InputEntityDeserializer.fetchNextOrNull(InputEntityDeserializer.java:78)
    at org.neo4j.unsafe.impl.batchimport.input.csv.InputEntityDeserializer.fetchNextOrNull(InputEntityDeserializer.java:42)
    at org.neo4j.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
    at org.neo4j.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
    at org.neo4j.unsafe.impl.batchimport.input.csv.ParallelInputEntityDeserializer.lambda$new$0(ParallelInputEntityDeserializer.java:89)
    at org.neo4j.unsafe.impl.batchimport.staging.TicketedProcessing.lambda$submit$0(TicketedProcessing.java:121)
    at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:242)
Caused by: java.lang.NumberFormatException: Not an integer: "EANHotelID:ID"
    at org.neo4j.csv.reader.Extractors.extractLong(Extractors.java:958)
    at org.neo4j.csv.reader.Extractors.access$000(Extractors.java:65)
    at org.neo4j.csv.reader.Extractors$LongExtractor.extract0(Extractors.java:361)
    at org.neo4j.csv.reader.Extractors$AbstractSingleValueExtractor.extract(Extractors.java:287)
    at org.neo4j.csv.reader.BufferedCharSeeker.tryExtract(BufferedCharSeeker.java:238)
    at org.neo4j.unsafe.impl.batchimport.input.csv.InputEntityDeserializer.deserializeNextFromSource(InputEntityDeserializer.java:139)
    ... 7 more

**Comment by chasemc** [comment]
This feature would be useful and, if possible, a flag for each import statement would be great. Currently pulling files from multiple locations, some have headers, some don't

**Comment by tinwelint** [comment]
To not make configuring this overly complicated, would it be OK with this approach:

`--auto-skip-header-line true` will automatically look at header lines for each file and if it looks like a header line it will skip it. 

The reason it shouldn't always be true and always do that would be that a data line may accidentally, even tho very unlikely, look like a header line. Otherwise there would have to be some way of tagging each file with yes/no on "has header line", which I can imagine be tedious and error prone.
