### ISSUE TITLE
ServerStartupException: IO problem while loading or creating TLS certificates on Linux

### ISSUE THREAD

**Issue by adriens** [neo4j/neo4j#7761]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests.  If you have questions on how to use Neo4j, please ask on [StackOverflow](http://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

If you want to make a feature request then there is no guideline, so feel free to stop reading and open an issue. If you have a bug report however, please continue reading.

To help us understand your issue, please specify important details, primarily:
- Neo4j version: community-3.0.4
- Operating system: Linux Mint 17.3 Rosa
- API/Driver: (for example Cypher/Java API/Python driver vX.Y.Z)
- **Steps to reproduce** : neo4j-community-3.0.4/bin/neo4j console (just try to start server)
- Expected behavior : should have started
- Actual behavior get the following stacktrace :

```
➜  ~ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
➜  ~ /opt/neo4j-community-3.0.4/bin/neo4j console
Starting Neo4j.
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
2016-08-22 02:03:32.502+0000 INFO  No SSL certificate found, generating a self-signed certificate..
2016-08-22 02:03:32.768+0000 ERROR Failed to start Neo4j: IO problem while loading or creating TLS certificates: /opt/neo4j-community-3.0.4/certificates/neo4j.cert (No such file or directory) IO problem while loading or creating TLS certificates: /opt/neo4j-community-3.0.4/certificates/neo4j.cert (No such file or directory)
org.neo4j.server.ServerStartupException: IO problem while loading or creating TLS certificates: /opt/neo4j-community-3.0.4/certificates/neo4j.cert (No such file or directory)
        at org.neo4j.server.AbstractNeoServer.createKeyStore(AbstractNeoServer.java:419)
        at org.neo4j.server.AbstractNeoServer.init(AbstractNeoServer.java:173)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:186)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:67)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: java.io.FileNotFoundException: /opt/neo4j-community-3.0.4/certificates/neo4j.cert (No such file or directory)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at java.io.FileWriter.<init>(FileWriter.java:90)
        at org.neo4j.bolt.security.ssl.Certificates.writePem(Certificates.java:195)
        at org.neo4j.bolt.security.ssl.Certificates.createSelfSignedCertificate(Certificates.java:113)
        at org.neo4j.server.AbstractNeoServer.createKeyStore(AbstractNeoServer.java:389)
        ... 5 more

```

I don't knwo what i have missed, the fact is that in the tar.gz, there is no certificates dir.

**Comment by spacecowboy** [comment]
You haven't mentioned how you installed neo4j. I am assuming that you extracted the tarball to `/opt`.

I think the reason for the exception is simple. You don't have write permissions in `/opt/neo4j-community-3.0.4/`

maybe you extracted the tarball as `sudo`, and then tried starting neo4j as your normal user?

**Comment by mantri-govind** [comment]
I also had same issue.. all you need to do is run neo4j with sudo, as suggested by @spacecowboy normal user don't have permission to write.

**Comment by chrisvest** [comment]
Instead of running Neo4j as the `root` user (by running it with `sudo`), you can `sudo chown -R user:group path` such that the Neo4j install directory is owned by the user that the Neo4j process will run with.

I'll assume this is all there is to this issue and close it. It can always be reopened if need be.

**Comment by annevanleyden** [comment]
I think neo4j should not write to the installation tree, but to a separate config dir. Maybe in the home directory of user that runs the process?

**Comment by spacecowboy** [comment]
@anneq neo4j has its own home dir. It is typically where you unpacked/installed it, but it can be changed to any directory. This is the directory where `/conf` directory and `/data` directory lives for example.
