### ISSUE TITLE
3.1M08 Shiro authentication timeout after 30 minutes for long-running queries

### ISSUE THREAD

**Issue by graphadvantage** [neo4j/neo4j#7886]
Windows Server 2012 R2 Azure D15v2 Standard 140GB, 20 cores, SSD

Neo4j 3.1M08 Enterprise

I have a large graph and my transactions are timing out after 30 minutes, irrespective of driver. Docs indicate default REST session timeout is 60 minutes.  I see a 30 minute session timeout for REST console and for Bolt transactions using the neo4j-python driver.  I suspect this has to do with a Shiro authentication session timeout, since it is shorter than the default transaction timeout.

From Deployment Appendix A
Timeout for idle transactions in the REST endpoint.
dbms.transaction_timeout is a duration (valid units are ms, s, m)
Default value 60000 ms  --> 60 minutes
# 

localhost:7474

Session with id [fb3e726e-e9ea-449f-b8a9-5ba721a2d5bf] has expired. Last access time: 9/7/16 2:47 AM.  Current time: 9/7/16 3:17 AM.  Session timeout is set to 1800 seconds (30 minutes)
# 

Apoc procedure, localhost:7474

CALL apoc.warmup.run()

Failed to invoke procedure `apoc.warmup.run`: Caused by: org.apache.shiro.session.ExpiredSessionException: Session with id [1d93f4ae-1b4f-403b-8534-4818462dbe19] has expired. Last access time: 9/7/16 2:43 AM.  Current time: 9/7/16 3:13 AM.  Session timeout is set to 1800 seconds (30 minutes)
# 

Bolt driver for python:

2016-09-07 03:45:46.739+0000 ERROR Fatal, worker for session 'db8670bb-2f83-4b3a-ba11-3c1d4dc8396f' crashed. Please contact your support representative if you are unable to resolve this. The client is unauthorized due to authentication failu
re.
org.neo4j.bolt.v1.runtime.BoltConnectionFatality: The client is unauthorized due to authentication failure.
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:347)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.init(BoltStateMachine.java:117)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onInit$0(BoltMessageRouter.java:64)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:126)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:87)
        at java.lang.Thread.run(Thread.java:745)
# 

Debug:

2016-09-08 05:04:59.818+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: Session with id [34be60ab-47cf-48e6-9e0e-37bd445e57a0] has expired. Last access time: 9/8/16 4:34 AM.  Current time: 9/8/16 5:04 AM.  Session timeout is set to 1800 seconds (30 minutes), reference 13a63b23-bfa6-421d-bedb-468762c4e20f. Session with id [34be60ab-47cf-48e6-9e0e-37bd445e57a0] has expired. Last access time: 9/8/16 4:34 AM.  Current time: 9/8/16 5:04 AM.  Session timeout is set to 1800 seconds (30 minutes)
org.apache.shiro.session.ExpiredSessionException: Session with id [34be60ab-47cf-48e6-9e0e-37bd445e57a0] has expired. Last access time: 9/8/16 4:34 AM.  Current time: 9/8/16 5:04 AM.  Session timeout is set to 1800 seconds (30 minutes)
    at org.apache.shiro.session.mgt.SimpleSession.validate(SimpleSession.java:292)
    at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.doValidate(AbstractValidatingSessionManager.java:186)
    at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.validate(AbstractValidatingSessionManager.java:143)
    at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.doGetSession(AbstractValidatingSessionManager.java:120)
    at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupSession(AbstractNativeSessionManager.java:108)
    at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupRequiredSession(AbstractNativeSessionManager.java:112)
    at org.apache.shiro.session.mgt.AbstractNativeSessionManager.getAttribute(AbstractNativeSessionManager.java:209)
    at org.apache.shiro.session.mgt.DelegatingSession.getAttribute(DelegatingSession.java:141)
    at org.apache.shiro.session.ProxiedSession.getAttribute(ProxiedSession.java:121)
    at org.apache.shiro.subject.support.DelegatingSubject.getRunAsPrincipalsStack(DelegatingSubject.java:469)
    at org.apache.shiro.subject.support.DelegatingSubject.getPrincipals(DelegatingSubject.java:153)
    at org.apache.shiro.subject.support.DelegatingSubject.hasPrincipals(DelegatingSubject.java:126)
    at org.apache.shiro.subject.support.DelegatingSubject.isPermitted(DelegatingSubject.java:158)
    at org.neo4j.server.security.enterprise.auth.EnterpriseAuthSubject.allowsReads(EnterpriseAuthSubject.java:112)
# 

Shiro Documentation
http://shiro.apache.org/session-management.html#SessionManagement-SessionTimeout

```
Session Timeout

By default, Shiro's SessionManager implementations default to a 30 minute session timeout. That is, if any Session created remains idle (unused, where its lastAccessedTime isn't updated) for 30 minutes or more, the Session is considered expired and will not be allowed to be used anymore.

You can set the default SessionManager implementation's globalSessionTimeout property to define the default timeout value for all sessions. For example, if you wanted the timeout to be an hour instead of 30 minutes:

Setting the Default Session Timeout in shiro.ini
[main]
...
#3,600,000 milliseconds = 1 hour
securityManager.sessionManager.globalSessionTimeout = 360000
```
# 

**_Steps to reproduce**_
1. Find a large graph
2. Run a query that takes excess of 30 minutes to complete
3. Query can be executed through console or python Bolt driver

**_Expected behavior:**_
Setting session timeout in neo4j.conf should be inherited by Shiro.  Long running queries should be updating Shiro lastAccessedTime to prevent timeout.  Should function the same for Bolt and REST.  Sessions with queries returning results and within the neo4j.conf session timeout should not be interrupted by Shiro.  If Shiro can't inherit the neo4j.conf, then expose shiro.ini so users can configure the timeout directly.

Thanks Michael

**Comment by henriknyman** [comment]
Hi @qosmy-michael , thanks for the detailed report! This issue should be fixed by https://github.com/neo4j/neo4j/pull/7830, which turns off the Shiro sessions all together.

**Comment by graphadvantage** [comment]
Thanks Henrik - do you think this will be avail in M09?

**Comment by spacecowboy** [comment]
Closing since @henriknyman says it's fixed
