### ISSUE TITLE
"Cannot inherit from final class" error with multiple plugins

### ISSUE THREAD

**Issue by ahmetkizilay** [neo4j/neo4j#8142]
Hello,

I am trying to run two plugins at the same time however I get the following `Cannot inherit from final class` error on startup and neo4j fails to startup.

```
2016-10-10 14:37:27.911+0000 INFO  Starting...
2016-10-10 14:37:28.403+0000 INFO  Bolt enabled on localhost:7687.
2016-10-10 14:37:31.305+0000 INFO  [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime disabled.
2016-10-10 14:37:34.974+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@349cc412' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@349cc412' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@349cc412' was successfully initialized, but failed to start. Please see attached cause exception.
    at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:215)
    at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
    at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:67)
    at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@349cc412' was successfully initialized, but failed to start. Please see attached cause exception.
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
    ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.CommunityFacadeFactory, /home/ahmetkizilay/WORK/TOOLS/neo4j-community-3.0.6/data/databases/graph.db
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:144)
    at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:40)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108)
    at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:55)
    at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
    ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@22067885' was successfully initialized, but failed to start. Please see attached cause exception.
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:140)
    ... 10 more
Caused by: java.lang.VerifyError: Cannot inherit from final class
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:132)
    at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:110)
    at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
    at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
    at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:85)
    at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:77)
    at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:125)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
    ... 12 more

```

Specifically I am trying to run GraphAware's timetree plugin along with ElasticSearch plugin. I have no problems with running them individually.
- Neo4j Community Edition 3.0.6
- [Graphaware's Timetree Plugin](https://github.com/graphaware/neo4j-timetree) with
  - graphaware-server-community-all-3.0.6.43.jar
  - graphaware-timetree-3.0.6.43.25.jar
- [ElasticSearch plugin](https://github.com/neo4j-contrib/neo4j-elasticsearch) (branch 3.0)
  - jars created from source with `mvn clean install -DskipTests`
- java-1.8.0-openjdk-amd64
- Ubuntu 14.04

Related issues: graphaware/neo4j-timetree#62 neo4j-contrib/neo4j-elasticsearch#26
Thanks a lot.

**Comment by chrisvest** [comment]
The `neo4j-elasticsearch` is building against Neo4j 3.0.1, and you are using their binaries on Neo4j 3.0.6. So you have a version mismatch, and I strongly suspect that that's the culprit of your VerifyError.
Try building `neo4j-elasticsearch` against Neo4j 3.0.6 to see if it's a compatibility problem between 3.0.1 and 3.0.6, or if `neo4j-elasticsearch` is relying on internal APIs.

**Comment by ahmetkizilay** [comment]
I update the neo4j.version to 3.0.6 and generate a new jar. However, I still get the same error.

**Comment by ahmetkizilay** [comment]
I investigated this problem a little more and realized the error is caused by duplicate guava jars in each plugin.

I added a debug log on this [line](https://github.com/neo4j/neo4j/blob/3.0/community/kernel/src/main/java/org/neo4j/kernel/impl/proc/ProcedureJarLoader.java#L128) and noticed the VerifyError occurs while loading `com.google.common.collect.RegularImmutableMultiset$NonTerminalEntry`.

Do you think a patch is possible here?

**Comment by sinswa28** [comment]
Hi,
Is there any fix available for this issue? If we want to keep both plugins working together how to go ahead with it? Please let us know if this issue has been fixed.

**Comment by craigtaverner** [comment]
This sounds like an issue with neo4j-elasticsearch dependencies clashing with graphware timetree dependencies. One option might be to look at the alternative https://github.com/graphaware/neo4j-to-elasticsearch. 

I will also move this issue to neo4j-elasticsearch github repo in case they can fix it from their side.

**Comment by chrisvest** [comment]
We do not control what plug-ins include in their jar files. To avoid this problem, the plug-ins should either coordinate their dependency versions, or shade with class-relocation: https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html
