### ISSUE TITLE
Unrecognized unit in neo4j.conf

### ISSUE THREAD

**Issue by endrec** [neo4j/neo4j#8149]
I have discovered (took me some time...) that trailing spaces in the neo4j.conf file can cause issues.

**Neo4j version:** 3.0.6
**Operating system:** Ubuntu 16.04
### Steps to reproduce
1. Edit your `neo4j.conf`, and add `dbms.transaction.timeout=1m` (including trailing spaces) in the last line.
2. Restart neo4j.
### Expected behavior

Neo4j starts without an error.
### Actual behavior

Neo4j fails to start with the following error:

```
Failed to start Neo4j on unknown address Unrecognized unit m            
java.lang.RuntimeException: Unrecognized unit m            
        at org.neo4j.helpers.TimeUtil.lambda$static$0(TimeUtil.java:67)
        at org.neo4j.kernel.configuration.Settings$11.apply(Settings.java:473)
        at org.neo4j.kernel.configuration.Settings$11.apply(Settings.java:469)
        at org.neo4j.kernel.configuration.Settings$DefaultSetting.apply(Settings.java:1042)
        at org.neo4j.kernel.configuration.Settings$DefaultSetting.apply(Settings.java:964)
        at org.neo4j.kernel.configuration.ConfigurationValidator.validate(ConfigurationValidator.java:49)
        at org.neo4j.kernel.configuration.Config.replaceSettings(Config.java:217)
        at org.neo4j.kernel.configuration.Config.<init>(Config.java:105)
        at org.neo4j.server.configuration.ConfigLoader.loadConfig(ConfigLoader.java:63)
        at org.neo4j.server.ServerBootstrapper.createConfig(ServerBootstrapper.java:166)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:76)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:67)
        at org.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:32)
```

**Comment by benbc** [comment]
@endrec I'm sorry that you had to struggle with that. It's a ludicrous bug that you shouldn't have had to deal with. We'll fix it as soon as we can.
