### ISSUE TITLE
neo4j-import enhancement request: mix unspecified and specified id groups

### ISSUE THREAD

**Issue by fpavageau** [neo4j/neo4j#8161]
Currently with `neo4j-import`, all or none of your ids should be grouped, otherwise you get the following error:

> Import error: Mixing specified and unspecified group belongings in a single import isn't supported

**Neo4j version:** 3.0.6
**Operating system:** MacOS
## Steps to reproduce
1. Create CSV files for the import
   - `a.csv`:
   
   ```
   :ID
   abc
   ```
   - `b.csv`:
   
   ```
   :ID(B-ID)
   def
   ```
2. Try to import:

```
$ /path/to/neo4j/bin/neo4j-import --into graph.db --id-type string --nodes:A a.csv --nodes:B b.csv --stacktrace true
Neo4j version: 3.0.6
Importing the contents of these files into graph.db:
Nodes:
  :A
  /tmp/a.csv

  :B
  /tmp/b.csv

Available resources:
  Free machine memory: 226,86 MB
  Max heap memory : 3,56 GB
  Processors: 8

Nodes
Import error: Mixing specified and unspecified group belongings in a single import isn't supported
Caused by:Mixing specified and unspecified group belongings in a single import isn't supported
java.lang.IllegalStateException: Mixing specified and unspecified group belongings in a single import isn't supported
    at org.neo4j.unsafe.impl.batchimport.input.Groups.getOrCreate(Groups.java:52)
    at org.neo4j.unsafe.impl.batchimport.input.csv.InputNodeDeserialization.initialize(InputNodeDeserialization.java:60)
    at org.neo4j.unsafe.impl.batchimport.input.csv.InputEntityDeserializer.initialize(InputEntityDeserializer.java:69)
    at org.neo4j.unsafe.impl.batchimport.input.csv.ParallelInputEntityDeserializer.lambda$new$0(ParallelInputEntityDeserializer.java:103)
    at org.neo4j.unsafe.impl.batchimport.staging.TicketedProcessing.lambda$submit$0(TicketedProcessing.java:122)
    at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:243)
```
## Workaround

Obviously, this can be avoided by specifying the default group explicitly: anywhere an unspecified group is found (standalone `:ID`), just replace it with `:ID(Default-ID)`.
## Enhancement

Is there actually a technical limitation? A quick overview of the code of the [`Group`](https://github.com/neo4j/neo4j/blob/3.0/community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/input/Group.java) and [`Groups`](https://github.com/neo4j/neo4j/blob/3.0/community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/input/Groups.java) classes doesn't seem to suggest so, as the [`GLOBAL` group](https://github.com/neo4j/neo4j/blob/3.0/community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/input/Group.java#L91) is created exactly the same way as any [explicit one](https://github.com/neo4j/neo4j/blob/3.0/community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/input/Groups.java#L65).

It's not a big deal, but I think it would reduce the friction when using `neo4j-import`.

**Comment by tinwelint** [comment]
This is fixed in 3.4 and forwards.
