### ISSUE TITLE
java code is not updating the existing neo4j db folder which is created first time by running th same code

### ISSUE THREAD

**Issue by jiwitesh** [neo4j/neo4j#8244]
its working fine when i just delete the db folder .It creates a new db folder

my exception log is 

```
Exception in thread "main" java.lang.RuntimeException: Error starting org.neo4j.kernel.EmbeddedGraphDatabase, C:\Users\Bipil\Desktop\innoneuron7oct16\innoneuron\Transform\Feature1_Automatic_Tagging\Feature1_Automatic_Tagging\databases\demo.db
    at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:366)
    at org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:59)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:91)
    at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:181)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(GraphDatabaseFactory.java:71)
    at feature3.AutomatedGraph.startDb(AutomatedGraph.java:91)
    at feature3.AutomatedGraph.main(AutomatedGraph.java:51)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.transaction.XaDataSourceManager@191f517' was successfully initialized, but failed to start. Please see attached cause exception.
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:513)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115)
    at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:343)
    ... 6 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.nioneo.xa.NeoStoreXaDataSource@4aa2f2' was successfully initialized, but failed to start. Please see attached cause exception.
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:513)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:115)
    at org.neo4j.kernel.impl.transaction.XaDataSourceManager.start(XaDataSourceManager.java:164)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507)
    ... 8 more
Caused by: org.neo4j.kernel.impl.storemigration.StoreUpgrader$UpgradingStoreVersionNotFoundException: 'neostore.nodestore.db' does not contain a store version, please ensure that the original database was shut down in a clean state.
    at org.neo4j.kernel.impl.storemigration.UpgradableDatabase.checkUpgradeable(UpgradableDatabase.java:78)
    at org.neo4j.kernel.impl.storemigration.StoreMigrator.needsMigration(StoreMigrator.java:135)
    at org.neo4j.kernel.impl.storemigration.StoreUpgrader.getParticipantsEagerToMigrate(StoreUpgrader.java:268)
    at org.neo4j.kernel.impl.storemigration.StoreUpgrader.migrateIfNeeded(StoreUpgrader.java:143)
    at org.neo4j.kernel.impl.nioneo.xa.NeoStoreXaDataSource.start(NeoStoreXaDataSource.java:344)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:507)
    ... 11 more
```

**Comment by chrisvest** [comment]
What version of Neo4j are you using and what are you doing to it?

The exception is telling you this:
`please ensure that the original database was shut down in a clean state.`
Are you ensuring that?

**Comment by vinrana** [comment]
I am facing the same problem. I am shutting down database properly and .DB file can be updated until it is not opened in Neo4j. But once it is opened in Neo4j after that I am unable to update .DB file. I am using Neo4j 3.0.4 version. @chrisvest

**Comment by jiwitesh** [comment]
@chrisvest I am using Neo4j 3.0.4 version.I am shutting down database properly.

**Comment by jiwitesh** [comment]
@chrisvest @vinrana  thanks for your response. I got the solution actually there is version conflict. I am using 2.1.5 jar files in my java code and opening the demo.db in 3.0.4 neo4j thats why its not updating the db folder after it opens with neo4j . Thanks again

**Comment by Divyajose93** [comment]
Hi,
Could you please tell me how you fixed the issue?

**Comment by jiwitesh** [comment]
@Divyajose93
Hey there
Like I mentioned in my last post I solved it by replacing the compatible jar files respective to the neo4j database version.
