### ISSUE TITLE
org.neo4j.ogm.exception.CypherException: Error executing Cypher "Neo.ClientError.Statement.EntityNotFound"

### ISSUE THREAD

**Issue by weikeqin** [neo4j/neo4j#8281]
I use spring-data-neo4j 4.1.2.RELEASE     neo4j 3.1.0-M03    ogm 2.0.3

i meet this problem, who can help me

```
org.neo4j.ogm.exception.CypherException: Error executing Cypher "Neo.ClientError.Statement.EntityNotFound"; Code: Neo.ClientError.Statement.EntityNotFound; Description: Relationship with id 3050
    at org.neo4j.ogm.drivers.http.response.AbstractHttpResponse.initialise(AbstractHttpResponse.java:83) ~[neo4j-ogm-http-driver-2.0.3.jar:na]
    at org.neo4j.ogm.drivers.http.response.AbstractHttpResponse.<init>(AbstractHttpResponse.java:74) ~[neo4j-ogm-http-driver-2.0.3.jar:na]
    at org.neo4j.ogm.drivers.http.response.RowModelResponse.<init>(RowModelResponse.java:31) ~[neo4j-ogm-http-driver-2.0.3.jar:na]
    at org.neo4j.ogm.drivers.http.request.HttpRequest.execute(HttpRequest.java:123) ~[neo4j-ogm-http-driver-2.0.3.jar:na]
    at org.neo4j.ogm.session.request.RequestExecutor.executeSave(RequestExecutor.java:116) ~[neo4j-ogm-core-2.0.3.jar:na]
    at org.neo4j.ogm.session.delegates.SaveDelegate.save(SaveDelegate.java:70) ~[neo4j-ogm-core-2.0.3.jar:na]
    at org.neo4j.ogm.session.delegates.SaveDelegate.save(SaveDelegate.java:43) ~[neo4j-ogm-core-2.0.3.jar:na]
    at org.neo4j.ogm.session.Neo4jSession.save(Neo4jSession.java:364) ~[neo4j-ogm-core-2.0.3.jar:na]
    at org.springframework.data.neo4j.template.Neo4jTemplate.save(Neo4jTemplate.java:203) ~[spring-data-neo4j-4.1.2.RELEASE.jar:na]
    at sun.reflect.GeneratedMethodAccessor121.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_80]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_80]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) ~[spring-tx-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at com.sun.proxy.$Proxy67.save(Unknown Source) ~[na:na]
    at org.springframework.data.neo4j.repository.GraphRepositoryImpl.save(GraphRepositoryImpl.java:48) ~[spring-data-neo4j-4.1.2.RELEASE.jar:na]
    at sun.reflect.GeneratedMethodAccessor120.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_80]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_80]
    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:503) ~[spring-data-commons-1.12.2.RELEASE.jar:na]
    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:488) ~[spring-data-commons-1.12.2.RELEASE.jar:na]
    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:460) ~[spring-data-commons-1.12.2.RELEASE.jar:na]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) ~[spring-tx-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) ~[spring-tx-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at com.sun.proxy.$Proxy80.save(Unknown Source) ~[na:na]
```

**Comment by MohammedNajim** [comment]
q

**Comment by spacecowboy** [comment]
You need to add details on what you are actually doing so someone can understand the problem

Please follow the issue template: https://github.com/neo4j/neo4j/blob/3.1/ISSUE_TEMPLATE.md

**Comment by kaleeswaran393** [comment]
I am facing the same issue. is it resolved ?

**Comment by spacecowboy** [comment]
Closing as reporter has not added required information to diagnose.

If this is still a problem, consider reporting it to https://github.com/neo4j/neo4j-ogm since the stack trace reports an error thrown in the ogm library and not in neo4j.
