### ISSUE TITLE
Can't run execute cypher querys; caused by Scala

### ISSUE THREAD

**Issue by aruscher** [neo4j/neo4j#8414]
Problem: i cant execute any kind of cypher querys. But creation of nodes works using createNode()

Code:
```java
public void dbAction() {
    File dbFile = new File(dbPath);
    this.db = new GraphDatabaseFactory().newEmbeddedDatabaseBuilder(dbFile).newGraphDatabase();
    registerShutdownHook(this.db);
    try (Transaction tx = this.db.beginTx()) {
        Map<String, Object> params = new HashMap<>();
        db.execute("MATCH (n) RETURN n",params);
        tx.success();
    }
}
```
Error Stacktrace:
```java
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
	at org.neo4j.cypher.internal.compiler.v3_0.helpers.RuntimeScalaValueConverter.asShallowScalaMap(RuntimeScalaValueConverter.scala:40)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:108)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:65)
	at org.neo4j.kernel.impl.factory.ClassicCoreSPI.executeQuery(ClassicCoreSPI.java:77)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:357)
	at gsmvisualizer.graph.util.Neo4JGraphExport.dbAction(Neo4JGraphExport.java:53)
	at gsmvisualizer.Main.main(Main.java:30)
```
Info:
Java: OpenJDK 1.8.0_111
Maven: 3.0.5
Neo4j: 3.0.1 (and tried other versions from 3.0.0 to 3.1.0-M13-beta3)

**Comment by chrisvest** [comment]
Check `mvn dependency:tree` and make sure that all dependencies in the `org.neo4j` group has the same package version.

**Comment by aruscher** [comment]
@chrisvest: seems normal to me
```
[INFO] gsmvisualizer:gsm-visualizer:jar:1.0-SNAPSHOT
[INFO] +- org.graphstream:gs-ui:jar:1.3:compile
[INFO] |  +- junit:junit:jar:4.12:compile
[INFO] |  |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |  \- org.scala-lang:scala-library:jar:2.10.1:compile
[INFO] +- org.graphstream:gs-core:jar:1.3:compile
[INFO] |  +- org.graphstream:pherd:jar:1.0:compile
[INFO] |  \- org.graphstream:mbox2:jar:1.0:compile
[INFO] +- org.graphstream:gs-algo:jar:1.3:compile
[INFO] |  +- org.apache.commons:commons-math:jar:2.1:compile
[INFO] |  +- org.apache.commons:commons-math3:jar:3.4.1:compile
[INFO] |  \- org.jfree:jfreechart:jar:1.0.14:compile
[INFO] |     +- org.jfree:jcommon:jar:1.0.17:compile
[INFO] |     +- xml-apis:xml-apis:jar:1.3.04:compile
[INFO] |     \- com.lowagie:itext:jar:2.1.5:compile
[INFO] |        +- bouncycastle:bcmail-jdk14:jar:138:compile
[INFO] |        \- bouncycastle:bcprov-jdk14:jar:138:compile
[INFO] +- com.google.code.gson:gson:jar:2.8.0:compile
[INFO] +- commons-io:commons-io:jar:2.5:compile
[INFO] +- org.apache.commons:commons-jexl3:jar:3.0:compile
[INFO] |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] +- org.javatuples:javatuples:jar:1.2:compile
[INFO] +- org.neo4j:neo4j:jar:3.0.1:compile
[INFO] |  +- org.neo4j:neo4j-kernel:jar:3.0.1:compile
[INFO] |  |  +- org.neo4j:neo4j-graphdb-api:jar:3.0.1:compile
[INFO] |  |  |  \- org.neo4j:neo4j-resource:jar:3.0.1:compile
[INFO] |  |  +- org.neo4j:neo4j-common:jar:3.0.1:compile
[INFO] |  |  +- org.neo4j:neo4j-collections:jar:3.0.1:compile
[INFO] |  |  +- org.neo4j:neo4j-primitive-collections:jar:3.0.1:compile
[INFO] |  |  |  \- org.neo4j:neo4j-unsafe:jar:3.0.1:compile
[INFO] |  |  +- org.neo4j:neo4j-io:jar:3.0.1:compile
[INFO] |  |  |  \- org.apache.commons:commons-lang3:jar:3.3.2:compile
[INFO] |  |  +- org.neo4j:neo4j-csv:jar:3.0.1:compile
[INFO] |  |  +- org.neo4j:neo4j-logging:jar:3.0.1:compile
[INFO] |  |  +- org.neo4j:neo4j-security:jar:3.0.1:compile
[INFO] |  |  \- org.neo4j:neo4j-lucene-upgrade:jar:3.0.1:compile
[INFO] |  |     \- org.apache.lucene:lucene-backward-codecs:jar:5.5.0:compile
[INFO] |  +- org.neo4j:neo4j-lucene-index:jar:3.0.1:compile
[INFO] |  |  +- org.apache.lucene:lucene-analyzers-common:jar:5.5.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-core:jar:5.5.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-queryparser:jar:5.5.0:compile
[INFO] |  |  \- org.apache.lucene:lucene-codecs:jar:5.5.0:compile
[INFO] |  +- org.neo4j:neo4j-graph-algo:jar:3.0.1:compile
[INFO] |  +- org.neo4j:neo4j-udc:jar:3.0.1:compile
[INFO] |  +- org.neo4j:neo4j-graph-matching:jar:3.0.1:compile
[INFO] |  +- org.neo4j:neo4j-cypher:jar:3.0.1:compile
[INFO] |  |  +- org.scala-lang:scala-reflect:jar:2.11.8:compile
[INFO] |  |  +- org.neo4j:neo4j-codegen:jar:3.0.1:compile
[INFO] |  |  |  \- org.ow2.asm:asm:jar:5.0.2:compile
[INFO] |  |  +- org.neo4j:neo4j-cypher-compiler-2.3:jar:2.3.3:compile
[INFO] |  |  |  \- org.neo4j:neo4j-cypher-frontend-2.3:jar:2.3.3:compile
[INFO] |  |  +- org.neo4j:neo4j-cypher-compiler-3.0:jar:3.0.1:compile
[INFO] |  |  |  \- org.neo4j:neo4j-cypher-frontend-3.0:jar:3.0.1:compile
[INFO] |  |  +- org.parboiled:parboiled-scala_2.11:jar:1.1.7:compile
[INFO] |  |  |  \- org.parboiled:parboiled-core:jar:1.1.7:compile
[INFO] |  |  +- net.sf.opencsv:opencsv:jar:2.3:compile
[INFO] |  |  \- com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar:1.4.2:compile
[INFO] |  +- org.neo4j:neo4j-jmx:jar:3.0.1:compile
[INFO] |  \- org.neo4j:neo4j-consistency-check:jar:3.0.1:compile
[INFO] \- org.neo4j.driver:neo4j-java-driver:jar:1.0.6:compile
```

**Comment by aruscher** [comment]
i compared  the dependency tree with one of my coworkers and found the following:
```
//mine
[INFO] |  +- org.neo4j:neo4j-cypher:jar:3.0.1:compile
[INFO] |  |  +- org.scala-lang:scala-reflect:jar:2.11.8:compile
//coworker
[INFO] |  +- org.neo4j:neo4j-cypher:jar:3.0.1:compile
[INFO] |  |  +- org.scala-lang:scala-library:jar:2.11.8:compile
[INFO] |  |  +- org.scala-lang:scala-reflect:jar:2.11.8:compile
```
so it seems the missing scala-library is causing the problem

**Comment by jexp** [comment]
It's because this one pulls in an older version of scala:

```
[INFO] +- org.graphstream:gs-ui:jar:1.3:compile
[INFO] |  \- org.scala-lang:scala-library:jar:2.10.1:compile
```

you would have to exclude `org.scala-lang:scala-library` from `org.graphstream:gs-ui`
