### ISSUE TITLE
Neo4j-import error

### ISSUE THREAD

**Issue by Ming-Lei** [neo4j/neo4j#8419]
## Question

there are three nodes.csv(3.5G).
follow the docs of import tool, I started importing data to neo4j(3.0.7).
It's normal to start. but when the node reaches 2.24 GB, an error has occurred.

[>:2|PROPER|NODE:2.24 GB----------------|*LABEL SCAN--------------------------|v:9.24 MB/s----] 299M 
Done in 28m 39s 72ms 
Import error: null 
Caused by:null 
java.lang.NullPointerException...

the import task is not completed yet, but it has already dropped out.
the next step is prepare node index, but it occurred an error.
what caused the problem and how to fix it.

each nodes.csv is correct, because the single nodes not found the import error

the nodes like this
company.csv
companyId:ID(Company-ID)
1
2
3

geti.csv
getiId:ID(Geti-ID)
100
101
102

person.csv
personId:ID(Person-ID)
1000
1001
1002
1003

all files are only ID, no other fields.
all configurations are default.

**Comment by jexp** [comment]
What is your exact command line and the full output?

Can you re-run it with `--stacktrace true `

I'm not sure how well it handles dashes in the groups, could you try to remove them?

**Comment by Ming-Lei** [comment]
@jexp hi 
the command line is
./neo4j/bin/neo4j-import --into company --nodes:company company.csv --nodes:person person.csv --nodes:geti geti.csv --stacktrace true

there is no problem with the command and dashes  because a small number of tests are successful.

the full outpup is
[>:|PRO|NODE:2.22 GB---------|*LABEL SCAN-------------------------------------|v:8.84 MB/s----][>:|PROP|NODE:2.23 GB-------------|*LABEL SCAN----------------------------|v:8.84 MB/s--------][>:|PROP|NODE:2.23 GB----------|*LABEL SCAN-------------------------------|v:8.83 MB/s--------][>:1.|PROP|NODE:2.23 GB----|*LABEL SCAN---------------------------------------|v:8.83 MB/s----][>:1|PROP|NODE:2.24 GB----|*LABEL SCAN-------------------------------------------|v:8.84 MB/s-] 299M
Done in 29m 57s 445ms
Import error: null
Caused by:null
java.lang.NullPointerException
	at org.neo4j.unsafe.impl.batchimport.cache.NodeRelationshipCache.close(NodeRelationshipCache.java:541)
	at org.neo4j.unsafe.impl.batchimport.ParallelBatchImporter.doImport(ParallelBatchImporter.java:224)
	at org.neo4j.tooling.ImportTool.main(ImportTool.java:414)
	at org.neo4j.tooling.ImportTool.main(ImportTool.java:303)


the debug log is
2016-11-23 00:35:54.931+0000 INFO  [o.n.u.i.b.ParallelBatchImporter] Import starting
2016-11-23 00:35:56.328+0000 WARN  [o.n.k.i.s.MetaDataStore] Missing counts store, rebuilding it.
2016-11-23 01:06:15.573+0000 INFO  [o.n.k.i.s.c.CountsTracker] About to rotate counts store at transaction 1 to [company/neostore.counts.db.b], from [company/neostore.counts.db.a].
2016-11-23 01:06:15.587+0000 INFO  [o.n.k.i.s.c.CountsTracker] Successfully rotated counts store at transaction 1 to [company/neostore.counts.db.b], from [company/neostore.counts.db.a].
2016-11-23 01:06:22.621+0000 ERROR [o.n.u.i.b.ParallelBatchImporter] Error during import
java.lang.NegativeArraySizeException
	at org.neo4j.unsafe.impl.batchimport.cache.HeapByteArray.<init>(HeapByteArray.java:40)
	at org.neo4j.unsafe.impl.batchimport.cache.NumberArrayFactory$1.newByteArray(NumberArrayFactory.java:158)
	at org.neo4j.unsafe.impl.batchimport.cache.NumberArrayFactory$Auto.newByteArray(NumberArrayFactory.java:256)
	at org.neo4j.unsafe.impl.batchimport.cache.NumberArrayFactory.newByteArray(NumberArrayFactory.java:96)
	at org.neo4j.unsafe.impl.batchimport.cache.NodeRelationshipCache.setHighNodeId(NodeRelationshipCache.java:139)
	at org.neo4j.unsafe.impl.batchimport.NodeStage.close(NodeStage.java:96)
	at org.neo4j.unsafe.impl.batchimport.staging.ExecutionSupervisors.superviseExecution(ExecutionSupervisors.java:86)
	at org.neo4j.unsafe.impl.batchimport.ParallelBatchImporter.executeStages(ParallelBatchImporter.java:324)
	at org.neo4j.unsafe.impl.batchimport.ParallelBatchImporter.doImport(ParallelBatchImporter.java:162)
	at org.neo4j.tooling.ImportTool.main(ImportTool.java:414)
	at org.neo4j.tooling.ImportTool.main(ImportTool.java:303)

run with  --stacktrace true did not print more information.

**Comment by tinwelint** [comment]
This has been fixed in 3.4 where this piece of memory isn't allocated on the heap at all.
