### ISSUE TITLE
Performance degrades when using multiple synchronous write statements

### ISSUE THREAD

**Issue by inadler** [neo4j/neo4j#8497]
Sending 1000 synchronous write statements - "create (n:Person {id:<id>})" - takes several seconds.
Just to be clear, sending the statements takes several msec, but consuming them takes several seconds (~3).

Even more, while adding more running threads (each thread run 1000 synchronous statement), the results degrades.

We got the same result when using both the Bolt driver and an HTTP client.  
 
Taking a look at the server threads dump, there are many threads waiting to get released from lock and some blocked. 
Bellow is n example of what we have seen:

```
qtp91329346-247152" #247152 prio=5 os_prio=0 tid=0x00007f89b8001800 nid=0x24dd runnable [0x00007f8990dfa000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000a7574320> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireNanos(AbstractQueuedSynchronizer.java:934)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireNanos(AbstractQueuedSynchronizer.java:1247)
        at java.util.concurrent.locks.ReentrantLock.tryLock(ReentrantLock.java:442)
        at org.neo4j.concurrent.WorkSync.apply(WorkSync.java:86)
        at org.neo4j.kernel.impl.transaction.command.IndexBatchTransactionApplier.close(IndexBatchTransactionApplier.java:105)
        at org.neo4j.kernel.impl.api.BatchTransactionApplierFacade.close(BatchTransactionApplierFacade.java:70)
        at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:348)
        at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:78)
        at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:51)
        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:585)
        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.close(KernelTransactionImplementation.java:463)
        at org.neo4j.server.rest.transactional.TransitionalTxManagementKernelTransaction.commit(TransitionalTxManagementKernelTransaction.java:94)
        at org.neo4j.server.rest.transactional.TransactionHandle.closeContextAndCollectErrors(TransactionHandle.java:245)
        at org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:153)
        at org.neo4j.server.rest.web.TransactionalService.lambda$executeStatementsAndCommit$1(TransactionalService.java:211)
        at org.neo4j.server.rest.web.TransactionalService$$Lambda$231/167727069.write(Unknown Source)
        at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
        at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
        at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
```

Can it be the cause?
Or is it a known issue you have when writing "bulk" of statements instead of using transactions?

I am using a single node of Neo4j v3.0.7 running on a Linux OS with a 64 cores machine and 128 GB of RAM so this is not the problem..
I tried both the JAVA Bolt driver and my own HTTP client.

**Comment by jexp** [comment]
You have a constraint on `:Person(id)`, correct?

**Comment by inadler** [comment]
Not any more. 
I deleted the schema and went back to the basics: A simple create node

**Comment by inadler** [comment]
I updated the thread stack trace to one which is more relevant.
Also, we tried the 3.1.0 RC version and saw the same problem (but the thread stack trace look different)

**Comment by spacecowboy** [comment]
In the synchronous case, performance should be solved by using a transaction.
The multi-threaded case is a bug.

**Comment by inadler** [comment]
But what if the nature of our business doesn't allow us to bulk nodes in a single transactions?
I don't want a single failed create/merge node/relation operation to cause the whole chunk to fail

**Comment by chrisvest** [comment]
Hi @inadler. How many threads are we talking about? I understand that each is running 1.000 queries in sequence; these are your client-side threads, right? Also, each of these 1.000 queries are executed in a separate transaction, correct? When you say performance is degrading, is that for the individual thread, or the system as a whole?

On the server side, Bolt and HTTP use different networking stacks, and different thread pools. For HTTP, you can limit the number of worker threads with the `dbms.threads.worker_count` setting. I don't think we yet have a similar setting for Bolt. You can try setting it to the same as, or 2x of, how many logical CPU cores your machine has. This _may_ reduce contention – you'll have to experiment and see if it helps your workload.

I can explain the particular stack trace you posted:

```
        at org.neo4j.concurrent.WorkSync.apply(WorkSync.java:86)
        at org.neo4j.kernel.impl.transaction.command.IndexBatchTransactionApplier.close(IndexBatchTransactionApplier.java:105)
        at org.neo4j.kernel.impl.api.BatchTransactionApplierFacade.close(BatchTransactionApplierFacade.java:70)
```

We currently use Lucene as our index implementation. Transactional writes to Lucene are slow, and for consistency we only allow one thread to write to Lucene at any one time. We effectively guard Lucene behind a lock to ensure this. However, to improve index write throughput we use a technique called _Flat Combining_ (implemented by the `WorkSync` above) where index writes that cannot be applied immediately (because the lock is taken) is piled up, and then applied as a single batch (which is much faster than writing each entry individually) as soon as the lock gets released. When the lock guarding the index gets released, the waiting threads compete to grab it, and the winner applies the index writes for all the other threads.

So seeing threads waiting in the `WorkSync` is normal, when you have a concurrent work load with many index writes.

In 3.1, the `WorkSync` implementation got faster by using a better a lock implementation, so that would change the stack trace a bit. And probably also improve the performance of your work load.

Even if you don't have an index on `:Person(id)` per se, labels themselves are still indexed using a special index (so we can scan for all nodes with specific labels), so creating nodes like this still involves index writes. If you create nodes without any labels, you'll see your write throughput go up considerably, but not using labels is probably too inconvenient to be practical. You'll be delighted to know that the special label index is something that we are working on improving in 3.2.

Until then, I suspect that you are limited by the write throughput of the indexes, and your only options are to tune the database and the workload. If you observe any _other_ locks being sources of contention, then we can take a look at those separately.
