### ISSUE TITLE
"ERROR Failed to generate JSON output" in Neo4j 3.1 that kills Browser

### ISSUE THREAD

**Issue by dhimmel** [neo4j/neo4j#8580]
See more details and the steps to reproduce at https://github.com/dhimmel/hetionet/issues/4#issue-198788442. Here is the error message:

```
2017-01-04 19:07:01.093+0000 ERROR Failed to generate JSON output.
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:364)
	at org.eclipse.jetty.io.SelectChannelEndPoint.onSelected(SelectChannelEndPoint.java:111)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processKey(SelectorManager.java:636)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:607)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:545)
	at org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170)
	... 10 more
```

**Comment by spacecowboy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GH#8580 "ERROR Failed to generate JSON output" in Neo4j 3.1 that kills Browser](https://trello.com/c/egWCz0qk/1086-gh-8580-error-failed-to-generate-json-output-in-neo4j-3-1-that-kills-browser)

**Comment by dhimmel** [comment]
For convenience, you can see the bug in action at https://neo4j.het.io/browser/ when you run `MATCH p=()-[*..3]->() RETURN p`. However, I update the Neo4j version at neo4j.het.io frequently, so of course the versioned Docker method above is best for longevity.

**Comment by dhimmel** [comment]
Note, I'm not getting this error anymore on https://neo4j.het.io/browser/ which is now running 3.1.1, so @spacecowboy perhaps this was fixed?

**Comment by spacecowboy** [comment]
@dhimmel awesome. but you can still reliably reproduce on 3.1.0? If so sounds like it's fixed yeah :)

**Comment by dhimmel** [comment]
Hey @spacecowboy, not fixed :disappointed:. I reran the browser query (`MATCH p=()-[*..3]->() RETURN p`) on http://localhost:7474/browser/ for both the 3.1.0 and 3.1.1 dockers. Both got the "Aw snap" in Chrome.

With `dhimmel/hetionet:hetionet-v1.0_neo4j-3.1.0`, I got the following error:

```
2017-02-04 23:57:35.085+0000 ERROR Failed to generate JSON output.
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:364)
	at org.eclipse.jetty.io.SelectChannelEndPoint.onSelected(SelectChannelEndPoint.java:111)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processKey(SelectorManager.java:636)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:607)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:545)
	at org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170)
	... 10 more
2017-02-04 23:57:35.087+0000 ERROR Unable to reply to request, because the client has closed the connection (Broken pipe).
2017-02-04 23:57:35.087+0000 ERROR Unable to reply to request, because the client has closed the connection (Broken pipe).
```

With `dhimmel/hetionet:hetionet-v1.0_neo4j-3.1.1`, I got the following error:

```
2017-02-05 00:02:05.482+0000 ERROR Failed to generate JSON output.
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:684)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:480)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:768)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:801)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:142)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:135)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:350)
	at com.sun.jersey.spi.container.servlet.WebComponent$Writer.write(WebComponent.java:300)
	at com.sun.jersey.spi.container.ContainerResponse$CommittingOutputStream.write(ContainerResponse.java:135)
	at org.codehaus.jackson.impl.Utf8Generator._flushBuffer(Utf8Generator.java:1754)
	at org.codehaus.jackson.impl.Utf8Generator.flush(Utf8Generator.java:1088)
	at org.codehaus.jackson.map.ObjectMapper.writeValue(ObjectMapper.java:1615)
	at org.neo4j.server.rest.transactional.Neo4jJsonCodec.writeValue(Neo4jJsonCodec.java:102)
	at org.codehaus.jackson.impl.JsonGeneratorBase.writeObject(JsonGeneratorBase.java:314)
	at org.codehaus.jackson.JsonGenerator.writeObjectField(JsonGenerator.java:1090)
	at org.neo4j.server.rest.transactional.GraphExtractionWriter.writeProperties(GraphExtractionWriter.java:151)
	at org.neo4j.server.rest.transactional.GraphExtractionWriter.writeRelationships(GraphExtractionWriter.java:129)
	at org.neo4j.server.rest.transactional.GraphExtractionWriter.write(GraphExtractionWriter.java:50)
	at org.neo4j.server.rest.transactional.AggregatingWriter.write(AggregatingWriter.java:43)
	at org.neo4j.server.rest.transactional.ExecutionResultSerializer.lambda$writeRows$0(ExecutionResultSerializer.java:442)
	at org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor3_1$$anon$7.visit(CompatibilityFor3_1.scala:405)
	at org.neo4j.cypher.internal.compiler.v3_1.helpers.RuntimeJavaValueConverter$feedIteratorToVisitable.accept(RuntimeJavaValueConverter.scala:55)
	at org.neo4j.cypher.internal.compiler.v3_1.PipeExecutionResult.accept(PipeExecutionResult.scala:109)
	at org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor3_1.accept(CompatibilityFor3_1.scala:402)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$1.apply$mcV$sp(ClosingExecutionResult.scala:169)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$1.apply(ClosingExecutionResult.scala:168)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$1.apply(ClosingExecutionResult.scala:168)
	at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor3_1$runSafely$.apply(CompatibilityFor3_1.scala:190)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.accept(ClosingExecutionResult.scala:168)
	at org.neo4j.cypher.internal.javacompat.ExecutionResult.accept(ExecutionResult.java:317)
	at org.neo4j.server.rest.transactional.ExecutionResultSerializer.writeRows(ExecutionResultSerializer.java:438)
	at org.neo4j.server.rest.transactional.ExecutionResultSerializer.statementResult(ExecutionResultSerializer.java:112)
	at org.neo4j.server.rest.transactional.TransactionHandle.executeStatements(TransactionHandle.java:324)
	at org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:157)
	at org.neo4j.server.rest.web.TransactionalService.lambda$executeStatementsAndCommit$1(TransactionalService.java:216)
	at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
	at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
	at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.neo4j.server.rest.dbms.AuthorizationDisabledFilter.doFilter(AuthorizationDisabledFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:172)
	... 72 more
2017-02-05 00:02:05.494+0000 ERROR Unable to reply to request, because the client has closed the connection (Broken pipe).
2017-02-05 00:02:05.494+0000 ERROR Unable to reply to request, because the client has closed the connection (Broken pipe).
```

On https://neo4j.het.io/browser/ with 3.1.1, I'm not getting the error -- the query runs indefinitely and oddly does not get killed by my `dbms.transaction.timeout=120s` [configuration](https://github.com/dhimmel/hetionet/blob/59c448fd912555f84b9822b4f49b431b696aea15/hetnet/neo4j/docker/files/neo4j.conf#L57) (likely unrelated?).

Hopefully, someone can decode these error messages better than I can (;

**Comment by spacecowboy** [comment]
OK thanks, we'll take a look

**Comment by technige** [comment]
@dhimmel Sorry for the delay in picking this up. Can you clarify whether this is still a problem with the latest versions of Neo4j and the driver?

**Comment by dhimmel** [comment]
Currently https://neo4j.het.io is running `neo4j:3.2.8-enterprise`. I just attempted the problematic query:

```
MATCH p=()-[*..3]->() RETURN p
```

I got the following response in the browser (which did not crash):

```
ServiceUnavailable
WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3
```

> Can you clarify whether this is still a problem with the latest versions of Neo4j and the driver?

I would say the issue is no longer present because the browser does not crash. Perhaps it is a separate issue that the error message is not displayed due to a "WebSocket connection failure"... not sure, haven't looked into it.

**Comment by technige** [comment]
Hi again @dhimmel. It's very likely that the problem you're seeing was fixed in a more recent version of the JS driver, which is used by the browser. From what I can see, you have browser version 3.1.2, which embeds the 1.4.1 JS driver. If it's possible to upgrade your server to the latest 3.2 patch release (3.2.13) then you'll receive the 1.6 driver instead. Alternatively, you can try accessing your server from the latest Neo4j Desktop release, which should contain the 1.7 driver.

**Comment by dhimmel** [comment]
> It's very likely that the problem you're seeing was fixed in a more recent version of the JS driver

@technige are you talking about the `WebSocket connection failure`?

I tested out upgrading to 3.2.13 locally and I no longer got the `WebSocket connection failure`. However, the query seemed to go on forever, which also is not the expected behavior. Need to investigate this more. Will update if I get around to this.

**Comment by zhenlineo** [comment]
Hi @dhimmel,

As your original problem raised in this issue is already solved and considering this issue has been for 3.1 which is a pretty old db version, I am closing this issue. Please be free to open a new one if you have any new problems with any newer versions of the database.
