### ISSUE TITLE
Import data error...

### ISSUE THREAD

**Issue by new94** [neo4j/neo4j#8677]
- Neo4j version: 3.1.1
- Operating system: (Ubuntu 14.04)

I'm trying import data from csv. (3 files. Vertexes and related):
..............
**Import error: Value 2570207036 is too big to be represented as int
Caused by:Value 2570207036 is too big to be represented as int
java.lang.ArithmeticException: Value 2570207036 is too big to be represented as int
	at org.neo4j.unsafe.impl.batchimport.Utils.safeCastLongToInt(Utils.java:36)
	at org.neo4j.unsafe.impl.batchimport.cache.NumberArrayFactory$1.newByteArray(NumberArrayFactory.java:157)
	at org.neo4j.unsafe.impl.batchimport.cache.NumberArrayFactory$Auto.newByteArray(NumberArrayFactory.java:255)
	at org.neo4j.unsafe.impl.batchimport.cache.NumberArrayFactory.newByteArray(NumberArrayFactory.java:95)
	at org.neo4j.unsafe.impl.batchimport.cache.NodeRelationshipCache.setHighNodeId(NodeRelationshipCache.java:140)
	at org.neo4j.unsafe.impl.batchimport.NodeStage.close(NodeStage.java:96)
	at org.neo4j.unsafe.impl.batchimport.staging.ExecutionSupervisors.superviseExecution(ExecutionSupervisors.java:86)
	at org.neo4j.unsafe.impl.batchimport.ParallelBatchImporter.executeStages(ParallelBatchImporter.java:325)
	at org.neo4j.unsafe.impl.batchimport.ParallelBatchImporter.doImport(ParallelBatchImporter.java:163)
	at org.neo4j.tooling.ImportTool.doImport(ImportTool.java:464)
	at org.neo4j.commandline.dbms.CsvImporter.doImport(CsvImporter.java:145)
	at org.neo4j.commandline.dbms.ImportCommand.execute(ImportCommand.java:210)
	at org.neo4j.commandline.admin.AdminTool.execute(AdminTool.java:92)
	at org.neo4j.commandline.admin.AdminTool.main(AdminTool.java:39)**

**Comment by spacecowboy** [comment]
@new94 could you paste the header and an example line from each of your CSV files?

@tinwelint I distinctly remember you and me fixing 32bit integers in the importer. Did we miss one?

**Comment by tinwelint** [comment]
The node cache in the import-tool is flexible w/ regards to where memory is allocated (on/off heap). First off-heap is tried (which just allocates memory off-heap). If that fails the on-heap allocator is tried, where it stores the cache in an array and java has a limit of Integer.MAX_VALUE for array length. It looks like this is what you're running into.

Strange thing is that it should then instead try to split up the memory, some on-heap and some off-heap. By the looks of the stack trace it didn't try to split it up, but simply failed on the second allocator candidate (on-heap). I'll look into this a bit more.

**Comment by tinwelint** [comment]
When trying locally doing this sort of allocation in a VM with limited memory I can see that this exception gets thrown too, but it immediately moves on and tries to chunk it up instead. Hard to tell why it doesn't do that for you.

**Comment by tinwelint** [comment]
@new94 Could you verify Neo4j version to be 3.1.1? It should even be in 3.1.0, although I see that there's yet no 3.0.x version with this fix in (I think).

**Comment by new94** [comment]
@tinwelint Sorry for my late answer... I have got version 3.1.0... I have updated version 3.1.1. Everything is ok! Thank you!

**Comment by spacecowboy** [comment]
Closing as already fixed then. :+1:
