### ISSUE TITLE
No check point found in any log file

### ISSUE THREAD

**Issue by mjr129** [neo4j/neo4j#8681]
- **Neo4j version:** 3.1.0
- **Operating system:** Ubuntu 16.04
- **API/Driver:** Command line
- **Steps to reproduce**

Encountered an error "file has been unmapped", looks similar to issue #7249.

Any attempts to run further queries resulted in the same error.

Stopped the server via `./neo4j stop` and restarted via `./neo4j start`.

Neo4j refuses to start with the error `No check point found in any log file from version 661 to 678`.

- **Expected behavior**

Recovery from error condition

- **Actual behavior**

Unhelpful error message

**Comment by MishaDemianenko** [comment]
Hi @mjr129 can you please share your transaction logs/debug log files with us?

**Comment by waldeyr** [comment]
I had this same problem.

> File has been unmapped: /home/work/neo4j-community-.1.1/data/databases/graph.db/neostore.counts.db.b

> Neo.DatabaseError.General.UnknownError

Log:

> 2017-03-29 14:49:33.249+0000 ERROR Client triggered an unexpected error [UnknownError]: File has been unmapped: /home/work/neo4j-community-3.1.1/data/databases/graph.db/neostore.counts.db.b. See debug.log for more details, reference fd4df91b-b8c3-41a7-ba41-9d0ef2bfad9d.

**Comment by pvanagtmaal** [comment]
I encounter the same issue, but in version 3.2.1. Please find my debug logs below. I do have transaction logs, but from way before this error so I decided not to include them.

```
2017-06-10 19:28:04.806+0000 INFO [o.n.k.i.f.CommunityEditionModule] No locking implementation specified, defaulting to 'community'
2017-06-10 19:28:04.907+0000 INFO [o.n.k.AvailabilityGuard] Requirement makes database unavailable: Database available
2017-06-10 19:28:04.922+0000 INFO [o.n.k.i.DiagnosticsManager] --- INITIALIZED diagnostics START ---
2017-06-10 19:28:04.923+0000 INFO [o.n.k.i.DiagnosticsManager] Neo4j Kernel properties:
2017-06-10 19:28:04.923+0000 INFO [o.n.k.i.DiagnosticsManager] dbms.connector.http.enabled=true
2017-06-10 19:28:04.923+0000 INFO [o.n.k.i.DiagnosticsManager] dbms.security.auth_enabled=false
2017-06-10 19:28:04.924+0000 INFO [o.n.k.i.DiagnosticsManager] dbms.connector.bolt.type=BOLT
2017-06-10 19:28:04.924+0000 INFO [o.n.k.i.DiagnosticsManager] unsupported.dbms.directories.neo4j_home=/Users/piet/Documents/Neo4j/urbansearch.db
2017-06-10 19:28:04.924+0000 INFO [o.n.k.i.DiagnosticsManager] dbms.directories.import=import
2017-06-10 19:28:04.924+0000 INFO [o.n.k.i.DiagnosticsManager] dbms.connector.https.enabled=false
2017-06-10 19:28:04.924+0000 INFO [o.n.k.i.DiagnosticsManager] dbms.connector.http.type=HTTP
2017-06-10 19:28:04.924+0000 INFO [o.n.k.i.DiagnosticsManager] dbms.tx_log.rotation.retention_policy=0 files
2017-06-10 19:28:04.924+0000 INFO [o.n.k.i.DiagnosticsManager] unsupported.dbms.directories.database=/Users/piet/Documents/Neo4j/urbansearch.db
2017-06-10 19:28:04.924+0000 INFO [o.n.k.i.DiagnosticsManager] dbms.logs.http.enabled=false
2017-06-10 19:28:04.924+0000 INFO [o.n.k.i.DiagnosticsManager] dbms.connector.https.type=HTTP
2017-06-10 19:28:04.925+0000 INFO [o.n.k.i.DiagnosticsManager] dbms.memory.pagecache.size=512m
2017-06-10 19:28:04.925+0000 INFO [o.n.k.i.DiagnosticsManager] dbms.allow_format_migration=false
2017-06-10 19:28:04.925+0000 INFO [o.n.k.i.DiagnosticsManager] unsupported.dbms.edition=community
2017-06-10 19:28:04.925+0000 INFO [o.n.k.i.DiagnosticsManager] dbms.connector.bolt.enabled=true
2017-06-10 19:28:04.925+0000 INFO [o.n.k.i.DiagnosticsManager] Diagnostics providers:
2017-06-10 19:28:04.925+0000 INFO [o.n.k.i.DiagnosticsManager] org.neo4j.kernel.configuration.Config
2017-06-10 19:28:04.925+0000 INFO [o.n.k.i.DiagnosticsManager] org.neo4j.kernel.info.DiagnosticsManager
2017-06-10 19:28:04.925+0000 INFO [o.n.k.i.DiagnosticsManager] SYSTEM_MEMORY
2017-06-10 19:28:04.925+0000 INFO [o.n.k.i.DiagnosticsManager] JAVA_MEMORY
2017-06-10 19:28:04.925+0000 INFO [o.n.k.i.DiagnosticsManager] OPERATING_SYSTEM
2017-06-10 19:28:04.925+0000 INFO [o.n.k.i.DiagnosticsManager] JAVA_VIRTUAL_MACHINE
2017-06-10 19:28:04.925+0000 INFO [o.n.k.i.DiagnosticsManager] CLASSPATH
2017-06-10 19:28:04.925+0000 INFO [o.n.k.i.DiagnosticsManager] LIBRARY_PATH
2017-06-10 19:28:04.926+0000 INFO [o.n.k.i.DiagnosticsManager] SYSTEM_PROPERTIES
2017-06-10 19:28:04.926+0000 INFO [o.n.k.i.DiagnosticsManager] NETWORK
2017-06-10 19:28:04.926+0000 INFO [o.n.k.i.DiagnosticsManager] System memory information:
2017-06-10 19:28:04.929+0000 INFO [o.n.k.i.DiagnosticsManager] Total Physical memory: 8.00 GB
2017-06-10 19:28:04.929+0000 INFO [o.n.k.i.DiagnosticsManager] Free Physical memory: 2.13 GB
2017-06-10 19:28:04.930+0000 INFO [o.n.k.i.DiagnosticsManager] Committed virtual memory: 7.05 GB
2017-06-10 19:28:04.930+0000 INFO [o.n.k.i.DiagnosticsManager] Total swap space: 1.00 GB
2017-06-10 19:28:04.931+0000 INFO [o.n.k.i.DiagnosticsManager] Free swap space: 825.75 MB
2017-06-10 19:28:04.931+0000 INFO [o.n.k.i.DiagnosticsManager] JVM memory information:
2017-06-10 19:28:04.931+0000 INFO [o.n.k.i.DiagnosticsManager] Free  memory: 93.31 MB
2017-06-10 19:28:04.931+0000 INFO [o.n.k.i.DiagnosticsManager] Total memory: 123.00 MB
2017-06-10 19:28:04.931+0000 INFO [o.n.k.i.DiagnosticsManager] Max   memory: 1.78 GB
2017-06-10 19:28:04.933+0000 INFO [o.n.k.i.DiagnosticsManager] Garbage Collector: PS Scavenge: [PS Eden Space, PS Survivor Space]
2017-06-10 19:28:04.933+0000 INFO [o.n.k.i.DiagnosticsManager] Garbage Collector: PS MarkSweep: [PS Eden Space, PS Survivor Space, PS Old Gen]
2017-06-10 19:28:04.935+0000 INFO [o.n.k.i.DiagnosticsManager] Memory Pool: Code Cache (Non-heap memory): committed=5.38 MB, used=5.34 MB, max=240.00 MB, threshold=0.00 B
2017-06-10 19:28:04.935+0000 INFO [o.n.k.i.DiagnosticsManager] Memory Pool: Metaspace (Non-heap memory): committed=20.00 MB, used=19.10 MB, max=-1.00 B, threshold=0.00 B
2017-06-10 19:28:04.935+0000 INFO [o.n.k.i.DiagnosticsManager] Memory Pool: Compressed Class Space (Non-heap memory): committed=2.75 MB, used=2.56 MB, max=1.00 GB, threshold=0.00 B
2017-06-10 19:28:04.935+0000 INFO [o.n.k.i.DiagnosticsManager] Memory Pool: PS Eden Space (Heap memory): committed=32.50 MB, used=15.59 MB, max=672.50 MB, threshold=?
2017-06-10 19:28:04.935+0000 INFO [o.n.k.i.DiagnosticsManager] Memory Pool: PS Survivor Space (Heap memory): committed=5.00 MB, used=4.98 MB, max=5.00 MB, threshold=?
2017-06-10 19:28:04.936+0000 INFO [o.n.k.i.DiagnosticsManager] Memory Pool: PS Old Gen (Heap memory): committed=85.50 MB, used=9.12 MB, max=1.33 GB, threshold=0.00 B
2017-06-10 19:28:04.936+0000 INFO [o.n.k.i.DiagnosticsManager] Operating system information:
2017-06-10 19:28:04.936+0000 INFO [o.n.k.i.DiagnosticsManager] Operating System: Mac OS X; version: 10.12.4; arch: x86_64; cpus: 8
2017-06-10 19:28:04.937+0000 INFO [o.n.k.i.DiagnosticsManager] Max number of file descriptors: 10240
2017-06-10 19:28:04.937+0000 INFO [o.n.k.i.DiagnosticsManager] Number of open file descriptors: 37
2017-06-10 19:28:04.945+0000 INFO [o.n.k.i.DiagnosticsManager] Process id: 5057@Makki
2017-06-10 19:28:04.945+0000 INFO [o.n.k.i.DiagnosticsManager] Byte order: LITTLE_ENDIAN
2017-06-10 19:28:04.945+0000 INFO [o.n.k.i.DiagnosticsManager] Local timezone: Europe/Amsterdam
2017-06-10 19:28:04.945+0000 INFO [o.n.k.i.DiagnosticsManager] JVM information:
2017-06-10 19:28:04.945+0000 INFO [o.n.k.i.DiagnosticsManager] VM Name: Java HotSpot(TM) 64-Bit Server VM
2017-06-10 19:28:04.945+0000 INFO [o.n.k.i.DiagnosticsManager] VM Vendor: Oracle Corporation
2017-06-10 19:28:04.945+0000 INFO [o.n.k.i.DiagnosticsManager] VM Version: 25.60-b23
2017-06-10 19:28:04.945+0000 INFO [o.n.k.i.DiagnosticsManager] JIT compiler: HotSpot 64-Bit Tiered Compilers
2017-06-10 19:28:04.946+0000 INFO [o.n.k.i.DiagnosticsManager] VM Arguments: [-Dfile.encoding=UTF-8, -Dinstall4j.launcherId=24, -Dinstall4j.swt=false, -Dexe4j.moduleName=/Applications/Neo4j Community Edition 3.2.1.app, -Di4j.ownBundlePath=/Applications/Neo4j Community Edition 3.2.1.app, -Di4j.jreBundle=/Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/jre.bundle]
2017-06-10 19:28:04.946+0000 INFO [o.n.k.i.DiagnosticsManager] Java classpath:
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [loader.1] file:/Applications/Neo4j%20Community%20Edition%203.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/ext/sunjce_provider.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [loader.1] file:/Applications/Neo4j%20Community%20Edition%203.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/ext/sunec.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [loader.0] file:/Applications/Neo4j%20Community%20Edition%203.2.1.app/Contents/Resources/app/bin/neo4j-desktop-3.2.1.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [loader.1] file:/Applications/Neo4j%20Community%20Edition%203.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/ext/jaccess.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [bootstrap] /Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/classes
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [loader.1] file:/Applications/Neo4j%20Community%20Edition%203.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/ext/sunpkcs11.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [bootstrap] /Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/jfr.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [classpath] /Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/app/bin/neo4j-desktop-3.2.1.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [bootstrap] /Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/jce.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [bootstrap] /Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/rt.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [loader.1] file:/Applications/Neo4j%20Community%20Edition%203.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/ext/dnsns.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [bootstrap] /Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/jsse.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [loader.0] file:/Applications/Neo4j%20Community%20Edition%203.2.1.app/Contents/Resources/app/.install4j/i4jruntime.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [loader.1] file:/Applications/Neo4j%20Community%20Edition%203.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/ext/jfxrt.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [loader.1] file:/Applications/Neo4j%20Community%20Edition%203.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/ext/nashorn.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [bootstrap] /Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/resources.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [classpath] /Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/app/.install4j/i4jruntime.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [loader.1] file:/Applications/Neo4j%20Community%20Edition%203.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/ext/cldrdata.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [loader.1] file:/Applications/Neo4j%20Community%20Edition%203.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/ext/zipfs.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [bootstrap] /Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/charsets.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [bootstrap] /Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/sunrsasign.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [loader.1] file:/Applications/Neo4j%20Community%20Edition%203.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib/ext/localedata.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager]  [loader.1] file:/System/Library/Java/Extensions/MRJToolkit.jar
2017-06-10 19:28:04.948+0000 INFO [o.n.k.i.DiagnosticsManager] Library path:
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] /Users/piet/Library/Java/Extensions
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] /Library/Java/Extensions
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] /Network/Library/Java/Extensions
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] /System/Library/Java/Extensions
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] /usr/lib/java
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] /Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/app/bin
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] System.properties:
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] exe4j.moduleName = /Applications/Neo4j Community Edition 3.2.1.app
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] sun.boot.library.path = /Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/jre.bundle/Contents/Home/jre/lib
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] i4j.jreBundle = /Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/jre.bundle
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] gopherProxySet = false
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] path.separator = :
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] file.encoding.pkg = sun.io
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] user.country = GB
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] sun.java.launcher = SUN_STANDARD
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] sun.os.patch.level = unknown
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] install4j.exeDir = /Applications/
2017-06-10 19:28:04.949+0000 INFO [o.n.k.i.DiagnosticsManager] user.dir = /Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/app/bin
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] i4j.ownBundlePath = /Applications/Neo4j Community Edition 3.2.1.app
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] sun.jnu.encoding = UTF-8
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] unsupported.dbms.udc.source = desktop
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] sun.awt.enableExtraMouseButtons = true
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] install4j.launcherId = 24
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] sun.management.compiler = HotSpot 64-Bit Tiered Compilers
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] install4j.swt = false
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] http.nonProxyHosts = local|*.local|169.254/16|*.169.254/16
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] user.home = /Users/piet
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] user.timezone = Europe/Amsterdam
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] file.encoding = UTF-8
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] user.name = piet
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] sun.java.command = com.install4j.runtime.launcher.MacLauncher
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] sun.arch.data.model = 64
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] user.language = en
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] awt.toolkit = sun.lwawt.macosx.LWCToolkit
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] install4j.appDir = /Applications/Neo4j Community Edition 3.2.1.app/Contents/Resources/app/
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] file.separator = /
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] sun.font.fontmanager = sun.font.CFontManager
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] sun.io.unicode.encoding = UnicodeBig
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] sun.cpu.endian = little
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] socksNonProxyHosts = local|*.local|169.254/16|*.169.254/16
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] ftp.nonProxyHosts = local|*.local|169.254/16|*.169.254/16
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] sun.cpu.isalist = 
2017-06-10 19:28:04.950+0000 INFO [o.n.k.i.DiagnosticsManager] Network information:
2017-06-10 19:28:04.961+0000 INFO [o.n.k.i.DiagnosticsManager] Interface utun0:
2017-06-10 19:28:04.962+0000 INFO [o.n.k.i.DiagnosticsManager]     address: fe80:0:0:0:1feb:dedf:bcba:4e81%utun0
2017-06-10 19:28:04.962+0000 INFO [o.n.k.i.DiagnosticsManager] Interface awdl0:
2017-06-10 19:28:04.962+0000 INFO [o.n.k.i.DiagnosticsManager]     address: fe80:0:0:0:944b:e5ff:fe8b:255d%awdl0
2017-06-10 19:28:04.962+0000 INFO [o.n.k.i.DiagnosticsManager] Interface en0:
2017-06-10 19:28:04.962+0000 INFO [o.n.k.i.DiagnosticsManager]     address: fe80:0:0:0:107c:7360:7f93:906e%en0
2017-06-10 19:28:04.962+0000 INFO [o.n.k.i.DiagnosticsManager]     address: 10.0.0.18
2017-06-10 19:28:04.962+0000 INFO [o.n.k.i.DiagnosticsManager] Interface lo0:
2017-06-10 19:28:04.962+0000 INFO [o.n.k.i.DiagnosticsManager]     address: fe80:0:0:0:0:0:0:1%lo0
2017-06-10 19:28:04.962+0000 INFO [o.n.k.i.DiagnosticsManager]     address: 0:0:0:0:0:0:0:1
2017-06-10 19:28:04.962+0000 INFO [o.n.k.i.DiagnosticsManager]     address: 127.0.0.1
2017-06-10 19:28:04.962+0000 INFO [o.n.k.i.DiagnosticsManager] --- INITIALIZED diagnostics END ---
2017-06-10 19:28:05.382+0000 INFO [o.n.b.v.r.WorkerFactory] Bolt Server extension loaded.
2017-06-10 19:28:05.383+0000 INFO [o.n.b.v.r.WorkerFactory] Bolt enabled on 127.0.0.1:7687.
2017-06-10 19:28:05.482+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Selected RecordFormat:StandardV3_2[v0.A.8] record format from store /Users/piet/Documents/Neo4j/urbansearch.db
2017-06-10 19:28:05.509+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Selected RecordFormat:StandardV3_2[v0.A.8] record format from store /Users/piet/Documents/Neo4j/urbansearch.db
2017-06-10 19:28:05.509+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Format not configured. Selected format from the store: RecordFormat:StandardV3_2[v0.A.8]
2017-06-10 19:28:05.910+0000 INFO [o.n.k.i.a.i.IndexingService] IndexingService.init: indexes not specifically mentioned above are ONLINE
2017-06-10 19:28:05.935+0000 INFO [o.n.k.i.i.l.NativeLabelScanStore] Scan store recovery completed: Number of cleaned crashed pointers: 0 Number of pages visited: 96 Time spent: 3ms
2017-06-10 19:28:07.074+0000 WARN [o.n.k.NeoStoreDataSource] Exception occurred while starting the datasource. Attempting to close things down. Component 'org.neo4j.kernel.recovery.Recovery@1e3f3674' failed to initialize. Please see the attached cause exception "No check point found in any log file from version 13 to 13".
org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.recovery.Recovery@1e3f3674' failed to initialize. Please see the attached cause exception "No check point found in any log file from version 13 to 13".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:416)
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
	at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:511)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:100)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:205)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:124)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211)
	at org.neo4j.desktop.runtime.DatabaseActions.start(DatabaseActions.java:71)
	at org.neo4j.desktop.ui.StartDatabaseActionListener$1.run(StartDatabaseActionListener.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.neo4j.kernel.impl.store.UnderlyingStorageException: No check point found in any log file from version 13 to 13
	at org.neo4j.kernel.recovery.PositionToRecoverFrom.apply(PositionToRecoverFrom.java:108)
	at org.neo4j.kernel.recovery.DefaultRecoverySPI.getPositionToRecoverFrom(DefaultRecoverySPI.java:81)
	at org.neo4j.kernel.recovery.Recovery.init(Recovery.java:80)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
	... 31 more
2017-06-10 19:28:07.076+0000 INFO [o.n.k.i.DiagnosticsManager] --- STOPPING diagnostics START ---
2017-06-10 19:28:07.076+0000 INFO [o.n.k.i.DiagnosticsManager] --- STOPPING diagnostics END ---
2017-06-10 19:28:07.076+0000 INFO [o.n.k.i.f.GraphDatabaseFacadeFactory] Shutdown started
```

**Comment by pushpendrachauhan** [comment]
any updates on above issue, I am facing the same, I am using neo4j 3.2.0 on Ubuntu 14.04

**Comment by vvavepacket** [comment]
how do we force neo4j start even if there are no checkpoints found?

**Comment by MishaDemianenko** [comment]
The database performs checkpointing periodically to guarantee that updates that are held in memory are applied to the persisted store. That is done to minimise the time that will gonna be required for recovery, in case of a not clean shutdown.
You can fully recover the database without checkpoints only if you have all the transaction logs that particular database ever produced. 
"No check point found in any log file from version A to B" means that database was expecting to find one or more checkpoint record in transaction logs but it fails to do so and can't perform recovery and that should not be the case ever.
To be able to understand and figured out why particular database fails to find transaction logs and can't recover we need to have transaction logs and debug logs most of the time and its case by case analysis always.

**Comment by MishaDemianenko** [comment]
Please open a new issue if you encountered a similar problem, closing since there is no news from the reporter for a while.
