### ISSUE TITLE
Setting HA cluster in docker fails to start

### ISSUE THREAD

**Issue by Kivol** [neo4j/neo4j#8766]
[debug.log.txt](https://github.com/neo4j/neo4j/files/754137/debug.log.txt)
- Neo4j version: 3.1.0-enterprise
- Operating system: Amazon Linux 2016.09

Hello,
I'm trying to setup a HA cluster in docker with three instances, but it fails in the instances with server_id 2 and 3. My command to run docker containers were:

```
docker run --name=myserver1.example.com --ulimit nofile=262143:262143 \
    --publish=7474:7474 --publish=7687:7687 \
    --publish=5001:5001 --publish=7001:7001 --publish=6001:6001 \
    --hostname=myserver1.example.com \
    --volume=/data/neo4j/logs:/logs \
    --volume=/data/neo4j/db:/db \
    --env=NEO4J_dbms_mode=HA --env=NEO4J_ha_serverId=1 --env=NEO4J_ha_joinTimeout=180s --env=NEO4J_ha_paxosTimeout=180s \
    --env=NEO4J_ha_broadcastTimeout=180s --env=NEO4J_ha_defaultTimeout=180s --env=NEO4J_ha_leaveTimeout=180s \
    --env=NEO4J_ha_phase1Timeout=180s --env=NEO4J_ha_phase2Timeout=180s \
    --env=NEO4J_ha_initialHosts=myserver1.example.com:5001,myserver2.example.com:5001,myserver3.example.com:5001 \
    neo4j:3.1-enterprise
```
The command is similar with three instances but with different `name` and `hostname` and `NEO4J_ha_serverId`.

The error message in instance 2/3 are like:
```
2017-02-06 09:04:11.504+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3923468a' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3923468a' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3923468a' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:227)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:68)
	at org.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3923468a' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:199)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:193)
	at org.neo4j.kernel.ha.HighlyAvailableGraphDatabase.<init>(HighlyAvailableGraphDatabase.java:43)
	at org.neo4j.server.enterprise.EnterpriseNeoServer.lambda$static$0(EnterpriseNeoServer.java:85)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.cluster.client.ClusterJoin@30a7f22e' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:189)
	... 9 more
Caused by: java.util.concurrent.TimeoutException: Conversation-response mapping:
{3/13#=ResponseFuture{conversationId='3/13#', initiatedByMessageType=join, response=null}}
	at org.neo4j.cluster.statemachine.StateMachineProxyFactory$ResponseFuture.get(StateMachineProxyFactory.java:315)
	at org.neo4j.cluster.client.ClusterJoin.joinByConfig(ClusterJoin.java:143)
	at org.neo4j.cluster.client.ClusterJoin.start(ClusterJoin.java:82)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
	... 13 more
```

I also attached the `debug.log` in instance 2/3. There was nothing special(connection/disconnection only) in the `debug.log` in instance 1.

**Comment by spacecowboy** [comment]
@Kivol you are inventing your own config options which are not exposed via environment variables.

Please see the manual: https://neo4j.com/docs/operations-manual/current/installation/docker/#_highly_available_cluster_settings

Only the following ha settings are exposed via environment variables:

* `NEO4J_ha_serverId`: the id of the server, must be unique within a cluster
* `NEO4J_ha_host_coordination`: the address (including port) used for cluster coordination in HA mode, this must be resolvable by all cluster members
* `NEO4J_ha_host_data`: the address (including port) used for data transfer in HA mode, this must be resolvable by all cluster members
* `NEO4J_ha_initialHosts`: comma-separated list of other members of the cluster

furthermore, the `7001` port is not used so no point in exposing it.

And the debug log says this:

```
Failed to connect to myserver3.example.com/10.20.16.167:5001 due to: java.net.ConnectException: Connection refused: myserver3.example.com/10.20.16.167:5001
```

It seems like nothing is listening at that port. Note that ip-resolution must be correct for HA to function. You might want to look into docker network if you are running these instances on different physical hosts.

**Comment by Kivol** [comment]
It works when I change the network setting to `--net=host`. Thanks.
