### ISSUE TITLE
Using ImpermanentGraphDatabase compiles but fails during runtime in Gradle builds

### ISSUE THREAD

**Issue by szarnyasg** [neo4j/neo4j#8796]
I use ImpermanentGraphDatabase for testing and managed to create a Gradle project that compiles fine but fails runtime.

The related part of the docs presents the required Maven settings: https://neo4j.com/docs/java-reference/current/#tutorials-java-unit-testing

**Neo4j Version:** 3.1.1
**Operating System:** Ubuntu 16.04
**API:** Java API

### Steps to reproduce
1. Clone the repository: https://github.com/szarnyasg/neo4j-impermanentgraphdatabase
2. `cd neo4j-impermanentgraphdatabase-gradle`
3. `./gradlew test --stacktrace`

### Expected behavior
Either the compilation should fail or the test should succeed.

### Actual behavior
The test fails with the following exception:

```
org.neo4j.kernel.impl.util.UnsatisfiedDependencyException: No dependency satisfies type interface org.neo4j.kernel.GraphDatabaseQueryService
	at org.neo4j.kernel.impl.util.Dependencies.resolveDependency(Dependencies.java:71)
	at org.neo4j.kernel.impl.util.Dependencies.resolveDependency(Dependencies.java:67)
	at org.neo4j.graphdb.DependencyResolver$Adapter.resolveDependency(DependencyResolver.java:101)
	at org.neo4j.kernel.impl.factory.ClassicCoreSPI.queryService(ClassicCoreSPI.java:142)
	at org.neo4j.function.Suppliers$1.get(Suppliers.java:72)
	at org.neo4j.kernel.impl.query.Neo4jTransactionalContextFactory.lambda$create$0(Neo4jTransactionalContextFactory.java:52)
	at org.neo4j.kernel.impl.query.Neo4jTransactionalContextFactory.newContext(Neo4jTransactionalContextFactory.java:111)
	at org.neo4j.kernel.impl.query.Neo4jTransactionalContextFactory.newContext(Neo4jTransactionalContextFactory.java:37)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:428)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:412)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:396)
	at igdb.test.IgdbTest.test1(IgdbTest.java:14)
```

The solution is to add the following dependency:

```
compile group: 'org.neo4j', name: 'neo4j', version: neo4jVersion
```

### Remarks

I am not sure this is an error on Neo4j's part and might happen due to Gradle's dependency resolution, as Gradle does not support the `<type>test-jar</type>` notion, but has `classifier: 'tests'` instead (see the related [SO discussion](http://stackoverflow.com/questions/20224260/how-do-i-pull-maven-test-jars-using-gradle)).

I included a Maven project in the repository, which works as expected - without the `org.neo4j:neo4j` dependency, the code does not even compile.

Both the Gradle and the Maven builds are executed on Travis: https://travis-ci.org/szarnyasg/neo4j-impermanentgraphdatabase

**Comment by sarmbruster** [comment]
Your test uses Cypher, therefore your `build.gradle` needs to have the `neo4j-cypher` dependency aboard. Amending this line to `build.gradle` makes a `./gradlew build` succeed:

```testRuntime group: 'org.neo4j', name: 'neo4j-cypher', version: neo4jVersion```

It seems that Gradle and Maven behave slightly different in terms of transitiveness of dependencies using classifiers.

Since this is not a Neo4j I'm closing off this issue.

**Comment by szarnyasg** [comment]
Thanks for the quick reply. It is interesting that Gradle and Maven behave
differently - for most of the time, they use pretty much the same
dependency resolution mechanisms.
Anyways, I hope this issue will be useful for someone who stumbles upon the
same problem in the future.
