### ISSUE TITLE
Race condition deleting an index via REST

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#89]
@garrettheaver: 'I observed a strange behavior rather by accident of having two test runners watching my filesystem for changed test files.

The script I was editing does a full index delete (via curl) before each test and this repeatably results in the server being left locked out with:
```
SEVERE: Commit failed
java.lang.RuntimeException: Index config for 'a' not found
	at org.neo4j.kernel.impl.index.IndexStore.remove(IndexStore.java:215)
	at org.neo4j.index.impl.lucene.LuceneDataSource.deleteIndex(LuceneDataSource.java:591)
	at org.neo4j.index.impl.lucene.LuceneCommand$DeleteCommand.perform(LuceneCommand.java:287)
	at org.neo4j.index.impl.lucene.LuceneTransaction.doCommit(LuceneTransaction.java:259)
	at org.neo4j.kernel.impl.transaction.xaframework.XaTransaction.commit(XaTransaction.java:319)
	at org.neo4j.kernel.impl.transaction.xaframework.XaResourceManager.commit(XaResourceManager.java:476)
	at org.neo4j.kernel.impl.transaction.xaframework.XaResourceHelpImpl.commit(XaResourceHelpImpl.java:64)
	at org.neo4j.kernel.impl.transaction.TransactionImpl.doCommit(TransactionImpl.java:541)
	at org.neo4j.kernel.impl.transaction.TxManager.commit(TxManager.java:444)

...

SEVERE: Unable to rollback transaction. Some resources may be commited others not. Neo4j kernel should be SHUTDOWN for resource maintance and transaction recovery ---->
```
The only way to recover that I've figured so far is to shutdown, reset the database and restart.

Below is a snapshot of FINEST log output setting:

I believe the last two requests (@6ab17e0, @320aad0) are virtually simultaneous requests to delete the index via `curl -X DELETE http://.….`

Just to be sure I reset the DB and introduced a random sleep before the call to delete the index and sure enough the problem disappeared, remove the sleep and it reoccurs immediately.

```
FINE: REQUEST /db/data/index/node/identifiers/urn/urn:def:00000002 on org.mortbay.jetty.HttpConnection@3e9d9ed
FINE: REQUEST /db/data/index/node/identifiers/urn/urn:def:00000002 on org.mortbay.jetty.HttpConnection@3643b5b
FINE: RESPONSE /db/data/index/node/identifiers/urn/urn:def:00000002  200
FINE: RESPONSE /db/data/index/node/identifiers/urn/urn:def:00000002  200
FINE: REQUEST /db/data/node/3/properties on org.mortbay.jetty.HttpConnection@272b72f
FINE: RESPONSE /db/data/node/3/properties  200
FINE: REQUEST /db/data/node/3/properties on org.mortbay.jetty.HttpConnection@16ff634
FINE: RESPONSE /db/data/node/3/properties  200
FINE: REQUEST /db/data/index/node/identifiers on org.mortbay.jetty.HttpConnection@6ab17e0
FINE: REQUEST /db/data/index/node/identifiers on org.mortbay.jetty.HttpConnection@320aad0
FINE: RESPONSE /db/data/index/node/identifiers  204
Jul 5, 2012 8:55:31 PM org.neo4j.kernel.impl.transaction.TxManager commit
SEVERE: Commit failed
java.lang.RuntimeException: Index config for 'identifiers' not found
	at org.neo4j.kernel.impl.index.IndexStore.remove(IndexStore.java:215)
	at org.neo4j.index.impl.lucene.LuceneDataSource.deleteIndex(LuceneDataSource.java:591)
	at org.neo4j.index.impl.lucene.LuceneCommand$DeleteCommand.perform(LuceneCommand.java:287)
	at org.neo4j.index.impl.lucene.LuceneTransaction.doCommit(LuceneTransaction.java:259)
```
The script at the bottom (ruby) will cause the problem to happen. It may take a few runs but eventually will result in the second curl operation returning:
```
< HTTP/1.1 500 Unable to commit transaction
```
And the server is locked at this stage with subsequent requests rendering the following in the log:
```
SEVERE: /db/data/node
org.neo4j.graphdb.TransactionFailureException: Unable to begin transaction
	at org.neo4j.kernel.AbstractGraphDatabase.beginTx(AbstractGraphDatabase.java:771)
	at org.neo4j.kernel.TransactionBuilderImpl.begin(TransactionBuilderImpl.java:39)
	at org.neo4j.server.rest.web.DatabaseActions.beginTx(DatabaseActions.java:231)
	at org.neo4j.server.rest.web.DatabaseActions.createNode(DatabaseActions.java:213)
	at org.neo4j.server.rest.web.RestfulGraphDatabase.createNode(RestfulGraphDatabase.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
```
### SCRIPT
EDIT!: removed and replaced with simpler shell only script in comment below'

**Comment by jakewins** [comment]
This has been resolved in 1.9+ releases
