### ISSUE TITLE
load data.zip using 3.1.1 error

### ISSUE THREAD

**Issue by waterdudu** [neo4j/neo4j#8933]
I am trying to run the neo4j-meetups-reporting example from https://github.com/neo4j-contrib/neo4j-meetups-reporting , after extracting all the files from [data.zip](https://github.com/neo4j-contrib/neo4j-meetups-reporting/tree/master/neo4j) to graph.db folder, I started neo4j server, I got an error.

Here is the console output.

```
$ ./bin/neo4j console
Starting Neo4j.
2017-03-02 15:32:48.066+0000 INFO  Starting...
2017-03-02 15:32:48.940+0000 INFO  Bolt enabled on localhost:7687.
2017-03-02 15:32:49.110+0000 INFO  Starting upgrade of database
2017-03-02 15:32:49.121+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@525332b1' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@525332b1' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@525332b1' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:227)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:68)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@525332b1' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:199)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /Users/dudu/Documents/programs/neo4j-community-3.1.1/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:193)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:124)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:57)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@65b2ad7' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:100)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:189)
	... 9 more
Caused by: org.neo4j.kernel.impl.storemigration.StoreUpgrader$UnexpectedUpgradingStoreVersionException: Not possible to upgrade a store with version 'v0.A.2' to current store version `v0.A.7` (Neo4j 3.1.1).
	at org.neo4j.kernel.impl.storemigration.UpgradableDatabase.checkUpgradeable(UpgradableDatabase.java:135)
	at org.neo4j.kernel.impl.storemigration.StoreUpgrader.migrateIfNeeded(StoreUpgrader.java:130)
	at org.neo4j.kernel.impl.storemigration.DatabaseMigrator.migrate(DatabaseMigrator.java:98)
	at org.neo4j.kernel.NeoStoreDataSource.upgradeStore(NeoStoreDataSource.java:571)
	at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:440)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
	... 14 more
```

**Neo4j Version:** 3.1.1
**Operating System:** macOS

**Comment by spacecowboy** [comment]
@waterdudu you are trying to upgrade a store which has a too old version.

> Not possible to upgrade a store with version 'v0.A.2' to current store version `v0.A.7` (Neo4j 3.1.1).

I can see that `neo4j-contrib` was last updated 3 years ago. So that is a very old version. It's even before version `2.1.0`:
https://github.com/neo4j/neo4j/blob/18e01e340a7366b5078945ca791a096c53f62d3d/community/kernel/src/main/java/org/neo4j/kernel/impl/store/format/StoreVersion.java#L28

To upgrade to 3.1 you would need to:

* First upgrade to `2.3.x`
* Upgrade to `3.0.x`
* Upgrade to `3.1.x`

Please raise an issue with the `neo4j-contrib` project directly or reach out as according to its readme. `neo4j-contrib` is not supported by people typically reading issues here.
