### ISSUE TITLE
Error while running neo4j-import tool

### ISSUE THREAD

**Issue by agastaldoDataxu** [neo4j/neo4j#8990]
Hi team,

I'm running into issues while importing data with neo4j-import tool. 
I've been tweaking my 2 files and went through loads of errors, but I do not know how to go through this one, any idea?

Here the details:

- Neo4j version: Neo4j 3.2.0-alpha05
- Operating system: Linux

`sudo sh neo4j-import --into wiki.db --nodes /home/wikigames/data/nodes.tsv --relationships /home/wikigames/data/rels.tsv --delimiter TAB --stacktrace
WARNING: neo4j-import is deprecated and support for it will be removed in a future
version of Neo4j; please use neo4j-admin import instead.

Neo4j version: 3.2.0-alpha05
Importing the contents of these files into wiki.db:
Nodes:
  /home/wikigames/data/nodes.tsv
Relationships:
  /home/wikigames/data/rels.tsv

Available resources:
  Free machine memory: 24.53 GB
  Max heap memory : 6.98 GB
  Processors: 8

Nodes
[>:34|PROPERTIES-------------------------|NODE:0.00 B|*v:20.85 MB/s---------------------------]2.93M
Done in 5s 281ms
Prepare node index

Done in 30ms
Calculate dense nodes
Error in input data
Caused by:Panic called, so exiting
java.lang.RuntimeException: Panic called, so exiting
	at org.neo4j.unsafe.impl.batchimport.staging.AbstractStep.assertHealthy(AbstractStep.java:155)
	at org.neo4j.unsafe.impl.batchimport.staging.AbstractStep.lambda$new$0(AbstractStep.java:75)
	at org.neo4j.unsafe.impl.batchimport.staging.Processing.await(Processing.java:55)
	at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.receive(ProcessorStep.java:87)
	at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.sendDownstream(ProcessorStep.java:175)
	at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.access$100(ProcessorStep.java:48)
	at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep$Sender.send(ProcessorStep.java:201)
	at org.neo4j.unsafe.impl.batchimport.CalculateRelationshipsStep.process(CalculateRelationshipsStep.java:48)
	at org.neo4j.unsafe.impl.batchimport.CalculateRelationshipsStep.process(CalculateRelationshipsStep.java:33)
	at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.lambda$receive$2(ProcessorStep.java:96)
	at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:242)
Caused by: org.neo4j.unsafe.impl.batchimport.input.InputException: Too many bad entries 1001, where last one was: InputRelationship:
   source: /home/wikigames/data/rels.tsv:502
   startNode: 20 (global id space)
   endNode: 2247231 (global id space)
   type: LINKS_TO
 refering to missing node 20
	at org.neo4j.unsafe.impl.batchimport.input.BadCollector$1.exception(BadCollector.java:86)
	at org.neo4j.unsafe.impl.batchimport.input.BadCollector.checkTolerance(BadCollector.java:175)
	at org.neo4j.unsafe.impl.batchimport.input.BadCollector.collectBadRelationship(BadCollector.java:73)
	at org.neo4j.unsafe.impl.batchimport.CalculateDenseNodesStep.processNodeId(CalculateDenseNodesStep.java:75)
	at org.neo4j.unsafe.impl.batchimport.CalculateDenseNodesStep.forkedProcess(CalculateDenseNodesStep.java:57)
	at org.neo4j.unsafe.impl.batchimport.CalculateDenseNodesStep.forkedProcess(CalculateDenseNodesStep.java:36)
	at org.neo4j.unsafe.impl.batchimport.staging.ForkedProcessorStep.process(ForkedProcessorStep.java:85)
	... 2 more

There were bad entries which were skipped and logged into /usr/local/neo4j/bin/wiki.db/bad.log`

**Comment by agastaldoDataxu** [comment]
Also, I've tried to increase the value of --bad-tolerance and it seems that every time I increase it, it increases the number of bad entries in the log: initially was 1000 and the log tells 1001 bad entries, i put that to 1006 and it tells 1007, then I put to 6000 and it tells 6001.
