### ISSUE TITLE
Can't profile UNION queries

### ISSUE THREAD

**Issue by nawroth** [neo4j/neo4j#920]
This is what I get:
```
java.lang.AssertionError: assertion failed: Can't profile the same pipe twice
	at scala.Predef$.assert(Predef.scala:179)
	at org.neo4j.cypher.internal.profiler.Profiler.decorate(Profiler.scala:47)
	at org.neo4j.cypher.internal.pipes.Pipe$class.createResults(Pipe.scala:35)
	at org.neo4j.cypher.internal.pipes.NullPipe$.createResults(Pipe.scala:47)
	at org.neo4j.cypher.internal.pipes.PipeWithSource.createResults(Pipe.scala:61)
	at org.neo4j.cypher.internal.pipes.PipeWithSource.createResults(Pipe.scala:61)
	at org.neo4j.cypher.internal.pipes.PipeWithSource.createResults(Pipe.scala:61)
	at org.neo4j.cypher.internal.pipes.UnionIterator.loadNextIterator$1(UnionIterator.scala:60)
	at org.neo4j.cypher.internal.pipes.UnionIterator.step$1(UnionIterator.scala:68)
	at org.neo4j.cypher.internal.pipes.UnionIterator.stepIfNeccessary(UnionIterator.scala:79)
	at org.neo4j.cypher.internal.pipes.UnionIterator.hasNext(UnionIterator.scala:43)
	at org.neo4j.cypher.internal.profiler.ProfilingIterator.hasNext(Profiler.scala:164)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:388)
	at org.neo4j.cypher.internal.profiler.ProfilingIterator.hasNext(Profiler.scala:164)
	at org.neo4j.cypher.internal.ClosingIterator$$anonfun$next$1.apply(ClosingIterator.scala:45)
	at org.neo4j.cypher.internal.ClosingIterator.failIfThrows(ClosingIterator.scala:84)
	at org.neo4j.cypher.internal.ClosingIterator.next(ClosingIterator.scala:43)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at org.neo4j.cypher.internal.ClosingIterator.foreach(ClosingIterator.scala:31)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:178)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:259)
	at org.neo4j.cypher.internal.ClosingIterator.to(ClosingIterator.scala:31)
	at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:243)
	at org.neo4j.cypher.internal.ClosingIterator.toList(ClosingIterator.scala:31)
	at org.neo4j.cypher.EagerPipeExecutionResult.<init>(EagerPipeExecutionResult.scala:32)
	at org.neo4j.cypher.internal.executionplan.ExecutionPlanBuilder$$anonfun$5.apply(ExecutionPlanBuilder.scala:145)
	at org.neo4j.cypher.internal.executionplan.ExecutionPlanBuilder$$anonfun$5.apply(ExecutionPlanBuilder.scala:143)
	at org.neo4j.cypher.internal.executionplan.ExecutionPlanBuilder$$anon$1.profile(ExecutionPlanBuilder.scala:51)
	at org.neo4j.cypher.ExecutionEngine$$anonfun$profile$1.apply(ExecutionEngine.scala:53)
	at org.neo4j.cypher.ExecutionEngine$$anonfun$profile$1.apply(ExecutionEngine.scala:52)
	at org.neo4j.cypher.ExecutionEngine.prepare(ExecutionEngine.scala:132)
	at org.neo4j.cypher.ExecutionEngine.profile(ExecutionEngine.scala:52)
	at org.neo4j.cypher.ExecutionEngine.profile(ExecutionEngine.scala:61)
	at org.neo4j.cypher.javacompat.ExecutionEngine.profile(ExecutionEngine.java:96)
```

**Comment by jakewins** [comment]
This seems to work now: http://console.neo4j.org/r/asuegi
