### ISSUE TITLE
causal_cluster cannot start from existing database

### ISSUE THREAD

**Issue by alcoha** [neo4j/neo4j#9248]
Neo4j Version: 3.1

neo4j causal_cluster with 3 cores, and i restore the seeding store from the backed-up database on each of the Core instances in my cluster( i have ensured the graph.db in each one are the same, and i have cleaned the cluster-state). After i start each of the instance, i got the followings in the /logs/debug.log:

2017-04-19 07:30:16.596+0000 INFO  [o.n.c.c.s.CoreStateApplier] Spawning new applier
2017-04-19 07:30:16.601+0000 INFO  [o.n.c.c.s.LocalDatabase] Starting with storeId: Store{creationTime:1492496854561, randomId:-5715753784488176687, upgradeTime:1492496854561, upgradeId:1}
2017-04-19 07:30:16.602+0000 INFO  [o.n.k.i.s.f.RecordFormatSelector] Selected RecordFormat:StandardV3_0[v0.A.7] record format from store /home/smy/neo4j-2/data/databases/graph.db
2017-04-19 07:30:16.604+0000 INFO  [o.n.k.i.s.f.RecordFormatSelector] Selected RecordFormat:StandardV3_0[v0.A.7] record format from store /home/smy/neo4j-2/data/databases/graph.db
2017-04-19 07:30:16.605+0000 INFO  [o.n.k.i.s.f.RecordFormatSelector] Format not configured. Selected format from the store: RecordFormat:StandardV3_0[v0.A.7]
2017-04-19 07:30:16.966+0000 INFO  [o.n.k.i.a.i.IndexingService] IndexingService.init: indexes not specifically mentioned above are POPULATING
2017-04-19 07:30:17.014+0000 INFO  [o.n.k.NeoStoreDataSource] No commits found after last check point (which is at LogPosition{logVersion=0, byteOffset=16})
2017-04-19 07:30:17.015+0000 INFO  [o.n.k.i.a.i.IndexingService] IndexingService.start: indexes not specifically mentioned above are POPULATING
2017-04-19 07:30:17.016+0000 INFO  [o.n.k.i.DatabaseHealth] Database health set to OK
2017-04-19 07:30:17.016+0000 INFO  [o.n.c.c.s.LocalDatabase] Stopping, reason: Database is stopped
2017-04-19 07:30:17.016+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [1]:  Starting check pointing...
2017-04-19 07:30:17.016+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [1]:  Starting store flush...
2017-04-19 07:30:17.023+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [1]:  Store flush completed
2017-04-19 07:30:17.023+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [1]:  Starting appending check point entry into the tx log...
2017-04-19 07:30:17.040+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [1]:  Appending check point entry into the tx log completed
2017-04-19 07:30:17.040+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [1]:  Check pointing completed
2017-04-19 07:30:17.041+0000 INFO  [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [0]:  Starting log pruning.
2017-04-19 07:30:17.041+0000 INFO  [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [0]:  Log pruning complete.
2017-04-19 07:30:17.067+0000 INFO  [o.n.c.c.s.LocalDatabase] Stopping, reason: Database is stopped to copy store from another cluster member
2017-04-19 07:30:17.067+0000 INFO  [o.n.c.c.s.s.CoreStateDownloader] Downloading snapshot from core server at MemberId{406e9373}
2017-04-19 07:30:17.076+0000 INFO  [o.n.c.c.s.RemoteStore] No transaction logs found. Will use metadata store as base for pull request.
2017-04-19 07:30:17.077+0000 INFO  [o.n.c.c.s.RemoteStore] Pulling transactions from: 1
2017-04-19 07:30:17.080+0000 ERROR [o.n.c.c.CatchUpClient] Failed to process message on channel [id: 0xcd7e0890, L:/10.0.56.197:40700 - R:/10.0.56.197:6000]. Expected txId: 1 but got: 2
java.lang.RuntimeException: Expected txId: 1 but got: 2
 at org.neo4j.causalclustering.catchup.tx.TransactionLogCatchUpWriter.onTxReceived(TransactionLogCatchUpWriter.java:83)
 at org.neo4j.causalclustering.catchup.tx.TxPullClient$1.onTxPullResponse(TxPullClient.java:58)
 at org.neo4j.causalclustering.catchup.TrackingResponseHandler.onTxPullResponse(TrackingResponseHandler.java:94)
 at org.neo4j.causalclustering.catchup.tx.TxPullResponseHandler.channelRead0(TxPullResponseHandler.java:45)
 at org.neo4j.causalclustering.catchup.tx.TxPullResponseHandler.channelRead0(TxPullResponseHandler.java:28)
 at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
 at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
 at org.neo4j.causalclustering.catchup.RequestDecoderDispatcher.channelRead(RequestDecoderDispatcher.java:60)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
 at org.neo4j.causalclustering.catchup.ClientMessageTypeHandler.channelRead(ClientMessageTypeHandler.java:78)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
 at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
 at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
 at java.lang.Thread.run(Thread.java:745)
 at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)
2017-04-19 07:30:17.082+0000 ERROR [o.n.c.c.CatchUpClient] Failed to process message on channel [id: 0xcd7e0890, L:/10.0.56.197:40700 - R:/10.0.56.197:6000]. Unexpected value: 6
io.netty.handler.codec.DecoderException: Unexpected value: 6
 at org.neo4j.causalclustering.messaging.marshalling.storeid.StoreIdMarshal.unmarshal0(StoreIdMarshal.java:61)
 at org.neo4j.causalclustering.messaging.marshalling.storeid.StoreIdMarshal.unmarshal0(StoreIdMarshal.java:31)
 at org.neo4j.causalclustering.core.state.storage.SafeChannelMarshal.unmarshal(SafeChannelMarshal.java:42)
 at org.neo4j.causalclustering.catchup.tx.TxPullResponseDecoder.decode(TxPullResponseDecoder.java:44)
 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
 at org.neo4j.causalclustering.catchup.RequestDecoderDispatcher.channelRead(RequestDecoderDispatcher.java:60)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
 at org.neo4j.causalclustering.catchup.ClientMessageTypeHandler.channelRead(ClientMessageTypeHandler.java:78)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
 at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
 at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
 at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
 at java.lang.Thread.run(Thread.java:745)
 at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)
2017-04-19 07:30:18.946+0000 INFO  [o.n.c.c.c.m.RaftMembershipManager] Target membership: [MemberId{683a3289}, MemberId{63a03555}, MemberId{406e9373}]
2017-04-19 07:30:18.948+0000 INFO  [o.n.c.d.HazelcastCoreTopologyService] Current read replica topology is ReadReplicaTopology{readReplicas=[]}
2017-04-19 07:30:22.079+0000 INFO  [o.n.c.c.CatchUpClient] Request timed out. Time since last response: 5000
2017-04-19 07:30:22.132+0000 ERROR [o.n.c.c.s.CoreState] Failed to download snapshot org.neo4j.causalclustering.catchup.CatchUpClientException: Timed out executing operation TxPullRequest{txId=0, storeId=Store{creationTime:1492496854561, randomId:-5715753784488176687, upgradeTime:1492496854561, upgradeId:1}} on MemberId{406e9373} (10.0.56.197:6000)
org.neo4j.causalclustering.catchup.storecopy.StoreCopyFailedException: org.neo4j.causalclustering.catchup.CatchUpClientException: Timed out executing operation TxPullRequest{txId=0, storeId=Store{creationTime:1492496854561, randomId:-5715753784488176687, upgradeTime:1492496854561, upgradeId:1}} on MemberId{406e9373} (10.0.56.197:6000)
 at org.neo4j.causalclustering.catchup.storecopy.RemoteStore.pullTransactions(RemoteStore.java:182)
 at org.neo4j.causalclustering.catchup.storecopy.RemoteStore.tryCatchingUp(RemoteStore.java:136)
 at org.neo4j.causalclustering.core.state.snapshot.CoreStateDownloader.downloadSnapshot(CoreStateDownloader.java:114)
 at org.neo4j.causalclustering.core.state.CoreState.downloadSnapshot(CoreState.java:123)
 at org.neo4j.causalclustering.core.state.CoreState.handle(CoreState.java:87)
 at org.neo4j.causalclustering.core.state.CoreState.handle(CoreState.java:43)
 at org.neo4j.causalclustering.core.server.BatchingMessageHandler.run(BatchingMessageHandler.java:96)
 at org.neo4j.causalclustering.core.consensus.ContinuousJob$AbortableJob.run(ContinuousJob.java:73)
 at java.lang.Thread.run(Thread.java:745)
Caused by: org.neo4j.causalclustering.catchup.CatchUpClientException: Timed out executing operation TxPullRequest{txId=0, storeId=Store{creationTime:1492496854561, randomId:-5715753784488176687, upgradeTime:1492496854561, upgradeId:1}} on MemberId{406e9373} (10.0.56.197:6000)
 at org.neo4j.causalclustering.catchup.TimeoutLoop.exception(TimeoutLoop.java:70)
 at org.neo4j.causalclustering.catchup.TimeoutLoop.waitForCompletion(TimeoutLoop.java:61)
 at org.neo4j.causalclustering.catchup.CatchUpClient.makeBlockingRequest(CatchUpClient.java:102)
 at org.neo4j.causalclustering.catchup.tx.TxPullClient.pullTransactions(TxPullClient.java:48)
 at org.neo4j.causalclustering.catchup.storecopy.RemoteStore.pullTransactions(RemoteStore.java:172)
 ... 8 more
Caused by: java.util.concurrent.TimeoutException
 at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
 at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
 at org.neo4j.causalclustering.catchup.TimeoutLoop.waitForCompletion(TimeoutLoop.java:40)
 ... 11 more

**Comment by martinfurmanski** [comment]
Please upgrade to latest 3.2 (or later branch) and you should not see such issues.
