### ISSUE TITLE
Database crashes and cannot be restarted when writing numbers to the index

### ISSUE THREAD

**Issue by stigrv** [neo4j/neo4j#9352]
In order to enable searching through the data in our database, we've written a plugin that indexes the data it contains. When first indexing nodes and relationships, everything appears to work as expected.

The problem is when data is updated. When data is updated, problems start to occur if there are numeric values in the index for the document to be updated. These are incorrectly translated into SORTED_SET instead of SORTED_NUMERIC when read back from the index, which in turn makes the Lucene index update operation crash. This in turn makes the database server crash, and the full database application is stopped, as this exception is not handled.

When restarting the database, this update operation are found saved in the transaction log, which causes this index update to be attempted again, with the exact same result. This of course results in the database being in such a state that it no more can be restored.

This is the error message I am given:
```
java.lang.IllegalArgumentException: cannot change DocValues type from SORTED_NUMERIC to SORTED_SET for field "modified"
        at org.apache.lucene.index.FieldInfos$FieldNumbers.verifyConsistent(FieldInfos.java:256)
        at org.apache.lucene.index.FieldInfos$FieldNumbers.setDocValuesType(FieldInfos.java:281)
        at org.apache.lucene.index.DefaultIndexingChain.indexDocValue(DefaultIndexingChain.java:430)
        at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:397)
        at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:321)
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:234)
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:450)
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1477)
        at org.neo4j.index.impl.lucene.legacy.CommitContext.applyDocuments(CommitContext.java:99)
        at org.neo4j.index.impl.lucene.legacy.CommitContext.close(CommitContext.java:112)
        at org.neo4j.index.impl.lucene.legacy.LuceneCommandApplier.close(LuceneCommandApplier.java:124)
        at org.neo4j.kernel.impl.api.LegacyBatchIndexApplier.close(LegacyBatchIndexApplier.java:106)
        at org.neo4j.kernel.impl.api.BatchTransactionApplierFacade.close(BatchTransactionApplierFacade.java:70)
        at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:354)
        at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:78)
        at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:51)
        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:608)
        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:484)
        at org.neo4j.kernel.api.KernelTransaction.close(KernelTransaction.java:135)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.closeTransaction(TransactionStateMachine.java:325)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$2.run(TransactionStateMachine.java:229)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:77)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$2.run(BoltStateMachine.java:396)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.run(BoltStateMachine.java:196)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onRun$3(BoltMessageRouter.java:80)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:135)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.executeBatch(RunnableBoltWorker.java:122)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:94)
        at java.lang.Thread.run(Thread.java:745)
```

I've temporarily patched the problem by making changes to the LuceneCommandApplier class, for the close method:
```java
    public void close() {
        try {
            if (this.definitions != null) {
                this.dataSource.getWriteLock();
                for (final CommitContext context : this.nodeContexts.values()) {
                    context.close();
                }
                for (final CommitContext context : this.relationshipContexts.values()) {
                    context.close();
                }
            }
        } catch (final IOException e) {
            throw new RuntimeException("Failure to commit changes to lucene", e);
        } catch (final IllegalArgumentException e) {
            System.out.println("Incorrect lucene data format");
            e.printStackTrace();
        } finally {
            if (this.definitions != null) {
                this.dataSource.releaseWriteLock();
            }
        }
    }
```

This will allow the server to continue running if the index contain numbers, as well as the server to be started if such an operation exists in the transaction log.

**Neo4j Version:** 3.1.3 Enterprise
**Operating System:** Windows 10 64bit 
**API:** Spring Data Neo4j 4.2.3

### Steps to reproduce
1. Add both textual and numberic data to an index
2. Save said index
3. Do an update on the same node, so that the document will be updated
4. Try to save this update to the database
5. See that the server crashes, and refuses to start again

### Expected behavior
It should be possible to save and update numerical values in the index. ValueContext should be honored.

### Actual behavior
Database server crashes and refuses to start up if numerical values are part of an index.

**Comment by tinwelint** [comment]
This was initially fixed in 3.2, so now such a transaction will not be able to commit.
