### ISSUE TITLE
Getting neo4j.v1.api.CypherError: Internal error - should have used fall back to execute query, but something went horribly wrong

### ISSUE THREAD

**Issue by ajays20078** [neo4j/neo4j#9353]
I was trying out the example mentioned in [this](http://neomodel.readthedocs.io/en/latest/getting_started.html#connecting) link using python-driver and on executing the code, i got the below mentioned exception.

Neo4j Version - 3.2.0 (Community edition)
Python neomodel version - 3.2.3
Python neo4j-driver version - 1.1.0
OS - Linux 3.13.0-74-generic #118-Ubuntu

Code:
```
from neomodel import (StructuredNode, StringProperty, IntegerProperty,
    RelationshipTo, RelationshipFrom, config, install_labels)

config.DATABASE_URL = 'bolt://neo4j:password@localhost:7687'

class Country(StructuredNode):
    code = StringProperty(unique_index=True, required=True)

    # traverse incoming IS_FROM relation, inflate to Person objects
    inhabitant = RelationshipFrom('Person', 'IS_FROM')


class Person(StructuredNode):
    name = StringProperty(unique_index=True)
    age = IntegerProperty(index=True, default=0)

    # traverse outgoing IS_FROM relations, inflate to Country objects
    country = RelationshipTo(Country, 'IS_FROM')

install_labels(Country)
install_labels(Person)

jim = Person(name='Jim', age=3).save()

germany = Country(code='DE').save()
jim.country.connect(germany)

if jim.country.is_connected(germany):
    print("Jim's from Germany")

for p in germany.inhabitant.all():
    print(p.name) # Jim

len(germany.inhabitant) # 1

# Find people called 'Jim' in germany
germany.inhabitant.search(name='Jim')

```

Exception:

```
python3 rel.py 
Traceback (most recent call last):
  File "rel.py", line 28, in <module>
    if jim.country.is_connected(germany):
  File "/usr/local/lib/python3.4/dist-packages/neomodel/relationship_manager.py", line 275, in is_connected
    return self._new_traversal().__contains__(node)
  File "/usr/local/lib/python3.4/dist-packages/neomodel/match.py", line 448, in __contains__
    return self.query_cls(self).build_ast()._contains(int(obj.id))
  File "/usr/local/lib/python3.4/dist-packages/neomodel/match.py", line 407, in _contains
    return self._count() == 1
  File "/usr/local/lib/python3.4/dist-packages/neomodel/match.py", line 398, in _count
    results, _ = db.cypher_query(query, self._query_params)
  File "/usr/local/lib/python3.4/dist-packages/neomodel/util.py", line 28, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/neomodel/util.py", line 120, in cypher_query
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.4/dist-packages/neomodel/util.py", line 109, in cypher_query
    results, meta = [list(r.values()) for r in response], response.keys()
  File "/usr/local/lib/python3.4/dist-packages/neomodel/util.py", line 109, in <listcomp>
    results, meta = [list(r.values()) for r in response], response.keys()
  File "/usr/local/lib/python3.4/dist-packages/neo4j/v1/api.py", line 437, in records
    keys = self.keys()
  File "/usr/local/lib/python3.4/dist-packages/neo4j/v1/api.py", line 427, in keys
    self.fetch()
  File "/usr/local/lib/python3.4/dist-packages/neo4j/v1/api.py", line 409, in fetch
    return self._session.fetch()
  File "/usr/local/lib/python3.4/dist-packages/neo4j/v1/bolt.py", line 151, in fetch
    return self.connection.fetch()
  File "/usr/local/lib/python3.4/dist-packages/neo4j/bolt/connection.py", line 397, in fetch
    response.on_failure(metadata or {})
  File "/usr/local/lib/python3.4/dist-packages/neo4j/v1/bolt.py", line 222, in on_failure
    raise self.error_class(metadata)
neo4j.v1.api.CypherError: Internal error - should have used fall back to execute query, but something went horribly wrong
```

And i could see the below information in debug.log on neo4j server

```
2017-05-16 12:54:24.187+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: Internal error - should have used fall back to execute query, but something went horribly wrong, reference 4c32d6e0-a66a-4db4-830c-b8d03ce6f1e3.
2017-05-16 12:54:24.187+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: Internal error - should have used fall back to execute query, but something went horribly wrong, reference 4c32d6e0-a66a-4db4-830c-b8d03ce6f1e3. Internal error - should have used fall back to execute query, but something went horribly wrong
org.neo4j.cypher.internal.ir.v3_2.exception.CantHandleQueryException: Internal error - should have used fall back to execute query, but something went horribly wrong
	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plannerQuery.ClauseConverters$$anonfun$addStartToLogicalPlanInput$1.apply(ClauseConverters.scala:471)
	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plannerQuery.ClauseConverters$$anonfun$addStartToLogicalPlanInput$1.apply(ClauseConverters.scala:460)
	at org.neo4j.cypher.internal.ir.v3_2.PlannerQuery$class.amendQueryGraph(PlannerQuery.scala:66)
	at org.neo4j.cypher.internal.ir.v3_2.RegularPlannerQuery.amendQueryGraph(PlannerQuery.scala:179)
	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plannerQuery.PlannerQueryBuilder$$anonfun$amendQueryGraph$1.apply(PlannerQueryBuilder.scala:34)
	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plannerQuery.PlannerQueryBuilder$$anonfun$amendQueryGraph$1.apply(PlannerQueryBuilder.scala:34)
	at org.neo4j.cypher.internal.ir.v3_2.PlannerQuery$class.updateTailOrSelf(PlannerQuery.scala:81)
	at org.neo4j.cypher.internal.ir.v3_2.RegularPlannerQuery.updateTailOrSelf(PlannerQuery.scala:179)
	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plannerQuery.PlannerQueryBuilder.amendQueryGraph(PlannerQueryBuilder.scala:34)
	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plannerQuery.ClauseConverters$.addStartToLogicalPlanInput(ClauseConverters.scala:460)
	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plannerQuery.ClauseConverters$.addToLogicalPlanInput(ClauseConverters.scala:41)
	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plannerQuery.StatementConverters$$anonfun$toPlannerQueryBuilder$1.apply(StatementConverters.scala:34)
	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plannerQuery.StatementConverters$$anonfun$toPlannerQueryBuilder$1.apply(StatementConverters.scala:33)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plannerQuery.StatementConverters$.toPlannerQueryBuilder(StatementConverters.scala:33)
	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plannerQuery.StatementConverters$.toUnionQuery(StatementConverters.scala:58)
	at org.neo4j.cypher.internal.compiler.v3_2.phases.CreatePlannerQuery$.process(CreatePlannerQuery.scala:38)
	at org.neo4j.cypher.internal.compiler.v3_2.phases.CreatePlannerQuery$.process(CreatePlannerQuery.scala:29)
	at org.neo4j.cypher.internal.frontend.v3_2.phases.Phase$$anonfun$transform$1.apply(Phase.scala:39)
	at org.neo4j.cypher.internal.frontend.v3_2.helpers.package$$anonfun$closing$1.apply(package.scala:27)
	at org.neo4j.cypher.internal.frontend.v3_2.helpers.package$$anonfun$closing$1.apply(package.scala:27)
	at org.neo4j.cypher.internal.frontend.v3_2.helpers.package$.using(package.scala:35)
	at org.neo4j.cypher.internal.frontend.v3_2.helpers.package$.closing(package.scala:27)
	at org.neo4j.cypher.internal.frontend.v3_2.phases.Phase$class.transform(Phase.scala:38)
	at org.neo4j.cypher.internal.compiler.v3_2.phases.CreatePlannerQuery$.transform(CreatePlannerQuery.scala:29)
	at org.neo4j.cypher.internal.frontend.v3_2.phases.PipeLine.transform(Transformer.scala:48)
	at org.neo4j.cypher.internal.frontend.v3_2.phases.PipeLine.transform(Transformer.scala:52)
	at org.neo4j.cypher.internal.frontend.v3_2.phases.PipeLine.transform(Transformer.scala:48)
	at org.neo4j.cypher.internal.frontend.v3_2.phases.PipeLine.transform(Transformer.scala:52)
	at org.neo4j.cypher.internal.frontend.v3_2.phases.PipeLine.transform(Transformer.scala:48)
	at org.neo4j.cypher.internal.frontend.v3_2.phases.PipeLine.transform(Transformer.scala:48)
	at org.neo4j.cypher.internal.frontend.v3_2.phases.If.transform(Transformer.scala:83)
	at org.neo4j.cypher.internal.frontend.v3_2.phases.PipeLine.transform(Transformer.scala:52)
	at org.neo4j.cypher.internal.compiler.v3_2.CypherCompiler.org$neo4j$cypher$internal$compiler$v3_2$CypherCompiler$$createPlan$1(CypherCompiler.scala:80)
	at org.neo4j.cypher.internal.compiler.v3_2.CypherCompiler$$anonfun$2.apply(CypherCompiler.scala:85)
	at org.neo4j.cypher.internal.compiler.v3_2.CypherCompiler$$anonfun$2.apply(CypherCompiler.scala:85)
	at org.neo4j.cypher.internal.compiler.v3_2.QueryCache$$anonfun$getOrElseUpdate$1$$anonfun$apply$1.apply(CacheAccessor.scala:36)
	at org.neo4j.cypher.internal.compiler.v3_2.MonitoringCacheAccessor$$anonfun$1.apply(CacheAccessor.scala:57)
	at org.neo4j.cypher.internal.compiler.v3_2.LFUCache$$anon$1.apply(LFUCache.scala:31)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$16(BoundedLocalCache.java:1973)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1892)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1971)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1954)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
	at org.neo4j.cypher.internal.compiler.v3_2.LFUCache.getOrElseUpdate(LFUCache.scala:30)
	at org.neo4j.cypher.internal.compiler.v3_2.LFUCache.apply(LFUCache.scala:48)
	at org.neo4j.cypher.internal.compiler.v3_2.MonitoringCacheAccessor.getOrElseUpdate(CacheAccessor.scala:55)
	at org.neo4j.cypher.internal.compiler.v3_2.QueryCache$$anonfun$getOrElseUpdate$1.apply(CacheAccessor.scala:34)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at org.neo4j.cypher.internal.compiler.v3_2.QueryCache.getOrElseUpdate(CacheAccessor.scala:46)
	at org.neo4j.cypher.internal.compiler.v3_2.CypherCompiler.planPreparedQuery(CypherCompiler.scala:85)
	at org.neo4j.cypher.internal.compatibility.v3_2.Compatibility$$anon$1$$anonfun$plan$1.apply(Compatibility.scala:72)
	at org.neo4j.cypher.internal.compatibility.v3_2.Compatibility$$anon$1$$anonfun$plan$1.apply(Compatibility.scala:69)
	at org.neo4j.cypher.internal.compatibility.v3_2.exceptionHandler$runSafely$.apply(exceptionHandler.scala:90)
	at org.neo4j.cypher.internal.compatibility.v3_2.Compatibility$$anon$1.plan(Compatibility.scala:69)
	at org.neo4j.cypher.internal.ExecutionEngine.org$neo4j$cypher$internal$ExecutionEngine$$producePlan$1(ExecutionEngine.scala:167)
	at org.neo4j.cypher.internal.ExecutionEngine$$anonfun$liftedTree1$1$1.apply(ExecutionEngine.scala:170)
	at org.neo4j.cypher.internal.ExecutionEngine$$anonfun$liftedTree1$1$1.apply(ExecutionEngine.scala:170)
	at org.neo4j.cypher.internal.compiler.v3_2.QueryCache$$anonfun$getOrElseUpdate$1$$anonfun$apply$1.apply(CacheAccessor.scala:36)
	at org.neo4j.cypher.internal.compiler.v3_2.MonitoringCacheAccessor$$anonfun$1.apply(CacheAccessor.scala:57)
	at org.neo4j.cypher.internal.compiler.v3_2.LFUCache$$anon$1.apply(LFUCache.scala:31)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$16(BoundedLocalCache.java:1973)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1971)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1954)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
	at org.neo4j.cypher.internal.compiler.v3_2.LFUCache.getOrElseUpdate(LFUCache.scala:30)
	at org.neo4j.cypher.internal.compiler.v3_2.LFUCache.apply(LFUCache.scala:48)
	at org.neo4j.cypher.internal.compiler.v3_2.MonitoringCacheAccessor.getOrElseUpdate(CacheAccessor.scala:55)
	at org.neo4j.cypher.internal.compiler.v3_2.QueryCache$$anonfun$getOrElseUpdate$1.apply(CacheAccessor.scala:34)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at org.neo4j.cypher.internal.compiler.v3_2.QueryCache.getOrElseUpdate(CacheAccessor.scala:46)
	at org.neo4j.cypher.internal.ExecutionEngine.liftedTree1$1(ExecutionEngine.scala:170)
	at org.neo4j.cypher.internal.ExecutionEngine.planQuery(ExecutionEngine.scala:156)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:106)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:61)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachineSPI$1.start(TransactionStateMachineSPI.java:144)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:202)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:74)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$2.run(BoltStateMachine.java:394)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.run(BoltStateMachine.java:193)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onRun$3(BoltMessageRouter.java:80)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:130)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:91)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by mdantonio** [comment]
I have the same problem by using an almost identical setup
@ajays20078 do you think that we should report the problem also to neomodel? I'm not totally sure that the problem arises from neo4j, maybe the neomodel library requires an update to support neo4j 3.2

**Comment by ajays20078** [comment]
@mdantonio  The issue is with the latest version of neo4j. Once you set `cypher.default_language_version=3.1` in neo4j.conf and restert neo, it should start working.

**Comment by mdantonio** [comment]
Great suggestion, many thanks! It works

**Comment by ajays20078** [comment]
Re-opening the issue as it  still needs to be fixed in the latest version.

**Comment by rremigius** [comment]
I get the same error using the [Neo4jPHP](https://github.com/jadell/neo4jphp/) driver, when setting a label using `addLabels`.

**Comment by OliviaYtterbrink** [comment]
This has been fixed in https://github.com/neo4j/neo4j/pull/9354
