### ISSUE TITLE
neo4j-import error

### ISSUE THREAD

**Issue by tocean** [neo4j/neo4j#9364]
I want to import data in csv file into neo4j with the following command:
../bin/neo4j-import --into ../data/databases/entity.db --nodes:Entity "nodes_header.csv,node.csv" --relationships:RELE "edges_header.csv,edge.csv" --multiline-fields=true --bad-tolerance 100000000 --stacktrace true --skip-duplicate-nodes true
there are about 2billion nodes and 10billion edges in the csv file.

but i get the error like:

[*RESOLVE (82 collisions):61.19 GB------------------------------------------------------------]2.01B
[*RESOLVE (82 collisions):61.19 GB------------------------------------------------------------]2.03B
[*RESOLVE (82 collisions):61.19 GB------------------------------------------------------------]2.04B
[*RESOLVE (82 collisions):61.19 GB------------------------------------------------------------]2.06B
[*RESOLVE (82 collisions):61.19 GB------------------------------------------------------------]2.08B
[*RESOLVE (82 collisions):61.19 GB------------------------------------------------------------]2.09B
[*RESOLVE (82 collisions):61.19 GB------------------------------------------------------------]2.11B
[*RESOLVE (82 collisions):61.19 GB------------------------------------------------------------]2.13B
[*RESOLVE (82 collisions):61.19 GB------------------------------------------------------------]2.14BException in thread "Thread-1302" java.lan
g.IllegalArgumentException: Collision in source with too many lines (-2143568315)
	at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.SourceInformation.encodeSourceInformation(SourceInformation.java:52)
	at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.EncodingIdMapper.buildCollisionInfo(EncodingIdMapper.java:486)
	at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.EncodingIdMapper.prepare(EncodingIdMapper.java:282)
	at org.neo4j.unsafe.impl.batchimport.IdMapperPreparationStep.process(IdMapperPreparationStep.java:54)
	at org.neo4j.unsafe.impl.batchimport.staging.LonelyProcessingStep$1.run(LonelyProcessingStep.java:56)
Import error: Collision in source with too many lines (-2143568315)
Caused by:Collision in source with too many lines (-2143568315)
java.lang.IllegalArgumentException: Collision in source with too many lines (-2143568315)
	at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.SourceInformation.encodeSourceInformation(SourceInformation.java:52)
	at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.EncodingIdMapper.buildCollisionInfo(EncodingIdMapper.java:486)
	at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.EncodingIdMapper.prepare(EncodingIdMapper.java:282)
	at org.neo4j.unsafe.impl.batchimport.IdMapperPreparationStep.process(IdMapperPreparationStep.java:54)
	at org.neo4j.unsafe.impl.batchimport.staging.LonelyProcessingStep$1.run(LonelyProcessingStep.java:56)

Input error: Collision in source with too many lines (-2143568315)
Caused by:Collision in source with too many lines (-2143568315)
java.lang.IllegalArgumentException: Collision in source with too many lines (-2143568315)
	at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.SourceInformation.encodeSourceInformation(SourceInformation.java:52)
	at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.EncodingIdMapper.buildCollisionInfo(EncodingIdMapper.java:486)
	at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.EncodingIdMapper.prepare(EncodingIdMapper.java:282)
	at org.neo4j.unsafe.impl.batchimport.IdMapperPreparationStep.process(IdMapperPreparationStep.java:54)
	at org.neo4j.unsafe.impl.batchimport.staging.LonelyProcessingStep$1.run(LonelyProcessingStep.java:56)

Neo4j version: 3.1.2 community
 Operating system: linux

is this a bug when there are too many nodes or edges?

**Comment by tocean** [comment]
is there a limit of node size with neo4j-import tool? I read the code and find the lineNumber member of class BufferedCharSeeker is int... Will it change to long in the future?

**Comment by tinwelint** [comment]
This is no longer the case in 3.4 and forwards.
