### ISSUE TITLE
MetataStore Closed Exception

### ISSUE THREAD

**Issue by kanghq** [neo4j/neo4j#9378]
- Neo4j version: 3.1.4-Enterprise, HA 4 cluster.
- Operating system: RHEL7
- API/Driver: JDBC driver
- **Steps to reproduce**
When I using JDBC to execute read-only procedures for a period of time, ususally 40min, an exception occurred.

Client Side:
org.neo4j.driver.v1.exceptions.DatabaseException: MetaDataStore for file '/home/ec2-user/neo4j-enterprise-3.1.4/data/databases/graph.db/neostore' is closed
	at org.neo4j.driver.internal.connector.socket.SocketResponseHandler.handleFailureMessage(SocketResponseHandler.java:74)
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:464)
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:425)
	at org.neo4j.driver.internal.connector.socket.SocketClient.receiveOne(SocketClient.java:130)
	at org.neo4j.driver.internal.connector.socket.SocketClient.receiveAll(SocketClient.java:124)
	at org.neo4j.driver.internal.connector.socket.SocketConnection.receiveAll(SocketConnection.java:129)
	at org.neo4j.driver.internal.connector.socket.SocketConnection.sync(SocketConnection.java:108)
	at org.neo4j.driver.internal.connector.ConcurrencyGuardingConnection.sync(ConcurrencyGuardingConnection.java:136)
	at org.neo4j.driver.internal.pool.PooledConnection.sync(PooledConnection.java:161)
	at org.neo4j.driver.internal.InternalTransaction.close(InternalTransaction.java:110)
	at org.neo4j.jdbc.bolt.BoltPreparedStatement.executeInternal(BoltPreparedStatement.java:92)
	at org.neo4j.jdbc.bolt.BoltPreparedStatement.executeQuery(BoltPreparedStatement.java:54)
	at com.hqkang.SparkApp.core.DBHelper$3.call(DBHelper.java:220)
	at com.hqkang.SparkApp.core.DBHelper$3.call(DBHelper.java:1)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$7$1.apply(JavaRDDLike.scala:186)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$7$1.apply(JavaRDDLike.scala:186)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

ServerSize:
2017-05-17 05:13:10.379+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: MetaDataStore for file '/home/ec2-user/neo4j-enterprise-3.1.4/data/databases/graph.db/neostore' is closed. See debug.log for more details, reference da1392a7-e0fe-43a1-82ee-054eea1ca869.
2017-05-17 05:13:10.379+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: MetaDataStore for file '/home/ec2-user/neo4j-enterprise-3.1.4/data/databases/graph.db/neostore' is closed, reference da1392a7-e0fe-43a1-82ee-054eea1ca869. MetaDataStore for file '/home/ec2-user/neo4j-enterprise-3.1.4/data/databases/graph.db/neostore' is closed
java.lang.IllegalStateException: MetaDataStore for file '/home/ec2-user/neo4j-enterprise-3.1.4/data/databases/graph.db/neostore' is closed
	at org.neo4j.kernel.impl.store.CommonAbstractStore.assertNotClosed(CommonAbstractStore.java:837)
	at org.neo4j.kernel.impl.store.MetaDataStore.getLastClosedTransactionId(MetaDataStore.java:785)
	at org.neo4j.kernel.api.txtracking.TransactionIdTracker.newestEncounteredTxId(TransactionIdTracker.java:108)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachineSPI.newestEncounteredTxId(TransactionStateMachineSPI.java:89)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$2.run(TransactionStateMachine.java:230)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:77)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$2.run(BoltStateMachine.java:396)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.run(BoltStateMachine.java:196)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onRun$3(BoltMessageRouter.java:80)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:135)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.executeBatch(RunnableBoltWorker.java:122)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:94)
	at java.lang.Thread.run(Thread.java:745)

Would you please explain why this exception occurred and how to aovid it.

**Comment by Prillan** [comment]
Same problem. Running a HA cluster with 3 nodes running 3.1.0.
```
java.lang.IllegalStateException: MetaDataStore for file '/var/lib/neo4j/data/databases/graph.db/neostore' is closed
        at org.neo4j.kernel.impl.store.CommonAbstractStore.assertNotClosed(CommonAbstractStore.java:837)
        at org.neo4j.kernel.impl.store.MetaDataStore.getLastClosedTransactionId(MetaDataStore.java:785)
        at org.neo4j.kernel.api.txtracking.TransactionIdTracker.newestEncounteredTxId(TransactionIdTracker.java:108)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachineSPI.newestEncounteredTxId(TransactionStateMachineSPI.java:89)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$2.run(TransactionStateMachine.java:230)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:77)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$2.run(BoltStateMachine.java:397)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.run(BoltStateMachine.java:197)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onRun$3(BoltMessageRouter.java:81)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:136)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:89)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by martinfurmanski** [comment]
@technige Sorry, but I think this is Bolt Server issue. Feel free to remove label again, but it will be without an owner then.

**Comment by zhenlineo** [comment]
Hi @kanghq @Prillan,
Sorry for late reply, but is this problem still exists in your development today?
We would like to look into this issue if it still exists in a more recent version of Neo4j.
Pls do reopen this issue if the problem still exists.
 
Cheers,
Zhen
