### ISSUE TITLE
neo4j-import - NullPointerException

### ISSUE THREAD

**Issue by mjr129** [neo4j/neo4j#9400]
Version 3.20

Crash on importing data:

        java.lang.NullPointerException
        at org.neo4j.unsafe.impl.batchimport.store.BatchingTokenRepository.getOrCreateId(BatchingTokenRepository.java:106)
        at org.neo4j.unsafe.impl.batchimport.store.BatchingTokenRepository$BatchingPropertyKeyTokenRepository.propertyKeysAndValues(BatchingTokenRepository.java:223)
        at org.neo4j.unsafe.impl.batchimport.PropertyEncoderStep.process(PropertyEncoderStep.java:88)
        at org.neo4j.unsafe.impl.batchimport.PropertyEncoderStep.process(PropertyEncoderStep.java:42)
        at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.lambda$receive$2(ProcessorStep.java:97)
        at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:236)

**Comment by jexp** [comment]
Can you provide more detail about your CSV files, and the invocation on the commandline?
