### ISSUE TITLE
already has a transaction bound

### ISSUE THREAD

**Issue by jakinto** [neo4j/neo4j#9445]
I discovered that when I request some unmanaged extension I see in the log a **_already has a transaction bound_** warning.

**Neo4j Version:** 3.1.2 (Enterprise)
**Operating System:** Ubuntu 16.04.2 LTS
**API:** Java API

### Steps to reproduce
1. Using Jmeter for load testing purposes on a custom unmanaged extension
2. Code snipet of the extension:

```
...
Transaction tx = db.beginTx()
db.execute("CALL CustomProcedure")
tx.success();
...
```

### Expected behavior
No warnings in the neo4j.log

### Actual behavior
neo4j.log shows:

2017-05-30 11:31:01.798+0000 WARN  /db/data/transaction/321/commit Thread[qtp2061149602-291,5,main] already has a transaction bound
java.lang.IllegalStateException: Thread[qtp2061149602-291,5,main] already has a transaction bound
	at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.bindTransactionToCurrentThread(ThreadToStatementContextBridge.java:51)
	at org.neo4j.server.rest.transactional.TransitionalTxManagementKernelTransaction.resumeSinceTransactionsAreStillThreadBound(TransitionalTxManagementKernelTransaction.java:64)
	at org.neo4j.server.rest.transactional.TransactionHandle.ensureActiveTransaction(TransactionHandle.java:223)
	at org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:156)
	at org.neo4j.server.rest.web.TransactionalService.lambda$executeStatementsAndCommit$1(TransactionalService.java:216)
	at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
	at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
	at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.neo4j.server.rest.dbms.AuthorizationEnabledFilter.doFilter(AuthorizationEnabledFilter.java:122)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)

**Comment by fickludd** [comment]
Hi @jakinto 
Do I understand it correctly that the only problem the stack-trace in the log, the procedure executes as expected? 

Also to understand this issue further we would need to pinpoint the problem more. Does CustomProcedure generate the stack trace without the unmanaged extension. What about it you use only the unmanaged extension and a regular cypher query? Can you share the actual procedure and unmanaged extension?

**Comment by fickludd** [comment]
I am closing this because of a lack of activity (from everyone!). Please re-open if there is still interest in this.
