### ISSUE TITLE
Neo4j v3.2.1 fails to start from command line

### ISSUE THREAD

**Issue by aamanlamba** [neo4j/neo4j#9528]
- Neo4j version: 3.2.1
- Operating system:Windows Server 2012
-
- **Steps to reproduce**
Trying to start Neo4j 3.2.1 from the command line (using Invoke-Neo4j console) fails with a java error. The application starts fine from the desktop icon. The command line option works fine with v 3.2.0
- Expected behavior
Neo4j runs
- Actual behavior
Error log:
2017-06-16 11:54:03.206+0000 INFO [o.n.k.i.DiagnosticsManager] --- INITIALIZED diagnostics END ---
2017-06-16 11:54:03.551+0000 INFO [o.n.b.v.r.WorkerFactory] Bolt Server extension loaded.
2017-06-16 11:54:03.552+0000 INFO [o.n.b.v.r.WorkerFactory] Bolt enabled on 0.0.0.0:7687.
2017-06-16 11:54:03.722+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Selected RecordFormat:StandardV3_2[v0.A.8] record format from store D:\Apps\Neo4j CE 3.1.4\data\databases\graph.db
2017-06-16 11:54:03.750+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Selected RecordFormat:StandardV3_2[v0.A.8] record format from store D:\Apps\Neo4j CE 3.1.4\data\databases\graph.db
2017-06-16 11:54:03.751+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Format not configured. Selected format from the store: RecordFormat:StandardV3_2[v0.A.8]
2017-06-16 11:54:04.474+0000 INFO [o.n.k.i.a.i.IndexingService] IndexingService.init: indexes not specifically mentioned above are ONLINE
2017-06-16 11:54:05.445+0000 WARN [o.n.k.NeoStoreDataSource] Exception occurred while starting the datasource. Attempting to close things down. Component 'org.neo4j.kernel.recovery.Recovery@e9890a4' failed to initialize. Please see attached cause exception.
org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.recovery.Recovery@e9890a4' failed to initialize. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:416)
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
	at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:511)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:100)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:205)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:124)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:107)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:80)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
**Caused by: java.lang.IllegalArgumentException: Unrecognized log entry version -10. At position LogPosition{logVersion=0, byteOffset=86193010} and entry version null**
	at org.neo4j.kernel.impl.transaction.log.entry.LogEntryVersion.byVersion(LogEntryVersion.java:162)
	at org.neo4j.kernel.impl.transaction.log.entry.VersionAwareLogEntryReader.readLogEntry(VersionAwareLogEntryReader.java:97)
	at org.neo4j.kernel.impl.transaction.log.LogEntryCursor.next(LogEntryCursor.java:54)
	at org.neo4j.kernel.recovery.LatestCheckPointFinder.find(LatestCheckPointFinder.java:82)
	at org.neo4j.kernel.recovery.PositionToRecoverFrom.apply(PositionToRecoverFrom.java:89)
	at org.neo4j.kernel.recovery.DefaultRecoverySPI.getPositionToRecoverFrom(DefaultRecoverySPI.java:81)
	at org.neo4j.kernel.recovery.Recovery.init(Recovery.java:80)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
	... 18 more
2017-06-16 11:54:05.447+0000 INFO [o.n.k.i.DiagnosticsManager] --- STOPPING diagnostics START ---
2017-06-16 11:54:05.447+0000 INFO [o.n.k.i.DiagnosticsManager] --- STOPPING diagnostics END ---
2017-06-16 11:54:05.448+0000 INFO [o.n.k.i.f.GraphDatabaseFacadeFactory] Shutdown started

**Comment by aamanlamba** [comment]
This was resolved by using the full Windows zip distribution, rather than just the \bin folder
