### ISSUE TITLE
Slaves failed to start on Highly Available cluster

### ISSUE THREAD

**Issue by helmiriawan** [neo4j/neo4j#9537]
I am following this [guideline](https://neo4j.com/docs/operations-manual/3.2/tutorial/highly-available-cluster/) to create a Highly Available cluster with 2 AWS instances and another server as an arbiter. When I start the service on all the servers, one of them will be elected as the master, while the others will failed to start (including the arbiter). The master server can be accessed and operated normally.

I have allowed all inbound traffic on AWS servers. All of them also have similar database (I load a dump file to all of them). I use IP address for `ha.initial_hosts` configuration.

This is the log message from the master:
```
2017-06-20 02:01:44.948+0000 INFO  ======== Neo4j 3.2.1 ========
2017-06-20 02:01:45.483+0000 INFO  Starting...
2017-06-20 02:01:46.561+0000 INFO  Write transactions to database disabled
2017-06-20 02:01:47.260+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2017-06-20 02:01:47.314+0000 INFO  Initiating metrics...
2017-06-20 02:01:49.889+0000 INFO  Attempting to join cluster of [<ip_server_1>:5001, <ip_server_2>:5001, <ip_server_3>:5001]
2017-06-20 02:01:51.890+0000 INFO  Could not join cluster of [<ip_server_1>:5001, <ip_server_2>:5001, <ip_server_3>:5001]
2017-06-20 02:01:51.890+0000 INFO  Creating new cluster with name [neo4j.ha]...
2017-06-20 02:01:51.926+0000 INFO  Instance 1 (this server)  entered the cluster
2017-06-20 02:01:51.938+0000 INFO  Instance 1 (this server)  was elected as coordinator
2017-06-20 02:01:51.976+0000 INFO  I am 1, moving to master
2017-06-20 02:01:52.064+0000 INFO  Instance 1 (this server)  was elected as coordinator
2017-06-20 02:01:52.174+0000 INFO  I am 1, successfully moved to master
2017-06-20 02:01:52.192+0000 INFO  Instance 1 (this server)  is available as master at ha://172.31.0.159:6001?serverId=1 with StoreId{creationTime=1497742013651, randomId=4211096603262723165, storeVersion=15813456178476550, upgradeTime=1497742013651, upgradeId=1}
2017-06-20 02:01:52.340+0000 INFO  Instance 1 (this server)  is available as backup at backup://127.0.0.1:6362 with StoreId{creationTime=1497742013651, randomId=4211096603262723165, storeVersion=15813456178476550, upgradeTime=1497742013651, upgradeId=1}
2017-06-20 02:01:52.361+0000 INFO  Database available for write transactions
2017-06-20 02:01:54.969+0000 INFO  Started.
2017-06-20 02:01:55.334+0000 INFO  Mounted REST API at: /db/manage
2017-06-20 02:01:56.980+0000 INFO  Remote interface available at http://localhost:7474/
```

This is the log message from the slave:
```
2017-06-20 02:01:44.948+0000 INFO  ======== Neo4j 3.2.1 ========
2017-06-20 02:01:45.534+0000 INFO  Starting...
2017-06-20 02:01:46.562+0000 INFO  Write transactions to database disabled
2017-06-20 02:01:47.234+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2017-06-20 02:01:47.274+0000 INFO  Initiating metrics...
2017-06-20 02:01:49.898+0000 INFO  Attempting to join cluster of [<ip_server_1>:5001, <ip_server_2>:5001, <ip_server_3>:5001]
2017-06-20 02:02:20.087+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@337a9406' was successfully initialized, but failed to start. Please see the attached cause exception "Conversation-response mapping:
{2/13#=ResponseFuture{conversationId='2/13#', initiatedByMessageType=join, response=null}}". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@337a9406' was successfully initialized, but failed to start. Please see the attached cause exception "Conversation-response mapping:
{2/13#=ResponseFuture{conversationId='2/13#', initiatedByMessageType=join, response=null}}".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@337a9406' was successfully initialized, but failed to start. Please see the attached cause exception "Conversation-response mapping:
{2/13#=ResponseFuture{conversationId='2/13#', initiatedByMessageType=join, response=null}}".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:219)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:107)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:80)
	at org.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@337a9406' was successfully initialized, but failed to start. Please see the attached cause exception "Conversation-response mapping:
{2/13#=ResponseFuture{conversationId='2/13#', initiatedByMessageType=join, response=null}}".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /home/ubuntu/neo4j-enterprise-3.2.1/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:209)
	at org.neo4j.kernel.ha.HighlyAvailableGraphDatabase.<init>(HighlyAvailableGraphDatabase.java:50)
	at org.neo4j.server.enterprise.EnterpriseNeoServer.lambda$static$0(EnterpriseNeoServer.java:68)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.cluster.client.ClusterJoin@6066c4ff' was successfully initialized, but failed to start. Please see the attached cause exception "Conversation-response mapping:
{2/13#=ResponseFuture{conversationId='2/13#', initiatedByMessageType=join, response=null}}".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:205)
	... 9 more
Caused by: java.util.concurrent.TimeoutException: Conversation-response mapping:
{2/13#=ResponseFuture{conversationId='2/13#', initiatedByMessageType=join, response=null}}
	at org.neo4j.cluster.statemachine.StateMachineProxyFactory$ResponseFuture.get(StateMachineProxyFactory.java:315)
	at org.neo4j.cluster.client.ClusterJoin.joinByConfig(ClusterJoin.java:143)
	at org.neo4j.cluster.client.ClusterJoin.start(ClusterJoin.java:82)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	... 13 more
2017-06-20 02:02:20.091+0000 INFO  Neo4j Server shutdown initiated by request
```

This is the log message from the arbiter:
```
2017-06-20 02:01:46.459+0000 INFO [o.n.c.c.ClusterJoin] Attempting to join cluster of [<ip_server_1>:5001, <ip_server_2>:5001, <ip_server_3>:5001]
Exception in thread "main" org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.cluster.client.ClusterJoin@3bbc39f8' was successfully initialized, but failed to start. Please see the attached cause exception "Conversation-response mapping:
{3/4#=ResponseFuture{conversationId='3/4#', initiatedByMessageType=join, response=null}}".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.enterprise.ArbiterBootstrapper.start(ArbiterBootstrapper.java:94)
	at org.neo4j.server.enterprise.ArbiterEntryPoint.main(ArbiterEntryPoint.java:44)
Caused by: java.util.concurrent.TimeoutException: Conversation-response mapping:
{3/4#=ResponseFuture{conversationId='3/4#', initiatedByMessageType=join, response=null}}
	at org.neo4j.cluster.statemachine.StateMachineProxyFactory$ResponseFuture.get(StateMachineProxyFactory.java:315)
	at org.neo4j.cluster.client.ClusterJoin.joinByConfig(ClusterJoin.java:143)
	at org.neo4j.cluster.client.ClusterJoin.start(ClusterJoin.java:82)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	... 3 more
```

This is my configuration:
```
dbms.connectors.default_listen_address=0.0.0.0
dbms.connector.bolt.listen_address=:7687
dbms.connector.http.listen_address=:7474
dbms.connector.https.listen_address=:7473
dbms.mode=HA (ARBITER for the arbiter)
ha.server_id=1 (2 & 3 for other servers)
ha.initial_hosts=<ip_server_1>:5001,<ip_server_2>:5001,<ip_server_3>:5001
dbms.security.allow_csv_import_from_file_urls=true
#ha.host.coordination=127.0.0.1:5001
#ha.host.data=127.0.0.1:6001
```

**Neo4j Version:** enterprise-3.2.1 trial edition
**Operating System:** Ubuntu Server 16.04

**Comment by helmiriawan** [comment]
Found the issue!
It is working now by using private IP address of the servers

**Comment by vvavepacket** [comment]
what do u mean private ip, you mean the internal / subnet ip of AWS like the 172.x.x ? I'm using external public IPs and they are failing...

**Comment by helmiriawan** [comment]
There are several IPs on the configuration, which are public IP, private IP, and IPv6. Use the private IP for HA cluster.

**Comment by vvavepacket** [comment]
Is there any specific reason why use private ip? I just tried now public ip and it worked

**Comment by fashiontai** [comment]
hi ,is just use host mode?
i use docker swarm. create service,set ha.initial_hosts=servicename1:5001,servicename2:5001
network is ok
but can not add to cluster['cluster://servicename1:5001', 'cluster://servicename2:5001'']
can you help me?
