### ISSUE TITLE
[Driver] Exception logs every 3 seconds server side

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#9551]
One of our customer db has log entries every 3s, the origin is unknown.

**Neo4j Version:** 3.2.1
**Operating System:** Debian
**API:** PHP/Python

### Actual behavior

```
2017-06-20 12:14:21.807+0000 WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. Connection reset by peer
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by doopey** [comment]
hi @ikwattro ~
I also seem to be getting this problem.
Did you solve this?
Thanks!

**Comment by ikwattro** [comment]
No, this doesnt cause any issues so far though, except growing log files

**Comment by technige** [comment]
@ikwattro Can you suggest a way for us to recreate this issue?

**Comment by zhenlineo** [comment]
Closing, pls reopen if there is more information to recreate.
