### ISSUE TITLE
division by zero in SingleFilePageSwapper.getLastPageId (Neo4j 2.x)

### ISSUE THREAD

**Issue by joshsh** [neo4j/neo4j#9557]
A small graph (around 200 MB) I have been using for some time appears to be corrupted or unreadable.  The error is one I have not seen before, which has to do with page caching.

Neo4j version: 2.3.3 (via neo4j-gremlin 3.2.4 and neo4j-tinkerpop-api 0.1).
OS: macOS Sierra 10.12.4
Steps to reproduce: attempt to open the graph in Gremlin 3.2.4 Console, e.g.
```
graph = Neo4jGraph.open("/Volumes/encrypted/joshkb/joshkb-neo4j")
```

Stack trace:

```
        Suppressed: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.CommunityFacadeFactory, /Volumes/encrypted/joshkb/joshkb-neo4j
                at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:143)
                ... 22 more
        Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@fd7d7aa' was successfully initialized, but failed to start. Please see attached cause exception.
                at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:462)
                at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
                at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:112)
                at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
                at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
                at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:139)
                ... 22 more
        Caused by: java.lang.ArithmeticException: / by zero
                at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.getLastPageId(SingleFilePageSwapper.java:728)
                at org.neo4j.io.pagecache.impl.muninn.MuninnPagedFile.<init>(MuninnPagedFile.java:100)
                at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.map(MuninnPageCache.java:357)
                at org.neo4j.kernel.impl.store.CommonAbstractStore.loadStorage(CommonAbstractStore.java:181)
                at org.neo4j.kernel.impl.store.CommonAbstractStore.initialise(CommonAbstractStore.java:103)
                at org.neo4j.kernel.impl.store.NeoStores.initialize(NeoStores.java:429)
                at org.neo4j.kernel.impl.store.NeoStores$StoreType$5.open(NeoStores.java:128)
                at org.neo4j.kernel.impl.store.NeoStores$StoreType$5.open(NeoStores.java:121)
                at org.neo4j.kernel.impl.store.NeoStores.openStore(NeoStores.java:422)
                at org.neo4j.kernel.impl.store.NeoStores.getOrCreateStore(NeoStores.java:467)
                at org.neo4j.kernel.impl.store.NeoStores.<init>(NeoStores.java:365)
                at org.neo4j.kernel.impl.store.StoreFactory.openNeoStores(StoreFactory.java:174)
                at org.neo4j.kernel.impl.store.StoreFactory.openAllNeoStores(StoreFactory.java:138)
                at org.neo4j.kernel.NeoStoreDataSource.buildNeoStore(NeoStoreDataSource.java:661)
                at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:535)
                at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
                ... 27 more
```

**Comment by chrisvest** [comment]
Any idea how you got it into that state?

Have you ever specified a custom value for the `string_block_size` (or any `*_block_size`) setting?

What happens is that the block size is recorded in the store itself upon creation, and apparently when we read this value back it is greater than the page size, which the code is not expecting.

**Comment by joshsh** [comment]
No, I have not specified a custom `*_block_size`. FWIW, I don't find anything by grepping on "block_size" in the database directory, either.

Unfortunately, I can't say how the database got into this state; the error first occurred during a normal startup.  It is possible that Gremlin Server was previously killed during a Neo4j transaction, but I think it is unlikely.

**Comment by joshsh** [comment]
FYI, when I try to upgrade from 2.3.3 to 3.0.3, the following (Lucene-related) failure occurs:

```
Exception in thread "Lucene Merge Thread #0" org.apache.lucene.index.MergePolicy$MergeException: org.apache.lucene.index.CorruptIndexException: doc counts differ for segment _u: fieldsReader shows 28 but segmentInfo shows 30
	at org.apache.lucene.index.ConcurrentMergeScheduler.handleMergeException(ConcurrentMergeScheduler.java:549)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:522)
Caused by: org.apache.lucene.index.CorruptIndexException: doc counts differ for segment _u: fieldsReader shows 28 but segmentInfo shows 30
	at org.apache.lucene.codecs.lucene3x.Lucene3xStoredFieldsReader.<init>(Lucene3xStoredFieldsReader.java:181)
	at org.apache.lucene.codecs.lucene3x.Lucene3xStoredFieldsFormat.fieldsReader(Lucene3xStoredFieldsFormat.java:37)
	at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:133)
	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:108)
	at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:145)
	at org.apache.lucene.index.ReadersAndUpdates.getReaderForMerge(ReadersAndUpdates.java:664)
	at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4152)
	at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:3811)
	at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:409)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:486)
[WARN] DefaultGraphManager - Graph [graph] configured at [conf/neo4j-joshkb.properties] could not be instantiated and will not be available in Gremlin Server.  GraphFactory message: GraphFactory could not instantiate this Graph implementation [class org.apache.tinkerpop.gremlin.neo4j.structure.Neo4jGraph]
java.lang.RuntimeException: GraphFactory could not instantiate this Graph implementation [class org.apache.tinkerpop.gremlin.neo4j.structure.Neo4jGraph]
	at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:82)
	at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:70)
	at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:104)
	at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.lambda$new$0(DefaultGraphManager.java:57)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:671)
	at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.<init>(DefaultGraphManager.java:55)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:111)
	at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:90)
	at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:110)
	at org.apache.tinkerpop.gremlin.server.GremlinServer.main(GremlinServer.java:354)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:78)
	... 13 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.CommunityFacadeFactory, /Volumes/encrypted/joshkb/joshkb-neo4j
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:144)
	at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:40)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:100)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory.lambda$createDatabaseCreator$203(GraphDatabaseFactory.java:89)
	at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:183)
	at org.neo4j.tinkerpop.api.impl.Neo4jFactoryImpl.newGraphDatabase(Neo4jFactoryImpl.java:46)
	at org.neo4j.tinkerpop.api.Neo4jFactory$Builder.open(Neo4jFactory.java:32)
	at org.apache.tinkerpop.gremlin.neo4j.structure.Neo4jGraph.<init>(Neo4jGraph.java:130)
	at org.apache.tinkerpop.gremlin.neo4j.structure.Neo4jGraph.open(Neo4jGraph.java:144)
	... 18 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@30a88433' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:99)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:140)
	... 27 more
Caused by: org.neo4j.kernel.impl.storemigration.StoreUpgrader$UnableToUpgradeException: Failure doing migration
	at org.neo4j.kernel.impl.storemigration.StoreUpgrader.migrateToIsolatedDirectory(StoreUpgrader.java:248)
	at org.neo4j.kernel.impl.storemigration.StoreUpgrader.migrateIfNeeded(StoreUpgrader.java:132)
	at org.neo4j.kernel.impl.storemigration.DatabaseMigrator.migrate(DatabaseMigrator.java:98)
	at org.neo4j.kernel.NeoStoreDataSource.upgradeStore(NeoStoreDataSource.java:557)
	at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:430)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	... 32 more
Caused by: java.io.IOException: Legacy index migration failed.
	at org.neo4j.kernel.impl.storemigration.participant.LegacyIndexMigrator.migrateLegacyIndexes(LegacyIndexMigrator.java:127)
	at org.neo4j.kernel.impl.storemigration.participant.LegacyIndexMigrator.migrate(LegacyIndexMigrator.java:77)
	at org.neo4j.kernel.impl.storemigration.StoreUpgrader.migrateToIsolatedDirectory(StoreUpgrader.java:240)
	... 37 more
Caused by: org.neo4j.upgrade.lucene.LegacyIndexMigrationException: Migration of legacy index at path:/Volumes/encrypted/joshkb/joshkb-neo4j/upgrade/index/lucene/node/shortcut-index failed.
	at org.neo4j.upgrade.lucene.LuceneLegacyIndexUpgrader.upgradeIndexes(LuceneLegacyIndexUpgrader.java:114)
	at org.neo4j.kernel.impl.storemigration.participant.LegacyIndexMigrator.migrateLegacyIndexes(LegacyIndexMigrator.java:121)
	... 39 more
Caused by: java.io.IOException: background merge hit exception: _u(3.6.2):C30 into _x [maxNumSegments=1]
	at org.apache.lucene.index.IndexWriter.forceMerge(IndexWriter.java:1829)
	at org.apache.lucene.index.IndexWriter.forceMerge(IndexWriter.java:1769)
	at org.apache.lucene.index.IndexUpgrader.upgrade(IndexUpgrader.java:165)
	at org.apache.lucene.index.IndexUpgrader.main(IndexUpgrader.java:73)
	at org.neo4j.upgrade.lucene.IndexUpgraderWrapper.upgradeIndex(IndexUpgraderWrapper.java:66)
	at org.neo4j.upgrade.lucene.LuceneLegacyIndexUpgrader.upgradeIndexes(LuceneLegacyIndexUpgrader.java:108)
	... 40 more
Caused by: org.apache.lucene.index.CorruptIndexException: doc counts differ for segment _u: fieldsReader shows 28 but segmentInfo shows 30
	at org.apache.lucene.codecs.lucene3x.Lucene3xStoredFieldsReader.<init>(Lucene3xStoredFieldsReader.java:181)
	at org.apache.lucene.codecs.lucene3x.Lucene3xStoredFieldsFormat.fieldsReader(Lucene3xStoredFieldsFormat.java:37)
	at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:133)
	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:108)
	at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:145)
	at org.apache.lucene.index.ReadersAndUpdates.getReaderForMerge(ReadersAndUpdates.java:664)
	at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4152)
	at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:3811)
	at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:409)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:486)
```

**Comment by joshsh** [comment]
If I just remove the index/lucene directory, I again run into the page cache issue (with a slightly more informative error message):

```
	Suppressed: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.CommunityFacadeFactory, /Volumes/encrypted/joshkb/joshkb-neo4j
		at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:144)
		... 27 more
	Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@27d7507a' was successfully initialized, but failed to start. Please see attached cause exception.
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
		at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
		at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:99)
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
		at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
		at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:140)
		... 27 more
	Caused by: java.lang.IllegalArgumentException: Cannot map files with a filePageSize (0) that is less than 8 bytes
		at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.map(MuninnPageCache.java:359)
		at org.neo4j.kernel.impl.store.CommonAbstractStore.loadStorage(CommonAbstractStore.java:246)
		at org.neo4j.kernel.impl.store.CommonAbstractStore.initialise(CommonAbstractStore.java:127)
		at org.neo4j.kernel.impl.store.NeoStores.initialize(NeoStores.java:224)
		at org.neo4j.kernel.impl.store.NeoStores.createDynamicStringStore(NeoStores.java:545)
		at org.neo4j.kernel.impl.store.NeoStores.createDynamicStringStore(NeoStores.java:539)
		at org.neo4j.kernel.impl.store.StoreType$5.open(StoreType.java:69)
		at org.neo4j.kernel.impl.store.StoreType$5.open(StoreType.java:64)
		at org.neo4j.kernel.impl.store.NeoStores.openStore(NeoStores.java:217)
		at org.neo4j.kernel.impl.store.NeoStores.getOrCreateStore(NeoStores.java:262)
		at org.neo4j.kernel.impl.store.NeoStores.<init>(NeoStores.java:136)
		at org.neo4j.kernel.impl.store.StoreFactory.openNeoStores(StoreFactory.java:158)
		at org.neo4j.kernel.impl.store.StoreFactory.openAllNeoStores(StoreFactory.java:122)
		at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.<init>(RecordStorageEngine.java:210)
		at org.neo4j.kernel.NeoStoreDataSource.buildStorageEngine(NeoStoreDataSource.java:573)
		at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:441)
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
		... 32 more
```

**Comment by chrisvest** [comment]
The `index/lucene` directory contains the manual indexes. They cannot be rebuilt if they are deleted, just so you know.

It's definitely the block size recorded by the store that is wrong. The first four bytes of `neostore.propertystore.db.strings` should say `00 00 00 78` for the 120 byte block size that was default in 2.3.X, or `00 00 00 80` for the 128 byte block size that is the default in 3.X onwards.

If you manage to make the file mappable, and the database startable, then I recommend you run a consistency check on the store. Something certainly happened to the file, and this is likely not the only problem.

**Comment by joshsh** [comment]
No worries; it is easy to rebuild the Lucene index in my case.

You were right about `neostore.propertystore.db.strings`; I see 128 bytes worth of zeroes (with the exception of the first four bytes, `00 00 00 80`) at the beginning of the file in an uncorrupted directory, but no such empty block in the corrupted directory.  FWIW, they are 128-byte blocks even in backup directories created with Neo4j 2.3.3.

I had some limited success reading from the graph by simply prepending the 128-byte header to `neostore.propertystore.db.strings`.  For some reason, that header was simply missing, with most of the rest of the file identical to my backups.  This wasn't a complete fix, though, as I ran into another problem while attempting to export the graph with a scan over all nodes.

**Comment by joshsh** [comment]
Btw. although I was able to export my graph after removing the transaction log and catching individual `InvalidRecordException`s as in https://github.com/neo4j/neo4j/issues/5055, the string table was not correct; many property values appeared permuted in the graph.

**Comment by chrisvest** [comment]
Why did you remove the transaction logs? Was it not able to run recovery on the store?

**Comment by chrisvest** [comment]
Closing since it sounds like the files might have been interfered with by external factors, which we have no idea about.
