### ISSUE TITLE
batch-import loads data but then java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by mongoose54** [neo4j/neo4j#9645]
I am having the following configuration:

- Neo4j version: 3.2.2
- Operating system: Ubuntu 14.04)
- API/Driver: Java API

I am trying to load a nodes.csv and relationships.csv like this:

./neo4j-community-3.2.2/bin/neo4j-import --into neo4j-community-3.2.2/data/databases/graph.db --nodes nodes.csv --relationships rels.csv --stacktrace true --skip-bad-relationships true --skip-bad-nodes true --skip-duplicate-nodes true --ignore-empty-strings true --ignore-extra-columns true 

I think it is almost done importing but I get the following error:

```
IMPORT DONE in 35m 27s 271ms. 
Imported:
  3436328 nodes
  71988252 relationships
  3436328 properties
Peak memory usage: 592.64 MB
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.neo4j.kernel.impl.store.kvstore.ConcurrentMapState.sortedUpdates(ConcurrentMapState.java:390)
	at org.neo4j.kernel.impl.store.kvstore.ConcurrentMapState.dataProvider(ConcurrentMapState.java:377)
	at org.neo4j.kernel.impl.store.kvstore.ConcurrentMapState.dataProvider(ConcurrentMapState.java:363)
	at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:92)
	at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:52)
	at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:311)
	at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.run(AbstractKeyValueStore.java:296)
	at org.neo4j.kernel.impl.store.kvstore.ConcurrentMapState$1.close(ConcurrentMapState.java:149)
	at org.neo4j.kernel.impl.store.counts.CountsUpdater.close(CountsUpdater.java:155)
	at org.neo4j.unsafe.impl.batchimport.ParallelBatchImporter.doImport(ParallelBatchImporter.java:249)
	at org.neo4j.tooling.ImportTool.doImport(ImportTool.java:505)
	at org.neo4j.tooling.ImportTool.main(ImportTool.java:438)
	at org.neo4j.tooling.ImportTool.main(ImportTool.java:347)
```

Here are samples of the nodes.csv:

```
"CUI:ID",":LABEL"
"C3609949","['Hippeastrum morelianum Lem.', 'Hippeastrum morelianum']"
"C2056228","['tenderness on palpation of distal phalanx of fifth toe of left foot (physical finding)', 'tenderness on palpation of distal phalanx of fifth toe of left foot']"
```

and from the relationships.csv:

```
"CUI:START_ID","CUI:END_ID",":TYPE"
"C0236642","C0270715","RB"
"C0003787","C0037728","RB"
"C0018090","C0032636","RB"
"C0039194","C0024264","RB"
"C0004561","C0024264","RB"
"C0022801","C0035287","RB"
"C0022801","C0227525","RB"
"C0022801","C0449475","RB"
"C0034143","C0682702","RB"

```

**Comment by chrisvest** [comment]
Try giving it more heap memory with the `HEAP_SIZE` environment variable, e.g. `HEAP_SIZE=4g ./neo4j-community-3.2.2/bin/neo4j-import --into …`

**Comment by jexp** [comment]
The time is also way too long. 

You use of node labels is very unusual are you sure it's not a names or name and aliases fields? I presume you have millions of them. 

Label would be sth like Species

**Comment by eebus** [comment]
@mongoose54 
Had any success with the suggestions?
