### ISSUE TITLE
Neo4j 3.2.0 won't start on database files used by a 3.2.3 instance previously

### ISSUE THREAD

**Issue by amorgner** [neo4j/neo4j#9775]
Neo4j 3.2.0 is unable to run on database files created with Neo4j 3.2.0 after they have been used by Neo4j 3.2.3, log shows error

    Unrecognized log entry version -10. At position LogPosition{logVersion=0, byteOffset=34} and entry version null

**Neo4j Version:** 3.2.3 / 3.2.0
**Operating System:** Ubuntu 17.10  

### Steps to reproduce
1. Start Neo4j 3.2.0 (fresh installation)
2. Stop Neo4j 3.2.0
3. Start Neo4j 3.2.3 on same database files created by 3.2.0 instance
4. Stop Neo4j 3.2.3
5. Start Neo4j 3.2.0 again on same database files previously used with 3.2.3 instance

### Expected behavior
Normal database startup there's no documented format change, and 3.2.3 starts without `dbms.allow_format_migration` being enabled.

### Actual behavior
Database fails to start with the following exception stacktrace:

	2017-08-04 11:09:58.921+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@156604c1' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@156604c1' was successfully initialized, but failed to start. Please see attached cause exception.
	org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@156604c1' was successfully initialized, but failed to start. Please see attached cause exception.
		at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
		at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:219)
		at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:107)
		at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:80)
		at org.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:32)
	Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@156604c1' was successfully initialized, but failed to start. Please see attached cause exception.
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
		at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
		at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211)
		... 3 more
	Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /home/axel/Downloads/neo4j-enterprise-3.2.0/data/databases/graph.db
		at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:209)
		at org.neo4j.graphdb.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:44)
		at org.neo4j.server.enterprise.EnterpriseNeoServer.lambda$static$1(EnterpriseNeoServer.java:74)
		at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
		... 5 more
	Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.recovery.Recovery@e4efaa5' failed to initialize. Please see attached cause exception.
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:416)
		at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
		at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
		at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:511)
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
		at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
		at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:100)
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
		at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
		at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:205)
		... 9 more
	Caused by: java.lang.IllegalArgumentException: Unrecognized log entry version -10. At position LogPosition{logVersion=0, byteOffset=34} and entry version null
		at org.neo4j.kernel.impl.transaction.log.entry.LogEntryVersion.byVersion(LogEntryVersion.java:162)
		at org.neo4j.kernel.impl.transaction.log.entry.VersionAwareLogEntryReader.readLogEntry(VersionAwareLogEntryReader.java:97)
		at org.neo4j.kernel.impl.transaction.log.LogEntryCursor.next(LogEntryCursor.java:54)
		at org.neo4j.kernel.recovery.LatestCheckPointFinder.find(LatestCheckPointFinder.java:82)
		at org.neo4j.kernel.recovery.PositionToRecoverFrom.apply(PositionToRecoverFrom.java:89)
		at org.neo4j.kernel.recovery.DefaultRecoverySPI.getPositionToRecoverFrom(DefaultRecoverySPI.java:81)
		at org.neo4j.kernel.recovery.Recovery.init(Recovery.java:80)
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
		... 18 more
	2017-08-04 11:09:58.922+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by chrisvest** [comment]
To fix another bug, we had to change our transaction log format in 3.0.10/3.1.5/3.2.1, so your 3.2.3 store can only be started as far back as 3.2.1.

**Comment by amorgner** [comment]
Ok, thanks for clarifying. Wouldn't it be good to document it and not allow upgrades from 3.2.0 to 3.2.x without the `dbms.allow_format_migration` switch?

**Comment by chrisvest** [comment]
We call it out in the release notes every time we do this, but you're right that the product should handle it better when this happens. I'll open an issue to track this internally.

**Comment by amorgner** [comment]
Thanks!
