### ISSUE TITLE
Failed to rotate Logs:   Expected version: 54 74367, actual version: 3813743, wait timeout (ms): 600001

### ISSUE THREAD

**Issue by chrisfauerbach** [neo4j/neo4j#9807]
- Neo4j version: 3.1.4 Enterprise
- Operating system: Centos 7
- API/Driver: py2neo
- **Steps to reproduce**

My QA Neo4J has been experiencing this failure for months.     It happens every day or so, sometimes multiples times a day.

Try as I may to fix it, I have to run the following to fix it (it's super bad, don't judge me):

```
service neo4j stop
cd /var/lib/neo4j/data/databases/graph.db/
find . | grep lock |xargs rm -f
rm -f neostore.transaction.db.??
rm -f /var/log/neo4j/*.log
service neo4j start

```
Output of some logs:  

```$ sed '188,329!d' neo4j.log
2017-04-15 04:15:44.458+0000 ERROR Failed to start transaction. Database has encountered some problem, please perform necessary action (tx recovery/restart)
org.neo4j.graphdb.TransactionFailureException: Database has encountered some problem, please perform necessary action (tx recovery/restart)
	at org.neo4j.kernel.impl.factory.ClassicCoreSPI.beginTransaction(ClassicCoreSPI.java:181)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransactionInternal(GraphDatabaseFacade.java:578)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransaction(GraphDatabaseFacade.java:383)
	at org.neo4j.server.rest.transactional.TransitionalTxManagementKernelTransaction.startTransaction(TransitionalTxManagementKernelTransaction.java:123)
	at org.neo4j.server.rest.transactional.TransitionalTxManagementKernelTransaction.<init>(TransitionalTxManagementKernelTransaction.java:51)
	at org.neo4j.server.rest.transactional.TransitionalPeriodTransactionMessContainer.newTransaction(TransitionalPeriodTransactionMessContainer.java:54)
	at org.neo4j.server.rest.transactional.TransactionHandle.ensureActiveTransaction(TransactionHandle.java:213)
	at org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:156)
	at org.neo4j.server.rest.web.TransactionalService.lambda$executeStatementsAndCommit$1(TransactionalService.java:216)
	at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
	at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
	at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.neo4j.server.rest.dbms.AuthorizationDisabledFilter.doFilter(AuthorizationDisabledFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.neo4j.kernel.api.exceptions.TransactionFailureException: Database has encountered some problem, please perform necessary action (tx recovery/restart)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.neo4j.kernel.internal.DatabaseHealth.assertHealthy(DatabaseHealth.java:62)
	at org.neo4j.kernel.impl.api.Kernel.newTransaction(Kernel.java:99)
	at org.neo4j.kernel.impl.factory.ClassicCoreSPI.beginTransaction(ClassicCoreSPI.java:173)
	... 40 more
Caused by: org.neo4j.kernel.impl.store.UnderlyingStorageException: Error performing check point
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.constructCombinedFailure(CheckPointScheduler.java:96)
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.run(CheckPointScheduler.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)
	Suppressed: org.neo4j.kernel.impl.store.kvstore.RotationTimeoutException: Failed to rotate logs. Expected version: 5472028, actual version: 3813743, wait timeout (ms): 600090
		at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:79)
		at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:52)
		at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:311)
		at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:288)
		at org.neo4j.kernel.impl.store.counts.CountsTracker.rotate(CountsTracker.java:154)
		at org.neo4j.kernel.impl.store.NeoStores.flush(NeoStores.java:237)
		at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.flushAndForce(RecordStorageEngine.java:479)
		at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:202)
		at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.checkPointIfNeeded(CheckPointerImpl.java:171)
		at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.run(CheckPointScheduler.java:60)
		... 8 more
	Suppressed: org.neo4j.kernel.impl.store.kvstore.RotationTimeoutException: Failed to rotate logs. Expected version: 5474367, actual version: 3813743, wait timeout (ms): 600001
		at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:79)
		at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:52)
		at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:311)
		at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:288)
		at org.neo4j.kernel.impl.store.counts.CountsTracker.rotate(CountsTracker.java:154)
		at org.neo4j.kernel.impl.store.NeoStores.flush(NeoStores.java:237)
		at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.flushAndForce(RecordStorageEngine.java:479)
		at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:202)
		at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.checkPointIfNeeded(CheckPointerImpl.java:171)
		at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.run(CheckPointScheduler.java:60)
		... 8 more
	Suppressed: org.neo4j.kernel.impl.store.kvstore.RotationTimeoutException: Failed to rotate logs. Expected version: 5474367, actual version: 3813743, wait timeout (ms): 600083
		at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:79)
		at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:52)
		at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:311)
		at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:288)
		at org.neo4j.kernel.impl.store.counts.CountsTracker.rotate(CountsTracker.java:154)
		at org.neo4j.kernel.impl.store.NeoStores.flush(NeoStores.java:237)
		at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.flushAndForce(RecordStorageEngine.java:479)
		at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:202)
		at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.checkPointIfNeeded(CheckPointerImpl.java:171)
		at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.run(CheckPointScheduler.java:60)
		... 8 more
```

**Comment by chrisvest** [comment]
Don't delete the transaction logs. Try deleting the `neostore.counts.db.a/.b` files instead. Neo4j will rebuild them if they are missing. If possible, try upgrading to 3.1.6.

**Comment by chrisfauerbach** [comment]
@chrisvest  - I upgraded to 3.2.3, and removed the count files.    Time to keep an eye on it!    Thanks for the advice.

**Comment by MishaDemianenko** [comment]
Hi @chrisfauerbach, I would assume @chrisvest suggestion did the trick right? If so can we close this issue?

**Comment by MishaDemianenko** [comment]
@chrisfauerbach closing this as solved. Please feel free o reopen in case this is still a problem

**Comment by chrisfauerbach** [comment]
Yes, this saved the day.    Thank you, and my apologies for not responding.

**Comment by vladkras** [comment]
Seems to help for 3.4.1 too. I had this bunch of errors:

`The database has encountered a critical error, and needs to be restarted.`

`Error performing check point`

`Failed to rotate logs. Expected version: ..., actual version: ..., wait timeout (ms): ...`

and

`ERROR Failed to start transaction. The database has encountered a critical error, and needs to be restarted. Please see database logs for more details`

**Comment by oschlueter** [comment]
Is there any information available on potential causes of this behaviour?

**Comment by mvanderkroon** [comment]
We are seeing similar errors on our Read Replicas. I would love to hear any clues on how to debug this particular error.

```
2019-04-11 09:53:36.890+0000 ERROR [o.n.k.i.t.l.c.CheckPointerImpl] Checkpoint failed Failed to rotate logs. Expected version: 881458, actual version: 881392, wait timeout (ms): 600058
org.neo4j.kernel.impl.store.kvstore.RotationTimeoutException: Failed to rotate logs. Expected version: 881458, actual version: 881392, wait timeout (ms): 600058
     at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:78)
     at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:51)
     at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:310)
     at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:287)
     at org.neo4j.kernel.impl.store.counts.CountsTracker.rotate(CountsTracker.java:127)
     at org.neo4j.kernel.impl.store.NeoStores.flush(NeoStores.java:260)
     at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.flushAndForce(RecordStorageEngine.java:468)
     at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:164)
     at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.checkPointIfNeeded(CheckPointerImpl.java:138)
     at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.run(CheckPointScheduler.java:64)
     at org.neo4j.kernel.impl.scheduler.ScheduledJobHandle.lambda$new$0(ScheduledJobHandle.java:83)
     at org.neo4j.kernel.impl.scheduler.ThreadPool.lambda$submit$0(ThreadPool.java:58)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)
```

**Comment by browndp08** [comment]
We're seeing this same error in the community edition of neo4j. It happens every day and requires a restart.

**Comment by AisTop** [comment]
Neo4j version: 3.5.12 
Operating system: Centos 6.6
We are seeing similar errors on our Read Replicas. I would love to hear any clues on how to debug this particular error. thinks !
error info :
ERROR [o.n.k.i.t.l.c.CheckPointerImpl] Error performing check point Failed to rotate logs. Expected version: 25698, actual version: 5, wait timeout (ms): 600001
org.neo4j.kernel.impl.store.kvstore.RotationTimeoutException: Failed to rotate logs. Expected version: 25698, actual version: 5, wait timeout (ms): 600001
	at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:79)
	at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:52)
	at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:309)
	at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:286)
	at org.neo4j.kernel.impl.store.counts.CountsTracker.rotate(CountsTracker.java:127)
	at org.neo4j.kernel.impl.store.NeoStores.flush(NeoStores.java:246)
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.flushAndForce(RecordStorageEngine.java:468)
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:160)
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.checkPointIfNeeded(CheckPointerImpl.java:134)
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.run(CheckPointScheduler.java:64)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)

**Comment by mrbungle733t** [comment]
@AisTop I had a similar issue after database crash (crash was caused as there was not enough space for transaction logs) 
After investigation, i found out that in **graph.db** folder last **neostore.transaction.db** the file is owned by root, not a **neo4j** service account
Also, there was ownership issue with **neo4j.log** and **debug.log**. After fixing file ownership and restarting the server was the issue resolved. 
I believe that in my case after database crash i started neo4j service incorrectly, and somehow file ownership changed from neo4j -> root

**Comment by k2glyph** [comment]
I also faced the same issue. But after @mrbungle733t comment. I check the files and folder permission and the issue was with logs folder was owned by root and right after I changed the folder owner to neo4j and restarted server. It started working fine now.

**Comment by SongJiaQiang0831** [comment]
> Don't delete the transaction logs. Try deleting the `neostore.counts.db.a/.b` files instead. Neo4j will rebuild them if they are missing. If possible, try upgrading to 3.1.6.

I would like to ask, what are the uses of these two files counts.db.a and counts.db.b
