### ISSUE TITLE
Process still running after Database is stopped

### ISSUE THREAD

**Issue by bhalbert** [neo4j/neo4j#9838]
- Neo4j version: 2.3.11
- Operating system: CentOS 6.5

I recently upgraded from 2.3.4 to 2.3.11 and am now having problems. I can start neo4j from the terminal using the start command but when I try to stop it the proccess I get an error:

```
-bash-4.1$ /opt.neo4j.neo4j-community-2.3.11/bin/neo4j stop
Stopping Neo4j Server [7013].....................................................................................................................................
Neo4j Server [7013] is taking more than 120s to stop
There might be some troubles with the shutdown of Neo4j Server, please read log files for details
```

At first both the logs and messages say the database successfully shut down put that process is still running.  After some time I got an exception in the logs.

```

2017-08-16 21:08:39.843+0000 INFO  [o.n.k.i.DiagnosticsManager]   store_lock: 2017-07-25T11:36:36-0400 - 0.00 B

2017-08-16 21:08:39.843+0000 INFO  [o.n.k.i.DiagnosticsManager] --- STARTED diagnostics for KernelDiagnostics:StoreFiles END ---

2017-08-16 21:08:40.941+0000 INFO  [o.n.k.i.DiagnosticsManager] --- SERVER STARTED START ---

2017-08-16 21:08:42.152+0000 INFO  [o.n.k.i.DiagnosticsManager] --- SERVER STARTED END ---

2017-08-17 14:06:40.467+0000 INFO  [o.n.k.i.f.GraphDatabaseFacade] Shutdown started

2017-08-17 14:06:40.468+0000 INFO  [o.n.k.i.f.CommunityFacadeFactory] Database is now unavailable

 

 

 

 

 

 

2017-08-16 17:08:40.937-0400 INFO  Successfully started database

2017-08-16 17:08:40.955-0400 INFO  Starting HTTP on port 7474 (40 threads available)

2017-08-16 17:08:41.081-0400 INFO  Enabling HTTPS on port 7473

2017-08-16 17:08:41.133-0400 INFO  Mounting static content at /webadmin

2017-08-16 17:08:41.166-0400 INFO  Mounting static content at /browser

2017-08-16 17:08:42.152-0400 INFO  Remote interface ready and available at http://localhost:7474/

2017-08-17 10:06:40.440-0400 INFO  Neo4j Server shutdown initiated by request

2017-08-17 10:06:40.466-0400 INFO  Successfully shutdown Neo4j Server

Exception in thread "Thread-27" java.lang.RuntimeException: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@31451d06' failed to stop. Please see attached cause exception.

        at org.neo4j.helpers.RunCarefully.run(RunCarefully.java:57)

        at org.neo4j.server.AbstractNeoServer.stop(AbstractNeoServer.java:505)

        at org.neo4j.server.Bootstrapper$1.run(Bootstrapper.java:181)

Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@31451d06' failed to stop. Please see attached cause exception.

        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:484)

        at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:165)

        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:147)

        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.stop(DataSourceManager.java:132)

        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:476)

        at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:165)

        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:147)

        at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:188)

        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.shutdown(GraphDatabaseFacade.java:285)

        at org.neo4j.server.database.LifecycleManagingDatabase.stop(LifecycleManagingDatabase.java:111)

        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:476)

        at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:165)

        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:147)

        at org.neo4j.server.AbstractNeoServer$6.run(AbstractNeoServer.java:531)

        at org.neo4j.helpers.RunCarefully.run(RunCarefully.java:47)

        ... 2 more

   Suppressed: org.neo4j.kernel.lifecycle.LifecycleException: Failed to transition component 'org.neo4j.kernel.impl.pagecache.PageCacheLifecycle@1c44e9d4' from STOPPED to SHUTTING_DOWN. Please see attached cause exception

                at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:515)

                at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:203)

                ... 9 more

        Caused by: java.lang.IllegalStateException: Cannot close the PageCache while files are still mapped:

        neostore (1 mapping)

        neostore.counts.db.b (1 mapping)

        neostore.relationshipgroupstore.db (1 mapping)

        neostore.schemastore.db (1 mapping)

        neostore.labeltokenstore.db (1 mapping)

        neostore.labeltokenstore.db.names (1 mapping)

        neostore.relationshiptypestore.db (1 mapping)

        neostore.relationshiptypestore.db.names (1 mapping)

        neostore.relationshipstore.db (1 mapping)

        neostore.propertystore.db (1 mapping)

        neostore.propertystore.db.arrays (1 mapping)

        neostore.propertystore.db.strings (1 mapping)

        neostore.propertystore.db.index (1 mapping)

        neostore.propertystore.db.index.keys (1 mapping)

        neostore.nodestore.db (1 mapping)

        neostore.nodestore.db.labels (1 mapping)

                at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.close(MuninnPageCache.java:521)

                at org.neo4j.kernel.impl.pagecache.PageCacheLifecycle.shutdown(PageCacheLifecycle.java:42)

                at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:507)

                ... 10 more

Caused by: org.neo4j.kernel.impl.store.kvstore.RotationTimeoutException: Failed to rotate logs. Expected version: 239481, actual version: 217467, wait timeout (ms): 600016

        at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:74)

        at org.neo4j.kernel.impl.store.kvstore.RotationState$Rotation.rotate(RotationState.java:50)

        at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:292)

        at org.neo4j.kernel.impl.store.kvstore.AbstractKeyValueStore$RotationTask.rotate(AbstractKeyValueStore.java:273)

        at org.neo4j.kernel.impl.store.counts.CountsTracker.rotate(CountsTracker.java:147)

        at org.neo4j.kernel.impl.store.NeoStores.flush(NeoStores.java:409)

        at org.neo4j.kernel.impl.transaction.log.rotation.StoreFlusher.forceEverything(StoreFlusher.java:52)

        at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:1215)

        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:476)

        ... 16 more

~

**Comment by tinwelint** [comment]
The problems seems to be about some issue with the counts store, i.e. `neostore.counts.db.a/b`. What you normally do is to delete those (they will be rebuilt on the next startup) and hopefully that will resolve it.

**Comment by archer247** [comment]
@tinwelint You saved my day buddy! great work out there! 👍

**Comment by MishaDemianenko** [comment]
@bhalbert do you still have this problem or @tinwelint suggestion resolved it? If so can we close the issue?

**Comment by MishaDemianenko** [comment]
@bhalbert closing as solved. Please feel free to reopen in case this is still an issue.

**Comment by yar-malik** [comment]
@tinwelint  this saved me big time. Sending all good Karma your way. Bless up

**Comment by andresest83** [comment]
@tinwelint This is really a great find, thanks to this I was finally able to connect through the Gremlin console using a pre-existing Neo4j database. Thank you sir!
