### ISSUE TITLE
Unable to start neo4j after upgrade

### ISSUE THREAD

**Issue by foobargeez** [neo4j/neo4j#9913]
- Neo4j version: 3.2.3
- Operating system: CentOS

I upgraded neo4j version to v3.2.3 from v3.1.0 and started neo4j after setting `dbms.allow_format_migration=true` leaving the rest of the settings in tact.

I am getting the following stacktrace in the logs:

```2017-08-26 03:01:00.688+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7e334734' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7e334734' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7e334734' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:227)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:68)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7e334734' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:199)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /data/dbstore02/neo4j.3.2.3/databases/podb
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:193)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:124)
        at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:57)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@6e420c5c' failed to initialize. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:415)
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:189)
        ... 9 more
Caused by: java.lang.NoSuchMethodError: org.neo4j.kernel.impl.api.scan.LabelScanStoreProvider.<init>(Ljava/lang/String;Lorg/neo4j/kernel/api/labelscan/LabelScanStore;)V
        at org.neo4j.kernel.impl.api.scan.NativeLabelScanStoreExtension.newInstance(NativeLabelScanStoreExtension.java:73)
        at org.neo4j.kernel.impl.api.scan.NativeLabelScanStoreExtension.newInstance(NativeLabelScanStoreExtension.java:38)
        at org.neo4j.kernel.extension.KernelExtensions.init(KernelExtensions.java:69)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:405)
        ... 12 more
```

Appreciate any pointers!

**Comment by jexp** [comment]
Are you using Neo4j as a server or embedded?

If the latter, your dependency management seems to be flawed as it misses some of the new dependencies.
It's enough to depend on `org.neo4j:neo4j:3.2.3`

**Comment by foobargeez** [comment]
> Are you using Neo4j as a server or embedded?

Server.

Rolling back to the earlier version v3.1.0 works just fine with existing config settings, so I am confused.

**Comment by foobargeez** [comment]
Ah, got this resolved.  The issue is that I installed neo4j earlier by hand and I now "upgraded" using "yum install", which placed newer jars alongside the old ones under lib directory.  I now cleaned all the earlier ones and neo4j started just fine.  Grr ...
