### ISSUE TITLE
neo4j run error when use java -jar

### ISSUE THREAD

**Issue by hsh8523** [neo4j/neo4j#9915]
java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /Users/shaohuahe/neo4jDB
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:209)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:124)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:140)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(GraphDatabaseFactory.java:133)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:108)
	at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:193)
	at org.neo4j.tinkerpop.api.impl.Neo4jFactoryImpl.newGraphDatabase(Neo4jFactoryImpl.java:46)
	at org.neo4j.tinkerpop.api.Neo4jFactory$Builder.open(Neo4jFactory.java:32)
	at org.apache.tinkerpop.gremlin.neo4j.structure.Neo4jGraph.<init>(Neo4jGraph.java:130)
	at org.apache.tinkerpop.gremlin.neo4j.structure.Neo4jGraph.open(Neo4jGraph.java:144)
	at io.openmg.metagraph.benchmark.impl.GraphTraversalBenchmark.prepare(GraphTraversalBenchmark.java:52)
	at io.openmg.metagraph.benchmark.impl.generated.GraphTraversalBenchmark_g_V_label_groupCount_jmhTest.g_V_label_groupCount_sample_jmhStub(GraphTraversalBenchmark_g_V_label_groupCount_jmhTest.java:246)
	at io.openmg.metagraph.benchmark.impl.generated.GraphTraversalBenchmark_g_V_label_groupCount_jmhTest.g_V_label_groupCount_SampleTime(GraphTraversalBenchmark_g_V_label_groupCount_jmhTest.java:209)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:430)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:412)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@45025f48' was successfully initialized, but failed to start. Please see the attached cause exception "Configured label index 'NATIVE', but couldn't find it among candidates [LUCENE]".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:100)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:205)
	... 22 more
Caused by: java.lang.IllegalArgumentException: Configured label index 'NATIVE', but couldn't find it among candidates [LUCENE]
	at org.neo4j.kernel.extension.dependency.NamedLabelScanStoreSelectionStrategy.select(NamedLabelScanStoreSelectionStrategy.java:93)
	at org.neo4j.kernel.impl.util.Dependencies.resolveDependency(Dependencies.java:58)
	at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:410)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	... 27 more

**Comment by jexp** [comment]
You should more detail why and when you run Neo4j this way.

Neo4j is usually either started as a server or run embedded in an application.

It seems that your setup is missing Neo4j dependencies. The only `java -jar` that works for Neo4j is for Neo4j-Desktop, b/c that bundles all dependencies into ONE jar.

**Comment by chrisvest** [comment]
Use the scripts and shortcuts that come with the Neo4j distribution, for starting the database. If you are already doing that, then please include the Neo4j version tried in the bug report, plus exact steps with copy-pastable command lines (if applicable) for reproducing the problem.
