### ISSUE TITLE
neo4j with java query giving org.neo4j.helpers.ThisShouldNotHappenError

### ISSUE THREAD

**Issue by prachikhartadkar** [neo4j/neo4j#997]
try{
String query3="START p3=node:aProduct('productId:*')  "+"\n"+ 
"WHERE p3.dvsn_nbr IN  [20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,4,3,2,1]"+
" WITH p3 "+"\n"+
"MATCH p3<-[r:HAS_BOUGHT]-t  "+"\n"+
"RETURN p3.dvsn_nbr as p3, count(distinct t) as supp2  "+"\n"+
"ORDER BY p3.dvsn_nbr DESC";
System.out.println(query3);
ExecutionResult rs3 = engine.execute(query3);

System.out.println("check2");
}catch(Exception e){
        db.shutdown();
}

----------------------------------------error---
ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/MarketBasketAnalysis].[ProductServ]](http-localhost-127.0.0.1-8080-1) Servlet.service() for servlet ProductServ threw exception: org.neo4j.helpers.ThisShouldNotHappenError: Developer: Andres claims that: Need something with properties
    at org.neo4j.cypher.internal.commands.expressions.Property.apply(Property.scala:32) [neo4j-cypher-1.9.2.jar:1.9.2]
    at org.neo4j.cypher.internal.pipes.ExtractPipe$$anonfun$internalCreateResults$1$$anonfun$apply$1.apply(ExtractPipe.scala:47) [neo4j-cypher-1.9.2.jar:1.9.2]
    at org.neo4j.cypher.internal.pipes.ExtractPipe$$anonfun$internalCreateResults$1$$anonfun$apply$1.apply(ExtractPipe.scala:45) [neo4j-cypher-1.9.2.jar:1.9.2]
    at scala.collection.immutable.Map$Map1.foreach(Map.scala:109) [scala-library-2.10.0.jar:]
    at org.neo4j.cypher.internal.pipes.ExtractPipe$$anonfun$internalCreateResults$1.apply(ExtractPipe.scala:45) [neo4j-cypher-1.9.2.jar:1.9.2]
    at org.neo4j.cypher.internal.pipes.ExtractPipe$$anonfun$internalCreateResults$1.apply(ExtractPipe.scala:44) [neo4j-cypher-1.9.2.jar:1.9.2]
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328) [scala-library-2.10.0.jar:]
    at scala.collection.Iterator$class.foreach(Iterator.scala:727) [scala-library-2.10.0.jar:]
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1156) [scala-library-2.10.0.jar:]
    at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48) [scala-library-2.10.0.jar:]
    at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:178) [scala-library-2.10.0.jar:]
    at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45) [scala-library-2.10.0.jar:]
    at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:259) [scala-library-2.10.0.jar:]
    at scala.collection.AbstractIterator.to(Iterator.scala:1156) [scala-library-2.10.0.jar:]
    at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:243) [scala-library-2.10.0.jar:]
    at scala.collection.AbstractIterator.toList(Iterator.scala:1156) [scala-library-2.10.0.jar:]
    at org.neo4j.cypher.internal.pipes.SortPipe.internalCreateResults(SortPipe.scala:33) [neo4j-cypher-1.9.2.jar:1.9.2]
    at org.neo4j.cypher.internal.pipes.PipeWithSource.createResults(Pipe.scala:69) [neo4j-cypher-1.9.2.jar:1.9.2]
    at org.neo4j.cypher.internal.pipes.PipeWithSource.createResults(Pipe.scala:66) [neo4j-cypher-1.9.2.jar:1.9.2]
    at org.neo4j.cypher.internal.executionplan.ExecutionPlanImpl.org$neo4j$cypher$internal$executionplan$ExecutionPlanImpl$$prepareStateAndResult(ExecutionPlanImpl.scala:164) [neo4j-cypher-1.9.2.jar:1.9.2]
    at org.neo4j.cypher.internal.executionplan.ExecutionPlanImpl$$anonfun$getLazyReadonlyQuery$1.apply(ExecutionPlanImpl.scala:139) [neo4j-cypher-1.9.2.jar:1.9.2]
    at org.neo4j.cypher.internal.executionplan.ExecutionPlanImpl$$anonfun$getLazyReadonlyQuery$1.apply(ExecutionPlanImpl.scala:138) [neo4j-cypher-1.9.2.jar:1.9.2]
    at org.neo4j.cypher.internal.executionplan.ExecutionPlanImpl.execute(ExecutionPlanImpl.scala:38) [neo4j-cypher-1.9.2.jar:1.9.2]
    at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:72) [neo4j-cypher-1.9.2.jar:1.9.2]
    at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:67) [neo4j-cypher-1.9.2.jar:1.9.2]
    at org.neo4j.cypher.javacompat.ExecutionEngine.execute(ExecutionEngine.java:66) [neo4j-cypher-1.9.2.jar:1.9.2]
    at com.mba.dao.hibernate.DataDAOImpl.getProdAssoc(DataDAOImpl.java:44) [classes:]
    at com.mba.service.DataServiceImpl.getProdAssoc(DataServiceImpl.java:19) [classes:]
    at com.mba.servelet.ProductServ.handleRequest(ProductServ.java:29) [classes:]
    at org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:67) [org.springframework.web_3.1.1.RELEASE.jar:3.1.1.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161) [jbossweb-7.0.13.Final.jar:]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671) [jbossweb-7.0.13.Final.jar:]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930) [jbossweb-7.0.13.Final.jar:]
    at java.lang.Thread.run(Thread.java:722) [rt.jar:1.7.0_09]

---

Hi is my query.I am using neo4j-community-1.9.2 version.I am tryin to implement on a java platform.I have all the necessary jar files.All my other cypher queries are getting executed without any issues ,apart from this one

**Comment by sherfert** [comment]
First of all sorry for responding so late. Thanks for the report, this problem should have been fixed in more recent versions of neo4j.
